### ISSUE TITLE
oldWebmin theme not allowing view to expand (javascript opernerobj.innerHTML issue)

### ISSUE THREAD

**Issue by victimsofgaybullying** [virtualmin/virtualmin-gpl#10]
On Modern Firefox and Chrome browsers the old classic webmin theme isn't usable, hidden values can not be expanded.

Some people would still like to use this simplistic theme so they can run webmin without miniserv cgi-bin style as themes aren't supported in that mode. I'll attempt to get webmin working with fastcgiwrap with nginx and document my success / failure later, and if all else fails use a proxy to miniserv.

I'd look at the javascript in sub ui_hidden_javascript in ui-lib.pl

This is more of a webmin issue than a virtualmin issue.

**Comment by swelljoe** [comment]
There's a Webmin github, too! http://github.com/webmin/webmin

Which Webmin theme specifically (there's several old ones!)? I revert back to the gray theme (pretty much the same as Virtualmin Framed Theme) now and then and haven't seen this behavior...but, maybe there's a new issue.

**Comment by jcameron** [comment]
This is a known Webmin bug that happens only with some themes - the next release will fix it.

**Comment by victimsofgaybullying** [comment]
"Old Webmin Theme" is what webmin calls it. I called it old/classic theme off the top of my head.

I remember seeing exactly the same javascript in sub ui_hidden_javascript in ui-lib.pl in my chrome/firefox view source when it was messing up.
Surely it shouldn't be too hard to replicate it.

Is it still true that themes (apart from classic) isn't supported if you try and replace miniserv.pl with cgi-bin like fastcgiwarp or apache cgi?

**Comment by jcameron** [comment]
If you install the 1.851 development version from http://www.webmin.com/devel.html , it should fix this.

**Comment by victimsofgaybullying** [comment]
Great do you know of any sites that are in this day and age using cgi-bin, or do you strongly reconmend mod proxy. The reason being is nginx has web application firewall features, that could run through a proxy, but also cgi-bin, the other reason is systemd is being spammed by virutalmin/webmin logs, or is it my pam setup (default gentoo / sabayon)

Something is up with pam + systemd + webmin but I haven't investigated it yet. I will shortly. That was my underlying motive for interest in the "Classic theme" still working, as it's the only way to run webmin without miniserv.pl. Miniserv.pl as runs minicron right? 

Those crons can run seperately or from a real crontab?


```
Jul 15 03:29:40 mail perl[31651]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:40 mail perl[31648]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:40 mail perl[31648]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:40 mail perl[31651]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:40 mail perl[31649]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:40 mail perl[31649]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:40 mail perl[31503]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:40 mail perl[31503]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:40 mail perl[31650]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:40 mail perl[31650]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:40 mail perl[31502]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:40 mail perl[31502]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:40 mail perl[31648]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:40 mail perl[31503]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:40 mail perl[31648]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:40 mail perl[31503]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:40 mail perl[31649]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:40 mail perl[31649]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:40 mail perl[31651]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:40 mail perl[31651]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:41 mail perl[31650]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:41 mail perl[31650]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:41 mail perl[31502]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:41 mail perl[31502]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:41 mail perl[31648]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:41 mail perl[31648]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:41 mail perl[31649]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:41 mail perl[31649]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:41 mail systemd-logind[1086]: Removed session c1491.
-- Subject: Session c1491 has been terminated
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID c1491 has been terminated.
Jul 15 03:29:41 mail perl[31649]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:41 mail perl[31649]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:41 mail perl[31651]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:41 mail perl[31651]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:41 mail perl[31648]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:41 mail perl[31648]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:41 mail perl[31503]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:41 mail perl[31503]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:41 mail perl[31502]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:41 mail perl[31502]: pam_systemd(webmin:session): Cannot create session: Already running in a session
Jul 15 03:29:42 mail perl[31697]: pam_unix(webmin:session): session opened for user root by (uid=0)
Jul 15 03:29:42 mail systemd[1]: Started Session c1494 of user root.
-- Subject: Unit session-c1494.scope has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit session-c1494.scope has finished starting up.
-- 
-- The start-up result is done.
Jul 15 03:29:42 mail systemd-logind[1086]: New session c1494 of user root.
-- Subject: A new session c1494 has been created for user root
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A new session with the ID c1494 has been created for the user root.
-- 
-- The leading process of the session is 31697.
Jul 15 03:34:44 mail systemd-logind[1086]: Removed session c1494.
-- Subject: Session c1494 has been terminated
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID c1494 has been terminated.
Jul 15 03:34:44 mail systemd-logind[1086]: Removed session c1486.
-- Subject: Session c1486 has been terminated
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID c1486 has been terminated.
Jul 15 03:34:44 mail systemd-logind[1086]: Removed session c1492.
-- Subject: Session c1492 has been terminated
```

**Comment by victimsofgaybullying** [comment]
P.s. Jamie this was me years ago, I'm getting into postfix, finally bit the bullet on my own gentoo custom patchset, but I can make my old qmail dietlibc execute in place ([xip - now DAX](http://lwn.net/Articles/610174/)) high concurrency patchset work with ldap, or do the same tweaks to indymail people will definately still want you NOT TO REMOVE the qmail / qmail-ldap support. Whole telco's run on that platform. I think that bug still exists with vpopmail, at least now we have github and i can do more pull requests if I every try out tweaking indymail (and keep postfix as my backup MTA).
https://www.virtualmin.com/node/22970
https://www.virtualmin.com/node/22952

In the beginning wasn't webmin partnered with Caldera linux?? I haven't read the Linux journal for a decade :)

**Comment by victimsofgaybullying** [comment]
Re the devel version, can I use the github version of virtualmin and just symlink the modules I'm using. I'm currently using my own gentoo ebuilds to install an uptodate webmin-minimal and just update the non-core modules. Where are the devel wbm.gz files? Do you roll them out too?

**Comment by swelljoe** [comment]
Tarballs are here: http://download.webmin.com/devel/tarballs/

**Comment by swelljoe** [comment]
On the qmail-ldap issue, if there's whole telcos running on it, get them in touch with me. We'll work out a support agreement where we keep that stuff working for them (it won't be cheap in individual terms, but it will be perfectly reasonable for a telco).

Otherwise, the upstream has been unmaintained for years. There are no new deployments of qmail-ldap. If old software is OK (as it must be for someone to still be using qmail-ldap), then folks can keep using old versions of Virtualmin that support qmail-ldap.

**Comment by victimsofgaybullying** [comment]
http://www.indimail.org talk to them, they are in the business of supporting it for whole telcos. I made my own patchset to qmail too for the citizens ombudsman project (dark net research stuff I started after finding where every government leader lives http://tinyurl.com/strathfield and set up a CRM to track leftist troll accounts by their real identities offline). It's on my todo list when I've got time for performance tuning, to try and get my dietlibc / DAX patches to qmail working with indimail that is more scalable, as my old version didn't have ldap support. Nothing plays nice with those qmail-ldap patches.

Postfix is great I'm trying to use it to its max ability, but qmail is very scalable. It's kind of like lighttpd, extremely small and extremely fast. Qmail's excessive process spawning can be offset by how small the binaries are and execute in place and everything can be written in C, from ipv6 support, to SRS, DKIM, SPF, SSL etc. I think we all know C trumps perl modules as far as performance.

Then of course Qmail is wrote by Dan Bertstien god of cr.yp.to. Can you remember him flaming the creator of sendmail using language much worse than even I have ever used. That creates a loyal following. I saw some diffs that someone was just trying to remove qmail support. Am I right?

**Comment by swelljoe** [comment]
No, we are not removing qmail support in Webmin or Virtualmin. No one  has ever said that we are.

We are removing qmail-ldap support from Virtualmin. They are different things. qmail-ldap has been unmaintained for about a decade as far as I can tell. qmail, at least, has people patching it now and then.

If someone wants to keep qmail-ldap in Virtualmin, they'll need to do it themselves in their own patched version (anyone using qmail loves patching software anyway, so should be fine) or pay for a long-term support contract from us to make it happen for some special case. It's going away in Virtualmin. We cannot make running unmaintained third party software safe, so we can't keep supporting it.
