### ISSUE TITLE
Enabling SSL with wildcard Let's Encrypt certificate fails

### ISSUE THREAD

**Issue by unguul** [virtualmin/virtualmin-gpl#101]
Enabling SSL with a wildcard Let's Encrypt certificate fails due to invalid certificate. The same certificate has been used with other vhosts without issues.

This is on Debian 9, Webmin 1.930, Usermin 1.780 with Virtualmin 6.07.

**Comment by jcameron** [comment]
What's the error message you're getting exactly?

**Comment by unguul** [comment]
@jcameron The error message is the same as per #102 . 

```bash
Adding new SSL virtual website ..
.. certificate file is not valid : Line 31 does not look like PEM format
```

The SSL certificate is created manually, using certbot and then copied over to the vhost home directory. I might try to recreate this on a fresh VM. Maybe there's something peculiar with this host.

**Comment by jcameron** [comment]
What is on line 31 of the file `etc/ssl.cert` under the domain's home directory?

**Comment by unguul** [comment]
@jcameron There's no `~/etc/ssl.cert` file. I simply copy the `fullchain.pem` generated by `certbot` to `~/cert.pem` and the `privkey.pem` to `~/privkey.pem`.

Line 31 of `fullchain.pem` contains `-----END CERTIFICATE-----`.

Is this how I find out I'm doing it the wrong way? :smile: 

Thank you for the help btw. Much appreciated!

**Comment by jcameron** [comment]
Are there any extra spaces before or after the dashes?

**Comment by unguul** [comment]
@jcameron None. I've also tried this on a fresh installation of Virtualmin and I've had no issues so this is likely something particular to my setup. Until I find out what that is I'll close this and #102 so I don't waste your time.

I'll reopen once I find out how to reproduce the issue(s).
