### ISSUE TITLE
SSL website creation fails

### ISSUE THREAD

**Issue by unguul** [virtualmin/virtualmin-gpl#102]
Creating a new vhost with SSL enabled creates the vhost but the SSL side is not actually enabled. Attempting to enable it post creation fails with 

```bash
Adding new SSL virtual website ..
.. certificate file is not valid : Line 31 does not look like PEM format
```
This applies to both the CLI and the web GUI.

This is potentially linked to #101, but this is a fresh vhost creation so there's no let's encrypt certificate.

This is on Debian 9, Webmin 1.930, Usermin 1.780 with Virtualmin 6.07.

**Comment by jcameron** [comment]
That's unusual, since the PEM format certificate should be generated by Virtualmin itself.

Do you have Virtualmin configured to request a new Let's Encrypt certificate for new domains?

**Comment by unguul** [comment]
> Do you have Virtualmin configured to request a new Let's Encrypt certificate for new domains?

@jcameron No. Virtualmin is configured to create self-signed certificates.

**Comment by unguul** [comment]
Closing until (and if) this can be reproduced on a fresh installation of Virtualmin.
