### ISSUE TITLE
Cpanel Backup Migrate MariaDB 10.4 user password

### ISSUE THREAD

**Issue by qlpqlp** [virtualmin/virtualmin-gpl#106]
Hello to all,

We are using CentOS 7 and latest webmin + Virtualmin with MariaDb 10.4 with the lastest patch to fix de recent issues user creation and edit.

Wen we migrate a cpanel backup to Virtualmin, the user password for the database is not set correctly and we have to manually edit the mariadb user password to work with the client php script.

I think the problem is that the password is encrypted on cpanel back and wen Virtualmin imports it set as plaintext.

Is there any quick fix for this?

Thanks in advance.

**Comment by jcameron** [comment]
Did you get any error message while migrating, or is the password just not set correctly?

**Comment by qlpqlp** [comment]
Hello jcameron :)

No, no erros, all is imported correctly, only the password is set rong. I have to go to Virtualmin->Edit Users->(select the database user)->)Password->(and add manually the script password) to the database conection work.

**Comment by qlpqlp** [comment]
Just to add extra notes to this. I have downgraded from MariaDb 10.4 TO MariaDb 10.1and now migrating from cPanel the password is added correcrly so it only afects MariaDb 10.2, 10.3 and 10.4

**Comment by iliarostovtsev** [comment]
Support for MariaDB 10.4+ and MySQL 8+ has been implemented in Webmin 1.960 and Virtualmin 6.13. Let us know if it works for you.
