### ISSUE TITLE
TLSA: --enable-tlsa fails with "undefined value"

### ISSUE THREAD

**Issue by iam-TJ** [virtualmin/virtualmin-gpl#108]
As reported in the forums by another operator at https://www.virtualmin.com/node/67210

The SOA serial isn't updated when enabling/modifying TLSA records which is a problem when you've got 6 slave servers on the public facing side.

When using:
```
# virtualmin modify-dns --domain <domain.tld> --enable-tlsa
Updating server <domain.tld> ..
    Creating TLSA records ..
    .. done

Can't use an undefined value as an ARRAY reference at /usr/share/webmin/bind8/records-lib.pl line 439.
```
This indicates the call chain from:
```
modify-dns.pl ->
  feature-dns.pl::post_records_change($d, $recs, $file) 
    records-lib.pl::bump_soa_record($fn, $recs)
```
fails because in `modify-dns.pl $recs` is empty when handling the TLSA case:
```
if (defined($tlsa))
```
All the preceding `if()` clauses set `$recs` - it looks like what is missing is something similar to:
```
                # Records may have changed, so re-read
                ($recs, $file) = &get_domain_dns_records_and_file($d); 
```

**Comment by jcameron** [comment]
Thanks - this will be fixed in the next release.
