### ISSUE TITLE
Virtualmin 6: List Users opened in new tab

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#11]
Hi,

It's apparently not needed to pass `new` value for _target_ attribute in navigation menu for List Users link:

`/virtual-server/list_users.cgi`

It happens in all themes.

**Comment by jcameron** [comment]
In the Virtualmin Framed Theme, the target of that link is just "right" which indicates that it opens in the existing right frame ... at least on all my test systems.

**Comment by qooob** [comment]
Have a look at the [videoscreencast](https://rostovtsev.ru/pub/src/authentic/list_users_new_tab.webm) please.

**Comment by shoulders** [comment]
this should be closed because 
- virtaulmin 6
- there is no bug.
> In the Virtualmin Framed Theme, the target of that link is just "right" which indicates that it opens in the existing right frame ... at least on all my test systems.

**Comment by jcameron** [comment]
@iliajie can we close this then?

**Comment by iliajie** [comment]
Yeah! Thanks for pointing this out!
