### ISSUE TITLE
Wrong php_fpm_version var prevents FPM mode in vhosts

### ISSUE THREAD

**Issue by ftrojahn** [virtualmin/virtualmin-gpl#112]
Problem: after upgrading from Debian 9 to 10 Buster, no vhost could be switched from FCGId to FPM mode using neither gui nor cmd line.

- `virtualmin check-config` shows, that both fcgi and php-fpm 7.3 are available. 
- In `Server Templates ->  PHP options` all modes are available for default selection: Apache mod_php, CGI wrapper, FCGId and FPM.
- but in each domains `Server configuration -> Website Options` only CGI wrapper and FCGId are available.

Solution: if php-fpm mode had been used before the upgrade, the var `php_fpm_version=7.0` has to be changed to `php_fpm_version=7.3` in the domains/nnn file:

```
sed -i 's/php_fpm_version=7\.0/php_fpm_version=7.3/' /etc/webmin/virtual-server/domains/*
```
check-config and validate-domain did not find this. After that change, all vhosts could be switched back to fpm.

**Comment by MattWilcox** [comment]
I've just done a fresh install of VirtualMin (6.08) on a fresh Ubuntu 18.04; and after running the post-installation config check guess what I see...

The following PHP versions are available : 7.2.19 (/usr/bin/php-cgi7.2), 7.2 (mod_php)
The following PHP-FPM versions are available on this system : 7.2.3 (php7.2-fpm)
PHP versions have changed to 7.2, 7.2 since last check. Regenerating any missing php.ini files

This isn't right, is it?

**Comment by jcameron** [comment]
Yes, this is a known problem - if `php_fpm_version` no longer matches an installed version, it can cause other breakage.

**Comment by jcameron** [comment]
This will be fixed in the next Virtualmin release.

**Comment by whereisaaron** [comment]
@jcameron thanks for this fix. It looks like this and a lot of other important FPM fixed are in 6.09 released in Feb. But on Ubuntu the latest version is still 6.08. Will 6.09 arrive on Ubuntu soon or do we need to use a different package repo to get it?

**Comment by iliarostovtsev** [comment]
What do you have on the _source.list_ in `/etc/apt`?

**Comment by whereisaaron** [comment]
Hi @iliarostovtsev, are you able to update to 6.09 on Ubuntu? I have sources as follows.
```
$ cat /etc/apt/sources.list | grep ^deb
deb http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu/ bionic main restricted
deb http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
deb http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu/ bionic universe
deb http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu/ bionic-updates universe
deb http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
deb http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu bionic-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
deb http://software.virtualmin.com/vm/6/gpl/apt virtualmin-bionic main
deb http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal main
```
