### ISSUE TITLE
DANE TLSA DNS records fail validation

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#115]
The Bug: 
Virtualmin's DANE TLSA DNS records fail to keep up with LetsEncrypt TLS certificate renewals/modifications (modifications such as expanding the cert to add more hostnames), and therefore Virtualmin hosted servers fail DANE TLSA validation.  Note, this server where this was tested has a system cronjob renewing the LetsEncrypt certs.  Failure is verifed with a command line tool installed from Linux distro's package manager.

Security consequences:
All DANE-TLSA-enforcing remote servers (and user client apps such as mail and web) can and will refuse to exchange email, web, webmin/virtualmin/usermin/cloudmin, and indeed all TLSA-IP-port-secured traffic, with our Virtualmin server, because our Virtualmin server's invalid DANE TLSA records make it appear to be an imposter server/phishing server run by cybercriminals.

Priority: 
High priority bug and should be fixed ASAP. 

A possible solution:
At least, a fix should provide a command line to generate and add the new TLSA records according to a scheme that takes into account remote caching DNS servers and the TTL of the old expiring TLSA records.  How and why to do it this way? See following 3 pages:
1. https://www.internetsociety.org/blog/2016/01/lets-encrypt-certificates-for-mail-servers-and-dane-part-1-of-2/
2. https://www.internetsociety.org/blog/2016/03/lets-encrypt-certificates-for-mail-servers-and-dane-part-2-of-2/
3. https://www.internetsociety.org/blog/2017/12/monitoring-your-dane-deployment/

How to Check your Virtualmin server's DANE TLSA records from the command line:
```
apt install ldnsutils

ldns-dane verify mail.myvirtualmin.com 25
Warning! No TLSA records for _25._tcp.mail.myvirtualmin.com. were found.
PKIX validation without DANE will be performed.
handshaking SSL_get_error: 1
error: could not get cert chain from ssl
140052808631952:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:797:

ldns-dane verify mail.myvirtualmin.com 993
x.x.x.x did not dane-validate, because: The TLSA record(s) did not match with the server certificate (chain)
a:b:c:d::e did not dane-validate, because: The TLSA record(s) did not match with the server certificate (chain)

ldns-dane verify www.myvirtualmin.com 443
Warning! No TLSA records for _443._tcp.www.myvirtualmin.com. were found.
PKIX validation without DANE will be performed.
x.x.x.x did not dane-validate, because: Could not PKIX validate

ldns-dane verify server1.myvirtualmin.com 10000
x.x.x.x did not dane-validate, because: The TLSA record(s) did not match with the server certificate (chain)
a:b:c:d::e did not dane-validate, because: The TLSA record(s) did not match with the server certificate (chain)

ldns-dane verify server1.myvirtualmin.com 20000
x.x.x.x did not dane-validate, because: The TLSA record(s) did not match with the server certificate (chain)
a:b:c:d::e did not dane-validate, because: The TLSA record(s) did not match with the server certificate (chain)
```

**Comment by jcameron** [comment]
That's odd, because the TLSA records should be re-generated by Virtualmin after all cert updates (as long as they are done within Virtualmin).

**Comment by chris001** [comment]
> That's odd, because the TLSA records should be re-generated by Virtualmin after all cert updates (as long as they are done within Virtualmin).

It's probably failing to update TLSA DNS records because this particular server's Virtualmin refuses to touch LetsEncrypt renewals, because LetsEncrypt certbot had previously run on the server to manually generate the TLS certs, before the LetsEncrypt feature was added to Virtualmin.

To fix this bug, an external script needs to be able to run a command line, to trigger Virtualmin to re-generate all of a zone's TLSA DNS records, in a way that respects the TTLs of the zone's existing cached TLSA records out on the internet.  See the first 2 articles cited above for full details and reasoning.

The general method of securely regenerating the TLSA records is, at one TTL of time before the old TLSA DNS records expire, you generate and add the new TLSA records to the zone, then wait until the TTL expires on the old TLSA records, then remove the old TLSA records from the zone.

**Comment by chris001** [comment]
Note: Up to date TLSA records are essential to prevent mass surveillance by means of the well known Man-In-The-Middle `**STRIPTLS**` attack, carried out by Thailand government ISP, and Cricket Wireless ISP (USA). (1)
1. Source: https://en.wikipedia.org/wiki/Opportunistic_TLS

Here's a simple script to (re)generate our DANE TLSA DNS resource records.
This script doesn't insert the records into your DNS zone, that's left as an exercise for the reader. ;)  Hint: `rndc`
```
#!/usr/bin/env bash
if [[ $# -ne 1 ]]; then
  echo "You must pass the domain name to create its DANE-TLSA DNS records from the actual cert served on the well-known secure smtp, pop, imap, web, ldap, webmin, and usermin  ports."
  exit 1
fi
ldns-dane create mail."$1" 465  #smtps
ldns-dane create mail."$1" 993  #imaps
ldns-dane create mail."$1" 995    #pop3s
ldns-dane create www."$1" 443  #https
ldns-dane create "$1" 443    #https
ldns-dane create "$1" 636  #ldaps
ldns-dane create "$1" 990  #ftps
#ldns-dane create "$1" 563  #nntps. Not very common.
ldns-dane create admin."$1" 10001   #webmin/virtualmin
ldns-dane create webmail."$1" 20001  #usermin
```

**Comment by chris001** [comment]
An easy to use `DANE` security validator tool,  you just enter your virtualmin domain, select `SMTP` and enter port 25, or select `IMAP` and enter port 143, and it will use `STARTTLS` (aka opportunistic `TLS`) to test your virtualmin server's `DANE TLSA` records for validity:
https://www.huque.com/bin/danecheck

**Comment by jcameron** [comment]
Ah, so what you really need is a Virtualmin API command to re-sync the TLSA records. I'll add that..

**Comment by unsalkorkmaz** [comment]
**Website matches all sub-domains** option adds * wildcard dns record.. but if this is not in the last row of dns records, TSLA gives error. IF you disable and enable **Website matches all sub-domains** option, it moves it to the bottom and TSLA errors goes away

**Comment by jcameron** [comment]
@unsalkorkmaz do you mean that the order of TLSA DNS records matters?

**Comment by unsalkorkmaz** [comment]
> @unsalkorkmaz do you mean that the order of TLSA DNS records matters?

it seems so

**Comment by unsalkorkmaz** [comment]
@jcameron I dont know if same problem with above but let me explain from start about what I found:

I opened **Website matches all sub-domains** option from Website options which adds * wildcard dns record. This is necessary for wildcard SSL. But I saw problems from [Let's Encrypt](https://letsencrypt.org/) when requesting wildcard SSL or DNSSEC reports like this:
![Screenshot 2022-07-21 140818](https://user-images.githubusercontent.com/207720/180199841-7eaad7b6-6075-4e81-96f8-ce3911d92dbb.png)

And solution was moving * wildcard dns to bottom with disabling and enabling **Website matches all sub-domains**.

**Comment by jcameron** [comment]
I had a closer look at this, and it seems like the real issue is that there is no TLSA record for `mail.domain.com` even though it's used for SMTP. We'll fix this in the next release of Virtualmin ..
