### ISSUE TITLE
REQUEST: notification/repair A record without AAAA record.

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#118]
With accessibility of all web services thru both IPv4 and IPv6 now required, it'd be a great help to add a feature to Virtualmin, which notifies the server admin and/or system admin, when any hostname(s) in the server's zone(s), has a DNS `A` (ipv4 address) record without a corresponding `AAAA` (ipv6 address) record for the hostname.  A button would instantly create the missing `AAAA` record, assign the zone's default IPv6 address to it, and insert it into the zone.  The goal would to make it easy and fast for the Virtualmin admin, or virtual server admin, to correct this defect, inaccessibility over IPV6, in the domains/zones under their responsibility. So they don't have to go in by hand and manually inspect each zone which is usually huge, look at each `A` record and try to find out whether or not there's a matching `AAAA` record, and then create that `AAAA` record without screwing up the zone file, repeat this hundreds or thousands of times depending on how many hosts are listed in the entire `bind9 DNS` server running on Virtualmin. 😫

**Comment by jcameron** [comment]
I'm not sure if such a check makes sense by default as part if the regular validation process in Virtualmin, as on some systems the admin may not want to have an AAAA address for every A. However, we can at least expand the validation of common records like `www.domain.com` and `domain.com` to ensure they have an AAAA address matching the domain's, if IPv6 is enabled.

**Comment by chris001** [comment]
Certainly, all common, default, web services, if they have an IPv4 address `A` record in DNS, should throw a firm warning to the virtual server admin (and virtualmin system admin), that they need an IPv6 `AAAA` record in DNS in order to become accessible to users with IPv6.  This is the list of common DNS records, the same web service hostnames that `DANE TLSA` is also concerned about: HTTP, IMAP/SMTP/POP3, LDAP, FTP, SSH, webmin, and usermin,
```
example.com
www.example.com
ftp.example.com
mail.example.com
imap.example.com
pop3.example.com
ldap.example.com
ssh.example.com
admin.example.com  (webmin)
webmail.example.com (usermin)
```

**Comment by abclution** [comment]
Rolling out IPV6 as well and having to generate missing entries for previously IPv4 domains is quite troublesome.

**Comment by jcameron** [comment]
I suppose if there is an A record pointing to the Virtualmin system, the AAAA record should exist and point to it as well.

**Comment by chris001** [comment]
Yes, it'd be a good feature to add, save a lot of time vs. manually editing each virtual server DNS records thru the GUI, if Virtualmin would ask you: "Create AAAA (ipv6) record for every A (ipv4) record pointing to the virtual server? yes/no".

**Comment by jcameron** [comment]
Note that by default, for new domains with IPv6 enabled, this should already happen.

**Comment by chris001** [comment]
> Note that by default, for new domains with IPv6 enabled, this should already happen.

Understood.  This feature would be for rolling out IPv6 `AAAA` DNS records to pre-existing domains (virtual servers) that were previously created as IPv4 only, most likely a long time ago, or on a server before it got an allocation of IPv6 addresses.

**Comment by abclution** [comment]
> Note that by default, for new domains with IPv6 enabled, this should already happen.

Where can I check to see why this is not happening?

On an up to date, but system that has been upgraded through the years, I have some new domains that are newly added and enabled for IPV6, but none of the DNS AAAA records are being created for them automatically, EXCEPT for autoconfig. and autodiscover. 

Been through the settings a few times and cannot figure out what I am missing.
I have added them manually to "BIND DNS records for new domains" but according to what you said, they should already appear?

**Comment by jcameron** [comment]
@abclution are you seeing this even for domains that have an IPv6 address at creation time?

**Comment by abclution** [comment]
@jcameron If you mean by have, assigning them either the shared one, or one from a range at creation time, yes.

**Comment by jcameron** [comment]
Does this happen if a domain is using a shared IPv6 address, it's own private v6 address, or both?

**Comment by abclution** [comment]
Pretty sure its the same for either/both. 

Will triple check right now

**Comment by abclution** [comment]
@jcameron  Yeah, happens regardless whether shared or allocated.

only the AAAA for autoconfig and AAAA autodiscover is created.

**Comment by jcameron** [comment]
Is DNS hosted locally on your Virtualmin system, or on a remote server?

**Comment by abclution** [comment]
> Is DNS hosted locally on your Virtualmin system, or on a remote server?

Locally, although I do have a slave/secondary setup through webmin.

**Comment by jcameron** [comment]
Can you post the contents of the /etc/webmin/bind8/config file on your system? There's an option to control if AAAA records are enabled.

**Comment by abclution** [comment]
Here it is:

```

this_ip=199.20.49.19
support_aaaa=1
tmpl_dnssecalg=RSASHA1
checkzone=named-checkzone
file_perms=
tmpl_dnssecsizedef=1
chroot=
dnssec_period=1
forwardzonefilename_format=ZONE.hosts
named_conf=/etc/bind/named.conf
restart_cmd=
slave_dir=/var/lib/bind
allow_underscore=1
updserial_man=1
tmpl_email=hostmaster@fixd.eu
rndc_cmd=rndc
rev_must=0
rndcconf_cmd=rndc-confgen
dnssectools_keydir=
named_user=
named_group=
pid_file=/var/run/bind/run/named.pid /var/run/named.pid /var/run/named/named.pid /var/run/bind/run/named/named.pid
extra_reverse=
allow_comments=1
auto_chroot=
other_slaves=0
slave_file_perms=
tmpl_dnssec_dt=
named_path=/usr/sbin/named
ndc_cmd=ndc
free_nets=
zones_file=/etc/bind/named.conf.local
soa_start=0
whois_cmd=whois
rev_def=0
confirm_zone=1
keys_dir=
master_dir=/var/lib/bind
reversezonefilename_format=ZONE.rev
relative_paths=0
confirm_rec=0
signzone=dnssec-signzone
soa_style=1
tmpl_dnssecsingle=0
max_zones=500
start_cmd=
updserial_def=0
keygen=dnssec-keygen
stop_cmd=
default_master=
extra_forward=
allow_long=0
tmpl_dnssecsize=
file_owner=
allow_wild=1
no_chroot=0
tmpl_dnssec=0
force_random=0
checkconf=named-checkconf
records_order=1
ipv6_mode=1
dnssectools_rollrec=
by_view=0
spf_record=0
dnssectools_rollmgr_pidfile=
master_ttl=1
largezones=0
no_pid_chroot=0
show_list=1
extra_slaves=secondaries
rndc_conf=/etc/bind/rndc.conf
dnssectools_conf=
updserial_on=1
short_names=0
default_view=
default_slave=126.45.19.68
servers=1601155604
secservers=1601155604
default_prins=


```

**Comment by jcameron** [comment]
Is your system perhaps behind NAT, where the IP address used in DNS records is different from the internal IP used by your machine?

**Comment by abclution** [comment]
My IPV4 address, yes behind a nat.
My IPV6 addresses are assigned directly to the interface.

I smell you are getting close.

**Comment by jcameron** [comment]
Thanks! I see the bug now - it will be fixed in the next Virtualmin release.

**Comment by abclution** [comment]
Thank you!
