### ISSUE TITLE
BUG: dnssec-signzone fails on some Virtualmin domains due to redundant DKIM record with missing DKIM identifier.

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#122]
Virtualmin is failing to re-sign some domains/zones.
Could this be fixed?

Error message on dashboard:
```
Error!
Warning : The following zones have expired DNSSEC signatures : 
mydomain.com (15/Nov/2019), 
mydomain2.com (15/Nov/2019), 
mydomain3.com (15/Nov/2019), 
mydomain4.com (15/Nov/2019), 
mydoamin5.com (15/Nov/2019), 
mydomain6.com (15/Nov/2019), 
mydomain7.com (15/Nov/2019), 
mydomain8.com (15/Nov/2019)

Use the BIND DNS Server module to either disable DNSSEC for these domains, or check why signing is failing. 
```

When you go to BIND DNS Server module, then go to one of the domains with expired DNSSEC and Virtualmin failed to re-sign the domain, and click "Sign Zone", this is the resulting error you get:
```
Failed to sign zone : 
dnssec-signzone: warning: /var/lib/bind/mydomain.com.hosts:1: no TTL specified; using SOA MINTTL instead 
dnssec-signzone: warning: /var/lib/bind/mydomain.com.hosts:46: signature has expired
dnssec-signzone: error: dns_master_load: /var/lib/bind/mydomain.com.hosts:140: empty label 
dnssec-signzone: fatal: failed loading zone from '/var/lib/bind/mydomain.com.hosts': empty label 
```

**Comment by jcameron** [comment]
Could you post the contents of `/var/lib/bind/mydomain.com.hosts` here? It's not clear what that "empty label" message means..

**Comment by chris001** [comment]
> Could you post the contents of `/var/lib/bind/mydomain.com.hosts` here? It's not clear what that "empty label" message means..

Here's line 140-145 from `/var/lib/bind/mydomain.com.hosts` (it's a multi line entry of the rather long DKIM public key):
```
._domainkey.mydomain.com.      IN      TXT     ( "v=DKIM1; k=rsa; t=s; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwtOxLWP+9e1hu"
        "RPHQ7dexdvkJntS/Xb43BiBgMTU4R4omTrDVwR47WZyn2IX1WzJ1oA+wnCb+xLqGmzOPEZYUEA9d8ExK"
        "SIC+Jt9YKeldb4QQPUl0QPo+NQ7BmXfAImJFpjt/htbP1gXfqSXzNA2BPrREpvjhhrtrxLkTduM1QYsj"
        "0FSAfWi2Y4lB4OxwEkcENGby1W+UV1qWXR6f49waNF69ay93Lg4MGFii6V1HcbC2g25BnWfyfj0K3Hlg"
        "CvdmfvUbKt8vEB0u0OeMWDMQVsY8kBp2FzUxz4AIIh5UwoAqIeQ93VoPamsiD2YSKZznJU+vK2moJ//D"
        "FbQ+tAa5QIDAQAB" )
```

**Comment by chris001** [comment]
On further investigation, this `bind9` command/feature `dnssec-signzone` fails for a domain managed by Virtualmin, when, on the page **"Server Configuration / DomainKey Options"**, the domain is set to use its own uniquely generated DKIM key (`Use key below`), in other words, to NOT `Use global default key` as its DKIM key.

How to fix ??

**Comment by chris001** [comment]
More info:
When you try to turn off the unique generated DKIM key, by setting `use global default key`, and click `Save`, it fails with this message:
```
Using default DKIM key ..
.. done

Adding DKIM records to DNS domain mydomain.com ..
.. records already exist
```
That's correct, the DKIM record already exists.  Yet, shouldn't Virtualmin overwrite the existing `DKIM` record in bind DNS, with the `global default DKIM key` ??

**Comment by chris001** [comment]
I found the fix to this bug.
I had to manually REMOVE the offending (invalid) `DKIM` record in the DNS zone file, for EACH zone/domain containing one, and there were about zones, each of which failed DNSSEC signing, and each of which became invisible/inaccessible on the secure internet because of the expiration of the DNSSEC signatures!  😥 🤦‍♂ 
The bug is, webmin/virtualmin code **_should not generate a `DKIM` record without a label!_**
This is an example of the start of a DNS record without a label. It's INVALID and will break DNSSEC signing and cause your domain to become unreachable!! :
`._domainkey.mydomain.com.    IN   TXT  `
This is an example of the start of DNS record WITH a label. This is VALID and will allow DNSSEC to sign your zone/domain, and allow the public internet to continue to reach your domain:
`201912._domainkey.mydomain.com.   IN    TXT    `
Somewhere in the perl code, this bug must be found and fixed...

**Comment by jcameron** [comment]
Virtualmin won't allow you to create a DKIM config without a selector, but if one of the underlying config files is missing it, the error you reported could happen. I'll add a check in the next release to prevent this..

**Comment by shoulders** [comment]
did this check get added?

**Comment by jcameron** [comment]
Yes it did
