### ISSUE TITLE
Different Default Apache Directives for SSL port on Virtual Server Creation

### ISSUE THREAD

**Issue by UnleavenedEagle** [virtualmin/virtualmin-gpl#123]
Hello!
I would like to be able to use a different Apache Server Template for the SSL websites created by Virtualmin. This would very useful if I am running Varnish in the background, and want the Apache SSL virtual host to be a proxy of the port 80, which runs Varnish, with the addition of an SSL certificate. Currently, I have to manually modify the vhosts to achieve this, but it would be nice to have a feature like this. If there is already a way to do this (without editing the Perl scripts), please tell me. Otherwise, take this as a feature request.
Thanks.

**Comment by jcameron** [comment]
You can customize the Apache template at System Settings -> Server Templates -> Default Settings -> Apache Website.

**Comment by UnleavenedEagle** [comment]
Yes, I know that. But I'm talking about one for SSL. If I change the option where you mentioned, it will change for SSL & non-ssl. It would be nice to have a feature where you can configure different directives for SSL websites from those on non-SSL.

**Comment by jcameron** [comment]
Right now, that's not possible - the same directives are always used in both types of VirtualHost.

**Comment by UnleavenedEagle** [comment]
Could you please add this to the roadmap?

**Comment by jcameron** [comment]
Yes, I think we can do this.

**Comment by jcameron** [comment]
This has been added for including in the next release.

**Comment by UnleavenedEagle** [comment]
Thanks for implementing this, however you have only added "extra directives", which does not solve my problem. I need completely different directives. Basically, website is hosted on port 8080, that vhost has the normal directives. Varnish runs on port 80, and proxies Apache on port 8080. As Varnish does not support SSL (at least not in the free version), the Apache vhost on the port 443 is basically SSL terminating and reverse proxying the Varnish server.

**Comment by UnleavenedEagle** [comment]
@jcameron Please reopen the issue.

**Comment by jcameron** [comment]
For that level of customization, maybe it's better to write your own script which runs after domain creation (virtualmin has hooks for this) and modifies the Apache config?

**Comment by UnleavenedEagle** [comment]
In my opinion this should be implemented on Virtualmin's side. Is there any negative impact implementing this would have?

**Comment by UnleavenedEagle** [comment]
Many Apache users tend to use Varnish to speed up the website, this would be a very a handy feature I think for lots of people.

**Comment by jcameron** [comment]
@UnleavenedEagle only extra complexity of having to support this case. Also, with browsers switching to HTTPS by default, it seems like there isn't as much value in a HTTP-only cache these days?
