### ISSUE TITLE
Can't change IP address to *

### ISSUE THREAD

**Issue by UnleavenedEagle** [virtualmin/virtualmin-gpl#124]
`Virtualmin > Addresses and Networking > Change IP addresses`

Setting `New IPv4 address` to `*` then clicking `Change Now` results in error: `Failed to change IP addresses : Missing or invalid new address`.

`*` should be a valid IP addresses, as it means any IP address for Apache.

I was able to set Virtualmin up so that it automatically gives virtual servers this IP address, however I'm unable to change it afterwards for already existing virtual servers.

The fix should probably be a one line code.

**Comment by UnleavenedEagle** [comment]
Also affects `Server Configuration > Change IP Address`.

**Comment by jcameron** [comment]
You cant enter * here as the IP is used for more than just the apache config (ie. DNS records)

**Comment by UnleavenedEagle** [comment]
Well, I have manually edited the files, but I want Apache to listen not just on one IP.
