### ISSUE TITLE
Let's Encrypt - End of Life Plan for ACMEv1

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#125]
The API used for the generation of Let's Encrypt certificates needs to be upgraded

Currently it is no longer possible to register new accounts via the ACMEv1, which as far a I understand means that only server where no virtualserver was ever used together with Let's Encrypt has problems registering new certificates?

Next year all new domains will be blocked from validating via ACMEv1

https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

**Comment by rostovtsev** [comment]
Thanks for your feedback.

It's already been fixed and scheduled for new, upcoming release.

**Comment by PitWenkin** [comment]
Any ETA on that release?

I might be able to create the certificate I need on an other server an transfert it to the one where I need it… but I prefer waiting some days if it means it will work out of the box …

**Comment by jcameron** [comment]
The plan is to stop including an ACME client in Webmin, and just use `certbot` (the official client) instead. You can just install it yourself right now, and Webmin will use it..

**Comment by PitWenkin** [comment]
Seems to work.

**Comment by chris001** [comment]
> The plan is to stop including an ACME client in Webmin, and just use `certbot` (the official client) instead. You can just install it yourself right now, and Webmin will use it..

Will Webmin simply accept and start taking over the periodic renewal task of, the existing LetsEncrypt certificates on the machine, previously manually obtained on the command line with the official clients `certbot` and `certbot-auto`, and located where the official clients save them, in `/etc/letsencrpt` ?

**Comment by PitWenkin** [comment]
As far as I understand it seems that Webmin manually triggers the certbot and places the certificates in the home-folder the website

**Comment by chris001** [comment]
> As far as I understand it seems that Webmin manually triggers the certbot and places the certificates in the home-folder the website

If that's true, then Webmin should not only install certs in home folder of website for use by web server, but also install certificates for the other services:
1. postfix smtp mail with SNI virtual host support, 
2. dovecot imap mail with SNI virtual host support, 
3. pop3 mail with SNI virtual host support, 
4. ftp with SNI virtual host support, 
5. etc.

**Comment by dianlujitao** [comment]
@jcameron ig it's still not available from latest stable release? I installed certbot but the web interface showed the same error.

**Comment by rostovtsev** [comment]
Yes, it will be coming in Webmin 1.940 next week.

**Comment by chris001** [comment]
> Yes, it will be coming in Webmin 1.940 next week.

If you run `update-from-repo.sh`, would that download this new code, which uses certbot?

**Comment by rostovtsev** [comment]
Yes, it would.

**Comment by PitWenkin** [comment]
Updating Webmin does NOT install certbot.

I updated ine server and tried to manually renew the certifcat for one website, but selecting the Let's Encrypt Tab on the SSL Certificate thingy showed the following:

> Let's Encrypt is a free, automated, and open certificate authority that can be used to generate an SSL certificate for use by Virtualmin.
However, it cannot be used on your system : The Let's Encrypt client command letsencrypt or certbot was not found on your system

I guess automatic updates would fail too?

**Comment by PitWenkin** [comment]
Executing `apt install certbot` and revisiting the page shows the certificate update form which then works as expected.

Should certbot not be included in dependencies, or at least add an option to install it via the web-interface e.g.:

> Let's Encrypt is a free, automated, and open certificate authority that can be used to generate an SSL certificate for use by Virtualmin.
However, it cannot be used on your system : The Let's Encrypt client command letsencrypt or certbot was not found on your system
**Click here to install certbot**

**Comment by jcameron** [comment]
@PitWenkin  - what page in Webmin did you see that error message on? It should have a prompt to install certbot below it.

**Comment by PitWenkin** [comment]
In Virtualmin.

`Server Conviguration` -> `SSL Certifcate` in the  `Let's Encrypt` Tab

Seems like this if failed: 	
https://github.com/virtualmin/virtualmin-gpl/blob/ee6d08d8ecde7364687faceb20a98942dcef75d9/cert_form.cgi#L353

I only got the error message from &webmin::check_letsencrypt()

**Comment by PitWenkin** [comment]
Stupid question, but has the current version of cert_form.cgi been added to the Webmin 1.940 release?

I can't find the cert_fom.cgi any where on my servers with the content as in https://github.com/virtualmin/virtualmin-gpl/blob/ee6d08d8ecde7364687faceb20a98942dcef75d9/cert_form.cgi … 

It seems to only exist at /usr/share/webmin/virtual-server/cert_form.cgi but that file has last been changed oct 16th 2019 …

**Comment by jcameron** [comment]
When the next release of Virtualmin comes out, it will prompt you to install `certbot` on that page.

**Comment by rostovtsev** [comment]
> When the next release of Virtualmin comes out, it will prompt you to install certbot on that page.

Jamie, I would like to propose to display a warning to install `certbot` for all CentOS 7 (and later), Debian 9 (and later), Ubuntu 16(and later), Fedora 30 (and later) - as of right now, because we got back ACME Tiny script as a fallback, it doesn't give a warning, and leave users to use ACME Tiny script, rather than `certbot` even though `certbot` is available on their systems for install from default repos.

**Comment by chris001** [comment]
Note: 
**The distro package of `certbot` is only working for a subset of the popular linux distros.**

On some operating system versions, (e.g. Debian 8 Jessie, and many others), the EFF says you must **remove the distro packaged version of `certbot`**, and instead **download the version directly from `EFF.org`.** to get basic domain certs, and **you must use the Docker method to get wildcard certs!!**

Reference: https://certbot.eff.org/lets-encrypt/debianjessie-apache

>  Remove packaged Certbot installation
>
> We previously recommended that Debian 8 (jessie) users install Certbot from the packaged version. Because of important updates in the Certbot code, we are now recommending that Debian 8 users switch to the `certbot-auto` method, described below.
> Run this command on the command line on the machine to remove previous installations of Certbot. If Certbot has never been installed, the command will not do anything.

`sudo apt-get remove certbot`

> Install Certbot
>
> Run these commands on the command line on the machine to install Certbot.

```
    wget https://dl.eff.org/certbot-auto
    sudo mv certbot-auto /usr/local/bin/certbot-auto
    sudo chown root /usr/local/bin/certbot-auto
    sudo chmod 0755 /usr/local/bin/certbot-auto
```

> **WILDCARD CERTS:**
> Follow Docker instructions
>
> To get a wildcard certificate on this system, you'll need to run Certbot in Docker. You can do so by following these steps from our documentation:
https://certbot.eff.org/docs/install.html#running-with-docker

**Comment by rostovtsev** [comment]
Chris, `certbot` package works on all major distros we tested it. I wouldn't recommend your solution to the future readers. 

By "many other", which ones exactly are you referring to?

**Comment by chris001** [comment]
> Chris, `certbot` package works on all major distros we tested it. I wouldn't recommend your solution to the future readers.
> 
> By "many other", which ones exactly are you referring to?

These "many other" distros, supported by Webmin/Virtualmin, must download `certbot-auto` from eff.org, either because a distro package doesn't exist, or the distro package is outdated, old version, and fails to obtain certs!:
1. Ubuntu 14.04 LTS
2. Debian 7
3. Debian 8
4. CentOS 6
5. RHEL 6
6. CentOS 8
7. RHEL 8

**Comment by rostovtsev** [comment]
In this case, I agree! Expect for CentOS 8, the list is correct. The mentioned distros are either EOL or will reach it very soon - exactly for such old distros we have ACME Tiny support (unless user would want to install _certbot-auto_ manually).

All contemporary Linux distros, will support _certbot_ installation from default (or additionally enabled) repos.

Virtualmin install script is not going to support EOL or reaching EOL distros anyway.

**Comment by chris001** [comment]
However, CentOS 6/RHEL 6 EOL is November 30, 2020, and Debian 8 EOL is June 30, 2020, so it's important to properly install `certbot-auto` for these distros, so they  can have these certs, automatically.
