### ISSUE TITLE
UI: Ambiguous "Setup DNSSEC Key" page.

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#129]
"BIND DNS Server" module.

It's not (at all) obvious, what the ramifications would be, to the `DS` records, should the user click the first or third button on this page:

![virtualmin ambiguous language bind dns server module dnssec key](https://user-images.githubusercontent.com/259416/70855009-ad9c1500-1e91-11ea-810f-7cf894eb61af.png)

Clicking which of these 2 buttons (  "Remove Key",  "Re-sign Zone" ) , would force a regeneration of the `DS` records??

Need to know, because if either of those button actions would cause the side effect where virtualmin would regenerate the `DS` records, then the consequence is serious, it'd require a very slow 2+ days turnaround, have to manually copy paste new `DS` records, email them to the sys admin at the DNS registrar, and wait for reply that they're active at the registry (verisgn for `.com`) !!

**Comment by rostovtsev** [comment]
I have added an improvement on UI side to make it more self-explanatory (starting with Webmin 1.941 release).

![image](https://user-images.githubusercontent.com/4426533/72730635-c7243100-3ba2-11ea-8eab-ff7c51aef140.png)

Using two last options (buttons in white) is safe, and will not regenerate DS records, set on registrar side.
