### ISSUE TITLE
Enhancement: Option to *not* compress backups

### ISSUE THREAD

**Issue by ghost** [virtualmin/virtualmin-gpl#13]
I currently create local backups and then use a separate backup applications which is much more robust in terms of compression, encryption and incrementals than Virtualmin's function - which is fine because Virtualmin shouldn't be trying to become a fully-fledged backup tool.

However, Virtualmin gzip's the tar files produced from the backup (or tells the tar tool to gzip it, not sure). It would be nice if I could specify no compression for backups, so the backup tool which I use can compress them better without me having to gunzip them after they are backed up.

**Comment by qooob** [comment]
Hi,

Virtualmin Configuration page has multiple options for _Backup and restore_.

There you can find _Backup compression format_ option. Besides there are _Extra command-line parameters for compression command_ option that will satisfy your needs in using additional software.

At the same time, in case your machine has available `xz` command installed, you can use it with `tar` command in options above and have super powerful compression.

**Comment by qooob** [comment]
_Additonal parameters to tar command_ can be used. Using tar's lowercase `j` switch uses _bzip_, uppercase `J` switch uses _xz_.

`XZ_OPT` is environment var that is used to define the compression level using `-9` is not maximal. You could use extreme compression levels:

```Bash
XZ_OPT=-e9
```

I bet that will be either the same powerful or even more than any other 3 party software. :wink:

**Comment by Orbixx** [comment]
Thanks for this, I'm actually trying to do this via CLI and was not able to find anything in the documentation that would allow me to avoid compressing the archives:

https://www.virtualmin.com/documentation/developer/cli/backup_domain

I still need to use my backup tool for practical reasons, so there's no sense compressing the backups twice. The tool I use will use LZMA compression, which is very similar to XZ and will likely achieve the same compression, but it also does incremental backups, de-duplication and encryption.

**Comment by qooob** [comment]
You can set `Backup compression format` to `None (tar only)` and get uncompressed file.

Besides, you can easily create encrypted archive using `7za` or `xz` and probably other.

Virtualmin does already support incremental backups. Check for option `Backup level` in _Scheduled Backup_ under _Destination and format_ tab and set it to `Incremental (only files changed since last full backup)
`

**Comment by Orbixx** [comment]
That's great, but I'm trying to back up Virtualmin and other unrelated things on the server at the same time, so even if Virtualmin did all of these things, I'd still have to use another backup tool.

So I can see that you can set this option via the GUI, but I can't see an option to do this via the CLI.

**Comment by qooob** [comment]
It's probably set using _UI_, globally. Let's see what Jamie or Joe gonna say.

**Comment by swelljoe** [comment]
As far as I can tell it is a global option. I don't think I understand your use case, though.

Why doesn't setting it in the GUI solve the problem for all future CLI backups for you?

Options can also be set from the command line, though it will still be global...I guess you could set it and then set it back after every backup that needs this option, if you only want this option sometimes. All Virtualmin configuration is stored in /etc/webmin/virtual-server/config and this option is labeled `compression`. You'd set it to `2` for no compression.

And, the flags option is called `zip_args`.

You could use sed or similar to change them for each backup run that needs custom options.

**Comment by jcameron** [comment]
There's a global option at System Settings -> Virtualmin Configuration -> Backup and Restore -> Backup compression format that you can set to "tar only" to have an uncompressed backup.

**Comment by marclaporte** [comment]
Looks like this issue should be closed as resolved.

**Comment by jcameron** [comment]
Yes this is long since fixed
