### ISSUE TITLE
REQ: Add domain expiration date to dashboard

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#131]
It'd be extremely helpful to have an overview of all domain expiration dates on the dashboard.

IIRC the expiration date could be extracted from the text returned by `dig mydomain.com`.

**Comment by jcameron** [comment]
Do you mean the SSL cert expiry date (possible, since Virtualmin knows this), or the DNS registrar expiry date?

**Comment by jcameron** [comment]
Never mind, I didn't read carefully enough - I guess you mean the second.

I think this would make sense to show as a warning in Virtualmin, rather than in the list of domains.

**Comment by rostovtsev** [comment]
Oh, that would be great to have.

I had a thought just now, that maybe creating a new accordion on the dashboard, called expiry or something, and display all kind of expiry details for domains? Like, registrar, SSL, DNSSEC and etc?

**Comment by rostovtsev** [comment]
Oh, and if another column could display, if the latest renewal was past due date or unsuccessful/successful, that would be even more awesome.

I also believe that it's must have for *Virtual Server Summary* page.

**Comment by chris001** [comment]
Exactly. There's a lot of security and registration items which, if ever allowed to expire, would end up causing a pretty bad catastrophe for the sys admin / organization / virtual server owner.  Domain registration, DNSSEC, LetsEncrypt or any SSL certs, DKIM keys (these don't self expire but to prevent email header forgery and phishing thefts, the server management software SHOULD automatically rotate them every 1-6 months as specified in the IETF RFC for DKIM), etc.

Wouldn't it be great to not have to worry about chasing after all those expiration dates, and just load the Virtualmin dashboard, it shows all the expiration dates/times, and when nothing in the list is warning as expiring soon (or already expired), then don't worry, be happy, "it just works"(TM).

**Comment by jcameron** [comment]
Yes, that's a good idea! We do show SSL certs nearing expiry already, but could expand this to DNS registration and other certs.

**Comment by jcameron** [comment]
Now that I'm looking into this ... is there a reliable way of figuring out the expiry date of a domain at it's registrar? I'm not seeing this in the `dig` output.

**Comment by chris001** [comment]
> Now that I'm looking into this ... is there a reliable way of figuring out the expiry date of a domain at it's registrar? I'm not seeing this in the `dig` output.

My bad!  It's not `dig` it's `whois`.
Here's the (nearly) complete solution in the form of a script to get the expiration date from the command-line (it needs tweaks to work with some two-level domains such as `.co.nz`):
https://www.cyberciti.biz/tips/domain-check-script.html
Installation and usage:
```
wget https://raw.githubusercontent.com/nixcraft/domain-check-2/master/domain-check-2.sh
wget https://raw.githubusercontent.com/nixcraft/domain-check-2/master/domain-list.txt
sudo mv domain-check-2.sh /usr/local/bin/
sudo chmod +x /usr/local/bin/domain-check-2.sh
/usr/local/bin/domain-check -d virtualmin.com
domain-check-2.sh -h
Usage: domain-check-2.sh [ -e email ] [ -x expir_days ] [ -q ] [ -a ] [ -h ]
          {[ -d domain_namee ]} || { -f domainfile}
 
  -a               : Send a warning message through email 
  -d domain        : Domain to analyze (interactive mode)
  -e email address : Email address to send expiration notices
  -f domain file   : File with a list of domains
  -h               : Print this screen
  -s whois server  : Whois sever to query for information
  -q               : Don't print anything on the console
  -x days          : Domain expiration interval (eg. if domain_date < days)
```
For comic relief, flash back to the time that `google.de` went down for a few hours, when Google forgot to renew that domain, and someone else registered it the instant it expired!  https://www.techcrunch.com/2007/01/23/google-forgets-to-renew-googlede-site-goes-down/

**Comment by jcameron** [comment]
The next Webmin release will use the `whois` command to get the expiry date and show a warning for domains close to or past expiry.

**Comment by rostovtsev** [comment]
Thank you so much! <3

**Comment by Deepcuts** [comment]
> The next Webmin release will use the `whois` command to get the expiry date and show a warning for domains close to or past expiry.

Any clue if this was ever implemented?
I have searched and searched and came up empty.
Maybe my searching skills are subpar today?

**Comment by iliajie** [comment]
Yes, this feature has been implemented and works just fine in a standard Virtualmin deployment.

If it doesn't work for you, try running `whois domain-name.com` and share the output with us.

**Comment by Deepcuts** [comment]
> Yes, this feature has been implemented and works just fine in a standard Virtualmin deployment.
> 
> If it doesn't work for you, try running `whois domain-name.com` and share the output with us.

whois works, of course, I am talking about the "Add domain expiration date to dashboard" part.
Or the implementation refers to just the CLI whois command and I have to check every domain hosted?

**Comment by iliajie** [comment]
> whois works

Ah, great!



> Or the implementation refers to just the CLI whois command

No.

> I am talking about the "Add domain expiration date to dashboard" part.

Yes, it's already showing domain expiration time in the dashboard, e.g.:

<img width="1152" alt="image" src="https://github.com/user-attachments/assets/040d2c1b-02f3-47b3-a43d-5cd36561bf7d">

**Comment by jcameron** [comment]
Would it help if expiration was shown on the List Virtual Servers page?

**Comment by Deepcuts** [comment]
If the message apears on the dashboard, it is just what the doctor ordered.
The issue I am having is that I have a domain that just expired and I did not see any message on the dash board.
Was just starting to code a script to send me a warning when I stumbled upon this issue here.
Do I have to enable something or is there any settings page for this please?
I tried adding a domain that will expire today, arleneehly.com and I do not see any warning on the dashboard.
![image](https://github.com/user-attachments/assets/3a114c46-6806-41a6-9308-bcffec5fdc55)

**Comment by iliajie** [comment]
> The issue I am having is that I have a domain that just expired and I did not see any message on the dash board.

We just call and parse `whois domain-name.com` command.

> Do I have to enable something or is there any settings page for this please?

Yes, status collection shouldn't be disabled:

<img width="1422" alt="image" src="https://github.com/user-attachments/assets/9745373a-2923-44f2-aa3b-adb62c77c55d">

**Comment by iliajie** [comment]
> Everything works just fine. It seems my eyes deceived me and I did not see the warning.

Oh, got it! Glad it did!
