### ISSUE TITLE
install.sh tries to install an old version of epel

### ISSUE THREAD

**Issue by wwalker** [virtualmin/virtualmin-gpl#136]
install.sh tries to install an old version of EPEL repo, and throws an erro because a newer version of EPEL is already installed:

```
package epel-release-8-8.el8.noarch (which is newer than epel-release-8-7.el8.noarch) is already installed                                                               
```

**Comment by wwalker** [comment]
Full execution text:
```
[INFO] Started installation log in /root/virtualmin-install.log

▣□□ Phase 1 of 3: Setup
/usr/sbin/setenforce: SELinux is disabled
Downloading virtualmin-release-latest.noarch.rpm                        [  ✔  ]
Installing virtualmin-release package                                   [  ✔  ]

▣▣□ Phase 2 of 3: Installation
Downloading epel-release-latest-8.noarch.rpm                            [  ✔  ]
Installing EPEL release package                                         [ERROR] Failed with error: 2
[  ✘  ]

[ERROR] Something went wrong. Exiting.
[ERROR] The last few log entries were:
2020-01-12 22:05:33 URL:https://software.virtualmin.com/vm/6/gpl/centos/8/x86_64/virtualmin-release-latest.noarch.rpm [14112/14112] -> "virtualmin-release-latest.noarch.rpm" [1]
Downloading virtualmin-release-latest.noarch.rpm: Success.
Spin pid is: 916
Installing virtualmin-release package: Success.
[2020-01-12 22:05:34 UTC] [DEBUG] Phase 2 of 3: Installation
Spin pid is: 946
2020-01-12 22:05:34 URL:https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm [21844/21844] -> "epel-release-latest-8.noarch.rpm" [1]
Downloading epel-release-latest-8.noarch.rpm: Success.
Spin pid is: 977
        package epel-release-8-8.el8.noarch (which is newer than epel-release-8-7.el8.noarch) is already installed
Made it here...why?
Installing EPEL release package: [2020-01-12 22:05:34 UTC] [ERROR] Failed with error: 2
[2020-01-12 22:05:34 UTC] [ERROR] Something went wrong. Exiting.
[2020-01-12 22:05:34 UTC] [ERROR] The last few log entries were:
```

**Comment by swelljoe** [comment]
This specific issue is a problem upstream. The `epel-release-latest` package should point to the latest epel-release package...that it doesn't is out of our control. You'll need to remove that newer EPEL release package. (install.sh expects a fresh OS install, anyway...don't do anything, enable any repos, etc. before installing Virtualmin...do those things after.)

But, also, CentOS 8 is not yet supported in Virtualmin. The list of supported operating systems is printed at the start of the install and on our [Virtualmin OS Support page](https://www.virtualmin.com/os-support).

There is a version of the install script that adds CentOS 8 support here: https://github.com/virtualmin/virtualmin-install/raw/add-centos-8/virtualmin-install.sh

But, and this is a very big but: There is an outstanding issue with Webmin restarting itself reliably that will prevent any reasonable usage of Virtualmin. You'll have weird problems with it on a daily basis until I figure out why it's doing what it's doing.
