### ISSUE TITLE
Renaming MySQL user .. .. MySQL database failed! ...

### ISSUE THREAD

**Issue by lisandi** [virtualmin/virtualmin-gpl#137]
When importing a virtual server backup from another Virtualmin instance to a new server with freshly installed Virtualmin and Mariadb 10.4, and then moving the virtual-server to a new user throws an error - Version 6.08 Virtualmin -
Renaming MySQL user ..
.. MySQL database failed! : mysql::execute_sql_logged failed : SQL rename 'user.name'localhost' to 'other.user'localhost' failed : You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''user.name'localhost' to 'other.user'localhost'' at line 1 at /usr/share/webmin/web-lib-funcs.pl line 1495.

A new user can't be created either mysql/save_user.cgi?xnavigation=1

Failed to save user : SQL insert into user (host, user, Select_priv, Insert_priv, Update_priv, Delete_priv, Create_priv, Drop_priv, Reload_priv, Shutdown_priv, Process_priv, File_priv, Grant_priv, References_priv, Index_priv, Alter_priv, Show_db_priv, Super_priv, Create_tmp_table_priv, Lock_tables_priv, Execute_priv, Repl_slave_priv, Repl_client_priv, Create_view_priv, Show_view_priv, Create_routine_priv, Alter_routine_priv, Create_user_priv, Event_priv, Trigger_priv, Create_tablespace_priv, Delete_history_priv, ssl_type, ssl_cipher, x509_issuer, x509_subject, authentication_string) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) failed : The target table user of the INSERT is not insertable-into

It is also not possible to create a new database - virtual-server/save_database.cgi?xnavigation=1
Failed to create database : SQL grant all privileges on `data\_base\_name\_2`.* to 'user.name'@'localhost' failed : Can't find any matching row in the user table 

And no database can actually be seen in the phpmyadmin (virtualmin) script when setting the user to be able to see ANY database - mysql/list_dbs.cgi?xnavigation=1. He can't see even his own in phpmyadmin. But his own database and other are visible in the webmin/mysql server and virtualmin/local server/database when logged in as root in virtualmin.

**Comment by jcameron** [comment]
The Virtualmin part of this bug will be fixed in the next release. The Webmin part will take longer..

**Comment by iliarostovtsev** [comment]
Support for MariaDB 10.4+ and MySQL 8+ has been implemented in Webmin 1.960. Let us know if it works for you.
