### ISSUE TITLE
php-fpm fails to restart on Ubuntu 16.04

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-gpl#14]
Virtualmin on Ubuntu 16.04 can't find the php-fpm service to restart it. It's named php7.0-fpm but even when I add that to php-lib.pl it fails to restart. I can't quite figure out how to make it to the right thing.

Here's where I added it:

```perl
foreach my $init ("php-fpm", "php5-fpm", "php7-fpm", "php7.0-fpm",
                  (map { "php${_}-fpm" } @all_possible_php_versions)) {
        my $st = &init::action_status($init);
        if ($st) {
                $rv->{'init'} = $init;
                $rv->{'enabled'} = $init > 1;
                last;
                }
        }
```
But, no dice.

Also, there's still some issues detecting init type...it still seems to detect/treat it like upstart even though it has systemd. I may have broken it with my change that changed the order of detected init system; or maybe this new system has upstart in addition to systemd or something (I dunno why they'd do that, but sometimes people do weird stuff).

Anyway, error is:

```
Restarting PHP-FPM server ..
.. failed : Failed to restart php-fpm.service: Unit php-fpm.service not found. 
```

But, I can restart it successfully with:

```bash
# service php7.0-fpm restart
```

And, sites begin to work afterward; so config seems to be doing the right thing, but the service just isn't being restarted.

**Comment by jcameron** [comment]
Did you restart webmin after making that change? Cause that file is cached in RAM on startup..

**Comment by swelljoe** [comment]
Yeah, I restarted Webmin. Problem persists. The text of the error indicates it's trying to start php-fpm.service, but that doesn't exist, and Webmin *knows* it doesn't exist (it doesn't show up in the Bootup And Shutdown services list), and systemctl only knows about:

```bash
# systemctl list-units|grep php
php7.0-fpm.service                                           loaded active running   The PHP 7.0 FastCGI Process Manager
```

I see 7.0 in `@all_possible_php_versions`, as well, so it seems like maybe my change shouldn't even be needed. I'm thoroughly confused where it's getting php-fpm.service from.

**Comment by swelljoe** [comment]
I added logging at the end of that function, and it's clearly returning $rv->{'init'} == 'php-fpm'. I just can't see why.

**Comment by swelljoe** [comment]
Ah, this comes down to something broken in Webmin's init module.

When I change it to:

```perl
foreach my $init ("boogadie", "php-fpm", "php5-fpm", "php7-fpm",
                  (map { "php${_}-fpm" } @all_possible_php_versions)) {
        my $st = &init::action_status($init);
        if ($st) {
                $rv->{'init'} = $init;
                $rv->{'enabled'} = $init > 1;
                webmin_log("Have init of: $st", 'joe', 'joe');
                last;
                }
        }
```

It returns "boogadie". Would this happen if init system is incorrectly detected? (Because that seems to be happening, as well. It thinks this system is upstart.)

**Comment by swelljoe** [comment]
Yep, that's the problem. Forcing it to be systemd in the Bootup and Shutdown module resolves this. So...just need to fix init module to correctly detect systemd in this case.

**Comment by swelljoe** [comment]
So, yeah, I think it was the change I committed a while back broke this. But, I'm not sure what to do to fix it. Ubuntu 16.04 in some cases apparently has both initctl and systemctl, even when it is actually a systemd system.

**Comment by swelljoe** [comment]
Oh, shit. I actually fixed this with my last commit. Nevermind. It just isn't in a released Webmin yet. I thought it had gone into 1.852.
