### ISSUE TITLE
"Failed to read help file" newips_old6.html & newips_new6.html

### ISSUE THREAD

**Issue by Francewhoa** [virtualmin/virtualmin-gpl#141]
Steps to reproduce challenge

1. Using Virtualmin, navigate to "Addresses and Networking" ---> "Change IP Addresses"

1. Click on "IPv6 address of servers to update" field title

1. This error message is display

> Error
> 
> Failed to read help file /usr/share/webmin/virtual-server/help/newips_old6.html

This screenshot shows the location of the first challenge

![Failed to read help file  SLASH usr SLASH share SLASH webmin SLASH virtual-server SLASH help SLASH newips_old6 html](https://user-images.githubusercontent.com/119942/73334769-693abd80-4222-11ea-9df2-76c460e844f8.jpg)

4. On the same page, click on the field titled "New IPv6 address"

1. This error message is display

> Error
> 
> Failed to read help file /usr/share/webmin/virtual-server/help/newips_new6.html

This is the second challenge

6. Expected result is that no error message are display. Instead the appropriate help text is display. 

All other help links on this page are successfully opening. Just those two above need fixing love.

Using Virtualmin 6.08

**Comment by rostovtsev** [comment]
Okay, thanks! Fixed https://github.com/virtualmin/virtualmin-gpl/commit/e3daa81d8d52683d77d818ca62bcac314eecd68a.

**Comment by Francewhoa** [comment]
Thanks @rostovtsev
