### ISSUE TITLE
“PHP-FPM Configuration” button wrong URL

### ISSUE THREAD

**Issue by Francewhoa** [virtualmin/virtualmin-gpl#148]
### Summary

On each "PHP Versions" change, in Virtualmin left side menu, somehow the URL on the "PHP-FPM Configuration" button is not updated. In turn, this result in four challenges. Steps to reproduce those & details are below. 

### Steps to reproduce

1. Using fresh

   - Debian 10 Buster
   - Virtualmin 6.08
   - Webmin 1.941
   - Authentic theme 19.46 
   - Firefox 68.5 ESR

1. Install PHP-FPM using the 3 command lines in this [documentation](https://www.virtualmin.com/documentation/web/multiplephp#toc-installing-php-56-70-71-72-73-74-on-debian-10-buster-9QanbRc4 ). So that you are able to easily and quickly switch PHP version per Virtual Server. Including PHP versions 5.6, 7.0, 7.1, 7.2, 7.3, 7.4.

1. Choose one default PHP version. To do so, using Virtualmin dropdown menu, select one Virtual Server. Navigate to "Server Configuration" ---> "PHP Versions". On the "PHP Versions" page, select one PHP version. In this example 5.6.40. Click on "Save Versions" button. The numbers 1 and 2 in this screenshot show this. 
![select_default---php_versions](https://user-images.githubusercontent.com/119942/76339270-13444580-62b7-11ea-96ec-60bc488a5efe.jpg)

1. Customized the PHP-FPM 5.6.40 configuration. To do so,  using the same Virtualmin Virtual Server, navigate to "Services" ---> "PHP-FPM Configuration". On the "Manage PHP Configuration" page, click on "Edit Configuration Manually" button. Edit this file to your liking. Click on "Save" button. This screenshot show this.
![Edit Configuration Manually](https://user-images.githubusercontent.com/119942/76340365-b47fcb80-62b8-11ea-8985-f968aaaca9cf.jpg)

1. Change the default PHP version. To do so, using the same Virtualmin Virtual Server, navigate to "Server Configuration" ---> "PHP Versions". On the "PHP Versions" page, select another PHP version. In this example change it from 5.6.40 to 7.3.15.  Click on "Save Versions" button. 

1. Notice that when the user click on the "Save Versions" button above, the left side vertical menu did _not_ refresh. This is the **first challenge**. The expected result is that when the user click on "Save Versions" button, somehow this menu needs to be refresh. So that the its URLs are updated appropriately.

1. Try to customized the PHP-FPM 7.3.15 configuration. To do so,  using the same Virtualmin Virtual Server, navigate to "Services" ---> "PHP-FPM Configuration". Before you click on this "PHP-FPM Configuration" button, notice that its URL is wrong. In this example, the URL still reads `https://domainexample.ca:10000/phpini/list_ini.cgi?file=/etc/php/5.6/fpm/pool.d/254570124514625.conf`
This is the **second challenge**. Expected result is that somehow this URL needs to be updated to match the one new default "PHP Versions". In this example the expected URL is `https://domainexample.ca:10000/phpini/list_ini.cgi?file=/etc/php/7.3/fpm/pool.d/254570124514625.conf`
The number 1 in this screenshot shows the location of this second challenge.
![PHP-FPM Configuration---menu](https://user-images.githubusercontent.com/119942/76342929-9ae08300-62bc-11ea-804c-d46c1a282e3c.jpg)

1. On the "Manage PHP Configuration" page, notice that right below the title the PATH to the configuration file is wrong. In this example, the PATH still reads `/etc/php/5.6/fpm/pool.d/254570124514625.conf (FPM format)`
This is the **third challenge**. Expected result is that somehow this PATH needs to be updated to match the new default "PHP Versions". In this example the expected PATH needs to read `/etc/php/7.3/fpm/pool.d/254570124514625.conf (FPM format)`
The number 1 in this screenshot shows the location of this third challenge.
![Edit Configuration Manually---7 3](https://user-images.githubusercontent.com/119942/76342651-2d345700-62bc-11ea-8c04-4fa7823dc358.jpg)

1. Still on the "Manage PHP Configuration" page, notice that the editing area is empty. This is the **fourth challenge**. Expected result is that the default PHP 7.3 configuration needs to be both loaded and display to the user. The number 2 in this screenshot shows the location of this fourth challenge.
![Edit Configuration Manually---7 3](https://user-images.githubusercontent.com/119942/76342651-2d345700-62bc-11ea-8c04-4fa7823dc358.jpg)

We have not tried to click on the "Save" button. As this is risky to create an additional challenge(s). Including, but not limited to, the realistic risk that in good faith, clicking this button would likely result in [kicking-off the moon from its orbit](https://youtu.be/6MP920xMC0Q). Which would mess-up the ocean tides, LOL ;) I do enjoy beach waves so would miss them.

Any volunteer for a patch? The Ubertus team would be happy to contribute testing and documentation if needed :)

### Cause

This is a speculation. In the "Steps to reproduce" section above, at step 5, about "Change the default PHP version", maybe when the user clicks on the "Save Versions" button above, the left side vertical menu did _not_ refresh. So the URL is outdated. In turn, this result in all four challenges above?

### Resolution

How about this suggested resolution? In the "Steps to reproduce" section above, at step 5, about "Change the default PHP version", after the user click on the "Save Versions" button above, how about somehow always refresh the Virtualmin left side vertical menu? This would likely resolve this first challenge. So that the the correct URL is on the button. Same suggested resolution for the other three challenges about the right side page titled "Edit Configuration Manually".

#### Refresh the browser page(s)

After the user click on the "Save Versions" button, using the browser, such as Firefox, refreshing the page did resolve this challenge. As the left side menu was refresh with the correct link.

#### Deactivate "Preload Virtualmin libraries"

After a fresh Virtualmin installation, using the Virtualmin "Post-Installation Wizard", at the "Memory use" step, activate "Preload Virtualmin libraries". In other words, set it to "Yes". So that both Virtualmin & Authentic theme load much faster. Alternatively, this feature is located under "System Settings" ---> "Virtualmin Configuration" ---> "Preload Virtualmin libraries at startup?".

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the detailed bug report - amazing!

It's fixed now. Give it a try [by patching a file](https://github.com/virtualmin/virtualmin-gpl/commit/f23dbb4100eb4a79ef6a4d8729bf916757410822).

Does it work for you?

**Comment by Francewhoa** [comment]
Thanks @iliarostovtsev for the lightning fast patch ☇ :)  

I'll happily pass it on the UB team. For their next batch of testing. When done I'll add the result in this ticket.

**Comment by Francewhoa** [comment]
This is to confirm that your patch is successful @iliarostovtsev 🎉🥇 It passed the Ubertus team testing. Thanks :)

When user click on the "Save Versions" button, the left side menu automatically reload. Plus a handy spinning progress wheel is display. Nice. This screenshot shows this successful patch in action. You saved the moon 🌔 ;) Again.
![successful_patch_f23dbb4100eb4a79ef6a4d8729bf916757410822---2020-03-10---14:17:22---Selection_001---ubertus](https://user-images.githubusercontent.com/119942/76360743-d68a4580-62da-11ea-92b2-79b918283941.jpg)
