### ISSUE TITLE
WordPress is invisible on Ubuntu 16.04 and I can't figure out why

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-gpl#15]
This is the weirdest damned thing...WordPress installer shows disabled in the Disable Scripts interface and doesn't show up at all for domain install scripts form.

Here's what's whack about it:

In the scripts-lib get_script function, when I log the state of all of the scripts immediately before the object is constructed WordPress has avail_only set to 1 just like all the rest of them.

Here's all the availability related vars for WordPress right before filling in the return hash:

"avail: 1 avail_only: 1 disabled:  allowmaster: "

This is identical to all the rest, which all work.

But, when I log it in edit_newscripts.cgi, avail_only is empty, while all the ones that work are `1`.

I can't figure out where it could be changing in the interim. There's no other code I can see that changes the state of that variable.

And, worse, this only happens on Ubuntu 16.04. I thought it might be related to scope changes or something in newer Perls, but it doesn't hit Debian 9, and sticking some `my`s in there doesn't fix it.

I'm completely stumped. If you want to see this in action, you can login to 51.15.216.77 with the usual test server password.

**Comment by jcameron** [comment]
Taking a look now ..

**Comment by jcameron** [comment]
Ok, turns out that this was due to an incompatability between the current virtualmin version and updated script files. The 6.01 release will fix it.
