### ISSUE TITLE
php7.4 is not detected

### ISSUE THREAD

**Issue by Gamesh** [virtualmin/virtualmin-gpl#152]
> Apache is installed.
> 
> The following PHP versions are available : 7.0.33 (/usr/bin/php-cgi7.0), 7.2.29 (/usr/bin/php7.2), 7.3.16 (/usr/bin/php7.3)
> 
> The following PHP-FPM versions are available on this system : 7.0.33 (php7.0-fpm) 7.2.29 (php7.2-fpm) 7.3.16 (php7.3-fpm)
> 

php7.4 installed and fpm available:
```
php7.4 -v
PHP 7.4.4 (cli) (built: Mar 20 2020 14:24:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies
```
```
ls /etc/init.d/php*
/etc/init.d/php7.0-fpm  /etc/init.d/php7.2-fpm  /etc/init.d/php7.3-fpm  /etc/init.d/php7.4-fpm
```
```
ls /etc/php/7.4/
apache2  cgi  cli  fpm  mods-available
```

**Comment by iliarostovtsev** [comment]
Hi,

It will be fixed in Virtualmin 6.09. Meanwhile, you can using the [following work-around](https://forum.virtualmin.com/t/php-7-4-not-showing-as-option-under-virtualmin/104088/4?u=ilia).

**Comment by Gamesh** [comment]
oh, great! thank you

**Comment by Gamesh** [comment]
@iliarostovtsev can we please not hardcode php versions and use /etc/php/<version> as an actual detection mechanism?

**Comment by iliarostovtsev** [comment]
We could, I bet, but at the moment we've just simply added more of other PHP versions, up to 7.9, which should be fine for the near future.

**Comment by Gamesh** [comment]
@iliarostovtsev what if the next version won't be 7.x, but 8 straight away :D which is entirely possible they are working on it, if we look back at the history 
last 4.x version was 4.4, then 5.0 came;
last 5.x version was 5.6, then 7.0, they even skipped 6, 
so please don't assume version numbers are sequential and consistent, they are not :)

**Comment by jcameron** [comment]
I wouldn't want to have Virtualmin attempt to configure a hypothetical PHP 9 until we've qualified that it works, which is why I'd prefer a fixed list of known versions.
