### ISSUE TITLE
Apt/deb package for version 6.09 missing

### ISSUE THREAD

**Issue by ardabeyazoglu** [virtualmin/virtualmin-gpl#156]
Just installed virtualmin on ubuntu 18.04 latest using your installer, which installed 6.08. 

Would it be okay, if i would just copy-paste latest release to apt installed webmin directory ?

**Comment by whereisaaron** [comment]
Yeah @ardabeyazoglu I am missing 6.09 too. Looks like [6.09 came out in February](https://github.com/virtualmin/virtualmin-gpl/releases/tag/6.09) but there is some blockage getting to to the package repos. Hopefully soon as it looks like some good fixes in it!

**Comment by ardabeyazoglu** [comment]
@whereisaaron As far as I see, modifying installed files dont cause problems so its not an urgent issue. Just downloaded and replaced.

**Comment by ardabeyazoglu** [comment]
just got an update on ubuntu 18.04, so closing the issue.

**Comment by whereisaaron** [comment]
Me too, just today 6.09 popped up on Ubuntu 🎉
