### ISSUE TITLE
Linux Firewall - Don't see all the rules

### ISSUE THREAD

**Issue by 7starsone** [virtualmin/virtualmin-gpl#16]
Hello, 
I don't know if from Virtualmin or Authentic

if I do on shell `iptables -L -n |more` I can see all the rules and chains, many as usual...all the banned IPs and so on

If I click on "Linux Firewall"on Networking, the rules are not updated, there's not a button to see all the rules or to update to see the current real status of iptables

thanks

**Comment by qooob** [comment]
What do you see in Gray Theme?

**Comment by 7starsone** [comment]
the same, I just see old rules... there are not the entire fail2ban chains and the listed banned IPs are wrong, not updated

**Comment by swelljoe** [comment]
The Linux Firewall module shows what is in the iptables save file, *not the active set of rules*.

You can tell it to "Revert configuration" which will cause the running rules to become the saved rules, but you probably don't want to do that for fail2ban rules (as they're supposed to be ephemeral, and removable by fail2ban). You should think of fail2ban rules as being separate from your normal firewall managed by Webmin. You don't want to change them...fail2ban does that.

**Comment by 7starsone** [comment]
ok, and how to see the active set on Virtualmin? Is that possible?

**Comment by gnadelwartz** [comment]
You can set firewall to direct, then it does show current config and mot the saved config

**Comment by gnadelwartz** [comment]
This should be the default if you use fail2ban

**Comment by 7starsone** [comment]
@gnadelwartz ok, thanks...got it 😄
