### ISSUE TITLE
Private key mangled/not handled correctly when updating end entity certificate

### ISSUE THREAD

**Issue by ChristopherW** [virtualmin/virtualmin-gpl#161]
I obtained an updated (reissued) certificate from my CA after I added some more SANs. I uploaded the new certificate to the site's home directory, chowned appropriately and then navigated to it via the _File on Server_ GUI browser to select. I left the _Matching private key_ option as _"Keep existing private key"_ as it was unchanged.

However, when submitting the form, I was shown this error:

 ```
/home/exampleuser/certs/1234567890repl_2.crt

Failed to install certificate : Failed to open /home/exampleuser/certs/exampleprivate.key.webmintmp.12939 : Permission denied
```

This occurred on a couple of sites I tried (which used their own copies of the same cert). Each time, the update process would also **delete** the private key, meaning I had to restore a backup.

The update only worked when I explicitly provided the path to the unchanged private key file with the _"File on server"_ option.

**Comment by jcameron** [comment]
Was this file and the original cert file owned by the domain user?

**Comment by ChristopherW** [comment]
Yes, each copy chowned to that domain's user and group and and chmod 644.

**Comment by jcameron** [comment]
Also, is the directory `/home/exampleuser/certs` owned by and writable by the domain user?

**Comment by ChristopherW** [comment]
I think you win the prize today @jcameron! Missed that as I was working at a sudo prompt, not in the context of the site's user.
