### ISSUE TITLE
2 simple things regarding backups (Virtualmin GPL) unaware if these are present on the Pro.

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#162]
### Per Backup Job/Schedule Compression Options

Currently, as far as I understand it, compression options for backups are global (at least in the web interface.)

**I would propose allowing compression options be set on a per backup job/schedule basis.**
**_Let the current global settings option be the default for any newly created job._**

Use case: I currently backup (FULL) to several locations, one of these locations has a block de-duping compressing file system. When sending archives to there, leaving them in tar format is preferable as the filesystem is super efficient with the storage. My secondary storage is of course remote and I use gzip/bzip with it to efficiently transfer. A backup job defined individually with compression options per schedule job would make sense here.

### Backup Job Naming / Label and/or Notes 

This is simply to be able to discern what a particular backup job is for.
Currently, I must drill into the backup job, look at the options to grok why that particular job exists.
Being able to name a job, or have a notes column would be a big quality of life inprovement.

Any particular reason why the above are not a good idea, or perhaps they exist and I am unaware?

**Comment by chris001** [comment]
Good point, it looks like Virtualmin backup doesn't let you specify any compression option, so if I'm not mistaken, this would be a very good feature to add:
https://www.virtualmin.com/documentation/developer/cli/backup_domain

**Comment by jcameron** [comment]
These are good ideas - I'll look into implementing them for the next release.

**Comment by jcameron** [comment]
Ok, support for per-backup compression type has been implemented for inclusion in the next release.
