### ISSUE TITLE
MySQL 8 authentication plugin

### ISSUE THREAD

**Issue by adbario** [virtualmin/virtualmin-gpl#170]
MySQL 8 uses `caching_sha2_password` authentication plugin by default and this works nicely in Virtualmin.

For PHP to support the same authentication plugin, you will need to use version 7.4 or above. With previous PHP versions you will have to set MySQL 8 `default_authentication_plugin` setting to `mysql_native_password` for your scripts to work. Even when changing this setting, Virtualmin keeps creating new users with `caching_sha2_password` authentication plugin, so I'm wondering if there could be some global configuration option to make sure users will be created the correct way?

I could create some custom script to run after server creation, that sets the password using correct auth plugin, or manually update how the user is created here https://github.com/virtualmin/virtualmin-gpl/blob/master/feature-mysql.pl#L2819, but would rather use some config option to handle this.

**Comment by adbario** [comment]
For reference, here's an example script that can be run automatically after making changes to server. This will update MySQL users authentication plugin virtual server has MySQL enabled.

```bash
#!/bin/sh

if [ "$VIRTUALSERVER_ACTION" != "DELETE_DOMAIN" ]; then

    if [ $VIRTUALSERVER_MYSQL ]; then
        echo "<p>Configuring MySQL authentication plugin ..<br>"

        mysql --user="root" -e "ALTER USER '$VIRTUALSERVER_MYSQL_USER'@'localhost' IDENTIFIED WITH mysql_native_password BY '$VIRTUALSERVER_MYSQL_PASS';"

        echo ".. done</p>"
    fi

fi
```
MySQL root user credentials needs to be saved in `/root/.my.cnf` for this to work.

**Comment by unixnut** [comment]
https://github.com/virtualmin/virtualmin-gpl/pull/206 should fix this.

**Comment by iliarostovtsev** [comment]
Check this patch, guys.

https://github.com/virtualmin/virtualmin-gpl/commit/12397f01dbb3d5451189833c1029bf266d96df50

**Comment by iliarostovtsev** [comment]
Fixed.

Okay. There is the final patch for this and familiar issues.

https://github.com/virtualmin/virtualmin-gpl/commit/d7dec417248fc7ae9638ceb5a43d564fbc88f087#diff-6fa2afd8e898593d63a1dacfb644de43
