### ISSUE TITLE
S3 backups can fail without warning

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-gpl#172]
When copying backup files to S3 fails due to `'AWSHTTPSConnection' object has no attribute 'ssl_context'` error (seemingly caused by a bug in AWS CLI when working with newer versions of python requests library) the backup will "succeed" but no backups exist. It's pretty bad to have backups fail silently.

See thread here for more: https://forum.virtualmin.com/t/aws-s3-bucket-setup-stopped-working/106127

**Comment by jcameron** [comment]
Looks like the `aws` command can fail but not exist with a non-zero status in some cases. I'll add an extra check for this kind of failure..
