### ISSUE TITLE
Removing domain leaves out records in `miniserv.conf` file

### ISSUE THREAD

**Issue by iliarostovtsev** [virtualmin/virtualmin-gpl#174]
When deleting a domain, the records in _miniserv.conf_ are left behind leaving Webmin broken for restart/start.

![image](https://user-images.githubusercontent.com/4426533/85208048-0b745280-b336-11ea-852c-b1f6cdf0bbae.png)

When deleting the default domain for Webmin, same happens but in global scope. When deleting the default domain, Webmin should switch to using default `keyfile=/etc/webmin/miniserv.pem` and delete/reset `certfile` and `extracas` directives.

**Comment by jcameron** [comment]
I was unable to re-produce this - can you post the steps needed to trigger it, using the latest checked-in webmin code?

**Comment by iliarostovtsev** [comment]
Yes, nothing special. Add domain, remove domain. :slightly_smiling_face: 

It was the same on different, updated (with Webmin and Virtualmin) machines.

**Comment by jcameron** [comment]
Odd ... did you create the domain via the UI, or the API?

**Comment by iliarostovtsev** [comment]
Reference - https://github.com/virtualmin/virtualmin-gpl/issues/175
