### ISSUE TITLE
SSL related records for services are left over, after virtual server is deleted

### ISSUE THREAD

**Issue by iliarostovtsev** [virtualmin/virtualmin-gpl#175]
If you create a virtual server with SSL website enabled, you will have correspondent records with certificates files added to _miniserv.conf_, _dovecot.conf_, _sni_map_ and etc. If you try to immediately delete a virtual server all works fine and the records for domain are deleted as expected. However, if you request Lets Encrypt certificate and later try to delete virtual server - the SSL related records are not deleted, from neither of files.

For instance, what I could test out, is after you request Lets Encrypt certificate and the **.ca** entry is added to _miniserv.conf_, when deleting a virtual server, like mentioned above does nothing and SSL related entries (_ipcert_dom.com_, _ipkey_dom.com_ and _ipextracas_dom.com_) are not removed from _miniserv.conf_. However, if before clicking delete virtual server button, I manually edit and remove only _ipextracas_dom.com_ record, and safe the file and then try to delete virtual server, then other two _ipcert_dom.com_ and _ipkey_dom.com_ records are deleted correctly. It's worth pointing out, that It doesn't have the same logic in relation to _dovecot.conf_ and _sni_map_ though.

Using latest committed code for both Webmin and Virtualmin. Tried on Ubuntu 20.04, Debian 10 and CentOS 8.

**Comment by jcameron** [comment]
Ok, seems like this may be related to the Dovecot and Webmin certs not being detected as associated with the domain at deletion time.

**Comment by iliarostovtsev** [comment]
It also affects new _sni_map_.

**Comment by jcameron** [comment]
Latest commit fixes this issue
