### ISSUE TITLE
SNI map for Postfix is incorrect

### ISSUE THREAD

**Issue by iliarostovtsev** [virtualmin/virtualmin-gpl#177]
I was doing more pre-production tests and found out that the **sni_map** that we're currently generating is not in correct format.

We are generating:

![image](https://user-images.githubusercontent.com/4426533/86252968-8c480f80-bbbc-11ea-9cd4-92d54b44cb0e.png)

While the correct should be:

![image](https://user-images.githubusercontent.com/4426533/86253029-a386fd00-bbbc-11ea-905b-2d4955f77231.png)

I made a patch https://github.com/virtualmin/virtualmin-gpl/commit/7326a393fae2c510c71847c70237803638817b1c to make the map generate with expected format, meanwhile, there are few other, correlated things to fix.

**Comment by iliarostovtsev** [comment]
Jamie, we need to double check what Postfix states on its [docs for SNI](http://www.postfix.org/postconf.5.html#tls_server_sni_maps):

> Note that the SNI lookup tables should also have entries for the domains that correspond to the Postfix SMTP server's default certificate(s). This ensures that the remote SMTP client's TLS SNI extension gets a positive response when it specifies one of the Postfix SMTP server's default domains, and ensures that the Postfix SMTP server will not log an SNI name mismatch for such a domain. The Postfix SMTP server's default certificates are then only used when the client sends no SNI or when it sends SNI with a domain that the server knows no certificate(s) for.

I am not sure yet what it affects really but I assume that SNI table should include default hostname records. As previously discussed, adding those records upon wizard check and requesting hostname's default certificate would be a solution, unless it creates extra unforeseeable issues.

**Comment by iliarostovtsev** [comment]
Jamie, there is only a need to fix ***.** to **.** in map for wildcard domains. Having certificates in comma separated list is working, thanks goodness!

https://github.com/virtualmin/virtualmin-gpl/commit/96c2ddc0675c44eae434581a075fe4d529dd753a

**Comment by iliarostovtsev** [comment]
Meaning that, the correct SNI map for Postfix should be:

![image](https://user-images.githubusercontent.com/4426533/86269197-151d7600-bbd2-11ea-9556-bdcd5084f8f0.png)

It seems to work just fine like that, but please double check that changing *. to . in [code](https://github.com/virtualmin/virtualmin-gpl/blob/master/feature-ssl.pl#L2242) will not affect anything else. 

I can tell already say, that it doesn't delete the following record, as it expects ***.** :

~~~
.server1.ubuntu20.indie.engineer	/home/server1/ssl.key,/home/server1/ssl.cert,/home/server1/ssl.ca
~~~

**Comment by iliarostovtsev** [comment]
I think `sub hostname_under_domain` needs a fix.

**Comment by iliarostovtsev** [comment]
@jcameron Jamie, if this https://github.com/virtualmin/virtualmin-gpl/commit/a8785247ebdc78f6f33ad103546cf91357151d81 patch wouldn't have any other bad consequences, I can tell that it works just fine in the context of SSL Certificate page.

**Comment by jcameron** [comment]
Thanks for this patch - you're correct about the format.

**Comment by iliarostovtsev** [comment]
Great. I'll keep testing!
