### ISSUE TITLE
Sporadic disability to work out externally visible IP address

### ISSUE THREAD

**Issue by iliarostovtsev** [virtualmin/virtualmin-gpl#178]
I am currently testing things on Ubuntu 20.04. I create and delete virtual-servers.

Time after time, when I create virtual server I get this error:

![image](https://user-images.githubusercontent.com/4426533/86257859-c6b4ab00-bbc2-11ea-9bfa-69791d41af00.png)

It would be alright, if the error persisted but the problem is, that I simply wait a bit, click go back button and then try again and have new virtual-server created successfully. 

![image](https://user-images.githubusercontent.com/4426533/86258070-1004fa80-bbc3-11ea-9595-07679c338452.png)

I only defined in Virtualmin Configuration network interface name:

![image](https://user-images.githubusercontent.com/4426533/86258206-3a56b800-bbc3-11ea-9be9-30abd5922edf.png)

However, before submitting this request, I changed it back to detect automatically, and behavior still the same.

**Comment by lukesUbuntu** [comment]
I have had the same issue happen about a  year ago was on a virtualmin setup which was a virtual server running ubuntu 18.04lts but has never happened on my dedicated servers. I presumed it was a vps issue and just manually added the network settings when it did happen.

**Comment by iliarostovtsev** [comment]
Thanks for heads up.

I just would want Jamie to have a look. What if there is something evident that's causing it, and could be fixed easily.

**Comment by iliarostovtsev** [comment]
It's apparently connected to DNS configuration and how it's resolved. Network configuration can be easily changed to make Virtualmin work with default options (detect automatically) but what makes me wonder why it doesn't fail _all the time_, if result of `dig ubuntu20.indie.engineer` run from localhost always _127.0.0.1_. I expected it in such case scenario to fail all the time.

Nevermind, it can be closed.
