### ISSUE TITLE
Error, Failed to save Enable Features, 16.04.

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#18]
```
Error
Failed to save enabled features : Suexec is enabled in the default template, but the suexec command was not found on your system.
```
16.04.
Installed is `libapache2-mod-fcgid`.
Result of `apachectl configtest` is `Syntax OK`.

Goal is to have virtualmin use the lowest RAM/CPU resource consuming version of Apache 2.4 = PHP-FPM.

**Comment by chris001** [comment]
`apt install apache2-suexec-custom`

**Comment by swelljoe** [comment]
So, you got this figured out? (suexec-custom is the package you need)

**Comment by chris001** [comment]
@swelljoe Yes, it looks like you can pick from 2 packages on 16.04 which provide `suexec`, either `apache2-suexec-custom` or `apache2-suexec-pristine`.
```
Description: Apache HTTP Server configurable suexec program for mod_suexec
 Provides a customizable version of the suexec helper program for mod_suexec.
 This is not the version from upstream, but can be configured with a
 configuration file.
 .
 If you do not need non-standard document root or userdir settings, it is
 recommended that you use the standard suexec helper program from the
 apache2-suexec-pristine package instead.
```
I picked `apache2-suexec-custom` because as far as I know virtualmin is running websites from document root directories other than `/var/www`.

**Comment by swelljoe** [comment]
Yes, custom is the one you need. You can see a full list of the dependencies we install on Ubuntu here: https://github.com/virtualmin/virtualmin-lamp-stack-ubu

You probably want to make your own metapackage with the dependencies you want to include, so you can automate it and even use the install.sh (if you want to) with a minor tweak to add another repository for your own custom metapackage. You can make a custom Virtualmin-Config plugin bundle, as well, if you wanted to. It just needs to be a sub-class of Virtualmin::Config.

Here's what those look like: https://github.com/virtualmin/Virtualmin-Config/blob/master/lib/Virtualmin/Config/MiniLAMP.pm

They're declarative, you don't need to know any Perl to understand what they do. You'd just change the list of plugins to include and give the file/object a new name.

Or you can use:

```bash
# virtualmin config-system --include Apache --include Postfix --include ProFTPd
```

Where you'd list all the plugins you want. It's also possible to use a bundle, and exclude the things you don't want, e.g.:

```bash
# virtualmin config-system --bundle MiniLAMP --exclude ProFTPd
```
