### ISSUE TITLE
REQ for Info: How to install/use/test virtualmin git releases on existing server

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#181]
Is there any instructions how to install / use virtualmin-gpl git releases on an existing server? (For testing purposes)

I tried searching for it but only came across info regarding the git feature usage in virtualmin.

**Comment by abclution** [comment]
Nevermind, found the deb releases of the dev versions 👍 

https://download.webmin.com/download/virtualmin/

Herpaderp

**Comment by iliarostovtsev** [comment]
We are discussing to setup _testing_ repos in the future.

**Note:** The link in your comment above is actually a stable release branch.

**Comment by abclution** [comment]
Oh I didnt realize that. I guess it hits there before the repos.

Was trying to test out the postfix SNI in 6.10 but when I enable "Postfix IP Certificate enabled? " in the new Site -> SSL Options ->  Service Certificates area, I get this error.

 500 - Error - Perl execution failed
Undefined subroutine &postfix::regenerate_sni_table called at /usr/share/webmin/virtual-server/feature-ssl.pl line 2268.

I looked through all the files and cannot find the postfix::regenerate_sni_table function anywhere, so I guess its not in 6.10 👀

**Comment by chris001** [comment]
Unit tests would be a very good thing to add.

The easiest way to add unit tests, is to **test the command line interface command which does the function of the corresponding Web GUI links**.

Question: _**Is there one command line command, for every one of the major function clickable Web GUI links ?**_

**Comment by iliarostovtsev** [comment]
> Was trying to test out the postfix SNI in 6.10 but when I

It requires Webmin 1.953.

**Comment by abclution** [comment]
> > Was trying to test out the postfix SNI in 6.10 but when I
> 
> It requires Webmin 1.953.

Sigh. I was sure I already tried that but I was incorrect. Thank you.
