### ISSUE TITLE
Post Backup command is failing as of ~1 month ago, did the backup job owner change? 

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#183]
Just realized that my post backup commands (rclone sync) have been failing for about a month.
I didn't exactly pay attention to the days I upgraded VM/WM but I am assuming it is because of one of the recent versions. It appears because the backup job is no longer running as root, but as another account?

Working Post Backup Job

```
Running post-backup command ..
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Elapsed time:         0.0sTransferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Elapsed time:         0.0sTransferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -

```

Broken Post Backup Job

```
Running post-backup command ..
2020/06/09 05:24:14 NOTICE: Config file "/tmp/.webmin/400355_32738_22_backup.pl/.config/rclone/rclone.conf" not found - using defaults
```

Previously, the job running as root, would find the rclone.conf in the root home folder and be on its merry way.
Now it is looking for the rclone.conf in a randomish place.

I know I can fix this by specifing my rclone.conf on the command line, but I have no idea who/what permissions I need to assign to it.

Is there a changelog / documentation area I missed? 

Who do backup jobs run as now?

I am sure there is a good reason for the changes but I am used to running backups as root, I feel worried that any user other than root is not going to be able to do a full and complete backup job.

**Comment by jcameron** [comment]
The post-backup commands always run as `root`, but it's possible that the backup process changed the $HOME environment variable which led to `rclone.conf` not being found. So specifying the full path to the config files is the safest option.

**Comment by abclution** [comment]
Great, duly noted. 

Closed and hopefully someone else that may have this issue can find the resolution as well in future googly searches.

Thank you @jcameron

**Comment by jcameron** [comment]
BTW, I found the code that causes $HOME to be set incorrectly in some cases, and will include a fix for it in the next Webmin release.

**Comment by abclution** [comment]
Hooray, I almost contributed!

**Comment by jcameron** [comment]
You did contribute - this was a legit bug that hadn't been noticed till now.

**Comment by abclution** [comment]
Well shucks, if finding obscure issues is contributing, I'll take it!
