### ISSUE TITLE
Restore failed : Failed to find section local_name domain.tld !

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#186]
Trying to restore a simple domain backup, not sure what is happening. 

Here is the output of the error_stack=1

Additionally I have been getting "Failed to find section local_name " occasionally sometimes during domain creation

```
...clipped
Restoring Apache virtual host configuration ..
.. done

Checking restored PHP execution mode ..
.. mode FPM OK for this system

Restoring Apache log files ..
.. done

Restoring SSL Apache virtual host configuration and certificate ..

Restore failed : Failed to find section local_name domain.tld !
```
Call Stack Trace

File | Line | Function
-- | -- | --
/usr/share/webmin/dovecot/dovecot-lib.pl | 252 | WebminCore::error
/usr/share/webmin/virtual-server/feature-ssl.pl | 1995 | dovecot::save_directive
/usr/share/webmin/virtual-server/copycert-lib.pl | 264 | virtual_server::sync_dovecot_ssl_cert
/usr/share/webmin/virtual-server/feature-ssl.pl | 882 | virtual_server::enable_domain_service_ssl_certs
/usr/share/webmin/virtual-server/backups-lib.pl | 2789 | virtual_server::restore_ssl
/usr/share/webmin/virtual-server/restore.cgi | 346 | virtual_server::restore_domains
(eval 80) | 6 | (eval)
/usr/share/webmin/miniserv.pl | 2485 | (eval)
/usr/share/webmin/miniserv.pl | 972 | miniserv::handle_request

**Comment by iliarostovtsev** [comment]
Hi, 

Thanks for detailed issue report.

Are you running latest Webmin.1.953 and Virtualmin 6.10?

**Comment by abclution** [comment]
Yes. 

I forgot to mention, this is a subserver of an primary account.
The type that has this arrow  ↴

**Comment by iliarostovtsev** [comment]
> I forgot to mention, this is a subserver of an primary account.

Jamie will have a look but meanwhile, what if you try not to restore SSL feature at all? You simply could enable SSL website feature later and request new certificates.

**Comment by geofftech** [comment]
I have seeing the same on all attempts to transfer a domain or restore a backup.

I just installed a brand new VPS to test this and am getting the same error consistantly.

When restoring a backup, the restore will fail and no database will be created.. However, re-doing the restore over the top of an existing domain resolves this.

**Comment by iliarostovtsev** [comment]
You can apply [this patch](https://github.com/webmin/webmin/commit/2ee43178df0cefe4e72398c521e2a908eb38011c) to give it a try.
