### ISSUE TITLE
Sub `save_domain()` can actually save empty files

### ISSUE THREAD

**Issue by iliarostovtsev** [virtualmin/virtualmin-gpl#187]
I have been working today on patches for Bugzilla:

https://github.com/virtualmin/virtualmin-gpl/commit/ee8202cae0ab94bb116fd86d16d0c0d8f9225494
https://github.com/virtualmin/virtualmin-pro/commit/4339622339a3916d9a151f60e7b662a3c516776e

.. and, I came across devastating behavior - under unclear circumstances the domain config file (_/etc/webmin/virtual-server/domains/159307676413884_) is getting written empty.

I have debugged it and found out that it only happened, when you run Bugzilla install script. Because `create_script_database` is being called all the time for scripts with db - it didn't happen with other scripts. So when does it happen? It happens if **save_domain()** cannot read file AFTER lock, right here:

![image](https://user-images.githubusercontent.com/4426533/87666334-1bcef000-c771-11ea-81e5-4f3ea3ac30b4.png)

In other words, if **$oldd** is empty things get broken further (empty domain config file is written). Empty **$oldd** might be just an indicator of a main issue. Empty **$oldd** happened to be only in Bugzilla install script.

So, something break **&lock_file/&read_file** in some way. I couldn't figure this out reliably and quick enough, so I am reporting it back to you. 

To reproduce an issue, simply try installing Bugzilla (I tried on CentOS 7 and Debian 10), and you will end up with:

![image](https://user-images.githubusercontent.com/4426533/87666520-6d777a80-c771-11ea-9fce-6572f7ed3ef0.png)

.. because the file will be empty after calling **save_domain()** sub:

![image](https://user-images.githubusercontent.com/4426533/87666576-82eca480-c771-11ea-869c-95428cc771a2.png)

.. and then you would end up with errors like this all over:

![image](https://user-images.githubusercontent.com/4426533/87666610-939d1a80-c771-11ea-804b-04e20997aed1.png)

**Comment by jcameron** [comment]
Failure to read `$oldd` won't cause an empty file to be written - it's only used to check for changed values.

The `save_domain` function already has protection against writing an empty hash, on line 199 in your screenshot..

**Comment by iliarostovtsev** [comment]
> Failure to read $oldd won't cause an empty file to be written - it's only used to check for changed values.

Something else does then?

**Comment by iliarostovtsev** [comment]
I just tried it on a new install with latest commits and it happened again, on the second go.

![image](https://user-images.githubusercontent.com/4426533/87811397-4bf8ba80-c867-11ea-9c89-a457a667c28a.png)

**Comment by jcameron** [comment]
What actions trigger this though?

Also, is the system perhaps low on disk space?

**Comment by iliarostovtsev** [comment]
> Also, is the system perhaps low on disk space?

No!

> What actions trigger this though?

Regular install BugZilla action with latest patches I made, the let through dependency installations. Technically it happens in create data base section, which later calls **save_domain()**, which  actually has correct **$d** data in it.

**Comment by iliarostovtsev** [comment]
Okay, the issue been fixed. Thanks @jcameron
