### ISSUE TITLE
Undefined subroutine &virtual_server::modify_ipkeys

### ISSUE THREAD

**Issue by SnakeO** [virtualmin/virtualmin-gpl#188]
When I run this command:
virtualmin modify-domain --domain OLD --newdomain NEW --shared-ip IPV4 --shared-ip6 IPV6

I get this error:
Updating virtual server arvadavethospital.com ..

Updating users ..
.. done

Removing from email domains list ..
.. done

Adding to email domains list ..
.. done

Changing domain name in mail aliases ..
.. done

Updating aliases for contact address ..
.. done

Error: virtualmin-nginx-ssl::feature_modify failed : Undefined subroutine &virtual_server::modify_ipkeys called at /usr/share/webmin/virtualmin-nginx-ssl/virtual_feature.pl line 384.

**Comment by iliarostovtsev** [comment]
Yeah, that sub has been removed since Virtualmin 5.07. @jcameron what this sub has been replaced with?

**Comment by jcameron** [comment]
This functionality has moved elsewhere in Virtualmin - we need to fix the Nginx module to not call this function anymore.

Will have a patch shortly..

**Comment by jcameron** [comment]
Ok a fix for this has been submitted, and should trigger an update to the Nginx plugin shortly.

**Comment by SnakeO** [comment]
Thank you!

**Comment by SnakeO** [comment]
Strangely, the error persists. I've updated and restarted the server:

apt list --installed

```
webmin-virtualmin-nginx/stable,stable,now 2.11 all [installed]
webmin-virtualmin-nginx-ssl/stable,stable,now 1.11 all [installed]
```

```
Updating users ..
.. done

Removing from email domains list ..
.. done

Adding to email domains list ..
.. done

Changing domain name in mail aliases ..
.. done

Updating aliases for contact address ..
.. done

Error: virtualmin-nginx-ssl::feature_modify failed : Undefined subroutine &virtual_server::modify_ipkeys called at /usr/share/webmin/virtualmin-nginx-ssl/virtual_feature.pl line 384.

Error
-----
virtualmin-nginx-ssl::feature_modify failed : Undefined subroutine &virtual_server::modify_ipkeys called at /usr/share/webmin/virtualmin-nginx-ssl/virtual_feature.pl line 384.
```

**Comment by SnakeO** [comment]
I went ahead and just edited my file directly with your commit and it works. Just FYI here's a warning Im seeing:

```
Updating virtual server arvadavethospital.com ..

Updating users ..
.. done

Removing from email domains list ..
.. done

Adding to email domains list ..
.. done

Changing domain name in mail aliases ..
.. done

Updating aliases for contact address ..
.. done

Changing domain name in Nginx configuration ..
.. done

Changing IP address in Nginx configuration ..
.. done

Changing IPv6 address in Nginx configuration ..
.. done

Use of uninitialized value $old_alog in string ne at /usr/share/webmin/virtualmin-nginx/virtual_feature.pl line 492.
Renaming Nginx log files ..
Use of uninitialized value $old_elog in string ne at /usr/share/webmin/virtualmin-nginx/virtual_feature.pl line 502.
.. done

Renaming Nginx configuration file ..
.. done

Saving server details ..
.. done

Updating virtual server webmail.ocmt.org ..

Saving server details ..
.. done

Applying Nginx configuration ..
.. Nginx webserver is not running

All done
```

**Comment by iliarostovtsev** [comment]
> webmin-virtualmin-nginx/stable,stable,now 2.11 all [installed]
> webmin-virtualmin-nginx-ssl/stable,stable,now 1.11 all [installed]

It will only be updated in 2.12 and 1.12 releases. @swelljoe is fixing his automated build systems.

**Comment by iliarostovtsev** [comment]
@SnakeO Check this patch please https://github.com/virtualmin/virtualmin-gpl/issues/188#issuecomment-660958393
