### ISSUE TITLE
/etc/skel/public_html/index.html is ignored/replaced with Virtualmin default page

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-gpl#192]
It's impossible to configure a default index page in Virtualmin GPL, and it's confusing/requires user input in Virtualmin Pro.

In Virtualmin GPL, `/etc/skel/public_html/index.html` gets overwritten by the Virtualmin default index. This goes against years of documentation/advice and makes it impossible for a user to configure their own default page.

In Virtualmin Pro, it is possible to get the `/etc/skel/public_html/index.html`, but it requires user input (making it not "default" anymore). in order to get the page from `/etc/skel`, the user has to select "No" for *Create initial web page?* (at least, I cannot find this option in Server Templates). This is confusing....because a default page is being put in place from /etc/skel, where it's always been configured in the past....but it sounds like nothing will be put in place.

I think the simplest thing to do here is that if there is an `/etc/skel/public_html/index.html` it is always used. Labeling on the Virtualmin Pro page may need to change to make it more clear what's going on.

We can't demand extra user input on every new domain creation for something like this. It has to be in Server Templates (if it's configurable on the Creation form) and it has to respect /etc/skel.

**Comment by jcameron** [comment]
Yeah, that's a bug ... I just checked in a fix for this.
