### ISSUE TITLE
Let's Encrypt renewal fails due to race contition?

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#193]
Since the last update (6.10) there seems to have been some changes, which have the effect that all domains expiring on one day are renewed at the same time. Could be related to #171 

These are the emails I received for renewals on one server for today:

![Screenshot 2020-07-23 at 07 21 14](https://user-images.githubusercontent.com/45786226/88254383-7908fb00-ccb5-11ea-89ec-6625a53fa1a7.png)

I could have sworn that before the update, renewals were more distributed over time.

Problem is there seems to be some kind of racecondition, where the completed renewal of one domain trigggers an apache restart which fails because the renewal of another domain was already started and some files mismatch.

The following happened at 3:59 when the first two domains for that specific server were renewed

> [Thu Jul 23 03:59:23.923323 2020] [mpm_prefork:notice] [pid 19533] AH00171: Graceful restart requested, doing restart
…
[Thu Jul 23 03:59:35.502152 2020] [ssl:emerg] [pid 19533] AH02565: Certificate and private key `domain`:443:0 from /home/`domain`/ssl.cert and /home/`domain`/ssl.key do not match
[Thu Jul 23 03:59:35.502172 2020] [:emerg] [pid 19533] AH00020: Configuration Failed, exiting
[Thu Jul 23 03:59:36.450584 2020] [ssl:warn] [pid 22031] (22)Invalid argument: AH02026: Failed to acquire SSL session cache lock
[Thu Jul 23 03:59:36.450735 2020] [ssl:warn] [pid 22031] (22)Invalid argument: AH02027: Failed to release SSL session cache lock

Should the renewal script, if it triggers a apache restart, not check if that restart was successfull?

Im still not sure how the subsequent renewals could be completed since apache was down from 3:59 until 6:02 … unless the renewal uses only DNS for verification and no longer checks the url itself?

I had the same issue last week on two other servers. It does not happen every time though.

All servers have the following versions:

> Operating system Ubuntu Linux 16.04.6
> Webmin version 1.953
> Usermin version 1.802
> Virtualmin version 6.10
> Authentic theme version 19.52

**Comment by jcameron** [comment]
That's odd, as Virtualmin only does one renewal at a time - however, I can see this causing problems if Apache restarts are done asynchronously as Virtualmin just sends a signal to Apache telling it to reload the config.

The best solution is to add a random factor to space out these renewals so they don't all happen at once - we'll add that in the next release.

**Comment by PitWenkin** [comment]
Thanks
