### ISSUE TITLE
Usermin / Webmin Read mail module: Poor support of dovecot layout=fs folders, IMAP (instead of local maildir)  times out

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#194]
I recently spent some time setting up mailbox sharing on the Virtualmin system (It works, although only between same domain users, not across separate domain users.) , so I have been a bit deep into the mail services these days. Additionally I hope to write a little tutorial on it once I get everything debugged and maybe with the blesssing of the Virtualmin team you guys can add it to the documentation.. but I digress..

I recently switched from regular maildir to maildir:layout=fs. The biggest reason is that regular maildir prevents users from using . (period) in mail folders as dots present to dovecot as subdirectories, as well as nested directories behave more predictably for end users as well.

It turns out that layout=fs is poorly supported in the Usermin read mail module. (Either that or there is a setting or two I am missing.)

Using layout=fs, usermin mail only shows the Inbox, no other folders are represented.

On creation of a new folder using Usermin Mail, the folder is created with the leading . in the folder name as it seems to be unaware of the layout=fs setting, and that folders are named normally and normal folders without the leading dot are IMAP.

I read a much earlier suggestion (old virtuamin forum post) to improve Usermin mail when using this setting to switch the module to using IMAP as the primary connection, instead of the local maildir option.

So I switched, Webmin -> Usermin Configuration -> Usermin Module Configuration -> Read Mail -> Mail storage format for Inbox, switched from Maildir style to remote IMAP server option.

POP3 or IMAP server name | localhost
Use SSL when connecting to IMAP server | Yes No, I tried both
Prevent POP3 or IMAP logout once logged in? |  Yes

No matter what the settings are, the Usermin interface takes 1-2 minutes to time out, but then strangely enough gives me an error about POP3.

Here is the web interface error:

An error occurred listing mail in this folder : Failed to login to POP3 server : [AUTHENTICATIONFAILED] Authentication failed.

To be quite honest, I don't really know where to debug this more. I did NOT see any connection in the mail logs.

Switching back to maildir and adding an IMAP folder of the local server works, but this particular method only represents a single IMAP folder, and does not present the tree of folder to subscribe to, so also not optimal.

Anyways, if I am doing something wrong, lemme have it.
If this is expected behavior, color me surprised.

**Comment by chris001** [comment]
For comparison and to see if this is really a bug, although it does sound like one, could you install and test using the Roundcube mail into webmin/virtualmin, on the same mailboxes, with the same dovecot settings.  Roundcube's an open source mail reader with broad support, and if it breaks the same way, then that will mean something.  If it works with the same settings, then that will mean something else...

**Comment by abclution** [comment]
Sure, was going to do it anyways.


> For comparison and to see if this is really a bug, although it does sound like one, could you install and test using the Roundcube mail into webmin/virtualmin, on the same mailboxes, with the same dovecot settings. Roundcube's an open source mail reader with broad support, and if it breaks the same way, then that will mean something. If it works with the same settings, then that will mean something else...

**Comment by abclution** [comment]
My existing roundcube worked with no additional configuration, everything shows as expected including shared folders.

**Comment by chris001** [comment]
OK, it looks like the email client in `usermin` does indeed need an update to handle the `dovecot` IMAP setting `layout=fs`  folders.

**Comment by chris001** [comment]
https://dovecot.org/pipermail/dovecot/2018-January/110733.html

**Comment by abclution** [comment]
> https://dovecot.org/pipermail/dovecot/2018-January/110733.html

Yes, it does appear Usermin expect things a certain way.  Although it seems to be as simple as it currently filters any folders without a . preceding the folder names, expecting regular old Maildir happily unaware of the layout=fs method.

There are real client side benefits to running layout=fs if using Maildir as a default, specifically for client facing behaviors such as in IMAP folder names which that email list message does not cover.

Dots . periods are very common in folder naming requirements, especially considering many / most business email addresses are some form of firstname.lastname@bizdom.com , filtering into folders based on email names become possible, not to mention filtering into folders by doman.XXX also becomes possible. 

**The ONLY benefit of not using layout=fs is lowered inode usage,** but this is a relic of a long gone era and side effect of the ext2 and early ext3 days. I run ZFS so I don't worry regarding inodes, but neither do most ext4 systems either.

https://wiki.dovecot.org/Plugins/Listescape

As mentioned there:
>Listescape plugin
>The Listescape plugin allows users to use characters in mailboxes names that would otherwise be illegal (due to the underlying mailbox storage), for example:
>Maildir++ layout disallows using the '.' character (unless LAYOUT=fs is used), since it's used internally as the folder hierarchy separator.

The combination of supporting layout=fs as well as the Listescape plugin (as well as shared mailboxes) pretty much brings Virtualmin up to par with other solutions. And also gives users the full range of names and capabilities of IMAP email system.

Also, please again read my first comment regarding the Usermin -> Read Email -> Connect to IMAP server ALSO not working, which this should probably work regardless as well since it is not related to the .layout=fs settings. 

Now, whether Usermin email system is intended to keep up with modern sensibilities, I understood it to be part of a unified system and package, especially for the commercial offering Virtualmin Pro, and I do feel it is a bug.


 I don't make money using Virtualmin (don't get me wrong, I always wanted to moonlight as webhost, but I primarily do small business systems administration and solutions), and my "clients" consist of supporting friends and family for their own web dreams by handling their hosting (free) and teaching them about web technologies..as well as my own personal project de jour.  

Only recently due to pandemic time off have I had the time to dig into all the aspects of the Virtualmin hosting system from corner to corner.  I haven't looked for support (beyond reading Google searches) in the 15 years I have been using Virtualmin and I only report my findings  as a wish for the product to mature further, nothing more. 
<... irrelevant side-quest>
I am but a simple + grateful GPL user that has been using Virtualmin (+ my first love Webmin) since their initial releases and have always been thankful for them. I almost saved enough money to buy a perpetual license back when they were offered but it was not meant to be. For me it was a dream to support a project that has been a part of my life for such a significant period, I never needed Pro support, I wanted to support Pro.  

I missed that period and my chance to feel like I was part of building Virtualmin by supporting monetarily has passed. (I have a thing about buying for life software licenses.) Its the only way I feel like I am getting something for my money.  I am well aware the continual costs for development and fully understand why so little software can afford to be offered as such. I don't complain, I wax poetic. So now, I contribute like this. 
</... irrelevant side-quest>

 In fact, until just recently, I only used the web hosting simplifications it brings for development and have never even used the Usermin email functions, ever (well since the early early days). I just happen to a so called "client/friend" who actually is interested in using all the features that Virtualmin has to offer so I have indulged them by pushing my system to its potential by dusting off all the corners. I have found a few spiders.

I have mostly for my own uses, used either Squirrelmail (woo!)/ RoundCube or various mail clients, for me Usermin mail is not a show stopper, I just like showing off how much Virtualmin can do! 

 I don't know, but I do believe layout=fs + Listescape is more sensible default for the sanity of end users, especially if Maildir continues to be the default. Now switching to other mailbox formats is another story, which I have seen it be thrown around as being add as well to support. MDBox etc. 

Supporting additional mailbox format  will require a reworking of Usermin Read mail as well, and likely several factors higher than to support layout=fs

**Comment by abclution** [comment]
> Also, please again read my first comment regarding the Usermin -> Read Email -> Connect to IMAP server ALSO not working, which this should probably work regardless as well since it is not related to the .layout=fs settings.

Regarding this, IMAP from Usermin is now working for me. I don't know if this was fixed, or something janky on my server cleared up. Seems to work well now and have switched to only using IMAP for Usermin.

Which brings me to another small issue. With  layout=fs imap folders are not prepended with a . (dot) They are full folder names, and the default folders Virtuamin creates are regular maildir style with the prepended .  (dot)

Having these dot.folders created end up showing up in a weird way using IMAP clients and I need to get rid of them.

No problem, I just setup dovecot (see pasted config below) to create / subscribe to the correct folder names at first login and disable Virtualmins creation of the default folders, as seen here. Please 

![image](https://user-images.githubusercontent.com/10130237/94870084-5b8fa480-044f-11eb-9967-7cee254e3eae.png)
![image](https://user-images.githubusercontent.com/10130237/94870093-634f4900-044f-11eb-8de7-06ad89823a0d.png)
![image](https://user-images.githubusercontent.com/10130237/94870166-8d087000-044f-11eb-8ef7-ec0967b93632.png)

Great!  No problem here. These default folders no longer exist for new users. 

But wait a .spam folder is still being created in the Maildir... Hmm must dig some more. Ah there it is.
![image](https://user-images.githubusercontent.com/10130237/94870322-e375ae80-044f-11eb-9a29-20b486e2b772.png)

**Unfortunately, this doesn't prevent the .spam folder from being created on user (email account) creation. 

Somewhere else during user creation process, a .spam folder is being created, and it is not attached to any of the previous options. Clues?**

**Bonus**

My /etc/dovecot/conf.d/15-mailboxes.conf suitable for varying clients folder particularities to show a unified IMAP folder structure.  ( its for maildir:layout=fs but if you edit the separator should work for regular maildir as well.) 

```

namespace inbox {
  type = private
  separator = /
  inbox = yes

# Drafts
mailbox Drafts {
    special_use = \Drafts
    auto = subscribe
  }
# Junk Mail - Spam
  mailbox Junk {
    special_use = \Junk
    auto = no
  }

  mailbox spam {
    special_use = \Junk
    auto = no
  }

  mailbox Spam {
    special_use = \Junk
    auto = subscribe
  }
# Trash
  mailbox Trash {
    special_use = \Trash
    auto = subscribe
  }
# Sent messages Boxes
  mailbox Sent {
    special_use = \Sent
    auto = subscribe
  }

  mailbox "Sent Mail" {
    special_use = \Sent
    auto = no
  }

  mailbox "Sent Messages" {
    special_use = \Sent
    auto = no
  }
# Archived messages
# Archive
  mailbox Archive {
    special_use = \Archive
    auto = no
  }

  mailbox "Archives" {
    special_use = \Archive
    auto = subscribe
  }

# If you have a virtual "All messages" mailbox:
  mailbox "All Mail" {
    special_use = \All
    auto = subscribe
    comment = All mail sent & recived.
  }

 # If you have a virtual "Flagged" mailbox:
  mailbox Flagged {
    special_use = \Flagged
    auto = subscribe
    comment = All flagged messages.
  }



}



```

**Comment by abclution** [comment]
I am going to close this issue because IMAP now seems to work properly with  maildir:layout=fs.  Not sure where this was fixed so I cannot reference it, but I will start a new issue with my previous post.
