### ISSUE TITLE
Apache: Reload config after editing "Services/Configure Website" page

### ISSUE THREAD

**Issue by iliarostovtsev** [virtualmin/virtualmin-gpl#195]
Jamie, hi!

What is the correct way of restarting Apache internally (in code), after options were changed, like in **Directory Indexing** or any other. At the moment, after editing those pages, new configuration is not applied automatically, and requires manual restart. You can test it when changing _DirectoryIndex_ option.

**Comment by jcameron** [comment]
If you want an immediate re-read of the config, call `&apache::restart_apache()`

In Virtualmin, it's best to use `&register_post_action(\&restart_apache);` which registers a callback to be run at the end of the current script.

**Comment by iliarostovtsev** [comment]
Okay, great. Thanks, Jamie - here is the [patch](https://github.com/webmin/webmin/commit/399ded7829473aebe1dde2bfbca676b1bf5c8319).  I was just double checking, as I was baffled that it wasn't part of the current code already.

**Comment by jcameron** [comment]
That's by design - the apache module intentionally doesn't reload configs automatically. The user has to click the apply config button.

**Comment by iliarostovtsev** [comment]
So, that is better to unroll?

**Comment by iliarostovtsev** [comment]
Unrolled.
