### ISSUE TITLE
Update AWS S3 request signatures -- ALL new buckets are now incompatible with Virtualmin.

### ISSUE THREAD

**Issue by native-it** [virtualmin/virtualmin-gpl#198]
(My apologies if you prefer dealing with this sort of thing on the Virtualmin forums)

Per a statement from AWS made in June 2019, as a follow-up to the announcement in June 2018 that the Signature v2 (SigV2) method of signing S3 requests is being deprecated--

> Any new buckets created after June 24, 2020 will not support SigV2 signed requests, although existing buckets will continue to support SigV2 while we work with customers to move off this older request signing method.

This has been a long time coming. I realize that maintaining development for Virtualmin must be a ferocious effort given its complexity and generous feature-set. Before I say anything else I would very much like to *THANK YOU* for that. I've been using Virtualmin to manage my webservers for the last decade and I would go back to CLI-only administration before I would use any other frontend system manager. 

But given how vital solid backup mechanisms are for every sysadmin using it I would like to suggest that this receive a higher priority for an update soon. It doesn't appear to have been changed or updated in at least 5-6 years now. Like many others, I am currently using a combination of in-built scheduled backups and rclone to transfer everything to my S3 storage, and it is more or less reliable. However, if that's going to be the only real way to maintain cloud backups moving forward, then it would honestly be better to remove the largely defunct S3 components altogether and put some recommended alternatives in the documentation. I am not a software developer, so I'm relatively ignorant as to what kind of time and effort would be involved in updating the S3 signatures to V4. I did see there are several frameworks for Perl and a newer CPAN module available for it.

The rclone workaround is fairly effective, so I suppose this isn't critical for me personally right now, but with every new release for the last year or more I eagerly scan the changelog hoping to see this addressed. I resisted formally opening an issue for a long time, but it looks like after this summer this problem stands to become much larger now that any new bucket created will be fundamentally incompatible with Virtualmin's backup module.

Thanks again for everything that you have done to make Virtualmin, and to any other developers who contribute. I wish I'd spent more time on programming as a teenager...

**Comment by native-it** [comment]
@jcameron Thanks for the info and perspective. I will absolutely start testing the AWS CLI tool on  my dev server immediately. While messing with Perl code is beyond my abilities, I'm adept enough with CLI on Debian that I'm confident I'll be able to make this work, and I'll gladly share the solution with others here and/or on the Virtualmin forums.

@chris001 I am on Debian, thanks very much for the command!

I'll post back soon with an update on how this goes. Thanks again!

**Comment by tr3pan** [comment]
@chris001 AWS doesn't recomment using the awscli package from distrost, because it might be outdated. I don't know how much is the burden to maintain the S3 client in virtualmin, but it is definitely faster than the cli if you have to push a lot of files. For more information how to install the aws cli clien check the [aws docs](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html)

**Comment by jcameron** [comment]
It's actually quite a lot of work to maintain the S3 client in Virtualmin, because the API often changes. So we want to get out of this business of keeping our own implementation, and eventually will deprecate it in favor of recommending that users install the `aws` command.

**Comment by native-it** [comment]
Sorry for not closing this sooner. I resolved my own needs pretty handily using a very simple rclone command after backups complete with my Backblaze B2. An S3-compatible section in Virtualmin's backup module would be nice just to have an elegant built-in solution, but I agree it isn't worth the headache for now.
