### ISSUE TITLE
Spelling errors on Virtualmin > Server Configuration > SSL Certificate

### ISSUE THREAD

**Issue by c-prompt** [virtualmin/virtualmin-gpl#202]
I believe you mean "cer**t**ificate."

```
Webmin domain cerificate enabled?
Usermin domain cerificate enabled?
Dovecot domain cerificate enabled?
Postfix IP cerificate enabled?
```

**Comment by altmas5** [comment]
I confirm, using webmin 1.955, virtualmin 6.12, under "Service Certificates" tab
![Screenshot at 2020-09-09 19-43-42](https://user-images.githubusercontent.com/1054618/92671972-dcd29c00-f2d4-11ea-8427-cab164629c6a.png)

**Comment by swelljoe** [comment]
Fixed by @altmas5 PR.
