### ISSUE TITLE
Buggy group name behavior when importing a sub-server converted to a parent (I think), breaking PHP-FPM

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-gpl#204]
From this thread: https://forum.virtualmin.com/t/virtualmin-php-fpm-rewriting-group-after-switch/107395

Note the only really relevant bit is at the very end of the post where they point out that the ugroup doesn't match the user name (I guess it keeps its old parent group), and that's how things are getting botched in PHP-FPM.

Seems like it's specific to sub-server backups imported as parent servers.

**Comment by jcameron** [comment]
Thanks - this is fixed in https://github.com/virtualmin/virtualmin-gpl/commit/23e27695af88453ab54c6d5a4e188c089b837eb3

**Comment by lexo-mfleuti** [comment]
We experience the same issue after every Virtualmin upgarde. We just upgraded from 6.11 Pro to 6.12 Pro and PHP-FPM was down again. The hosts causing the problems are all hosts, which we once moved or changed the admin group name. For example: We once set-up a vHost as a subdomain. Then we converted the subdomain into a primary domain and moved it from /home/vHostname/domains/subdomainname to /home/newVHostname. This changed the path, username and group name. Now after every update the group-name in the PHP-FPM pool file is changed to the old (original) group name and PHP-FPM won't start anymore. We have to manually change group names in like 10 hosts after every systemupdate requiring us about 15 minutes and a 15 minutes downtime. It's quite annoying. Please check if this fix will also fix that issue.

**Comment by iliarostovtsev** [comment]
@lexo-mfleuti Give this patch a try, please https://github.com/virtualmin/virtualmin-gpl/commit/23e27695af88453ab54c6d5a4e188c089b837eb3

**Comment by lexo-mfleuti** [comment]
I just tested it by doing a "apt reinstall webmin-virtual-server". It's not working. The fpm pool files are bugged out again.

**Comment by swelljoe** [comment]
That's not what Ilia suggested you do. This patch is not in a release yet. If you want to try the fix, you need to apply the patch Ilia linked you to.
