### ISSUE TITLE
Reboot failed (Ubuntu 20.04 / LEMP)

### ISSUE THREAD

**Issue by malde11** [virtualmin/virtualmin-gpl#205]
Hi,
I have got a fresh install of virtualmin on ubuntu server 20.04 with a LEMP stack.
Now, if I try to reboot/restart with the webmin gui, then I can not login to virtualmin/webmin(no connection).
And I can not ssh to the server(no connection).

But I can access via vnc and if I check virtualmin/webmin  status they are running and the same for ssh.

Hope, someone can help me..

**Comment by jcameron** [comment]
Does it restart if you run /etc/webmin/start ?

**Comment by malde11** [comment]
> Does it restart if you run /etc/webmin/start ?

It says, it is already running. 
Here is a pic from webmin status..

![Bildschirmfoto 2020-09-21 um 00 27 20](https://user-images.githubusercontent.com/16993039/93723828-4dfe3300-fba2-11ea-87ba-3399927ca084.png)

**Comment by malde11** [comment]
I logged in via VNC and did "virtualmin check-config" and got the following:

**ERROR: Virtualmin could not work out the default IPv4 address for virtual servers on your system. You will need to update either the network interface for virtual addresses or default virtual server IP address fields on the module configuration page.**

That happends after reboot on a fresh install. Maby some miss configuration in the post install wizzard. But I do not know, what I did wrong. I guess something with the nameserver. But have no clue how to fix it.

**Comment by jcameron** [comment]
That message can be fixed by setting the correct IP to use on the Virtualmin Configuration page in the UI - however, it shouldn't stop you from accessing the Virtualmin UI as long as the system is on the network.

However, it looks like you're not actually online based on your report that SSH doesn't work either. Is this a VM, or a real machine?

**Comment by malde11** [comment]
hi,
it is a VPS (real machine) and it happens only after reboot, that i can not access via SSH or UI.
The virtualmin installation finished with no erros and I can login to the UI.

The machine should be online, cause I can access it via VNC.

I guess, that I am doing something wrong in the post installation wizzard. For example Hostname, DNS, NS or IP.

Thanks for your help.

**Comment by jcameron** [comment]
Can you post the files from the `/etc/netplan` directory on this system?

**Comment by malde11** [comment]
Same issue..

https://forum.virtualmin.com/t/virtual-interface-removed-after-reboot-on-ubuntu-20-04/107958/17

**Comment by iliarostovtsev** [comment]
@malde11 [Replied](https://forum.virtualmin.com/t/virtual-interface-removed-after-reboot-on-ubuntu-20-04/107958/18?u=ilia). You need to check init scripts setup by your server providers.
