### ISSUE TITLE
Backup to S3 fails when hundreds virtual servers are backed up when using S3 virtualmin client

### ISSUE THREAD

**Issue by tr3pan** [virtualmin/virtualmin-gpl#207]
I do backup to S3 on 1000+ virtual servers and each server is configured to have its own backup file. When the file is put to S3 the connection is closed on AWS side, but not on the script side. This results to TCP connection in CLOSE_WAIT state that is using file descriptor. When you do backup for multiple virtual servers it seems for every put file one file descriptor for TCP connection is taken. The default limit set by systemd is 1024. If you back up 100 sites, you won't notice it. Eventually you will notice the increased number of TCP connections in CLOSE_WAIT state. When the backup pocess fails Virtualmin shows the backup as failed, but it doesn't show what is the problem.

Since virtualmin is module for webmin, the backup process inherits the max open file limits from webmin miniserv process. systemd has option to set the max open file limit, but it works only for systemd unit files. webmin is started using init script and the only way to set the limits now is in the init script. Which is bad to do it manually, because the change will be overwritten on the next package update.

As a workaround you set systemd to set the default max open files to 65536 in /etc/systemd/system.conf.

I tested with aws-cli v2 and the connections are properly closed.

**Comment by jcameron** [comment]
Thanks for reporting this. It's unusual though because I couldn't see any place in the current code where the connection to S3 is left open.

How large are the domain files you're backing up?

**Comment by tr3pan** [comment]
They are small like 100-200kb. It is just the apache configuration and the SSL certificate.

Just in comparison with the aws cli, it seems the backup is faster using the internal S3 client. It is understandable, because you don't have to load python interpreter and modules every time to send a file.

**Comment by jcameron** [comment]
OK, I found the bug that causes this - it will be fixed in the next Virtualmin release.
