### ISSUE TITLE
Bug? Server Template -> BIND DNS Domain -> Additional SPF IPs and hostnames -> Adding IPV6 range / subnet incorrectly added as a: (address) spf instead of ip6:

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#208]
When adding records in the server template -> bind dns domain -> Additional SPF IPs and hostnames

If I add an ipv6 range, such as 6c01:5e2:340:7252::/64  to " Additional SPF IPs and hostnames" ... when creating a domain, and checking the generated spf record, it is created as

a: form used for dns addresses
`a:6c01:5e2:340:7252::/64` 

instead of the correct form, ip4 /  ip6 form
`ip6:6c01:5e2:340:7252::/64` 

This leads to a broken spf record, and is surely not intended.
As far as I know, it is ok to indicate a range of ips / subnet and this is a bug.

Trying to override manually by entering ip6:6c01:5e2:340:7252::/64 in the form, generates a spf record looking like this:

`a:ip6:6c01:5e2:340:7252::/64`  

:P

**Comment by jcameron** [comment]
Thanks, we'll fix this in the next release.

https://github.com/virtualmin/virtualmin-gpl/commit/96321293ff945ae5d15130bff1da64ac14e06559

**Comment by abclution** [comment]
Just tested this and works for me!
