### ISSUE TITLE
Bug/Question - Mystery creation of .spam folder, Virtualmin Configuration -> Actions upon server & user creation + Spam filtering options don't cover all created Maildir folders at creation time. 

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#212]
Virtualmin is creating outside of the settings / not obeying all settings for newly created Maildir folders

 With  layout=fs imap folders are not prepended with a . (dot) They are full folder names, and the default folders Virtuamin creates are regular maildir style with the prepended .  (dot)

Having these dot.folders created end up showing up in a weird way using IMAP clients and I need to get rid of them.

No problem, I just setup dovecot (see pasted config below) to create / subscribe to the correct folder names at first login and disable Virtualmins creation of the default folders, as seen here. 

![image](https://user-images.githubusercontent.com/10130237/94870084-5b8fa480-044f-11eb-9967-7cee254e3eae.png)
![image](https://user-images.githubusercontent.com/10130237/94870093-634f4900-044f-11eb-8de7-06ad89823a0d.png)
![image](https://user-images.githubusercontent.com/10130237/94870166-8d087000-044f-11eb-8ef7-ec0967b93632.png)

Great!  No problem here. These default folders no longer exist for new users. 

But wait a .spam folder is still being created in the Maildir... Hmm must dig some more. Ah there it is.
![image](https://user-images.githubusercontent.com/10130237/94870322-e375ae80-044f-11eb-9a29-20b486e2b772.png)

**Unfortunately, changing this doesn't prevent the .spam folder from being created on user (email account) creation, likely it just changes the end delivery of spam, not during creation time..** 

**Somewhere else during user creation process, a .spam folder is being created, and it is not attached to any of the previous options. Clues?**

**Bonus**

My /etc/dovecot/conf.d/15-mailboxes.conf suitable for varying clients folder particularities to show a unified IMAP folder structure.  ( its for maildir:layout=fs but if you edit the separator should work for regular maildir as well.) 

```

namespace inbox {
  type = private
  separator = /
  inbox = yes

# Drafts
mailbox Drafts {
    special_use = \Drafts
    auto = subscribe
  }
# Junk Mail - Spam
  mailbox Junk {
    special_use = \Junk
    auto = no
  }

  mailbox spam {
    special_use = \Junk
    auto = no
  }

  mailbox Spam {
    special_use = \Junk
    auto = subscribe
  }
# Trash
  mailbox Trash {
    special_use = \Trash
    auto = subscribe
  }
# Sent messages Boxes
  mailbox Sent {
    special_use = \Sent
    auto = subscribe
  }

  mailbox "Sent Mail" {
    special_use = \Sent
    auto = no
  }

  mailbox "Sent Messages" {
    special_use = \Sent
    auto = no
  }
# Archived messages
# Archive
  mailbox Archive {
    special_use = \Archive
    auto = no
  }

  mailbox "Archives" {
    special_use = \Archive
    auto = subscribe
  }

# If you have a virtual "All messages" mailbox:
  mailbox "All Mail" {
    special_use = \All
    auto = subscribe
    comment = All mail sent & recived.
  }

 # If you have a virtual "Flagged" mailbox:
  mailbox Flagged {
    special_use = \Flagged
    auto = subscribe
    comment = All flagged messages.
  }



}



```

_Originally posted by @abclution in https://github.com/virtualmin/virtualmin-gpl/issues/194#issuecomment-702436750_

**Comment by abclution** [comment]
Ok, so strangely enough, this issue cleared up.. I don't really have an easy way to confirm / understand the results.

The mystery .spam folders were being created on new users both for existing domains, as well as newly added domains + users.
On a whim I went into a specific domains Spam and Virus Delivery and changed / toggled the Delivery Destinations to another options, and suddenly the mystery .spam folder was fixed server wide, including on other domain + users.

Still testing but seems like some sort of weird edge case with mixed settings? 
If I figure something out I will update.

**Comment by jcameron** [comment]
Virtualmin will attempt to pre-create spam and virus folders based on the default delivery destination, so that could be the cause of the issue you were seeing.

What were the destinations set to previously?

**Comment by abclution** [comment]
Yeah that is what I figured, the default which was on my system

![image](https://user-images.githubusercontent.com/10130237/95008294-3b174400-0621-11eb-81c8-6229088233a8.png)

I changed it to 
![image](https://user-images.githubusercontent.com/10130237/95008302-479b9c80-0621-11eb-8eeb-e4edb9623927.png)

But it still kept creating the .spam folder.
Then I changed it to 
![image](https://user-images.githubusercontent.com/10130237/95008309-5a15d600-0621-11eb-9e4a-31d7006acfb3.png)

And it wouldnt create the Spam folder, and was still creating the .spam folder

Eventually like I said in the original post, I went into a specific domains settings, did a similar toggle there, and suddenly all subsequent users / domains were following the global configuration I had set. Very odd.

Its working now tho, although I  was scratching my head for quite a few hours.

**Comment by abclution** [comment]
While on the subject of mail, this option:

![image](https://user-images.githubusercontent.com/10130237/95008396-474fd100-0622-11eb-855b-096225bd8ea8.png)

I have never actually found the "Search Mail Logs page"

![image](https://user-images.githubusercontent.com/10130237/95008419-6d757100-0622-11eb-9163-f995e568b418.png)


I am 99.9% of the time logged in as a master admin, so maybe that is why I dont see it?

**Comment by jcameron** [comment]
It should appear under Logs and Reports, assuming you are running Virtualmin Pro and have a domain with email selected.

**Comment by abclution** [comment]
> It should appear under Logs and Reports, assuming you are running Virtualmin Pro and have a domain with email selected.

Ok, well there's my problem.
Didn't realize mail logs were a pro feature. 
I'm a terminal monkey anyways. 
Thank you
