### ISSUE TITLE
virtualmin set-mysql-pass is not working on centos 8/mariadb 10.3

### ISSUE THREAD

**Issue by nicutor** [virtualmin/virtualmin-gpl#213]
Hi,

Please check and fix this. Thank you!

```
virtualmin set-mysql-pass --user root --pass *****
```

```
Shutting down MySQL server ..
.. done

Starting MySQL server with authentication disabled ..
.. done

Changing the password for user root ..
.. password change failed : mysql::execute_sql_logged failed : SQL alter user 'root'@'127.0.0.1' identified by '*****' failed : The MariaDB server is running with the --skip-grant-tables option so it cannot execute this statement



Stopping the MySQL server with authentication disabled ..
.. done

Starting up MySQL server ..
.. done

ERROR: .. password change failed : mysql::execute_sql_logged failed : SQL <tt>alter user &#39;root&#39;@&#39;127.0.0.1&#39; identified by &#39;*****&#39;</tt> failed : <tt>The MariaDB server is running with the --skip-grant-tables option so it cannot execute this statement</tt>
```

**Comment by jcameron** [comment]
@iliarostovtsev is this something that your recent changes already fixed?

**Comment by iliarostovtsev** [comment]
> is this something that your recent changes already fixed?

No, this is new, unrelated issue. I have spent considerable amount of time today testing and fixing it, eventually making a patch https://github.com/virtualmin/virtualmin-gpl/commit/1f34cb4994b2416a0546699856b518fbac35d606 that solves all issues on all MariaDB/MySQL versions.

@nicutor You are welcome to try the patch.

**Note:** Related patch https://github.com/webmin/webmin/commit/02e8ada0059321f6ae5cee4dac1e27b91b2e5e5e

**Comment by nicutor** [comment]
Thank you @iliarostovtsev 

I will try it and let you know about. 

Please check this comment too: https://github.com/virtualmin/virtualmin-gpl/commit/1f34cb4994b2416a0546699856b518fbac35d606#r42976383

**Comment by iliarostovtsev** [comment]
There were [more final fixes](https://github.com/virtualmin/virtualmin-gpl/commit/97e9dfde227fd349153a4c60975ecf660ee9420) to make it right to change MySQL root password when Webmin cannot connect to it. It really works now.
