### ISSUE TITLE
Restored domains have broken php-fpm config if php version has changed

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-gpl#215]
The restored domain apps don't work, and there is reportedly no way to make them work, because the php-fpm option is hidden. So, users are suck in an unfixable state (without config file spelunking).

https://forum.virtualmin.com/t/php-fpm-option-not-available-for-restored-servers/107408

Copy-pasting the relevant bit:

In my case the fresh install was equipped with PHP 7.4 while the old system was running PHP 7.2.
The restored vserver had in it’s config file php_fpm_version=7.2 which was not found on the new system. I corrected it to php_fpm_version=7.4, saved it and went to Virtualmin > Website Options and the option to select PHP-FPM appeared.

**Comment by jcameron** [comment]
Ok I see the cause of this - I'll fix it in the next Virtualmin release.
