### ISSUE TITLE
Rant, but not at Virtualmin... Using "user@domain.com" format for everything and the "Create extra Unix user on Postfix systems when using user@domain format?"

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#216]
First off, I am fully aware, this is not a Virtualmin "issue", in fact, the devs have handsomely worked around Postfix being retarded about usernames with @ in them.

I made it a goal to figure out why if **deselecting** the "Create extra Unix user on Postfix systems when using user@domain format?" **Postfix fails com-fucking-letely to find the user account**, even though its right in front of its face and in fact in the logs and debug tools, show that it finds it as well

```
# For LDAP debug looking up the user during the mail reciving process
postmap -q noextraaccountuser@domain.tld ldap:/etc/postfix/virtual_alias_maps.1.ldap.conf

noextraaccountuser\@domain.tld

# For text config, debug looking up the user during the mail reciving process
postmap -q noextraaccountuser@domain.tld hash:/etc/postfix/virtual

noextraaccountuser\@domain.tld
```

Even the Postfix logs show it finds it but it does nothing with it and the final error message when trying to deliver to these user@domain.com accounts without an extra Unix user account **is a stupendous fart of an error...**

`User unknown in virtual alias table 
`

I effn hate seeing duplicate users in my userlist, even if they are just aliases for the original. It also clutters the postfix virtual alias/domains (both ldap and configs) and just seems meh. 

Anyways after much searching and gnashing of teeth I stumbled upon the simple one line answer with apparently a complicated backstory.

In /etc/postfix/main.cf add this line: (Debian 10, ymmv)
```

resolve_dequoted_address = no
# Default is, YES

```

From postfix man pages.

resolve_dequoted_address (default: yes)

By default, the Postfix address resolver does not quote the address localpart as per RFC 822, so that additional @ or % or ! operators remain visible. This behavior is safe but **it is also technically incorrect.**

If you specify "resolve_dequoted_address = no", then the Postfix resolver will not know about additional @ etc. operators in the address localpart. This opens opportunities for obscure mail relay attacks with user@domain@domain addresses when Postfix provides backup MX service for Sendmail systems.

**If there is a better way to resolve/ use the user@domain.com format everywhere WITHOUT have extra user accounts all over the place, I am all eyes/ears.**

Ref:  http://postfix.1071664.n5.nabble.com/Erroneous-handling-of-addresses-containing-a-character-td90016.html

**Comment by chris001** [comment]
Excellent discovery @abclution !  You're right. it's massively crucial to maintain **consistent canonical naming** of usernames/accounts, across all of the applications which Virtualmin manages, the popular mainstays `Postfix`, `Dovecot`, `Linux/Unix OS`, `Apache/Nginx`, `DKIM`, `LetsEncrypt`, etc... Without that, you get a system that breaks far too easily and is too difficult to maintain over time.

**Comment by swelljoe** [comment]
After reading that thread from the postfix list I'm still not sure I understand the implications of this option and whether it is safe to use generally. Sometimes the postfix list is frustratingly opaque.

**Comment by jcameron** [comment]
If that `resolve_dequoted_address` does work, I would be so happy, because the code in Virtualmin to maintain extra users without the @  is a real pain!

**Comment by abclution** [comment]
To be quite honest, I have searched for the root cause of this issue on and off since, I think about 2009? *eek*

Searching for "mail doesn't deliver to local  with @ in username" and variants of bring up a bunch of wild goose chases regarding mydomain, myorigin and miscellaneous options.

@chris001 I'm still testing but so far so good and I literally jumped for joy when that first mail was delivered to the final account without the extra Unix user account.

Like @swelljoe said, and much nicer than I would have described them, the postfix lists are so obtuse and full of snark that I too still am still deciphering what implications are.

Because this setting obviously changes how the destination address is read and processed, the first place I checked was the 

`recipient_delimiter = +^#`

and I found no problems there. Even with various, multiple delimiters, mail was delivered properly to each sole user@domain.tld account as well as to my other extra unix accounts accounts and their aliased via delimiter iterations. 

I am trying to remember years ago that you could route a mail address via specific server by using multiple user@domain.com@routethrough.here  but I can not remember. This may be related to the warning. 

@jcameron  I honestly didn't realize you didn't know what was causing the issue, my clue from you "On some systems this is not needed", was enough for me to realize there *IS* a solution to use Postfix without extra accounts and I am stubborn as hell when I want to solve something.

**Comment by jcameron** [comment]
I'm actually not sure why I even added that option to not create these extra users, given that they seem to be mandatory for Postfix delivery to work!

**Comment by abclution** [comment]
Anyone else got a chance to test this out?

**Comment by iliajie** [comment]
Yes, I did just test it, and it works like charm, starting from CentOS 7 up to Ubuntu 22.04 (i.e. various Postfix versions). 

Virtualmin doesn't configure Postfix to relay mail, so there should be no risk for abusing it in obscure mail relay attacks.

For anyone who wants to test it on the local network using `/etc/hosts` for name resolution just add to the older Postfix (CentOS 7) this option `disable_dns_lookups = yes` and for all newer `smtp_dns_support_level = disabled`, then also add  `resolve_dequoted_address = no` (i.e. to `main.cf`), restart Postfix and try it.

I will add this change to `Virtualmin Config` for all new installs, to finally have no additional annoying accounts created for Postfix!

**Comment by jcameron** [comment]
Hang on, why is it necessary to set `disable_dns_lookups = yes` ? That seems like it could have other side effects?

**Comment by iliajie** [comment]
> Hang on, why is it necessary to set `disable_dns_lookups = yes` ? That seems like it could have other side effects?

Yes, correct, and we are _**not**_ adding it! I just mentioned it for running local tests _only_.

**Comment by jcameron** [comment]
Does `resolve_dequoted_address` have any other side effects?

**Comment by iliajie** [comment]
> Does `resolve_dequoted_address` have any other side effects?

It is described here:
https://www.postfix.org/postconf.5.html#resolve_dequoted_address

Do you see any possible side effects? I don't because we're not configuring open relay, and virtual map can only be edited by admins, or users in a limited way.

**Comment by jcameron** [comment]
OK, that seems safe. Maybe we could check for this option when deciding whether to create @-format usernames?

**Comment by iliajie** [comment]
Well, I wouldn't mind to have that option checked (or enabled automatically). Will you do it? I don't want it to hold off the new release. I'm just not at the computer right now.

**Comment by jcameron** [comment]
I'll do it, but maybe in a future release.

**Comment by iliajie** [comment]
Agreed!

**Comment by jcameron** [comment]
Ok, I've added code to not create an extra user if `resolve_dequoted_address` is set to `no`.
