### ISSUE TITLE
Usermin Read Mail cannot / does not display UTF8 glyphs (in names of folders) in folder listing, nor can it create them.

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#217]
This is using Usermin Read Mail in IMAP mode.

Ok, this is exact same problem here: https://forum.virtualmin.com/t/french-language-problems-in-usermin/104253/12

Same issue with IMAP

---------------------------------------------------
Have some oddly named folders, "♻♻♻-grrrr"  for example.

In usermin, in the folders display, it displays as such

&JnsmeyZ7- grrr
![image](https://user-images.githubusercontent.com/10130237/95732636-aef0c680-0c89-11eb-81d8-49e02918ed1d.png)

I can access the folder, but folder name display is incorrect.

Other Usermin error messages display correctly the glyph however
*Please ignore the content on this error (it is because I am accessing the root of a namespace, it is not a real folder), only pay attention to the glyph*

![image](https://user-images.githubusercontent.com/10130237/95732619-a6988b80-0c89-11eb-9159-e6f20af3adcd.png)

Additionally creating folders with glyphs which Dovecot supports, also give an Usermin/Webmin error.

"Folder names can only contain letters, numbers, spaces and the characters dot, dash and underscore"

Additionally one time while copy pasting into the "Create New Folder" field, this error occurred one time.
The field was blank but I had possibly pasted binary data there which lit up the create button and had accidentally pressed it thinking my text had pasted.

![image](https://user-images.githubusercontent.com/10130237/95732894-068f3200-0c8a-11eb-964c-9e063e6ec689.png)

I was unable to reproduce.

------------------------------------------------
Ok, in case it wasn't obvious, Usermin is not translating the modified UTF-7 (Dovecot default) to the correct symbols.
No problem, I will switch Dovecot to UTF8 backend storage.

ls of of some of the folders with UTF-7 + UTF8

![image](https://user-images.githubusercontent.com/10130237/95738156-72c16400-0c91-11eb-83b2-1d1d8e97d368.png)

Same problem.

![image](https://user-images.githubusercontent.com/10130237/95738218-8a98e800-0c91-11eb-9aa8-1e4987871fcc.png)

The funny thing is Usermin displays all my spam mails with their silly glyphs in the email subject and body.. .

![image](https://user-images.githubusercontent.com/10130237/95738309-af8d5b00-0c91-11eb-862c-77a772e3ed18.png)

Anyways, not sure if this is a known issue or what. 
Roundcube displays the UTF-7 glyphs when using the UTF7 backed store correctly, (Not pictured) 

However when switching Dovecot to UTF8 the previously created UTF7  folders appear wrongly, as can be expected..
Roundcube also displays the UTF-8  characters correctly when using the UTF8 backed store.

![image](https://user-images.githubusercontent.com/10130237/95738566-1e6ab400-0c92-11eb-89be-e2c4a9584785.png)

**Comment by iliarostovtsev** [comment]
This should be fixed with the latest Usermin 1.820.
