### ISSUE TITLE
PHP8

### ISSUE THREAD

**Issue by 1ucay** [virtualmin/virtualmin-gpl#222]
Hi, I just installed PHP 8.0 - fpm and not detecting.
https://blog.remirepo.net/post/2020/04/10/PHP-8.0-as-Software-Collection

Loaded: loaded (/usr/lib/systemd/system/php80-php-fpm.service; enabled; vendor preset: disabled)
Active: active (running) since Thu 2020-10-22 21:42:30 CEST; 18min ago

Also I tried edit virtual-server-lib.pl 
@all_possible_php_versions = (5, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9,
		      "7.0", 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8, 8.0);

and php-lib.pl
foreach my $pname ("php-fpm", "php5-fpm", "php7-fpm", "php8-fpm", "php80-fpm",

not luck.
Thank you

**Comment by 1ucay** [comment]
Well, now it works with
@all_possible_php_versions = (5, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9,
		      "7.0", 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8, 8.0, **80**);

The following PHP versions are available : 7.4.11 (/bin/php-cgi), 8.0.0 (/bin/php80-cgi)

The following PHP execution modes are available : fpm

The following PHP-FPM versions are available on this system : 7.4.11 (php-fpm) 8.0.0~rc2 (php80-php-fpm)

**Comment by chris001** [comment]
Make pull request for these changes, if you can.

**Comment by jcameron** [comment]
Did you really need to add "80" and "8" as well as "8.0" ?

**Comment by iliarostovtsev** [comment]
> I just installed PHP 8.0 - fpm and not detecting.

What is the exact package name for PHP 8.0? Is this _-rc_ version?

**Comment by marclaporte** [comment]
@1ucay Can you retest latest stable version (Virtualmin 7.5)?

Thanks!
