### ISSUE TITLE
missing text in German translations

### ISSUE THREAD

**Issue by HonkXL** [virtualmin/virtualmin-gpl#229]
As I am very unhappy with the German translation, I am trying to fix this issues. I did some correctings in the last days, but I am missing some texts in the de and de.auto file:

Create Virtual Server
File Manager

This are just two examples. How can I add the missing texts to the de file in the correct way?

**Comment by iliarostovtsev** [comment]
> This are just two examples. How can I add the missing texts to the de file in the correct way?

First of all make sure that _de.auto_ files are used by enabling _Include machine translations_ option:

![image](https://user-images.githubusercontent.com/4426533/98851083-cc6ea700-2466-11eb-91fc-a32cbc02d4c8.png)

Later, if you still see text in English, reset cache:

![image](https://user-images.githubusercontent.com/4426533/98851192-f9bb5500-2466-11eb-84e8-2e318758a838.png)

All strings that were translated by human (you) must be moved from _de.auto_ to _de_ file (removed from _de.auto_).

> As I am very unhappy with the German translation,

Are you unhappy with default translation (*de* file) or automated translation (_de.auto_ file)?

> I am trying to fix this issues.

Thank you very much for your help.

**Comment by HonkXL** [comment]
Thanks for explanation. Works, so this issue can be closed.
