### ISSUE TITLE
Create a git repository fails if the `git` directory was somehow deleted

### ISSUE THREAD

**Issue by alanmels** [virtualmin/virtualmin-gpl#232]
After hitting https://github.com/virtualmin/virtualmin-gpl/issues/231, I've manually deleted the `git` directory, but then failed to create any new repositories for the same websites. Unfortunately, Virtualmin's UI fails silently without giving any error messages. Only after re-instating the deleted directory I was able to create another repository. 

I believe UI should give some context to user of what's going on behind the scenes.

**Comment by alanmels** [comment]
.. or automatically re-create the missing directory.

**Comment by jcameron** [comment]
Sure, we can re-create the missing directory. I'll do that in the next release of the plugin..
