### ISSUE TITLE
Best Virtualmin practices for production, staging & development environments

### ISSUE THREAD

**Issue by alanmels** [virtualmin/virtualmin-gpl#234]
Unfortunately, searching for "Production, Staging & Development environments on Virtualmin" gives just couple discussions and both do not provide clarification to the question in subject:

https://www.virtualmin.com/node/38902
https://www.virtualmin.com/node/11341

I really hoped to use Virtualmin Git Repositories to create different environments for a single website, however it's not even clear how to make it work with the main website itself (as described in https://github.com/virtualmin/virtualmin-gpl/issues/233) let alone creating additional environments. 

I would appreciate if Virtualmin gurus shared their recommendations for best practices for creating and maintaining the production, staging & development environments.

**Comment by iliarostovtsev** [comment]
Hi, Alan.

This is an issue tracker, not QA, thus you should rather ask your question on [Virtualmin Forum](https://forum.virtualmin.com/).
