### ISSUE TITLE
PHP-FPM and chroot = Timezone database is corrupt - this should *never* happen!

### ISSUE THREAD

**Issue by Ryvix** [virtualmin/virtualmin-gpl#240]
Hi there,

I've been getting into Virtualmin again and just setup some new servers. I noticed there is a chroot option in it now. I thought I should test it out and ran into this issue so thought I should report it. I hope this is the right spot to report it.

I enabled chroot on users in Virtualmin and set the server to use PHP-FPM but then the site gets errors like this:

`Got error 'PHP message: PHP Warning:  date_create(): Invalid date.timezone value 'America/Toronto', we selected the timezone 'UTC' for now.
PHP message: PHP Fatal error:  date_create(): Timezone database is corrupt - this should *never* happen!`

I think that the timezone data isn't copied into the chroot properly so PHP can't access it but I'm not 100% sure the best way to fix it.

Is chroot more secure now? I noticed you didn't add it before because it added no additional security but since I see it there I wonder what's changed?

Thanks!

Edit: I found this which may be useful: http://ivanbayan.com/index.php/2013/06/26/how-to-fix-timezone-database-is-corrupt-this-should-never-happen/

**Comment by swelljoe** [comment]
You'll need to modify your chroot to include the time zone database in your chroot. I don't know about the security implications of that, as I've never researched it.

> Is chroot more secure now? I noticed you didn't add it before because it added no additional security but since I see it there I wonder what's changed?

It is not *insecure*, as it uses kernel capabilities to limit the process that sets it up to only the necessary access. I discussed it at length when adding the feature, though I'm not able to dig up a link to that now. This does resolve the problem I discussed in the past about chroot opening up security concerns while not really providing much extra protection. It still does not provide significant security benefits...but it does not provide additional attack vectors. An attacker probably cannot consider a poorly implemented chroot an opportunity to escalate to root.

So, it is also not *more secure*, generally speaking (though maybe in some rare circumstances it might provide an additional layer of protection). It was something a lot of people wanted, and people were treating it as an important "feature" that cPanel had that Virtualmin did not and I figured we might be losing sales over it. So, we added it.

I still don't recommend it. I don't *not* recommend it, either, but it's asking for more work for dubious benefit.

**Comment by Ryvix** [comment]
Thank you for taking the time to write back!

That makes sense. I only wanted to keep someone who doesn't know much in their own little area and that seems to work ok for it. I'm glad it's not insecure though. Awesome work! Things have been coming along quite nicely since I last setup Virtualmin. Thank you for all your hard work!

I was able to do what I mentioned in that link I posted afterwards to get it working actually. I had tried copying things to the chroot but it wouldn't work right for some reason or another. I tried to symlink it and copy them but maybe I was doing something wrong so figured I'd try that and that technique worked ok for the time being.

I'm on Ubuntu 20.04 if that matters.

**Comment by swelljoe** [comment]
You should configure files to be put in the chroot in the jailkit config files. There is also [jk_cp](https://olivier.sessink.nl/jailkit/jk_cp.8.html) for copying into existing jails. There is a Webmin module for configuring jailkit config files, as well. We use jailkit for the behind the scenes stuff, which is documented here: https://olivier.sessink.nl/jailkit/

**Comment by pixel-paul** [comment]
I've encountered this exact issue on a fresh install of CentOS 8 with Virtualmin. Having not seen this feature before I was confused by it, especially as I had to manually copy the files for zoneinfo over to the chroot folder: 

`/home/chroot/1635798169196707/usr/share/zoneinfo `

to get the Virtualmin virtual server to work.

Might this be a bug?

**Comment by Ryvix** [comment]
I was able to make it work with the technique they mentioned on here: http://ivanbayan.com/index.php/2013/06/26/how-to-fix-timezone-database-is-corrupt-this-should-never-happen/

I just had to update it for my system.

Virtualmin doesn't seem to copy the zoneinfo stuff by default.

I also noticed when messing around in the jailkit files and in the Jailkit Jail Manager module which links to those that there is actually another entry there which specifies the /etc/localtime symlink which doesn't copy either. So I think something is up with symlinks somewhere.

I noticed that localtime symlink doesn't copy as well or any symlinks that I made in the /etc/skel folder either.

I tried adding a new entry for zoneinfo stuff but for some reason I couldn't get it to work right either.

**Comment by jcameron** [comment]
It looks like there is an option in the jailkit config to copy /etc/localtime, but Virtualmin doesn't use it by default. We'll fix that ..

**Comment by jbd7** [comment]
@jcameron FYI I just got the same "_Timezone database is corrupt - this should *never* happen!_" error after changing the PHP version of the virtual server from FCGI to FPM (on Virtualmin 6.17-gpl)
The culprit PHP line was         `$timestamp = date('M j H:i:s');`

I used the JK module to check in Webmin, and realized that only `/etc/localtime` was copied into the jail. Once I added another line, `/usr/share/zoneinfo`, the Apache server stopped erroring.

**Comment by jcameron** [comment]
Thanks for pointing this out - I will have Virtualmin copy all of /usr/share/zoneinfo into the chroot in the next release.
