### ISSUE TITLE
Changing the `Selector for DKIM record name` does not have effect on the ` /etc/dkim-keytable` file

### ISSUE THREAD

**Issue by alanmels** [virtualmin/virtualmin-gpl#243]
On a CentOS server with Virtalmin the string `2019` was indicated as the `Selector for DKIM record name` and DKIM was passing fine. However, after changing the selector to `default` using Virtualmin UI, the sent e-mail failed passing DKIM. Restarting the `opendkim` service didn't have expected effect. 

Troubleshooting this revealed the `2019` string was still in the `/etc/dkim-keytable` file:

```
default	%:2019:/etc/opendkim/keys/default.private
```

Only manually changing the file's content to:

```
default	%:default:/etc/opendkim/keys/default.private
```

allowed the outgoing e-mails to start successfully passing DKIM.

Please make sure changing the selector via Virtualmin UI also makes necessary changes in the `/etc/dkim-keytable` file.

**Comment by jcameron** [comment]
Which CentOS version is this system running? The OpenDKIM version has changed on later releases..

**Comment by alanmels** [comment]
It's CentOS 7.x

**Comment by jcameron** [comment]
Thanks - this will be fixed in the next release.
