### ISSUE TITLE
Endlessly growing PATH in external hook script.

### ISSUE THREAD

**Issue by fortran77** [virtualmin/virtualmin-gpl#245]
Apparently Virutalmin adds a new component to its PATH in a loop, so the PATH grows endlessly. After a while, it looks like this:

<code>
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/bin:/usr/bin:/sbin: ( ... keeps on going many more times ...)
</code>

Observed in an external script configured to be called by Virtualmin as “Command to run after making changes to a server”.

Has done no harm, but presumably on a server with a very long time between restarts it will eat up some memory.

Webmin version = 1.962
Virtualmin version = 6.14 
OS = ubuntu 20.04 LTS.

**Comment by jcameron** [comment]
Thanks for pointing this out - we'll fix it in the next Webmin release.
