### ISSUE TITLE
End-user can stop atd process in Scheduled Commands module.

### ISSUE THREAD

**Issue by fortran77** [virtualmin/virtualmin-gpl#246]
End-user can stop atd process in Scheduled Commands module.

An end-user using Webmin => System => Scheduled Commands can only run jobs as himself, which means the module is enforcing security. However, it appears that any end-user can stop **atd** or set it to not restart on machine boot, and that allows denial of service.

Webmin version = 1.962
Virtualmin version = 6.14 
OS = ubuntu 20.04 LTS

**Comment by jcameron** [comment]
Thanks for finding this - it will be fixed in the next Webmin release.
