### ISSUE TITLE
Copy to... for certs still confuses people a lot.

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-gpl#247]
This comes up at least once a week, which means we need better UI.

The label "Copy to.." for certificates consistently makes people think two things, which are both wrong things for them to think:

1. That they must copy the certificate for each domain in order to use it for services that support multiple certificates via SNI (which is actually, and should be, automatic in those services that support SNI).
2. That they should copy the certificate for every domain. (Which is nonsensical based on how it actually works. It just switches and confuses the user.)

e.g. https://forum.virtualmin.com/t/sending-emails-but-not-receiving-emails/109174/4?u=joe

We have tooltips for these items, but they do not clear up the above two confusions.

So, we at least need new labels and tooltips for these options...though I don't know what exactly they should be.

Something like "Use this certificate by default for.." for the services that support SNI, maybe?

Tool tips definitely need to make it clear that it should be clicked *once* for the domain that they want to be the default for the named service, and that it does not effect name-based certificate selection for the services that support it. I can make a PR for this, if we agree on how it ought to be worded. I'm kinda drawing a blank on how to make this clear enough to where it doesn't confuse everyone who encounters it for the first time (even some people who I think of as Virtualmin experts don't understand this, so I know with 100% certainty that we're in the wrong).

**Comment by iliarostovtsev** [comment]
Joe, great suggestion!

I remember we discussed it in the past. I would suggest to get rid of those buttons all together and have it displayed all in one place, _*otherwise*_ we make it believe that it's somewhat else, a _*different*_ functionality.

I was prototyping for you a little bit and this is how **Service Certificate** page should look like:

![image](https://user-images.githubusercontent.com/4426533/106383539-c211d880-63d7-11eb-8beb-da6ccd9f061d.png)

**Comment by swelljoe** [comment]
This is almost there, but is still misleading in the case of "Yes, as default". It makes it sound like it will *always* be used...but if the service supporters SNI, it won't be for requests to domains that have a certificate.

**Comment by swelljoe** [comment]
Maybe the word "fallback" or similar should be in there. Or change wording from "all requests" to "all requests for domains that do not have a certificate".

Older postfix needs to get the same behavior as proftpd...i.e. no offer of yes to SNI.

Actually, though, the more I think about it, why is "no" even available for services that support SNI? That's adding more possible ways to configure this wrong, and for no benefit. There shouldn't be a no option.

So, no third option and remove the word "yes"...just describe what each option does.

**Comment by iliarostovtsev** [comment]
"No" is the way to show that a service already has setup certificate, either self-signed or from another domain.

> Or change wording from "all requests" to "all requests for domains that do not have a certificate".

Yes, I personally like it. We could call it:

~~~
Yes, for requests to _ubuntu20-pro_ and make global default for all requests for domains that do not have a certificate
Yes, for requests to _ubuntu20-pro_ only
No, use already installed certificate from _sub10.ubuntu20-4-pro_
~~~

Almost all services support SNI, like _Webmin_, _Usermin_, _Dovecot_ and _Postfix 3.4+_, and I would just like it explicitly display, what domain uses exactly what, and what are the current defaults (displayed in "No" option).

What's for sure buttons should go.

**Comment by swelljoe** [comment]
> "No" is the way to show that a service already has setup certificate, either self-signed or from another domain.

I don't think I understand this. If a service supports SNI, *and*, if the domain has a certificate (which is the only way this page would show up, I assume?), then what possible reason could someone have for choosing "no"? That's not even currently a possibility in the current UI, right? Right now, if a service supports SNI and if Virtualmin knows about a certificate for the domain, it sets up the service to use it for the domain, right? So...we're adding more options for a use case that doesn't exist? "No" would be like saying, "I don't want this service to work right for this domain because my users will get certificate errors or silent failures depending on the mail client or sender". (That can also happen with services that don't support SNI if the user tries to use a domain that isn't in the cert, but that's a different issue with a different solution.)

Am I just completely missing a use case where "no" does something useful? (For services that do not offer SNI, it is a useful indicator that this is not *the* certificate being used by the service. But, for services that do...it's just a switch to break things, as far as I can tell. And somebody will absolutely flip the "break things" switch if we give them one.

**Comment by iliarostovtsev** [comment]
> Am I just completely missing a use case where "no" does something useful? For services that do not offer SNI, it is a useful indicator that this is not the certificate being used by the service.

Joe, yes, you are right, and technically we don't need **_No_** option because we shouldn't expect a user to wish to remove legit SSL certificate for a virtual server, and possibly getting an error in the end. Though, it's not adding anything new, right? We already have an option to remove service certificate for a domain (with this current **_No_** option).

> if the domain has a certificate (which is the only way this page would show up, I assume?), then what possible reason could someone have for choosing "no"?

I presume, there might be a case involving wildcard certificates, when disabling (using **_No_** option) might be needed, and only in case when SSL certificate sharing is off.

@jcameron Jamie, what are your thoughts on all of this?

**Comment by swelljoe** [comment]
> I presume, there might be a case involving wildcard certificates, when disabling (using No option) might be needed, and only in case when SSL certificate sharing is off.

Maybe the wildcard case makes sense. But, I had to try to reduce the number of options...and, I'm still not entirely convinced that this one rare use case makes it worth the trade off of having switch that will break it for like 99.9% of users. But, maybe just having it be a lot more clear what all the options do and giving them their own page is sufficient to alleviate this source of constant support burden most of the time. At least the last option sounds like something most people *don't* want, so they won't clicking thinking they're enabling TLS for the service for this domain, which is why things are so bad with the current UI; to a lot of people it looks like something they need to click to make TLS work for a service.

**Comment by jcameron** [comment]
You're right, we could get rid of the "No" option. In that case, maybe this page could simply not list the services for which the cert is already setup.

Now I think about it, should we even offer the option to copy to global in the UI? We could leave that functionality in the command-line API for users who really want it..

**Comment by elfensky** [comment]
During the youtube tutorial you mention that the hostname should be a fqdn. 
The confusion surrounding this setting could be waved away if you ask the user to choose a hostname+fqdn during the installation process:
1) what website do you plan to host on this server? - virtualmin.com
2) what would you like to call your server? - server01
3) install script sets server hostname to server01.virtualmin.com

Right now there's a self-signed certificate that's used for all those options, it's automatically configured and the user doesn't see it. 

Once the creates a virtual server for virtualmin.com and requests the LetsEncrypt certs, one is also requested for server01.virtualmin.com and automatically used for all the services.

**Comment by swelljoe** [comment]
> For example, I requested additional certificates from Lets Encrypt for all the subdomains virtualmin created like mail, m, ftp, admin, webmail etc.. (which, really, should happen automatically I think)

This can only be automatic for names that have a website or locally hosted DNS and a LE client that supports DNS validation. Extremely likely to fail and confuse a lot of people. It probably should become automatic for `mail` (and `m` and `ftp` should probably go away as automatic names, I think).

> Do I need to press "copy to dovecot/postfix" after I requested the certificate for the mail subdomain?

You don't ever *need* to press it, if your versions of Dovecot and Postfix support SNI. Most people do not have a Postfix version that supports SNI, so those folks should press it *once* for the one domain that will be used for mail service.

**Comment by elfensky** [comment]
> This can only be automatic for names that have a website or locally hosted DNS and a LE client that supports DNS validation. Extremely likely to fail and confuse a lot of people. It probably should become automatic for `mail` (and `m` and `ftp` should probably go away as automatic names, I think)

Ah right, that makes sense. Lets Encrypt wont resolve and fail. About automatically signing the mail subdomain - If you disable "set up BIND DNS for vServer" when creating a new one, won't it always fail until you set up the DNS records? Or will/should that fall back on self-signed certificates? 

I think with the shift to responsive design in the last decade, the m domain definitely has to go. I only know very few legacy websites that still use a separate mobile design on the subdomain.

On the topic of ftp I think that connecting directly to whichever (sub)domain you want to manage makes more sense, so I agree there too.

> You don't ever _need_ to press it, if your versions of Dovecot and Postfix support SNI. Most people do not have a Postfix version that supports SNI, so those folks should press it _once_ for the one domain that will be used for mail service.

Can you explain more about "the one domain that will be used for mail service"? What domain is it, the server's own fqdn?

For example, I call my server: "vps.lavrenov.io", and host a virtual server "lavrenov.io" and "example.com" on it. 
I want to send and receive emails for both of those domains. What certificates does postfix/dovecot use? 
Should I request one for vps.lavrenov.io and press "copy", and that will then be used for all virtual servers?

If I understand correctly, Postfix started supporting SNI from 3.4.0 onwards, so my installation of virtualmin actually supports it (postfix 3.4.13). That brings up a new question - do I (currently) still need to request certificates for the mail subdomain of any virtual server I add, do I still need to press "copy" afterwards, or will the ones requested automatically (lavrenov.io and www.lavrenov.io) be enough and used automatically? 

My Dovecot version (2.3.7.2) also seems to support it - same question.

**Comment by swelljoe** [comment]
> Can you explain more about "the one domain that will be used for mail service"? What domain is it, the server's own fqdn?

It is whatever domain you choose to use for mail client connections. Er...whatever domain's certificate you choose to use, I guess, is more accurate. A certificate can contain more than one name (i.e. domain certs usually always contain at least example.tld and www.example.tld, so either of those names would work for most mail clients if you use that cert), and Postfix will serve that certificate to clients that can choose to consider it valid for any of those names.

> Should I request one for vps.lavrenov.io and press "copy", and that will then be used for all virtual servers?

I would never do that. I always choose one of my Virtualmin-hosted domains for the mail domain.

**Comment by swelljoe** [comment]
> do I still need to press "copy" afterwards

Probably not. If all of your services support SNI, and all of your clients support SNI, it won't matter.

It is harmless to do so, however, and maybe even useful for clients that may not support SNI. Pick a domain to be the "default" and click copy one time for all the services so they all have that default certificate.

**Comment by iliarostovtsev** [comment]
@jcameron Jamie, it would be good, if upon wizard step, when admin adds a default domain for the server (which presumably must be server's hostname), and if Let's Encrypt request is successful, Virtualmin would automatically used this domain's certificate as default for all services (Webmin, Usermin, Dovecot, Postfix, and ProFTPd).

**Comment by iliarostovtsev** [comment]
> Be careful about front-loading complicated decisions. 

Yes, you are right. However, my suggestion about settings up service certificates with default domain certificate will not make anything more complicated nor would add any additional UI options. Default domain, when it's setup using post-install wizard will only try to request Let's Encrypt and will not return any errors even if Let's Encrypt certificate cannot be request.

@jcameron My suggestion, if Let's Encrypt for default domain (on initial post-install wizard page) is successful, then automatically install this default domain certificate as default services' certificate. The same way if you clicked those **Copy to ..** buttons manually (while default domain is selected) but do this automatically.

**Comment by iliarostovtsev** [comment]
Jamie, Joe, I suggest the following in regards of **Service Certificates** page -

 1. We can completely remove this page
 2. If service supports SNI - enable it for all services by default - Webmin, Usermin, Dovecot, Postfix
 3. _Copy to .._ buttons can be replaced with a single _Yes/No_ radio under **Server Configuration ⇾ Email Settings**
 4. All other less popular configurations will still be possible to perform using CLI

What do you think?

**Comment by jcameron** [comment]
That's not a bad idea - we could just switch to always setting up the service certs for new domains, and when SSL is enabled for an existing domain. It seems like a rare case when the user wants to **not** have this setup.

**Comment by iliarostovtsev** [comment]
> we could just switch to always setting up the service certs for new domains, and when SSL is enabled for an existing domain

Isn't it already the case? I think we could just remove the tab and that's it?

>  It seems like a rare case when the user wants to not have this setup.

Yes, agreed.

> Copy to .. buttons can be replaced with a single Yes/No radio under Server Configuration ⇾ Email Settings

No, actually, lets move and combine **Copy to ..** buttons,in to a single button and place it under **SSL Certificate / Current Certificate** page, right before **Delete SSL Certificate** button. Perhaps the new button could be called **Set As Default Services Certificate**, like this, for example:

![image](https://user-images.githubusercontent.com/4426533/117567870-cb8d9980-b0c6-11eb-9f0a-da4ba0dcd867.png)


.. and it would be also cool to reset to initial default certificates, like:

![image](https://user-images.githubusercontent.com/4426533/117568002-39d25c00-b0c7-11eb-83f5-8a1923ac658c.png)

**Comment by iliarostovtsev** [comment]
Jamie, what are we doing here? What about my suggestions above?

**Comment by jcameron** [comment]
I like that suggestion - I'll update the page as you suggested, and drop the "Service SSL Certs" tab.

**Comment by jcameron** [comment]
Ok, I've checked in a large change to simplify that page.

**Comment by iliarostovtsev** [comment]
Thanks, Jamie. I have also submitted a [tiny fix](https://github.com/virtualmin/virtualmin-gpl/commit/82078cdde5e4b268188f0d912e27c047461da773) to your commit, to print `<hr>` only if buttons exists, and swapped buttons for copying to global with copying for requests.

Besides, on the theme side I made a brand, special case icons for certificate operations.

**Example:**

![image](https://user-images.githubusercontent.com/4426533/120536040-5b83e200-c3ec-11eb-83ad-ebd2756cdc91.png)

![image](https://user-images.githubusercontent.com/4426533/120535993-4c9d2f80-c3ec-11eb-8d11-2aa3d8795ea4.png)

![image](https://user-images.githubusercontent.com/4426533/120535774-0ea00b80-c3ec-11eb-80aa-52a3d1a37567.png)

![image](https://user-images.githubusercontent.com/4426533/120535860-26778f80-c3ec-11eb-9955-7080908eb4af.png)

---

Joe, are you happy with this change? Can this ticket be closed?

**Comment by swelljoe** [comment]
Yes, this is vastly better. I think there's still room for people to get confused, but I don't think we can solve that. It's a very complicated thing with a half dozen services with varying levels of capability, etc.

So, let's get it merged/released and see how this UI confuses people. It cannot possibly be worse than the "Copy to.." UI.

**Comment by jcameron** [comment]
We're down to 2 buttons now, so hopefully less opportunities to get confused :-)
