### ISSUE TITLE
install script fails LEMP when no apache2 is installed on Ubuntu 20.04

### ISSUE THREAD

**Issue by elfensky** [virtualmin/virtualmin-gpl#252]
**Problem**
Virtualmin's install script fails when attempting to remove apache2 when no apache2 is installed on Ubuntu 20.04 (it came like that from OVHcloud)
<img width="725" alt="image" src="https://user-images.githubusercontent.com/4704358/108128795-9700d780-70ad-11eb-941b-1fd177ea478b.png">

**Temporary Solution**
Manually install apache2 using `apt install apache2-bin` and rerun the virtualmin install script, it will proceed without further issues. 

**Permanent Solution**
Figure out what went wrong and fix the script :)

Edit: Created issue in the wrong repository

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up.

This should fix that - https://github.com/virtualmin/virtualmin-install/commit/8a56f3704b3010863052ad510dbe08b04f1d75b7
