### ISSUE TITLE
Let's Encrypt renewals no longer updates certificates correctly

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#254]
Until recently Let's encrypt certificates were renewed more then 10 days before they expired (I have setup 3 months between automatic renewal, and I am checking the certificates to alert me when they are less then 10 days valid)

I now have had serveral certificates with less than 10 days remaining:
-Twice I could manually trigger the renewal and everything worked as expected.
-Twice there was a problem with the domain, which until recently triggered an email wich stated "An error occurred requesting a new certificate for <domain> …"

I'm experiencing those problem on servers running webmin 1.962 as well as 1.970.

letsencrpyt.log has detailed errors matching the different problems, but none of those were send by email as previously

**Comment by PitWenkin** [comment]
There are now multiple Site which will expire in the next 10 days.

I ran the commands `sudo certbot certificates` and `sudo certbot renew` which both state the certifcates in question are valid for around 65 days. So apparently something was renewed 25 days ago.
As I have setup 3 months between renewal, and the certificates are renewed 1 month before expiration, the automatic renewal seems to work somehow …  but unfortunately only files in `/etc/letsencrypt/live/` seem to have changed, but not the files that are actually used, which in my case are located in `/home/<site>/`

My guess is, that until certs were being copied to the home folder, and somehow this is no longer working. I did no changes on the server which would explain this behaviour …

The problem seem to have started at the beginning of february … but not all renewals failed …

**Comment by pixel-paul** [comment]
I'm experiencing this too. Looks like it has been flagged as an issue: 

https://forum.virtualmin.com/t/lets-encrypt-certificates-not-renewing-anymore/109301

**Comment by PitWenkin** [comment]
"We’ll be rolling updates to fix this problem (and another LE related issue) this weekend." 

I don't see any webmin/virtualmin package updates in the update history for the last days  and there are no pending updates … @swelljoe 

I guess untill the update is released I will have to manually trigger renewals … same for already "broken" certificates

**Comment by pixel-paul** [comment]
Yes, I am relying on the Let's Encrypt expiry emails to be sent, so I can address each site as it occurs.

**Comment by iliarostovtsev** [comment]
Currently Virtualmin 6.14 doesn't have the check done right for newly issued Let's Encrypt certificates, however upcoming Virtualmin 6.15 will have it fixed!

Meanwhile, you could manually patch `feature-ssl.pl` file and line 2437 from what it is now, and replace it with:


<pre>
next if ($info->{'issuer_o'} !~ /Let's\s+Encrypt/i);
</pre>

I cannot say it's recommended way of doing it for everyone but it's better than not working automatic renewals. 

Few tips:

  1. To find mentioned file use `find /usr -name feature-ssl.pl` command
  2. You will need to restart Webmin after editing this file with `/etc/webmin/restart` command

**Comment by PitWenkin** [comment]
Is there an ETA for Virtualmin 6.15?

**Comment by synio-wesley** [comment]
Hi, I'm the one who created the topic on the forum you linked to 24 days ago. I just wanted to thank you for looking into the issue and hopefully it will be resolved soon now that it's getting some more attention.

**Comment by PitWenkin** [comment]
Just saw that [6.15](https://github.com/virtualmin/virtualmin-gpl/releases/tag/6.15) is released.

Just wondering if this will fix certificates that are already "broken", or will it just work for certificates that are renewed (manually) from now on

**Comment by PitWenkin** [comment]
I'm getting "spammed" with certificate renewal emails, minutes after updateing to 6.15.

I can therefor confirm that this is fixed

**Comment by erpsolns** [comment]
Sorry to say on 6.16 again Letsencrypt Certificate issue or renew not working

**Comment by swelljoe** [comment]
No. The issue you reported is unrelated to this one, @erpsolns .
