### ISSUE TITLE
Security Issue!!! Virtualmin Update broke PHP

### ISSUE THREAD

**Issue by redflo** [virtualmin/virtualmin-gpl#255]
On my Opensuse 15.1 Server the Update of virtualmin last week changed the file
/etc/apache2/conf.d/php7.conf from
`
<IfModule mod_php7.c>
       <FilesMatch "\.ph(p[345]?|tml)$">
           SetHandler application/x-httpd-php
       </FilesMatch>
       <FilesMatch "\.php[345]?s$">
           SetHandler application/x-httpd-php-source
       </FilesMatch>
        DirectoryIndex index.php4
        DirectoryIndex index.php5
        DirectoryIndex index.php
</IfModule>
`
to
`
<IfModule mod_php7.c>
       <FilesMatch "\.ph(p[345]?|tml)$">
       </FilesMatch>
       <FilesMatch "\.php[345]?s$">
       </FilesMatch>
        DirectoryIndex index.php4
        DirectoryIndex index.php5
        DirectoryIndex index.php
</IfModule>
`
Which completely broke some Websites and is a **big security issue!** Websites did not deliver generated content but code and configuration data!

**Comment by chris001** [comment]
The two `SetHandler` statements were removed!  _No bueno.._  That shouldn't happen!  Was it the update of the `php7` package, or the update of `virtualmin`, that removed them?

Unrelated question, why use the old `mod_php7`?  `php7-fpm` is more efficient on resources, faster, and consensus best practice.

**Comment by redflo** [comment]
From the file change time and the installation time when checking rpm installation history, it must have been the installation of wbm-virtual-server-6.14.gpl-1.noarch over Version 6.08.gpl 
I plan to switch to php7-fpm, but first i have to update the OS, which is out of support unfortunately.

**Comment by PitWenkin** [comment]
On Ubuntu a similar thing happens in `/etc/apache2/mods-available/php7.0.conf`

```
<FilesMatch "\.php$">
        SetHandler application/x-httpd-php
</FilesMatch>
```

is  changed to

```
<FilesMatch "\.php$">
</FilesMatch>
```

This happens since serveral years back … I always though it was **_my_** config that caused this …

**Comment by swelljoe** [comment]
It *is* your config. You should not have mod_php installed or enabled. Ever. It is consider deprecated by the PHP developers, and we follow their lead.

**Comment by swelljoe** [comment]
Solution is to either: Uninstall mod_php and never use it again. Or edit that file and configure dpkg to not replace modified config files (this is the default behavior, but I guess it isn't configured that way on your systems). If you delete the file, it will be replaced on updates. If you modify it, and you have the default behavior, it should leave the file unchanged on updates.

**Comment by swelljoe** [comment]
Er, wait, I see we're talking about RPM-based distros...I'm not sure why it'd be modifying config files. That may actually be a bug in the postinstall script, but I'm not really inclined to try to support distributions and Apache modules that have been EOL/deprecated for months or years. If you're OK with old software, stop updating.

**Comment by jcameron** [comment]
Virtualmin does attempt to remove those global `SetHandler` lines on install, as they can break per-domain PHP configs.

All domain should have the correct Apache directives to run PHP scripts in the correct mode though .. unless you also have apache virtualhosts that were setup outside of Virtualmin?

**Comment by redflo** [comment]
All Apache virtual hosts are managed through Virtualmin. Not every virtual host was broken. The virtual hosts, which config was generated before 2017 and not changed due to configuration changes do not have the "AddType application/x-httpd-php .php" and were therefore broken. Maybe these would have been broken with php-fpm too?

**Comment by iliarostovtsev** [comment]
Florian, just uninstall or disable _mod_php_. For instance, it's deprecated on newer RH systems (i.e. you cannot even install it).

Yesterday, we have fixed the installer, it was accidentally installing _mod_php_ for newly deployed systems. It will no longer be an issue for new, future installs.

Locally, you could fix this issue with running:

~~~
zypper a2dismod php7
zypper remove apache2-mod_php7
~~~

.. and make sure that you have FCGId and FPM, along side with other recommended packages installed:

~~~
zypper install apache2-mod_fcgid php7-fpm php7-cgi php7-cli php7-pdo php7-zip php7-gd php7-xml php7-mysqlnd php7-opcache
~~~

**Note:** For more stable and pleasant experience we suggest running Virtualmin on [A grade supported systems](https://www.virtualmin.com/os-support.html).

**Comment by jcameron** [comment]
So the code in Virtualmin to remove these `AddType` lines should only effect global config files like `/etc/apache2/mods-available/php7.0.conf` . Any in domain's VirtualHost blocks should be untouched.
