### ISSUE TITLE
2 x PostgreSQL handling bugs: Database deletion failure on delete of virtual server & cAsESenSitivity handling on table/relationship names during drop all tables

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#258]
**Issue 1:** 
Can't fully delete virtual server with in use PostGres db.

Deleting PostgreSQL database confluencedb ..
.. PostgreSQL database failed! : SQL drop database "confluencedb" failed : database "confluencedb" is being accessed by other users

![image](https://user-images.githubusercontent.com/10130237/111127455-8ba1ae80-857c-11eb-838a-d946d2f08f74.png)

**Solution:** 
Postgres 13+ add FORCE option for DROP DATABASE
Postgres 12 and under, implement REVOKE CONNECT ON DATABASE thedb FROM public; before dropping.

Ref: https://dba.stackexchange.com/questions/11893/force-drop-db-while-others-may-be-connected

**Issue 2:**
Webmin Postgres module doesn't properly handle table name or likely relationship case sensitivity during drop database cgi.

Failed to drop database : SQL select count(*) from AO_098293_ANNOUNCEMENT_ENTITY failed : ERROR: relation "ao_098293_announcement_entity" does not exist LINE 1: select count(*) from AO_098293_ANNOUNCEMENT_ENTITY ^

![image](https://user-images.githubusercontent.com/10130237/111127736-d3283a80-857c-11eb-9721-bb09fd20801b.png)

![image](https://user-images.githubusercontent.com/10130237/111127929-05399c80-857d-11eb-8b9a-d8a6bc1e07ae.png)

Solution: Probably difficult but involves double quoting.
True solution is to use all lowercase tables in the app but no choice here.

Ref: https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive

![image](https://user-images.githubusercontent.com/10130237/111128236-55186380-857d-11eb-8988-a131df828ede.png)

Dropping the database as postgre admin worked fine.

DROP DATABASE confluencedb ;

**Comment by jcameron** [comment]
Thanks for pointing these out - they will be fixed in the next Virtualmin and Webmin releases respectively.
