### ISSUE TITLE
Validation path checks needed in Backup Virtual Server Panel.

### ISSUE THREAD

**Issue by alexbogias** [virtualmin/virtualmin-gpl#26]
If you try to Backup a virtual server and you select the public_html path on "Backup destinations" Local directory like /home/user/public_html virtualmin will delete your public_html path and write a file with filename public_html and without a file extension.

**Comment by jcameron** [comment]
Which Virtualmin version are you running there? I thought we fixed this a release or two ago.

**Comment by alexbogias** [comment]
I was running the latest version but I think it happened a month ago...

**Comment by alexbogias** [comment]
I was able to reproduce it now in v6.01-3
![gsddfsggdsfg](https://user-images.githubusercontent.com/1313467/32766059-eae19e54-c915-11e7-8b0f-dce3a14893c2.png)

**Comment by qooob** [comment]
Looking at your console I can tell that you're trying to go to `public_html` from your `~` home directory but not from `/home/test`.

Try `cd /home/test` first.

**Comment by alexbogias** [comment]
Oops you are right. I was on rush...
root@one ~ # ls -l /home/test/public_html/
total 40
-rw------- 1 root root 28444 Nov 14 09:44 test.com.tar.gz
-rw-r--r-- 1 root root  5488 Nov 14 09:44 test.com.tar.gz.dom
-rw-r--r-- 1 root root   144 Nov 14 09:44 test.com.tar.gz.info

Looks great now.. It creates a file with the domain name
