### ISSUE TITLE
Transferring (or restoring) a virtual server fails if php_admin_value engine parameter is set

### ISSUE THREAD

**Issue by pixel-paul** [virtualmin/virtualmin-gpl#263]
Webmin version | 1.973
Virtualmin version | 6.15

When transferring a vritual server and the php_admin_value engine parameter is set in the httpd.conf directive and the new server is running PHP 7.4, Apache will fail to restart and the httpd service will stop.

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up. I will run few tests and get back to you tomorrow.

**Comment by jcameron** [comment]
That's surprising, because we have code in Virtualmin which should strip out these directives on restore if mod_php is not installed.

**Comment by pixel-paul** [comment]
I have transferred another virtual host and the parameter was removed this time. Could it have occured because the transfer script failed elsewhere, before it reached the removal code? I've run into a couple of problems whilst transferring virtual hosts.

**Comment by iliarostovtsev** [comment]
Perhaps you could share with us a backup that failed to make it easier for us?

(considering you ran it on the same latest Virtualmin 6.15 in both cases)

**Comment by pixel-paul** [comment]
I think, looking at the recent commits that this is likely linked to issue #267 and the restore failed that meant that the parsing of the virtual host entry didn't work correctly. 

I added the fix as per #267 and the transfers are working flawlessly.

**Comment by iliarostovtsev** [comment]
> I added the fix as per #267 and the transfers are working flawlessly.

.. to double check - can you confirm that restoring a backup from system **with** _mod_php_ installed and enable, where Apache config contains _php_admin_value_ is working properly, i.e.   _php_admin_value_ directives are getting dropped on the new system, where _mod_php_ is not installed, thus there is no problem in starting Apache?

**Comment by pixel-paul** [comment]
The transfer is from a server with mod_php enabled to a server without (so it only has php-fpm).
The originating website wasn't using mod_php, it was also using php-fpm, however the php_admin_value was present.

From what I can see, the parameter may have remained because the transfer failed because of #267. Apache will not start with the php_admin_value present. 

Secondly, #266 also stops Apache restarting due to port conflicts.

So perhaps we are seeing a combination of issues whereby the transfer fails, however new records are added to the httpd.conf file and Apache is restarted.

**Comment by pixel-paul** [comment]
I'm repoening this as it has happened again. 

RemoveHandler .php  
RemoveHandler .php7.4  
**php_admin_value engine Off**  
SSLEngine on

is present in the new server's virtualhost block of httpd.conf

**Comment by jcameron** [comment]
I found another bug that can cause this if a domain has SSL enabled :-(

We're going to release a minor update with a fix shortly.

**Comment by pixel-paul** [comment]
Thanks @jcameron!

**Comment by GeekOnTheHill** [comment]
Well, that's good to know. I've been banging my head against the wall thinking it was something I was doing. My wall will be grateful.

**Comment by verne-wv** [comment]
not sure of my versions, but for at least a year when I migrate a virtual host from an older server to a newer one using backup and restore, I have this exact issue BITE ME .... my solution is to manually edit httpd.conf on the old system immediately before I make the backup and comment out the ENGINE line in that individual stanza, then make the backup, then un-comment the line.

Glad to see its not just me having an issue !!

Sorry I have been lazy (or busy) and not reported it before.

**Comment by pixel-paul** [comment]
@verne-wv - yes that's a good idea. If you comment out the line and save the file, as long as you do not apply the configuration, apache won't know about the change.
