### ISSUE TITLE
PHP: Version of PHP incorrectly listed as available

### ISSUE THREAD

**Issue by iliarostovtsev** [virtualmin/virtualmin-gpl#268]
Jamie, hi! Look, the check below should be done based on PHP CGI _**version**_ being installed/available:

https://github.com/virtualmin/virtualmin-gpl/blob/f690a50d282c6fc9b3a43284c2ff6b41a87268c7/php-lib.pl#L940-L952

At the moment I have intentionally installed **PHP 5.6-FPM** only and **PHP 7.3** with both **CGI** and **FPM**. When you visit **PHP Options** page it displays multiple PHP versions available for _**FCGId**_ mode while it should be only version 7.3. While choosing 5.6 from select doesn't brake anything and just leaves version 7.3 running, I think it must not be displayed, as it simply not installed. 

What are your thoughts?

**Comment by iliarostovtsev** [comment]
.. same happens for other PHP versions (not only with 5.6 but 7.4 as well and other) .. besides, if you _remove_ both **_CGI_** and **_FPM_** packages for given PHP version, then again, PHP version **will be displayed as available** in an option list but it won't work if you try selecting it and saving options. It won't break virtual server (Apache/Nginx configs) though, leaving PHP files without a handler but it pretends that all is going well, things look are getting saved and no error reported ..

.. removing PHP **_CLI_** makes it disappear from the list but it is not something we should rely on when performing the test.

**Comment by iliarostovtsev** [comment]
> I'll take a look

Thanks.

> So really this function should be returning different lists of versions depending on the PHP mode.


Yeah, it does but it always returns FCGI from some other global, default version, and doesn't actually run a check on version basis.

**Comment by jcameron** [comment]
I'm having trouble reproducing this on my system.

What output do you get when you run `virtualmin list-php-versions --multiline`

**Comment by iliarostovtsev** [comment]
I started thinking that it is indeed somewhat a local issue(after your comment), and done quick tests on the other instance. This time it was **Ubuntu 20.04 with Apache**. Eventually, I could reproduce the same problem, what's worse, it breaks things (with Apache), leaving PHP with an error, when trying to set a version that doesn't exists (no wonder).

```bash
root@debug-ubuntu20-pro:~# virtualmin list-php-versions --multiline
7.3
    Command: /bin/php7.3
    PHP modes: cgi fcgid
    FPM support: No
    Full version: 7.3.27
7.4
    Command: /bin/php-cgi7.4
    PHP modes: cgi fcgid
    FPM support: Yes
    Full version: 7.4.3
```

For this Ubuntu 20.04 instance apart from default configuration with PHP 7.4 I only installed `php7.3-cli` package. The output above in clearly a bit off, considering the packages installed.

```bash
ii  php7.3-cli            7.3.27-9+ubuntu20.04.1+deb.sury.org+1      amd64        command-line interpreter for the PHP scripting language
ii  php7.3-common         7.3.27-9+ubuntu20.04.1+deb.sury.org+1      amd64        documentation, examples and common module for PHP
ii  php7.3-json           7.3.27-9+ubuntu20.04.1+deb.sury.org+1      amd64        JSON module for PHP
ii  php7.3-opcache        7.3.27-9+ubuntu20.04.1+deb.sury.org+1      amd64        Zend OpCache module for PHP
ii  php7.3-readline       7.3.27-9+ubuntu20.04.1+deb.sury.org+1      amd64        readline module for PHP
ii  php7.4-cgi            7.4.3-4ubuntu2.4                           amd64        server-side, HTML-embedded scripting language (CGI binary)
ii  php7.4-cli            7.4.3-4ubuntu2.4                           amd64        command-line interpreter for the PHP scripting language
ii  php7.4-common         7.4.3-4ubuntu2.4                           amd64        documentation, examples and common module for PHP
ii  php7.4-fpm            7.4.3-4ubuntu2.4                           amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.4-json           7.4.3-4ubuntu2.4                           amd64        JSON module for PHP
ii  php7.4-mbstring       7.4.3-4ubuntu2.4                           amd64        MBSTRING module for PHP
ii  php7.4-mysql          7.4.3-4ubuntu2.4                           amd64        MySQL module for PHP
ii  php7.4-opcache        7.4.3-4ubuntu2.4                           amd64        Zend OpCache module for PHP
ii  php7.4-readline       7.4.3-4ubuntu2.4                           amd64        readline module for PHP
ii  php7.4-xml            7.4.3-4ubuntu2.4                           amd64        DOM, SimpleXML, XML, and XSL module for PHP
```

Worth saying that FPM detected/not detected correctly, while CGI/FCGI modes are false positive, and should absent for PHP 7.3 in this given example.

**Comment by jcameron** [comment]
Ok I see the real issue - the attached commit should fix this.

**Comment by iliarostovtsev** [comment]
Okay, cool. It works great now!
