### ISSUE TITLE
Virtualmin LEMP - cannot validate virtual server after changing root directory

### ISSUE THREAD

**Issue by pixel-paul** [virtualmin/virtualmin-gpl#269]
O/S: RHEL 8.3
Webmin version: 1.973
Virtualmin version: 6.15
Installed using installer.sh --bundle LEMP

To reproduce:

1. Create a new virtual server
2. Click Services
2. Configure Nginx Website
3. Document options
4. Select new folder for document root
5. Click apply
6. Result: 
`'Virtual host no longer exists!'`
7. Click Limits and Validation
8. Validate Virtual Servers
9. Validate
10. Error: 
`Nginx website : The Nginx virtual host root directory is /home/next/public_html/nextcloud, but Virtualmin expects it to be /home/next/public_html`

**Comment by iliarostovtsev** [comment]
Hi, Paul.

Do you expect home directory to be automatically altered on other configs too?

**Comment by pixel-paul** [comment]
Looking at the nginx config, it looks like the issue could related to the php fastcgi parameters not being updated. I corrected the following:

`fastcgi_param SCRIPT_FILENAME /home/next/public_html/$fastcgi_script_name;`
and
`fastcgi_param DOCUMENT_ROOT /home/next/public_html`

to 

`fastcgi_param SCRIPT_FILENAME /home/next/public_html/nextcloud/$fastcgi_script_name;`
and
`fastcgi_param DOCUMENT_ROOT /home/next/public_html/nextcloud`

and it everything appears to work as expected.

**Comment by pixel-paul** [comment]
> Do you expect home directory to be automatically altered on other configs too?

Only in terms of the nginx config, as I would expect changing the document root using Virtualmin not to fail.

**Comment by iliarostovtsev** [comment]
I remember suggesting in the past renaming the home directory, on changing this option on _Website Options_ page, and discussed it with Jamie but he wanted to keep the way it is.

Jamie, perhaps we should reconsider and when that option is changed, we would both rename the home directory and change Apache/Nginx configs?

**Comment by pixel-paul** [comment]
Ah, so this is what has had me confused (this is the first time I have used the LEMP stack with Virtualmin).

If I go to 'Website Options' I do not get the options to change the 'Website documents sub-directory' as I would for Apache:

![Screenshot_2021-03-20- Website Options — Webmin 1 973 (Redhat Enterprise Linux 8)](https://user-images.githubusercontent.com/389303/111880684-d66c5d80-89a4-11eb-940f-3b515dba20d8.png)

**Comment by jcameron** [comment]
That seems like a bug ... I'll take a look

**Comment by jcameron** [comment]
Ok, a fixed for this will be in the next Virtualmin release.

**Comment by pixel-paul** [comment]
Thanks @jcameron!

**Comment by iliarostovtsev** [comment]
Jamie, there is a little more than that - it does change `root`:

~~~
-       root /home/debian10-pro/public_html;
+       root /home/debian10-pro/public_html2;
~~~

.. but it doesn't change these directives:

~~~
fastcgi_param SCRIPT_FILENAME /home/debian10-pro/public_html$fastcgi_script_name;
fastcgi_param DOCUMENT_ROOT /home/debian10-pro/public_html;
~~~

.. and again, it doesn't rename existing directory to a new one automatically. Should Virtualmin also rename _htmldir_, if the directory with new name doesn't exist?

**Comment by iliarostovtsev** [comment]
I assume Nginx `set_public_html_dir` needs a fix..

**Comment by jcameron** [comment]
No, I don't want to change the existing behavior by renaming the directory.

I will fix that `fastcgi_param` though.
