### ISSUE TITLE
Remove SSL certificate configuration link if "SSL website" is turned off 

### ISSUE THREAD

**Issue by alanmels** [virtualmin/virtualmin-gpl#271]
To replicate the issue go to _System Settings > Features and Plugins_ and check off the _SSL website_ option, create a website (virtual server) and you still see the, completely useless, SSL certificate link.

**Comment by iliarostovtsev** [comment]
Hi,

Starting with Virtualmin 6.15, virtual server SSL configuration is no longer coupled with website feature. This link is not useless, and it is not a bug. It is intentional.
