### ISSUE TITLE
feature-web.pl has typo in a comment

### ISSUE THREAD

**Issue by verne-wv** [virtualmin/virtualmin-gpl#272]
I think v6-15 introduced the enhancement in feature-web.pl that contains the comment line

`# If the restored config contains php_value entires but this system`

did you want that to say "php_value entries" ?

**Comment by iliarostovtsev** [comment]
Hi,

Thanks, you're right. https://github.com/virtualmin/virtualmin-gpl/commit/25b07cd02707e614f86b00405be905f7f68f8896
