### ISSUE TITLE
Debian 10: MariaDB/MySQL label mismatch

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#275]
![2021-04-04_223104](https://user-images.githubusercontent.com/1004261/113531263-41698700-9596-11eb-9f90-5331f83f9a62.png)

Thanks!

**Comment by swelljoe** [comment]
It used to always say MySQL everywhere. That's progress, I guess? ;-)

**Comment by marclaporte** [comment]
haha, yes :-)

**Comment by iliarostovtsev** [comment]
This is on the todo.

I will have a look at it tomorrow, trying to find the right solution for it, as just fixing it is not a problem at all.

**Comment by iliarostovtsev** [comment]
This [PR](https://github.com/webmin/webmin/pull/1470/files) will address it.

Thanks for the heads up.
