### ISSUE TITLE
modification of TLS protocol to TLSv 1.0 in Ubuntu 20.04 and Virtualmin 6.16 does not work

### ISSUE THREAD

**Issue by NargesTavassoli** [virtualmin/virtualmin-gpl#278]
Hi,
I have Ubuntu 20.04 and Virtualmin 6.16, I need to enable TLSv1 in Virtualmin, I had checked TLSv1 in services>configure SSL website>SSL options, but when I check the website in CDN77.com TLS 1.0 is disable however TLS 1.3 and 1.2 are enabled :|

I tried to edit  SSLProtocol in services>configure SSL website>edit directives, even in Apache2 but nothing happens. 

Also when I disable  SSL, that doesn't work too, though all of these changes are working in centos 8.
Do you have any suggestions? 
Thanks in advance.

**Comment by iliarostovtsev** [comment]
Hi,

This is highly not recommended to re-enable TLS 1.0/1.1 as of [numerous security](https://datatracker.ietf.org/doc/draft-ietf-tls-oldversions-deprecate/) flaws.

If you still need this to re-enable for testing purposes you would need to check on **`SSLProtocol`** option in main Apache config and on given virtual server config as well -


![image](https://user-images.githubusercontent.com/4426533/114833522-5a650a00-9dd8-11eb-8ab3-28a8248912c7.png)

**Comment by NargesTavassoli** [comment]
Hi again 
thanks for the tip but I have done that already to no avail when I check the SSL version TLSv1 is still disabled
