### ISSUE TITLE
It should be easy to add ssh public keys for new or existing users

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-gpl#284]
I don't know exactly what this should look like, but it should be easy to add an ssh public key when creating a new user, or when that user logs into Usermin. Most of the cloud providers have some mechanism for this, and it's really convenient and easy to use good security practices so ssh can have password logins disabled. Right now there is no super simple way to tell people to create an `authorized_keys` file (and getting permissions right, etc.).

So, it needs a way to either upload a pub key or paste it into a form text field (probably with some validation to make sure it both is a key and isn't the private key).

**Comment by swelljoe** [comment]
And, by "user" I mean pretty much any kind of Virtualmin or system user, including domain owners and mail/ftp users.

**Comment by marclaporte** [comment]
It would be nice to have an option to point to a URL such as https://gitlab.com/marclaporte.keys

I have not tested but FYI:
https://bitbucket.org/jrsupplee/webmin-user-ssh-keys.git/src/master/

**Comment by jcameron** [comment]
One thing I could add pretty easily is a field on the Create User page of the Users and Groups module to enter the SSH public key for new users.

**Comment by iliarostovtsev** [comment]
I would also like to suggest adding an option (to this new feature), to import SSH key from authorities, like GitHub. All you would need to do is to ask a user on the UI for his/her username, and it would automatically returned you the public key.

This is how it is implemented on Ubuntu installer.

It may be a very useful and time saving feature, as copy/paste of public key is not always available.

For example, calling the following URL would return you your public SSH key:
 https://api.github.com/users/iliarostovtsev/keys

Jamie, if you wish to skip on doing that, it would be easier for me to implement it on the theme side, as it would require to make a background call, which on old themes could only be done by opening a pop-up window.

**Comment by jcameron** [comment]
Let me add it in the Users and Groups module first ..

**Comment by jcameron** [comment]
@swelljoe does it make sense to also have this in Virtualmin?

**Comment by swelljoe** [comment]
Yes, I brought it up because someone didn't understand why they couldn't login with their public key with the Virtualmin user they just created...and I didn't want to explain authorized keys and all that other crap, but there's no easier way to do it. So, if there is always a clear path for adding a public key (both by users themselves and the server administrator) I won't ever have to answer questions like that again. ;-)

**Comment by jcameron** [comment]
Ok, so I guess it would make sense to also allow a public key to be specified on the virtual server creation page.

**Comment by iliarostovtsev** [comment]
This has been implemented for inclusion to Virtualmin 7.
