### ISSUE TITLE
Let's Encrypt certificats still not renewed correctly

### ISSUE THREAD

**Issue by Sn4kY** [virtualmin/virtualmin-gpl#288]
Hi. (and sorry for my bad frenchy english)

Since few weeks, we notice that virtualmin with certbot still not copy /etc/letsencrypt renewed certificates files to /home/<dirname>/ssl.* 

Debian 9, with packages Webmin 1.974 and webmin-virtual-server 6.16.gpl

The ./install.sh -s was done

I have tried to apply the suggestion of replace everything in line 2437 of feature-ssl.pl with
`next if ($info->{'issuer_o'} !~ /Let's\s+Encrypt/i);`
But it's inside the sub get_postfix_ssl_cert ; so I didn't manually patch
I noticed that my /usr/share/webmin/virtual-server/feature-ssl.pl seems to be patched to handle correctly "Let's Encrypt" pattern in both issuer_cn and issuer_o (lines 2556 and 2557)
I noticed that my /usr/share/webmin/virtual-server/feature-ssl.pl differs from the master in this github. I replace mine with your's, but no changes.
(for the record)
```
--- /usr/share/webmin/virtual-server/feature-ssl.pl-dpkg.dist   2021-03-28 22:45:40.000000000 +0200
+++ /usr/share/webmin/virtual-server/feature-ssl.pl     2021-05-07 09:30:27.611478980 +0200
@@ -1199,9 +1199,11 @@
                }
        &unlink_file($pass_script);
        }
-&lock_file(@pps_str ? $pps_str[0]->{'file'} : $conf->[0]->{'file'});
+my $pps_file = @pps_str ? $pps_str[0]->{'file'} : $conf->[0]->{'file'};
+&lock_file($pps_file);
 &apache::save_directive("SSLPassPhraseDialog", \@pps, $conf, $conf);
 &flush_file_lines();
+&unlock_file($pps_file);
 &register_post_action(\&restart_apache, &ssl_needs_apache_restart());
 }

@@ -3030,7 +3032,7 @@
        }
 my @rv;
 foreach my $p (&unique(@paths)) {
-       $p =~ s/^\Q$d->{'home'}\E\///;
+       $p =~ s/^\Q$d->{'home'}\E\/// || next;
        if ($p =~ /^(.*)\//) {
                push(@rv, $1);
                }

```

More investigations

```
virtualmin list-certs-expiry --all-domains | grep vermersh
| vermersh.xxxxxx.net             | /home/xxxxxx/domains/vermersh.xxxxxx.net/ssl.cert             | Jun 01, 2021 | 25 days    | VALID   |

```
show me the good EXPIRES value (of the certificated loaded into apache) :
```
# openssl x509 -in /home/xxxxxx/domains/vermersh.xxxxxx.net/ssl.cert -noout -issuer -enddate
issuer=C = US, O = Let's Encrypt, CN = R3
notAfter=Jun  1 16:09:50 2021 GMT
```
BUT certbot is renewing successfully the certificate, at good date : 
```
openssl x509 -in /etc/letsencrypt/live/vermersh.xxxxxx.net/cert.pem -noout -issuer -enddate
issuer=C = US, O = Let's Encrypt, CN = R3
notAfter=Aug  1 04:18:01 2021 GMT
```

I can't understand why renewd certificates by certbot isn't apply by Virtualmin while collectinfo.pl's cron job
Of course, "Automatically renew certificate?" is at "Yes"

On cfg file, I noticed that letsencrypt_renew is at 2, but auto_letsencrypt at 0. It may be the problem ?
```
grep -P "lets|ssl|renew" /etc/webmin/virtual-server/domains/143374749729895
web_urlsslport=
letsencrypt_renew=2
ssl_cert_expiry=1622563790
ssl_cert=/home/xxxxxx/domains/vermersh.xxxxxx.net/ssl.cert
edit_ssl=0
ssl_cert_expiry_cache=1614791393
limit_ssl=0
ssl_key=/home/xxxxxx/domains/vermersh.xxxxxx.net/ssl.key
ssl_combined=/home/xxxxxx/domains/vermersh.xxxxxx.net/ssl.combined
ssl=1
ssl_everything=/home/xxxxxx/domains/vermersh.xxxxxx.net/ssl.everything
web_sslport=443
auto_letsencrypt=0
letsencrypt_last=1614791395
letsencrypt_last_failure=1570720689
letsencrypt_last_success=1614791395
letsencrypt_dname=vermersh.xxxxxx.net xxxxxx.fr www.xxxxxx.fr
ssl_pass=
ssl_chain=/home/xxxxxx/domains/vermersh.xxxxxx.net/ssl.ca
backup_ssl_type=ssl
```

```
dpkg -l | grep certbot
ii  certbot                          0.28.0-1~deb9u3                                                         all          automatically configure HTTPS using Let's Encrypt
ii  python-certbot-apache            0.28.0-1~deb9u1                                                         all          transitional dummy package
ii  python3-certbot                  0.28.0-1~deb9u3                                                         all          main library for certbot
ii  python3-certbot-apache           0.28.0-1~deb9u1                                                         all          Apache plugin for Certbot
```

Thanks you very much for your advice and/or explanation or correction.
If you need more details, please ask.

Thanks for your great work.

Pierre.

**Comment by iliarostovtsev** [comment]
Hi, Pierre.

> I have tried to apply the suggestion of replace everything in line 2437 of feature-ssl.pl with

There is no reason to apply any patches as Virtualmin 6.16 already has those.

> The ./install.sh -s was done

What does this supposed to mean? This command is only used to setup repos and exit. What command exactly did you use to install Virtualmin?

> Since few weeks, we notice that Virtualmin with certbot still not copy `/etc/letsencrypt` renewed certificates files to `/home//ssl.*`

Check template paths for keys under **System Settings ⇾ Virtualmin Virtual Servers ⇾ Configuration: SSL settings**.

> On cfg file, I noticed that letsencrypt_renew is at 2, but auto_letsencrypt at 0. It may be the problem ?

**`letsencrypt_renew`** usually set to **`1`** or **`0`**, as **`2`** perhaps something left from older installs, however looking at the code, I don't see where it could trigger a problem. 

**`auto_letsencrypt`** option is used to request Let's Encrypt certificate at domain creation time. Not related.

> ssl_cert_expiry=1622563790 letsencrypt_last_failure=1570720689 letsencrypt_last_success=1614791395

It looks like the last failure was in 2019 and and that the certificate is valid until June 1, 2021. I suppose the renewal was run manually?

I suggest you looking at **[`feature-ssl.pl -> sub apply_letsencrypt_cert_renewals {}`](https://github.com/virtualmin/virtualmin-gpl/blob/master/feature-ssl.pl#L2563-L2626)** and seeing what could prevent certificates from being automatically renewed in your case?

Later can you provide us a diff of **`/etc/webmin/virtual-server/domains/143374749729895`** before and after **Automatically renew certificate** first set to **No** and then again to **Yes**, please?

**Comment by Sn4kY** [comment]
Hi.
All template path are default 
```
Template for private key path 	Default (~/ssl.key)  
Template for certificate path 	Default (~/ssl.cert)  
Template for CA certificate path 	Default (~/ssl.ca)  
Template for combined certificate path 	Default (~/ssl.combined)  
Template for key and certificates path 	Default (~/ssl.everything) 
```

> Later can you provide us a diff of /etc/webmin/virtual-server/domains/143374749729895 before and after Automatically renew certificate first set to No 
I have changed the domain ID because of missclick to "REQUEST certificate" instead of "only update renewal". but i have dozens of domains concerned by this behaviour, so...
```
--- 149019730612153_BEFORE_Automatically_renew_certificate_switch_to_NO 2021-05-07 14:44:13.938686541 +0200
+++ 149019730612153_AFTER_Automatically_renew_certificate_switch_to_NO  2021-05-07 14:45:13.121426559 +0200
@@ -5 +5 @@
-lastsave=1620338543
+lastsave=1620391500
@@ -165 +165 @@
-letsencrypt_renew=2
+letsencrypt_renew=0
@@ -166,0 +167 @@
+letsencrypt_dwild=
```
and switch back to YES :
```
--- 149019730612153_AFTER_Automatically_renew_certificate_switch_to_NO  2021-05-07 14:45:13.121426559 +0200
+++ 149019730612153_AFTER_Automatically_renew_certificate_switch_BACK_to_YES    2021-05-07 14:46:16.992066778 +0200
@@ -5 +5 @@
-lastsave=1620391500
+lastsave=1620391567
@@ -165 +165 @@
-letsencrypt_renew=0
+letsencrypt_renew=1
```



Well... OK, after reading all comments in https://github.com/virtualmin/virtualmin-gpl/blob/master/feature-ssl.pl#L2563-L2626 , I've discover that :
> 	# Is it time? Either the user-chosen number of months has passed, or
> 	# the cert is within 21 days of expiry
There is no more "user-chosen" in "Domain" -> "Server Configuration" -> "SSL Certificate" -> "Let's Encrypt" tab
and why 21 days ? Usually Let's Encrypt's certificates are renewed 1 month before expiry.
That's confusing (both for end client, and for system administrators)

After changing the value to 31 days, and restarting webmin, the collectinfo.pl to the job correctly.

Well, sorry for this misunderstanding, but I think that the modification should be documented (only "Let's Encrypt auto-renewal has been simplified and is on by default." on the Webmin Changelog is a little cheap), and revert back to 30/31 days by default, like Let's Encrypt recommends https://letsencrypt.org/docs/faq/#what-is-the-lifetime-for-let-s-encrypt-certificates-for-how-long-are-they-valid

Best Regards

N.B. : ./install.sh -s is just beacause you ask some people to do this in other topics related to errors with LE/certbot

**Comment by jcameron** [comment]
I think I chose 21 because Let's Encrypt sends warning emails 21 days before expiry. But we can make this configurable..

**Comment by iliarostovtsev** [comment]
> I think I chose 21 because Let's Encrypt sends warning emails 21 days before expiry. But we can make this configurable..

Cool, Jamie. Thanks!
