### ISSUE TITLE
Feature: remove false-positive warnings for Let's Encrypt generated keys with ec-384 keylengths

### ISSUE THREAD

**Issue by trocster** [virtualmin/virtualmin-gpl#289]
https://github.com/virtualmin/virtualmin-gpl/blob/dd15d612a99303079e3a95dcb704b5342176bc1f/feature-ssl.pl#L1263

with regex "(RSA |EC )?PRIVATE KEY" generates warnings for Let's Encrypt keys generated with the ec-384 "keylength" as they have a ec parameter stanza preceding the key material. These keys are generated and renewed by a central LE daemon not virtualmin itself. Here is an example key structure: 

```
-----BEGIN EC PARAMETERS-----
....=
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
...
....
....==
-----END EC PRIVATE KEY-----
```

generating a warning: 
`
Warning!  The SSL key file /home/site/ssl.key for site.example.com is invalid : Data starts with -----BEGIN EC PARAMETERS----- , but expected -----BEGIN (RSA |EC )?PRIVATE KEY----- `

Virtualmin TLS/SSL enabled sites is fully functional and apache accepts the certs and keys with ec-parameters with out issue. We appreciate this is not a virtualmin issue so is only a nice to have feature request.

**Comment by jcameron** [comment]
Thanks for pointing this out - it will be fixed in the next release.
