### ISSUE TITLE
Wordpress install script fail with php 7+

### ISSUE THREAD

**Issue by Vagrantin** [virtualmin/virtualmin-gpl#29]
With the PHP script execution mode set to FPM, installing WordPress with the built-in installer script the install fail because it requires ``mysql`` module but this module has been removed in [PHP 7.0.0](http://php.net/manual/en/intro.mysql.php).

So in version 7+ the require mode has to be ``mysqli``

On my side i updated the wordpress.pl script with a condition if PHP < 7.0 I'm returning ``mysql`` otherwise I'm returning ``mysqli``.

I have test the script on a Debian 9 with Webmin 1.860 / Virtualmin 6.01 and PHP 7 only.

I'm happy to do a PR if you wish.

kind regards

Matth

**Comment by jcameron** [comment]
What's the exact error message you get from Virtualmin when trying to install Wordpress? We should be handling this case automatically (via this code : https://github.com/virtualmin/virtualmin-gpl/blob/master/scripts-lib.pl#L953)

**Comment by Vagrantin** [comment]
Hello @jcameron ,

Sorry for the late feedback here is the output when using the built-in script:
```
Downloading http://scripts.virtualmin.com:80/wordpress-4.9.zip (9.92 MB) ..
     Received 1024 bytes (0 %)
     Received 1017 kB (10 %)
     Received 1.99 MB (20 %)
     Received 2.98 MB (30 %)
     Received 3.97 MB (40 %)
     Received 4.96 MB (50 %)
     Received 5.96 MB (60 %)
     Received 6.95 MB (70 %)
     Received 7.94 MB (80 %)
     Received 8.93 MB (90 %)
     Received 9.92 MB (100 %)
.. download complete.

PHP module _mysql_ is required ..
.. could not find global php.ini file
```
As soon as I use my modified script it's working properly but, I'm maybe fixing only a symptom and not the root cause.

Kindly
Matth

**Comment by jcameron** [comment]
Does a file named `php.ini` exist anywhere under your `/etc/` directory?

**Comment by Vagrantin** [comment]
Yes, I have several ``php.ini`` files under ``/etc/``

````
./php/5.6/cli/php.ini
./php/5.6/fpm/php.ini
./php/7.0/apache2/php.ini
./php/7.0/cgi/php.ini
./php/7.0/cli/php.ini
./php/7.0/fpm/php.ini
````
**Couple of details:**
I'm using php7.0 in fpm mode
for recall I'm experiencing this install issue only in fpm mode...
I don't use php5.6 anymore and have it uninstalled but still remain some config files.

hope that help.

Matth

**Comment by Vagrantin** [comment]
I just notice that, virtualmin is using the folder ``/etc/php/5.6/fpm/pool.d/`` instead of ``/etc/php/7.0/fpm/pool.d/`` one...
![image](https://user-images.githubusercontent.com/19902259/33593479-f9de4902-d9d2-11e7-8594-caa1437a5709.png)

Even if the serve template is set to use highest or 7.0 version 
![image](https://user-images.githubusercontent.com/19902259/33593515-225f7ef0-d9d3-11e7-85a1-4e7243b4d464.png)

not sure this is related or not, maybe the script got confused...

my2 cents
Matth

**Comment by Vagrantin** [comment]
hum this issue was due to un-clean uninstall of php5.6 on Debian 9, after a full manual cleanup I'm not experiencing the issue, thanks for the help !
