### ISSUE TITLE
Virtualmin.com server is down

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#291]
https://www.virtualmin.com/ fails to load.

https://downforeveryoneorjustme.com/virtualmin.com agrees it's down.

Updates fail: `W: Failed to fetch http://software.virtualmin.com/vm/6/gpl/apt/dists/virtualmin-jessie/Release.gpg  System error resolving 'software.virtualmin.com:http' - getaddrinfo (110: Connection timed out)`

**Comment by jcameron** [comment]
It's back now - looks like our colo had a network glitch
