### ISSUE TITLE
Issues with SSL Cert Sharing NGINX

### ISSUE THREAD

**Issue by MarcHagen** [virtualmin/virtualmin-gpl#296]
Webmin version | 1.974
-- | --
Virtualmin version | 6.16 Pro

I cannot link subdomains ssl to the master domain when i switched to nginx.
With apache this worked great!

I was digging a bit in the code, perl is not my main language but still it's all the same.
I believe it's because the function `find_matching_certificate_domain` doesn't look for the nginx ssl key `virtualmin-nginx-ssl` and only for the apache key `ssl`

https://github.com/virtualmin/virtualmin-gpl/blob/7f61136e9161cae596dec19b02f92b0445663e80/feature-ssl.pl#L1714-L1731

When change this line 
```perl
$_->{'ssl'}
```
to 
```perl
( $_->{'ssl'} || $_->{'virtualmin-nginx-ssl'} ) &&
```

the linked worked perfectly with `virtualmin modify-web --domain domain.nl --link-ssl-cert`

I also noticed that allot of code in this file only is relying on `$_->{'ssl'}` Maybe there should be a wrapper function to include the nginx notation and the apache notation that returns true/false if the domains has ssl enabled?

OR just update the ssl=1 even for nginx :)

**Comment by jcameron** [comment]
Thanks for pointing this out - we'll fix it properly in the next release
