### ISSUE TITLE
Features that have not been backuped are restored

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#299]
I'm using the backup & restore function to transfert virtual servers betwwen hosts.

I'am explicitly not backing up `Logrotate configuration`
![Screenshot 2021-06-24 at 12 48 03](https://user-images.githubusercontent.com/45786226/123253467-cad18b00-d4ed-11eb-8de1-d176316b5e86.png)

When restoring the backup I select `Restore all features` which I understand will only backup the features available in the backup.
![Screenshot 2021-06-24 at 12 59 33](https://user-images.githubusercontent.com/45786226/123253648-f8b6cf80-d4ed-11eb-85aa-4e74e3394b43.png)

On the preview screen there is no mention of `Logrote configuration` which might be restored/created
![Screenshot 2021-06-24 at 12 59 51](https://user-images.githubusercontent.com/45786226/123253800-29970480-d4ee-11eb-886b-f9c0a2e430ad.png)

However while restoring it clearly say that log file rotation is being setup
![Screenshot 2021-06-24 at 13 03 12](https://user-images.githubusercontent.com/45786226/123253881-45020f80-d4ee-11eb-9a8b-b7db8137a44a.png)

And afterwards there is a new entry under `Webmin > System > Log file Rotation`
![Screenshot 2021-06-24 at 13 05 33](https://user-images.githubusercontent.com/45786226/123254009-68c55580-d4ee-11eb-9e39-f362f2cdf30d.png)

Which will throw an error next time logrotate is run, as there already exists a line handlying the files
![Screenshot 2021-06-24 at 13 05 40](https://user-images.githubusercontent.com/45786226/123254065-7bd82580-d4ee-11eb-8eda-279db09f3f96.png)

Is this due to the Log file rotation section in the Server Template?
![Screenshot 2021-06-24 at 13 18 49](https://user-images.githubusercontent.com/45786226/123254390-e2f5da00-d4ee-11eb-8e6b-7f9908908bb1.png)

**Comment by jcameron** [comment]
So if restoring a backup re-creates a missing domain, it will re-create all features that were enabled originally (with default settings), even if they weren't included in the backup. 

This can be avoided when using the `virtualmin restore-domain` shell command to restore a backup, by providing the `--only-features` flag.

**Comment by PitWenkin** [comment]
> This can be avoided when using the virtualmin restore-domain shell command to restore a backup, by providing the --only-features flag.

Which would be the same as using the `Only those selected below…` radio button on the restore screen?

**Comment by jcameron** [comment]
No - that controls which features are restored from the backup, which is different from which features are enabled (with the default settings) for re-created domains.
