### ISSUE TITLE
Let's Encrypt scheduled - does't restart Apache to apply + CA bundle not still written

### ISSUE THREAD

**Issue by qooob** [virtualmin/virtualmin-gpl#3]
1. I have tested on 3 domains before posting this as an issue. After new certificates are issued and downloaded - Apache is not restarted and certificates are not applied.

2. We [discussed it here and you said](https://github.com/virtualmin/virtualmin/issues/30#issuecomment-282635472) that next release of Virtualmin will support CA bundle. It's still missing.

**Comment by jcameron** [comment]
I think I see the cause of this - it will be fixed in the next Virtualmin release.
