### ISSUE TITLE
MySQL password length limit

### ISSUE THREAD

**Issue by adbario** [virtualmin/virtualmin-gpl#30]
While creating a new virtual server with database, the MySQL password length is always set to 16. Option "Characters for random passwords" works for DB passwords too, but there doesn's seem to be a way to change the initial password length.

There's a manual option to allow longer database user names "mysql_user_size=80" (default 16), is there already or is it possible to have similar setting for database passwords?

**Comment by jcameron** [comment]
Yes, you can change the random password length via the `passwd_length=` field in `/etc/webmin/virtual-server/config

**Comment by adbario** [comment]
Thanks for quick answering. Sadly that doesn't change the length of DB password, only the username pass.

**Comment by jcameron** [comment]
My apologies, actually the mysql password is fixed to 16 characters.

I will fix this in the next release so that the config option is respected.
