### ISSUE TITLE
No individual port for compatible S3 storage possible.

### ISSUE THREAD

**Issue by StefanZi** [virtualmin/virtualmin-gpl#300]
When modifying the server name for Amazon S3 cloud storage provider to add a compatible provider, there is no chance to modify the used TCP port. Only the default `443` is possible.

The server name is checked to be a valid IP address, so something like `minio.my-domain.com:9000` does not work and results in the error message `S3 compatible server must be a valid hostname`.

I propose to change the validation and underlying code to support different ports, too.

It might be worth thinking about a more generalized approach for checking hostnames which includes port specifications (or is configurable to do so or not).

**Comment by jcameron** [comment]
Good idea, I'll add support for that in the next release.

https://github.com/virtualmin/virtualmin-gpl/commit/cd13b493bf58b976088fc74bb3d50d5355fd27f1
