### ISSUE TITLE
Transfer Virtual Server only uses port 22

### ISSUE THREAD

**Issue by Zen4All** [virtualmin/virtualmin-gpl#301]
When trying to move a virtual server from one server to another, this fails due to the fact that port 22 is always used by the script. Is it possible to change this any where? Or add a new field where the port for SSH on the destination server can be filled in?

**Comment by jcameron** [comment]
You can enter the destination in the format hostname:port if the remote SSH server is running on a different port.

**Comment by Zen4All** [comment]
thx
