### ISSUE TITLE
Is there a way to use mdbox?

### ISSUE THREAD

**Issue by hydazz** [virtualmin/virtualmin-gpl#303]
Hi, I need to host some mail accounts with over 30,000 emails, and Maildir is not a suitable option for me (I have tried it - it is not a pleasant experience). Is there a way I can _hack_ virtualmin/webmin to utilise mdbox? I have tried to set `mail_location` to `mail_location = mdbox:~/Maildir` but this did nothing. Probably a noob question - I'm still wrapping my head around dovecot and postfix.

**Comment by jcameron** [comment]
Do Dovecot and Postfix support mdbox? If so, and if they can be configured to manually deliver to and read from a mdbox-format inbox, the rest of Virtualmin should be happy.

**Comment by chris001** [comment]
@hydazz @jcameron See issues where this `mdbox` was first requested, in #138 then later in #194
