### ISSUE TITLE
"Create alias websites by: Creating Redirect virtual host" - only creating redirect for non ssl

### ISSUE THREAD

**Issue by hayden-t** [virtualmin/virtualmin-gpl#307]
I just found out about this neat feature, but when I create the server alias after setting this setting it only creates redirect for port 80 non ssl from alias to parent. It should do 443/ssl too.

**Comment by hayden-t** [comment]
Maybe it cant be done ? As i tried editing the apache file, and the redirect on ssl gets blocked by ssl error about cert for the server being used rather than the alias domain.

**Comment by hayden-t** [comment]
Actually I got it working, i just needed to copy the SSL details from the parent to alias in the virtualhost block
```
<VirtualHost [IP]:443>
    SSLEngine on
    SSLCertificateFile /home/[domain]/ssl.cert
    SSLCertificateKeyFile /home/[domain]/ssl.key
    SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
    SSLCACertificateFile /home/[domain]/ssl.ca
    ServerName [domain].com
    ServerAlias www.[domain].com
    ServerAlias mail.[domain].com
    RedirectPermanent / http://www.[domain].com.au/
</VirtualHost>
```

**Comment by jcameron** [comment]
Supporting this kind of SSL alias domain is something we're still working on. I'll update this bug when it's done..

**Comment by jcameron** [comment]
FYI, the next release of Virtualmin will fix this by allowing redirects from HTTP to HTTPS that preserve the hostname when it's an alias domain.
