### ISSUE TITLE
PHP imports are messy and result in errors

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-gpl#309]
Several users see import errors due to the shotgun approach of importing every possible module name (e.g. `imagick.so` and `pecl-imagick.so`) and think it means something is wrong, and spend a lot of time trying to "fix" the problem. (one example thread with two different users going down the same dead end path: https://forum.virtualmin.com/t/about-wordpress-imagick/112221)

Is it possible to be more selective? i.e. detect what the actual module name is for the OS and PHP version installed rather than multiple imports?

**Comment by jcameron** [comment]
Yes, I'll look into making this part of the process more selective and quieter.

**Comment by jcameron** [comment]
Ok, I've committed fixes to clean up the output
