### ISSUE TITLE
Wordpress Install Script - Debian Buster - pecl-imagick problems

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#310]
Webmin version | 1.981
Virtualmin version | 6.17

Have been too busy to keep up with development, but noticed a lot of installer script work recently.

Did an virtualmin update and getting errors when running the wordpress installer script on new domains. 

Still researching it but putting the error up for posterity.

php*-imagick is already installed

PHP module pecl-imagick is recommended ..
Installing package php-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php-pecl-imagick ..
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-imagick
.. install failed!
Installing package php-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-imagick
.. install failed!
Installing package php-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-imagick
.. install failed!
Installing package php-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-imagick
.. install failed!
Installing package php-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-imagick
.. install failed!
Installing package php-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-imagick
.. install failed!
Installing package php-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php-pecl-imagick
.. install failed!
Installing package php5.6-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php5.6-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php5.6-pecl-imagick
E: Couldn't find any package by glob 'php5.6-pecl-imagick'
E: Couldn't find any package by regex 'php5.6-pecl-imagick'
.. install failed!
Installing package php7.0-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php7.0-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.0-pecl-imagick
E: Couldn't find any package by glob 'php7.0-pecl-imagick'
E: Couldn't find any package by regex 'php7.0-pecl-imagick'
.. install failed!
Installing package php7.1-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php7.1-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.1-pecl-imagick
E: Couldn't find any package by glob 'php7.1-pecl-imagick'
E: Couldn't find any package by regex 'php7.1-pecl-imagick'
.. install failed!
Installing package php7.2-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php7.2-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.2-pecl-imagick
E: Couldn't find any package by glob 'php7.2-pecl-imagick'
E: Couldn't find any package by regex 'php7.2-pecl-imagick'
.. install failed!
Installing package php7.3-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php7.3-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.3-pecl-imagick
E: Couldn't find any package by glob 'php7.3-pecl-imagick'
E: Couldn't find any package by regex 'php7.3-pecl-imagick'
.. install failed!
Installing package php7.4-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php7.4-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.4-pecl-imagick
E: Couldn't find any package by glob 'php7.4-pecl-imagick'
E: Couldn't find any package by regex 'php7.4-pecl-imagick'
.. install failed!
Installing package php8.0-pecl-imagick ..
Installing package(s) with command apt-get -y -f install php8.0-pecl-imagick ..

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php8.0-pecl-imagick
E: Couldn't find any package by glob 'php8.0-pecl-imagick'
E: Couldn't find any package by regex 'php8.0-pecl-imagick'
.. install failed!
.. failed to install!
Configuring webserver PHP settings ..
.. already done.

**Comment by jcameron** [comment]
This isn't a problem, those messages about installing an optional PHP package are just too verbose. We're working on fixing it..

**Comment by rionwolf** [comment]
shut up jcameron you know nothing its not optional if the installation fails because of it!!!! Im working on finding the real solution, dont act like you know a thing, go back to your dark hole troll.

**Comment by iliarostovtsev** [comment]
> you know nothing its not optional if the installation fails because of it

Jamie is the author, he knows! Installation never fails because of it.

> dont act like you know a thing, go back to your dark hole troll.

I think you need to learn some manners but most importantly sign up for a doctor's visit to get some help, which you apparently need!
