### ISSUE TITLE
Disable Virtual Server Seems to not resolve to host after a while

### ISSUE THREAD

**Issue by neural-oD** [virtualmin/virtualmin-gpl#311]
Hi,
Not sure if someone can replicate, but I have this issue. I went in on the GUI front end, and used: "Disable Virtual Server".
Everything appeared correct, and checking on the website gave the disabled page with the custom message. However, a couple of days later, I checked again, and that url could not be resolved. The whois info is still pointing to my servers, but the server isn't responding at all. It's as if it has been removed. I'm not sure if this is because something on BIND is not responding now to requests at all? 
Please could someone test and confirm issue.
Thanks

**Comment by jcameron** [comment]
By default, Virtualmin will disable the DNS domain as well when disabling a virtual server .. which will cause it to eventually fail to resolve.

You can configure this at System Settings -> Virtualmin Configuration -> Features to deactivate when disabling

**Comment by neural-oD** [comment]
Thanks Jamie, for guiding me to this sitting.
