### ISSUE TITLE
"Backup failed" email not sent when a server reaches disk full during backup

### ISSUE THREAD

**Issue by beat** [virtualmin/virtualmin-gpl#313]
It during the last ZIP of the backup a disk-full state is reached, the "Backup failed" mail is not sent out (due to disk full state).

This results in failed and unexistant backups getting unnoticed, which is a potentially catastrophic, and thus major issue imho. 

But when the backup is delete, there is plenty of disk available to send the mail.

1. Suggestion 1:  Send the backup failed mail **after** deleting the failed ZIP file, *instead of immediately when the disk is **still full**, which prevents the sending of the mail.
2. Suggestion 2: Never fill-up completely the disk with a backup ZIP. Maybe leave at least 1% of the disk free.

**Comment by jcameron** [comment]
Email is sent at the very last step in the scheduled backup process though.

Is the partial ZIP file still being left around on your system when you run out of disk space?

**Comment by neural-oD** [comment]
Hi @beat 
I didn't get the exact issue as you, however one of my clients was trying to do a backup, and we have some issues too. Wonder if it could be the latest update. I raised something in the forum: [https://forum.virtualmin.com/t/backup-some-options-greyed-out-output-file-incorrect/112513](url)

Also, another thing, which I will raise here as a separate issue, is that when trying to do a zip file from within the file manager, it seems if the quota is breached while creating a zip, then there's a distinct possibility to lose files and folders....this could be potentially related but not sure.

**Comment by beat** [comment]
@jcameron No, the system had almost enough fee space.

Something like 19 GB of free disk space, and the largest tar.gz backup takes around 20 GB (second largest takes 7 GB).

And the failed backup file gets deleted, as when checking the system, the free disk space is again around 18-24 GB free.

In some cases, I got the failed backup mail, in some cases I didn't for several days in a row.

Now I have split that largest domain into two domains, so that each backup is around 10 GB, to avoid that problem, so can't reproduce the issue anymore.
