### ISSUE TITLE
New default domain has email selected even when email is disabled

### ISSUE THREAD

**Issue by nabab** [virtualmin/virtualmin-gpl#316]
Hi, 

Great job with all the apps, thanks for that!

I ran into a bug just after installing Virtualmin: I disabled all the email features in Features and plugins, then I went through the wizard, which didn't ask anything about mail, anti-virus, spamAssassin as expected. It offers to create a default domain, which I did.
Once the default domain created Cloudmin was telling me there were configuration problems on this machine, so I ran the config checker which said:

*.. problems found : The feature Mail for domain cannot be disabled, as it is used by the following virtual servers : xxx.xxx.xx*

So it had created the default domain with email on, but I couldn't deactivate it as the checkbox wasn't there. I had to reactivate the email feature, remove it from the domain (the checkbox was checked), then deactivate it again to not see this message anymore.

Thanks for your time

**Comment by jcameron** [comment]
That is odd, because the default domain created in the post-install wizard doesn't have email enabled.

Unless you enabled it later?

**Comment by jcameron** [comment]
I will have to see if I can reproduce this. Because normally it's not possible to disable a global feature if any existing domain is using it ..

**Comment by jcameron** [comment]
Ok I get it ... but from looking at the code, I wasn't able to see any way this could happen in Virtualmin, as that default domain never gets the email feature enabled in the first place.

Was it perhaps created in an older version of Virtualmin?

**Comment by nabab** [comment]
I did a fresh install on Ubuntu 20.04, disabled email, created sa new default domain.. .and I didn't get the error again, sorry for the waste of time!

**Comment by jcameron** [comment]
Do you get the same error if you SSH into the Virtualmin system as `root` and then run `virtualmin check-config` ?

**Comment by nabab** [comment]
I did a fresh install, this time with Debian 10, and I am getting the exact same output from the command line (on the virtualmin machine), ending with all OK.

Then I add the machine to Webmin and get this:

```
Checking SSH login ..
.. logged in OK.
Checking Webmin login ..
.. logged in OK.

Fetching current status ..
.. status successfully retrieved (Virtualmin - Config errors found)

Checking Virtualmin configuration ..
.. errors found : 0
```

ANd I still get the same message after doing a configuration check on Cloudmin (but fine on Virtualmin):

`.. problems found : The feature Mail for domain cannot be disabled, as it is used by the following virtual servers : xxxx.xxx.xx`
