### ISSUE TITLE
Clone Virtual Server FPM Port not configured in httpd.conf

### ISSUE THREAD

**Issue by ecropolis** [virtualmin/virtualmin-gpl#319]
Whenever I clone a virtual server, I have to go to the PHP FPM configuration and get the port number (listen = localhost:8061) and then go to both the ssl/non-ssl httpd.conf files and update the port setting at: SetHandler proxy:fcgi://localhost:8061. Otherwise the server only will output the message 'file not found'.

Operating system | CentOS Linux 8
Webmin version | 1.981 | Usermin version | 1.823
Virtualmin version | 6.17 | Authentic theme version | 19.83-2

**Comment by jcameron** [comment]
Ok, I see what can cause this - it will be fixed in the next release.

https://github.com/virtualmin/virtualmin-gpl/commit/22eba57b6c6f3b125ce086091964f35339d24133
