### ISSUE TITLE
Change domain/user PHP-FPM config not updated

### ISSUE THREAD

**Issue by ecropolis** [virtualmin/virtualmin-gpl#320]
I changed the domain name of a virtual server (and allowed Vmin to also update the username and it caused the PHP-FPM to fail to re-start.
`Oct 20 15:07:20 z.com systemd[1]: Starting The PHP FastCGI Process Manager...
Oct 20 15:07:20 z.com php-fpm[9999]: [20-Oct-2021 15:07:20] ERROR: [pool 9999] cannot get uid for user 'zzzzzzz'`

I updated the php-fpm ini file for the virtual server with the correct username and that fixed the issue.

However, I had another issue with httpd service also failing.
The home directory name was also updated. Another domain/site in the domains folder had an SSL cert and the configured path was not updated for it. I didn't check if other paths were not updated. I didn't need this domain any longer so deleted it and that cleaned up that problem.

`Oct 20 15:11:53 z.com httpd[9999]: SSLCertificateFile: file '/home/user/domains/zzzzzz.com/ssl.cert' does not exist or is empty
Oct 20 15:11:53 z.com systemd[1]: httpd.service: Main process exited, code=exited, status=1/FAILURE
Oct 20 15:11:53 z.com systemd[1]: httpd.service: Failed with result 'exit-code'.
Oct 20 15:11:53 z.com systemd[1]: Failed to start The Apache HTTP Server.
`

**Comment by marclaporte** [comment]
@ecropolis I know it's been a long time but it would be much appreciated if you can confirm if the issue is reproducible with the latest stable Virtualmin (7.5 as of now)

Thanks!

**Comment by ecropolis** [comment]
Hi Marc,

I believe things have been stable now on that issue. I did just do a clone
of a template site that I've been using for a long time to base a
foundation for a new site. It worked fine... no detectable server downtime
in the process. Thank you so much for your work on this and for following
up with me!

Warren

Warren Gwartney
Principal Consultant

*Ecropolis, LLC*
Schedule time with me <https://calendar.app.google/2pKWyEKzvPcxqhLZ7>
817.755.0575 (mobile)
214.945.0506 (main)

[image: Ecropolis]
<https://ecropolis.com?utm_campaign=email-signatures&utm_source=warren&utm_medium=email>
ecropolis.com
<https://ecropolis.com/?utm_campaign=email-signatures&utm_source=warren&utm_medium=email>
Help us grow by leaving a review! <https://g.page/r/Cd_Y5pXyrUzPEBM/review>

**Comment by iliajie** [comment]
This issue has been fixed too. Thanks for the heads-up, Marc!
