### ISSUE TITLE
procmail no DNS / bounce

### ISSUE THREAD

**Issue by ghost235** [virtualmin/virtualmin-gpl#326]
I have a user which is over quota but procmail not return any error.

/var/log/mail.log :

`postfix/local[18897]: 16E94B1D012: to=<_user_@_server_>, orig_to=<_email_@_domain_>, relay=local, delay=123, delays=122/0/0/0.71, dsn=2.0.0, status=sent (delivered to command: /usr/bin/procmail-wrapper -o -a $DOMAIN -d $LOGNAME)`

/var/log/procmail.log : 

`procmail: Quota exceeded while writing "/home/_user_/homes/info/Maildir/tmp/1635844454.19097_0._server_"
procmail: Quota exceeded while writing "/home/_user_/homes/info/Maildir/tmp/1635844454.19097_1._server_"
From _sender_  Tue Nov  2 10:14:13 2021
 Subject: Test
  Folder: **Bounced**                                                    301070
Time:1635844454 From:_sender_ To:_email_ User:_user_ Size:301122 Dest: Mode:None
`

**Comment by jcameron** [comment]
Is email just being lost rather than bounced back to the sender in this situation?

**Comment by ghost235** [comment]
looks like this or you know a destination where I could find this mails.

**Comment by jcameron** [comment]
Does this domain have spam filtering enabled? Also, what does the `/etc/procmailrc` file contain on this system?

**Comment by ghost235** [comment]
No I've MailScanner infront so no spam filtering from virtualmin.

`cat /etc/procmailrc
LOGFILE=/var/log/procmail.log
TRAP=/etc/webmin/virtual-server/procmail-logger.pl
:0wi
VIRTUALMIN=|/etc/webmin/virtual-server/lookup-domain.pl $LOGNAME
EXITCODE=$?
:0
* ?/usr/bin/test "$EXITCODE" = "73"
/dev/null
EXITCODE=0
:0
* ?/usr/bin/test "$VIRTUALMIN" != ""
{
INCLUDERC=/etc/webmin/virtual-server/procmail/$VIRTUALMIN
}
DEFAULT=$HOME/Maildir/
ORGMAIL=$HOME/Maildir/
DROPPRIVS=yes
:0
$DEFAULT
`

**Comment by jcameron** [comment]
Try enabling email bouncing when quota is full by SSHing in as `root` and running `virtualmin set-spam --quota-behavior bounce`

**Comment by ghost235** [comment]
It's odd.
If I create a new user it works.
In an other domin it works.
with this special user works not.

Any way.... Thanks for help ... I will recreate th user
