### ISSUE TITLE
domain name change do not change  TLS certificate domain name

### ISSUE THREAD

**Issue by aqueos** [virtualmin/virtualmin-gpl#327]
hi,

 when changing the domain name of a website the certificate part is not modified by the name change leading to certificate problem between sites ( if i invert 2 domains between a test and production site for example)

  If a domain name is changed it seems it  should change the associated certificate if:

- self signed certificate
- letsencrypt one
 

to avoid any issue and being coherent :)

regards,
Ghislain.

**Comment by jcameron** [comment]
That's a good suggestion - in the old days when an SSL cert had to be requested from a CA manually it wasn't possible to automatically generate a new one when a domain was renamed, but with Let's Encrypt this has changed.

I'll update this bug when this has been implemented..

**Comment by jcameron** [comment]
Turns out this was easy - look for this feature in the next Virtualmin release.
