### ISSUE TITLE
tranfering virtual server to new host results in problems

### ISSUE THREAD

**Issue by HonkXL** [virtualmin/virtualmin-gpl#328]
I transfered some virtual servers from one virtualmin host to an new one.
Both machines running CentOS 8 with indetical software and software versions!
PHP 7.2 (default), 7.4 and 8.0 is installed and running in FPM mode.

Transfer worked fine on the destination machine I had the following problems:
* IPv6 diabled for domain -> on source machine IPv4 and IPv6 was enabled. Why is it not migrated to use the IPv6 default domain on destination?
* PHP scripts are not working. Apache brings timeouts in the log. I think a port setting for the fpm in apache config is wrong. I had not enough time to find out what was wrong. Solution was to disable PHP in Virtualmin for each server and sub-servers and re-enable it again (without changing anything else). This resulted in a running page again.

**Comment by jcameron** [comment]
Regarding the IPv6 issue, is v6 enabled globally on the destination system? And if so, does a Virtualmin configuration check report it as enabled?

Regarding the PHP issue, which PHP execution mode are you using? If it's FPM, it does seem like you're hitting a bug related to port allocation.

**Comment by HonkXL** [comment]
IPv6:
Check of configuration says:
![image](https://user-images.githubusercontent.com/16715040/142822069-5a6c30de-9e50-4724-b051-cebd973e7d54.png)

IP-Settings of VirtualMin shows that it is enabled:
![image](https://user-images.githubusercontent.com/16715040/142822137-7efc2e23-eff4-4b6b-bbd8-a68f28d2bb06.png)


PHP: yes, it's FPM on source and destination machine. Same versions installed, too - this means 7.2, 7.4 and 8.0 FPM are installed and operational for different domains / subdomains!

**Comment by jcameron** [comment]
So on the source system, before you did the migration, did the domain have it's own private IPv6 address? Or was it using the system's shared IPv6 address?

**Comment by HonkXL** [comment]
Source and destination systems had a shared IPv6 and IPv4 address. No private addresses used!

**Comment by jcameron** [comment]
On the destination system, what is the `ip6enabled` option in `/etc/webmin/virtual-server/config` set to?

Also, how are you doing the transfer to the new system exactly?

**Comment by HonkXL** [comment]
ip6enabled = 0 in config.
But that's the ip config in VirtualMin:
![grafik](https://user-images.githubusercontent.com/16715040/143411959-702ed936-7554-40f3-b191-3be2d0a17c2b.png)

This was how I transfered it:
![grafik](https://user-images.githubusercontent.com/16715040/143412153-b336888c-193c-402f-8cc0-02fc85121b38.png)

And this was the ip config on source:
![grafik](https://user-images.githubusercontent.com/16715040/143412293-145a65cf-8101-4938-a4e0-471fc1cd2f8d.png)

**Comment by jcameron** [comment]
Ok, having `ip6enabled` set to `0` is the cause of the problem - this means IPv6 is disabled globally in Virtualmin.

Just edit that file and change the line to `ip6enabled=1` . In future releases, we will make this the default.

**Comment by HonkXL** [comment]
Tested with ip6enabled = 1 -> this works.
I don't understand, why I have to enable ipv6 for Virtualmin in a extra config, while it is already enabled for the system (in ip settings, for virtual servers in Virtualmin and so on).

**Comment by jcameron** [comment]
Yes, this is a bug - we shouldn't require an extra step to enable IPv6. I've fixed this for future installs.
