### ISSUE TITLE
save_user.cgi  doesn't work - times out, after long wait-time

### ISSUE THREAD

**Issue by exetico** [virtualmin/virtualmin-gpl#329]
Hi

Today I tried to login to a Usermin user. That part worked just fine. Hereafter I opened the Inbox, and asked it to order mails based on size. There was 6000+ email in the folder.

After a short while, Usermin returned:
```
500 -
sdbm store returned -1, errno 122, key "cur/_REMOVE__0._REMOVE.ovh.net_subject" at /usr/share/usermin/mailbox/folders-lib.pl line 820.
```

I couldn't do anything, so I signed out. Now I can't use the "Login to Usermin"-function. It's simply timing out, after long waiting time.

![image](https://user-images.githubusercontent.com/3549445/142922877-3c86351f-bb37-4984-ac2a-4efa559dda00.png)

The function are broken for all users on all domains. 

The normal Login-form in Usermin works just fine, if I login directly.

I know it founds a bit odd... But it just hangs 🙃 

The user who faced the user, are also working just fine, if I sign in manually with the login-details.

The server has been restarted, but that didn't change anything.

**Comment by jcameron** [comment]
Looks like a correct mailbox index file is the cause.

Did this user perhaps run out of disk quota?

**Comment by exetico** [comment]
Thank you for answering the question.

Due to other things - hostname and more broke after a system upgrade, I ended up restoring a backup from the day before (yesterday evening). I've not been able to reproduce it, cause I deleted half of the emails in the users account - before trying to do any sorting in the GUI. I'm not sure if it somehow triggered the bug... But, auto-deletion is now enabled, and everything works as expected.

**Comment by jcameron** [comment]
Just curious, which Usermin version are you running there?

**Comment by exetico** [comment]
6.17-3 👍 😄

**Comment by jcameron** [comment]
I think that's the Virtualmin version. What is in the `/etc/usermin/version` file on your system?

**Comment by exetico** [comment]
Oh, sorry.

```
$ cat /etc/usermin/version
1.823
```

**Comment by jcameron** [comment]
Thanks .. and what is on line 820 of /usr/share/usermin/mailbox/folders-lib.pl on your system?

**Comment by exetico** [comment]
```
if ($index->{'lastchange'} != $folder->{'lastchange'} ||
    !$folder->{'lastchange'}) {
        # The mail file has changed .. get IDs and update the index with any
        # that are missing
        local @ids = &mailbox_idlist($folder);

        # Find IDs that are new
        local @newids;
        foreach my $id (@ids) {
                if (!defined($index->{$id."_size"})) {
                        push(@newids, $id);
                        }
                }
        local @mails = scalar(@newids) ?
                        &mailbox_select_mails($folder, \@newids, 1) : ( );
        foreach my $mail (@mails) {
                foreach my $f (@index_fields) {
                        if ($f eq "date") {
                                # Convert date to Unix time
                                $index->{$mail->{'id'}."_date"} =
                                  &parse_mail_date($mail->{'header'}->{'date'});
                                }
                        elsif ($f eq "size") {
                                # Get mail size
                                $index->{$mail->{'id'}."_size"} =
                                        $mail->{'size'};
                                }
                        elsif ($f eq "from" || $f eq "to") {
```

So it's totally something with the sorting I tried. 820 is this one:
`if ($f eq "date") {`

The error started after I tried to sort by size, with 6000+ emails, if I remember correctly.

**Comment by jcameron** [comment]
That's very confusing, because line 820 `if ($f eq "date") {` doesn't access an SDBM database at all, so it's unclear why Perl would have reported that error on that line.

**Comment by exetico** [comment]
As mentioned I has sorted by size, with over 6000 mails. It must have been some kind of "lock"/memory overflow, which triggered it, cause it didn't sort at all. Just executed the code, with no results. After that, I couldn't use the "Login as user". I didn't try to reproduce it the second time - but maybe I should have done that :-)

**Comment by jcameron** [comment]
If you do ever see this again, one possible fix is to delete all `*index*` files in `.usermin/mailbox` under the user's home directory.
