### ISSUE TITLE
PHP sites are not working after migrating to new server

### ISSUE THREAD

**Issue by savjain** [virtualmin/virtualmin-gpl#339]
Steps to reproduce

1. Create multiple virtual servers on source machine with PHP sites.
2. Follow the steps on https://www.virtualmin.com/migrate/ to migrate to new server
3. After migration, some PHP sites may not work due to configuration mismatch.

Error found in Apache log file:
AH01071: Got error 'Primary script unknown\n'

Workaround:
copy files from /etc/php-fpm.d/ directory from source machine to target machine and restart the server.

**Comment by jcameron** [comment]
Was FPM mode in use on both the source and destination systems to execute PHP scripts?

Also, if you create a new domain on the destination system, can it run PHP scripts OK?

**Comment by savjain** [comment]
Yes, FPM mode is in use on both systems. 
This was my production systems and I have already applied the workaround I mentioned above to fix the problem. So not sure if the test is relevant. 
What I noticed is the listening ports on the config files in the php-fpm.d directory was different from the source system. When I copied the config files from the source system, it resolved the issue.

**Comment by jcameron** [comment]
Before you fixed it, was there a mismatch between the port in the FPM pool files and the port in the Apache configuration? That may have been the source of the issue..

**Comment by savjain** [comment]
Yes there was. That is why the workaround works.

**Comment by jcameron** [comment]
Ok, it looks like we have a fix for this implemented already, and it will be included in the next Virtualmin release.
