### ISSUE TITLE
This isn't a problem, those messages about installing an optional PHP package are just too verbose. We're working on fixing it..

### ISSUE THREAD

**Issue by rionwolf** [virtualmin/virtualmin-gpl#342]
This isn't a problem, those messages about installing an optional PHP package are just too verbose. We're working on fixing it..

_Originally posted by @jcameron in https://github.com/virtualmin/virtualmin-gpl/issues/310#issuecomment-925427211_

**Comment by rionwolf** [comment]
this is ignorance by jcameron! why was this thread closed its not fixed nor was any creditable solution offered!

**Comment by rionwolf** [comment]
Believe you need to install with PECL and then enable with docker-php-ext-enable

RUN apt-get update && apt-get install -y \
    libmagickwand-dev --no-install-recommends \
    && pecl install imagick \
	&& docker-php-ext-enable imagick

this solution has helped some people

**Comment by iliarostovtsev** [comment]
> this is ignorance by jcameron! why was this thread closed its not fixed nor was any creditable solution offered!

It's fixed!
