### ISSUE TITLE
Virtualmin API: modify-dns

### ISSUE THREAD

**Issue by tpnsolutions** [virtualmin/virtualmin-gpl#346]
The API is allowing duplicate zone records to be added...

ex.

virtualmin modify-dns --domain mydomain.com --add-record "www A 1.2.3.4"
virtualmin modify-dns --domain mydomain.com --add-record "www A 1.2.3.4"

Both will add without any errors.

The resulting zone file will then be polluted with two identical records.

www.mydomain.com. IN A 1.2.3.4
www.mydomain.com. IN A 1.2.3.4

I think there should be some validation done so that exact matches like the above example result in an error the second time preventing duplicate records.

In comparison, the following would be OK:

virtualmin modify-dns --domain mydomain.com --add-record "www A 1.2.3.4"
virtualmin modify-dns --domain mydomain.com --add-record "www A 5.6.7.8"

The difference here as you can see is the "IP address" the A record is pointing to is different in each request, which is a legit if you've got two different IPs both serving up your domain.

**Comment by tpnsolutions** [comment]
I would imagine this would also affect the Pro version too :-)

**Comment by jcameron** [comment]
Thanks for pointing this out - we'll fix it in the next release.
