### ISSUE TITLE
Wordpress , phpMyAdmin not showing in the Virtualmin GPL 

### ISSUE THREAD

**Issue by skol101** [virtualmin/virtualmin-gpl#353]
Ubuntu 20.04
Webmin version	1.984 	
Usermin version	1.834
Virtualmin version	6.17-3

I've tried manually adding script from here https://github.com/virtualmin/virtualmin-gpl/tree/master/scripts but no luck.

**Comment by jcameron** [comment]
Does the "Install Scripts" link appear on the left menu when you select a domain?

**Comment by skol101** [comment]
Yes, here's sample of available scripts.
<img width="1402" alt="Screenshot 2022-01-13 at 7 42 29" src="https://user-images.githubusercontent.com/53978091/149272568-0d03f2b4-2845-4746-bc6b-5f5af92f5619.png">

**Comment by skol101** [comment]
Hmm , I've just checked -- both scripts appeared in the list.
<img width="833" alt="Screenshot 2022-01-13 at 11 29 37" src="https://user-images.githubusercontent.com/53978091/149303521-f4a0783d-5d6c-4e4b-a9f6-be5d1e13cee9.png">

**Comment by iliarostovtsev** [comment]
> Yes, here's a sample of available scripts.

Have a look at **System Settings ⇾ Script Installers** and see if those scripts aren't disabled?

**Comment by skol101** [comment]
I was managed to install Wordpress from the script. But wordpress isn't playing nicely well with FCGI/FPM. I've increased limits to upload big media files, but they are not uploaded. 
FCGI doesn't actually write to nginx error logs, whilst FPM does write to nginx error logs. What gives?

When updates site PHP configuration, PHP service actually doesn't restart and must be restarted manually.
 
With ipv6 enabled, FPM throws errors that it cannot connect to localhost:8000.

Also, there's suggestion to use unix socket for FPM instead of TCP. Why it's not being used?

**Comment by skol101** [comment]
Forgot to reopen it.
