### ISSUE TITLE
Proftpd TLS and letsencrypt

### ISSUE THREAD

**Issue by aqueos** [virtualmin/virtualmin-gpl#354]
hi there,

 Hope all is well for you. I wanted to report an issue that is basicaly the same i reported for dovecot a while ago. 

=============
THE ISSUE
=============

Virtualmin when putting certificate for proftpd use the certificate alone and not the combined certificate+intermediate CA. 

Therefor the certificate chain is not correct. Particularly with letsencrypt it is a problem as it requires manual intervention every 2 month.

===============
The Why
===============

The tls support for proftpd has 2 parameters:

https://www.proftpd.org/docs/howto/TLS.html

    # Server's RSA certificate
    TLSRSACertificateFile /etc/ftpd/server-rsa.cert.pem
    TLSRSACertificateKeyFile /etc/ftpd/server-rsa.key.pem

 So there is no separate "CA" parameter but virtualmin use TLSCACertificateFile wich is not for this use:

The 

**TLSCACertificateFile**
The TLSCACertificateFile directive configures one file where you can assemble the certificates of Certification Authorities (CA) for your clients. 

**TLSCACertificatePath** 
The TLSCACertificatePath directive sets the directory for the certificates of Certification Authorities (CAs) for your clients. These are used to verify the client certificates presented. 

are not for a spécific certificate they are here for the whole CA root trust.

===========
Proposed solution
===========

 Use the ssl.combined file and not the ssl.cert file to create the proftpd file of the certificate for TLS**RSA**CertificateFile and do not touch the TLS**CA**CertificateFile parameter should do it.

  hope it helps ! :)

regards,
Ghislain.

**Comment by jcameron** [comment]
Thanks for pointing this out .. I'll have Virtualmin put the full cert plus CA into `TLSCACertificateFile` in the next release.

**Comment by aqueos** [comment]
you mean in the TLSRSACertificateFile i guess :)

thanks !

**Comment by jcameron** [comment]
Yes, that one
