### ISSUE TITLE
Enabling Chroot jail domain Unix user prevents PHP access to Mariadb socket

### ISSUE THREAD

**Issue by pixel-paul** [virtualmin/virtualmin-gpl#359]
Operating system | Redhat Enterprise Linux 8
-- | --
Webmin version | 1.984 |
Virtualmin version | 6.17  Pro

This had me stumped for a while (mainly because I couldn't figure out when I actually enabled chroot jails!), but it appears to be an issue.

If you turn on chroot jail for a user, then try and access mariadb via `localhost`, the connection will fail, rather uninformatively (as in no error message from mariadb). 

```
<?php
$link = mysqli_connect('localhost', 'mysql_user', 'mysql_password');
if (!$link) {
    die('Could not connect: ' . mysql_error());
}
echo 'Connected successfully';
mysql_close($link);
```
If you try and connect via IP, so `127.0.0.1`, it will work.

I believe that this means that you are currently forced to use TCP instead of socket to connect (and it is also very confusing to users).

**Comment by jcameron** [comment]
Unusual that `localhost` is interpreted as the socket file rather than a network connection.

What PHP app do you have installed in this domain that's in the chroot?

**Comment by pixel-paul** [comment]
I'm pretty sure this is default behaviour?

> The hostname localhost has a special meaning. It is bound to the use of Unix domain sockets. To open a TCP/IP connection to the localhost, 127.0.0.1 must be used instead of the hostname localhost. 

https://www.php.net/manual/en/mysqli.quickstart.connections.php

I ran into this problem with WordPress specifically. Took me a while to narrow down the cause, due to poor error messaging, but it is definitely due to the chroot functionality being switched on for a Virtual Server.

**Comment by pixel-paul** [comment]
I've updated the title to reflect that this may only be occuring with PHP.

**Comment by jcameron** [comment]
Ok, thanks for the info. I see two possible solutions to this :

1 - Bring the MariaDB socket file into the chroot
2 - Always use 127.0.0.1 instead of localhost, to force use of a TCP socket

**Comment by pixel-paul** [comment]
I would suggest that the MariaDB socket is brought into the chroot, as the default for WordPress (and in my experience for most php applications) is `localhost`.

I ran a quick check and the default set by the Virtualmin WordPress script installer is `localhost`, so that would be broken in this case too.

Some validation of this issue might be worthwhile, as I have only tested this on one server.

**Comment by iliarostovtsev** [comment]
This is odd. If I enabled jail on **Administration Options ⇾ Edit Owner Limits: Server Owner Limits** page, add **Can install scripts** under **Allowed capabilities and features** accordion, then switch to the server owner, install WordPress script, and then visiting WordPress looks fine, there is no error and all is working as expected?

Isn't the very same thing doesn't work for you on your side?

**Comment by pixel-paul** [comment]
When I followed your steps @iliarostovtsev, the WordPress config.php file contains:

```
/** MySQL hostname */
define('DB_HOST', '127.0.0.1');
```

When I installed another Virtual Server without enabling chroot, the WordPress config.php file contains:

```
/** MySQL hostname */
define('DB_HOST', 'localhost');
```

Virtualmin is therefore correctly setting up DB connections either via TCP/IP or socket, depending on if chroot is enabled. 

However, this does not cover the case where a user enables chroot after creating the Virtual Server (which is where I have run into this issue).

There is also a case where if a user creates a chrooted Virtual Server and manually installs or imports WordPress and their wp-config.php file contains `localhost`, a database connection error is thrown.

This is what the user sees if they try and connect via `localhost` in a chrooted Virtual Server:

`Error establishing a database connection`

And if they set `define( 'WP_DEBUG', true );`, this:

```
Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in /home/test2/public_html/wp-includes/wp-db.php on line 1653

No such file or directory
```

**Comment by iliarostovtsev** [comment]
I see. Manually is manually.

> However, this does not cover the case where a user enables chroot after creating the Virtual Server

It's easy to fix. I have added a facility for this recently. We can easily (or not that easily) change all hostnames in scripts configs upon chroot disabling/enabling, unless of course there is a better solution.

**Comment by pixel-paul** [comment]
Would this also cover importing or transferring Virtual Servers? What is the action if I transfer a Virtual Server from a chroot disabled server to a chroot enabled server?

**Comment by iliarostovtsev** [comment]
> What is the action if I transfer a Virtual Server from a chroot disabled server to a chroot enabled server?

This is also possible to do, if Jamie wants it to go this way.

**Comment by jcameron** [comment]
I've also checked in a fix that will link the mysql socket file into the chroot : https://github.com/virtualmin/virtualmin-gpl/commit/11a425b6b3f5aadac2cacf8a708b6e1d241766c4

**Comment by pixel-paul** [comment]
Thanks @jcameron.
