### ISSUE TITLE
[Server Template] FPM pool options doesn't change my pool config

### ISSUE THREAD

**Issue by Vagrantin** [virtualmin/virtualmin-gpl#36]
Hello,

I want to adapt the default FPM config when creating a new virtual-host for that purpose in 

``Server Templates > PHP options > Additional FPM pool options`` 

I have added this config:

```
pm = ondemand 
pm.max_children = 15
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 5
pm.max_requests = 200
```

But  any new Vhost created is still and always getting the default config 

```
pm = dynamic
pm.max_children = 9999
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 5
```

Is there something else to do to have those options replace by my mine ?

Thanks for any input 

Kind regards
Matth

**Comment by jcameron** [comment]
That should work - if you re-open the template, are the settings still there? Also, do you have multiple templates?

**Comment by Vagrantin** [comment]
@jcameron , 
yes when re-opening the template I can see the settings.
I have effectively several templates, the two defaults (_Default Settings_ and _Settings for Sub-Servers_) to create a new Vhost and a new sub-server.  
And a 3rd one which is my own template a clone from the Default in which I'm implementing my own settings to avoid screwing up the default one. I made this last template the Selected default at the Vhost creation step.

Also, i have just done a test if i put those settings in the Default template it does work well.
The fact that you ask if I have several templates means you have an idea what could be the issue right ? :)

Thanks for the help
Matth

**Comment by jcameron** [comment]
Ok, so the problem only happens when you add these custom settings to your 3rd template, and then create a domain with that template selected?

**Comment by Vagrantin** [comment]
yes exactly

**Comment by jcameron** [comment]
Ok, I see the bug - this will be fixed in the next Virtualmin release.
