### ISSUE TITLE
Support Debian 11 Bullseye

### ISSUE THREAD

**Issue by xxorax** [virtualmin/virtualmin-gpl#360]
The last stable version of Debian has been released 5 months ago already, Virtualmin does not support it yet.

The new Virtualmin forum is not suitable to track issues, the posts got closed after short time:
- https://forum.virtualmin.com/t/debian-11-is-officially-released/111831
- https://forum.virtualmin.com/t/when-will-debian-11-be-supported/112279
- https://forum.virtualmin.com/t/which-latest-version-of-debian-is-fully-supported/112206

So here the issue to know when it will be released, and to track the delivery :)

Thanks !

**Comment by iliarostovtsev** [comment]
Hi,

We are working on preparing Virtualmin 7 release. The support for Debian 11 will be officially added with Virtualmin 7 release.

There is a way to install Virtualmin 6 on Debian 11 right now, as described in a link below. Although, this is not recommended way. If you have skills and understanding how to switch to Virtualmin 7 repos later and it may work for you but we will not help with it.

https://forum.virtualmin.com/t/virtualmin-7-and-debian-11/113031/7

**Comment by chris001** [comment]
Awesome progress, in the 3 months since this issue was opened, I notice there's a 7.0 .DEB package released for Debian available on the webmin website.
When installing to Debian 11 from the `.deb` file directly, (available on the [webmin site other download formats page](https://www.webmin.com/vdownload.html), under "virtualmin GPL packages"), further attempts at `apt update` gives errors, as shown below, so package updates/upgrades from the official virtualmin RPM repo are breaking.  Any suggestions to fix these, in an appropriate way, suitable to the current status of the release, in other words, what steps in the install are we missing here for it to not error out?
```
root@ns1.mydomain.com:~# apt update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Ign:4 http://download.webmin.com/download/repository sarge InRelease
Hit:5 http://download.webmin.com/download/repository sarge Release
Ign:6 https://software.virtualmin.com/vm/7/gpl/apt virtualmin-bullseye InRelease
Err:7 https://software.virtualmin.com/vm/7/gpl/apt virtualmin-bullseye Release
  404  Not Found [IP: 163.172.162.254 443]
Get:8 https://software.virtualmin.com/vm/7/gpl/apt virtualmin-universal InRelease [10.7 kB]
Err:8 https://software.virtualmin.com/vm/7/gpl/apt virtualmin-universal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D9F9010760D62A6B
Reading package lists... Done
E: The repository 'https://software.virtualmin.com/vm/7/gpl/apt virtualmin-bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://software.virtualmin.com/vm/7/gpl/apt virtualmin-universal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D9F9010760D62A6B
E: The repository 'https://software.virtualmin.com/vm/7/gpl/apt virtualmin-universal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@ns1.mydomain.com:~#
```

**Comment by iliajie** [comment]
> E: The repository 'https://software.virtualmin.com/vm/7/gpl/apt virtualmin-bullseye Release' does not have a Release file.

@swelljoe Joe, hasn't added support for Virtualmin 7 on the repos yet.

**Comment by Gregory-K** [comment]
The `7` repositories are working, but not for an error-free clean installation though/yet.

```
▣▣□ Phase 2 of 3: Installation
Installing Webmin                                                       [  ✔  ]
Installing Usermin                                                      [  ✔  ]
Installing fail2ban                                                     [  ✔  ]
Installing postfix                                                      [  ✔  ]
Installing virtualmin-lamp-stack                                        [  ✔  ]
Installing Virtualmin and all related packages                          [ERROR] Failed with error: 100
[  ✘  ]

[ERROR] Something went wrong. Exiting.
[ERROR] The last few log entries were:
NOTICE: Not enabling PHP 7.4 FPM by default.
NOTICE: To enable PHP 7.4 FPM in Apache2 do:
NOTICE: a2enmod proxy_fcgi setenvif
NOTICE: a2enconf php7.4-fpm
NOTICE: You are seeing this message because you have apache2 package installed.
Processing triggers for php7.4-cgi (7.4.28-1+deb11u1) ...
Installing virtualmin-lamp-stack: Success.
Spin pid is: 52929
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package virtualmin-core
Installing Virtualmin and all related packages: [2022-05-02 17:40:31 BST] [ERROR] Failed with error: 100
[2022-05-02 17:40:31 BST] [ERROR] Something went wrong. Exiting.
[2022-05-02 17:40:31 BST] [ERROR] The last few log entries were:
```

**Comment by swelljoe** [comment]
I know. I will announce on the Virtualmin News forum when any of this is expected to work.

**Comment by silversword411** [comment]
Is this the right github project for virtualmin?

https://www.virtualmin.com/os-support/ says Grade A supported systems are: Deb 10 and 11.

Running the install.sh command on that page give a v6.2.2 that says

```
Welcome to the Virtualmin GPL installer, version 6.2.2

  This script must be run on a freshly installed supported OS. It does not
  perform updates or upgrades (use your system package manager) or license
  changes (use the "virtualmin change-license" command).

  The systems currently supported by install.sh are:

    CentOS/RHEL Linux 7, and 8 on x86_64
    Debian 9, and 10 on i386 and amd64
    Ubuntu 16.04 LTS, 18.04 LTS, and 20.04 LTS on i386 and amd64
```

Reading this thread, and other places it looks like that's a v7 milestone...but maybe you shouldn't say something supported...till it's actually supported? ;)

**Comment by iliajie** [comment]
> Reading this thread, and other places it looks like Deb11 is a v7 milestone...but maybe you shouldn't say something supported...till it's actually supported? ;)

No, because it says that it's supported in beta installer. This is a common practice to provide pre-release versions of software.

**Comment by xxorax** [comment]
I expected this issue to be closed once Virtualmin Stable support Debian 11...

Else how can I got a notification about this ?  The new forum system is just horrible : topics close after 10 days of inactivity...

Thanks

**Comment by iliajie** [comment]
> The new forum system is just horrible : topics close after 10 days of inactivity...

Actually, topics are closed 60 days of inactivity, not 10.

>  I expected this issue to be closed once Virtualmin Stable support Debian 11... Else how can I got a notification about this? 

Alright, I will notify you. Although, you could go to https://forum.virtualmin.com/c/news/5 and hit a bell button (on the top right) to be notified about all updates.

**Comment by xxorax** [comment]
> Actually, topics are closed 60 days of inactivity, not 10.

https://forum.virtualmin.com/t/authentic-theme-20-01-1-release-overview/116869 "This topic will close 10 days after the last reply."

Thanks anyway for reopening and suggestion, I susbcribed.
Waiting for stable release.

**Comment by silversword411** [comment]
> No, because it says that it's supported in beta installer.

That is not the implication at virtualmin.com. A user is going to go to https://www.virtualmin.com/download/

Check if their os is Grade A supported (shows it is), downloads the official script and runs it.
`/usr/bin/wget https://software.virtualmin.com/gpl/scripts/install.sh`

From one support guy to another, I'd be yelling at the web dev to make it supremely obvious stable is Deb 9 and 10
and Beta is Deb 10 and 11. I would not want to be the one to have to spend a year+ telling people that's beta only because the page doesn't make that abundantly clear.

![2022-09-15_093942 - brave_OS_Support_–_Virtualmin_-_Brave](https://user-images.githubusercontent.com/13395348/190420227-4778c4a1-b441-4aec-88a1-a83b8944bc28.png)

**Comment by xxorax** [comment]
I just tested the installation with the [install script](https://software.virtualmin.com/gpl/scripts/install.sh)  (without option) on Debian 11 : from now I see absolutely NO issue !

- No error reported
- Virtualmin runs well
- Virtual-server creation (even with some custom specificities) runs well (apache, ssl, mariadb, webmin login)
- Let's Encrypt cert generated

I guess there is still some incompatibilities to fix, and I will repport/fix if I found some.

But I see no reason to keep this ticket open :)

Thank you !

@iliajie I see the closing delay of the topics on the forum is now 2 months ! Thanks again !
