### ISSUE TITLE
PHPMyAdmin script upgrade fails when using PHP 7.4

### ISSUE THREAD

**Issue by pixel-paul** [virtualmin/virtualmin-gpl#361]
Operating system | Redhat Enterprise Linux 8
Webmin version | 1.984
Virtualmin version | 6.17  Pro
PHP version | 7.4

![Screenshot 2022-01-27 at 17-49-21 server300 egy hosting - PHP Options — Webmin 1 984 on server300 (Redhat Enterprise Linux 8)](https://user-images.githubusercontent.com/389303/151415252-3a52e153-9f7f-4bf6-a10a-f95cb26047fb.png)

When upgrading from 5.1.1 to 5.1.2:

```
Upgrading phpMyAdmin to version 5.1.2 ..

    .. failed dependencies : PHP version 7.1 or later is required, but this virtual server is using version 7.3
```

**Comment by jcameron** [comment]
Odd that it shows you are using PHP 7.3 in the error, but 7.4 on the PHP Options page. Do you also have PHP 7.3 installed?

**Comment by pixel-paul** [comment]
Yes, it's a strange one. This server is using RHEL 8 AppStream, so only PHP 7.4 is enabled:

<pre>$ dnf module list php
Updating Subscription Management repositories.
Last metadata expiration check: 1:08:53 ago on Fri 28 Jan 2022 07:44:18 GMT.
<b>Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)</b>
Name      Stream       Profiles                       Summary                   
php       7.2 [d]      common [d], devel, minimal     PHP scripting language    
php       7.3          common [d], devel, minimal     PHP scripting language    
php       7.4 [e]      common [d], devel, minimal     PHP scripting language    

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled</pre>

To note, I used the 'Domain' --> 'Install Scripts' route above, however I have now run the update from 'System Settings' --> 'Script Installers' --> 'Upgrade Scripts' and it worked successfully.

**Comment by iliarostovtsev** [comment]
Jamie, I mentioned this issue on **Scripts Installer Major Update** internal email.

**Comment by jcameron** [comment]
I didn't see that email? What was the cause of this issue?

**Comment by pixel-paul** [comment]
I'll close this issue, as it sounds like it has been already picked up.

Thanks!
