### ISSUE TITLE
generate-letsencrypt-cert - Failed to open PID file

### ISSUE THREAD

**Issue by nicutor** [virtualmin/virtualmin-gpl#364]
Hi there,

There is an issue when running this API command:

```
# virtualmin generate-letsencrypt-cert --domain domain.com --renew
Requesting SSL certificate for domain.com ..
.. done

Copying to webserver configuration ..
Error: Failed to open PID file
Error
-----
Failed to open PID file
-----
```

The SSL is put in place, but I think the apache was not restarted.
Had no time to test it more, just reporting so you can take a look if you like.

Rocky Linux release 8.5 (Green Obsidian)
webmin-1.984-1.noarch
virtualmin-release-6.0-3.gpl.noarch

Thank you.

**Comment by jcameron** [comment]
Is this error repeatable? It looks like Usermin went down somewhere in the middle of the cert copy process, which is surprising..

**Comment by jcameron** [comment]
Just in case, I'll add an extra check to prevent this from crashing the whole cert install process.

**Comment by nicutor** [comment]
Yes, usermin was stopped at that point.

Thank you!
