### ISSUE TITLE
modify-database-hosts - don't replace default hostnames

### ISSUE THREAD

**Issue by nicutor** [virtualmin/virtualmin-gpl#365]
Hi there,

This API command don't replace remove/add default hostnames on /etc/webmin/virtual-server/config

```
virtualmin modify-database-hosts --all-domains --type mysql --remove-host ${IP_OLD}
virtualmin modify-database-hosts --all-domains --type mysql --remove-host ${HOSTNAME_OLD}
virtualmin modify-database-hosts --all-domains --type mysql --add-host ${IP_NEW}
virtualmin modify-database-hosts --all-domains --type mysql --add-host ${HOSTNAME_NEW}
```

Before:

```
/etc/webmin/virtual-server/config:mysql_hosts=127.0.0.1 localhost IP_OLD HOSTNAME_OLD
```

After:

```
/etc/webmin/virtual-server/config:mysql_hosts=127.0.0.1 localhost IP_NEW HOSTNAME_OLD
```

Seems to work fine with IPs, but not with hostnames

Rocky Linux release 8.5 (Green Obsidian)
webmin-1.984-1.noarch
virtualmin-release-6.0-3.gpl.noarch

Thank you.

**Comment by jcameron** [comment]
This is expected .. the API command only updates existing domains, not the default configuration for new domains.

**Comment by nicutor** [comment]
Thank you @jcameron
