### ISSUE TITLE
Feature request: Add proftpd service on install-service-cert

### ISSUE THREAD

**Issue by nicutor** [virtualmin/virtualmin-gpl#366]
Hi,

Please add proftpd as well on the install-service-cert API command:

```
virtualmin install-service-cert --domain domain.com --add-global --service dovecot --service postfix --service webmin --service usermin --service proftpd
```

Thank you.

**Comment by jcameron** [comment]
This is already supported, as long as you have the FTP feature enabled on the Features and Plugins page of Virtualmin.

**Comment by nicutor** [comment]
Hi @jcameron. You was right. The process didn't finished because usermin was stopped and exited with the same error like on this issue: https://github.com/virtualmin/virtualmin-gpl/issues/364

Everything works with usermin started.

Thank you.
