### ISSUE TITLE
Cannot install virtualmin

### ISSUE THREAD

**Issue by dpark77** [virtualmin/virtualmin-gpl#370]
Trying to install on a fresh OS (Debian 10),

wget https://software.virtualmin.com/gpl/scripts/install.sh

ERROR: The certificate of ‘software.virtualmin.com’ is not trusted.
ERROR: The certificate of ‘software.virtualmin.com’ has expired.

I did update and upgrade to the latest and also updated ca-certificates.

**Comment by iliarostovtsev** [comment]
@dpark77 Please run `apt-get update && apt-get upgrade -y` first ..

**Comment by swelljoe** [comment]
You have an old ca-certificates package.
