### ISSUE TITLE
Virtualmin website down?

### ISSUE THREAD

**Issue by pixel-paul** [virtualmin/virtualmin-gpl#375]
Wasn't sure of the best support channel to raise this!

**Comment by pixel-paul** [comment]
And apologies if this was planned. It might be worth looking into Status Page - it's free and works well!

https://www.atlassian.com/software/statuspage

**Comment by swelljoe** [comment]
Which Virtualmin website do you think is down? (I'm seeing both www.virtualmin.com and the forum up, currently, and nothing in the logs that would make me think they were down.)

**Comment by pixel-paul** [comment]
Hmm interesting, there must be something up with my ISP's DNS server. Using 8.8.8.8 and everything is working. Should have tried that first. 

Thanks for your quick response :)

**Comment by pixel-paul** [comment]
Actually, you might want to check this:

https://www.whatsmydns.net/#A/www.virtualmin.com

It is actually showing outages.....

**Comment by swelljoe** [comment]
You're right. One of our DNS servers is offline! Dang.

**Comment by swelljoe** [comment]
We also had old glue records, which has now been fixed and is propagating.

**Comment by swelljoe** [comment]
Thanks for the heads up! I wouldn't have noticed for a few more hours, probably.

**Comment by pixel-paul** [comment]
Hey, no problem, good to get ahead of these things!
