### ISSUE TITLE
please print aws s3 response body rather than just error code

### ISSUE THREAD

**Issue by hayden-t** [virtualmin/virtualmin-gpl#377]
A failed backup will just print the first line of aws response, which just has the error code eg 400
This is not detail enough to really know what went wrong, and there is more detail available in the rest of the response available in $out variable.

eg by adding it after $line
/usr/share/webmin/virtual-server/s3-lib.pl
line 283:
```
	elsif ($line !~ /^HTTP\/1\..\s+(200|30[0-9])(\s+|$)/) {
		$err = "Invalid HTTP response : $line : $out";
		}
```
will do 
```
Uploading archive to Amazon's S3 service ..
.. upload failed! Invalid HTTP response : HTTP/1.1 400 Bad Request : InvalidRequestThe authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.{redacted}
```
(instead of just  `Invalid HTTP response : HTTP/1.1 400 Bad Request`)

**Comment by jcameron** [comment]
I don't know if it's a good idea to include the whole S3 reply body in the error (because it could be huge!), but I will include the first line.

**Comment by hayden-t** [comment]
sounds fine !
