### ISSUE TITLE
Config check should warn or error if any version of mod_php is installed

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-gpl#381]
Since there is no reason for anyone to ever use mod_php for anything anymore, and since people regularly install it anyway and break their other execution modes, we should make it an error or a warning whenever it is detected during a config check.

I think I'll try to figure out how to add a conflict somewhere in one of our packages to insure it never accidentally gets installed, as well (which is stupidly common because it's in the package named just `php`).

**Comment by jcameron** [comment]
I suppose I could do that pretty easily - but can we also disable it as part of the Virtualmin install?

Also, maybe we could disable it during a config check if no domains are using it..

**Comment by swelljoe** [comment]
The problem is we _can't_ disable it permanently. If the package is installed at any point in the future, it is enabled automatically via a config file that's part of the package.

We don't install it as part of the install process, and haven't for years now. But, users still install it, no matter how many times and ways I tell them not to...and when they do it breaks all other execution modes. Virtualmin tries to fix it, but fails pretty regularly (I dunno why it fails to get the SetHandler/RemoveHandler situation exactly right, but since there's not reason for mod_php to even be there, it's waste of time to try to get that right, when what we really want is for mod_php to not exist at all.

**Comment by swelljoe** [comment]
And, even if I add a Conflict that prevents it, users will uninstall the conflicting Virtualmin package to install mod_php, because of course they will.

**Comment by iliarostovtsev** [comment]
@swelljoe 

What do we do with these:
https://github.com/virtualmin/virtualmin-pro/blob/master/scripts/faqmasterflex.pl#L55-L56
https://github.com/virtualmin/virtualmin-pro/blob/master/scripts/zpush.pl#L54-L55

@jcameron Thanks for adding a message in config check. I have tweaked it a little bit to have it displayed more vividly:

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/4426533/159246791-d27c31c2-1776-492d-b38a-a351cf246f3c.png">

**Comment by iliarostovtsev** [comment]
@jcameron Jamie, I have taken a closer look to how PHP modes work when _mod_php_ is installed and there are few issues:

  1. **Bug:** _mod_php_ works only with Apache running _mpm_prefork_ which isn't setup by default (i.e. AlmaLinux), while it's still displayed on the list of options (AlmaLinux) on **PHP Options** page. If you select _mod_php_ in MPM other than prefork - it does super odd things (practically breaks things and falls back to FPM (by accident)). Solution - do not display _mod_php_ even if installed unless Apache _mod_prefork_ is enabled
  2. **Bug:** Even if _mod_php_ is installed and enabled on Ubuntu 20.04, and detected upon config check, it's still not displayed on **PHP Options** page
  3. **Suggestion:** Even if unacceptable _mod_php_ is still enabled can we print **PHP version** row so a user could click on a question mark to open `phpinfo();` page automatically? Like this:
  
<img width="430" alt="image" src="https://user-images.githubusercontent.com/4426533/159255286-cc590860-c6cf-4471-bf79-d49d9d1b2efe.png">

... right now it's just not printing this (PHP Version) row.

**Comment by iliarostovtsev** [comment]
@jcameron Jamie, one more **bug** - if you set mode to **Disabled** on RHEL systems it doesn't really get disabled as installed `php-fpm` package contains default FPM config that configures socket and it falls back to that (tested on Alma).

**Comment by jcameron** [comment]
@swelljoe what if we prevented users from switching to `mod_php` on domains where it isn't currently in use, even if it's theoretically possible?

**Comment by swelljoe** [comment]
I think we'll have a bunch of users that complain about that, because damned near everybody that has upgraded their PHP version also installed mod_php at the same time without realizing it (because the name of the package is `php` or `php7.4-php` or whatever. The problem isn't so much using mod_php as it is _having_ mod_php installed. When it's installed, it's seemingly guaranteed to break any other execution mode at some point in the future.

So...I just want to tell them they're doing it wrong by having it installed. I don't care if it's enabled or used. If it's installed, it's already the problem I'm trying to avoid hearing about.

I never want another forum post or support request from someone who broke their system by installing mod_php.

**Comment by jcameron** [comment]
Ok .. so if it is installed, is the fix to just disable the Apache module so it isn't loaded?

**Comment by swelljoe** [comment]
Yeah, but you have to do it by modifying the relevant `php.conf` to comment out the module load, as far as I know. Otherwise, if the file is just deleted, it gets overwritten with one that activates it on the next update

**Comment by swelljoe** [comment]
Oh, but also, the next time the user installs some other PHP version, they'll do it again and get yet another mod_php installed and enabled break their other execution modes.

**Comment by jcameron** [comment]
Ok, I'll work on this .. it shouldn't be too hard

**Comment by jcameron** [comment]
Ok, I've also added a prompt on the dashboard to properly disable `mod_php` if it's unused.

**Comment by iliajie** [comment]
Great! Thanks, Jamie.
