### ISSUE TITLE
deb packages for version 7 not found

### ISSUE THREAD

**Issue by ardabeyazoglu** [virtualmin/virtualmin-gpl#383]
Hi,

I have ubuntu 18.04 and virtualmin 6.17-3. So far it always received apt updates but it doesn't receive v7.0+ updates. Is there a different way to upgrade to v7 ?

**Comment by iliajie** [comment]
Virtualmin 7 isn't released yet. It's only on the way.

**Comment by ardabeyazoglu** [comment]
Ok, thanks.
