### ISSUE TITLE
Azure Blob Storage

### ISSUE THREAD

**Issue by hbjydev** [virtualmin/virtualmin-gpl#384]
Hey guys, I'd love to see an Azure Blob Storage target for Virtualmin backups, that would be brilliant as we've moved all of our backup tooling to Azure now.

For the time being I have a script I use, but it would obviously be preferable to have a built-in destination for Azure.

They just use a (non-S3-compatible) REST API for handling it, so it shouldn't be _too_ hard?

**Comment by jcameron** [comment]
We could definitely add this - I'll update this ticket with progress

**Comment by jcameron** [comment]
Ok, I have implemented support for Azure Blob Storage backups for inclusion in Virtualmin 7.5.

It will require that you install their `az` command line tool first though.

**Comment by chris001** [comment]
If you don't have `az` command on your system, here's [Instructions to install the `az` command, for the various Linux distro types](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt).

**Comment by iliajie** [comment]
Thanks, Chris. Although, I just noticed that we print `longdesc` (i.e. instructions) only after `az` command was installed. We will fix that so the instructions are be printed (if available) beforehand:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/4426533/213198316-50505100-fcae-4e9c-9269-c38dc7f1873d.png">
