### ISSUE TITLE
How to manually replace apache2 with nginx on 7.0 to get letsencrypt?

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#386]
It looks like `letsencrypt` feature depends on having a web server installed!?  By default, the DEB package installed `Apache (SSL) website`.  Prefer to use `nginx SSL website`.  Have manually installed `certbot`.  OS Debian 11 bullseye, `virtualmin 7.0`.

It looks like the `nginx` virtualmin packages have disappeared?  Would like to get `letsencrypt` running and let `virtualmin 7.0` auto renew certs, however `virtualmin` seems to require the `nginx` module installed in order to enable the feature `nginx web server`.  So, how do you manually install `nginx web server` feature on 7.0 ?

**Comment by swelljoe** [comment]
Always use the Virtualmin install script provided on Virtualmin.com. To get nginx, use the `--bundle LEMP` option [as documented](https://www.virtualmin.com/documentation/installation/automated/#LAMP_vs_LEMP).

**Comment by chris001** [comment]
Sorry to hear that.  Since rhe install script provided on Virtualmin.com was erroring out on Debian 11, we installed the DEB package 7.0 release from webmin.com and it went smoothly without trouble.  Does the install script run without error on Debian 11 now?  Is there any less destructive way than to erase and reinstall the Deb 11 OS, such as manually remove the DEB package, to attempt to reinstall virtualmin using the install script?
