### ISSUE TITLE
Basic issue: BIND SOA serial number format should conform to RFC 1912.

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#387]
The BIND DNS zone `SOA` serial number format appears not to conform to [RFC1912](https://datatracker.ietf.org/doc/html/rfc1912), which says the serial number should be in `YYYYMMDDnn` format.   Guess the software has been using the Unix timestamp for the serial number, which generates errors and warnings in DNS zone validation tools.
```
The recommended syntax is YYYYMMDDnn
   (YYYY=year, MM=month, DD=day, nn=revision number.  
This won't overflow until the year 4294.
```

**Comment by jcameron** [comment]
You can switch this this YYYYMMDDnn format at Webmin -> Servers -> BIND DNS Server -> Module Config -> Zone file options.

**Comment by jcameron** [comment]
Yes, I'll do that.
