### ISSUE TITLE
Virtualmin creates PHP FPM pool conf to remove php version

### ISSUE THREAD

**Issue by alexbogias** [virtualmin/virtualmin-gpl#39]
I have a fresh Debian 9 virtualmin install and wanted to also install php5.6 in addition with php7.0 that came with debian stretch. I added deb.sury.org repo and installed php5.6 successfully. I also installed php 5.6 fpm which I didnt needed and I removed afterwards. Now I am trying to switch php mode to fpm on one of my virtual server and virtualmin creates the pool conf file to /etc/php/5.6/fpm/pool.d/151472831711092.conf so I am getting Service unavailable when trying to access the website. If I edit /etc/php/7.0/fpm/php-fpm.conf and change include=/etc/php/7.0/fpm/pool.d/*.conf to include=/etc/php/5.6/fpm/pool.d/*.conf everything works great.
Is this a bug? 
Can you let me know how I can fix my setup so it will not break in the future?

**Comment by jcameron** [comment]
Virtualmin actually doesn't support multiple PHP versions when using FPM mode - you can have only one version installed, sorry. And by default it will detect the lowest-numbered config directory.

**Comment by alexbogias** [comment]
But php-frm (5.6) its actually uninstalled and it stills create the pool there :O

**Comment by jcameron** [comment]
Does the `/etc/php/5.6` directory still exist? If so, you should move all files from `/etc/php/5.6/fpm/pool.d` to `/etc/php/7.0/fpm/pool.d` , and then delete `/etc/php/5.6`

**Comment by alexbogias** [comment]
@jcameron I deleted /etc/php/5.6/fpm/pool.d and I think thats it works ok now! Thanks!

**Comment by jcameron** [comment]
Great! Out of interest, did that directory contain any other files?

**Comment by alexbogias** [comment]
Sorry @jcameron but i already deleted it. I am 90% sure that it was empty if this helps :P

**Comment by jcameron** [comment]
Ok, that's what I expected
