### ISSUE TITLE
Virtualmin configuration module show less options in non English language

### ISSUE THREAD

**Issue by nodo50** [virtualmin/virtualmin-gpl#390]
The section "System Settings -> Virtualmin configuration" show a different number of options depending of the language choosed. First I have realized that, when I choose Spanish, some options disappeared at "User interface settings" section, all related to choose columns to show.

And more are affected, in English the  configuration categories (drop down list) are 13. In Spanish only 8, in French 10. In French the "User interface settings" is very small, only 3 options.

I suppose you can reproduce changing interface language. If not I can take screenshots.

It happens with Virtualmin Pro and GPL 6.17-3 and Virtualmin GPL 7.0-4. Debian 9 and Debian 10.

**Comment by iliajie** [comment]
Hi,

Thanks for the heads up! You're right, it was a bug on Authentic Theme side. Fixed now.
