### ISSUE TITLE
Doc/FAQ: How to enable dual master BIND DNS with 2 Virtualmin servers?

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#391]
Sorry if dumb question: How do you enable or convert to dual master (or Master/Slave) BIND DNS between 2 Virtualmin servers currently running with independent BIND servers?
When Virtualmin server 1 creates a virtual server and a BIND DNS zone, the BIND should replicate to Virtualmin Server 2 as a slave BIND DNS zone?  And vice versa when Virtualmin server 2 creates a virtual server?

**Comment by jcameron** [comment]
Have you checked out the docs at https://www.virtualmin.com/documentation/dns/slave-configuration/ ?

**Comment by chris001** [comment]
Did the steps, however, at "Enabling Cluster Slave Servers", entered settings same as doc says, click "Add New", and it gives this error: 
```
Adding ns2.__mydomain__.com ..
Server ns2.__mydomain__.com is not running Webmin version 1.202 or above.
```
Not true, the Webmin version is the latest, 1.991 so why that error ?!

**Comment by chris001** [comment]
Also, I found an error in that docs page [DNS Slave Auto-configuration](https://www.virtualmin.com/documentation/dns/slave-configuration/), in the section "Setting the Master IP Address", this is wrong/outdated:
"In the **Zone file options** section, find the **Default master server IP for remote slave zones** field."

However, you moved the option "**Default master server IP for remote slave zones**" from the section "**Zone file options**" to "**Cluster slave servers**".
It should read:
"In the **Cluster slave servers** section, find the **Default master server IP for remote slave zones** field."

**Comment by chris001** [comment]
Update:
Error details displayed on "Webmin / Webmin Servers Index / Edit Server / Server status":
**Server status**  `Failed to connect to  ns2.__mydomain__.com : Invalid SSL certificate : Certificate is  self-signed by /O=Webmin Webserver on  host-54bd01/CN=*/emailAddress=root@host-54bd01`
Why is it saying Webmin on `ns2` is serving up a Webmin self signed cert, when Webmin is serving a genuine valid LetsEncrypt cert on port `10000` ?
What port and protocol is it trying to connect thru?  Isn't it supposed to be connecting thru `https` on virtualmin port `10000` ?

**Comment by jcameron** [comment]
Is the hostname it's trying to connect to as set in Webmin Servers Index the same one you're using in the browser?

**Comment by chris001** [comment]
Yes, Webmin Servers Index hostname is `ns2.__mydomain__.com`, port is `10000`, browser is  `https://ns2.__mydomain__.com:10000`, and shows `Verified by: Let's Encrypt`.

**Comment by jcameron** [comment]
As a work-around, you can go to Webmin Servers Index -> ns2 (edit), and un-check the "Check remote SSL certificate?" box.

**Comment by chris001** [comment]
That workaround worked, now it says `Server Status: Running Webmin 1.991`.  But where on earth is Webmin getting that self signed cert from, and is there a button to click to tell Webmin to use the same Verified by Let's Encrypt cert as it's using for `https` on port `10000` ??

**Comment by jcameron** [comment]
Agreed, this shouldn't be failing when SSL cert validation is enabled.

Do you have any per-IP certs configured on ns2? You can check by looking for `ipcert_` lines in `/etc/webmin/miniserv.conf` ?

**Comment by chris001** [comment]
Yes there's this, not sure why it's there, and why it'd be using that self signed non-verified cert, while port `10000` for the actual web interface thru the browser is using the genuine `Verified by Let's Encrypt` cert?:
```
ipcert_ns2.__mydomain__.com,*.ns2.__mydomain__.com=/etc/ssl/virtualmin/1650918378286180/ssl.cert
ipkey_ns2.__mydomain__.com,*.ns2.__mydomain__.com=/etc/ssl/virtualmin/1650918378286180/ssl.key
ipextracas_ns2.__mydomain__.com,*.ns2.__mydomain__.com=/etc/ssl/virtualmin/1650918378286180/ssl.ca
```
Note `__mydomain__` is a redacted real domain name.

**Comment by jcameron** [comment]
Does this system have Virtualmin installed, and if so is ns2.__mydomain__.com one of the hosted domains?

Also, which Webmin version is the master system and ns2 running?

**Comment by chris001** [comment]
Yes, this `ns2` has Virtualmin installed, and ns2.**mydomain**.com is one of the hosted domains.
The master and `ns2` both are running latest Webmin 1.991.

**Comment by jcameron** [comment]
One solution would be to make the cert for ns2 the default cert for Webmin. If you select ns2 from tjhe left menu at go to the "SSL Certificate" page, there should be a button to make it the global default cert.

**Comment by chris001** [comment]
Went to page "Server Configuration / SSL Certificate", it already says the Lets Encrypt verified cert is being used?  But obviously not, for "Webmin Servers Index"?  Could webmin be using the Lets Encrypt Verified cert for `https` port `10000`, and the self signed cert for `https` port `10001` ?
"SSL certificate file | /etc/ssl/virtualmin/1650918378286180/ssl.cert
-- | --
SSL private key file | /etc/ssl/virtualmin/1650918378286180/ssl.key
Web server hostname | ns2.**mydomain**.com | Issuer name | R3
Issuer organization | Let's Encrypt | Expiry date | Jul 31 17:24:30 2022 GMT
Certificate type | Signed by CA
Other domain names | ns2.**mydomain**.com
Used by services | Webmin (ns2.**mydomain**.com), Usermin (host ns2.**mydomain**.com), Postfix (host ns2.**mydomain**.com)"

**Comment by jcameron** [comment]
Is there also a button on that page labelled "Set as Default Services Certificate" ?  That's the one that will copy the cert to be the default for requests that don't match any more specific per-domain cert.

**Comment by jcameron** [comment]
Ok I looked closer at this, and I found a bug that is causing this error - we'll fix it in the next Webmin release. The patch can be seen here : https://github.com/webmin/webmin/commit/fb993f22f8b313a06bd5356c2fd3fdc05737a2ff
