### ISSUE TITLE
Nice to have: Little smarter Re-check Configuration.

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#394]
1. `phpinfo()` shows `Server API | FPM/FastCGI`!
`Re-Check Configuration`:
`HTTP2 not available` (not sure of wording?)
`No PHP execution modes are available!`
`The following PHP-FPM versions cannot be used : 7.4.28 (Apache module mod_fcgid is missing or not enabled)`
`:~$ sudo a2enmod fcgid`
`Module fcgid already enabled`
Turns out the package wasn't installed `libapache2-mod-fcgid` and modules `http2` and `actions` need to be enabled!
`Re-check Configuration` could be a little smarter, detect which pieces are missing, and button or command line to add!

2. `SpamAssassin and Procmail are installed and configured for use`
Actually `procmail` was not working!  `Webmin` `Servers` `Procmail Mail Filter` showed a warning it wasn't working!  See [issue on virtualmin-install](https://github.com/virtualmin/virtualmin-install/issues/62).  To dismiss warning, had to manually copy paste `/etc/procmailrc` from a running Virtualmin server, installed from shell script to oldstable Debian 10, afterward upgraded to current stable Debian 11.  Shouldn't it detect `procmail` not working, in Re-check Configuration?

3. Also, `SpamAssassin` silently fails to add `X-Spam` headers to any and all incoming mail messages!  Virtualmin and/or Webmin could get a little smarter, detect `SpamAssassin` is actually not getting called on incoming mail, not adding its `X-Spam` header, and put up an urgent warning in `Re-Check Configuration` with button or command line to fix!
4. **OPTIONAL** `ClamAV is installed and assumed to be running`  Why assume? How about checking it's running?
5. **OPTIONAL** `Postfix can support per-domain outgoing IP addresses, but is not currently configured to do so. This can be setup in the Postfix Mailserver module`  To make life easier, how about auto-assign a unique per-domain outgoing IPv6 address, from the typically large number of IPv6 allocated per server? This is usually needed to work around outgoing email normally fails to arrive at destination inbox due to the typical blacklisted IPv4 address provided by most hosting providers!
6. **OPTIONAL** `Chroot jails are available`.  For better security, how about default enable jail with the goal to isolate, sort of containerize, every virtual server, and most system services (bind9, apache2, ftp, postfix, dovecot, ssh ...)?

**Comment by iliajie** [comment]
Chris, please stop installing Virtualmin without `install.sh` script - it won't work as expected (1-5).

Certainly not (6). Probably, it's just better to use containers (in the future). We have plans for containers.

**Comment by chris001** [comment]
Thanks, however, most packages (`rpm`, `deb`) on linux usually include a configure script, which prompts to keep existing or overwrite config files with package default config files, and gets the package fully working.  It seems the Virtualmin packages only install code and not configure it completely?  This is unusual.  Can we run `virtualmin-config-system` or some command line, to non destructively get a Virtualmin system configured and have `apache2`, `fpm`, `nginx`, `procmail`, `spamassassin` work at a baseline level?

**Comment by iliajie** [comment]
This is a fair question. Infact, just the last night, I was thinking if we could do installation logic in a package scriplets. I think it's double, and it sounds like fun.

Surely, it would be cool - you call to install `webmin-virtual-server.rpm`, and then it pulls on the dependencies and runs post-installs, including `virtualmin-config-system`.

It doesn't sound like very complicated task, rather time consuming. At the moment, without giving it a deeper thought, the main problem seems to me is that we would have to build a specific package for each distro and probably each version for each distro.

**Comment by iliajie** [comment]
.. or, to simplify the process, we could display an alert on the dashboard saying that Virtualmin wasn't installed correctly using `install.sh` script and let user choose to click a button and internally ran `install.sh` script choosing LEMP or LAMP normal/minimal type of install before that.

This theoretically could work ..

**Comment by chris001** [comment]
> This theoretically could work ..

This would be fantastic, as it would help repair Virtualmin when there are missing configs for some of the system services, for any reason, possibly failed `install.sh` or installed code from package, or maybe system admin or dev accidentally removed config and need to config system again, in a non destructive way.
