### ISSUE TITLE
virtualmin 7.0, no repo for bullseye

### ISSUE THREAD

**Issue by aqueos** [virtualmin/virtualmin-gpl#395]
hi,

 I was thinking 7.0 was debian bulleyes supported but https://software.virtualmin.com/vm/6/gpl/apt/dists/  show no bullseye repository.

 Is it normal ? 

Thanks for the work ! 
Ghislain.

**Comment by aqueos** [comment]
oh sorry the url change also..

**Comment by iliajie** [comment]
Virtualmin 7 will support Debian 11.
