### ISSUE TITLE
PHP: Apache listen vs PHP-FPM listen

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#397]
Jamie, when Virtualmin creates Apache record with `SetHandler` directive, it creates it with `localhost`, instead of IP address, i.e.:

```
SetHandler proxy:fcgi://localhost:8001
```

PHP-FPM pool file gets:

```
listen = 127.0.0.1:8001
```

Wouldn't be right to always listen on 127.0.0.1?

**Comment by jcameron** [comment]
Yes .. I've fixed that.

**Comment by iliajie** [comment]
Thanks, that seems to work just fine, with both Unix sockets and TCP ports.
