### ISSUE TITLE
Template: PHP Options - PHP default version with FPM is ignored

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#399]
Using Ubuntu 20.04 with Apache. Multiple PHP versions installed - 7.3, 8.0 and 8.1.

Setting **Default PHP version** in **Templates** on **PHP options** page, when **FPM** mode is also set to default, _doesn't work_.

Creating new virtual server results in minimum PHP version selected all the time. It works just fine with FCGId mode set as default.

**Comment by iliajie** [comment]
The same happens with Nginx.

**Comment by jcameron** [comment]
Is the PHP version selected one of the versions that is supported in Nginx mode?

**Comment by iliajie** [comment]
Yes, as I assume fcgid and fpm are supported.

**Comment by jcameron** [comment]
Can you post the output from `virtualmin list-php-versions --multiline` ?

**Comment by iliajie** [comment]
Yes, sure, here you go:

```
root@ubuntu20-gpl:/etc# virtualmin list-php-versions --multiline
7.4
    Command: /bin/php-cgi7.4
    PHP modes: cgi fcgid
    FPM support: Yes
    Full version: 7.4.3
8.0
    Command: /bin/php-cgi8.0
    PHP modes: cgi fcgid
    FPM support: Yes
    Full version: 8.0.19
8.1
    Command: /bin/php-cgi8.1
    PHP modes: cgi fcgid
    FPM support: Yes
    Full version: 8.1.6
root@ubuntu20-gpl:/etc# 
```

**Comment by jcameron** [comment]
I just tested this, and confirmed that the default PHP version was respected in FPM mode when creating a new domain.

**Comment by iliajie** [comment]
> I just tested this, and confirmed that the default PHP version was respected in FPM mode when creating a new domain.

Are you saying that it worked for you and you couldn't reproduce the bug?

**Comment by jcameron** [comment]
Correct, I wasn't able to reproduce this.

**Comment by iliajie** [comment]
What distro and version did you try it on? Did you have multiple templates configured on that system?

**Comment by jcameron** [comment]
I tried it on a Debian 10 system with only a single template. Did you have this issue with the default template, or an extra one?

**Comment by iliajie** [comment]
I had only one, default template in place as well. I will apply all recent patches and try again.

**Comment by harvindersingh115** [comment]
The issue still exists, I am using the following versions: AlmaLinux 9.2, Webmin 2.101, Virtualmin version 7.8.2

**Comment by jcameron** [comment]
@harvindersingh115 can you tell us more about the issue you're seeing?

**Comment by harvindersingh115** [comment]
By default I have php 8 on my virtualmin install, I downloaded php 7 afterwards. I then changed default php version for main template and subdomain template from latest to version 7. However when I am doing cPanel migration it still assigns php-fpm 8 instead of 7. So I have to go inside each virtual server and change manually to version 7.

Hope this helps.

**Comment by iliajie** [comment]
It sounds that we don't detect correctly PHP version used  by cPanel backup file.

@harvindersingh115 Do you have latest Virtualmin 7.8.2 installed, right?

If so, it would help a lot if you could send me or Jamie downloadable link for your cPanel backup.

**Comment by harvindersingh115** [comment]
Yes I have the latest updates installed. I have already provided a cPanel sample to Jamie for FCGI error, same sample can be used to reproduce this issue as well.

**Comment by jcameron** [comment]
I don't think this is specific to cPanel migration, as we don't copy the PHP version from the cPanel backup.

**Comment by jcameron** [comment]
I also re-tested this with your cPanel backup and PHP 8 selected as the default version, and it was enabled just fine.

**Comment by iliajie** [comment]
Jamie, did you have PHP 7 installed as well? Also, did you have set as default FPM mode in templates too?

Harvinder, what default PHP execution mode you had set in templates? What OS and version do you have?

**Comment by jcameron** [comment]
Yes and yes ... I have multiple PHP versions installed.

**Comment by harvindersingh115** [comment]
I had selected php 7 in the templates but cPanel migration still selected 8.

**Comment by iliajie** [comment]
> I had selected php 7 in the templates but cPanel migration still selected 8.

I assume this is clean install with latest Virtualmin 7.8.2, right?

**Comment by harvindersingh115** [comment]
Yes it is pretty minor: AlmaLinux 9.2, Webmin 2.101, Virtualmin version 7.8.2

**Comment by iliajie** [comment]
Could you send me the link for your cPanel backup please? After visiting my GH profile, and with a bit of deduction, you should be able to easily figure it (my email address) out.

**Comment by harvindersingh115** [comment]
> iliajie

I have sent you in a message on virtualmin forums instead

**Comment by iliajie** [comment]
I have given it a closer look and restore file you sent me worked just fine, on both LEMP and LAMP Virtualmin stack! The PHP versions was set to 7.4 and mode to FPM (as I defined it on the template).

Could you provide more details about the template you're using?

  1. Is this the **Default** template?
  2. Can you share the screenshot of **System Settings ⇾ Server Templates: Edit Server Template / PHP options** page?
  3. When you migrated the domain, what exact output did Virtualmin produce for all text matching _PHP_ on the page?

**Comment by iliajie** [comment]
Also, in addition to my previous message, what output of the following command on your Virtualmin system:

```
grep php /etc/webmin/virtual-server/config
```

**Comment by jcameron** [comment]
Did you perhaps install a new PHP version after changing the default to version 8.something? If so, you may need to re-select the default..

**Comment by harvindersingh115** [comment]
> Also, in addition to my previous message, what output of the following command on your Virtualmin system:
> 
> ```
> grep php /etc/webmin/virtual-server/config
> ```

[root@vmi1482067 harvinder]# grep php /etc/webmin/virtual-server/config
php_sock=1
php_vars=+memory_limit=32M
php_log=1
avail_phpini=1
apache_config=ServerName ${DOM}	ServerAlias www.${DOM}	ServerAlias mail.${DOM}	DocumentRoot ${HOME}/public_html	ErrorLog /var/log/virtualmin/${DOM}_error_log	CustomLog /var/log/virtualmin/${DOM}_access_log combined	ScriptAlias /cgi-bin/ ${HOME}/cgi-bin/	DirectoryIndex index.php index.php4 index.php5 index.htm index.html	<Directory ${HOME}/public_html>	    Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch 	    Require all granted	    AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch	</Directory>	<Directory ${HOME}/cgi-bin>	    Require all granted	    AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch	</Directory>
php_suexec=3
phpchildren=
php_session_age=7
php_fpm_port=8000
php8.2cgi=none
php8.4cgi=none
php_ini_5=
php_ini_5.3=
php7.1cgi=none
php_fpm=
php8.0cgi=none
php_ini_7.0=
php_ini_8.0=
php5cgi=none
php8.3fcgi=none
php5.6cgi=none
php5.4fcgi=none
php7.4cgi=none
php5.2fcgi=none
php7.2cgi=none
php7.3fcgi=none
php_ini_8.1=
php5.3cgi=none
php_ini_8.3=
php_ini_7.1=
php8.1cgi=none
php_ini_7.3=
php_ini_5.6=
php7.0cgi=none
php5.5fcgi=none
php_ini_8.2=
php_ini_8.4=
php7.3cgi=none
php5.3fcgi=none
php8.1fcgi=none
php_noedit=0
php7.0fcgi=none
php5.5cgi=none
php_ini_7.4=
php_ini_7.2=
php_log_path=
php5.6fcgi=none
php5.2cgi=none
php7.2fcgi=none
php5.4cgi=none
php7.4fcgi=none
php7.1fcgi=none
php_ini_5.4=
php_ini_5.2=
php8.0fcgi=none
php_ini_5.5=
php5fcgi=none
php8.3cgi=none
php8.4fcgi=none
php8.2fcgi=none
phpver=7.4
last_check_php_vers=8.0
[root@vmi1482067 harvinder]#

**Comment by harvindersingh115** [comment]
> Did you perhaps install an update to PHP version 8 after changing the default to version 8.something? If so, you may need to re-select the default..

No I have not changed or updated PHP 8.0 after installing PHP 7.4

**Comment by jcameron** [comment]
Interesting that in the config file, the default PHP version is shown as 7.4. Can you share a screenshot of the page at System Settings ⇾ Server Templates -> Default Settings -> PHP options ?

**Comment by harvindersingh115** [comment]
<img width="923" alt="Screenshot 2023-10-20 at 15 58 26" src="https://github.com/virtualmin/virtualmin-gpl/assets/7438522/22394dc1-738e-4f16-957b-fb4d8dd386f6">

**Comment by harvindersingh115** [comment]
**Migration output**

Uploading migration file ..
.. uploaded 61.4 KiB
Validating migration file ..
.. done
Starting migration of cpmigratetest.com from uploaded file ..
Checking for cPanel features ..
.. found Home directory, Administration user, Apache website, Log file rotation, Webmin login, DNS domain .
However, the follow features are not supported or enabled on your system : Mail for domain. Some functions of the migrated virtual server may not work.
Checking for clashes and dependencies ..
.. all OK
Creating initial virtual server cpmigratetest.com ..
Creating administration group cpmigtest ..
.. done
Creating administration user cpmigtest ..
.. done
Adding administration user to groups ..
.. done
Creating home directory ..
.. done
Creating mailbox for administration user ..
.. done
Adding new DNS zone ..
.. done
Adding new virtual website ..
.. done
Starting FCGIwrap server ..
.. failed : /home/cpmigtest/public_html/cgi-bin not found
Adding webserver user apache to server's group ..
.. done
Performing other Apache configuration ..
.. done
Setting up log file rotation ..
.. done
Creating Webmin user ..
.. done
Saving server details ..
.. done
Re-starting DNS server ..
.. done
Applying webserver configuration ..
.. done
Restarting PHP-FPM 8.0 server ..
.. done
Re-loading Webmin ..
.. done
Updating Webmin user ..
.. done
Re-loading Webmin ..
.. done
.. done
Copying home directory to /home/cpmigtest ..
.. done
Fixing home directory permissions ..
.. done
Moving server owner's mailbox ..
.. done
Copying Cron jobs ..
.. done
Re-creating FTP users ..
.. done (created 0 FTP users)
Creating sub-domain sub1.cpmigratetest.com ..
Creating home directory ..
.. done
Adding records to DNS zone cpmigratetest.com ..
.. done
Adding to email domains list ..
.. done
Adding new virtual website ..
.. done
Starting FCGIwrap server ..
.. failed : /home/cpmigtest/public_html/sub1/cgi-bin not found
Performing other Apache configuration ..
.. done
Saving server details ..
.. done
Applying webserver configuration ..
.. done
Restarting PHP-FPM 8.0 server ..
.. done
Re-starting DNS server ..
.. done
Updating Webmin user ..
.. done
Re-loading Webmin ..
.. done
.. done
Creating sub-domain sub2.cpmigratetest.com ..
Creating home directory ..
.. done
Adding records to DNS zone cpmigratetest.com ..
.. done
Adding to email domains list ..
.. done
Adding new virtual website ..
.. done
Starting FCGIwrap server ..
.. failed : /home/cpmigtest/public_html/sub2/cgi-bin not found
Performing other Apache configuration ..
.. done
Saving server details ..
.. done
Re-starting DNS server ..
.. done
Applying webserver configuration ..
.. done
Restarting PHP-FPM 8.0 server ..
.. done
Updating Webmin user ..
.. done
Re-loading Webmin ..
.. done
.. done
Creating sub-domain top.cpmigratetest.com ..
Creating home directory ..
.. done
Adding records to DNS zone cpmigratetest.com ..
.. done
Adding to email domains list ..
.. done
Adding new virtual website ..
.. done
Starting FCGIwrap server ..
.. failed : /home/cpmigtest/public_html/top/cgi-bin not found
Performing other Apache configuration ..
.. done
Saving server details ..
.. done
Re-starting DNS server ..
.. done
Applying webserver configuration ..
.. done
Restarting PHP-FPM 8.0 server ..
.. done
Updating Webmin user ..
.. done
Re-loading Webmin ..
.. done
.. done
Successfully migrated cpmigratetest.com virtual server, to manage it.

**Comment by harvindersingh115** [comment]
Template screenshot for sub-servers
<img width="925" alt="Screenshot 2023-10-20 at 16 03 25" src="https://github.com/virtualmin/virtualmin-gpl/assets/7438522/120dc6f8-ae4e-45c4-b5e2-f0ee7fa3f3e5">

**Comment by jcameron** [comment]
If you click on that "Default PHP version" drop-down menu, what versions are shown?

Also, if you SSH in as `root` and run `virtualmin check-config`, what versions does it say are available in FPM mode?

**Comment by harvindersingh115** [comment]
Kind regards
Harvinder Singh

**Comment by harvindersingh115** [comment]
![image](https://github.com/virtualmin/virtualmin-gpl/assets/7438522/5b49257a-c560-4d15-a679-e6b903ed46c8)

**Comment by jcameron** [comment]
If you run `virtualmin check-config` as `root` , you should see a line like `The following PHP-FPM versions are available :` which lists the PHP versions FPM supports..

**Comment by iliajie** [comment]
Also, @harvindersingh115 how exactly did you install PHP 7.4?

Actually, what is the output of `dnf list | grep php | grep @` on your system?

**Comment by harvindersingh115** [comment]
> Also, @harvindersingh115 how exactly did you install PHP 7.4?
> 
> 
> 
> Actually, what is the output of `dnf list | grep php | grep @` on your system?

I followed instructions from this page: https://www.virtualmin.com/documentation/web/multiplephp/

I will send output from terminal commands tomorrow

**Comment by harvindersingh115** [comment]
[root@vmi1482067 harvinder]# dnf list | grep php | grep @
gd3php.x86_64                                                                            2.3.3-9.el9.remi                               @remi-safe         
oniguruma5php.x86_64                                                                     6.9.9-1.el9.remi                               @remi-safe         
php-cli.x86_64                                                                           8.0.27-1.el9_1                                 @appstream         
php-common.x86_64                                                                        8.0.27-1.el9_1                                 @appstream         
php-fpm.x86_64                                                                           8.0.27-1.el9_1                                 @appstream         
php-gd.x86_64                                                                            8.0.27-1.el9_1                                 @appstream         
php-mbstring.x86_64                                                                      8.0.27-1.el9_1                                 @appstream         
php-mysqlnd.x86_64                                                                       8.0.27-1.el9_1                                 @appstream         
php-opcache.x86_64                                                                       8.0.27-1.el9_1                                 @appstream         
php-pdo.x86_64                                                                           8.0.27-1.el9_1                                 @appstream         
php-pear.noarch                                                                          1:1.10.13-1.el9                                @appstream         
php-pecl-zip.x86_64                                                                      1.19.2-6.el9                                   @appstream         
php-process.x86_64                                                                       8.0.27-1.el9_1                                 @appstream         
php-xml.x86_64                                                                           8.0.27-1.el9_1                                 @appstream         
php74-php-cli.x86_64                                                                     7.4.33-8.el9.remi                              @remi-safe         
php74-php-common.x86_64                                                                  7.4.33-8.el9.remi                              @remi-safe         
php74-php-fpm.x86_64                                                                     7.4.33-8.el9.remi                              @remi-safe         
php74-php-gd.x86_64                                                                      7.4.33-8.el9.remi                              @remi-safe         
php74-php-json.x86_64                                                                    7.4.33-8.el9.remi                              @remi-safe         
php74-php-mbstring.x86_64                                                                7.4.33-8.el9.remi                              @remi-safe         
php74-php-mysqlnd.x86_64                                                                 7.4.33-8.el9.remi                              @remi-safe         
php74-php-opcache.x86_64                                                                 7.4.33-8.el9.remi                              @remi-safe         
php74-php-pdo.x86_64                                                                     7.4.33-8.el9.remi                              @remi-safe         
php74-php-pecl-zip.x86_64                                                                1.22.2-1.el9.remi                              @remi-safe         
php74-php-xml.x86_64                                                                     7.4.33-8.el9.remi                              @remi-safe         
php74-runtime.x86_64                                                                     7.4-3.el9.remi                                 @remi-safe         
php80-php-common.x86_64                                                                  8.0.30-1.el9.remi                              @remi-safe         
php80-php-pecl-zip.x86_64                                                                1.22.2-1.el9.remi                              @remi-safe         
php80-runtime.x86_64                                                                     8.0-3.el9.remi                                 @remi-safe         
wbm-php-pear.noarch                                                                      2:1.6-1                                        @virtualmin-noarch

**Comment by harvindersingh115** [comment]
[root@vmi1482067 harvinder]# virtualmin check-config
Your system has 7.49 GiB of memory, which is at or above the Virtualmin recommended minimum of 256 MiB

BIND DNS server is installed 

Apache is installed

CGI scripts can be executed using FCGIwrap

Apache supports HTTP/2 on your system

The following PHP execution modes are available : fpm

The following PHP-FPM versions are available : 8.0.27 (php-fpm) 7.4.33 (php74-php-fpm)

Apache is configured to host SSL websites

MariaDB 10.5.22 is installed and running

Logrotate is installed

Plugin AWStats reporting is installed

Plugin Protected web directories is installed

Using network interface eth0 for virtual IPs

Default IPv4 address for virtual servers is 158.220.82.103

Both user and group quotas are enabled for home and email directories

All commands needed to create and restore backups are installed

The selected package management and update systems are installed

Chroot jails are available

OK

**Comment by harvindersingh115** [comment]
cPanel migration still defaults to PHP 8.0 instead of 7.4 and creating a new server with default template selected still points to PHP 8.0 instead of 7.4

So not sure what is wrong with my installation. I have seen this same issues even after doing a fully clean install after reinstalling AlmaLinux 9. Since I am not using this server as live just yet, I am able to reinstall even the OS and have done it couple of times already with fresh install of virtualmin but always same issue.

**Comment by jcameron** [comment]
Any chance we could login to your system to see what's going on here? I am mystified as to why the wrong PHP version is being selected..

**Comment by harvindersingh115** [comment]
Sure, I have sent you login credentials on virtualmin forum private message

**Comment by jcameron** [comment]
Ok I found the issue, and patched it on your system! A fix will also be included in the next Virtualmin release..

Thanks for reporting this bug and helping us solve it!
