### ISSUE TITLE
Amazon Aurora - cannot set password when creating virtual server

### ISSUE THREAD

**Issue by versantus** [virtualmin/virtualmin-gpl#4]
I've been experimenting with using Amazon Aurora as a remote MySQL database for Virtualmin. There seems to be an incompatibility, based around the way Virtualmin creates and updates MySQL users. 

If I set the Aurora details in Webmin > Servers > MySQL Database Server > Config, Virtualmin correctly tries to create the database and users when I create a new Virtual Server.

However, upon creation, and at modification time, I get an error
"set password for 'example'@'hostname.com'=password('greatpassword') failed: Can't find any matching row in the user table"

The server is created, and the MySQL user is added to the database on Aurora, but no password is set.  Attempts to modify the server result in the same error, as do the same efforts from the virtualmin CLI tool ("virtualmin modify-database-pass  --domain mydomain.com --type mysql --pass "greatpassword"")

Trying to run the same SQL ("set password for....") directly on the Aurora DB also fails with the same error, even though the user definitely exists ("select * from user where User='example' and host='hostname.com'" returns the result).

A simple fix is to change the way Virtualmin sets and updates the password in /usr/share/webmin/virtual-server/feature-mysql.pl so that it specifies the user and host params in a different way.

Once this change is made, the user is created on the database, and can be modified as normal.

```
diff --git a/feature-mysql.pl b/feature-mysql.pl
index 33c52dd..cf64c82 100755
--- a/feature-mysql.pl
+++ b/feature-mysql.pl
@@ -2637,7 +2637,7 @@ if (&compare_versions($remote_mysql_version, "5.7.6") >= 0) {
        return ("insert into user (host, user, ssl_type, ssl_cipher, x509_issuer, x509_subject, plugin, authentication_string) values ('$host', '$user', '', '', '', '', 'mysql_native_password', $encpass)");
        }
 elsif (&compare_versions($remote_mysql_version, 5) >= 0) {
-       return ("insert into user (host, user, ssl_type, ssl_cipher, x509_issuer, x509_subject) values ('$host', '$user', '', '', '', '')", "flush privileges", "set password for '$user'\@'$host' = $encpass");
+       return ("insert into user (host, user, ssl_type, ssl_cipher, x509_issuer, x509_subject) values ('$host', '$user', '', '', '', '')", "flush privileges", "update user set password=$encpass where User='$user' and Host='$host'");
        }
 else {
        return ("insert into user (host, user, password) values ('$host', '$user', $encpass)");
@@ -2665,7 +2665,7 @@ foreach my $host (&unique(map { $_->[0] } @{$d->{'data'}})) {
                $flush++;
                }
        else {
-               $sql = "set password for '$user'\@'$host' = $encpass";
+           $sql = "update user set password=$encpass where User='$user' and Host='$host'";
                }
        &mysql::execute_sql_logged($mysql::master_db, $sql);
        }

```

**Comment by swelljoe** [comment]
I believe this has been fixed upstream in Webmin's MySQL module, due to the issue you filed at virtualmin.com (thanks for following up over there, we like this tracker better, but sometimes miss things over here because we have so many repos and so many notifications).

If that ticket (https://www.virtualmin.com/node/52366) isn't actually resolved, feel free to re-open.
