### ISSUE TITLE
Combine under one checkbox Apache website and Apache SSL website

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#402]
Jamie, what do you think about [combining under one checkbox](https://forum.virtualmin.com/t/nginx-virtual-hosts-that-only-listen-on-port-443/115514/30?u=ilia) Apache website and Apache SSL website (same for Nginx).

When enabling/creating a virtual server it would be cleaner.

Although, if we change that, how are we gonna handle various other pages that offer enabling website and SSL website features separately? Do you think we can do it easily and in a straightforward way, without introducing new bugs? Also, will that work with a restore?

**Comment by jcameron** [comment]
I think this would be a good idea. Back in the old days we used to have SSL enabled separately because it needed it's own private IP and getting a cert was difficult, but that's no longer the case.

**Comment by jcameron** [comment]
For example, Virtualmin will automatically enable the `logrotate` feature when a website is enabled. We could do the same for SSL.

**Comment by iliajie** [comment]
I mean, performing a large rework on this front maybe dangerous.

Thinking technically (even though probably not entirely correct design wise), it's trivial to make a checkbox hidden on UI, while still being submitted to the server (i.e. Apache SSL website enabled) if Apache website features was checked. The same would be true for unchecked.

CLI should have this functionality intact in my opinion.

What we could simply do is to write few lines of JavaScript code on Virtualmin side, which will hide SSL website feature, and attach the listener to regular website feature checkbox.

I also don't understand why `logrotate` feature should be attached to a website. While `awstats` is obvious but why `logrotate`?

**Comment by jcameron** [comment]
I think I can do this pretty safely without any javascript. Let me deal with this one, as I already have a good idea for how to implement it ..

**Comment by iliajie** [comment]
Great!

**Comment by jcameron** [comment]
I've written code for inclusion in the 7.5 Virtualmin release that will allow the SSL feature to be automatically activated when a non-SSL website is. We can also make this the default in future Virtualmin installs..

**Comment by iliajie** [comment]
I have checked the new code and the new `can_chained_feature` sub and it seems the only way to make it work is to set `ssl=3` on the Virtualmin config manually?

Also, if SSL for a domain is currently disabled, and then you manually change it to `ssl=3` and then if you go to Edit Virtual Server page and hit save, and even though Apache website is enabled, but SSL is not getting added, unless you first disable Apache website feature first, and re-enable over again.

Moreover, if you go to Feature and Plugins and disable Apache SSL website and then re-enabled it, then it won't be set to `ssl=3` again. Perhaps, in case of a chain feature we shouldn't display it on Features and Plugins page too?

**Comment by jcameron** [comment]
> I have checked the new code and the new can_chained_feature sub and it seems the only way to make it work is to set ssl=3 on the Virtualmin config manually?

The ssl config option will also be set to 3 if you enable the SSL feature on the Features and Plugins page, and have the box in the "Default" column checked. But I do plan to update the Virtualmin installer to set it to 3, like we do for logrotate.

> Also, if SSL for a domain is currently disabled, and then you manually change it to ssl=3 and then if you go to Edit Virtual Server page and hit save, and even though Apache website is enabled, but SSL is not getting added, unless you first disable Apache website feature first, and re-enable over again.

Hmmm ... that's a good point. Maybe if the feature isn't enabled, we should still allow it to be enabled? I'll fix that..

**Comment by jcameron** [comment]
Ok I checked in some fixes for this.

**Comment by iliajie** [comment]
Yeah, alright, it's fixed. Thank you! Tested and it works, and also more explicit now, as you can just enable manually chained feature later.

I have another suggestion. I think we should be more clear about the features being chained upon disabling. It may be unclear where those Apache SSL Website and Logrotate is popping up from, when one simply disabled Apache Website feature _only_:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/4426533/208236774-b2f06c1f-97f2-44c7-961f-0cba29fbad6b.png">

**Comment by jcameron** [comment]
Maybe we should just hide those?

**Comment by iliajie** [comment]
Or we should improved _Edit Virtual Server_ page and print dependent features under the parent feature (clearly instead of hiding it .. I was always confused with those missing/hidden features) .. and also replace checkboxes with a new nice toggles. So, toggling the parent would automatically and clearly unselect all children, and enabling one of the children would automatically toggle on (enable) the parent.

Although, Apache SSL and Nginx SSL shouldn't be mentioned _at all_ in `ssl=3` mode, but in if it's not _Default?_ then we could print it as a child too.

**Comment by jcameron** [comment]
I actually prefer to hide them, because the UI is already quite complex already and anything we can do to simplify it would be an improvement.

**Comment by jcameron** [comment]
I checked in https://github.com/virtualmin/virtualmin-gpl/commit/86a1cc9750dff0be0690184daf19c1ccea695bff

**Comment by swelljoe** [comment]
I love getting rid of options!

**Comment by iliajie** [comment]
Me too! But having features pop up out of the blue is confusing and unintuitive either.

**Comment by jcameron** [comment]
Well, from the point of view of the user, they shouldn't even see or care about these features. Basically when the Apache feature is enabled, logrotate and SSL should get enabled transparently.

**Comment by iliajie** [comment]
Alright, let's keep it as that for now.

Worth mentioning that even though we have default for user and home enabled (i.e. `unix=3` and `dir=3`) in _Features and Plugins_, it's still displayed on _Edit Virtual Server_ page:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/4426533/208306440-621f741f-dee2-4059-a9e7-09ea5b646770.png">

Is this a bug?

**Comment by jcameron** [comment]
Yeah for those features, they aren't chained from other features. I forget what `3` means though.

**Comment by iliajie** [comment]
We didn't show _Server administrator exists_ and _Home directory exists_ options before in _Create/Edit Virtual Server_ pages, so now we do .. is this intentional?

**Comment by iliajie** [comment]
Alright, now it looks and works as expected. Thank you!

**Comment by iliajie** [comment]
> We can also make this the default in future Virtualmin installs..

Check [this patch](https://github.com/virtualmin/virtualmin-gpl/commit/7bc87bce1d6275bf9234c3d2cb78346e6da3bc04) out, Jamie.

**Comment by jcameron** [comment]
I was thinking to do it in the Virtualmin install script, like we do here : https://github.com/virtualmin/Virtualmin-Config/blob/master/lib/Virtualmin/Config/Plugin/Virtualmin.pm#L55

**Comment by iliajie** [comment]
> I was thinking to do it in the Virtualmin install script, like we do here : https://github.com/virtualmin/Virtualmin-Config/blob/master/lib/Virtualmin/Config/Plugin/Virtualmin.pm#L55

Yes, this is not problem to do, but why we cannot make it in Virtualmin config instead?

**Comment by iliajie** [comment]
Alright, added here https://github.com/virtualmin/Virtualmin-Config/commit/e0989d3d4d7a6f91995260bb8b20fd1225b07e7e and reverted previous commit on the actual config. However, I don't really understand why we cannot just add it on the config iteself?

**Comment by jcameron** [comment]
I forget why we did it this way, but I'd like to keep things consistent..

**Comment by iliajie** [comment]
Got it. Thanks.

**Comment by iliajie** [comment]
> Ilia: We didn't show Server administrator exists and Home directory exists options before in Create/Edit Virtual Server pages, so now we do .. is this intentional?
> > Jamie: No .. I'll check in a fix for that.

I still see it with Virtualmin 7.5 code?

**Comment by jcameron** [comment]
Oops I didn't fix the domain creation form properly - doing that now.

**Comment by iliajie** [comment]
That patch fixes the problem! Thanks.
