### ISSUE TITLE
virtualmin modify-dns cli feature request

### ISSUE THREAD

**Issue by lukesUbuntu** [virtualmin/virtualmin-gpl#403]
Not an issue but a nice to have.

I went to the cli to type 
`virtualmin modify-dns --all-domains --spf-add-include relay.example.com`

But found out Virtualmin cli doesn't support the option for setting the include: to the spf record in bulk, only supports,  a , mx , ip4 , ip6 not sure if there is a work around have 250+ domains to update, so having to script it.

**Comment by jcameron** [comment]
Good idea, I will add a flag for this in the next Virtualmin release.
