### ISSUE TITLE
Icon misaligned - Schedule and reporting - Complex Schedule

### ISSUE THREAD

**Issue by mrkylegp** [virtualmin/virtualmin-gpl#405]
I noticed this small alignment issue of the icon for the complex schedule button. 

It is not centred vertically.

Tested in:
Chrome Version 102.0.5005.115 (Official Build) (64-bit)
Version 102.0.1245.44 (Official build) (64-bit)

Virtualmin 7.1-1
Webmin 1.994

![Screenshot 2022-06-17 082617](https://user-images.githubusercontent.com/52687659/174188958-0e8cda76-315a-46b1-bc43-e8d2a0a5f1f4.png)

**Comment by iliajie** [comment]
Thanks, you're right. We will fix that.
