### ISSUE TITLE
DNSSEC cryptographic algorithm not updated correctly

### ISSUE THREAD

**Issue by Chaots** [virtualmin/virtualmin-gpl#406]
On a virtualmin domain that has dnssec that then is disabled, Webmin does not check for changes to the "DNSSEC cryptographic algorithm" setting selected in the server template settings when one re-enables dnssec with a different algorithm in the template. Or the selected algorithm in the bind dns server module drop down for the "setup dnssec key" on a specific domain.

1 Create domain.
2 Enable dnssec with algorithm rsasha1 in the server template.
3 Disable dnssec for the domain, in the background Virtualmin saves the previous keys in the bind directory.
4 Change the algorithm to ecdsap256shs256 in the server template's dns settings. 
5 Enable dnssec for the domain.

The problem:
Virtualmin uses the former key algorithm instead of generating a new key based on the new set algorithm.

This happens for both dnssec edit options. regardless what algorithm is selected, it is ignored.
- Via dns options on the Virtualmin domain, option disable and then enable dnssec.
- Via the "Webmin -> Servers -> bind dns server -> select domain -> setup dnssec key" for a specific domain option.

Manually deleting the domains "k* .saved" keys files in the bind config directory /var/named makes Virtualmin generate a new key pair with the correct algorithm.

I suspect this bug is introduced by the fix made for this bug: (https://sourceforge.net/p/webadmin/bugs/5552/)

Steven

**Comment by jcameron** [comment]
Thanks for reporting this - we'll fix this with changes in the next Webmin and Virtualmin releases.
