### ISSUE TITLE
Removing email from a website do not remove all the autoconfig part

### ISSUE THREAD

**Issue by aqueos** [virtualmin/virtualmin-gpl#408]
hi,

 if i create an website with email it creates:
```
    ServerAlias autoconfig.testwithemail.com
    ServerAlias autodiscover.testwithemail.com

    ScriptAlias /AutoDiscover/AutoDiscover.xml /home/testwithemail/cgi-bin/autoconfig.cgi
    ScriptAlias /Autodiscover/Autodiscover.xml /home/testwithemail/cgi-bin/autoconfig.cgi
    ScriptAlias /autodiscover/autodiscover.xml /home/testwithemail/cgi-bin/autoconfig.cgi
    Redirect /mail/config-v1.1.xml /cgi-bin/autoconfig.cgi
    Redirect /.well-known/autoconfig/mail/config-v1.1.xml /cgi-bin/autoconfig.cgi
```

then if email move to google or other small business killers you remove email from site capacity and save BUT:
```

    ServerAlias autoconfig.testwithemail.com
    ServerAlias autodiscover.testwithemail.com

    ScriptAlias /AutoDiscover/AutoDiscover.xml /home/testwithemail/cgi-bin/autoconfig.cgi
    ScriptAlias /Autodiscover/Autodiscover.xml /home/testwithemail/cgi-bin/autoconfig.cgi
    ScriptAlias /autodiscover/autodiscover.xml /home/testwithemail/cgi-bin/autoconfig.cgi
    Redirect /mail/config-v1.1.xml /cgi-bin/autoconfig.cgi
    Redirect /.well-known/autoconfig/mail/config-v1.1.xml /cgi-bin/autoconfig.cgi
```

are still there and not removed :(

  It should be removed with the email capability, if not the autoconfig will have problems and redirect to the host instead of the google or MS servers. Hope that helps.

best regards,
Ghislain.

**Comment by jcameron** [comment]
Can you explain further what problem this causes for Outlook? Is it an issue when you are hosting email with Google instead of locally?

**Comment by aqueos** [comment]
Well it is simple, when the email client try to reach the autoconfig URL, virtualmin continue to provide it, telling the client to configure itself one the virtualmin host, therefor it does not go to the autoconfig on office 365 or google and will fail. Some that use the dns will work but the one using the url will fail.

Also if the domain do not provide any email it should not have those email related setting stay in place anyway :)

 This is why when you remove local email processing for a website the configuration for emails in apache/nginx should be removed with it imho :)

best regards,
Ghislain.

**Comment by jcameron** [comment]
Makes sense - we'll fix this in the next Virtualmin release.
