### ISSUE TITLE
PHP-FPM server connection type change

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#411]
Jamie, if we create a domain with PHP-FPM configured on a template to use TCP ports, then directive `php_fpm_port` is added to the domain config. All is good here.

However, the real problem pops up when you switch default PHP-FPM server connection type to sockets in templates. And if later you change PHP execution mode to FCGId and again back to PHP-FPM, then TCP port PHP configuration is still being added on Apache config for the domain, and things fail with _HTTP/1.1 503 Service Unavailable_ error.

The fix for this problem was simply removing `php_fpm_port` from domain config and toggling to PHP-FPM execution mode. 

We either need to ignore `php_fpm_port` if template is set to use sockets or configure it properly (i.e. domain pool config should get port instead of socket for listen directive). I think it would be better to ignore `php_fpm_port` in case a socket mode is configured on a template, to let a user get an actual configuration.

All of this was tested on Ubuntu 20.04 with LAMP stack and super latest patches applied from the repo.

Configs that are generated by Virtualmin:

1. Pool file `/etc/php/7.4/fpm/pool.d/1646778731239787.conf
`

```Conf
[1646778731239787]
user = ubuntu20-pro
group = ubuntu20-pro
listen.owner = ubuntu20-pro
listen.group = ubuntu20-pro
listen.mode = 0660
listen = /var/php-fpm/1646778731239787.sock
pm = dynamic
pm.max_children = 9999
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 5
php_value[upload_tmp_dir] = /home/ubuntu20-pro/tmp
php_value[session.save_path] = /home/ubuntu20-pro/tmp

```

2. Part of Apache config:

```
...
...
<FilesMatch \.php$>
    SetHandler proxy:fcgi://127.0.0.1:8000
</FilesMatch>
```

**Comment by jcameron** [comment]
See if the fix I just checked in for this bug helps.

**Comment by marclaporte** [comment]
@iliajie Can we close this?

**Comment by iliajie** [comment]
Hello, Marc. Thanks for the heads-up! Yes, I remember this issue was fixed a long time ago.
