### ISSUE TITLE
Disable Virtual Server htaccess 

### ISSUE THREAD

**Issue by sam-anam1** [virtualmin/virtualmin-gpl#412]
When Disable Virtual Server the ${HOME}/public_html  htaccess file should be disabled too
it does make sense that .htaccess should be inactive with user public.. 
or have an option if some world users would like to have 
"AllowOverride All"  for ovarll htaccess 

some sites used the below in their .htaccess
Options +SymLinksIfOwnerMatch
RewriteRule ^(.*)\.html$ $1.php [nc]

which case 500 error

also when WHMCS suspended Virtual Server it doesn't disabled sub-servers.
I think disable sub-servers option could be Yes by default that billing automation should disable all user account including sub virtual server.

So, its two problems for Disable Virtual Server
- .htaccess being overridden when disable virtual server.
- billing & automation platform should disabled sub-servers.

**Comment by jcameron** [comment]
Are you suggesting that users not be able to use `.htaccess` files by default? 

The default Apache config for new domains can be edited at System Settings -> Server Templates -> Default Settings -> Website for domain

**Comment by sam-anam1** [comment]
> Are you suggesting that users not be able to use `.htaccess` files by default?
> 
> The default Apache config for new domains can be edited at System Settings -> Server Templates -> Default Settings -> Website for domain

Hi @jcameron
Nope, we are talking about when **disable virtual server** 
for the first point "htaccess being overridden with disabled website"
My suggestion is apache setting  should be **AllowOverride None** only when you disabled virtual server!

For example
if you set  .httacess with rewrite rule for changing html and htm extensions to php

like you add this to your htaccess 
`RewriteRule ^(.*)\.htm /$1.php [R=301,L]
RewriteRule ^(.*)\.html /$1.php [R=301,L]`

and then try to disable your website.

**Comment by jcameron** [comment]
Ok I see what you mean. We'll fix this in the next Virtualmin release.
