### ISSUE TITLE
Server Templates: Sub-Servers - an option doesn't get saved

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#417]
Jamie,

When trying to change and save `Available to server owners` option for Sub-Servers templates it doesn't get saved on hitting either `Save` or `Save and Next` buttons:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/4426533/178753768-0cf5cf45-ce87-4366-9a0a-7629f287eb37.png">

**Comment by jcameron** [comment]
Thanks, I'll fix this in the next Virtualmin release.
