### ISSUE TITLE
Keep configuration files indentation after automatic actions

### ISSUE THREAD

**Issue by qooob** [virtualmin/virtualmin-gpl#42]
Jamie, hi!

Some admins are very picky on keeping configuration files easily readable and properly formatted.

I have indentation inside `<VirtualHost> ... <\VirtualHost>`

After Virtualmin runs SSL update it breaks it.

After:

```
	
	SSLEngine On
 SSLCertificateFile /home/user/cert.cert
 SSLCertificateKeyFile /home/user/cert.key
 SSLCACertificateFile /home/user/cert.ca
```

Before:

```
	
	SSLEngine On
	SSLCertificateFile /home/user/cert.cert
	SSLCertificateKeyFile /home/user/cert.key
	SSLCACertificateFile /home/user/cert.ca
```

Can this be fixed please?

**Comment by jcameron** [comment]
That's actually pretty tricky, because Webmin discards all comments and whitespace when parsing the config file. So by the time it comes to re-writing that line, any information about indentation is lost.

**Comment by qooob** [comment]
Can't we read files with respect to indentation? It's not nice at all to do that? Don't you like nice-looking config files? 😄

**Comment by jcameron** [comment]
I do like nice config files, but the catch is that Webmin parses configs into internal data structures that don't preserve indentation as it's not semantically meaningful.

**Comment by swelljoe** [comment]
There would need to be a separate data structure for the, um, structure of the file...and it'd have to guess for directives that weren't already in the file and are being added by Webmin. With something like XML there are standard tools for formatting and validating based on rules. Some config files probably have formatter tools available, but they'd have the negative of possibly altering the user's existing format.

Jamie's right...this is a tough problem. Without having a complete parser for every config file format (one that understands far more about the structure of the files than Webmin currently understands), I don't see how it'd be done in a way that wouldn't potentially introduce subtle bugs.

**Comment by qooob** [comment]
For adding new strings - yes, it's difficult to figure out the padding.

Initially I was talking to have whitespaces preserved for existing strings, which means just to find out if it exists, and then replace it with maintaining padding. In case it doesn't exist, then just insert as it it.

However, thinking right now, it would be possible to read previous line indentation an use it upon insertion?

**Comment by jcameron** [comment]
You know, looking at the code for the Apache module, indents for existing edited directives should be preserved. What page were you using in Virtulamin that causes them to go away?

**Comment by qooob** [comment]
Let's Encrypt automatic renewal, I suppose.

**Comment by jcameron** [comment]
Are you indenting with tabs or spaces?

**Comment by qooob** [comment]
Ha-ha 😂 I do tabs. Always tabs. But I'm sure there are those that do spaces.

**Comment by jcameron** [comment]
Ok, that explains it - I'll fix this in the next Webmin release.
