### ISSUE TITLE
Ubuntu 22.04 and VM7, Fail2ban not enabled after install

### ISSUE THREAD

**Issue by hans-nl** [virtualmin/virtualmin-gpl#427]
After a fresh Ubuntu 22.04 install followed by an error free VM7 RC8 or RC11 install Fail2ban is not enabled.
The solution is simple: run 'systemctl enable fail2ban' followed by 'systemctl start fail2ban'.

**Comment by iliajie** [comment]
Thanks for the heads up! That must be already fixed in our development code.
