### ISSUE TITLE
IPv6: Change IP address page

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#428]
Jamie, if you go to `virtual-server.name - Server Configuration ⇾ Change IP Address` page and enter manually `fe80::11:32ff:fe26:5418/64` as IPv6 address (using prefix length, i.e.`/64`), then `activate_ip6_interface` will also receive and pass this address to `net::activate_interface`, and even though the error message on UI says:

```
Updating IP addresses in virtual server virtual-server.name
.. Failed to change IP address : Failed to add IPv6 address : Error: inet6 prefix is expected rather than "fe80::11:32ff:fe26:5418/64/64".
```

but the main problem that it still saves net config and breaks `netplan` on Ubuntu 22.04:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/4426533/184480304-f30ed85f-9bb6-4869-9a25-6c065ad76855.png">

**Comment by chris001** [comment]
It has two  subnet masks.. `/64/64`!  `fe80::11:32ff:fe26:5418/64/64`. It should be `fe80::11:32ff:fe26:5418/64`.

**Comment by iliajie** [comment]
Thanks Chris. Yeah, I know. This is the whole point of this bug report, that prefix-length (as you called it subnet mask) is being added by Webmin API disregard if it's already present on the passed address.

Jamie, we need to test if prefix-length is being set already and not double adding it.

**Comment by jcameron** [comment]
I see the cause of this - checking in a fix now.

**Comment by iliajie** [comment]
It seems that this change solely won't affect Virtualmin users?

**Comment by jcameron** [comment]
It's only a change to Virtualmin .. which is where the bug is, right?

**Comment by iliajie** [comment]
Yeah, I thought it was a commit to Webmin repo. Unfortunately GitHub mobile is confusing yet.
