### ISSUE TITLE
Unintended data loss: Disabling SQLite Databases feature on a domain deletes MySQL databases

### ISSUE THREAD

**Issue by SamSirry** [virtualmin/virtualmin-gpl#430]
If a domain has both the SQLite and MySQL Databases features enabled, with existing databases, then the SQLite DB feature is disabled (via `Edit Virtual Server` page), a confirmation is prompted:

```
Are you sure you want to save the domain example.com? The following features have been selected for deletion :

    SQLite Databases - All SQLite databases owned by this virtual server will be deleted.
```

Answering yes deletes the MySQL databases (not SQLite databases).

OS: Debian 11
Virtualmin ver 7.1-1
SQLite components installed manually after installing Virtualmin: `apt install sqlite3 php-sqlite3 webmin-virtualmin-sqlite`

**Comment by jcameron** [comment]
That's surprising, and definitely a bug! Was the MySQL feature still selected on the Edit Virtual Server page?

**Comment by SamSirry** [comment]
I had a dream that I was mistaken about this. Really. So the first thing I did as I woke was to test it again, and I realized that this report is not correct.

The reason it happened the first time was another person working on the site deleting the database at the moment I confirmed the removal of the feature.

I apologize for wasting your time and effort on this.

**Comment by jcameron** [comment]
Ok, that would explain it!
