### ISSUE TITLE
Script installers does not check for supported PHP versions

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#433]
Script installers offers update to Roundcube 1.6.0. Which should not be done on Ubuntu 18.04 as only PHP 7.2. is installed by default:
```
php --version
PHP 7.2.24-0ubuntu0.18.04.13 (cli) (built: Jul  6 2022 12:23:22) ( NTS )
```

[Roundcube dropped support for PHP < 7.3 in 1.6.0
](https://github.com/roundcube/roundcubemail/releases/tag/1.6.0)

There is no mention of this incombatibility during the update progress. I even get emails about 'Virtualmin script upgrades available' which lists the script.

Either there is no check performed for needed php versions or it is broken …

**Comment by iliajie** [comment]
Hello,

Thank you for your suggestion! We will fix that.
