### ISSUE TITLE
maintaining old config file versions

### ISSUE THREAD

**Issue by kintaro1981** [virtualmin/virtualmin-gpl#44]
is already possible to maintain old configuration files after an edit?

For example if I edit php.ini and the old php.ini became `filename.ext.DATE-TIME` (with date configurable DATE/TIME for Europe/USA standards.)

Example:
`php.ini.2018-15-01-093212`

If is not already possible, how about it?

**Comment by swelljoe** [comment]
It is not currently possible. There are third-party ways to achieve what you're after, though; etckeeper (http://etckeeper.branchable.com/)is a popular one.

We wouldn't want to do it in the same directory with an extension as it would clutter it up, but I would like to see the ability to store configs in git in some other directory. That might just be in the form of a Webmin module for etckeeper, or similar.

**Comment by jcameron** [comment]
We have a Webmin feature that is a bit similar to this already - the file change logging in the Webmin Actions Log module.
