### ISSUE TITLE
`Website Options`: Redirect all requests to SSL site

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#444]
Jamie, when creating a `domain.com` and enabling SSL redirect on `domain.com - Server Configuration ⇾ Website Options` page all works fine. If you add an alias to the domain, then redirect from `alias1.domain.com` happens to `domain.com`.

This is undesirable. Can we preserve initial (requested) domain (alias) upon redirect?

**Comment by chris001** [comment]
Related, an option to redirect `www.domain.tld` to `domain.tld`, or redirect `domain.tld` to `www.domain.tld`, or none.

**Comment by iliajie** [comment]
Yeah, we should redirect request URI to `https`, and that's all (I think).

**Comment by chris001** [comment]
It looks like it already has the redirect request URI to `https`, under "Server Configuration" / "Website Options" / "Redirect all requests to SSL site : Yes No"

**Comment by jcameron** [comment]
This feature has been implemented for inclusion in the next Virtualmin release.

**Comment by iliajie** [comment]
> This feature has been implemented for inclusion in the next Virtualmin release.

That seems to work just fine! Thanks, Jamie.
