### ISSUE TITLE
Renewed LetsEncrypt Certs (by Certbot) Not Used by Virtualmin

### ISSUE THREAD

**Issue by kim-ln** [virtualmin/virtualmin-gpl#445]
- os debian 11 (bullseye)
- webmin 1.999
- virtualmin 7.1-1
- certbot 1.12.0

---

- I checked `virtualmin list-certs-expiry --all-domains --sort expiry` and found domains that expire in well under 30 days (e.g. 21 days). Paths are in either `/home/<user>[/domains/<domain>]` or `/etc/ssl/virtualmin/<domain id>`.
- However in `/var/log/letsencrypt/letsencrypt.log`, I see that those domains have been skipped for renewal because they will expire well over 30 days in the future, e.g. `/etc/letsencrypt/live/<domain>/fullchain.pem expires on 2022-12-03 (skipped)` (=82 days).
- Requesting the certificate manually by virtualmin works flawlessly.
- Probable reason is that renewal has been handled by `certbot.timer`, but no deploy hook (`man certbot` and look for `--deploy-hook`) was provided to trigger virtualmin to copy the new files and to restart/reload services using the certificate. Should this have been the case?

**Comment by jcameron** [comment]
Virtualmin will renew certs that it knows about via it's own scheduled process, which runs all the correct hook scripts. Renewals that are done in the background by Let's Encrypt may not work, because they're not under our control.

So my recommendation is always to let Virtualmin do it..

**Comment by kim-ln** [comment]
Thank you Jamie, that is very good to know. 

As autorenew has always been enabled in Virtualmin, I was still wondering whether the certificates that will expire in 21 days should have been renewed by Virtualmin. But I found it (they should not have been renewed, but will be very soon), so I will close the issue.

---

For those interested:

21 days is the default limit for certificates to be renewed. The renewal is handled as follows by Virtualmin:
- The scheduled process Jamie mentioned is a Webmin cron/Webmin Scheduled Function (which are run from `/usr/share/webmin/miniserv.pl`, i.e. the Virtualmin webserver process). Its config is in `/etc/webmin/webmincron/crons/` on my system and it calls `/usr/share/webmin/virtual-server/collectinfo.pl`.
- In collectinfo.pl `apply_letsencrypt_cert_renewals` is called.
- This function is in `/usr/share/webmin/virtual-server/feature-ssl.pl` and in it, the number of days is set to 21 if not configured:
  ```perl
  my $before = $config{'renew_letsencrypt'} || 21;
  ```

Debian's certbot package has a crontab (`/etc/cron.d/certbot`) that renews its certs out of the box. However as observed initially, these are not used by Virtualmin. (Makes sense, I guess: this way it is less dependent on the specifics of the package that is used to obtain the certificates.) This extra renewal doesn't hurt normally, although it consumes Let's Encrypt's resources unnecessarily for most Virtualmin users, according to me. You might therefore opt to disable the crontab.

**Comment by chris001** [comment]
You're right!  @jcameron For Virtualmin and `certbot` to compete and double renew an LE cert is bad and should avoid.  Can Virtualmin decode the cert expiry date, check it just before it's supposed to renew it, and NOT renew it if was already renewed and is valid for more than `$before` days, obviously `certbot` raced to renew it first, and did in fact do so with its own `cron`?
