### ISSUE TITLE
Password generation not available via edit user page

### ISSUE THREAD

**Issue by hayden-t** [virtualmin/virtualmin-gpl#447]
It is when creating user but not if changing password. Virtualmin 7

**Comment by iliajie** [comment]
Hello,

Can you share a screenshot of what you're seeing.

**Comment by hayden-t** [comment]
![image](https://user-images.githubusercontent.com/1000743/190575538-b9c62d5d-62fc-46ba-be6e-a188e89cf1b3.png)

**Comment by iliajie** [comment]
You need to make sure that you're running the latest Webmin version.

**Comment by hayden-t** [comment]
I am, this is a fresh install in debian 11, what does this have to do with webmin ?? Virtualmin user creation page has the password generator button that works fine, its it was forgotten to add it also to the edit user page.

**Comment by iliajie** [comment]
I can see it on edit virtual server page too. Can you try incognito tab?

**Comment by hayden-t** [comment]
Yes is is there, i said "EDIT USER PAGE"

**Comment by iliajie** [comment]
Fixed. Thanks.
https://github.com/webmin/authentic-theme/commit/36bc932f8b8a2b8c334607b0a24154aec10e5e47

**Comment by hayden-t** [comment]
thank you :)
