### ISSUE TITLE
Server Templates: Missing conditional test for MariaDB vs MySQL

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#449]
Work has been done in various places in Virtualmin to communicate to end user if MySQL is being used, vs MariaDB.

![2022-09-17_220650](https://user-images.githubusercontent.com/1004261/190882553-e7f31869-b125-4edb-9253-5d0e78df7f62.png)

**Comment by jcameron** [comment]
Thanks for pointing this out ... we'll fix that in the next release by adding the $MYSQL_TYPE template variable that will be set to "MySQL" or "MariaDB" as appropriate.

**Comment by marclaporte** [comment]
Thank you @jcameron
