### ISSUE TITLE
Understanding New Vhost creation same name as machine name

### ISSUE THREAD

**Issue by Vagrantin** [virtualmin/virtualmin-gpl#45]
**Version**
Debian 9
Apache 2.4
Webmin 1.870
Virtualmin 6.01

**Background info**
Machine name : my.dom.org  
The first time I had to declare a domain name in Virtualmin I choose``my.dom.org`` instead of ``dom.org``.
So ``my.dom.org`` was my first Vhost.  
I have delete it some time after.

**The issue**
From here if I want to re-create a virtual hosts for ``my.dom.org`` Virtualmin tells me the documentRoot are stored in ``/home/my/public_html/``.  
But if I access the website I got the standard Apache Debian default page, and after some testing I could confirm that the Document root is instead ``/var/www/``.  

The consequence is that Virtualmin expect all data to be in ``/home/my/public_html/`` but Apache looks at ``/var/www/``.  
For instance it's impossible to request a certificate with Let's Encrypt, always failing because ``.well-known`` can't be found.

In the ``/sites-available`` I have along with other vhost  
_000-default.conf > /var/www/html_  
_my.dom.org > /home/my/public_html_  

Not sure if I have done something wrong, and what would it be,if this can be fix without braking all my Apache/Virtualmin setup ?
Could it be a normal behavior ?

Thanks for the clarification

Matth

**Comment by jcameron** [comment]
Does this happen for ALL new domains that you create, or just my.dom.org ?

**Comment by Vagrantin** [comment]
It's just happening to my.dom.org.

**Comment by jcameron** [comment]
Is that the same name as the hostname of your system?

**Comment by Vagrantin** [comment]
Yes this is happening for the vhost which has the same name has the machine name.

**Comment by jcameron** [comment]
Ok, the cause is likely that your Apache config by default serves request for the hostname from the default /var/www/html directory. Check your Apache config files for a line like `ServerName your.hostname` , change it, and restart Apache.

**Comment by Vagrantin** [comment]
Okey, perfect now I got it thanks for the clarification !
