### ISSUE TITLE
Server Templates (default settings): Missing conditional test for MariaDB vs MySQL

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#452]
Work has been done in various places in Virtualmin to communicate to end user if MySQL is being used, vs MariaDB.

![2022-09-28_010449](https://user-images.githubusercontent.com/1004261/192692434-afd3f4f8-9a24-48e3-ba52-f85996396850.png)

**Comment by jcameron** [comment]
Thanks for pointing this out - we'll fix it in the next Virtualmin release.
