### ISSUE TITLE
A few more missing conditional tests for MariaDB vs MySQL

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#453]
![2022-09-28_014025](https://user-images.githubusercontent.com/1004261/192697371-1cb60aa5-f1f0-4737-8c1f-e435b05128da.png)
![2022-09-28_013838](https://user-images.githubusercontent.com/1004261/192697373-87853bfa-3528-4ef5-9fa6-0a34771a381c.png)
![2022-09-28_013744](https://user-images.githubusercontent.com/1004261/192697374-fce27073-9b70-4bb8-bf73-4f25b581e927.png)

**Comment by iliajie** [comment]
Hello, Marc. Good suggestion!

Added here https://github.com/virtualmin/virtualmin-gpl/commit/2f8912c36b9f7d0eaf68a5df88e7712eaaf50928 and here https://github.com/webmin/webmin/commit/fcd0c11ef9ed3d1387c031cfe0c356b4eb5a8b8e

@jcameron Jamie, also please check my commits above. For some reason I couldn't make `$help` be changed by reference using `&foreign_call($module, "help_pre_load", \$help)` and `$$htext` .. not sure why. So I just made it using regular assignment.

**Comment by jcameron** [comment]
Yeah, that code looks fine

**Comment by iliajie** [comment]
Thanks!
