### ISSUE TITLE
AWStats info is missing from mail templates

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#454]
I understand AWStats is now preferred to Webalizer.

![2022-09-28_011939](https://user-images.githubusercontent.com/1004261/192701584-1d32d217-5ebc-40d2-be95-cd5d827c6ab1.png)

**Comment by iliajie** [comment]
@jcameron Jamie, does Virtualmin has an ability to use the same `${IF-PLUGIN-NAME} ... ${ENDIF-PLUGIN-NAME}` for plugins, like `virtualmin-awstats` plugin?

**Comment by jcameron** [comment]
Yes, you can use `${IF-VIRTUALMIN-AWSTATS}`

**Comment by iliajie** [comment]
Jamie, how about that - https://github.com/virtualmin/virtualmin-gpl/commit/24fc132466d8962c2caf58310afe102c0aeafcee

**Comment by marclaporte** [comment]
@jcameron Can we close this?

**Comment by jcameron** [comment]
Yes, this is fixed now
