### ISSUE TITLE
A problem was detected with your Virtualmin license :

### ISSUE THREAD

**Issue by leveltgp** [virtualmin/virtualmin-gpl#456]
Hello, rcently set up a server with webmin / virtualmin free editions. From yesterday I receive this notice: arning!  A problem was detected with your Virtualmin license :
An error occurred checking the licence : Invalid host or serial number A renewal can be purchased at [Virtualmin Shop](https://virtualmin.com/shop/)
How can I remove this notice? Thank you.

**Comment by iliajie** [comment]
Hello,

Sorry about that.

There was a bug as we accidentally pushed a Pro package to GPL repos for the short period of time.

Please check this post for a fix:

https://forum.virtualmin.com/t/virtualmin-module-7-2-released/117020/2?u=ilia

The other solution would be is to actually purchase Virtualmin Pro license if you wish to keep Pro functionality and a message go away.

**Comment by leveltgp** [comment]
Thank you very much, error solved.
Ioannis Fellas

CEO / Owner

LEVELTGP.GR | WSU.GR

E shop | Applications - Software | Extreme Customer Support



215 215 1954 | 6938641069
***@***.***
https:// leveltgp.gr https://wsu.gr



[image: facebook] <https://www.facebook.com/leveltgp.gr>
[image: twitter] <https://twitter.com/j_fellas>
[image: linkedin] <https://www.linkedin.com/in/leveltgpgr/>
[image: instagram] <https://www.instagram.com/johnfellas/>


Στις Πέμ 29 Σεπ 2022 στις 8:57 π.μ., ο/η Ilia ***@***.***>
έγραψε:

**Comment by iliajie** [comment]
You're welcome.
