### ISSUE TITLE
New email uses wrong email address, `me.second@first.com` instead of `me@second.com`.

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#457]
Main virtual server is `first.com`.
Second virtual server is `second.com`

On Virtualmin page "Edit Users" for `second.com`, click the user `me`, and then click `Login to Usermin.`

In Usermin, click to write a new email.  You expect it to say From `me@second.com`, however it says From `me.second@first.com`.

**Comment by jcameron** [comment]
Which order are these email addresses in `/etc/postfix/virtual` ?

**Comment by chris001** [comment]
The order is all the `first.com` addresses are first, followed by all the `second.com` addresses.  Seems to be one per line, each line having two items: the email address, and either its login name, or the email address it's an alias of.

**Comment by chris001** [comment]
I found [the solution to this issue](https://www.virtualmin.com/documentation/email/troubleshooting/), Usermin New mail uses the correct From email address now.

> Usermin Webmail Sends With Incorrect From: Address
>
> In most cases, if Usermin webmail does not include the correct From: address, it is incorrectly configured. The default was not being set correctly in our automated installer until recently due to a bug.
>
> The old default would default to a From: address of the form `user-domain@hostingco.tld`, when it should instead be `user@domain.tld`.
>
> To correct this problem:
>
> Browse to Webmin / Usermin Configuration / Usermin Module Configuration / Read Mail page
>
> Locate the option labeled "From: address mapping file", and set it to `/etc/postfix/virtual`
>
> Locate the option labeled "Address mapping file format", and set it to `Address to username (virtusertable)`
>
> Save it.
