### ISSUE TITLE
REQ sender dependent transport maps (unique IP for each virtual server SMTP outgoing email client)

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#459]
Sometimes in hosting you receive a "dirty" IPv4 address which has previously been used by email spammers and marked as a source of spam, resulting in, many email providers drop incoming email from your "blacklisted" IPv4 address. To remove from blacklist, you have to pay `$$` to the blacklist maintainer, most IP block owners refuse and call it extortion.  Or you can wait `X months` with no spam reports for your IP address, that's impractical.

`Postfix` has `sender dependent transport maps`, which enables it to, for each domain (virtual server), set the outgoing SMTP email client to use a dedicated IP address, in most cases the IPv6 already assigned to each domain is perfect to use.  So that the receiving SMTP mail server will accept the incoming email, since it's not coming from your `blacklisted` IPv4 address.

Would this possible to add to Virtualmin easily?  Any suggestions or ideas?

**Comment by jcameron** [comment]
Do you want each domain that has it's own private IP address to use that IP for sending email? Or do you want the whole system to switch over to a single IP?

Using IPv6 is probably not practical, as not all recipient domains will support it.

**Comment by chris001** [comment]
Yes, each domain that has its own private IP use that IP for sending mail, "sender (domain) dependent transport (IP address) maps".  IPv6 are free so every domain can have one dedicated.  IPv4 cost, sometimes domains have a dedicated IPv4, it's rare, usually domains do not have an IPv4 dedicated, that IPv4 is usually shared with all domains on the server,
1. Postfix client should try to send with the domain dedicated IPv6 if available.
2. When sending over IPv6 fails (destination SMTP server is one of the minority of SMTP servers that fail to support incoming email on IPv6 yet, but should soon) then Postfix client should fall back to a domain dedicated IPv4, if any.
3. Then fall back to the server's shared public IPv4.
4. If public IPv4 is blacklisted, then email sending will fail and return to sender inbox with error, but at least we tried to send it to destination SMTP server the best way possible, with a clean IPv6 first before falling back to trying to send from the blacklisted IPv4.

**Comment by jcameron** [comment]
You can turn this on for new domains that have a private IP at System Settings -> Virtualmin Configuration -> Defaults for new domains -> Send email from domain's IP by default?

Or you can enable it for an existing domain by running `virtualmin modify-mail --domain example.com --outgoing-ip`

However, right now this only works for IPv4 .. and Postfix has to be configured to enable the `sender_dependent_default_transport_maps` feature.

**Comment by chris001** [comment]
Thanks!  [Here are steps in docs](https://www.virtualmin.com/documentation/email/dependent/) in case anyone else has this issue.

Also, [here it says IPv6 sender per domain was working in 4.04 (2013)](https://archive.virtualmin.com/node/30656). Since 4.04, did it break?

**Comment by jcameron** [comment]
Actually, it should also work for IPv6 if the domain has it's own v6 address.

**Comment by chris001** [comment]
Nice!  [Here is how to tell Virtualmin your server's IPv6 range, so Virtualmin will allocate a dedicated IPv6 address to a new domain](https://www.virtualmin.com/documentation/system/ipv6/).

> If your ISP has provided a range of IPv6 addresses for your system to use, they should be entered at **System Settings -> Server Templates -> Default Settings -> Virtual IP address**, in the **Ranges for automatic IPv6 allocation** field. Virtualmin will then pick a free address from this range when creating a new domain.
