### ISSUE TITLE
Does let's encrypt certificat at Vhost creation autorenew ?

### ISSUE THREAD

**Issue by Vagrantin** [virtualmin/virtualmin-gpl#46]
Hello,

I have setup my server template so at vhost creation it always create a certificate for the corresponding host also set the rewrite rules to point to the https page.  
What I don't know and didn't manage to find out is does the auto renew parameter is set if yes what's the default timing for the auto-renewal?  
Finally is there a way to find out either in the interface or in a config file if this parameter is set for a specific host ?  

Thanks for the clarification

Matth

**Comment by jcameron** [comment]
Auto-renewal will happen every 3 months or when the cert is within a week or expiry. You can see the last renewal date in the Virtualmin UI, on the Manage SSL Certificate page.

**Comment by Vagrantin** [comment]
OK perfect all clear now.
Thank you 

Matth
