### ISSUE TITLE
Suggested DNS Records is empty

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#463]
In the process of switching DNS from an external provider to our own servers I wanted to control what virtualmin would set as records. But when navigating to "Server Configuration > Suggested DNS Records" I'm presented with an empty line instead of actual DNS records.

![Screenshot 2022-10-04 at 17 02 55](https://user-images.githubusercontent.com/45786226/193856089-f53481b7-a3be-468d-b184-068b021ea27b.png)

DNS works normally for virtual server which have DNS enabled. But no server with DNS disabled seems to be able to present possible records.

I checked on a different server with a more recent OS but got the same results:
Operating system: Ubuntu Linux 18.04.6 or Ubuntu Linux 20.04.5
Webmin version: 2.001
Usermin version: 1.860
Virtualmin version: 7.2-1 
Authentic theme version: 20.01.1:5

**Comment by jcameron** [comment]
This is a bug that we'll fix in the next Virtualmin release. The fix is : https://github.com/virtualmin/virtualmin-gpl/commit/3798281f268f81954f1e19abd396a84d03d1800e
