### ISSUE TITLE
Missing favorite capability (the star) on Services -> PHP-FPM -> Error Logging

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#465]
![2022-10-08_202545](https://user-images.githubusercontent.com/1004261/194732141-aa625835-1f30-4ace-bbef-3afcdac35a56.png)

**Comment by jcameron** [comment]
@iliajie I assume this starring of pages is implemented via the theme?

**Comment by iliajie** [comment]
Yeah, I will fix this on the next theme release.

Thanks for reporting.
