### ISSUE TITLE
SPF contains IPv6 when IPv6 is disabled for the server

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#469]
Jamie, hello!

As you can see, in these suggested records here:

![image](https://user-images.githubusercontent.com/4426533/196755043-c3ce56c0-c164-4d66-90a3-c559f286d9d9.png)

.. there is no any `AAAA` records listed (correctly) because IPv6 is disabled for this virtual server on `Server Configuration ⇾ Change IP Address` page (set to _None_).

However, SPF record (as on the screenshot, stressed with the red border) contains IPv6. This seems as a bug and may cause issues for mail users.

**Comment by jcameron** [comment]
We add the IPv6 address any time there is a v6 address associated with the domain. This won't cause any problems, because the SPF record just contains the list of addresses that are allowed to send email for the domain - so there is no risk to adding a new address.

**Comment by iliajie** [comment]
True. Although, don't we want it to be precise? Or it adds a lot of complexity?

**Comment by jcameron** [comment]
Actually, we also add the system's default IPv6 address if there is one, because an outgoing SMTP connection may come from that address if the destination mail server supports IPv6.

**Comment by iliajie** [comment]
So, we will end up connecting via IPv6 when delivering mail, while having no IPv6 DNS records? It looks like a problem to me?

**Comment by jcameron** [comment]
No that's expected - the system itself might have a v6 address, even if there isn't one for the domain.

**Comment by iliajie** [comment]
And it won't raise such email's spam score?

**Comment by jcameron** [comment]
It might if the system's IPv6 address wasn't in the SPF record.

**Comment by iliajie** [comment]
Alrighty. I'll close it then. 😉
