### ISSUE TITLE
Feature Request: PHP-FPM logging set to 'per-domain'

### ISSUE THREAD

**Issue by pixel-paul** [virtualmin/virtualmin-gpl#474]
A useful feature for PHP-FPM would be to add it's logging to Virtualmin on a per-domain basis by default. For example:

`/etc/php-fpm.d/159645280026737.conf`
```
php_admin_value[error_reporting] = E_ALL
php_admin_value[error_log] = /home/mydomain.com/logs/php-fpm.log
```

This could then be accessed under 'Logs and Reports':

![image](https://user-images.githubusercontent.com/389303/199973227-d6131742-85d4-41c6-ae5e-f529ac0431a3.png)

**Comment by iliajie** [comment]
Hello,

That really sounds like a great feature request. Jamie, what do you think?

**Comment by jcameron** [comment]
Sure, that could be a good idea. What goes into that PHP log file though?

**Comment by pixel-paul** [comment]
With `E_ALL` set as the `error_reporting` level, PHP notices, deprecations, warnings and errors are generated. For example:

`[04-Nov-2022 12:19:09 UTC] PHP Notice:  Function wpdb::prepare was called <strong>incorrectly</strong>. Unsupported value type (array). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 4.8.2.) in /home/mydomain.com/public_html/wp-includes/functions.php on line 5833`

`
[04-Nov-2022 12:13:29 UTC] PHP Deprecated:  Required parameter $variable follows optional parameter $parameter_id in /home/mydomain.com/public_html/wp-content/plugins/myplugin-wp/includes/functions.php on line 230`

**Comment by jcameron** [comment]
I've checked in an update that will add a link to the PHP error log, if one is enabled in php.ini or the FPM config file.

I wonder, should we turn this on by default for new domains?

**Comment by iliajie** [comment]
I think having PHP logs easily accessible is must have feature.

**Comment by iliajie** [comment]
> I've checked in an update that will add a link to the PHP error log, if one is enabled in php.ini or the FPM config file.

Currently there is a bug, which always shows the **PHP Error Log** link on the menu, even if it's not configured on the configs. The link is pointed to the domain home dir.

> I wonder, should we turn PHP error logging on by default for new domains?

Yes, we should always configure custom PHP log, although maybe not, _only_ if it already configured to something else.

**Comment by jcameron** [comment]
Thanks, I'll fix that error with the log link. The rest of this feature is still in progress ...

**Comment by jcameron** [comment]
Support for enabling PHP logging by default will be included in the next Virtualmin release.
