### ISSUE TITLE
DEB : apache2-doc to remove

### ISSUE THREAD

**Issue by xxorax** [virtualmin/virtualmin-gpl#475]
Can someone remove **apache2-doc** dependancy  from `virtualmin-lamp-stack`and `virtualmin-lamp-stack-minimal` Debian packages ?

It introduce a /manual alias in `/etc/apache2/conf-enabled/apache2-doc.conf`:
```
Alias /manual /usr/share/doc/apache2-doc/manual/
```
This /manual path is available globaly, on all the websites :)

Thanks !

**Comment by iliajie** [comment]
Hello,

I wouldn't mind. It doesn't seem as essential package at all. @swelljoe Joe, why did you add it to `Depends:`?

**Comment by swelljoe** [comment]
No idea.

**Comment by iliajie** [comment]
We will remove it from depends on the next stack packages update.
