### ISSUE TITLE
Dashboard: operating system does not show point release on Redhat systems

### ISSUE THREAD

**Issue by pixel-paul** [virtualmin/virtualmin-gpl#477]
Minor UI issue:

![image](https://user-images.githubusercontent.com/389303/202015301-460a2cce-0d69-4a42-b503-9b1ce9019ced.png)

It always says `Redhat Enterprise Linux 8` - RH clones show the correct point release (in this case the installed version is actually 8.7)

**Comment by jcameron** [comment]
What does the real_os_version line in /etc/webmin/config contain on your system?

**Comment by jcameron** [comment]
Ok I see why this isn't being detected properly - I'll fix it in the next Webmin release.

**Comment by pixel-paul** [comment]
Thanks @jcameron !
