### ISSUE TITLE
Feature Request: make the php-fpm PM setting adjustable -- dynamic/ondemand/static

### ISSUE THREAD

**Issue by verne-work** [virtualmin/virtualmin-gpl#478]
the comments in www.conf in /etc/php-fpm.d/ say ... the Process Manager (pm) can run in one of three 'modes'

```
static
dynamic
ondemand
```

my request -- make this setting adjustable, ideally on the virtual server level.  Today its hardcoded to dynamic (middle line, trying to give some context) --

```
                   "listen = ".$port,
                   "pm = dynamic",
                   "pm.max_children = $defchildren",
```

Presently if I want to adjust it, I either manually edit the /etc/php-fpm.d/xxxxxx.conf file for a specific virtual server after its been made, or if I am really brave, edit the create_php_fpm_pool subroutine in php-lib.pl to affect all newly created virtual servers.

Verne

**Comment by iliajie** [comment]
Hello,

The funny thing that I was just thinking about adding it today and got carried away with other things.

Jamie, are you alright with that?

**Comment by jcameron** [comment]
Sure, I wouldn't object to that.

**Comment by abclution** [comment]
@iliajie Did some research last year, doing this with custom FPM pool options perhaps the help text could use these

; Required for PHP-FPM socket security, created bug report about it
listen.owner = $USER
listen.group = $GROUP

; ####### ONDEMAND
pm = ondemand

pm.process_idle_timeout = 1s
; Note: Used only when pm is set to 'ondemand'
; The number of seconds after which an idle process will be killed.
; Default Value: 10s


; ####### STATIC
; pm = static


; ####### DYNAMIC
; pm = dynamic

; pm.start_servers = 2
; Note: Used only when pm is set to 'dynamic'
; The number of child processes created on startup.
; Default Value: min_spare_servers + (max_spare_servers - min_spare_servers) / 2

; pm.min_spare_servers = 1
; Note: Used (Mandatory!) only when pm is set to 'dynamic'
; The desired minimum number of idle server processes.

; pm.max_spare_servers = 3
; Note: Used (Mandatory!) only when pm is set to 'dynamic'
; The desired maximum number of idle server processes.

; ####### COMMON

pm.max_children = 200
; Note: Used when pm is set to 'static', 'dynamic' or 'ondemand'
; static: The number of child processes to be created, period.
; dynamic / ondemand: The maximum number of child processes when pm is set to 'dynamic' or 'ondemand'.
; This value sets the limit on the number of simultaneous requests that will be served.
; Equivalent to the ApacheMaxClients directive with mpm_prefork.
; Equivalent to the PHP_FCGI_CHILDREN environment variable in the original PHP CGI. .
; Note: This value is mandatory.

pm.max_requests = 500
; The number of requests each child process should execute before respawning.
; This can be useful to work around memory leaks in 3rd party libraries. For
; endless request processing specify '0'. Equivalent to PHP_FCGI_MAX_REQUESTS.
; Default Value: 0

pm.status_path = /status
; The URI to view the FPM status page. If this value is not set, no URI will be recognized as a status page.

; ####### COMMON MEMORY and EXECUTION TIMEOUT

php_admin_value[memory_limit] = 128M
; PHP default is 128, bit high but ok
; php_admin_value[memory_limit] = 32M
; php_value[memory_limit] = 32M

php_value[max_execution_time] = 180
; php_admin_value[max_execution_time] = 60


; ####### COMMON POST and UPLOAD SIZE

php_value[post_max_size] = 1000M
;php_admin_value[post_max_size] = 1000M

php_value[upload_max_filesize] = 1000M
;php_admin_value[upload_max_filesize] = 1000M


; ####### COMMON LOGGING and STATS

php_flag[log_errors] = On
; php_admin_flag[log_errors] = on

php_flag[display_errors] = Off
;php_admin_flag[display_errors] = off

; php_admin_value[error_log] = /var/log/fpm-php.www.log


; catch_workers_output = Yes
; catch_workers_output bool
; Redirect worker stdout and stderr into main error log. If not set, stdout and stderr will be redirected to /dev/null according to FastCGI specs. Default value: no.

; slowlog string
; The log file for slow requests. Default value: #INSTALL_PREFIX#/log/php-fpm.log.slow.

; request_terminate_timeout mixed
; The timeout for serving a single request after which the worker process will be killed.
; This option should be used when the 'max_execution_time' ini option does not stop script execution for some reason.
; A value of '0' means 'Off'. Available units: s(econds)(default), m(inutes), h(ours), or d(ays). Default value: 0.

; request_slowlog_timeout mixed
; The timeout for serving a single request after which a PHP backtrace will be dumped to the 'slowlog' file.
; A value of '0' means 'Off'. Available units: s(econds)(default), m(inutes), h(ours), or d(ays). Default value: 0.

; ####### COMMON FILE DESCRIPTORS

; rlimit_files int
; Set open file descriptor rlimit for child processes in this pool. Default value: system defined value.

; rlimit_core int
; Set max core size rlimit for child processes in this pool. Possible Values: 'unlimited' or an integer greater or equal to 0. Default value: system defined value.

**Comment by iliajie** [comment]
Thanks but we are in _freeze_ now, i.e. not adding new features until we finally release Virtualmin 7.5.

**Comment by pixel-paul** [comment]
I have several websites that have PHP-FPM set to `pm = static`, but currently it is not possible to make any changes to the PHP-FPM options in Virtualmin without directly modifying the file.

For example:

```
[1600339919293188]
user = example
group = example
listen = localhost:8000
pm = static
pm.max_children = 150
pm.max_requests = 1000
pm.process_idle_timeout = 10s;
php_admin_value[upload_tmp_dir] = /home/example/tmp
php_admin_value[session.save_path] = /home/example/tmp
php_admin_value[post_max_size] = 265M
php_admin_value[upload_max_filesize] = 50M
php_admin_value[max_execution_time] = 300
php_admin_value[memory_limit] = 256M
php_value[max_execution_time] = 300
```

![image](https://user-images.githubusercontent.com/389303/233941739-abc21b30-7253-4502-8c9c-97f8fb0791e1.png)

If the above is saved, the following error is generated:

`Failed to save PHP options : Number of PHP sub-processes must be between 1 and 80`

**Comment by jcameron** [comment]
You can increase the maximum number of allowed PHP child-processes by editing `/etc/webmin/virtual-server/config` and adding the line `max_php_fcgi_children=200`

**Comment by iliajie** [comment]
> Failed to save PHP options : Number of PHP sub-processes must be between 1 and 80

Yes, this error is expected when the number of processes is incorrectly larger than available RAM on the system.



> I have several websites that have PHP-FPM set to `pm = static`, but currently it is not possible to make any changes to the PHP-FPM options in Virtualmin without directly modifying the file.

I will look into adding in one of the next Virtualmin releases.

**Comment by pixel-paul** [comment]
> Yes, this error is expected when the number of processes is incorrectly larger than available RAM on the system.

Can you point me to the calculation for this please?

**Comment by nekohayo** [comment]
Am I dreaming, or the "ondemand" switch has now appeared in the GUI options with VirtualMin 7.9? 🤩

If so, is it just as easy as turning on that radiobutton switch for each website's "PHP Options" and setting the "PHP service maximum sub-processes" setting to the limit we want (presuming the GUI would translate that to ondemand's `max_children` setting behind the scenes), or there is more to it?

**Comment by verne-work** [comment]
maybe its too late as 7.10 might be frozen ... can the PM mode be backed and and restored?  Presently I think anything restored from a backup is set to dynamic, regardless of what it originally was.

This may have been mentioned elsewhere but offhand I cannot find it.

**Comment by iliajie** [comment]
Thanks, nice suggestion. Fixed here https://github.com/virtualmin/virtualmin-gpl/commit/6ec92d61cb6c112cfa3f90f1f1065b22d35f609b.
