### ISSUE TITLE
Add a few directives to NGINX by default

### ISSUE THREAD

**Issue by SagnikSRHUSE** [virtualmin/virtualmin-gpl#484]
Could we add these directives to the NGINX config by default? The first one allows for large POST requests to go through, and increases the timeout. The second is necessary for applications that use friendly URLs etc. (like WP).

```       
        client_max_body_size 100m;
        client_body_timeout 600s;
```

```
        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }
````

**Comment by jcameron** [comment]
You can define additional Nginx directives for new domains at System Settings -> Features and Plugins, by clicking the Configure link next to the Nginx plugin.

**Comment by SagnikSRHUSE** [comment]
Perfect, tyvm!
