### ISSUE TITLE
mass create do not check existing user correctly  in mass_ucreate.cgi  lead to conflict

### ISSUE THREAD

**Issue by aqueos** [virtualmin/virtualmin-gpl#486]
hi,

### Bug: 

 virtual-server mass_ucreate.cgi

When a user 'xxx'  allready exist the script create a new user 'xxx.domain' instead to avoid collision.
BUT it gives it the SAME home directory as the existing user. Therefor 2 users have the same home and will conflict with each other

### how to reproduce:

choose the option, add part domain if user allready exist
use mass_ucreate.cgi to create several users including an existing one with no domain part

here done with 'testme3'
```
testme3:x:3147:1206::/home/testme/homes/testme3:/dev/null
testme3.testme:x:3149:1206:realname:/home/testme/homes/testme3:/dev/null

```

here we can see the users are differenciated in login and uid but their home is the same. This will lead to issues. 
For exemple the new user cannot access his home and if you delete  testme3.testme it will destroy the home of the previous user 'testme3'

I think it should fails in this case or test for the home directory and if it allready exist fail ?

best regards,
Ghislain.

**Comment by iliajie** [comment]
Hello,

I recall we have been fixing familiar issue recently. What Virtualmin versions are you running there?

**Comment by aqueos** [comment]
oh sorry i forgot the versions !
debian 10  amd64
virtualmin-core                    7.0.0
virtualmin-config                  7.0.2
webmin                             2.010

thanks for the quick review and sorry for the missing informations... :(
