### ISSUE TITLE
Incorrect redirect http to https code for Nginx with Virtualmin 7.3, carried to 7.5

### ISSUE THREAD

**Issue by johnheenan** [virtualmin/virtualmin-gpl#487]
In Virtualmin 7.3 with Nginx this is what a setting to use redirect http to https results in, in file nginx.conf:
```
if ($scheme = http) {
     rewrite "^\Q^/(?!.well-known)(.*)$\E(.*)" "https://%{HTTP_HOST}/$1$1" break;
}
```
So nginx.conf is polluted with leaked Perl code.

Aside from this, various minor edits to improve code from the Virtualmin forum, all adding \ before { or }, are:

Edit line 20 in /usr/libexec/webmin/virtual-server/list_redirects.cgi to
```
 $dest =~ /^(http|https):\/\/%\{HTTP_HOST\}(\/.*)$/) {
```
Edit line 39 of /usr/libexec/webmin/virtual-server/edit_redirects.cgi.
```
 $r->{'dest'} =~ /^(http|https):\/\/%\{HTTP_HOST\}(\/.*)$/) {
```

**Comment by jcameron** [comment]
This will be fixed in Virtualmin 7.4 - the patch can be seen at https://github.com/virtualmin/virtualmin-gpl/commit/e568e9532fc846a7435cd108db7b10d06eaee44e

**Comment by johnheenan** [comment]
The patch above fixes the second and third issues above, not the first issue. The first issue is specific only to nginx.

**Comment by iliajie** [comment]
This patch https://github.com/virtualmin/virtualmin-nginx/commit/fef02322f12993ff072950b697dee44abd158131 should also solve Nginx issue.

**Comment by johnheenan** [comment]
Thanks

**Comment by johnheenan** [comment]
The patch mentioned above for virtual_feature.pl in https://github.com/virtualmin/virtualmin-nginx/commit/fef02322f12993ff072950b697dee44abd158131 did not make it into the virtualmin 7.5 upgrade released and applied yesterday.

No virtual_feature.pl updates since Sep 25.
```
find  -name virtual_feature.pl -exec ls -l {} \;
-rw-r--r--. 1 root root 91453 Sep 25 18:59 ./usr/libexec/webmin/virtualmin-nginx/virtual_feature.pl
-rw-r--r--. 1 root root 17404 Apr 26  2022 ./usr/libexec/webmin/virtualmin-nginx-ssl/virtual_feature.pl
-rwxr-xr-x. 1 root root 7552 Apr 26  2022 ./usr/libexec/webmin/virtualmin-htpasswd/virtual_feature.pl
-rwxr-xr-x. 1 root root 23090 Apr 26  2022 ./usr/libexec/webmin/virtualmin-awstats/virtual_feature.pl
```
What can I do to remove and reinstall entire package without damage?

**Comment by johnheenan** [comment]
Was this fix in the never applied virtualmin 7.4 upgrade but not carried to version 7.5?

If so ow many other fixes did not get carried?

**Comment by jcameron** [comment]
This fix is in the Nginx plugin, so it will be picked up in it's next release..

**Comment by johnheenan** [comment]
I confirm this has been fixed in the Nginx plugin just released. Thanks.

However. 'Mail Client Configuration' setup for Nginx is not fixed. Will open a separate issue for this.
