### ISSUE TITLE
User-friendly return to previous page.

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#49]
Hi,

It's just expected in some cases to be bounced back to previous page.

For example when running Checking Configuration and it fails, it lets you set  127.0.0.1 to the list of DNS servers:

![screenshot from 2018-02-07 13-34-33](https://user-images.githubusercontent.com/4426533/35912166-d648744c-0c0c-11e8-86b4-34a7abd39f13.png)

After you set it and hit Save it shouldn't take you to Network Configuration page.
![screenshot from 2018-02-07 13-40-53](https://user-images.githubusercontent.com/4426533/35912268-21115ea8-0c0d-11e8-94b9-411a14896b75.png)
![screenshot from 2018-02-07 13-40-59](https://user-images.githubusercontent.com/4426533/35912267-20ee65ec-0c0d-11e8-8bb3-2f1fc033e550.png)

_Checking Configuration_ page should add to links the query, like `bounce=/virtual-server/check.cgi`, which redirect function should seek for and redirect user back to it.

Could you do it, it's very easy to implement, I think?

**Comment by shoulders** [comment]
@iliajie I think most of the pages in Virtualmin have these buttons to take you back now, is this what you meant with this issue.

p.s. if it is, this should be closed 😄

**Comment by iliajie** [comment]
Yes, I will close it. Thanks!
