### ISSUE TITLE
https://archive.virtualmin.com/ is down for at least the last 2 days... 

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#492]
![image](https://user-images.githubusercontent.com/10130237/208843721-b93b87f0-2e52-4f5b-b5a7-e412799a715d.png)

**Comment by iliajie** [comment]
Thanks, should be fixed now.

**Comment by swelljoe** [comment]
Thanks for the heads up, but also, what did you need on archive.virtualmin.com? Nearly everything of value should be on the new sites (except a few old support tickets).

**Comment by abclution** [comment]
> Thanks for the heads up, but also, what did you need on archive.virtualmin.com? Nearly everything of value should be on the new sites (except a few old support tickets).

Dunno, google results brought me there for some queries. ;) Maybe I should ask chatgptbot instead
