### ISSUE TITLE
Administration Options ⇾ Edit Resource Limits: Resource Limits

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#499]
Setting the option called _Maximum number of processes_ to some value will add `RLimitNPROC` to Apache config. However, disabling it back to _Unlimited_, still leaves `RLimitNPROC` set to the previously used value in limit.

Tested on Ubuntu 22.04 with latest patches.

**Comment by jcameron** [comment]
Checking in a fix for this now ...

**Comment by iliajie** [comment]
Excellent! Thanks, this also works!
