### ISSUE TITLE
Restore Virtual Server missing "select all" button 

### ISSUE THREAD

**Issue by hayden-t** [virtualmin/virtualmin-gpl#504]
so when creating the backup there is this button, but not when restoring

![image](https://user-images.githubusercontent.com/1000743/211707918-691dcb87-ab15-4065-903e-a0661b35fa19.png)

![image](https://user-images.githubusercontent.com/1000743/211707951-5e2890e2-2529-497d-bf43-624274a15eac.png)

**Comment by jcameron** [comment]
Thanks for pointing this out - we'll fix it in the next release.

**Comment by hayden-t** [comment]
great work guys, love the system
