### ISSUE TITLE
Edit DNS records, ignores validate option

### ISSUE THREAD

**Issue by hayden-t** [virtualmin/virtualmin-gpl#505]
Hi, trying to set a website to a ip records off server, works in webmin bind interface, but when editing in virtualmin it wont save, even when "validate new records" is unticked 

![image](https://user-images.githubusercontent.com/1000743/211709510-5e95b207-f1ce-42b4-86c3-1b0271e26b54.png)

**Comment by jcameron** [comment]
Thanks - we'll fix this in the 7.6 release.
