### ISSUE TITLE
Changing PHP version open the phpinfo

### ISSUE THREAD

**Issue by hayden-t** [virtualmin/virtualmin-gpl#506]
for some reason when i change the drop down it open phpinfo in a new tab, when i believe this should only open when you click the php logo

![image](https://user-images.githubusercontent.com/1000743/211715687-fdfc341f-d2ea-4e20-a653-a89881b70e0f.png)

**Comment by jcameron** [comment]
@iliajie I think this is link you added recently?

**Comment by iliajie** [comment]
> for some reason when i change the drop down it open phpinfo in a new tab, when i believe this should only open when you click the php logo

Thanks for reporting it. We will fix it on the next Webmin release.

> @iliajie I think this is link you added recently?

Yeah, but this bug happened to be FIrefox related only. I have no idea why Firefox does it (propagates click event made on  the options list to the parent). Neither Chrome of Safari don't do it. This is unexpected. Anyway, it's fixed now.
