### ISSUE TITLE
Opinions about entries in nginx.conf for 'Mail Client Configuration'

### ISSUE THREAD

**Issue by johnheenan** [virtualmin/virtualmin-gpl#507]
The recent release of webmin package for Nginx fixed the redirection from http to https problem mentioned in https://github.com/virtualmin/virtualmin-gpl/issues/487.

Toggling on or off 'Virtualmin', 'Email Settings', 'Mail Client Configuration' adds or removes the settings below in a relevant virtual server section in nginx.conf.

Two issues:

1. \Q and \E are redundant PCRE delimiters as there is nothing to escape.
2. The fourth and fifth lines are identical to the third line.

```
rewrite ^\Q/mail/config-v1.1.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
rewrite ^\Q/.well-known/autoconfig/mail/config-v1.1.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
rewrite ^\Q/AutoDiscover/AutoDiscover.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
rewrite ^\Q/Autodiscover/Autodiscover.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
rewrite ^\Q/Autodiscover/autodiscover.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
```

**Comment by jcameron** [comment]
Not quite - the lines differ in case, which is needed because some mail clients use slightly different paths!

**Comment by johnheenan** [comment]
> Not quite - the lines differ in case, which is needed because some mail clients use slightly different paths!

Accepted. 

But why are \Q and \E included when they do not need to be? They look bizarre in nginx.conf. Doesn't this mean Nginx need to include PCRE level module support instead of just POSIX level module support for regular expressions?

\Q and \E are not in equivalent Apache directives with Virtualmin.

**Comment by jcameron** [comment]
\Q and \E indicate that everything between them should not be treated as a regexp - which means that the . character is just treated as it is. We could have instead added a line like : 

```
rewrite ^/Autodiscover/autodiscover\.xml(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
```

But using \Q and \E is a bit simpler..

**Comment by johnheenan** [comment]
I suppose you can argue from a software maintenance perspective that enveloping with \Q \E is more generic and so simpler than seeking and escaping dots inline.

I am closing this. Thanks for responding.

**Comment by johnheenan** [comment]
I have changed the title of the post and reopened it to seek an opinion

I agree enveloping with\Q \E as literal is simpler than escaping multiple dots for the first two lines below:
```
rewrite ^\Q/mail/config-v1.1.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
rewrite ^\Q/.well-known/autoconfig/mail/config-v1.1.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
```
Also, I suppose there is less processing when literals are used.

But in terms of readability and maintainability, would the following line work
```
rewrite ^/Auto[Dd]iscover/auto[Dd]iscover\.xml(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
```
to replace these three lines?
```
rewrite ^\Q/AutoDiscover/AutoDiscover.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
rewrite ^\Q/Autodiscover/Autodiscover.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
rewrite ^\Q/Autodiscover/autodiscover.xml\E(.*) $scheme://$host/cgi-bin/autoconfig.cgi$1 break;
```
I am not asking for the change, just seeking opinions.

**Comment by jcameron** [comment]
Yes, that would also work!
