### ISSUE TITLE
getting locked out of usermin, having to restart webmin, instead of working with fail2ban

### ISSUE THREAD

**Issue by gstlouisgit** [virtualmin/virtualmin-gpl#509]
In case this is worth a change

SYSTEM INFORMATION	
OS type and version	debian 10 (buster)
Webmin version	2.00
Usermin version	1.860
I came across this late post about getting locked out of usermin.

[webmin locked out](https://forum.virtualmin.com/t/webmin-user-blocked/53279)
I encouraged some users to use usermin, and of course they locked themselves out. But before I saw the late post I assumed this was blocked with fail2ban using webmin-auth maybe. This wasn’t the case, and I can see that this was an internal function.

Wouldn’t it make more sense to do this with fail2ban? I mean restarting webmin seems cumbersome, specially if several users would be using usermin no?

**Comment by iliajie** [comment]
Hello,

Webmin and Usermin have inbuilt feature for blocking failed logins, which can be controlled on `Webmin ⇾ Webmin Configuration: Authentication` and `Webmin ⇾ Usermin Configuration: Authentication` pages respectively.

**Comment by gstlouisgit** [comment]
Thank you for sharing @iliajie 
It looks like usermin config -> authentication has really good features.  I can see that usermin auth you can log failures to syslog as well, which should work with fail2ban.  I can also see there should only be a 60 second time out for 5+ failed attempts.  I'll play with those options.
