### ISSUE TITLE
SSL certification with certbot breaking when virtualmin executes renew certificates

### ISSUE THREAD

**Issue by gstlouisgit** [virtualmin/virtualmin-gpl#510]
I hope I'm explaining this correctly, as this is what I saw from the experience I just received.

System hostname | web.smbservices.ca (148.59.149.79) | Operating system | Debian Linux 10
-- | -- | -- | --
Webmin version | 2.011 | Usermin version | 1.860
Virtualmin version | 7.5-1 | Authentic theme version | 20.11.1:4
Time on system | Tuesday, January 24, 2023 12:01 PM | Kernel and CPU | Linux 4.19.0-23-amd64 on x86_64

System hostname	[web.smbservices.ca (148.59.149.79)](https://smbservices.ca:12000/net/list_dns.cgi)	Operating system	Debian Linux 10
Webmin version	2.011 	Usermin version	1.860
Virtualmin version	7.5-1  	Authentic theme version	20.11.1:4 
Time on system	[Tuesday, January 24, 2023 12:01 PM](https://smbservices.ca:12000/time/)	Kernel and CPU	Linux 4.19.0-23-amd64 on x86_64

I get this notification that with previous version I was not getting 
Warning!
SSL Certificate Warning
The following virtual servers' SSL certificates have expired : domains *

I am used to doing the certbot renew from the command line, again virtualmin was installed a long time ago and I would do this in the CLI

So basically some of my virtual servers didn't have SSL enable checkmark, and some did, all go through one certbot certification file.

I recently renewed on the command line using 
```
certbot renew
```
Everything went fine, but then a few days later, I believe when virtualmin thought it was the time to renew, it seems to have executed the renew command and I lost certification for a lot of domains.  Several folks where not happy.  I had to re-exec certbot with the expansion command and recall all the domains that needed it.  so that sucked.

I think, and I am hoping, that this problem will not occur in the next 89 days because I did this to HOPEFULLY fix the issue.

- backed up all my apache .conf files in `/etc/apache2/sites-enabled/` 
- In Virtualmin, I went to all my virtual servers and removed the SSL enable checkmark, and saved
- this removed the SSL <VirtualHost *:443> and messed up the config, I overwrite with my backups and reload apache

Now Virtualmin should believe no virtual server have SSL and hopefully will not ask or execute anything.

I'm too scared to reproduce this error.  Sorry!  But maybe worth an option to deactivate SSL in virtualmin?  I couldn't fine anyting after searching...  I only found [this link](https://forum.virtualmin.com/t/disable-remove-letsencrypt-from-virtualmin/107786) that lead me to my possible solution

**Comment by iliajie** [comment]
Hello,

> I am used to doing the certbot renew from the command line, again virtualmin was installed a long time ago and I would do this in the CLI

Virtualmin has a CLI for renewing Let's Encrypt certificates too. Besides, by default there is no need in doing it, as Virtualmin will do it automatically.

Also, there is no need to disable SSL website feature as you can tell Virtualmin not to automatically renew certificate in `Server Configuration ⇾ SSL Certificate` page. Moreover, I would recommend not to meddle with Virtualmin scheduled tasks and disable and mask `certbot.timer` service instead.

Webmin 2.013 is out to address various issues, please upgrade.

**Comment by gstlouisgit** [comment]
@iliajie 

> Virtualmin has a CLI for renewing Let's Encrypt certificates too. Besides, by default there is no need in doing it, as Virtualmin will do it automatically.

The problem I saw, or feared about this, is when virtualmin would give me the warning for SSL renewal coming up, it would show me the proper domains or all the domains that do need to be renewed.  So I couldn't trust virtualmin doing the certbot renew.  

Thank you for providing the section Server Configuration ⇾ SSL Certificate.  I've told it not to renew automatically.  Hopefully it will have issues on the next renew.

**Comment by jcameron** [comment]
Do you mean that Virtualmin is showing the warning even before it attempts to do it's own automated renewal? If so, we should fix that ...

**Comment by gstlouisgit** [comment]
sorry for the late reply.
virtualmin is showing a warning before renewal.  I forget how it looked like, but it is similar to this one.

![Screen Shot 2023-01-30 at 12 29 59 PM](https://user-images.githubusercontent.com/20375753/215550686-123b455f-98c0-4269-94fc-9a02362d714d.png)

**Comment by gstlouisgit** [comment]
are you referring to the "Let's Encrypt" tab -> **Automatically renew certificate?**

Here are two snapshots of the server that gives me the SSL Certificate Warning screenshot I gave prior.

![Screen Shot 2023-01-30 at 12 40 58 PM](https://user-images.githubusercontent.com/20375753/215552918-fee4fd18-e59e-4470-815b-56075dda60e1.png)
![Screen Shot 2023-01-30 at 12 40 39 PM](https://user-images.githubusercontent.com/20375753/215552920-2101637d-b28b-4641-9ba0-6e869c0ccfad.png)

**Comment by iliajie** [comment]
The certificates are not getting renewed automatically because it's not enabled to be renewed automatically, right .. ?

Try enabling it and see if that works for you. Also, don't use `certbot` directly, if you use Virtualmin to renew SSL certificates, then you should _disable_ and _mask_ `certbot.timer` service.

**Comment by gstlouisgit** [comment]
I hate to re-open this.  But this morning my certificates got renewed automatically again.  When looking at this conversation, I can see that I had turned off the auto renew, as I thought.  But I looked at virtualmin and I can now see again it is turned back on.  Does that make sense?   I've gone through several virtualmin and software updates since.  When I look at the letsencrypt logs I can see it ran this morning and `certbot certificates` is missing several of my domains

Anyway, since several domains were complaining of certs issues, I through since it is down, might as well be a good time to use the virtualmin's auto renew like @iliajie told me to do.  An error occurred when I did this...

<img width="1386" alt="Screen Shot 2023-06-29 at 7 42 33 AM" src="https://github.com/virtualmin/virtualmin-gpl/assets/20375753/a743c5be-468a-4188-87b0-e754bdd56381">

I do not use bind DNS server.  I assume this might be why, because I do not have DNS on the machine?  certbot command always works fine for me...  I had to redo my certbot like I do manually and everything is fine.  I've put myself a reminder within the 89 days to check if there were virtualmin updates, and if the auto renew went back to "yes".  Presently, I confirm it is set to "no"


<img width="512" alt="Screen Shot 2023-06-29 at 8 49 22 AM" src="https://github.com/virtualmin/virtualmin-gpl/assets/20375753/308b1027-49d5-4364-8a8f-db1838131850">

**Comment by jcameron** [comment]
Can you add the line `error_stack=1` to `/etc/webmin/config` , re-try requesting the cert, and let me know what it says?

**Comment by gstlouisgit** [comment]
@jcameron 
I've added error_stack=1 to end of file `vim /etc/webmin/config`
It seems to be the same error message

**Comment by jcameron** [comment]
What if you go to Limits and Validation -> Validate Virtual Servers and run a validation check on this domain?

**Comment by gstlouisgit** [comment]
Here are the results - I replaced my domain with **domain** I hope that's not confusing.
If its missing Directory it should be because its a proxy pass etc
I also do not use DNS on the server and run stuff through godaddy

====
 Validate Virtual Servers

Beginning validation of selected virtual servers. Any problems found will be shown in red ..

collaboration.domain.ca
DNS domain : No DNS zone found for domain collaboration.domain.ca
Apache website : Missing Apache <Directory> block for HTML directory /home/domain/domains/collaboration.domain.ca/public_html

forum.domain.ca
DNS domain : No DNS zone found for domain forum.domain.ca

collaborate.domain.ca
Apache website : Missing Apache <Directory> block for HTML directory /home/domain/domains/collaborate.domain.ca/public_html

docs.domain.ca
Apache website : Missing Apache <Directory> block for HTML directory /home/domain/domains/docs.domain.ca/public_html
Log file rotation : No webserver log found for virtual host docs.domain.ca

chat.domain.ca
DNS domain : No DNS zone found for domain chat.domain.ca

domain.ca
DNS domain : No DNS zone found for domain domain.ca
Apache website : Missing Apache <Directory> block for HTML directory /home/domain/public_html
Webalizer reporting : No webserver log found for virtual host domain.ca
Log file rotation : No webserver log found for virtual host domain.ca
DAV Login : Missing DAV alias from Apache configuration

cal.domain.ca
DNS domain : No DNS zone found for domain cal.domain.ca
Apache website : Missing Apache <Directory> block for HTML directory /home/domain/domains/cal.domain.ca/public_html/html
Webalizer reporting : No webserver log found for virtual host cal.domain.ca
Log file rotation : No webserver log found for virtual host cal.domain.ca

webmail.domain.ca
Apache website : Missing Apache <Directory> block for HTML directory /home/domain/domains/webmail.domain.ca/public_html
Log file rotation : No webserver log found for virtual host webmail.domain.ca

**Comment by chris001** [comment]
I've gotten this error when a domain's DNS records were returning the wrong IP addresses, or no IP addresses.
You must check all your domain's IP addresses in your godaddy's DNS A and AAAA and MX records, are returning the corresponding A and AAAA and MX IP addresses of your virtual servers (domains and subdomains) on your virtualmin.  If not, update the IP addresses on your godaddy DNS server so that they are.

**Comment by jcameron** [comment]
Those "No DNS zone found" errors seem odd. Was DNS initially enabled for these domains and then manually deleted?

**Comment by gstlouisgit** [comment]
Unfortunately, I cannot confirm that, sorry.
It is not installed on this system.  I've been so used to using godaddy's UI to configure my DNS I never ventured into BIND DNS.  I do recall once making time to work with it and failed, but I think this was on another cloud machine I have, but I do not recall, sorry.

Personally, I feel it might have something to do with it as well.  Luckily for the time being, I only have one parent domain running on this box so not too complicated, and my godaddy DNS records for this domain seems fine.  godaddy uses @ to point to the A record value static IP, most of my records hold @ to point to parent, except my CNAME's which I do not think are relevant at this point.  Sorry, I can't provide more insight.

for the time being, I have a reminder to check after virtualmin within the 89 days of renew to ensure the "Automatically renew certificate" stays "no"

**Comment by jcameron** [comment]
For those domain where you're using GoDaddy for DNS, you should consider turning off the DNS feature for them in Virtualmin (on the Edit Virtual Server page).

**Comment by gstlouisgit** [comment]
I'm going to close this off.  I do not recall having any issues since I've ensured that Automatically renew certificate" stays "no".
