### ISSUE TITLE
Mailbox: Inconsistent usage of the terms suffix and prefix

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#512]
It seems that (once upon a time) someone erroneously used the term `prefix`  to denominate the last part of mail accounts.

It seems to have only been fixed to `suffix` in the translations but internally it's still being referenced as `prefix`  e.g. https://github.com/virtualmin/virtualmin-gpl/blob/48d0aea47a5640eb2ffbc01c907eb51fde45b90a/edit_domain.cgi#L142

Unfortunately it is also called `Mailbox username prefix` in the output of the CLI in e.g. `virtualmin list-domains --domain example.com --multiline`

Fixing the output of the CLI might break someone's script if they rely ont the outpout being called `suffix` (which is the reasong I have to hold back my script until I might get an answer if it will be fixed …)

**Comment by jcameron** [comment]
Virtualmin has a few different formats for usernames with the domain appended or prepended, so sometimes it is the prefix and sometimes the suffix. We always use the word "prefix" in the CLI output though, and so aren't likely to change that because callers might depend on it ..

**Comment by PitWenkin** [comment]
Ok
