### ISSUE TITLE
check_ssl_cert_key_match and EC keys

### ISSUE THREAD

**Issue by ftrojahn** [virtualmin/virtualmin-gpl#516]
Hi there, 

using Webmin 2.013, Virtualmin 7.5-gpl on Debian 9 stretch (I know ...)

I couldn't activate ssl on a subdomain and got the errors:

```
Creating SSL certificate and private key ..
.. openssl failed! OpenSSL error creating private key :
req: Unknown digest addext
req: Use -help for summary.
```
and - using existent ssl.key and ssl.cert files -

```
Adding new SSL virtual website ..
.. certificate and key do not match : Certificate data is not valid : Modulus=Wrong Algorithm type

```

Digging a bit further in, these messages come from [sub check_ssl_cert_key_match](https://github.com/virtualmin/virtualmin-gpl/blob/286d9dfad92ce54056242ce12bade59a30d7cac5/feature-ssl.pl#L1271-L1303)

This seems derived from eg.

https://major.io/2007/09/14/check-the-modulus-of-an-ssl-certificate-and-key-with-openssl/

On an inactive domain (from 2012) these two checks do work on the ssl.key and ssl.cert files, as these had not been updated. But all newer (Letsencrypt) key/cert files show errors:

```
# openssl rsa -noout -modulus -in /home/xx/domains/yy/ssl.key 
140635695308864:error:0607907F:digital envelope routines:EVP_PKEY_get0_RSA:expecting an rsa key:../crypto/evp/p_lib.c:284:

# openssl x509 -noout -modulus -in /home/xx/domains/yy/ssl.cert 
Modulus=Wrong Algorithm type
```

I was able to add ssl to the subdomain using existing ssl.key/ssl.cert files after disabling the lines 167-171 in virtual-server/feature-ssl.pl.

So, I'm not asking for support for an old Debian os. But ... these openssl commands do not work at least for recent EC keys+certs.

Don't know if this sub routine is just a leftover for somewhat reason, or why it isn't used anywhere else. But I think, this could be fixed.

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up! You are right, it is a bug on Virtualmin side. Fixed in this patch https://github.com/virtualmin/virtualmin-gpl/commit/85dc1eacc685ae6114b2b68dc010f028b76ba9cb.
