### ISSUE TITLE
"New mailbox email" is send even if disabled

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#518]
Even if `Email message to send on mailbox creation` is set to `None` in `Server Template > New mailbox email` an email is placed in the newly created Inbox. Regardless if the account as created via the GUI or the CLI.

According to my knowledge and some forum entries this a new behaviour:
[Your mailbox has been set up successfully as follows… Can we disable this?](https://forum.virtualmin.com/t/your-mailbox-has-been-set-up-successfully-as-follows-can-we-disable-this/119123)
[New Mailbox Email, New Reseller Email, Updated Mailbox Email gone](https://forum.virtualmin.com/t/new-mailbox-email-new-reseller-email-updated-mailbox-email-gone/118722)

I think was introduced ba this commit: https://github.com/virtualmin/virtualmin-gpl/commit/f43dc5f6ae90ee78c97aa364a34e29164dffed73

**Comment by PitWenkin** [comment]
There is an `--no-creation-mail` (which I have not yet tested) option for the CLI `create-user` command, but no option in the GUI?

**Comment by jcameron** [comment]
The template-level option "Email message to send on mailbox creation" should be the correct way to disabling sending the new mailbox email.  Are you setting this in the "Default settings" template, or a custom template?

**Comment by PitWenkin** [comment]
In the "Default settings".
Are the templates only applied to new virtual servers, or are changes to the template also applied to every server that uses it? (I'm pretty sure None was selected before the current server was created)

**Comment by jcameron** [comment]
It will be used by all new and existing domains that are on that template.

When the email gets incorrectly sent, was the user created from the UI or the command-line API?

**Comment by PitWenkin** [comment]
I tried both. Both send the mail. I did not use the `--no-creation-mail`  (but as the template is set to none this should not have been necessary (and never was))

**Comment by jcameron** [comment]
Ok I see the bug that causes this - it will be fixed in the next Virtualmin release.
