### ISSUE TITLE
Mismatch of CLI vs Web version of PHP because CLI version is server-wide

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#520]
"Yes, this is possible" but "Note that this command will set default PHP version for the system and not for a specific user or a virtual server." Source: https://forum.virtualmin.com/t/changing-default-version-of-php-cli-for-virtual-host/117171

See also: 

- https://forum.virtualmin.com/t/changing-default-php-cli-version-on-the-server/60103
- https://forum.virtualmin.com/t/setting-cli-php-version-5-6/54449
- https://forum.virtualmin.com/t/change-the-default-php-version-for-command-line-interface/107682
- https://forum.virtualmin.com/t/multiple-php-versions-but-not-adhering-selected-version-in-cli/109177
- https://dev.tiki.org/item7820-Installing-package-is-hardly-possible-on-shared-hosting-without-an-option-to-select-the-PHP-CLI-to-use#threadId9986

Since this causes support requests, we added to [Tiki Check](https://doc.tiki.org/Server-Check)
![php-cli](https://user-images.githubusercontent.com/1004261/222068028-2232a674-a0d3-4fe8-89b9-fe2e1c0b0dad.png)

To address this in ClearOS, here is a wrapper we had made a while back:
https://github.com/WikiSuite/app-php-engines/blob/master/packaging/php_wrapper

Thanks!

**Comment by iliajie** [comment]
Hello, Marc.

Thanks for the heads-up!

> To address this in ClearOS, here is a wrapper we had made a while back

The easier solution would be to create an alias in user's home `.bashrc` file (in case user's shell is set to `bash`).

Jamie, perhaps this is something we could do on Virtualmin side automatically?

**Comment by jcameron** [comment]
I don't think a .bashrc alias will fix the PHP version that a script sees. 

Also, on a system with multiple PHP versions installed, `/usr/bin/php` absolutely can be a different version to the one run via FPM or fCGId.

**Comment by iliajie** [comment]
> I don't think a .bashrc alias will fix the PHP version that a script sees.

Yes, a script would have to call the needed PHP version explicitly.

**Comment by jcameron** [comment]
Virtualmin can generally figure out what the correct CLI PHP command is - I wonder if there's a way we can pass it to Tiki?

**Comment by iliajie** [comment]
Create a symlink to `~/bin/php`?

**Comment by marclaporte** [comment]
> I wonder if there's a way we can pass it to Tiki?

Well, it's not just Tiki :-) For example, someone using Composer, or any of the CLI tools of a web app.

Any thoughts on an approach like this? https://github.com/WikiSuite/app-php-engines/blob/master/packaging/php_wrapper

**Comment by iliajie** [comment]
Well, something should tell the app to use specific PHP version.

**Comment by kroky** [comment]
phpenv config wrapper is a nice idea but if virtualmin already knows what php version to use on a specific virtual domain (user home dir and all dirs below) we might try the solution with bin/php linking to the correct binary and put that in the PATH? Note that some cli commands are executed via cron or other non-interactive login shells which might get tricky setting up the PATH correctly. All that we have when we execute CLI commands is the virtual domain/directory where the script is executed and we need to make sure it uses the same version as the virtual domain php configuration suggests.

**Comment by jcameron** [comment]
Even putting a link from `php` in the `bin` directory won't help, because it's possible to have multiple PHP versions in use in different directories on the same virtual server.

**Comment by kroky** [comment]
Then, how can we check from a command line script which php version is set to use on a specific directory? A kind of a hidden .env file seems like a good solution here.

**Comment by jcameron** [comment]
I suppose we could create a link from `php` in each directory that has a custom version to the command for that version.

However, be aware that in some cases, there might not be a command-line version .... it's quite possible to install PHP FPM package and not the CLI.

**Comment by kroky** [comment]
That would be awesome, thanks! We will use a fallback solution if cli is not found.

**Comment by jcameron** [comment]
Another thing we could do is link from each domain's `~/bin` directory from php7.2 (for example) to the actual path to the php 7.2 CLI. Then scripts could look at the running PHP version and use this to select which CLI to run..

**Comment by jcameron** [comment]
Ok in the next release, there will be a link from each domain's `~/bin/php` to the PHP cli for the version enabled on the domain's top-level directory.

**Comment by jcameron** [comment]
A bash alias won't work when another script runs the `php` command though - it will only work when you SSH in..

**Comment by kroky** [comment]
Yes, scripts and non-interactive logins are not concerning, we can set them up with the correct path to the php exec. The problem is interactive user logins where user is not aware of the correct path or manages multiple locations with multiple versions. Aliases are quite nice there. Is there a way for us to make that system wide and default for new installs?

**Comment by jcameron** [comment]
Oh I see ... however, an alias like that which uses `../bin` in the path wouldn't work if you user is in a directory below `public_html` .

**Comment by kroky** [comment]
Right. That's just fine for our use-case but I suppose we don't want to add that alias in stock virtualmin if it works only in public_html. I couldn't find another solution besides recursively browsing parent directories for bin/php. If you think that is something you can add, I will send the code. Otherwise, we can just add the ../bin/php solution for our use-case.

**Comment by kroky** [comment]
This won't work for root user browsing different domains in addition to the subdomains problem.

@marclaporte , what do you think about adding a proper alias with parent directory traversal to find the right bin/php in our virtualmin-tikimanager plugin? https://gitlab.com/wikisuite/virtualmin-tikimanager

It could create the alias system-wide for all users during installation of that plugin.

**Comment by marclaporte** [comment]
@kroky Sure, please proceed.

Thanks!

**Comment by kroky** [comment]
https://gitlab.com/wikisuite/virtualmin-tikimanager/-/commit/dd799a0c77e52bad27dc2bf402327dc14d7ff1f5

@jcameron, besides using feature_enable, feature_validate and feature_setup, is there another way to make sure this code is always executed when our plugin is installed in webmin?

**Comment by iliajie** [comment]
> Oh I see ... however, an alias like that which uses `../bin` in the path wouldn't work if you user is in a directory below `public_html` .

I think I could think something up to make it work for sub-domains in the expected way.

**Comment by iliajie** [comment]
The solution for this problem is pretty simple!

Considering that Virtualmin already creates proper `/home/example/bin/php` and `/home/example/domains/sub-example/bin/php` links referring actual PHP version used by virtual server, we can simply put the following one-liner to `/home/example/.bashrc` to have it work correctly with sub-domains, e.g.:

```
alias php='$(phpdom="bin/php" ; phpdef="/bin/php" ; (while [ ! -f "$phpdom" ] && [ "$PWD" != "/" ]; do cd "$(dirname "$PWD")" || "$phpdef" ; done ; if [ -f "$phpdom" ] ; then echo "$PWD/$phpdom" ; else echo "$phpdef" ; fi))'
```

Now if a user is under `/home/example/public_html` and runs `php` it will refer to `/home/example/bin/php` link and if a user is in `/home/example/domains/sub-example/public_html` it will refer to `/home/example/domains/sub-example/bin/php`.

For example, in my case the parent domain has PHP 8.1 set and sub-domain has PHP 7.4 set, and here is the output I get:

```
ubuntu22-pro@ubuntu22-pro:~$ pwd && php -v
/home/ubuntu22-pro
PHP 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18) (NTS)
```

```
ubuntu22-pro@ubuntu22-pro:~/domains/sub1.ubuntu22-pro.virtualmin.dev$ pwd && php -v
/home/ubuntu22-pro/domains/sub1.ubuntu22-pro.virtualmin.dev
PHP 7.4.33 (cli) (built: Feb 14 2023 18:31:54) ( NTS )

```

**Comment by kroky** [comment]
Yes, I agree, @iliajie  - thanks for that! I have used similar script but not one-liner to traverse for the closest bin/php and put it in /etc/profile.d/phpalias.sh, so it is available for all logins - including root. If you prefer to put it in skel/bashrc and have it for each user's bashrc, that will be fine too. We just need to be sure that it is available for root as well.

**Comment by marclaporte** [comment]
The login option is necessary (-l)
![2024-01-27_162652](https://github.com/virtualmin/virtualmin-gpl/assets/1004261/4a2c90d5-051d-4d5e-9d8b-7dbf2beb54af)

**Comment by swelljoe** [comment]
I _really_ don't like messing with a users environment. I think I'd be furious, as a user, if software were munging my aliases.

**Comment by iliajie** [comment]
We can test if `php` alias is set before making any changes. Though, it isn't set in most cases.

**Comment by iliajie** [comment]
Actually, nothing needs to be done. A user environment already has precedence over a profile we create.
