### ISSUE TITLE
Transfered Domains has wrong php-fpm.conf file permissions

### ISSUE THREAD

**Issue by wstephan** [virtualmin/virtualmin-gpl#522]
Hi
i setup an Ubuntu 22.04 with Virtualmin GPL. Check runs without problems. Now i moved (transfer domain) from my old Virtualmin Server which runs on Ubuntu 18.04.

When i change their PHP-Mode from FCGID to FPM then i realized, that the FPM Server stops to work. If i try to restart the Server i got the message "another process listen allready..." or something like that.
Now i checked the files in /etc/php/8.1/fpm/pool.d an i realized a difference beetween the imported Domains from my Ubuntu 18.04 and domains i created in the fresh install of my Ubuntu 22.04.

If i create a new domain in my Ubuntu 22.04 then the files in /etc/php/8.1/fpm/pool.d get the following rights:
-rw-r--r-- 1 domain domain  361 Mär  2 09:04 13027344311489.conf

If i change the PHP Mode from FCGID to PHP-FPM in one of my transfered domain, then the rights look like this:
-rw-r--r-- 1 root root  361 Mär  2 09:04 13224321311489.conf

How i can change the creation rights of the conf-files? Which rights are the correct rights for these files?

Thank's very much for your help. Best regards
Steve

**Comment by jcameron** [comment]
OK it looks like we need to fix the way file writing permissions work in the `phpini` module. For FPM pool files, the writes need to be done as `root` and not the domain owner.

@iliajie please undo any change that effects the ownership of the FPM pool files.

**Comment by iliajie** [comment]
Yes, right! I will unroll that change.

**Comment by iliajie** [comment]
> @iliajie please undo any change that effects the ownership of the FPM pool files.

Alright, done!

**Comment by marclaporte** [comment]
For the record: https://github.com/virtualmin/virtualmin-gpl/commit/50bd1baa65f4eed4e641054242e147df251d2422

So we can close?

**Comment by iliajie** [comment]
Yes.

**Comment by wstephan** [comment]
Thank's for the quick support and your work in general!
