### ISSUE TITLE
Installing SSL certificate manually doesn't refresh cert expiry

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#526]
If a new SSL certificate installed using `Server Configuration ⇾ SSL Certificate / Update Certificate and Key` page i.e. `newkey.cgi`, domain config `ssl_cert_expiry` isn't updated.

**Comment by jcameron** [comment]
That's surprising, because we do have a call at https://github.com/virtualmin/virtualmin-gpl/blob/master/newkey.cgi#L102 to refresh it.

Is the correct expiry shown if you run `virtualmin get-ssl --domain whatever.com`

**Comment by iliajie** [comment]
> That's surprising, because we do have a call at https://github.com/virtualmin/virtualmin-gpl/blob/master/newkey.cgi#L102 to refresh it.

Yeah, I know.

> Is the correct expiry shown if you run `virtualmin get-ssl --domain whatever.com`

That I will have to check later but I remember that it wasn't showing the right expiry date in Virtual Server Summary page.

I just grabbed LE SSL certificate from the actual online server and installed it (using mentioned page) on local with the same domain name. And later noticed that summary page wasn't actually showing the correct date, where expiry date was 2028, presumably from self-generated certificate. The SSL Certificate page was showing correct everything.

**Comment by jcameron** [comment]
Ok let me know what `get-ssl` shows

**Comment by jcameron** [comment]
This patch should fix the issue of the wrong expiry date being shown : https://github.com/virtualmin/virtualmin-gpl/commit/60d03bc5ff32b02e1e743daa6b6534f5bdbd524c

**Comment by iliajie** [comment]
> This patch should fix the issue of the wrong expiry date being shown : [60d03bc](https://github.com/virtualmin/virtualmin-gpl/commit/60d03bc5ff32b02e1e743daa6b6534f5bdbd524c)

Jamie, thanks. However, this patch **_does not_** fix a problem described in [this comment](https://github.com/virtualmin/virtualmin-gpl/issues/526#issuecomment-1463792221) (above).

**Comment by iliajie** [comment]
I will open a new issue.
