### ISSUE TITLE
PHP log rotation issues

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#529]
The problem `#1` is serious. When PHP log rotation is setup for one domain (when changed using `PHP Options` page) then log rotation is remove for the other domain. I have two top level domains, and changing one removes log rotation for the other.

The problem `#2` is less problematic, and it's just printing a message where it shouldn't:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/4426533/224327640-258290ec-1b36-4dba-8344-708e5b81f174.png">

---

**Note**: All latest changes from _master_ are applied.

<br><br>

**Comment by jcameron** [comment]
When you say that log rotation is removed for the other domain, are all the log files in one big block in logrotate.conf on your system?

**Comment by iliajie** [comment]
Yes, all the logs were in one big block.

**Comment by jcameron** [comment]
So I just tested this on a system with all the latest code and the logrotate config in one block, and was unable to re-produce this bug using the UI or the command-line API.

**Comment by iliajie** [comment]
Yes, correct. All good. I no longer see this issue as well!
