### ISSUE TITLE
Better error message in Backup Virtual Servers with single archive file option selected

### ISSUE THREAD

**Issue by alexbogias** [virtualmin/virtualmin-gpl#53]
I tried to create a backup by visiting "**Backup Virtual Servers**" and selecting "**Servers to save -> only selected**", choose only 1 domain, with "**Include sub-servers of those selected?**" unchecked and also selected "**Backup Format** ->**One file per server**"

> 
> Starting backup of **1 domains** to local file /root/backups/xxxx.tar.gz ..
> Cannot backup **multiple domains** to /root/backups/xxxx.tar.gz, as it is not a directory
> Backup failed! See the progress output above for the reason why.

I know that i had to select "**Single archive file from Backup Format**" to get it done but I just wanted to let you know about the funny error message :D

**Comment by jcameron** [comment]
Yeah this is a bit confusing - what it should say is that the one-file-per-domain format cannot be used until the  destination is a directory.
