### ISSUE TITLE
File Manager: Respect additional allowed paths

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#534]
Hello, Jamie!

When additional allowed paths are added for virtual server owner in `Allow access to directories in Webmin ⇾ Webmin Users: username / File Manager – Module Access Control` page, the virtual server owner File Manager link still defaults to `/public_html` relative path, where in this case it should include the first absolute path found in `allowed_paths` directive.

This can be reproduced by adding and extra additional path and trying to open it in virtual server owner mode, which returns an expected error:

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/4426533/226066566-e82a82ae-9f26-4e9c-9134-0e27e9d0f585.png">

The ACLs for the user are as follows:

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/4426533/226066640-a0720a3b-cdb0-4f17-8154-8a4f2f7dfc1e.png">

If the path manually tweaked on the link then the File Manager itself handles it correctly:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/4426533/226066954-c0bddbde-1f0a-4b55-9dc5-f7bf97847401.png">

I have fixed that in Usermin a long time ago but it's not respected on Virtualmin side yet.

**Comment by jcameron** [comment]
What's the URL of the link to the file manager on the left menu? There should be a `path` parameter like `/home/username/public_html`

**Comment by jcameron** [comment]
Also, what's in `/etc/webmin/filemin/ubuntu22-pro.acl` ?

**Comment by iliajie** [comment]
> What's the URL of the link to the file manager on the left menu? There should be a `path` parameter like `/home/ubuntu22-pro/public_html`

Yeah, the path is `/public_html` when logged in as server owner.



> Also, what's in `/etc/webmin/filemin/ubuntu22-pro.acl` ?

That I cannot tell right now but the screenshot reflects the config, because allowed paths is the only thing that was changed away from defaults (from what Virtualmin creates).

**Comment by jcameron** [comment]
So Virtualmin actually does handle this case properly, by changing the link on the left menu to use the full path.  But if you just edit the ACL, that link might be cached! You can clean the cache by running : 

```
rm -f /etc/webmin/virtual-server/links-cache/*
```

**Comment by iliajie** [comment]
Oh, this is right, and now I remember making a fix to that code to work correctly in case it's only one allowed path is set in ACLs. I'm also aware about _links-cache_ but I was incorrectly considering that _clear-cache_ feature that is executed on the theme side actually cleans menu links in server owner mode, where it only does work properly in global mode. I will fix that.

Sorry for the false alarm!
