### ISSUE TITLE
New Feature Log: Many great features missing from list

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#536]
![2023-03-23_213415](https://user-images.githubusercontent.com/1004261/227402082-25592e57-9d37-476a-88fb-98bf68f0318b.png)

**Comment by swelljoe** [comment]
I completely forgot this existed. I suspect Jamie did, too!

**Comment by jcameron** [comment]
Yeah we haven't been maintaining that feature list. I think we should just remove that link ..

**Comment by marclaporte** [comment]
Yeah, probably not worth the maintenance effort for core devs. Users should just follow https://github.com/virtualmin/virtualmin-gpl/releases and https://forum.virtualmin.com/c/news/5

**Comment by marclaporte** [comment]
Deleted a bunch of files:

- https://github.com/virtualmin/virtualmin-gpl/commit/2460e01f53d1ca2c8cec9e7155e426f87d74cbdf
- https://github.com/virtualmin/virtualmin-gpl/commit/e8d1ce935a05fc65f25eec0c2de7447f8b159754
