### ISSUE TITLE
DKIM DNS record isn't updated upon regenerating the DKIM key for a virtual server

### ISSUE THREAD

**Issue by Stephano2000** [virtualmin/virtualmin-gpl#538]
Steps to reproduce:
- Select a virtual server
- Select Generate new key in Domainkey Options
- Click Save:
  * Adding DKIM records to DNS domain test.example.com ..
  * .. added successfully

The DKIM record isn't changed in "DNS Records", though /var/lib/bind/test.example.com.hosts is "touched"

**Comment by jcameron** [comment]
Thanks for pointing this out! It will be fixed in the next Virtualmin release ...
