### ISSUE TITLE
Let's encrypt Wildcard

### ISSUE THREAD

**Issue by alsemany** [virtualmin/virtualmin-gpl#54]
let's encrypt wildcard support is available now officially, but still not working with virtualmin yet, I'd appreciate your help to add this feature

**Comment by alsemany** [comment]
currently this message appears 
`Failed to request certificate : A domain name cannot start with *. To create a wildcard domain, first create it without the * and then go to Server Configuration -> Website Options.
`

**Comment by jcameron** [comment]
You can't create a domain with a * , but in future it will be possible to request a cert for *.domain.com

**Comment by whereisaaron** [comment]
[The future is now!](https://www.virtualmin.com/node/59651)

**Comment by jcameron** [comment]
And this is indeed supported in Virtualmin, if you have the `certbot` command installed and host DNS on your system.

**Comment by ameeno** [comment]
having a problem, with this, I have dns hosted on my system *HOWEVER* when using dns mode it simply does not give you the time nor the choices to modify your dns (if external dns) or neither does it modify the local bind dns server with _acme-challenge txt record.


Not sure if the script is up to date with the latest certbot from PPA.

but certbot changed and previous certbot from the repo cannot get wildcard certs and the new one does not seem to work with virtualmin scripts.


Help,

Couldent a simple 60 second wait or a yes / no confirmation prompt solve this issue?

A) tell me what you want my txt record to say, and ask me to continue when i am ready.
B) when i continue, do the challenge?

**Comment by jcameron** [comment]
Webmin / Virtualmin should update the DNS records automatically, if they are hosted locally.

A prompt for what to enter when hosting remotely is an interesting idea, but not one we're looking into currently.
