### ISSUE TITLE
Feature request: Make use of ProFTPD's support for name-based virtual hosts

### ISSUE THREAD

**Issue by Stephano2000** [virtualmin/virtualmin-gpl#540]
Reference: https://serverfault.com/questions/436565/proftpd-multiple-domain-virtualhosts-on-one-ip-address/766032#766032
"with the advent of [RFC 7151](https://www.rfc-editor.org/rfc/rfc7151), FTP now has a HOST command for supporting true name-based virtual hosts, just as the Host header does for HTTP 1.1.
ProFTPD implements this HOST command as of the 1.3.6rc1 release. To use it, you can simply use DNS names in your <VirtualHost> section"

Benefits:
- It allows the use of the virtual server hostnames instead of the default server hostname in FTP and FTPS connections
- It allows every virtual server to have its own FTP server listening on the same default FTP port even if all the virtual servers use the same IP

Setup example:
Default virtual server: server.example.com
Virtual server A: a.example.com
ProFTPD is listening to the default FTP port
Let's Encrypt certificates are created for both server.example.com and a.example.com

Connecting by FTPS to the default virtual server is ok
Connecting by FTPS to virtual server A with server.example.com as hostname is ok
Connecting by FTPS to virtual server A with a.example.com as hostname gives a certificate mismatch as ProFTPD will always present the certificate of server.example.com, while the ftp client is connecting to a.example.com

ProFTPD can make use of virtual hosts sections in its config file (the same as Apache), and each virtual host section would specify its domain and certificates. After all it's logical for server A to have its FTP/S hostname a.example.com rather than server.example.com

The below is just an example:
```
<VirtualHost a.example.com>
<IfModule mod_tls.c>
        TLSEngine on
        TLSLog /var/log/proftpd/tls.log
        TLSProtocol  all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
        TLSRSACertificateFile /etc/ssl/virtualmin/xxxxxxxxxxxxxxx/ssl.cert
        TLSRSACertificateKeyFile /etc/ssl/virtualmin/xxxxxxxxxxxxxxx/ssl.key
        TLSCACertificateFile /etc/ssl/virtualmin/xxxxxxxxxxxxxxx/ssl.ca
        TLSVerifyClient no
        TLSRequired on
        TLSRenegotiate required off
        TLSOptions NoSessionReuseRequired
</IfModule>

ServerName a.example.com
<Anonymous /home/a/ftp>
User ftp
Group nogroup
UserAlias anonymous ftp
<Limit WRITE>
DenyAll
</Limit>
RequireValidShell off
</Anonymous>
</VirtualHost>
```

**Comment by chris001** [comment]
Good issue!  I believe `SMTP` and `IMAP` domain name based virtual hosts have been made to work (comment if not true for you).  `ProFTPd` still has yet to get working, as mentioned in #21

**Comment by jcameron** [comment]
Thanks, we didn't know about this. I'll add support for name-based FTP to the project list, and update this bug with progress..

**Comment by jcameron** [comment]
Ok, the next release of Virtualmin will include support for name-based virtual FTP servers.
