### ISSUE TITLE
Disabling mail feature doesn't remove autodiscover records from DNS

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#544]
Jamie, hello.

If you enable **Mail for domain** feature then _autodiscover_ DNS and web-server records are added correctly, in case **Mail Client Configuration** feature is enabled. However, if you disable **Mail for domain**  feature, then _autodiscover_ DNS related records are not removed.

Tried on Ubuntu 22.04 with all latest code applied.

**Comment by jcameron** [comment]
Try out the patch I just attached ... that should fix it.

**Comment by iliajie** [comment]
Oh, wait. I think I incorrectly reported the problem initially. This patch doesn't change anything to the original issue and probably should be reverted!

The problem is that when the mail is enabled, these records are added:

```
autoconfig.ubuntu22-pro.virtualmin.dev.     IN      AAAA    2000:2c26:f4e4:0:333:3333:2222:1111
autodiscover.ubuntu22-pro.virtualmin.dev.   IN      AAAA    2000:2c26:f4e4:0:333:3333:2222:1111
mail.ubuntu22-pro.virtualmin.dev.           IN      A       1.2.3.4
autoconfig.ubuntu22-pro.virtualmin.dev.     IN      A       1.2.3.4
autodiscover.ubuntu22-pro.virtualmin.dev.   IN      A       1.2.3.4
```

However, when mail is disabled the records only removed partially, and here is what's left:

```
autodiscover.ubuntu22-pro.virtualmin.dev.   IN      AAAA    2000:2c26:f4e4:0:333:3333:2222:1111
autodiscover.ubuntu22-pro.virtualmin.dev.   IN      A       1.2.3.4

```

Also, it's not clear why `AAAA` records are added for `autodiscover.` and `autoconfig.` but not for `mail.` -- seems like a separate but also an issue!

**Comment by jcameron** [comment]
Check out the commit above - it should fix that deletion issue.

**Comment by iliajie** [comment]
That fixes original issue, however now MX record is left over when mail is disabled:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/4426533/230665283-0a013db5-0f95-47f5-89f1-904535b8f06a.png">

**Comment by jcameron** [comment]
Hmm, I wasn't able to reproduce this in my tests. How did you disable email - via the UI or command-line API?

**Comment by iliajie** [comment]
> Hmm, I wasn't able to reproduce this in my tests. How did you disable email - via the UI or command-line API?

Via UI. Did you apply all latest patches? Because before MX records weren't even added.

**Comment by iliajie** [comment]
Also, SPF is not getting removed when mail is disabled.

**Comment by jcameron** [comment]
Hang on, was this the default domain on a new Virtualmin system?

**Comment by iliajie** [comment]
I tried both, the default and just a domain.

**Comment by jcameron** [comment]
So I don't think we should remove the SPF record, because email can be sent from a domain even if incoming email is disabled.

What output do you see in the UI when disabling the mail feature for a domain?

**Comment by iliajie** [comment]
I clearly see the progressive output saying that MX record is being removed.

**Comment by iliajie** [comment]
> So I don't think we should remove the SPF record, because email can be sent from a domain even if incoming email is disabled.

I know. But why would anyone want to do it?

**Comment by iliajie** [comment]
> > So I don't think we should remove the SPF record, because email can be sent from a domain even if incoming email is disabled.
> 
> I know. But why would anyone want to do it?

Also, we don't tell user that we're disabling incoming mail. We just disable mail, right?

**Comment by iliajie** [comment]
Also, it's not a problem to re-enabled SPF using **DNS Options** page.

**Comment by jcameron** [comment]
Hmm, I can't see what's going on here. Does the same thing happen if you disable email using the `virtualmin disable-feature` command?

**Comment by iliajie** [comment]
That I haven't tried yet. But it's clearly happening if you toggle mail feature for a domain.

**Comment by jcameron** [comment]
Sorry, but I don't know what's happening here - I wasn't able to reproduce this with all the latest code, in the UI or API.

**Comment by iliajie** [comment]
> Sorry, but I don't know what's happening here - I wasn't able to reproduce this with all the latest code, in the UI or API.

The problem is this line:

https://github.com/virtualmin/virtualmin-gpl/blob/3f762c9abde77bb26b8cb05a291ce20125a84f4b/feature-dns.pl#L973

It's never getting resolved properly, i.e. `mail.alma9-pro.virtualmin.dev` is never getting resolved to an expected IP address, it always returns empty.

It may be a problem related to my local machines, I think?

**Comment by jcameron** [comment]
Oh I see, if somehow your system cannot resolve it's own DNS zones, this could fail.

Try this patch : https://github.com/virtualmin/virtualmin-gpl/commit/ac3a3a34c9048a6cd119a2f990f171414ef4305e

**Comment by iliajie** [comment]
Alright, that works fine! Thanks!
