### ISSUE TITLE
DNSSEC accordion is missing

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#545]
Jamie, when DNSSEC for domain is enabled in Virtualmin, there is no longer DNSSEC related accordion displayed in there:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/4426533/230672666-518b145b-63a4-4817-8552-01d06ff970f8.png">

I remember it was there?

**Comment by jcameron** [comment]
Looks like I broke this when adding remote DNS support ... check out the attached patch.

**Comment by iliajie** [comment]
That seems to work. Thanks.
