### ISSUE TITLE
Odd behavior for Secondary Mail Servers when different save buttons are used

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#547]
If first disable Secondary Mail Servers for a Webmin server (untick) and hit **Save, and add ..** then it deletes the records correctly.

However, if I want to enable it and then tick the checkbox and hit just **Save** button, servers are not actually added to the remote. Moreover, and what actually looks like a bug is that if I later click **Save, and add ..** button, then secondaries are still never added. The only fix is it to disable it first and then click **Save, and add ..** button straight way, which only works properly.

Do we even need the first **Save** button at all?

**Comment by jcameron** [comment]
The difference is that the **Save** button changes the behavior for future domains, while the **Save and** button also effects existing domains. This is working as intended ...

**Comment by iliajie** [comment]
Oh, I see now! This behavior makes sense then!

Although, I would suggest to name buttons more clearly. It's very confusing.

How about something like this:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/4426533/232203241-ce0cec68-309d-458e-89f9-b60474925095.png">

Also, the button should not be **Save and add**. It should be **Save and apply**, because it also removes secondaries.

I have updated labels and help files https://github.com/virtualmin/virtualmin-gpl/commit/f4640f66b7d5e12bcbef442f5dfe5b57126181fe.

**Comment by jcameron** [comment]
Seems reasonable, thanks!
