### ISSUE TITLE
Removed features on latest update

### ISSUE THREAD

**Issue by dpark77** [virtualmin/virtualmin-gpl#549]
After upgrading virtualmin to the latest version, noticed that some features are no longer there.

1. [x] Nginx SSL website enabled (edit virtual server) 
2. Show # items (per page on File manager)

These are quite useful features anytime when a quick work is needed. 
it could be from troubleshooting an ssl issues to a searching through a large number of files quickly in file manager.

Hope they're reinstated on your next update.

**Comment by iliajie** [comment]
Hello,

Those are all features and not bugs! 🙂 

 1. Nginx SSL website is now automatically enabled. You don't need to do anything. However, if you wish to see the old behaviour where you could separately check non SSL and SSL websites, you could do it by going to **System Settings ⇾ Features and Plugins** and un-checking **Default?** for **Nginx SSL webiste**.
 2. In File Manager, show items per page is now automatic and fits the user browser window. However, if you want to bring back the old behaviour you can do it by going to **File Manager ⇾ Preferences: General defaults** and un-checking **Automatic** checkbox for **Default number of items per page** option.

**Comment by dpark77** [comment]
You're right! I just had to un-tick first and tick it back on.
All great, thanks.

**Comment by iliajie** [comment]
> You're right! I just had to un-tick first and tick it back on.

Are you talking about **System Settings ⇾ Features and Plugins** and un-checking **Default?** for **Nginx SSL webiste** option?
