### ISSUE TITLE
Case Sensitive email addresses in Usermin Login

### ISSUE THREAD

**Issue by GENnetuk-DEV** [virtualmin/virtualmin-gpl#553]
When creating users in virtualmin, the form converts email addresses to lower case, which is fine. When logging into UserMin, it does not do the same, which confuses some users who naturally seem to think that Fred@ is the same as fred@. It would make sense to just convert the username to lower case in UserMin login and avoid that.

**Comment by jcameron** [comment]
Do you mean that usermin doesn't allow logins with the wrong username case?

**Comment by iliajie** [comment]
Jamie, I think, the fix for this problem is simple, because emails are case-insensitive. All we need to do in _miniserv_ is to test if a username contains `@` and if it does, just lowercase it, right?

**Comment by jcameron** [comment]
This is a little tricky, because in Linux usernames are case sensitive. But I have checked in a fix to try the lowercase username if the mixed-case one doesn't exist ..

**Comment by GENnetuk-DEV** [comment]
Maybe, and only a suggestion, you could have a setting in Webmin that just forces lower case usernames, or not. Assuming its set then lower case any input to username when creating or logging in, and a good default setting to use. Assuming it was switched from off -> on, then a quick check of the users to make sure there aren't any mixed case before enabling would probably be a nice check. only a suggestion of course, keep up the great work!

**Comment by jcameron** [comment]
The fix I checked in for the next release should handle this gracefully, because it will fall back to the lower-case username automatically if necessary..
