### ISSUE TITLE
new virtualmin install inside lxc container not redirecting to child virtual server

### ISSUE THREAD

**Issue by gstlouisgit** [virtualmin/virtualmin-gpl#554]
Debian 11.6
Webmin version	2.021 	
Usermin version	1.861
Virtualmin version	7.7  

In case this helps

I have an lxc container that holds virutalmin for http at this time.  After configuring the lxc profile so all http are re-directed to the container for virtualmin to serve the website to the appropriate virtual server, it would not work.  

I looked at `vim /etc/apache2/sites-available/websitenamed.conf` I noticed that its <VirtualHost tag was pointing to the container internal IP `<VirtualHost 10.23.99.23:80>`

I changed this to <VirtualHost *:80> and all worked fine after apache reload

I know that static IP's in this take precedence, maybe a good idea for virtualmin to use the wildcard *:80?

feel free to close if this is known or of no use for improvement.

**Comment by iliajie** [comment]
> I know that static IP's in this take precedence, maybe a good idea for virtualmin to use the wildcard *:80?

It's better not to mix `IP` with `*` for `VirtualHost` directives in one config file. Also, **System Settings ⇾ Virtualmin Virtual Servers ⇾ Configuration: Defaults for new domains** page has **Address format for Apache virtual hosts** option to address this problem.

**Comment by gstlouisgit** [comment]
Cool thanks @iliajie for pointing out how to configure that tag
