### ISSUE TITLE
Virtualmin's website SPF records are faulty - Cannot register on forum

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#560]
Hi

> I know this is not the right place to post an issue about the website but there is not other way of contacting virtualmin.

## The problem

I cannot register on your site because your SPF records on www.virtualmin are faulty and my spam software is deleting the verification emails. I do not control this server.

![image](https://user-images.githubusercontent.com/319997/236668165-9bc1f4c4-dfba-4134-8b7f-12b0e8317e9c.png)

## Research

Your SPF records are as follows (checked on MX toolbox)
- **www.virtualmin.com** || `v=spf1 include:mailgun.org ~all`
- **virtualmin.com** || `v=spf1 a mx a:n1.virtuamlin.com a:virtualmin.com a:new.cloud.virtualmin.com a:www.virtualmin.com mx:mail.virtualmin.com ip4:45.76.233.251 ip6:2001:19f0:6401:9e4:5400:3ff:fe31:dca3 -all`

**www.virtualmin.com**
- This is the domain responsibly for sending emails from virtualmin.
- This is wrong potentially because it only allows emails to be sent from the IPs specified in the SPF record of mailgun.org (your transactional emails provider
- and because softfail is on, it will allow spam to through some peoples spam setup.
- `pc232-3.mailgun.net` - does not seem to be in the allow IPs.

**virtualmin.com**
The @virtualmin.com SPF record is just faulty and I have not looked that much at it but it will not be getting used because of syntax or other errors in the statement

## What I would do to fix the issue:

- the email sending domain should be changed from **www.virtualmin.com** to **virtualmin.com** so it looks normal.
- Your new SPF record should be something like 
  - `v=spf1 a mx include:mailgun.org -all`
  - `v=spf1 a mx include:mailgun.org ip4:143.55.232.3 -all`

**Comment by jcameron** [comment]
@swelljoe I didn't know we were using mailgun .... any idea what's up here?

**Comment by chris001** [comment]
I agree @jcameron  Shouldn't the Virtualmin website demonstrate "live" the `virtualmin-gpl` server software's powerful capabilities to cleanly send its own outgoing email messages thru its own Postfix SMTP server?  Plus, all of its other superior management of its own backup, website, PHP, MariaDB, email security, spam virus filtering, and secure multiple DNS servers?

**Comment by iliajie** [comment]
> Plus, all of its other superior management of its own backup, website, PHP, MariaDB, email security, spam virus filtering, and secure multiple DNS servers?

We surely do that!


> I agree @jcameron Shouldn't the Virtualmin website demonstrate "live" the `virtualmin-gpl` server software's powerful capabilities

I don't think this is what Jamie was implying here!

>  to cleanly send its own outgoing email messages

The crucial aspect to consider is that the successful delivery of emails is not solely contingent upon the local server configuration, which is within the great capabilities of Virtualmin. As even a trivial blacklisting of an ISP IP address could prevent users from receiving emails from us! Therefore, utilizing Mailgun is a more dependable and simple solution for us.

**Comment by jcameron** [comment]
Yeah, Mailgun is a solid choice when you need to send a lot of email - it's all too easy for a single system to get blacklisted by some aggressive spam blocking services.

**Comment by shoulders** [comment]
Misconfigured SPF should also be added here: https://www.virtualmin.com/documentation/email/troubleshooting/ 😄

**Comment by iliajie** [comment]
> Misconfigured SPF should also be added here: https://www.virtualmin.com/documentation/email/troubleshooting/ 😄

This is something that only @swelljoe can fix.

**Comment by shoulders** [comment]
Can someone directly contact Joe on the forum or by email and get this fixed? He does not seem to be active on GitHub and I cannot access the forum or contact the team in any other way.

I don't understand why Virtualmin is happy for clients not even to be able to register or contact the team. Virtualmin is definitely loosing business. 😢

**Comment by swelljoe** [comment]
[www.virtualmin.com](http://www.virtualmin.com/) has the recommended records provided by the mailgun folks. I'm reading up to see what else I might be missing or if there have been changes since I set it up.

I don't see any reason to change the name of the sending system to virtualmin.com. I think it's useful to know the actual server sending the mail (the forum sends mail from forum.virtualmin.com, and we have a mail server, too, that doesn't use mailgun and is for our @virtualmin.com email addresses).

I have marked your account as email verified, so you should be able to login and use the forum.

**Comment by shoulders** [comment]
> thanks for authorizing my account. I cannot login because I lost the password I signed up with. but at least my username will not be  taken 😄 
- The IP addressess your forum is using to send mail from mailgun are not authorized by the mailgun SPF record. I checked the IP against the mailgun IPs listed in their SPF and I could not find it. Almost like there is a bank of their servers not added and you are on that bank.
- the forum emails are being sent from the domain **www.virtualmin.com** so this domain's SPF record needs to authorise the IP sending the email
- **www.virtualmin.com** the spf rcord should have `-all` and not `~all` and this record only allows emails to be sent from mail gun servers. no one should be recommending anything else but `-all`
- the **virtualmin.com** spf record is just corrupt
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/0b560fc8-5ceb-439e-bf64-4925fe5205b6)

Thanks

**Comment by swelljoe** [comment]
virtualmin.com is irrelevant to your problem (though I'll fix that SPF record).

**Comment by swelljoe** [comment]
When I follow the includes:

```
$ host -t txt www.virtualmin.com
www.virtualmin.com descriptive text "v=spf1 include:mailgun.org ~all"
$ host -t txt mailgun.org |grep spf
mailgun.org descriptive text "v=spf1 include:_spf.mailgun.org include:_spf.eu.mailgun.org -all"
$ host -t txt _spf.mailgun.org
_spf.mailgun.org descriptive text "v=spf1 ip4:209.61.151.0/24 ip4:166.78.68.0/22 ip4:198.61.254.0/23 ip4:192.237.158.0/23 ip4:23.253.182.0/23 ip4:104.130.96.0/28 ip4:146.20.113.0/24 ip4:146.20.191.0/24 ip4:159.135.224.0/20 ip4:69.72.32.0/20" " ip4:104.130.122.0/23 ip4:146.20.112.0/26 ip4:161.38.192.0/20 ip4:143.55.224.0/21 ip4:143.55.232.0/22 ip4:159.112.240.0/20 ip4:198.244.48.0/20 ~all"
```

Note `ip4:143.55.232.0/22` is listed. So...the IP being used is included.

I have added the `mailgun.org` include to the `virtualmin.com` SPF record, as well, and removed an old name and fixed a typo.

Let me know if you continue to have problems.

**Comment by shoulders** [comment]
> I am assuming that your records have actually been updated and that mxtoolbox has reflected this.

- emails from the reset password https://www.virtualmin.com/account/lost-password/ still getting failed
- The sending/bounce addresses is `@www.virtualmin.com` not `@virtualmin.com`

using MX toolbox https://mxtoolbox.com/spf.aspx

- virtualmin.com is still broken. I know it doesn't matter. There is an error in the syntax. `SPF Void Lookups  Void lookup limit of 2 exceeded (3)` some of the include commands must be bringing back empty or null results. This causes the whole spf record to be ignored.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/e8fd17c8-08b5-45ed-b521-125b11a211b2)

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/e9f085dd-4199-48a6-be9d-17c5e1cef4f2)

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/163a3995-bd67-4144-b583-0c38e527f662)

------
## What i think they should be:
**virtualmin.com**
`v=spf1 a mx -all` or
`v=spf1 +a +mx -all`  some people do not include the + sign anymore because it is implied
- there was a lot of duplicates, dead and pointless entries in this one.
- this is assuming you do not use mailgun on this domain

**www.virtualmin.com**
`v=spf1 a mx include:mailgun.org -all` or
`v=spf1 +a +mx include:mailgun.org -all`  some people do not include the + sign anymore because it is implied
- the record is a best guess to fix this.
- i do not know why this record is causing SPF failure at my end if the sending IP is included. The only thing I can think of is that the email is getting relayed and the IPs need including.
- this domain has 2 mx records
  - mxa.mailgun.org.virtualmin.com
  - mxb.mailgun.org.virtualmin.com

If it is of interest I could rig up a test account on my server tomorow and send you the details somehow.

I appreciate your time looking into this.

**Comment by swelljoe** [comment]
I'm getting all green results for the configuration I changed to, but I saw that our secondary DNS server didn't automatically update when I made changes, I'm not sure why), so I guess your check was getting old results from the old server. I've forced a refresh on that server. If you're still unable to get delivery, I think I'm stumped.

![Screenshot from 2023-06-21 16-29-59](https://github.com/virtualmin/virtualmin-gpl/assets/99768/1ec72b61-5eb5-439c-bf5c-5ad61d97fe79)

![Screenshot from 2023-06-21 16-30-34](https://github.com/virtualmin/virtualmin-gpl/assets/99768/26d5ca9c-769d-48ee-80fa-5add5c2f971e)

**Comment by shoulders** [comment]
> Still broken, could be the server cache but the record on `www.virtualmin.com` has not been changed except for softfail is now hardfail (which is good)

- why don't you run it pass mailgun, maybe see if they thing the records below are better.
- I checked each one for duplicates and whether they replied to ping.
- i would change the sending domain from `www.virtualmin.com` to `virtualmin.com` for your transaction emails
- try the SPF records below

## What i think they should be: (checked against your new records)
**virtualmin.com**
`v=spf1 a mx a:n1.virtualmin.com include:mailgun.org -all` 
- I am not sure why you need to include the name server, you probably don't need to unless you have a mailserver installed on that domain. So i would remove it from the statement above.

**www.virtualmin.com**
`v=spf1 a mx include:mailgun.org -all`

- All SPF values (except the -all) are all resolved down to IP addresses so you do not need to add domains and IPs if their domain is specified. It could maybe cause issues if the webserver is on a CDN and there are different IPs given out for it depeneding where you are located, in which case remove the `a` and add an `ipv4:` specification
- a on its own is the IP of the domains A record
- mx is the ip of mx record for the domain

**Comment by swelljoe** [comment]
`n1.virtualmin.com` is not the name server.

**Comment by shoulders** [comment]
## I have a theory

- the emails are being sent from the domain `www.virtualmin.com`
- cPanel when it checks the spf record is actually checking the `virtualmin.com` SPF record
- `virtualmin.com` has a broken SPF record so cPanel will never validate the email, this causes the email to have the `sender verified failed` error

This is probably caused by cPanel classing `www` and `non-www` domains as the same

## Solution
- Fix the SPF record on `virtualmin.com`
- the records I did above should work.
- I would also send the emails from `virtualmin.com` to make things tidy, but I think this is optional.

## Research
- https://www.spf-record.com/spf-lookup/www.virtualmin.com?ip=69.72.42.1 = passes
- https://www.spf-record.com/spf-lookup/virtualmin.com?ip=69.72.42.1 = fails because of a syntax error
  - The SPF record for `virtualmin.com` is not valid.
  - The syntax check resulted in a total of 1 errors.
  - `mx:mail.virtualmin.com` cannot be resolved (IPv4) / there is no mx entry for this domain.
