### ISSUE TITLE
usermin not working for one of the virtual servers

### ISSUE THREAD

**Issue by gstlouisgit** [virtualmin/virtualmin-gpl#562]
Operating system | CentOS Linux 7.9.2009
-- | --
Webmin version | 2.021 | Usermin version | 1.861
Virtualmin version | 7.7 | Authentic theme version | 20.21

I have a virtual server user that I tried to introduce usermin for them to see their emails.  They have a 3 gig email account created under their virtual server, not the primary account of the virtual server itself.

When I help them login it just says "NO NEW MAIL"
On the left side hidden bar that opens, I can see that sent email has 3 new messages and spam has like 3000.  But nothing really happens when I click on any of the inboxes.

If I go into virttualmin and choose to "Read User Mail", from here everything works fine.  But from user perspective, it is not working.

How would I go about troubleshooting this?
Another domain I have tried are working on this server.  I have tried logging in with user@domain and user.domain, which both authenticate, but server templates is setup with user@domain

<img width="1135" alt="Screen Shot 2023-05-09 at 10 36 24 PM" src="https://github.com/virtualmin/virtualmin-gpl/assets/20375753/81511c3a-ed68-45d7-af26-9d3acb865b64">

**Comment by jcameron** [comment]
Does the page just load and load and eventually time out when you click on Inbox? It's possible that the mailbox is just too large to load..

Also, are you able to access email for this user using another mail program like Outlook or Thunderbird?

**Comment by gstlouisgit** [comment]
@jcameron 
Thanks for your comment
This is my fault.  I turns out that server domain had reached its quotas.  Your comment about putting the account in thunderbird made me try it and once I accepted the certificate, I could see in journalctl that the quota was exceeded.  Sucks I didn't see it before, maybe he didn't accept the cert and it was stuck logging?

anyway, sorry for the trouble, and thank you.

**Comment by chris001** [comment]
Would be brilliant for `usermin` to display the `quota exceeded` error, in the browser, to the user, then he knows, he can make more space by clicking a few times to empty out his `spam` folder.

**Comment by jcameron** [comment]
Did you get a quota exceeded error in Thunderbird or Outlook, or did it only appear in the logs?

**Comment by chris001** [comment]
> once I accepted the certificate, I could see in journalctl that the quota was exceeded.

It would seem, to show your IMAP mailbox quota in Thunderbird, you have to install [an optional add-on, like this one](https://addons.thunderbird.net/en-us/thunderbird/addon/display-quota/).

**Comment by gstlouisgit** [comment]
@jcameron 
I cannot really confirm as I did not look at thunderbird for that, sorry.  Once I saw the warning in the journalctl I was content and modified the account acconrdingly

**Comment by jcameron** [comment]
Was it the individual user who was out of quota, or the entire domain? The first one should trigger a warning on the dashboard after the user signs in..
