### ISSUE TITLE
Can not zip files when selecting files across multiple pages

### ISSUE THREAD

**Issue by Whip** [virtualmin/virtualmin-gpl#563]
Steps to reproduce problem:

1. Go to File manager and open a directory that has enough files to have 2 or more pages.
2. Use the Select All option. A warning prompt asks if you want to select files across all pages, choose Yes.
3. Go to File > Create new archive. Errors will appear in the bottom right corner and you will not be able to create an archive
4. Close the dialog, deselect any one file and select it again.
5. Go to File > Create new archive. It works now.

**Comment by iliajie** [comment]
Hello,

Have you tried manually updating to the latest Authentic Theme 20.22 release? It should fix the issue your talking about, right?

**Comment by Whip** [comment]
Hi. I don't have 20.22 available. My current version is 20.21.

By manual, do you mean downloading files from somewhere?

**Comment by iliajie** [comment]
I mean installing from Theme Configuration page (disabling Usermin updates first). Also, make sure to install latest stable version rather than development.

**Comment by Whip** [comment]
I think I'll just wait for the update to arrive on the dashboard. If you're sure this is fixed in 20.22 you can close the issue.

**Comment by iliajie** [comment]
Actually, I'm also seeing this. I will take a closer look. Thanks for the heads up!

**Comment by iliajie** [comment]
This issue will be fixed in the next Webmin release (with Authentic Theme 20.30).

Thanks for the heads up!
