### ISSUE TITLE
Return of the 0 byte new secondary zone file with bind cluster use

### ISSUE THREAD

**Issue by johnheenan** [virtualmin/virtualmin-gpl#565]
The 0 byte secondary zone file after zone creation problem is back when using bind cluster service!

Originally fixed in https://github.com/virtualmin/virtualmin-gpl/commit/d5c5ac0945a4fa00b73f80d7de9af46d925ddcda

Reraised in https://forum.virtualmin.com/t/return-of-the-0-byte-new-secondary-zone-file-with-bind-cluster-use/120844

Complete description of problem in closed topic at https://forum.virtualmin.com/t/bind-cluster-name-servers-setup-doesnt-create-slave-zones-anymore-but-0-byte-files-are-present/115777/1

|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Rocky Linux 9.2     |
|  Webmin version      |     2.021      |
|  Usermin version     |     1.861     |
|  Virtualmin version  |     7.7  Pro       |
|  Theme version       |     20.21      |
|  Package updates     |      1  package update is available   |

**Comment by jcameron** [comment]
Is anything logged by `bind` to `/var/log/messages` on the slave server when you create a zone? Or when you try to force a zone transfer in Webmin on the slave?

**Comment by johnheenan** [comment]
Hi Jamie

I think it will help to present the information you request in context due to the complex nature of the issue.

These are the expected steps. Suppose the domain name has name 111179.xyz

1. Virtualmin cluster on primary server logs into secondary server and creates a secondary zone file `/var/named/slaves/111179.xyz.hosts`
2. Virualmin cluster on primary opens the file above in secondary server, fills in contents of file and closes file
3. Virtualmin cluster on primary runs `rndc reload 111179.xyz` or equivalent on the secondary server

Suppose only step 1 is completed without steps 2 and 3.

Then we don't expect a log entry for step 3 in `/var/log/messages` or in the system journal logs as step 3 is not run.

So, what remedial action can be taken and what will the log entries show?

4) Logging manually into the secondary server and running `rndc reload 111179.xyz` to force a zone transfer won't fix the problem

5) Logging manually into secondary server and running the potentially computationally and network expensive `rndc reload` command will fix the problem (forcing zone transfers) with numerous log entries.

So using `journalctl -efu named` on secondary server with creation of 111179.xyz on primary server with virtualmin and with secondary server listed as a cluster slave server on the primary server:

Primary server
```
Re-starting slave DNS servers ..
.. done
```
Secondary server has no named log entry but we do get a 0 byte file on the scecondary server:
```
ll /var/named/slaves/111179.xyz.hosts 
-rw-r--r-- 1 named named 0 May 22 08:52 /var/named/slaves/111179.xyz.hosts

```
Concuision is that only Step 1 from above was completed.

Trying to force a zone transfer for 111179.xyz specifically fails:
```
rndc reload 111179.xyz

rndc: 'reload' failed: not found
no matching zone '111179.xyz' in any view
```

However using an unrecommended general reload does work with numerous first time only error messages
```
rndc reload 

server reload successful
```
Following are relevant messages using `journalctl -efu named`. The logs acknowledge named sees the zone file is empty but since named now knows the name of the zone from the name of the file it now knows the name of the zone to request a forced zone transfer of.

So the problem is remediated.

```
May 22 09:03:24 aus2.zgus.com named[2744]: ../../../lib/dns/master.c:2268: unexpected error:
May 22 09:03:24 aus2.zgus.com named[2744]: isc_stdio_read failed: end of file
May 22 09:03:24 aus2.zgus.com named[2744]: zone 111179.xyz/IN: loading from master file /var/named/slaves/111179.xyz.hosts failed: end of file
May 22 09:03:24 aus2.zgus.com named[2744]: zone 111179.xyz/IN: unable to load from '/var/named/slaves/111179.xyz.hosts'; renaming file to '/var/named/slaves/db-mtYm6g78' for failure analysis and retransferring.
May 22 09:03:24 aus2.zgus.com named[2744]: all zones loaded
May 22 09:03:24 aus2.zgus.com named[2744]: managed-keys-zone: Key 20326 for zone . is now trusted (acceptance timer complete)
May 22 09:03:24 aus2.zgus.com named[2744]: running
May 22 09:03:24 aus2.zgus.com named[2744]: zone 111179.xyz/IN: Transfer started.
May 22 09:03:24 aus2.zgus.com named[2744]: transfer of '111179.xyz/IN' from 45.76.120.89#53: connected using 139.180.167.29#41909
May 22 09:03:24 aus2.zgus.com named[2744]: zone 111179.xyz/IN: transferred serial 2023052100
May 22 09:03:24 aus2.zgus.com named[2744]: transfer of '111179.xyz/IN' from 45.76.120.89#53: Transfer status: success
May 22 09:03:24 aus2.zgus.com named[2744]: transfer of '111179.xyz/IN' from 45.76.120.89#53: Transfer completed: 1 messages, 16 records, 518 bytes, 0.002 secs (259000 bytes/sec) (serial 2023052100)
May 22 09:03:24 aus2.zgus.com named[2744]: zone 111179.xyz/IN: sending notifies (serial 2023052100)

```

**Comment by jcameron** [comment]
Ok, it sounds like the problem may be that Virtualmin is adding the zone to named.conf on the slave server and creating an empty zone file, but isn't running `rndc reload` or the equivalent so that BIND knows about the new zone.

What does `/etc/webmin/bind8/config` contain on the slave system? Also, which Linux distro and version is it running?

**Comment by johnheenan** [comment]
Linux distro and version on secondary is Rocky 9.2


|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Rocky Linux 9.2     |
|  Webmin version      |     2.021      |
|  Usermin version     |     1.861     |
|  Virtualmin version  |     7.7  Pro       |
|  Theme version       |     20.21      |
|  Package updates     |      1  package update is available   |

```
cat /etc/webmin/bind8/config 

rev_must=0
checkzone=named-checkzone
confirm_rec=0
tmpl_dnssec=0
reversezonefilename_format=ZONE.rev
updserial_def=0
ipv6_mode=1
no_pid_chroot=0
checkconf=named-checkconf
pid_file=/run/named/named.pid
rev_def=0
forwardzonefilename_format=ZONE.hosts
show_list=1
allow_underscore=1
spf_record=0
master_dir=/var/named
no_chroot=0
allow_comments=0
soa_style=1
dnssec_period=21
by_view=0
chroot=
other_slaves=1
signzone=dnssec-signzone
dnssec_info=1
force_random=0
rndc_conf=/etc/rndc.conf
allow_long=0
named_path=/usr/sbin/named
whois_cmd=whois
updserial_on=1
updserial_man=1
support_aaaa=1
rndcconf_cmd=rndc-confgen
ndc_cmd=ndc
confirm_zone=1
records_order=0
slave_dir=/var/named/slaves
allow_wild=1
named_conf=/etc/named.conf
soa_start=0
largezones=0
restart_cmd=systemctl reload named
master_ttl=1
tmpl_dnssec_dt=
max_zones=50
relative_paths=0
start_cmd=systemctl start named
auto_chroot=
keygen=dnssec-keygen
rndc_cmd=rndc
stop_cmd=systemctl stop named
short_names=0
extra_slaves=
this_ip=139.180.167.29
servers=1684282299 1684563949
default_slave=ns2.zgus.com
secservers=1684282299 1684563949
tmpl_dnssecsingle=0
tmpl_dnssecalg=RSASHA1
tmpl_dnssecsize=
tmpl_email=
tmpl_dnssecsizedef=1
```

**Comment by jcameron** [comment]
Try changing the line `restart_cmd=systemctl reload named` to `restart_cmd=rndc reload` and see if that helps.

**Comment by johnheenan** [comment]
Changed cluster config file as requested above to use `rndc reload`.

Also used a different domain, 111178.xyz, to avoid caching issues

With server creation got the following logs on the primary. The log messages are incorrect. This indicates the the `rndc reload` command is being applied too soon before the primary nameserver is ready

```
May 22 14:05:10 aus2.zgus.com named[2744]: client @0x7fe28804ec78 45.76.120.89#60506: received notify for zone '111178.xyz': not authoritative
May 22 14:05:10 aus2.zgus.com named[2744]: client @0x7fe290a4daa8 45.76.120.89#57159: received notify for zone '111178.xyz': not authoritative
```

From primary:
```
Re-starting DNS server ..
.. done
Re-starting slave DNS servers ..
.. done
```

Other than that, the exact same as for 111179.xyz above. A zero length file with commands `rndc reload 111178.xyz` and `rndc reload` behaving exactly as above for 111179.xyz.

**Comment by johnheenan** [comment]
Edited message above to indicate additional log entries were on secondary, not primary.

**Comment by johnheenan** [comment]
I need to correct above. The additional messages would have come from the secondary after correctly receiving notify messages from the primary and correctly deciding at the time of receipt the primary was not authoritative for the domain, even if the secondary was about to be informed the primary was authoritative.

Hence, the log messages are irrelevant.

Hence it looks like the 'rndc reload' was never executed through the cluster software.

**Comment by johnheenan** [comment]
This is a trick that might work. Update secondary servers before the primary server. That way when the primary server sends a notify message to the secondary servers the secondary servers will know beforehand that the primary server is authoritative.

A preferred solution is to actually fill the secondary zone file with content and then issue an update command.

Maybe both approaches can be used.

**Comment by jcameron** [comment]
I wonder if there's some delay between when Webmin issues a `reload` command and when BIND picks it up?

**Comment by johnheenan** [comment]
I have not experienced a noticeable delay when executing a reload on a command line in the sense that there is always some immediate entry in the logs. Commands `rndc reload` and `systemctl reload named` both have different log entries even if they get the same end result.

Leaving aside a potential delay issue for the moment I have found a potential issue in function `run_post_actions` in file virtual-server-libs-funcs.pl. 
```
# Don't run multiple times. For BIND, all restarts are considered equal
```
The function only considers a reference to the `restart_bind` function when comparing, not on which server the function is to run on.

So, if a bind restart is queued on the primary first and on the secondary next then only the bind restart on the primary will get called.

Any hints on a convenient way to debug or test this?

**Comment by jcameron** [comment]
You might be onto something there - does this patch help? 

https://github.com/virtualmin/virtualmin-gpl/commit/aa990d112747909c4a727bb934cab45a7fecfff8

**Comment by johnheenan** [comment]
I added your modifications in and added debugging code to determine what is being called. Output below. For the record the problem remains.

From the output of the debug code, the restart_bind function is called twice, once without a dom set and once with dom set to the new domain name. I need to further trace how this is working (or not working).

I am sorry if I am being confusing using the term 'secondary' instead of 'slave' in the context of nameservers. There is currently a big move to replace words such as master and slave.  For example github now uses main instead of master as the default name for repositories. I know secondary commonly refers to mail servers and slave to name servers.

```

2023-05-23T04:40:47
  CALLING function, dom: 'restart_bind, 111179.xyz'
    restart function succeeded?

  ALREADY EXECUTED function, dom: 'restart_bind, 111179.xyz'

  CALLING function, dom: 'restart_bind, not a dom function'
    restart function succeeded?

  CALLING function, dom: 'sync_secondary_virtusers, 111179.xyz'
    restart function succeeded?

  CALLING function, dom: 'print_apply_nginx, not a dom function'
    restart function succeeded?

  ALREADY EXECUTED function, dom: 'print_apply_nginx, not a dom function'

  CALLING function, dom: 'restart_webmin, not a dom function'
    restart function succeeded?

  CALLING function, dom: 'restart_usermin, not a dom function'
    restart function succeeded?

  CALLING function, dom: 'restart_mail_server, not a dom function'
    restart function succeeded?

  ALREADY EXECUTED function, dom: 'print_apply_nginx, not a dom function'




2023-05-23T04:41:09
  CALLING function, dom: 'restart_webmin, not a dom function'
    restart function succeeded?
```

**Comment by jcameron** [comment]
I forgot to mention - you will need to run `/etc/webmin/restart` after applying that patch for it to take effect for operations done in the UI.

**Comment by johnheenan** [comment]
I have found the answer to the issue and it is very simple. The solution is also very simple.

During server creation only two fastrpc.cgi calls are made to the slave server. One is to establish a session and the other is to call the create_slave_zone function. That is it. Also, the zone file is created and left empty.
```
# Create the slave file, so that BIND can write to it
if ($file) {
	my $ZONE;
	&open_tempfile($ZONE, ">".&make_chroot($file), 1, 1) || return 4;
	&close_tempfile($ZONE);
        &set_ownership(&make_chroot($file));
	}
```
There is no bind restart instruction issued to slave servers.

This behaviour is consistent with all the observations listed above.

There are two solutions.

1) Don't issue a bind restart on the master server until after the empty zone file on slave servers have been created, so as slave servers will not ignore notify messages from the master server.

2) Issue a bind restart on slave servers.

The first solution needs to be tested.

The second solution is not ideal as it needs a full reload instruction instead of just a zone reload instruction. 

Normal procedure is to fill in a slave zone file in full and just issue a zone reload instruction (such as `rndc reload 111179.xyz`) after the master is operational for the zone.

**Comment by johnheenan** [comment]
**Fixed by editing one line!**

Having examined the source code more closely I see there is code to restart bind on slaves.

I made a change to one line in the `restart_on_slaves` function in file `/usr/libexec/webmin/bind8/bind8-lib.pl`

The change is from 
`next if (%on && !$on{$slave->{'host'}});`
to 
`next if (%on && !$on{$slave->{'nsname'}});`

That is change letters `host` to `nsname`.

After this there were a lot more calls to `fastrpc.cgi` with server creation and the zone file was no longer a zero byte file on slave servers.

I can't find a public repository for the virtualmin bind8 module so I cannot put up a PR.
`

**Comment by chris001** [comment]
@johnheenan 
It occurs on 2 different lines.
The line of code you're looking for is here:
1. https://github.com/webmin/webmin/blame/1f28b054fe5c33a5593606563276a38bc4f33cf6/bind8/bind8-lib.pl#L3025
2. https://github.com/webmin/webmin/blame/1f28b054fe5c33a5593606563276a38bc4f33cf6/bind8/bind8-lib.pl#L3068
The second one is the most recently changed.

**Comment by jcameron** [comment]
Amazing, thanks for the fix!!
