### ISSUE TITLE
Disabling and re-enabling Apache website feature: Doesn't include `autodiscover` records

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#566]
Jamie,

Disabling and re-enabling _Apache_ website feature, doesn't included expected `autodiscover` records, however toggling _Mail_ feature does.

**Comment by jcameron** [comment]
Ah that sounds like a bug. Was the disable / enable done using the UI or the CLI?

**Comment by iliajie** [comment]
> Ah that sounds like a bug. Was the disable / enable done using the UI or the CLI?

This happens when trying both, UI and CLI.

**Comment by jcameron** [comment]
Do the autodiscover Apache configs get added by default when creating a new domain?

**Comment by iliajie** [comment]
> Do the autodiscover Apache configs get added by default when creating a new domain?

Yes, but only if _Mail_ feature was also enabled.

Anyway, check this patch https://github.com/virtualmin/virtualmin-gpl/commit/791d480a647dfa102346a2db254f91aa22b694d8, it works for me. Does it look alright for you?

**Comment by jcameron** [comment]
Looks good, thanks!

**Comment by iliajie** [comment]
> Looks good, thanks!

Great!
