### ISSUE TITLE
Default Services SSL Certificate: MariaDB not copied

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#571]
Hey, Jamie!

After we setup to **Use this SSL certificate as the default in ....** all looks good. However, if you update the SSL certificate (I used **Update Certificate and Key**  tab) then MariaDB certificate alone is not getting updated, while all other services are updated just fine. For example, this is how the button looks like in UI after certificate update:

<img width="575" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/ba4a3f4e-b2cd-4215-966e-d19bc3c9a2ce">

📝   To be clear, clicking this button makes things work as expected, the problem is that it's not getting updated automatically, as in other services.

**Comment by jcameron** [comment]
I see the bug that causes this, and just checked in a fix for it.

**Comment by iliajie** [comment]
Great, thanks! It works as expected now!
