### ISSUE TITLE
remote.cgi returns error to clients using openssl 3.0.x

### ISSUE THREAD

**Issue by johnheenan** [virtualmin/virtualmin-gpl#574]
The behaviour below is stopping me from upgrading a server from Rocky 8 to Rocky 9.

**Server** 1 runs Virtualmin and Nginx on Rocky 8 with a Openssl 1.1.1k (`openssl version`), Nginx uses this library (`nginx -V`) and as far as I am aware so does virtualmin (with Net::SSLeay).

**Client 1** has openssl 3.0.3 and curl uses this version of the Openssl library. Using curl for a ssl call to remote.cgi on virtualmin always terminates with line
```
curl: (56) OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0
```
Also, a web server on client 1, acting as a CLIENT, uses libcurl (and so the Openssl library) to make remote API calls to virtualmin, through remote.cgi, also fails.

The fact that the command through remote.cgi completes successfully is immaterial because the server acting as a client thinks the command was unsuccessful.

Oddly, calls using curl from this client to the nginx server with ssl do not terminate with the above error, despite nginx using the same Openssl library as Virtualmin.

Another client with openssl 3.0.7 showed same behaviour. 

**Client 2** has openssl 1.1.1k (such as another server making client calls to another Virtualmin server). There is no problem using curl or with a web server making client API calls to Virtualmin on Server 1.

Rocky 9 uses openssl 3.0.x. So a server with Rocky 8 cannot make Virtualmin remote.cgi calls to a server with Rocky 9.

A search on the Internet did not provide satisfactory answers. The fact that nginx is not affected shows that the usual answer of an incompatibility due to a tightening of standards with Openssl is not correct.

I have tried looking for configuration tweaks in miniserv.conf (Webmin, Webmin, Webmin Configuration). No solutions so far.

Can configuration adjustments be made to stop this fault? Such as miniserv explicitly closing a connection at the right time according to some standards, just for remote.cgi calls. Can an explicit close be added into remote.cgi to fix this? Such as can something be passed back to miniserv.pl from remote.cgi instructing miniserv to close the connection in a particular way?

**Comment by jcameron** [comment]
This could be a bug in the way Webmin's webserver uses the OpenSSL library. 

Do you only see this issue when a Rocky 8 system calls Rocky 9, but not for calls from 9 to 9 ?

**Comment by johnheenan** [comment]
I have just finished firing up a Rocky 9 server with a Virtualmin gpl install.

On a server with Rocky 9 (not Virtualmin) making a curl client call to remote.cgi on Virtualmin with Rocky 9 (the above server) the same curl error is generated. Both Rocky 9 servers have OpenSSL 3.0.7 libraries.

Expanded results:
Rocky 8 curl to Rocky 8 virtualmin remote.cgi call: SUCCESS
Rocky 8 curl to Rocky 9 virtualmin remote.cgi call: SUCCESS
Rocky 9 curl to Rocky 8 virtualmin remote.cgi call: FAILURE
Rocky 9 curl to Rocky 9 virtualmin remote.cgi call: FAILURE

Rocky 8 has openssl 1.1.1k. Rocky 9 has openssl 3.0.7

So, it only matters what version of the OpenSSL library is on the client to make a call with curl as to whether the curl call is regarded as succeeding or not.

So yes, altering the way Webmin's webserver uses the OpenSSL library to satisfy the pickier OpenSSL 3.0.x on the client side looks promising.

**Comment by jcameron** [comment]
OK I see the bug that causes this now - the fix is here https://github.com/webmin/webmin/commit/e552c68f7ee6ec530acbce641178aef8c2144e20 , and will be included in the next Webmin release.

**Comment by johnheenan** [comment]
Thanks!
