### ISSUE TITLE
New Virtual Server User - Security Issue

### ISSUE THREAD

**Issue by mdowais** [virtualmin/virtualmin-gpl#576]
Hello.

When i create a Virtual Server, a new User is created. And, I can login using SSH or using the webmin panel. 

I discovered that, this new user has access to sensitive parts of the configuration. The user account can read Bind Config in /etc/bind/named.conf.local and  /var/lib/bind/aaa.hosts. 

This posses a threat to other virtual servers, as the configuration of others is also exposed. Likewise, i am able to guess quite a few sensitive configs, which the user may have read access.

How do i prevent this?

**Comment by iliajie** [comment]
Hello,

> How do i prevent this?

You could enable jail for the domain, e.g.:

<img width="1193" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/bc446687-62a0-4db4-a540-c934099c9dd0">

**Comment by jcameron** [comment]
No, but we don't consider it a security risk that owners of one domain can read config files like named.conf, as all DNS records can be looked up externally anyway..

**Comment by chris001** [comment]
Owners of one domain shouldn't be able to easily read BIND config files, because then they could see what are the other domains on the same physical server.  A malicious domain owner or domain user could then easily do a DoS attack from inside their domain account on the server, in order to cause the targeted domain's users, on the same server, to experience outages.

**Comment by jcameron** [comment]
Unfortunately there are plenty of ways to figure out what other domains are hosted though, even in a chroot. For example by looking at running processes..

That said, we do recognize that some Virtualmin users do want this extra security which is why we offer the chroot jail feature. You can make it the default for new domains at System Settings -> Server Templates -> Default Settings -> Administration user -> Chroot jail new domain Unix users

**Comment by chris001** [comment]
Would this `chroot jail new domain Unix users`, totally prevent each and every `new domain Unix user` from being able to do some detective work, browse the folder tree, and the bind config files, and discover the other domains on the same physical server?

**Comment by mdowais** [comment]
@chris001 Yes, I have tried it, and it is safer that way. I know that there are a few caveats as @jcameron has mentioned, but I think from a security stand point, the data disclosed is ok and the jailed user will not be able to perform any critical issue, compromising the safety.

And, @jcameron, I dont think it would be safe to allow other site owners to access the configurations and other files without a proper cause. Usually, when a website is compromised or SSH is compromised, automated tools do try to find loopholes to escalate their ways and send Spam Emails, act as a DDOS Agent, etc... And if it was targeted attack, I could think of various ways, example : a shell upload would be catastrophic, access to configs of Bind9 can cause Critical Informational Disclosure of other users, which can disclose all subdomains, leaking IP address and a whole new bunch of security issues.

I propose a request here, In the initial setup of virtualmin, there could be an option explaining security issues and whether the Chroot Jail be enabled by default while creating a virutal servers.

**Comment by iliajie** [comment]
> Would this `chroot jail new domain Unix users`, totally prevent each and every `new domain Unix user` from being able to do some detective work,

I think you could still do "detective work" in _chroot_ using some files,  i.e. `/etc/passwd` file.

> will not be able to perform any critical issue, compromising the safety.

Despite of using _chroot_ for virtual server or not, standard Unix permissions still apply and won't let compromise other user's saft

**Comment by jcameron** [comment]
I suppose we could ask during initial setup whether to enable chroot or not. However, not all functionality works in a chroot (because not all binaries are included), so this might lead to a worse user experience.

**Comment by shoulders** [comment]
my thoughts would be, what does cPanel do, and then do that.

**Comment by iliajie** [comment]
> my thoughts would be, what does cPanel do, and then do that.

Definitely not!

**Comment by mdowais** [comment]
Chroot Jail has solved the issue which I was concerned about, and thus i am closing this issue.

Thank you all.
