### ISSUE TITLE
Disk Usage Home Directory tab isn't showing disk usage of subdirectories

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-gpl#579]
A domain owner user could be forgiven for thinking a page named "Disk Usage" would show the disk usage of their home directory in the "Home Directory" tab, but that's not what we're actually showing...we're showing quota usage for the domain owner user, which excludes all of the domain's users disk usage (but those files are in the domain's home and consume the domain's group quota, so they matter to the domain owner user). Edit: I don't actually know what we're showing in the home directory tab, as it shows an empty `public_html`, too, and that would be in the quota for the domain owner user.

Making it actually show disk usage would solve this. Or, making it labeled in a way that makes it clearer what kind of usage is being shown might also solve it (but I think users really want a way to see their usage, it comes up a lot). Showing group usage, either instead of, or in addition to, owner usage, is probably the quickest solution. And, doesn't introduce a slow `du` call or whatever, since reading either user or group quotas is very fast.

See thread for more discussion: https://forum.virtualmin.com/t/virtual-server-show-incorrect-disk-usage/121394/1

**Comment by jcameron** [comment]
Ok, I'll take a look at improving this page...

**Comment by jcameron** [comment]
I think that domain owners don't care in practice about the separation between files owned by the domain owner, and files owned by domain's group (because the latter will include the former). I think the right answer is to just show usage by sub-directory under the domain's home, regardless of Unix user ownership.

**Comment by swelljoe** [comment]
I think that's right. Domain owners (and root users) probably want to see, at a glance, how much data is in the home directory, including all the subdirs. Anything that contributes to the domain quota usage, including users in the domain.

**Comment by jcameron** [comment]
Ok I've updated this page in the latest set of commits to be more useful (hopefully)
