### ISSUE TITLE
Have a way to indicate default setting, and reset it.

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#580]
This is a feature that has existed in Tiki Wiki CMS Groupware for a long time. So I proposed to add to Cypht Webmail and it was also implement.

It is explained in detail here, with screenshots: https://github.com/cypht-org/cypht/issues/399

This is related, but different than https://github.com/virtualmin/virtualmin-gpl/issues/555

**Comment by iliajie** [comment]
Upcoming Webmin and Usermin releases come with great amount of mail related improvements!

**Comment by marclaporte** [comment]
I look forward to trying them out!!

**Comment by iliajie** [comment]
It's all already available in nightly builds. Note that unless it's a new Webmin/Usermin install, you would need to manually switch in module configuration to read and reply mail with HTML, and also switch the new _fetch images using server_ option to _yes_.

**Comment by marclaporte** [comment]
After discussing with Ilia, I am closing this issue. In the context of Virtualmin, it is quite tricky because we don't know the default values coming from the distros (compared to Tiki and Cypht where defaults are set by the app).
