### ISSUE TITLE
When a setting change is made via the GUI, the service should restart so the setting takes effect immediately

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#581]
It could also be a button to click like "Reload service for settings to go live"

![2023-06-29_205915](https://github.com/virtualmin/virtualmin-gpl/assets/1004261/db4b65a6-4085-4398-8c57-a264e43d6ca9)

Related:

- https://github.com/virtualmin/virtualmin-gpl/issues/555
- https://github.com/virtualmin/virtualmin-gpl/issues/580

**Comment by iliajie** [comment]
Marc, the new options are already applied automatically upon saving that page you mentioned.

**Comment by marclaporte** [comment]
@iliajie I tested again on Debian 11, latest Virtualmin and the setting change is not applied automatically.

**Comment by iliajie** [comment]
I have tested it in PHP-FPM mode and `zlib.output_compression` option. After applying it in Virtualmin UI, I see the immediate change when running `phpinfo()`.

Marc, how exactly are you running your tests? Are you sure that you're testing it against the right domain, and/or the right/expected domain is being served by the webserver?

**Comment by marclaporte** [comment]
I use Tiki Check to validate if a PHP environment is healthy:
- https://gitlab.com/tikiwiki/tiki/-/blob/master/tiki-check.php
- https://doc.tiki.org/Server-Check

I am sure I am testing against the right domain. I sent you a video in private so you can see the sequence. 

Thanks!

**Comment by iliajie** [comment]
> I use Tiki Check to validate if a PHP environment is healthy

Do you get the same result if you use **Server Configuration ⇾ PHP Options** page, e.g.:

<img width="412" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/a9784783-6ca4-42bd-a88b-6c6faf82ccd6">

**Comment by marclaporte** [comment]
That link leads me to HTTP/1.1 404 Not Found

**Comment by marclaporte** [comment]
Looking at phpinfo() via another way, I get the same result:

![Animation-php-ini-reload](https://github.com/virtualmin/virtualmin-gpl/assets/1004261/aff33209-f678-4b50-b015-52cdfe92509f)

**Comment by iliajie** [comment]
I don't see this issue happening with properly configured virtual server. Can I have access to this server where you're seeing this issue?

**Comment by marclaporte** [comment]
Sent via chat. Thank you!

**Comment by marclaporte** [comment]
After re-installation of Virtualmin or the [WikiSuite wrapper](https://gitlab.com/wikisuite/wikisuite-packages) by @domeshow, the problem is not seen anymore, so closing.

**Comment by iliajie** [comment]
Thanks for the feedback, Marc!
