### ISSUE TITLE
"Favorites" bookmarking feature should target the feature, rather than the feature in a specific server/domain

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#587]
In VirtualMin 7.7, it seems the ★ functionality (create a Favorite) in Virtualmin is currently unintentionally per-domain (i.e. per server/sub-server/alias; it adds `?dom=somebignumber` at the end of the favorite's URL, but doesn't reveal that explicitly), instead of global for the user...

As a result, if you have a bunch of websites/subdomains/aliases and just want to have a Quick Access to some of the menu items you use the most (or that you keep forgetting about) "without having to remember exactly how it's called", particularly for configuring the same multiple things across several vservers… the current system prevents you from choosing your server first and _then_ accessing the favorite as a shortcut, because the favorite is "that feature, but in another server", so you get thrown back to the other server's config page for that feature. It's just adding extra clicks and, if you are not careful, potential mistakes (because you might be accidentally editing the config of another server you were previously looking at when you created the Favorite).

Other unfortunate side-effects of this bug include:
* If you had favorited a config page (ex: "Change Domain Name") while on vserver X, when you visit the same "Change Domain Name" config page on vserver Y, the favoriting star button is not activated (it's empty)...
* ...then if you star/favorite it again, and go into the ★ favorites quick access menu at the bottom of the sidebar, you will see two identically-named favorites ("Server Configuration -> Change Domain Name" in both cases)

When loading the favorite without a specified domain name, it should load it for the currently selected vserver in the sidebar (or if you are not in the Virtualmin tab and you are in the Webmin,  then I guess it should select the feature for the last visited/edited server)

**Comment by iliajie** [comment]
The summary of all that was said is (correct me if I'm wrong):

>  favorites should load based on the currently selected product/virtual-server in the sidebar or the last visited/edited server if not in the Virtualmin tab.

If so, I don't really agree that it should.
