### ISSUE TITLE
When opening a server's configuration feature page in a new browser tab, the sidebar UI is absent

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#588]
In VirtualMin 7.7, if you use the mouse's middle-click to open any item in the sidebar's menus, or middle-click on a server's name in the "List Virtual Servers" page, the web browser will open the page in a new tab, which is great for multitasking. However, that new tab opens with only the _contents_ of the configuration page, without the sidebar menu available to be able to switch between vservers, or from one config page to another. I would rather expect the UI to remain the same when opening a new tab, i.e. with the presence of the sidebar.

**Comment by jcameron** [comment]
Can you attach a screenshot of what you're seeing? This shouldn't happen with the default (Authentic) theme..

**Comment by nekohayo** [comment]
Note that while the screenshot shows [GNOME Web](https://apps.gnome.org/app/org.gnome.Epiphany/) exhibiting the issue, I tested primarily on Firefox, the same issue happens across both browsers.

**Comment by iliajie** [comment]
The first assumption I have is that the theme isn't aware of the middle click. What is it anyway? Do you mean scroll-wheel click?

Nevertheless, there other are many ways of doing what you're trying to do:

  1. _right-click_ on the menu switch (at the very top of the navigation menu) to open a new tab
  2. hold `Ctrl` key while clicking the link in the menu 
  3. Use key-combo `Ctrl+Alt+D` to clone current page to the new tab (available only in nightly builds so far)

**Comment by nekohayo** [comment]
> What is it anyway? Do you mean scroll-wheel click?

Exactly!

> right-click on the menu switch (at the very top of the navigation menu) to open a new tab

That's quite an easter egg :)  I actually had thought of using right-click, but _on the individual menu items_ (not on the menu top tab itself), to open them in a new tab (or window) without scrollwheel-middle-click:

![image](https://github.com/virtualmin/virtualmin-gpl/assets/479401/47e045ce-c1b3-4417-9adc-94d9a9c25369)

...however this does not work either. When opening a menu item's link using that right-click menu, it

Ctrl+click indeed works as a workaround, though that's a lesser known feature of web browsers, too.

**Comment by iliajie** [comment]
Besides, some users use it the way it is now to open the module without the left menu ...

**Comment by iliajie** [comment]
I will close this, as opening new tabs and preserving the left menu using the middle click is now supported.
