### ISSUE TITLE
Migrating from cPanel, DNS does not migrate

### ISSUE THREAD

**Issue by geoffoliver** [virtualmin/virtualmin-gpl#59]
When I migrate a cPanel backup (using the command line or the web UI), none of the DNS entries are created. I have verified the zone file is present in the backups (in `dnszones/{domainname}.db`) but  `migration-cpanel.pl` does not appear to check for that file. Instead it is expecting to find DNS zone info in a daily backup in a file called `_var_named.tar.gz`.

The backup was generated using standard "Backup" feature in cPanel 11. I don't see any options for running a "daily backup" or anything else... It's pretty basic. Which is why I'm migrating a bunch of sites from cPanel to Virtualmin :-)

**Comment by plan8studios** [comment]
Yeah, that'd be OK. How would you like to get the file? I've got one here that's 116.4MB that I know has a lot of custom DNS entries.

**Comment by jcameron** [comment]
Can you make it available for download via HTTP or FTP?

**Comment by plan8studios** [comment]
Yep. Can I email you a link at jcameron@webmin.com?

**Comment by qlpqlp** [comment]
hello, is there any temporary fix for this?

**Comment by rostovtsev** [comment]
@qlpqlp What is your Virtualmin version? This thread is over one year old, the fix should have been added already.

**Comment by qlpqlp** [comment]
Hello :)

Here you go:

Versão Webmin: 1.930
Versão Virtualmin: 6.07
CentOS Linux: 7.7.1908
Versão Usermin: 1.780
Authentic theme version: 19.40-beta1-11

Like the user plan8studios , says, the migration script dosent check the correct folder for the DNS zones that are located in dnszones/{domainname}.db
