### ISSUE TITLE
In small-width portrait mode, automatically show the sidebar when mouse hovers the left margin, and auto-hide when needed

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#590]
In VirtualMin 7.7, in screens at 1080px wide and smaller, the sidebar is hidden by default, activatable in a "hamburger" menu. It works, but it's a bit cumbersome.

The page contents have a fairly thick margin on the sides, so this gives me an idea: it would be nicer if, in addition to the presence of the hamburger menu telling users they can access the menu in that area, the sidebar would, on desktop computers:
* Automatically show up when the mouse cursor is within the left margin (~10 pixels or so?), since it's not conflicting with the actual contents anyway;
* Remain open as long as the user doesn't click a menu item that changes the page, or as long as the mouse cursor hasn't clicked on the page contents, or that the mouse cursor has exited to the right of the sidebar area for more than 1 second; in those cases, it could auto-hide with the slide-out animation?

That way, you save yourself the tedious clicks to turn the sidebar on/off  all the time, and it feels a lot more fluid.

**Comment by iliajie** [comment]
This feature was implemented on the latest commit, and added to the latest nightly build.

This feature is optional and should be enabled first in **Theme Configuration → Navigation Menu** page with the new **Auto open closed panels on proximity** option.

**Comment by iliajie** [comment]
Did you have a chance to test the new feature?

Also note that you can open navigation menu using `Alt+A` hotkey ..
