### ISSUE TITLE
Postfix config broken on certificate renewal if using Default Services Certificate

### ISSUE THREAD

**Issue by BabelhalSupport** [virtualmin/virtualmin-gpl#591]
We have a Virtual Server sam.babelhal.hu. Under Server Configuration / SSL Certificate menu, we clicked the **Set as Default Services Certificate** button. After this, we see: 

Used by services | Webmin (sam.babelhal.hu), Dovecot (host sam.babelhal.hu), Dovecot (global), Postfix (global)

but next to the **Remove SSL Certificate from Services** button it shows only: 

Remove this SSL certificate for requests to this domain in Webmin and Dovecot
(Postfix is missing)

In our Postfix master.cf file, we have two smtps lines bound to specific IP addresses.
It seems so, that the Virtualmin autodetection does not recognise this.
This would be only a minor issue, but on certificate renewal Virtualmin adds a new line to the end of the master.cf file.
The new line make the Postfix config invalid and when Virtualmin tries to restart Postfix, it fails.

Please fix this issue.

Screenshots attached:
<img width="1052" alt="Screenshot 2023-07-13 at 9 08 05" src="https://github.com/virtualmin/virtualmin-gpl/assets/47210647/e40fcf6d-84b1-43d8-a1d1-e268203795e7">
<img width="1710" alt="Screenshot 2023-07-13 at 9 11 07" src="https://github.com/virtualmin/virtualmin-gpl/assets/47210647/bee526a1-e07e-4528-ba7a-30dd1fbb6161">
<img width="1711" alt="Screenshot 2023-07-13 at 9 11 38" src="https://github.com/virtualmin/virtualmin-gpl/assets/47210647/58f23980-b647-4661-a8fb-4f74d630a5bb">

**Comment by iliajie** [comment]
Hello,

Could you tell more about how you installed Virtualmin? What Webmin and Virtualmin versions you're currently running and on which OS?

**Comment by BabelhalSupport** [comment]
Hello,

Originally we have installed Virtualmin with the official install.sh script on May 18  2015 on Debian 8.
Since then our system is upgraded to Debian 9-10-11.

Debian	11.7
Webmin version	2.021
Virtualmin version	7.7
Authentic theme version	20.22

**Comment by jcameron** [comment]
Is that IP in the Postfix config a private IP that is used only by the `sam.babelhal.hu` domain?

**Comment by iliajie** [comment]
But Virtualmin already should be able to understand the old format, when private IPs were used to send mail from specific domain? I mean that Virtualmin should work equally well with both the config OP exampled and when this feature enabled on **Server Configuration ⇾ Email Settings** page with **Send outgoing email for domain from IP** option, right?

**Comment by jcameron** [comment]
Yes, it should support both cases. However, it will only recognize a Postfix config that uses an IP if the IP isn't used by any other domain (meaning it's private, not shared)

**Comment by BabelhalSupport** [comment]
> Is that IP in the Postfix config a private IP that is used only by the `sam.babelhal.hu` domain?

Our case is slightly complicated (see attached master.cf). We bound 3 different IP addresses to mailing protocols. The first one is 127.0.0.1 SMTP used only internally, the second one is 79.172.209.127 and has multiple protocols(SMTPS; SMTPS; SUBMISSION) used for general mail delivery, the last one is 79.172.209.36 SMTPS used for newsletter sending.

127.0.0.1 and 79.172.209.127 IPs are shared with other services (Apache2; Dovecot; MySQL; etc...) and some domains (puchner.hu; elmenybirtok.hu; etc...)
79.172.209.36 IP is dedicated for mass mail delivery

**Comment by BabelhalSupport** [comment]
> But Virtualmin already should be able to understand the old format, when private IPs were used to send mail from specific domain? I mean that Virtualmin should work equally well with both the config OP exampled and when this feature enabled on **Server Configuration ⇾ Email Settings** page with **Send outgoing email for domain from IP** option, right?

I don't understand what do you mean under "old format"? That I know, protocols IP prefixes are not obsolete (supported by Postfix from beginning). In our case, the "Send outgoing email for domain from IP" is set always to "System's default address".

**Comment by iliajie** [comment]
> I don't understand what do you mean under "old format"?

I referred internally to Virtualmin.

> In our case, the "Send outgoing email for domain from IP" is set always to "System's default address".

I wonder, would that work for you correctly if you just used Virtualmin option **Send outgoing email for domain from IP** to configure it?

Also, could you share your Postfix config files in plain text? You can drag and drop them as zip archive ..

**Comment by BabelhalSupport** [comment]
> I wonder, would that work for you correctly if you just used Virtualmin option **Send outgoing email for domain from IP** to configure it?

We have never tried. "Send outgoing email for domain from IP" offers only "Virtual server's address 79.172.209.127".

> Also, could you share your Postfix config files in plain text? You can drag and drop them as zip archive ..

[postfix_cf.zip](https://github.com/virtualmin/virtualmin-gpl/files/12049928/postfix_cf.zip)

**Comment by jcameron** [comment]
The IP used for outgoing email is completely separate from the IP used for incoming email (which the SSL cert is attached to). So it won't make any difference if you change the "Send outgoing email for domain from IP" option.

On your system, how many domains are using the IP 79.172.209.127 ?

**Comment by iliajie** [comment]
> The IP used for outgoing email is completely separate from the IP used for incoming email (which the SSL cert is attached to)

Duh, as those are used for incoming mail (which I completely forgot about as the last time I configure those manually was about 10 years ago), then what is the point of configuring it at all, because all contemporary Postfix versions support SNI and Virtualmin sets SSL certificate to be used for incoming connections already anyway, right?

**Comment by jcameron** [comment]
The way Virtualmin works currently, if a domain has a private IP that no other domain uses, Postfix will be configured to use that cert for all SMTP connections to that IP. It only depends on the SNI feature of Postfix if a domain doesn't have a private IP.

**Comment by iliajie** [comment]
> It only depends on the SNI feature of Postfix if a domain doesn't have a private IP.

Perfect!

**Comment by jcameron** [comment]
There may still be a bug here though. @BabelhalSupport can you post a screenshot of the page at Server Configuration -> Change IP Address for the domain sam.babelhal.hu ?

**Comment by BabelhalSupport** [comment]
> On your system, how many domains are using the IP 79.172.209.127 ?

del-dunantuli-programok.hu	
hagyomanyorzo-lovagrend.hu	
puchner.hu	
puchnerbirtok.hu
puchnerhotel.eu
elmenybirtok.hu	
sam.babelhal.hu

**Comment by BabelhalSupport** [comment]
> There may still be a bug here though. @BabelhalSupport can you post a screenshot of the page at Server Configuration -> Change IP Address for the domain sam.babelhal.hu ?
<img width="1270" alt="Screenshot 2023-07-17 at 9 37 39" src="https://github.com/virtualmin/virtualmin-gpl/assets/47210647/080e5aec-83bc-42bd-a9e8-d822672bef11">

We don't use dedicated IP addresses for general purpose, only for mass email sending (mail2.puchner.hu 79.172.209.36)

**Comment by BabelhalSupport** [comment]
If Virtualmin does not recognise the Postfix config, it should not change it.

**Comment by BabelhalSupport** [comment]
Additional info: In the IP address list, i don't see the secondary address (79.172.209.36).
Are subinterfaces also supported?

The output of command
`# ip address`

2: eth0@if23: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 76:99:99:4a:5f:e1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 79.172.209.127/24 brd 79.172.209.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 79.172.209.36/24 brd 79.172.209.255 scope global secondary eth0:1
       valid_lft forever preferred_lft forever

**Comment by jcameron** [comment]
Subinterfaces are supported, as long as they show up at Webmin -> Networking -> Network Configuration -> Network Interfaces.

**Comment by BabelhalSupport** [comment]
> Subinterfaces are supported, as long as they show up at Webmin -> Networking -> Network Configuration -> Network Interfaces.

Yes, all interfaces are listed.
<img width="1208" alt="Screenshot 2023-07-18 at 8 48 16" src="https://github.com/virtualmin/virtualmin-gpl/assets/47210647/40fad3e2-d015-45cf-982f-fd4bd04e0d86">

**Comment by iliajie** [comment]
> Additional info: In the IP address list, i don't see the secondary address (79.172.209.36).
> Are subinterfaces also supported?

@BabelhalSupport We've been working recently on fixing a few issues for that matter. You could try applying [this patch](https://raw.githubusercontent.com/webmin/webmin/1a807f5f5886e16145ac0d85423b672539902c7f/net/linux-lib.pl) and see if that helps in any way?

**Comment by BabelhalSupport** [comment]
We have applied the patch (replaced the file /usr/share/webmin/net/linux-lib.pl).
After this, all the original problems are still there:
1. The secondary IP address is missing from the dropdown at Server Configuration/Change IP Address
2. The secondary IP address is also missing at Server Configuration/Email Settings -> Send outgoing email for domain from IP
3. Service certificate renewal still breaks Postfix master.cf

**Comment by iliajie** [comment]
> 1. The secondary IP address is missing from the dropdown at Server Configuration/Change IP Address

Why would you expect it to be in the drop down? If you have a private IP for the virtual server, just add it using **Use dedicated address** radio, right below the **Shared address** dropdown.

> Service certificate renewal still breaks Postfix master.cf

Most probably because Virtualmin isn't aware of the IP address of that server.

**Comment by chris001** [comment]
> Yes, it should support both cases. However, it will only recognize a Postfix config that uses an IP if the IP isn't used by any other domain (meaning it's private, not shared)

Postfix 3.4+ supports SNI = as little as one shared IP address can serve many different domain SSL certs.

Postfix version 3.4+ (released Feb 2019) supports SNI and it's therefore available in Ubuntu 19.10+ and Debian 10+ (released July 2019), for example.

Also, there IS a good reason to enable SNI by default - mail app clients such as Outlook attempt autoconfiguration using a servername that matches the email domain name.  If your mail account is at Gmail or another shared domain this is not a problem as Gmail has SNI enabled so autoconfig will succeed, but a personal domain hosted on a Virtualmin virtual server, with multiple other virtual servers/domains, needs SNI, so that each request for a domain name will receive back the correct domain cert. and succeed

See: [Postfix SNI documentation](https://www.postfix.org/postconf.5.html#tls_server_sni_maps).

How to config Postfix SNI, for all mail enabled domains on a virtualmin server:

Step 1: Comment out the top two lines and add the following lines to `/etc/postfix/main.cf`:
```
        # smtpd_tls_cert_file = /etc/pki/dovecot/certs/dovecot.pem
        # smtpd_tls_key_file = /etc/pki/dovecot/private/dovecot.pem
    
        #
        # The indexed SNI table must be created with "postmap -F", see Step 2 below.
        #
        indexed = ${default_database_type}:${config_directory}/
        tls_server_sni_maps = ${indexed}tls_server_sni_maps.map
```

Step 2: Create the file `/etc/postfix/tls_server_sni_maps.map` with the following:
```
        # Run postmap -F hash:/etc/postfix/tls_server_sni_maps.map 
        # when adding/renewing any cert!
        # One host per line

        # The example.com domain has both an RSA and ECDSA certificate
        # chain.  The chain files MUST start with the private key,
        # with the certificate chain next, starting with the leaf
        # (server) certificate, and then the issuer certificates.
        #
        example.com /etc/postfix/sni-chains/rsa2048.example.com.pem,
                    /etc/postfix/sni-chains/ecdsa-p256.example.com.pem
        #
        # The example.net domain has a wildcard certificate, and two
        # additional DNS names.  So its certificate chain is also used
        # with any subdomain, plus the additional names.
        #
        example.net /etc/postfix/sni-chains/example.net.pem
        .example.net /etc/postfix/sni-chains/example.net.pem
        example.info /etc/postfix/sni-chains/example.net.pem
        example.org /etc/postfix/sni-chains/example.net.pem

        # add more domains as needed, one host per line.
```

Step 3: Run `postmap -F hash:/etc/postfix/tls_server_sni_maps.map` for the first time.

Step 4: Run `systemctl restart postfix` so postfix will start to use the SNI map.

Step 5: Super important!  Test the domains' SNI is working and serving the matching TLS cert for the domain!  For each of the domains, run the following command: 
`openssl s_client -connect localhost:25 -servername mail.mydomainname.com -starttls smtp`

Step 6:
For those who don't know, the server software must run the command to rebuild the SNI table each time a certificate changes!  Why?  The underlying table is generated with `postmap -F` which imports the cert file contents (it does not just store references to the file names).
After each successful certificate request, or renewal, Virtualmin must run this command:
`postmap -F hash:/etc/postfix/tls_server_sni_maps.map`

**Comment by jcameron** [comment]
FYI, Virtualmin should setup Postfix SNI for new domains by default, as long we you're running at least version 3.4.

**Comment by BabelhalSupport** [comment]
If we set up SNI in Postfix then the renewal of Service Certificate will not break the Postfix master.cf anymore?

**Comment by jcameron** [comment]
Yes, that's correct

**Comment by chris001** [comment]
Would be nice to auto enable SNI on existing Postfix domains where it's not enabled.  Since enabled by default is the way.

And, any mail domain with a dedicated IPv4 or IPv6 for its `MX` address handled by Postfix not externally by a third party mail service, then Postfix should be configured to send mail out from that dedicated IPv4 or IPv6.

**Comment by jcameron** [comment]
Recent versions of Virtualmin should enable Postfix SNI by default for new domains. However, you can go back and enable it for existing domains on the Manage SSL Certificate page, or with a shell command like : 

`virtualmin install-service-cert --domain whatever.com --service postfix`

**Comment by BabelhalSupport** [comment]
> However, you can go back and enable it for existing domains on the Manage SSL Certificate page

We don't see this page. Where should it be?
In our Postfix config SNI map is not defined.
Is this required to show the "Manage SSL Certificate page"?

**Comment by BabelhalSupport** [comment]
> Yes, that's correct

We have configured SNI mapping in Postfix and added sam.babelhal.hu to the map.
Then we requested a new certificate for sam.babelhal.hu and Postfix master.cf config file broke again.
By the domain configuration under SSL Certificate we saw:

`Used by services: Postfix (global)`

We clicked the "Copy SSL Certificate to Services" button and then we saw:

`Used by services: Postfix (global), Postfix (host sam.babelhal.hu)`

The renewal process still broke the config.

After this we had the idea to remove the global certificate from Postfix and it worked.

**One minor issue:** 
We hade to configure the certificate for the smtp(port: 25) manually. This is needed for STARTTLS protocol upgrade.

Many-many thanks for your help!

**Comment by jcameron** [comment]
Apologies, the correct page is at Server Configuration -> SSL Certificate.

However, you do need to do setup an SNI map in the Postfix config..

**Comment by chris001** [comment]
Would be very nice for the software to by default auto setup an SNI map in the Postfix config, and auto add all the domains to it.  Having mismatched domain and certificate should be the non-default option, that just about nobody would choose.

**Comment by jcameron** [comment]
Agreed, we should setup Postfix SNI as part of the Virtualmin install process. I'll look into this ...

**Comment by jcameron** [comment]
Ok, the next release of Virtualmin will enable SNI support automatically in the Postfix config if needed..
