### ISSUE TITLE
"Authentic" dark theme: some dropdown list items have black text on dark-gray background

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#592]
This is really a minor issue I found in the default dark theme in VirtualMin 7.7, but I guess it's worth reporting: those non-highlighted items in the dropdown list are nearly unreadable because of the black text color. I don't know if this type of widget is used elsewhere, but I noticed it in the `config.cgi?module=virtual-server` page.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/479401/3a315ba6-83a0-458d-9d6b-87ae6f4778e7)

**Comment by iliajie** [comment]
Authentic Theme 21.00 will have this and dozen of other issues solved.

You can try it already with the latest nightly Webmin builds, the links for which can be found in [webmin.com](https://webmin.com) website.

**Comment by nekohayo** [comment]
Oh thanks, I didn't know it was already fixed in the dev version :) Am I correct to presume this might end up bundled in a VirtualMin 7.8 / stable channel updates eventually, or is this 8.x material?

**Comment by iliajie** [comment]
Authentic Theme is distributed as part of Webmin. So, update Authentic Theme 21.00 will be released as part of Webmin 2.100 and Usermin 2.000.
