### ISSUE TITLE
'Apache SSL website enabled' feature uses Let's Encrypt without hint that it wil do so

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#595]
When enabling the 'Apache SSL website enabled' feature on a virtual server there is an automatic try to activate an SSL certificate via Let's Encrypt even though the [helper text](https://github.com/virtualmin/virtualmin-gpl/blob/0bec5a7161165a6fa6de85fa85c53e47149e42e3/help/ssl.html) only mentions selfsigned certificates.

While the activation process of the SSL website feature has a fallback to a selfsigned certificate, it should either be mentioned in the helper text that there will be be calls to Let's Encrypt or it should be an option to use this service.

**Comment by jcameron** [comment]
Thanks, I'll update the docs to mention this. Also, there is an option at System Settings -> Virtualmin Configuration to turn off requesting of the Let's Encrypt cert.
