### ISSUE TITLE
re-check config fail because of php_log

### ISSUE THREAD

**Issue by xxorax** [virtualmin/virtualmin-gpl#596]
The (new) default php_log file setting does not pass the config check anymore.

It stops on lororate check :
```
Current logrotate configuration is not valid :

error: stat of /home/****/logs/php_log failed: No such file or directory
```

My server template does not have specific logrotate option or PHP option, except maybe the Default PHP execution mode is FCGId.
Enable PHP logging is Yes
Default PHP log file is set to Default (logs/php_log)

I made a test :
- I created the test.test virtualserver
- I check the Server Configurration > PHP Options :  php log : it set to ` Default log file /home/test.test/logs/php_log` 
- I run the config check : ` error: stat of /home/test.test/logs/php_log failed: No such file or directory`
- I go back to the PHP Option and set php log to `  PHP logging disabled`
- I re-run the config check : it pass
- I go back to the PHP Option and re-enabled the php log to the default
- config check fail again.

**I don't think this php_log file will exists before there is PHP error, and so it will often fail.**
Maybe it needs a first ` touch ~logs/php_log` 

Workaround to make it pass the domain check, I have to, for each virtualserver :
- disable the php log
- re-run the config check and see the problem in the next virtualserver

BTW, is it not possible to keep the same log file as before, and so having all in ~/logs/error_log ?

Thanks !

**Comment by jcameron** [comment]
So the Virtualmin logrotate config should skip missing files, but it seems like in some cases this isn't happening. So in the next release we'll add a check to ensure the log is always created..
