### ISSUE TITLE
Possibly outdated Debian webmin packages or missing webmin repository config for VirtualMin?

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#599]
My apologies if this is just a case of "We're working on the packaging, be patient" and the packages simply aren't ready yet, but _in case that isn't the case_ , and the repos relocated, and there is a mismatch or something...

---

My personal test server I installed (a fresh Debian 11 x86_64) last month with VirtualMin 7.7 is currently unable to see the latest versions of Webmin (2.100) and Usermin (2.000):

![image](https://github.com/virtualmin/virtualmin-gpl/assets/479401/7a947650-1275-4dce-99d6-916cc5d892cb)

I searched through the forums, thinking "Maybe I need to do something special," and found [this thread](https://forum.virtualmin.com/t/no-longer-receiving-updates/117653) (among others) where Ilia suggests re-running the install script with the `--setup` parameter to force repositories to be reset. I thought, "I don't understand why/how it could be borked when this clean-install is not even a month old and I haven't used it more than once or twice, but OK, let's see", so I ran that command, and nope, still no updates available (as you can see further below).

Looking at the contents of https://software.virtualmin.com/vm/7/gpl/apt/dists/virtualmin/main/ I can see that there have indeed been no updates since July 10th.

Again I thought "Maybe they just didn't have time to create the new packages", but then I saw [this thread](https://forum.virtualmin.com/t/webmin-2100-update-webmin-repo-dashboard-button-not-working/121758) that mentions quite a different repository link, as can be seen in that screenshot in the thread:

![](https://cdn.forum.virtualmin.com/uploads/default/original/2X/f/fbb7f0e776aad76ecffa62e239c22c92a01b001d.jpeg)

...however, as you can see in the output below, running the install script with `--setup` yields quite a different repository.

Could it be that webmin now has standalone repositories and virtualmin (and the latest virtualmin install/setup script) never sets those up?

```
# wget https://software.virtualmin.com/gpl/scripts/virtualmin-install.sh
# chmod +x virtualmin-install.sh
# ./virtualmin-install.sh --setup

    ▣ Phase 1 of 1: Setup
    Downloading Virtualmin 7 key                                                 ✔ 
    Installing Virtualmin 7 key                                                  ✔ 
    Downloading Webmin key                                                       ✔ 
    Installing Webmin key                                                        ✔ 
    Downloading repository metadata                                              ✔ 
    Disabling cdrom: repositories                                                ✔ 
    Cleaning up software repo metadata                                           ✔ 
    [SUCCESS] Repository configuration successful. You can now install Virtualmin
    [SUCCESS] components using your OS package manager.

# apt clean
# apt update

    Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
    Hit:2 http://deb.debian.org/debian bullseye 
    Hit:3 http://deb.debian.org/debian bullseye-updates 
    Hit:4 https://packages.sury.org/php bullseye 
    Hit:5 https://software.virtualmin.com/vm/7/gpl/apt virtualmin InRelease

    Reading package lists... Done                  
    Building dependency tree... Done
    Reading state information... Done
    All packages are up to date.


# locate sources.list

    /etc/apt/sources.list
    /etc/apt/sources.list.d
    /etc/apt/sources.list.d/sury-debian-php-bullseye.list
    /etc/apt/sources.list.d/virtualmin.list
    /etc/apt/sources.liste

# cat /etc/apt/sources.list.d/virtualmin.list

    deb [signed-by=/usr/share/keyrings/debian-virtualmin-7.gpg] https://software.virtualmin.com/vm/7/gpl/apt virtualmin main

# cat /etc/apt/sources.list

    # deb cdrom:[Debian GNU/Linux 11.2.0 _Bullseye_ - Official amd64 NETINST 20211218-11:12]/ bullseye main

    #deb cdrom:[Debian GNU/Linux 11.2.0 _Bullseye_ - Official amd64 NETINST 20211218-11:12]/ bullseye main

    deb http://deb.debian.org/debian/ bullseye main
    deb-src http://deb.debian.org/debian/ bullseye main

    deb http://security.debian.org/debian-security bullseye-security main
    deb-src http://security.debian.org/debian-security bullseye-security main

    # bullseye-updates, to get updates before a point release is made;
    # see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates_and_backports
    deb http://deb.debian.org/debian/ bullseye-updates main
    deb-src http://deb.debian.org/debian/ bullseye-updates main

    # This system was installed using small removable media
    # (e.g. netinst, live or single CD). The matching "deb cdrom"
    # entries were disabled at the end of the installation process.
```

**Comment by jcameron** [comment]
The issue is that we haven't included the latest webmin package in the virtualmin repository yet. This is normal because we usually want to give it a bit more time to bake for webmin users before releasing it to virtualmin customers.. but should show up soon.

**Comment by nekohayo** [comment]
Ah OK, makes sense! Glad to know there is no mismatch issue with the repositories config files from the setup then. Presuming that is the case, I'm closing this, sorry for the false-positive :)
