### ISSUE TITLE
DMARC - missing 'mailto:' in DNS Record

### ISSUE THREAD

**Issue by andyhirsch** [virtualmin/virtualmin-gpl#60]
In server template: "Reporting URI for forensic reports: mailto:postmaster@domain" and "Reporting URI for aggregate reports: mailto:postmaster@domain" is selected but the generated DNS record is missing "mailto:" in both options.

**Comment by jcameron** [comment]
Are you sure that's required by the spec?

**Comment by andyhirsch** [comment]
https://dmarc.org/2016/07/common-problems-with-dmarc-records/
At "Bad Record Contents":

> v=DMARC1;p=none; rua=reports@XXXXXXXX.com; ruf=reports@XXXXXXXX.com
> DMARC requires that the addresses for reporting features be written as URIs, so this record should read “rua=mailto:reports@XXXXXXXX.com; ruf=mailto:reports@XXXXXXXX.com”

https://mxtoolbox.com also throws an error if the "mailto:" is missing.

**Comment by jcameron** [comment]
Thanks, I'll fix this in the next Virtualmin release.
