### ISSUE TITLE
[Feature Request] Add .git block in webserver config to block access to .git directory

### ISSUE THREAD

**Issue by naresh335** [virtualmin/virtualmin-gpl#600]
Hello Team, 
If possible, please add this block at the time of installation only to conf.d/security.conf file (ubuntu apache2 in this case)

```sh
<DirectoryMatch "/\.git">
   Require all denied
</DirectoryMatch>
```

**Comment by iliajie** [comment]
Hello,

You could use **System Settings ⇾ Server Templates: Edit Server Template / Website for domain** to add it to be used by the newly created virtual servers (domains).

**Comment by naresh335** [comment]
Hello @iliajie thanks for the response,
I already do this globally instead of doing it for every website at the time of virtualmin installation.

It was a suggestion to make virtualmin instances a bit less prone to git traversal attacks **by default** for the users who have no idea about this being a potential attack vector.

If possible, please enable it by default for both LAMP/LEMP installations, if not it would be great if a page can be added to virtualmin documentation I guess Under Get Started Section to make virtualmin installations a little more secure.
