### ISSUE TITLE
[File Manager] Increase column width and row height

### ISSUE THREAD

**Issue by ADDISON74** [virtualmin/virtualmin-gpl#603]
**Virtualmin > File Manager**

1 - On the **Size** column, the information is not fully visible. The width of the column must be increased to fit, here the longest possible string must be evaluated.

2 - Similarly on the **Modified** column, this time the height of the row must be increased.

![filemanager_window](https://github.com/virtualmin/virtualmin-gpl/assets/8360474/c691968d-b244-47cf-9609-88eafa804dcc)

**Comment by iliajie** [comment]
Thanks for the heads up!

This will be fixed in Webmin 2.101 and Usermin 2.001.
