### ISSUE TITLE
Orphan DNS record after enabling/disabling DNSSEC

### ISSUE THREAD

**Issue by ADDISON74** [virtualmin/virtualmin-gpl#604]
Go to **```Virtualmin > Server Configuration > DNS Option```** and choose **Yes** for **DNSSEC signature enabled**. Click the [Save] button.

Go to **```Virtualmin > Server Configuration > DNS Option```** and click the [Manually Edit Records] button.  After the last row related to SPF a lot of rows were added. 

Go to **```Virtualmin > Server Configuration > DNS Option```** and choose **No** for **DNSSEC signature enabled**. Click the [Save] button.

Go to **```Virtualmin > Server Configuration > DNS Option```** and click the [Manually Edit Records] button.  The row related to SPF should be the last one but there is another one after it

```domain.tld.	0	IN	NSEC3PARAM	1 0 0 -```

This one is an orphan left behind by DNSSEC.

**Comment by jcameron** [comment]
Can you attach a screenshot of the extra records?

**Comment by ADDISON74** [comment]
The line is mentioned n my post,

**Comment by jcameron** [comment]
Ok I see the cause of this now - it will be fixed in the 2.102 Webmin release.
