### ISSUE TITLE
virtualmin backups

### ISSUE THREAD

**Issue by gstlouisgit** [virtualmin/virtualmin-gpl#606]
I have this small virtualmin machine that does backups at midnight

It can barely do two backups because of limited space.  I notice that the second backup fails because of lack of space.  What I want it to do is erase the last backup and replace it with the new backup, which will be the latest.

What I noticed is that the backup script preps the tar for the new backup before it goes to check old backups to delete.  In my case this is actually a problem because of space, it halts trying to build tar with no space and does not delete the old backups.  I'm not sure if this was by design, in case the tar fails you still have the other backups.  But if not, It might be a good idea to remove the previous backup to complete the new one?

**Comment by jcameron** [comment]
I suppose this could be done, but it would be pretty risky because if we delete the old backup first and the new one fails, now you're left with nothing!

**Comment by chris001** [comment]
@gstlouisgit One way to solve this would be to set a `cron` task at 1:00 am (after the backup at midnight is done) to run a shell script to `rsync` upload the backup file to a different storage location - create another small linux server for storage only, then on success, erase the backup, to make space for the new backup, that will run at the next midnight.

**Comment by gstlouisgit** [comment]
@jcameron that is what I thought, and good logic.  I can't see that many in my situation nowadays anyway.  

@chris001 yes this will have to be the way, anyway, to eventually get a backup off site and not do it manually.  just lazy
