### ISSUE TITLE
Cloudflare DNS: Creating new domain exposes records that must be proxied

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#608]
When creating a new top-level virtual server using **Create Virtual Server** page, while default template and **Website for domain** template page has **Redirect webmail.${DOM}** and/or **Redirect admin.${DOM}** enabled (which is default) and when at the same time **DNS domain** template page has **Enable proxing on new records** set to **For all records** -- created record in Cloudflare is _still_ not proxied.

Though the main A and AAAA records are set to be proxied correctly.

**Comment by jcameron** [comment]
Checked in a fix for this for inclusion in the next release..

**Comment by iliajie** [comment]
Excellent! That fixes the problem.
