### ISSUE TITLE
FreeBSD 11: Let's Encrypt Auto Renewal not working

### ISSUE THREAD

**Issue by jwhulette** [virtualmin/virtualmin-gpl#61]
Requesting a new certificate works fine.
Auto renewals do not work even if I click the Only Update Renewal button. The page refreshes but the certificate does not update. I do not get any emails either about the Certificate expiring.

Running ` /usr/local/etc/webmin/virtual-server/collectinfo.pl` returns
Use of uninitialized value $bind8::config{"pid_file"} in split at /usr/local/lib/webmin-1.890/bind8/bind8-lib.pl line 1676.
Use of uninitialized value $bind8::config{"pid_file"} in split at /usr/local/lib/webmin-1.890/bind8/bind8-lib.pl line 1676.
Use of uninitialized value $bind8::config{"pid_file"} in split at /usr/local/lib/webmin-1.890/bind8/bind8-lib.pl line 1676.
Use of uninitialized value $bind8::config{"pid_file"} in split at /usr/local/lib/webmin-1.890/bind8/bind8-lib.pl line 1676.

Which makes sense since I have 4 SSL sites on the server. I do not have BIND installed. 

OS: 11.1-RELEASE-p11
Webmin: 1.890
Virtualmin: 6.03

**Comment by jcameron** [comment]
The "Only Update Renewal" button just changes the schedule for automatic renewals, which happen in the background when the cert is close to expiry.

**Comment by jcameron** [comment]
Did you get any email to the domain's contact address about the success or failure of the renewal?

Also, does it work if you trigger a renewal from the Virtualmin UI?

**Comment by jwhulette** [comment]
No, I get no emails at all. If I click the Request new certificate it works fine.

**Comment by jcameron** [comment]
Check the email address that's set for the domain on the Edit Virtual Server page, or the admin users' mailbox. Any failure notifications will go there.

**Comment by jwhulette** [comment]
I have check all user mailboxes and the mail log. No email notifications.
