### ISSUE TITLE
Nginx apply config error 521 when webmin runs from nginx reverse proxy.

### ISSUE THREAD

**Issue by amitsamanta996** [virtualmin/virtualmin-gpl#613]
Followed webmin faq page to setup nginx reverse proxy for webmin panel, everything works good except nginx apply configuration option and apply nginx config when creating or editing virtual server.
It shows error 521 on stats.cgi and then error 520 on restart.cgi in a error popup at the bottom.
No such error occurs when webmin opened directly on port 10000.

**Comment by jcameron** [comment]
That's not entirely surprising - if Nginx is restarted it's going to interrupt the connections proxied through it.

**Comment by amitsamanta996** [comment]
any other possible ways to fix, like it waits for the server to sends a respone after restart,  right now the ui kind of messed up after the error

**Comment by amitsamanta996** [comment]
can't use cloudflare directly on different port, there is some issues with ssl, 
cloudlfare provides the ssl, connection from cloudflare to server is on non ssl, but if webmin ssl is turned off, webmin panel tries websocket on ws://, which gets blocked by browser when cloudflare is providing ssl, and needs to connect via wss://

**Comment by jcameron** [comment]
What button in Virtualmin are you clicking currently to apply the configuration? Possibly it's doing a full restart rather than just applying the config..

**Comment by amitsamanta996** [comment]
Webmin ->servers -> Nginx Webserver ->Apply Nginx Configuration.
It's also happening when creating new virtual servers

**Comment by jcameron** [comment]
Can you post the contents of `/etc/webmin/virtualmin-nginx/config` on your system? That will show me the restart command being used ..

**Comment by amitsamanta996** [comment]
You were right, when nginx restarts or reloads connection will be broken, same thing happens when webmin is reloaded, it's expected.
The only problem is in ngnix config page after it shows 520(status code throws by cloudflare not webserver) error, the titile bar on top appears twice, so kind of small ui problem.
Sorry couldn't provide screenshot, now removed proxy and using on different port

**Comment by jcameron** [comment]
Actually it should be possible to gracefully restart Nginx without breaking connections. 

That's why I'd like to see what restart command is in `/etc/webmin/virtualmin-nginx/config`

**Comment by amitsamanta996** [comment]
`start_cmd=systemctl start nginx
php_socket=1
child_procs=4
add_link=/etc/nginx/sites-enabled
listen_mode=1
stop_cmd=systemctl stop nginx
nginx_config=/etc/nginx/nginx.conf
apply_cmd=systemctl restart nginx
add_to=/etc/nginx/sites-available
nginx_cmd=/usr/sbin/nginx`

**Comment by jcameron** [comment]
Does it help if you change the `apply_cmd` line to `apply_cmd=systemctl reload nginx`

**Comment by amitsamanta996** [comment]
i will try and let you know

**Comment by amitsamanta996** [comment]
Yes, the problem is fixed with `apply_cmd=systemctl reload nginx`

**Comment by jcameron** [comment]
Great! Which Linux distribution and version are you running there?

Regarding showing the remote IP, try adding the line `trust_real_ip=1` to `/etc/webmin/miniserv.conf` and then running `/etc/webmin/restart`

**Comment by amitsamanta996** [comment]
Ubuntu 22.04
`trust_real_ip` worked
thanks

**Comment by jcameron** [comment]
Great! In future, Virtualmin will use `reload` instead of `restart` to apply the Nginx configuration..

**Comment by jcameron** [comment]
Yes, Apache already does graceful restarts to apply config changes..

**Comment by iliajie** [comment]
Jamie, check this out:

https://github.com/virtualmin/virtualmin-nginx/commit/d7232224b7c4cd859be353ed5e87a05cfea0e03b
