### ISSUE TITLE
Awstat file read error and geoip2 not working 

### ISSUE THREAD

**Issue by amitsamanta996** [virtualmin/virtualmin-gpl#614]
Awstat plugin geoip2_country when enabled, save and generate report shows error but terminal output is blank.
Mmdb file linked in awstat.domain.com.conf

**Comment by amitsamanta996** [comment]
this cron just puts a index.html file in public_html/awstats folder, it doesn't generate a new report
 /etc/webmin/virtualmin-awstats/awstats.pl --output /home/example.com/public_html/awstats example.com
 can you say where virtualmin is auto generating the report everyday?

**Comment by amitsamanta996** [comment]
`/etc/webmin/virtualmin-awstats/awstats.pl --debug --output /home/example.com/public_html/awstats example.com`
shows error
`Create/Update database for config "/etc/awstats/awstats.example.com.conf" by AWStats version 7.8 (build 20200416)`
`From data in log file "/var/log/virtualmin/example.com_access_log"...`
`Error: Couldn't open server log file "/var/log/virtualmin/example.com_access_log" : Permission denied`
`Setup ('/etc/awstats/awstats.example.com.conf' file, web server or permissions) may be wrong.`
`Check config file, permissions and AWStats documentation (in 'docs' directory).`

**Comment by amitsamanta996** [comment]
Fixes:
Log file before awstats installed was created as 0660 www-data:www-data
So log file permission had to manually change to 0660 username:www-data
And it worked

**Comment by jcameron** [comment]
That's odd, the log file permissions should be world-readable to allow domain owners to read their own logs..

**Comment by amitsamanta996** [comment]
virtual server was created months back, that time log file permission was given www-data:www-data, which seems to be fixed now, but old log files permission was not updated.
while enabling awstats, a check on log file permission to see if it's user:www-data and if not chnage it required permission should fix the problem.

One more thing, cron for creating awstat has --output parameter which places a index file public_html/awstats folder, which is not recommended as it's publicly accessible, a option should be given, asking if it should output to public_html/awstat folder, for now removing --output from cron manually does the work.

**Comment by amitsamanta996** [comment]
admins can get awstat report from virtualmin -> logs and reports -> awstats report

**Comment by amitsamanta996** [comment]
FIxes for GeoIP2:
geoip2_country and geoip2_city needs mmdb file, no option is there to add such file from virtualmin->awstat config.
while enabling geoip2_country or geoip2_city, virtualmin adds the plugin without mmdb file, which creates error.
`LoadPlugin=geoip2_city`
`LoadPlugin="geoip2_country`
where as valid option should be
`LoadPlugin="geoip2_city /usr/share/GeoIP/GeoLite2-City.mmdb"`
`LoadPlugin="geoip2_country  /usr/share/GeoIP/GeoLite2-Country.mmdb"`

adding mmdb file manually in awstats.domainname.conf works, but when generating report from virtualmin, it removes the mmdb file link.

the only solution working right now is adding these to `/etc/awstats/awstats.conf.local`
`LoadPlugin="geoip2_city /usr/share/GeoIP/GeoLite2-City.mmdb"`
`LoadPlugin="geoip2_country  /usr/share/GeoIP/GeoLite2-Country.mmdb"`
(assuming geoip2 is enabling for all domains)
and not enabling geoip2_country and  geoip2_city while generating report from virtualmin.

2 more library needs to be installed for geoip2 to work
`sudo apt install libdata-validate-ip-perl libgeoip2-perl`

**Comment by jcameron** [comment]
Looking more into this, all Apache logs created by Virtualmin should be owned by their domain's user. Any idea how this might have gotten changed on your system?

**Comment by amitsamanta996** [comment]
> Looking more into this, all Apache logs created by Virtualmin should be owned by their domain's user. Any idea how this might have gotten changed on your system?

I am using nginx, and created the virtual server almost 2 months back, no idea how it got created with www-data:www-data, but the issue seems to be fixed now, new virtual server are created now with user:www-data for log files.

**Comment by jcameron** [comment]
Ok, maybe this is a bug we fixed a long time ago in Virtualmin but the fix didn't include updating existing log files..

**Comment by amitsamanta996** [comment]
Any way to implement the other 2 things i said?
Geoip2 and awstats in public_html

**Comment by jcameron** [comment]
I'll also add a field on the plugins list to edit extra per-plugin options in the next release of the Virtualmin AWstats feature..

**Comment by amitsamanta996** [comment]
Also add  a option so that cron for awstat doesn't output to /home/user/public_html/awstats because then the stats becomes publicly accessible and not everyone wants this.

**Comment by jcameron** [comment]
Actually that --output flag shouldn't be set at all when using Nginx, but it is due to a bug. We'll fix that too ...

**Comment by jcameron** [comment]
Oh wait ... under Nginx, does the awstats.pl CGI script even work?

**Comment by amitsamanta996** [comment]
cron works
`/etc/webmin/virtualmin-awstats/awstats.pl --output /home/username/public_html/awstats domain.com`
it puts a index.html file in `/home/username/public_html/awstats`
which can be accessed.
here is an example [https://technovive.one/awstats/](url)
it shows stats data.

**Comment by jcameron** [comment]
Ah ... so which directory would you prefer the generated index.html be placed in?

**Comment by amitsamanta996** [comment]
> Ah ... so which directory would you prefer the generated index.html be placed in?

if you're admin you can access the log easily from virtualmin -> logs and reports -> awstats report, no need for index.html.
but if someone prefers to access via web server, awstats directory should be password protected, so that it's not publicly available

**Comment by jcameron** [comment]
So ironically Virtualmin does protect that directory already, but using .htaccess files that are only supported on Apache. We are working on adding similar support for Nginx though, but it will take some work because the config format is totally different and there's no equivalent to .htaccess files.

**Comment by amitsamanta996** [comment]
Ok thanks,
an option asking if we want to create --output index file or not would be good, if possible.

**Comment by amitsamanta996** [comment]
I don't know if this issue fixed or not, procmail-wrapper by default doesn't work on arm cpu, only fix is to rebuild it
`wget https://raw.githubusercontent.com/virtualmin/virtualmin-gpl/master/procmail-wrapper.c`
`gcc procmail-wrapper.c -o procmail-wrapper`
`mv /usr/bin/procmail-wrapper /usr/bin/procmail-wrapper.backup`
`cp procmail-wrapper /usr/bin/procmail-wrapper`
`chmod 4755 /usr/bin/procmail-wrapper`

**Comment by jcameron** [comment]
This is a known issue - we need to create a new binary repo for ARM (and other CPU types).

**Comment by amitsamanta996** [comment]
ok thanks

**Comment by jcameron** [comment]
FYI, the procmail issue is tracked in this ticket : https://forum.virtualmin.com/t/i-have-a-problem-with-procmail-wrapper-on-arm-system/118719/27

**Comment by amitsamanta996** [comment]
`/etc/cron.d/awstats`
cron every 10mins for awstats update is disabled because of file permission issues
this cron and virtualmin cron for update could both work if file permission are set as such for
`/home/username/awstats`     `www-data:username`   `0776`

**Comment by jcameron** [comment]
You should disable `/etc/cron.d/awstats` , as Virtualmin sets up it's own per-domain AWstats cron jobs.

**Comment by amitsamanta996** [comment]
It's disabled for new installations, for old servers it didn't disabled during update.
You should have some scripts run during update, that fixes all this issues, like that log file permissions, etc

**Comment by jcameron** [comment]
We do have post-upgrade scripts, but generally I want to be really careful with what they do. Changing log file permissions is almost certainly the right thing, but also there are risks if the admin has changed them intentionally..

**Comment by amitsamanta996** [comment]
You need to change the permission and disable the cron otherwise it's breaking awstats.
You can add a note that says this file permissions changed or take  a input asking if they want to keep as it is

**Comment by amitsamanta996** [comment]
There is another issue with catch-all, as i said [here](https://github.com/virtualmin/virtualmin-gpl/issues/578#issuecomment-1677525716)
