### ISSUE TITLE
Type in a tooltip in Spam and Virus Scanning section

### ISSUE THREAD

**Issue by ADDISON74** [virtualmin/virtualmin-gpl#616]
Go to ```Virtualmin > Email Settings > Spam and Virus Scanning```

Click on **Allow mailbox users to create mail filters** to see the tooltip.

There is a typo in the paragraph, I marked it in the image bellow

![spamassassin](https://github.com/virtualmin/virtualmin-gpl/assets/8360474/25c18abe-9020-41b0-a161-8cfab0edda07)

**Comment by iliajie** [comment]
Thanks for the heads up! We will fix it in the next release.
