### ISSUE TITLE
look out after insallation 

### ISSUE THREAD

**Issue by Thakao** [virtualmin/virtualmin-gpl#62]
Hi i have troubles to install Virtualmin-gpl on my ubuntu 16.04.5 vps. 

I'm installing it via the installation script after phase 3 Virtualmin is asking for my primary network adapter: 
`Device "link" does not exist.
[WARNING] Unable to determine IP address of primary interface.
Please enter the name of your primary network interface:`
so i entered venet0:0 and virtualmin looked me out. 

```
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:84 errors:0 dropped:0 overruns:0 frame:0
          TX packets:84 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:5061 (5.0 KB)  TX bytes:5061 (5.0 KB)

venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:127.0.0.1  P-t-P:127.0.0.1  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:71193 errors:0 dropped:0 overruns:0 frame:0
          TX packets:48140 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:577314882 (577.3 MB)  TX bytes:4154799 (4.1 MB)

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:62.75.145.136  P-t-P:62.75.145.136  Bcast:62.75.145.255  Mask:255.255.255.0
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1

```

What can i do?

Greetings

**Comment by jcameron** [comment]
By "locked out" do you mean the whole machine was inaccessible, or just that the install script hung?

**Comment by swelljoe** [comment]
I can't think of what would cause that. We detect the IP for use in DNS records and in Apache virtual hosts and modifying the resolv.conf to use the system itself as a resolver. But, none of that should be able to lock you out.

What kind of VPS is this? (e.g. KVM, Xen, OpenVZ, Virtuozzo, etc.)

**Comment by Thakao** [comment]
Its a Virtuozzo 6.0.12.

**Comment by shoulders** [comment]
this should be closed because
- it is a support ticket from 2018
- it is an issue with the user rather than virtualmin

**Comment by iliajie** [comment]
Thanks for pointing this out!

**Comment by shoulders** [comment]
no probs, i will do a load more probably at the end of the week. I will concentrate on Virtualmin 😄 as I know that better.
