### ISSUE TITLE
logrotate for site messup between php and apache

### ISSUE THREAD

**Issue by aqueos** [virtualmin/virtualmin-gpl#621]
hi,

 when i add logrotate to a website it does not add a logrotate for the apache logs. It add them to my php fpm logs log rotation which has nothing to do with apache logs.

```
/home/*/logs/*fpm*log /home/*/logs/*slow*log /home/*/logs/*_error_log /home/*/logs/phpmail.log{
	rotate 25
	weekly
	missingok
	size 10M
	notifempty
	compress
	delaycompress
	sharedscripts
	postrotate
	# adapter au xx fpm qui tournent et non plus un seul
	for fichier in /etc/init.d/php*fpm; do $fichier reopen-logs > /dev/null; done
	endscript
}
```
/home/*/logs/*_error_log are /home/*/logs/<domain>_error_log are the php error logs

it add the site here wich never rotate the apache log correctly has restarting php does not flush the logs and rotate the apache ones.

If i remove the fpm rotation file virtualmin create a correct virtualmin.conf file for apache rotation BUT
the php fpm logsd are not rotated :(

best regards,
Ghislain.

**Comment by jcameron** [comment]
Did you create this logrotate block yourself? Normally Virtualmin will create one block per domain.. or one block that lists all domains' files on the first line.

**Comment by aqueos** [comment]
Well the php one is the system or debian sury  one modified to include the websites fpm logs and be unique for all fpm version running on the system. Those two main thing are modified:

`for fichier in /etc/init.d/php*fpm; do $fichier reopen-logs > /dev/null; done`

`/home/*/logs/*fpm*log /home/*/logs/*slow*log /home/*/logs/*_error_log /home/*/logs/phpmail.log`

i have one logrotate to rotate the fpm logs of the websites, and this is the one that virtualmin modify even if there is no link to apache in any way. And it add the apache logs to this logrotate.

I use an unified log rotation has one per website make apache crash from time to time when lograote gracefull/restart it 300 times in a minute. i end up tired of  wake at nigth to restart it.


regards

**Comment by aqueos** [comment]
i just tried again and each time a logrotate has

 /home/*/logs/*fpm*log 

virtualmin use it.

regards,
Ghislain.

**Comment by jcameron** [comment]
Oh I see, Virtualmin is seeing that the path starts with `/home` and assumes it's for it's own logs.

You can turn this behavior off at System Settings -> Server Templates -> Default Settings -> Log file rotation -> Share logrotate configuration with all domains.

**Comment by aqueos** [comment]
well yes but i want this feature as apache can crash when meet with hundreds of restart request at once on logrotation.

i just think its a bug that:

1/ when it find /home  it use a file not related to apache to put apache log rotation therefor leading to issue in apache log that will use "live"  old rotated files.

2/ even when virtualmin create its own file , virtualmin put apache logs AND fpm log rotation in the same file while only reopening logs for apache leading to php fpm logging problems with time as some process will continue to write the old file.

don't you think ?

**Comment by jcameron** [comment]
Those are good points ... I'll look into this and update this ticket with progress.

**Comment by jcameron** [comment]
Ok these issues will both be fixed in the next Virtualmin release.
