### ISSUE TITLE
Virtual Server Module - User ACL - Access Issues

### ISSUE THREAD

**Issue by mdowais** [virtualmin/virtualmin-gpl#625]
Hello,

I created a new webmin user, and added Virtual Server Module to be accessible. 

The newly created user is able to access all the virtual servers and able to change configurations. But the new user is also able to change the core Module Configurations like System Settings, etc. which i dint want to happen.

I then disabled "Can edit module configuration? " after which all the additional core settings were hidden, but now im unable to change other settings of a virtual server like website options, php options, edit users etc.. I get "You are not allowed to edit users in this domain [(eval 116) (line 6)]" error. And, allowed webmin modules are not shown aswell.

**Comment by swelljoe** [comment]
You created a root user. That's working as designed. Webmin is an administrative tool.

If you want a Virtualmin user, limited to managing one or more domains, you create it by creating a new Virtual Server in Virtualmin, which will create a new user that can administer that domain. That user can then create Sub-servers that belong to that user (or you, as root, can also create Sub-servers owned by the original domain).

Virtualmin Pro also has a Reseller account type, that can manage multiple Virtual Servers (not just one Virtual Server and its Sub-servers).
