### ISSUE TITLE
changing php  options could call modification hooks

### ISSUE THREAD

**Issue by aqueos** [virtualmin/virtualmin-gpl#627]
hi,

  I think that changing the php options of a website should call the  hooks of virtualmin for modification of a domain. Because this is a major change for a website and the hooks are a good mecanism to adapt your server to what happen in virtualmin. So i think this will be great if that would be the case.

perhaps having not in

 MODIFY_DOMAIN

but in something new like 

MODIFY_DOMAIN_PHPCONFIG

with the version, process numbers ans time out values.

or perhaps even another hook.

hope that idea can help.

have a nice day.

best regards,
Ghislain.

**Comment by jcameron** [comment]
We could add that ... are you referring to changing PHP options like the execution mode, or php.ini values?

**Comment by aqueos** [comment]
Yes i mean the php option of the site that change thing like the version, the number of process and other things. 

![Capture d’écran du 2023-08-23 08-51-51](https://github.com/virtualmin/virtualmin-gpl/assets/7724531/282a70ea-8395-4c3e-9563-e96ee330554d)

Of course the php.ini part is also important but this code do not replace all the php config that exist contrary to the "php options" part which will **completly reset all the settings if you change the php version** (wich make you loose all settings including the ones set in the service=> php fpm option.

  Perhaps this reset of options is a bug ? If you change the php version it does not read the previous configuration and reset everything loosiong all config done so far. So going from 8.0 to 8.1 for exemple will destroy any settings done on the php.ini settings done previously.


best regards,
Ghislain.

**Comment by chris001** [comment]
Sounds like a bug to me, because, to change to a different PHP version, the names of all of the settings are the same from one version to the next, so the settings should carry over.

However, I bet what's happening is, the new PHP version starts itself with a blank (reset) settings.

Virtualmin would have to copy the "previous" php version's settings files, to the "new" php version's settings files, and it would work great.

**Comment by jcameron** [comment]
Ok that does look like a separate bug - each PHP version has it's own .ini file and FPM options which aren't copied across if you change versions.

We will definitely fix the issue of the post-change action not being run when saving PHP Options though.

**Comment by aqueos** [comment]
ok thanks :)

do you want me to open a separate bug report for the config reset when php version is changed ?

best regards,
Ghislain.

**Comment by chris001** [comment]
There's several things to copy and bring along from old php to new php.  
1. The INI, 
2. the .Htaccess php_engine lines,
3. optionally the cgi command file, 
4. the fom config, and 
5. optionally the sessions if they're in  a different directory so you don't suddenly log out all active logged in users!

**Comment by aqueos** [comment]
@chris001 

1/ you mean the .user.ini ? it does not change so nothing to do here for virtualmin. The main ini file has nothing to do with specific site so not relevant here.
2/ the .htaccess do not change so nothing to do here anyway as it concern the module that i think nobody use anymore and that does not allow multi php version anyway ?
3/  well for this we create a link in the bin directory that link to the php version of the website. This is why i need the change of version to call the hooks to catch this one. this mean customer can use a command in cron that will change with the version that is used by the website.
4/ the fpm file is the one that is to be kept, and is the one reseted rigth now
5/ if you keep the settings, the sessions will not change therefor virtualmin ha nothing to do here also.

best regards,
Ghislain.

**Comment by aqueos** [comment]
i ceated a separate bug report for the fpm version change forgetting the settings.
https://github.com/virtualmin/virtualmin-gpl/issues/628#issue-1865094624

**Comment by jcameron** [comment]
I'll follow up on the PHP FPM settings being lost when changing versions in https://github.com/virtualmin/virtualmin-gpl/issues/628
