### ISSUE TITLE
changing php version do not keep the FPM settings

### ISSUE THREAD

**Issue by aqueos** [virtualmin/virtualmin-gpl#628]
hi,

 when you change the php version of a website the FPM settings are not kept. It drop all the prévious fpm settings and create a new empty fpm ini version. For exemple my fpm file has:

```
[150998780827309]
listen = /home/zero00-site-par-defaut/logs/php-fpm-1000.sock
user = 1000
group = 1000
listen.owner = www-data
listen.group = 000-site-par-defaut
listen.mode = 660
pm = ondemand
pm.max_children =  20
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 5
pm.max_requests = 20000
chdir = /home/zero00-site-par-defaut
request_slowlog_timeout = 5
slowlog = /home/zero00-site-par-defaut/logs/000-site-par-defaut.fr_slow_log
env[HOMEDIR] = /home/zero00-site-par-defaut
env[TMP] = /home/zero00-site-par-defaut/tmp/tmp
env[TMPDIR] = /home/zero00-site-par-defaut/tmp/tmp
php_admin_value[error_log] = /home/zero00-site-par-defaut/logs/000-site-par-defaut.fr_fpm_log
php_value[mail.log] = /home/zero00-site-par-defaut/logs/phpmail.log
;; monitoring
pm.status_path = /status-R2Y0NBUGVyYjRCdFRGMXh0ZFM4YmV.php
php_admin_value[session.save_path] = /home/zero00-site-par-defaut/tmp/sessions
php_admin_value[upload_tmp_dir] = /home/zero00-site-par-defaut/tmp/upload
php_admin_value[sys_temp_dir] = /home/zero00-site-par-defaut/tmp/tmp
ping.path = /aqping
ping.response = php8.1-fpm
include=/etc/php/8.1/fpm/php-aqfpm.d/150998780827309.conf
php_flag[log_errors] = on
php_value[session.gc_probability] = 1
php_value[open_basedir] = '/home/zero00-site-par-defaut/:/tmp/:/usr/share/php/:/usr/share/fonts/:/var/tmp/:/var/lib/mysql-files/zero00-site-par-defaut/'
php_admin_value[mail.add_x_header] = 1
php_value[session.gc_maxlifetime] = 86400

```

then i go to server congfiguration => php option

Then if i save the resulting file will be:

```
[150998780827309]
user = zero00-site-par-defaut
group = 000-site-par-defaut
listen.owner = zero00-site-par-defaut
listen.group = 000-site-par-defaut
listen.mode = 0660
listen = /var/php-fpm/150998780827309.sock
pm = dynamic
pm.max_children = 20
pm.start_servers = 3
pm.min_spare_servers = 1
pm.max_spare_servers = 10
php_value[upload_tmp_dir] = /home/zero00-site-par-defaut/tmp
php_value[session.save_path] = /home/zero00-site-par-defaut/tmp
php_value[error_log] = /home/zero00-site-par-defaut/logs/000-site-par-defaut.fr_fpm_log
php_value[log_errors] = On

```

as you see all the settings have been reseted.

if i change a setting like the process number the settings are kept.

its only when i change the php version that all is reseted.

best regards,
Ghislain.

**Comment by chris001** [comment]
See: Relevant items, containing settings, to copy over from old to new PHP version [here](https://github.com/virtualmin/virtualmin-gpl/issues/627#issuecomment-1691384282) and @aqueos comment right after.

**Comment by jcameron** [comment]
Thanks for reporting this ... I'll take a look at how we can support those `php_value` fields in the pool file.

**Comment by iliajie** [comment]
> Thanks for reporting this ... I'll take a look at how we can support those `php_value` fields in the pool file.

Jamie, I think we need to make this change aware (for the future) of PHP-FPM supporting per-directory configuration. Off hand, I'd say we store it inside domain config file for each version, i.e. `php_fpm_74`. If we setup let's say `php_fpm_81` we check if `php_fpm_81` has pre-saved directives. If not we should use from the closest available, i.e. `php_fpm_74` ..

Also, can we store stringified JSON as a value in Virtualmin domain config for those `php_fpm_74` and etc? If so, we can just presume directories there already. For now we only do `/` and later we can use other directories under `public_html` .. ?

**Comment by jcameron** [comment]
Per-directory FPM versions would also be a cool feature, but significantly more effort so I don't want to track it in this ticket..

**Comment by iliajie** [comment]
Alrighty, I can have a look though and make a PR. I like solving challenging issues for implementing features that people want ..

**Comment by jcameron** [comment]
Go for it! But this will have to wait till after the upcoming Virtualmin release ...

**Comment by iliajie** [comment]
Undoubtedly!

**Comment by jcameron** [comment]
The next Virtualmin release will copy across `php_value`, `php_admin_value`, `env` and `pm.` settings when changing PHP version..

**Comment by iliajie** [comment]
> The next Virtualmin release will copy across `php_value`, `php_admin_value`, `env` and `pm.` settings when changing PHP version.

Although, it doesn't seem it will be saving those values when the mode is changed. But I think it's fine ..

**Comment by jcameron** [comment]
No, not yet ... that would be a separate problem to fix, since the format of the options is different.
