### ISSUE TITLE
Disable website feature isn't triggering `create_disable_directives` when used with Nginx

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#631]
Jamie, when the website is being disabled it doesn't trigger `create_disable_directives` sub, and as a result the disabled template isn't looking right with Nginx.

**Comment by iliajie** [comment]
Fix here https://github.com/virtualmin/virtualmin-nginx/commit/56d9a0abdbb867393f1f6dc5ce041ebb5b14c326.

**Comment by jcameron** [comment]
Thanks for the fix!
