### ISSUE TITLE
Dynamic IP Update: SPF records are not updated when IP changes

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#633]
Jamie, when Virtualmin automatically updates dynamic DNS records, it does not update the SPF records.

Is this expected? I think we should also update the old IP address with the new one, if SPF record had an old IP address set.

**Comment by jcameron** [comment]
Yes, they should be updated if the IP changes.  If you use the Change IP Address page for a domain to update the IP, does the SPF DNS record get changed?

**Comment by iliajie** [comment]
> f you use the Change IP Address page for a domain to update the IP, does the SPF DNS record get changed?

No, SPF DNS record still isn't get changed, as I just tried **Change IP Address** page .

**Comment by jcameron** [comment]
Does this domain have separate internal and external IP addresses?

**Comment by iliajie** [comment]
Yes, it does!

**Comment by jcameron** [comment]
And were you changing the internal or external IP?

**Comment by iliajie** [comment]
I was changing the internal address, i.e. Virtualmin was changing internal IP address of my instance, after I changed it in the hypervisor.

**Comment by jcameron** [comment]
But does the SPF record contain the internal IP? It shouldn't need to ...

**Comment by jcameron** [comment]
I'll add code to handle that case, even though I wouldn't expect it to ever happen..
