### ISSUE TITLE
Backup functionality will fail when requesting a `.tar` formatted archive for direct download

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#638]
Steps to reproduce, with VirtualMin 7.7 (haven't tested 7.8.1 yet) on Debian 11:

1. Ask for a backup of all websites, in .tar format (instead of the Default), with "download" (to local PC) output
2. You get this error message when clicking the download link:

> Backup failed : Backup file to download is not formatted correctly 

Differential diagnosis:
* The "Default" output format (`tar.gz` instead of `tar`) works, even for direct download.
* The `tar` format works if outputting to the server's local filesystem, instead of downloading to the admin's PC.

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up! We will fix this in the next Virtualmin release.
