### ISSUE TITLE
dovecot protocol selector broken (pro/ubuntu 22.04 lts)

### ISSUE THREAD

**Issue by maxslug** [virtualmin/virtualmin-gpl#639]
The drop-down for the dovecot protocol selector is not working on a brand new Ubuntu 22.04 LTS AMD64 install.

I'm guessing it's this line in `/etc/dovecot/dovecot.conf` : 
```
!include_try /usr/share/dovecot/protocols.d/*.protocol
```

I manually changed it to this to disable POP3:

```
protocols = imap
```

**Comment by maxslug** [comment]
<img width="1101" alt="dovecot_virtualmin" src="https://github.com/virtualmin/virtualmin-gpl/assets/1693479/371e4a76-27f6-4ba5-86e5-7e718ba5ef1e">

**Comment by jcameron** [comment]
What do those `/usr/share/dovecot/protocols.d/*.protocol` files contain?

**Comment by maxslug** [comment]
Nothing that warrants a separate file :) 

```
$ cat /usr/share/dovecot/protocols.d/imapd.protocol
protocols = imap
$ cat /usr/share/dovecot/protocols.d/pop3d.protocol
protocols = $protocols pop3
```

**Comment by jcameron** [comment]
So in your screenshot, IMAP and POP3 are selected which matches the `protocols` lines you pasted?

**Comment by maxslug** [comment]
No, I was trying to disable POP and it would reset back to both being on.

**Comment by jcameron** [comment]
Oh I see ... because those two lines are combined, and Webmin only knows how to update one of them. 

I don't think this is solvable, sorry :-(

**Comment by maxslug** [comment]
no worries, it was an easy fix, just replace that !include line with the older protocol line, and it worked for me.   Feel free to close.

**Comment by iliajie** [comment]
This cannot be right! Webmin Dovecot module should be able at least save `protocols` directive correctly by writing it in `/etc/dovecot/dovecot.conf` rather than `/usr/share/dovecot/protocols.d/imapd.protocol`. I believe we shouldn't write to `/usr/share/dovecot/` at all. This is the place where all defaults are. We shouldn't touch it.

**Comment by maxslug** [comment]
Agreed, I don't think anyone suggested changing anything in /usr,   my fix was all in dovecot.conf.

**Comment by jcameron** [comment]
I think what Ilia meant is that Webmin should add a new line to `/etc/dovecot/dovecot.conf` instead of updating the lines under `/usr/share/dovecot/protocols.d`

**Comment by iliajie** [comment]
> I think what Ilia meant is that Webmin should add a new line to `/etc/dovecot/dovecot.conf` instead of updating the lines under `/usr/share/dovecot/protocols.d`

Yeah!

**Comment by jcameron** [comment]
This is non-trivial to fix unfortunately, as the current code just assumes that it can edit Dovecot directives anywhere in the config files...

**Comment by iliajie** [comment]
> This is non-trivial to fix unfortunately, as the current code just assumes that it can edit Dovecot directives anywhere in the config files...

I will submit you a PR to discuss it.
