### ISSUE TITLE
Unable to Update Virtualmin Module from “Update modules” tab of “Upgrade Webmin”

### ISSUE THREAD

**Issue by MSSEsq** [virtualmin/virtualmin-gpl#641]
Webmin does not detect the availability of the updated 7.8.2 version of Virtualmin for display on the Dashboard. Trying to upgrade the Virtualmin module from the “Update modules” tab of the “Upgrade Webmin” page in “Webmin Configuration,” either with the default Update from [www.webmin.com](http://www.webmin.com/) radio button selected, or the “Update from other sources…” radio button selected and either “[http://download.webmin.com/download/virtualmin/virtual-server-7.8.2.gpl.wbm.gz”](http://download.webmin.com/download/virtualmin/virtual-server-7.8.2.gpl.wbm.gz%E2%80%9D) or “[https://software.virtualmin.com/vm/7/gpl/wbm/virtual-server-7.8.2.gpl-1.wbm.gz”](https://software.virtualmin.com/vm/7/gpl/wbm/virtual-server-7.8.2.gpl-1.wbm.gz%E2%80%9D) entered into the text box, returns “Updating Webmin modules … No Webmin updates for this version.” Virtualmin was originally installed from “[https://software.virtualmin.com/vm/7/gpl/wbm/virtual-server-7.7.gpl-3.wbm.gz”](https://software.virtualmin.com/vm/7/gpl/wbm/virtual-server-7.7.gpl-3.wbm.gz%E2%80%9D) using the “Install Module” page.

It seems possible that the switch to semantic versioning underlies the inability to detect that a version update of a module is available. There is currently no way to use Webmin to update modules. The only current alternatives are to either reinstall modules or obtain updated standard modules as part of a Webmin update.

Webmin version 2.102 
Authentic theme version 21.06 
Kernel and CPU FreeBSD 13.2-RELEASE-p3 on amd64
 Virtualmin version 7.7

**Comment by jcameron** [comment]
How did you install Virtualmin originally? Was it using our script, or did you just install the module .wbm.gz file directly?

**Comment by MSSEsq** [comment]
> How did you install Virtualmin originally? Was it using our script, or did you just install the module .wbm.gz file directly?

As specified in my initial problem report: 

> Virtualmin was originally installed from “[https://software.virtualmin.com/vm/7/gpl/wbm/virtual-server-7.7.gpl-3.wbm.gz”](https://software.virtualmin.com/vm/7/gpl/wbm/virtual-server-7.7.gpl-3.wbm.gz%E2%80%9D) using the “Install Module” page.

**Comment by jcameron** [comment]
Ok I see the bug that causes this - it will be fixed in the next Webmin release.

**Comment by MSSEsq** [comment]
I replaced the webmin/update.cgi and webmin/webmin-lib.pl files with the versions in commit d8fa7f2 and retested. The results were still the same as described in my original report.

**Comment by jcameron** [comment]
Actually it looks like we didn't update the version on our side! Try waiting a day for caches to clear and then re-doing the update...

**Comment by MSSEsq** [comment]
With the webmin/update.cgi and webmin/webmin-lib.pl files having been previously updated with the versions in commit d8fa7f2, and now five days later, further testing produces the same Virtualmin module update failure as originally reported. Since the error message includes “No Webmin updates for this version,” it seems that the failure might be related to the out-of-date https://software.virtualmin.com/vm/7/gpl/wbm/webmin-version file. That file currently was last modified 2022-06-07 06:05 and contains “1.990.” The currently running version of Webmin is 2.102.

**Comment by MSSEsq** [comment]
System Information:
Webmin version 2.303
Virtualmin version 7.30.8
FreeBSD 14.2-RELEASE-p2 on amd64

This problem persists with the current Virtualmin system information specified above the same as was originally reported in Sep. 2023. The only way to use Webmin to update the Virtualmin module originally installed from https://software.virtualmin.com/vm/7/gpl/wbm/ is to install the updated module over the previously installed module using the Webmin Modules Install tab with the “From HTTP or FTP URL” radio button selected and the URL of the new Webmin Module (.wbm) file entered into the corresponding form field rectangle.

**Comment by iliajie** [comment]
> The only way to use Webmin to update the Virtualmin module originally installed from https://software.virtualmin.com/vm/7/gpl/wbm/ is to install

This is something that is handled by @swelljoe —Jamie and I have no control over it. Something is probably not working in the build scripts for `/wbm/` releases.

**Comment by MSSEsq** [comment]
> This is something that is handled by [@swelljoe](https://github.com/swelljoe)…

As an attempt to bring this problem back to the fore, I created a new Virtualmin Forum discussion: [Virtualmin Module Not Updatable From “Update modules” Tab of “Upgrade Webmin”](https://forum.virtualmin.com/t/virtualmin-module-not-updatable-from-update-modules-tab-of-upgrade-webmin/132857).
