### ISSUE TITLE
virtualmin check-config Fails to Detect PHP-FPM Used By Apache HTTP Server

### ISSUE THREAD

**Issue by MSSEsq** [virtualmin/virtualmin-gpl#643]
**Running “virtualmin check-config” in a Unix shell or opening the “Re-Check Configuration” Virtualmin page incorrectly reports:**

> No PHP execution modes are available!
> No PHP-FPM packages were found

**System Information:**

Webmin version 2.102 
Authentic theme version 21.06
 Kernel and CPU FreeBSD 13.2-RELEASE-p3 on amd64 
 Virtualmin version 7.7

The PHP 8.2.7 and Meta Extensions packages were installed as described in [FreshPorts -- lang/php82: PHP Scripting Language (8.2.X branch)](https://www.freshports.org/lang/php82/) and [FreshPorts -- lang/php82-extensions: "meta-port" to install PHP extensions](https://www.freshports.org/lang/php82-extensions/).

The /etc/rc.conf file includes:
`	php_fpm_enable="YES"`

PHP version information as reported in a shell session:
> % php --version
> PHP 8.2.7 (cli) (built: Jul  2 2023 01:22:57) (NTS)
> Copyright (c) The PHP Group
> Zend Engine v4.2.7, Copyright (c) Zend Technologies
>     with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies
> % php-fpm --version
> PHP 8.2.7 (fpm-fcgi) (built: Jul  2 2023 01:23:04)
> Copyright (c) The PHP Group
> Zend Engine v4.2.7, Copyright (c) Zend Technologies
>     with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

Running “service php-fpm status” returns:
> 	php_fpm is running as pid [1234].

The /usr/local/etc/apache24/httpd.conf file includes (not commented):
`	LoadModule proxy_fcgi_module libexec/apache24/mod_proxy_fcgi.so`
No conflicting apache24 modules are enabled.

A /usr/local/etc/apache24/modules.d/080_mod_php-fpm.conf file is installed which includes:

> 	
	<IfModule proxy_fcgi_module>
	    <IfModule dir_module>
	        DirectoryIndex index.php
	    </IfModule>
	    <FilesMatch "\.(php|phtml|inc)$">
	        SetHandler "proxy:unix:/var/run/php-fpm.sock|fcgi://localhost/"
	    </FilesMatch>
	</IfModule>

The /usr/local/etc|/php-fpm.d/www.conf file includes:
`	listen = /var/run/php-fpm.sock`

Note: The /var/run/php-fpm.sock file exists and correctly identifies the Unix socket. Referencing the Unix socket in the PHP-FPM configuration rather than a network communication port enhances security and avoids any possibility of network port conflicts. Apache HTTP Server running on the same system is effectively using the running PHP-FPM process to run PHP scripts.

**Comment by jcameron** [comment]
Looks like Virtualmin isn't looking in the right place for the PHP FPM packages on FreeBSD.

Where is the actual `php-fpm` binary located?

**Comment by MSSEsq** [comment]
> Looks like Virtualmin isn't looking in the right place for the PHP FPM packages on FreeBSD.
> 
> Where is the actual `php-fpm` binary located?

By convention, on Unix systems including FreeBSD and macOS, optional binary software is installed in `/usr/local` to keep user installed and system software discrete. The packaged PHP executable binary files are installed as `/usr/local/bin/php` and `/usr/local/sbin/php-fpm`. However, since these locations are conventional rather than mandatory, running `whereis php` and `whereis php-fpm` and checking the returned pathnames is more reliable because this uses the actual system search paths for finding executable files. Probably the best way to check the status of the `php-fpm` process is by running `service php-fpm status` and checking the result.

**Comment by jcameron** [comment]
I think unfortunately we're going to need to do some work to support PHP FPM on FreeBSD - the current code in Virtualmin for detecting it makes a lot of assumptions about the package manager and systemd action name that doesn't translate well to FreeBSD's way of doing things.

**Comment by MSSEsq** [comment]
It seems recommendable to also consider PHP FPM on macOS. An approach that works for both FreeBSD and macOS likely would have broad applicability. Here is a link to the Web page of the most commonly used packaged version of PHP for macOS: [https://formulae.brew.sh/formula/php#default](url).

**Comment by jcameron** [comment]
We'll look into this and update this ticket with details once we have better FPM support on FreeBSD.

**Comment by jcameron** [comment]
So I'm working on this now. But on a FreeBSD, where are the PHP FPM pool config files located?

**Comment by chris001** [comment]
On FreeBSD, the PHP FPM pool config files are typically located in:  `/usr/local/etc/php-fpm.d/`

**Comment by jcameron** [comment]
Thanks! The next release of Virtualmin will support FPM on FreeBSD, or other systems where it's been compiled manually..

**Comment by MSSEsq** [comment]
Virtualmin check-config still fails to detect running PHP-FPM with System Information:

Webmin version 2.303 
 FreeBSD 14.2-RELEASE-p2 on amd64 
 Virtualmin version 7.30.7

**Comment by jcameron** [comment]
@MSSEsq where are the FPM binary and config file on your system?

**Comment by MSSEsq** [comment]
> [@MSSEsq](https://github.com/MSSEsq) where are the FPM binary and config file on your system?

The locations on FreeBSD 14.2 are the same as described above for FreeBSD 13.2: The packaged PHP executable binary files are installed as `/usr/local/bin/php` and `/usr/local/sbin/php-fpm`, and the PHP FPM pool config files are typically located in:  `/usr/local/etc/php-fpm.d/`. However, these locations are technically only by convention, as I noted in a comment on Sep 19, 2023.

**Comment by MSSEsq** [comment]
**Current System Information:**

Operating system FreeBSD 14.2
Webmin version 2.303
Virtualmin version 7.30.8  
Authentic theme version 23.03
Webserver Apache HTTP Server 2.4

I considered alternative ways to determine if PHP FPM mode is available other than looking for PHP FPM binary and configuration files:

The Virtualmin Dashboard under Software Versions currently lists:
`PHP versions	8.3.19`
This matches what “php --version” returns, and indicates that Virtualmin accurately detects the availability of PHP.

The virtual-server config file currently includes these lines:
`php8.3cgi=none`
`php8.3fcgi=none`
`web_php_ini_8.3=`

Running
`php-fpm --info | grep 'php-fpm => active'`
if PHP FPM mode is available, then returns:
`php-fpm => active`
If PHP FPM mode is not available, then nothing is returned.

Running
`service php_fpm status`
returns:
`php_fpm is running as pid 1234.`
(with the actual PID)

Running
`service php_fpm status | grep 'php_fpm is running'`
if PHP FPM mode is available, then returns (with the actual PID):
`php_fpm is running as pid 1234.`
If PHP FPM mode is not available, then nothing is returned.

These possible methods seem more reliable than accessing executable and configuration files by following fixed file paths that are actually variable.

I hope that this is useful. This problem prevents use of all the PHP related functions of Virtualmin since none work if no PHP execution mode is detected.

**Comment by jcameron** [comment]
On FreeBSD, is PHP FPM installed from some kind of standard package, and if so what is it called?

**Comment by MSSEsq** [comment]
> On FreeBSD, is PHP FPM installed from some kind of standard package, and if so what is it called?

Yes, there are multiple standard packaged versions of PHP for FreeBSD. Here is a link to the FreshPorts page about PHP version 8.4, which is the latest branch: [FreshPorts -- lang/php84: PHP Scripting Language (8.4.X branch)](https://www.freshports.org/lang/php84/).

**Comment by jcameron** [comment]
Thanks! Is there a package specifically for the FPM server, or is it always bundled into the core package like `lang/php84` ?

**Comment by MSSEsq** [comment]
> Is there a package specifically for the FPM server, or is it always bundled into the core package…

I have always seen the FPM server bundled in the main package. There are many separate PHP shared extension packages, a meta-package of shared extensions (installed), and mod_php packges for Apache HTTP Server (not installed). FreshPorts does not list any separate php-fpm packages. If PHP is configured to run using the FPM server, then there are multiple php-fpm Unix processes running, one as the root user, and the others as the www user. On our system php-fpm listens on a Unix socket rather than on a network port.

**Comment by jcameron** [comment]
Actually I just remembered that there's another way that should already work to have Virtualmin detect a different PHP FPM install. At System Settings -> Virtualmin Configuration -> PHP options you can enter the path to the PHP binary, pool directory and bootup action. Only catch is that only one version is supported right now.

**Comment by MSSEsq** [comment]
The default Virtualmin PHP options were:

> **Additional PHP FPM server**
> `php-fpm`
> **Additional PHP FPM pool directory**
> `/usr/local/etc/php-fpm.d`
> **Additional PHP FPM bootup action**
> `php-fpm`
> **Cleanup PHP session files after**
> `7`

I removed the PHP 8.3.19 packages and installed the PHP 8.4.5 packages to fully upgrade PHP to the latest release version. I then edited the Virtualmin PHP options to be:

> **Additional PHP FPM server**
> `/usr/local/sbin/php-fpm`
> **Additional PHP FPM pool directory**
> `/usr/local/etc/php-fpm.d`
> **Additional PHP FPM bootup action**
> `php_fpm`
> **Cleanup PHP session files after**
> `7`

The edited server pathname and the pool directory path are both correct. I also tried `/usr/local/etc/rc.d/php_fpm`, `php_fpm_enable`, and `php_fpm_enable="YES"` as the **Additional PHP FPM bootup action**. None of this worked. The result of the Virtualmin Configuration check was always:

> ERROR — PERL EXECUTION FAILED
>       Undefined subroutine &init::action_status called at /usr/local/lib/webmin-
>       2.303/virtual-server/php-lib.pl line 2227.

This reported error was failure of excution of the following line in the php-lib.pl file:
`		my $st = &init::action_status($rv->{'init'});`

The entire section of the `php-lib.pl` file containing that line is:

```
# If FPM was setup without a package or init script, also allow it
if ($config{'php_fpm_cmd'} && -x $config{'php_fpm_cmd'} &&
    $config{'php_fpm_pool'} && -d $config{'php_fpm_pool'}) {
	my $rv = { 'cmd' => $config{'php_fpm_cmd'},
		   'fromconfig' => 1,
		   'init' => $config{'php_fpm_init'},
		   'dir' => $config{'php_fpm_pool'},
		 };
	$rv->{'version'} = &get_php_version($rv->{'cmd'});
	$rv->{'shortversion'} = $rv->{'version'};
	$rv->{'shortversion'} =~ s/^(\d+\.\d+)\..*/$1/;  # Reduce version to 5.x
	if ($rv->{'init'}) {
		my $st = &init::action_status($rv->{'init'});
		if ($st == 0) {
			$rv->{'err'} = &text('php_fpmnoinit3', $rv->{'init'});
			}
		elsif ($st == 2) {
			$rv->{'enabled'} = 1;
			}
		}
	push(@rv, $rv);
	}
```

**Comment by jcameron** [comment]
Ok so it looks like the issue now is that Webmin doens't know how to manage bootup actions on your OS.

What output do you get if you run `grep os_ /etc/webmin/config` ?

**Comment by jcameron** [comment]
Ok, see if this patch helps with the perl execution issue : https://github.com/virtualmin/virtualmin-gpl/commit/bbd5d71cf79e6dbe15e9a631bfb692b4eda0b047

**Comment by MSSEsq** [comment]
I applied the patch, and the Virtualmin configuration check now runs successfully. It still reports:

> CGI scripts cannot be executed on this system!
>
> No PHP execution modes are available!
>
> No PHP-FPM packages were found

Now, I will try editing the Virtualmin PHP options again.

**Comment by MSSEsq** [comment]
I again edited the Virtualmin PHP options as detailed in an earlier comment. The Virtualmin configuration check now reports:

> CGI scripts cannot be executed on this system!
>
> The following PHP execution modes are available : fpm
>
> The following PHP-FPM versions are available : 8.4.5 (/usr/local/sbin/php-fpm)

This makes it possible to edit Server Template PHP options.

I do not see why the Virtualmin configuration check still reports that “CGI scripts cannot be executed.” The Apache HTTP Server CGI Programs configuration for the default server does include a CGI directory alias that directs to the default `/usr/local/www/apache24/cgi-bin/` CGI directory. The Apache HTTP Server configuration includes a file that contains:

```
<IfModule proxy_fcgi_module>
    <IfModule dir_module>
        DirectoryIndex index.php index.html
    </IfModule>
    <FilesMatch "\.(php|phtml|inc)$">
        SetHandler "proxy:unix:/var/run/php-fpm.sock|fcgi://localhost/"
    </FilesMatch>
</IfModule>
```

This report that CGI scripts cannot be executed might be harmless.

**Comment by jcameron** [comment]
The error about CGI scripts means that Virtualmin was unable to find either `fcgiwrap` or `suexec`, which it needs to run CGI scripts with domain owner permissions.

**Comment by MSSEsq** [comment]
It would have to be `suexec` on our system. Running `httpd -V | grep suexec` returns ` -D SUEXEC_BIN="/usr/local/bin/suexec"`, so the packaged Apache HTTP Server was compiled with `suexec`, but the `/usr/local/bin/suexec` executable file does not exist. The [suEXEC Support - Apache HTTP Server Version 2.4](https://httpd.apache.org/docs/2.4/suexec.html) documentation page states “it has been the decision of the Apache HTTP Server development team to **NOT** make suEXEC part of the default installation of Apache httpd.” This decision was based upon security concerns. Perhaps CGI script execution is best left unavailable if installation of `suexec` would be required.

My testing results indicate that the https://github.com/virtualmin/virtualmin-gpl/commit/bbd5d71cf79e6dbe15e9a631bfb692b4eda0b047 patch can be merged into the master or stable branches.

Thanks for the help with the PHP FPM problem. Hopefully, future versions of Virtualmin will support multiple PHP versions with FPM, and not require manual configuration of the PHP options when running on FreeBSD systems.

**Comment by jcameron** [comment]
Ok sounds like you'd need to compile `suexec` manually to get it working with Apache and Virtualmin.

**Comment by iliajie** [comment]
Why not just `pkg install fcgiwrap`?

**Comment by MSSEsq** [comment]
> Why not just `pkg install fcgiwrap`?

I had thought of fcgiwrap as being for use with nGinx on Linux, but now see that a packaged version for FreeBSD is available: [FreshPorts -- www/fcgiwrap: Simple FastCGI wrapper for CGI scripts](https://www.freshports.org/www/fcgiwrap/). I remain hesitant to install that package though because the referenced fcgiwrap Web site does not exist, and the [gnosek/fcgiwrap: Simple FastCGI wrapper for CGI scripts](https://github.com/gnosek/fcgiwrap) project page shows stagnation for 10 years. This makes me think it might be time to consider CGI scripts as WWW history. Nevertheless, thanks for the suggestion.

**Comment by jcameron** [comment]
Yeah to be honest, CGI scripts are pretty outdated. However, fcgiwrap is a solid solution for implementing them, and quite secure the way we set it up in Virtualmin.
