### ISSUE TITLE
DNSSec enable fails (Pro/Ubuntu 22)

### ISSUE THREAD

**Issue by maxslug** [virtualmin/virtualmin-gpl#645]
After enabling DNS Sec, bind fails to load.

```
Sep 19 14:23:17 server.net systemd[1]: Reloading BIND Domain Name Server...
Sep 19 14:23:17 server.net named[469]: received control channel command 'reload'
Sep 19 14:23:17 server.net named[469]: loading configuration from '/etc/bind/named.conf'
Sep 19 14:23:17 server.net named[469]: /etc/bind/named.conf.options:24: option 'dnssec-enable' no longer exists
Sep 19 14:23:17 server.net named[469]: reloading configuration failed: failure
Sep 19 14:23:17 server.net rndc[687046]: rndc: 'reload' failed: failure
```

looks like the option was removed and now dnssec is just sorta on by default?

https://serverfault.com/a/1105506

I commented out the line and then bind was able to start (`systemctl start named.service`).

**Comment by maxslug** [comment]
I also had a weird unrelated bug:  I had to do a `chmod go+r /etc/mailname`    It was set to `0500` and postfix was failing.

**Comment by chris001** [comment]
From the [BIND 9.16.0 release notes](https://bind9.readthedocs.io/en/v9_16/notes.html#id77):

>    **The dnssec-enable option has been obsoleted and no longer has any effect. DNSSEC responses are always enabled if signatures and other DNSSEC data are present. [GL 866]**

I.e., the change is that there is no longer a way to turn off/on the basic handling of DNSSEC data. You can still enable/disable validation through [dnssec-validation](https://bind9.readthedocs.io/en/v9_16/reference.html#boolean-options) though.

**Comment by jcameron** [comment]
@maxslug which page did you enable DNSSEC on?

**Comment by maxslug** [comment]
@jcameron I think it was probably the Webmin -> Servers -> BIND -> DNSSEC Enable = Yes that did it.

I then went into each domain and did Virtualmin -> mydomain.com -> Server Configuration -> DNS Options -> DNSSEC signature enabled = yes.   But I suspect it was the former.

**Comment by jcameron** [comment]
Oh yeah, it's the former that would enable this. 

Since this option has been obsoleted in newer BIND versions, I will update Webmin to not show it when it's not supported.

**Comment by shoulders** [comment]
@jcameron did you fix this in your patch above?

**Comment by jcameron** [comment]
Yes I did!
