### ISSUE TITLE
MariaDB will fail to create the database if the "Create Webmin login" feature is disabled with an empty password in a vServer

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#646]
From what I observed in VirtualMin 7.8.2, if you create a virtual server, uncheck the "Create Webmin login" checkbox and don't fill in a password for that seemingly non-existent user (because you deem that the intended user does not actually need admin rights, just basic website development and maintenance rights), and keep the "Create MariaDB database" feature enabled, when you create / update the server, you will get this failure because of the empty password:

```
Modifying administration user ..
.. done

Changing disk quota ..
.. done

Creating MariaDB login ..
.. MariaDB database failed! : 
mysql::execute_sql_logged failed : 
SQL create user 'the_vserver_name'@'localhost' identified by password password('') failed : 
You have an error in your SQL syntax; 
check the manual that corresponds to your MariaDB server version for the right syntax to use near 'password('')' at line 1

Deleting Webmin login ..
.. done

Saving server details ..
.. done

Re-loading Webmin ..
.. done
```

I presume maybe the solution would be to force setting a server password (or a custom mariadb password) when the mariadb feature is requested in such a case?

**Comment by jcameron** [comment]
Thanks for pointing this out - we shouldn't allow passwordless domains to ever be created. I'll fix this in the next release.
