### ISSUE TITLE
"File on server" field label in the Virtual Servers backup UI is confusing when backing up "one file per server"

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#647]
## Initial problem

In Virtualmin's 7.8.2's "Backup and Restore > Backup Virtual Servers" utility (also in the "Scheduled Backups" UI), when using the direct to "FTP" or "SFTP" backup destination type, there's a field in the form called "File on server".

I left that blank because I didn't know what name I wanted, and I was backing up multiple vservers as individual files anyway, so I thought "just throw them all into that FTP folder". But it turns out that the backup process doesn't accept that, and the UI doesn't make it very clear.

This was confusing to me, because it seems that what was meant there was not "_File_ on server" (not with the _usual_ understanding of the word file, linguistically speaking) but rather "Folder" or directory...  and it should be made clear that this is a relative path subfolder within the jail that is FTP, rather than an absolute path.

## Source of the confusion

The backup system refuses to work if you leave that field empty; so I wondered:

> Should it really be mandatory, in FTP's case? For example, when I created a dedicated "backup" FTP account there, I already confined it to its own folder (is there such a thing as unconstrained FTP?); in that case, couldn't backups be allowed to go directly to the root directory that FTP has access to? If not, I could live with that, but it should probably be clearer that it's a mandatory field.

Then I realized that this might be a result of the "Backup format" section allowing a monolithic backup as a "Single archive file" vs the "One file per server" option. Quoting the (somewhat hidden, because not "next to each relevant field") documentation tooltip button:

> If the backup format is a single file, then the destination you specify here must be a file, which will be overwritten or created. If creating one file per domain, then the destination must be a directory which already exists.

## Proposed solution

I would suggest:
* Combine the "Backup format" (and "Backup compression format") sections  
(optional, but probably makes sense while we're at it?)
* Put the "Backup format" section above the "Backup destinations" section, and make it so that that it changes the "File on server" labels dynamically depending on if you're backuping as a "Single archive file" vs "One file per server"; in the latter case, it could be labelled:
  * "Folder path on the destination server" in the case of SFTP (presuming SFTP is not necessarily jailed)
  * "Subfolder on destination server" in the case of FTP

**Comment by jcameron** [comment]
@iliajie do you think we could fix this with some javascript that updates the labels in the UI?

**Comment by iliajie** [comment]
> @iliajie do you think we could fix this with some javascript that updates the labels in the UI?

Yeah, I think we could!

**Comment by iliajie** [comment]
> > @iliajie do you think we could fix this with some javascript that updates the labels in the UI?
> 
> Yeah, I think we could!

Alright, added in this patch https://github.com/virtualmin/virtualmin-gpl/commit/dbe1bd05025878669b4e51312cc51b078634a416. It was a little more difficult than I expected at first.

The example of how it works is in the screencast below:


https://github.com/virtualmin/virtualmin-gpl/assets/4426533/63f09320-332a-4c99-a685-83907fb3e58f

**Comment by nekohayo** [comment]
Oooh, those new dynamic placeholder texts in the textfields are neat, that's a good addition! 😉

Was it not possible to also dynamically change the "File on server" label on the left of the textfield, or that's just some forgotten detail?

**Comment by iliajie** [comment]
> Was it not possible to also dynamically change the "File on server" label on the left of the textfield, or that's just some forgotten detail?

I'm not sure what you mean. Did you try it and it didn't work for you?

**Comment by nekohayo** [comment]
I'm still running the stable version (7.8.2, authentic theme 21.09.2) and this change isn't yet landed there, so I'm just basing myself on your own demonstration video above: at the 6 seconds mark, when you click "One file per server", the "File on server" label does not change to "Folder path on server" like I was originally requesting. It only changes the dimmed placeholder text of the field, not the label in front of the field, which remains misleading.

**Comment by iliajie** [comment]
> label does not change to "Folder path on server" like I was originally requesting. It only changes the dimmed placeholder text of the field, not the label in front of the field, which remains misleading.

I beg your pardon, as I don't understand exactly what you mean? What is misleading?

The helper text (i.e. `placeholder` attribute) will _only_ change. We aren't gonna change the actual value that user enters, if that's what you mean.

**Comment by nekohayo** [comment]
Not talking about the value, but about the label on the left in your video:

![image](https://github.com/virtualmin/virtualmin-gpl/assets/479401/a4c55d7d-e73d-41b7-bf33-725e9ff92b01)

**Comment by iliajie** [comment]
Ahh, now I see what you mean. Well, everything is a file in Linux. 🙂 But your suggestion sounds reasonable. I'll have a look ..

**Comment by iliajie** [comment]
Alright, as running pre-release tests I have discovered a bug that was happening in the old Gray Theme.

Also, I fixed the code to update the label you mentioned earlier.

All is done!

Thanks for the initial suggestion! It will help users to get around it better!
