### ISSUE TITLE
Subtle color-tinted dark theme sidebar background color based on light theme's sidebar color

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#650]
Related to the wish for an automated light/dark ("system") theme (#535), I have a complementary idea: automatically tinting the sidebar to match its light theme's primary color. An example mockup can be found below.

---

## When is this useful?

I recently discovered that you can choose one of the primary preset colors for the Authentic Theme's sidebar, in `Theme Configuration > Navigation Menu > Color Palette`:

![image](https://github.com/virtualmin/virtualmin-gpl/assets/479401/dba3bd8d-71fd-40b0-a52a-51deed93a0ef)

...and I found this to be very useful to be able to provide a visual distinction between my various home servers, because I often work on them all at once with multiple tabs/windows open, and being able to color their sidebars by "dangerosity" lets me avoid mistakes.

For example,
* my trashy sandbox server is "Gold" colored;
* my "kind-of production, but still considered unsafe" server is "Red" colored;
* my real "production" server (where I host my email etc.) is "Green" colored.

... that way I don't have to think about server names / look at the URL bar all the time. Especially when some vservers are present on multiple such servers (during migrations etc.), the colors are nice to avoid confusion.

However, when using the dark theme, those colors disappear completely.

So while my "red-colored" server could easily be spotted from 10 meters away:

![light theme - red](https://github.com/virtualmin/virtualmin-gpl/assets/479401/b28228c6-2ed3-4c4b-9b0e-5a10f934c4ba)

...at night, it becomes identical to all other servers:

![dark theme - current](https://github.com/virtualmin/virtualmin-gpl/assets/479401/0b2efe7d-22be-4b7e-9602-bf74006f2b09)

## Possible solution

One way this could maybe be conveniently achieved, would be for the dark theme to automatically inherit & tint its sidebar background color based on the light theme's chosen color. Maybe with some CSS filters (with less saturation and brightness and higher contrast), etc. So in the case of my red-colored server for example, it could become a bit like this, still dark but quickly recognizable:

![dark theme - proposed](https://github.com/virtualmin/virtualmin-gpl/assets/479401/79d42ba7-5294-42d1-8da1-76c6e3aa71d7)

Throwing the idea out there. I hope you find the suggestion interesting 🦉

**Comment by jcameron** [comment]
@iliajie what do you think about this one?

**Comment by iliajie** [comment]
> @iliajie what do you think about this one?

Jamie, I feel that adding a tint to the dark palette's navigation menu detracts from its aesthetics.

Jeff, there is an option in Authentic Theme configuration page, which enables you to add HTML snippet to the navigation menu (for distinguishing purposes).

**Comment by iliajie** [comment]
I will close this one, as I won’t be able to implement it.
