### ISSUE TITLE
Server "Transfer" feature does not check destination server for required features (such as MariaDB) to enable the resulting server

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#652]
This is a corner case, which I discovered while migrating a website from a Debian 11 server Virtualmin 7.8.2 to another (Debian 12) server running Virtualmin 7.8.2. I'm reporting it in case you want to add an extra safety check for this:

* _If_ you are migrating a vserver/website that uses the usual HTTP+PHP+MariaDB+LetsEncrypt combo,  
_and_ for any reason the destination server's MariaDB daemon/service/server is down*...
* ... _then_ : the Transfer process will seemingly happen without warnings, but in reality it will silently fail behind the scenes on the resulting server, because mariadb was not online to receive, set up, and import the incoming mariadb database tables/data.

You only find out about this when you look at the website, which says it can't connect to the DB, then you see that mariadb is down for whatever reason, start mariadb, then wonder why the website still can't connect to the DB… so you go into that vserver's databases list, click the database (which apparently exists, alongside with the vserver's user for it), and you see:

```
Database server type | MariaDB
Size on disk | 8 KiB
Files on disk | 1
Number of tables | 0
```

...and if you click on "Manage Database", you get: 

> This database has no tables.

Uh oh.

Essentially, you have to do the Transfer again (to be sure stuff really is set up properly), which isn't catastrophic… _if_ you haven't set the source server to "Delete from this system" after the transfer (thankfully, I didn't, but it _could_ happen for some users...). So there's some potential danger here.

---

*:  in my case, the reason why mariadb was down at the time of the Transfer is: mariadb was killed overnight by the OOM-killer, possibly because ClamAV was eating the RAM or something 🫠

**Comment by jcameron** [comment]
It's surprising that the restore succeeded even when MySQL was down! But I will add an extra check to fail fast on a restore if MySQL isn't running ...

**Comment by nekohayo** [comment]
Cool, this will probably make it safer for other users potentially encountering this kind of weird timing badluck! Thanks :)
