### ISSUE TITLE
Secondary DNS settings

### ISSUE THREAD

**Issue by unsalkorkmaz** [virtualmin/virtualmin-gpl#655]
Hello,

![Screenshot 2023-09-27 at 17 12 29](https://github.com/virtualmin/virtualmin-gpl/assets/207720/2e0cbeae-2e1b-494a-afe2-621518cd89ec)

I want upper example IPs in **Allow transfers** but when created a new domain, it becomes like bottom example. I added those in **Allow transfers from...** list and in Other DNS Servers list.. What am I missing? Is it a bug?

![Screenshot 2023-09-27 at 17 40 50](https://github.com/virtualmin/virtualmin-gpl/assets/207720/eb809c15-0b2f-4fb5-af41-6b698d08cd8a)

**Comment by jcameron** [comment]
Hmm, looks like we're not respecting those extra allow-transfer and also-notify IPs when Virtualmin creates a domain. Let me see about fixing that...

**Comment by jcameron** [comment]
Actually, the global settings on that page should be added to /etc/named.conf , and thus will apply to all domains.

Are transfers not being allowed from those extra IPs?

**Comment by unsalkorkmaz** [comment]
Yeah, always get denied

**Comment by jcameron** [comment]
If you add the IP to the `allow-transfer` block at the zone level and restart BIND, does the transfer work?

**Comment by unsalkorkmaz** [comment]
Yes

**Comment by jcameron** [comment]
Wow, and here I was assuming that the global allow-transfer IPs would be also allowed even when they're set at the domain level. The next Virtualmin release will fix this by including them in the per-zone list as well, if needed.
