### ISSUE TITLE
php-fpm server connection HELP needs updating as the default switched to unix socket file

### ISSUE THREAD

**Issue by verne-work** [virtualmin/virtualmin-gpl#656]
the old help file (English version) virtualmin-gpl -- help -- template_php_sock.html has:

```
By default, Virtualmin will configure your webserver and PHP server to use
a <tt>localhost</tt> TCP port to communicate. However, you can instead
select to use a Unix domain socket file, which reduces the chance of port
clashes.
```

one place, maybe the only one, to view this help file is in Virtualmin -- System Settings -- Server Templates -- (choose a template) -- PHP Options, near the bottom for `FPM server connection`

A github update on Jan 1 2022  [Switch default FPM socket mode to a file which is more secure](https://github.com/virtualmin/virtualmin-gpl/commit/32d1661fc49c61c1b91f9726fa91da40ff86e82b) changed the default to unix socket file with the addition in CONFIG of

`php_sock=1`

I suggest the help file be updated to something like:

```
By default, Virtualmin will configure your webserver and PHP server to use
a Unix domain socket file to communicate. However, you can instead
select to use a <tt>localhost</tt> TCP port, which could have a chance of
port clashes.
```

I realize this change, any change, to help text is complicated as all the translation files also need updating.

**Comment by jcameron** [comment]
Thanks, I'll fix that!

**Comment by iliajie** [comment]
> I realize this change, any change, to help text is complicated as all the translation files also need updating.

Not at all, it's all automated https://github.com/virtualmin/virtualmin-gpl/commit/d761a2ecfb9d17706242cdef94aa916f59c3d531.
