### ISSUE TITLE
LE wildcard certificate request fails in domain creation time

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#657]
Hello, Jamie!

If we enable `letsencrypt_wild` to `1` in Virtualmin Configuration, then LE validation fails upon domain creation time. When wildcard is disabled, then it works just fine (upon domain creation time).

I have tried it with Cloudflare.

However, when I try to request SSL certificate afterwards, it works most of the time. If it doesn't work from the first try, it always works from the second.

Perhaps, we don't add the right `_acme-challenge` record in case of wildcard domain?

**Comment by jcameron** [comment]
Does it fail, and if so what error message are you getting?

Or does it just hang?

**Comment by iliajie** [comment]
> Does it fail, and if so what error message are you getting?

It fails with error message:

```
Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
  Domain: sub16.cloudmin.dev
  Type:   unauthorized
  Detail: Incorrect TXT record "vXD8MdaeAfRRq3GyDyvyobd3W0inG06422YGcnwWxvQ" found at _acme-challenge.sub16.cloudmin.dev

```

**Comment by iliajie** [comment]
To be clear I was creating parent domain `sub16.cloudmin.dev` with Cloudflare, and wildcard enabled by default in Virtualmin Configuration page.

**Comment by jcameron** [comment]
Does it work as expected if you request an LE cert after the domain is created?

**Comment by iliajie** [comment]
.. with the second attempt 90% of the time.

**Comment by jcameron** [comment]
Hmm, I wonder if the issue is that a totally new domain registered with Cloudflare isn't resolvable right away?

**Comment by jcameron** [comment]
Yeah but without a wildcard, web-based validation can be used..

**Comment by iliajie** [comment]
Yeah, meaning we're not adding the right acme challenge records with Cloudflare? Also, why does it work from the second attempt when renewing manually?

**Comment by jcameron** [comment]
Maybe there's some lag between when the challenge record is added and when it's visible?
