### ISSUE TITLE
new subservers php-fpm chroot directory set to another servers chroot

### ISSUE THREAD

**Issue by hydazz** [virtualmin/virtualmin-gpl#658]
when creating a subserver (havnt tested it with main servers), by default, the `chroot` option in php-fpm is set to the wrong chroot directory, 

![image](https://github.com/virtualmin/virtualmin-gpl/assets/53986978/fd70e003-a8f9-4f9f-8bea-3a430688625a)

I have not edited `chroot = /home/chroot/1687503619238689` here, thats how it generated, `1687503619238689` is the domain id of a completly different domain, though it got every other option correct?

not the biggest of issues, but caused some headaches when diagnosing missing files

**Comment by hydazz** [comment]
the domain for that subdomain is also not a chroot, so that chroot should of been set to `/home/.../domains/storage....`

**Comment by iliajie** [comment]
> thats how it generated, `1687503619238689` is the domain id of a completly different domain

What different domain .. a parent domain?

**Comment by hydazz** [comment]
> > thats how it generated, `1687503619238689` is the domain id of a completly different domain
> 
> What different domain .. a parent domain?

no, a completly different domain
![image](https://github.com/virtualmin/virtualmin-gpl/assets/53986978/f52348cd-87ac-487c-9a31-c1f895b7b22c)

i created the subdomain `storage.<>.services` and the php-fpm chroot was set to the chroot of the `.io` domain (the selected one here)

the `.services` user is also not chrooted, so it does not make sense to why its php is chrooted to /home/chroot in the first place

**Comment by hydazz** [comment]
its also repeatable, just tested it any subdomain (does not apply to domains) created has their chroot set to `chroot = /home/chroot/1687503619238689` by default

**Comment by hydazz** [comment]
deleting the `.io` domain (1687503619238689), the chroot is now set to another domain/id, which is still not the correct one for that domain

**Comment by iliajie** [comment]
I don't think we should add `chroot` record to FPM pool unless jail is enabled. The patch in the PR above.

**Comment by hydazz** [comment]
Indeed, just realised. But still for the users/domains that are chrooted, mystery why they are getting the wrong chroot path?

**Comment by iliajie** [comment]
> mystery why they are getting the wrong chroot path?

I don't believe I'm experiencing the same issue on my end.

**Comment by AndyAlvarezDev** [comment]
@iliajie I don't know if you remember, but in the forum in private, I had told you about this matter a while ago... now the forum doesn't work otherwise I would look for the link...

**Comment by AndyAlvarezDev** [comment]
It is as described here, the subservers with php-fpm and chroot always get the same invalid directory... I have been reporting this for months!

**Comment by jcameron** [comment]
This one will be fixed in the next Virtualmin release

**Comment by hydazz** [comment]
unrelated, unsure if planned or not, but would be nice to have an manual update chroot button, which refreshes the chroot like it does with the schedule feature

**Comment by iliajie** [comment]
> unsure if planned or not, but would be nice to have an manual update chroot button, which refreshes the chroot like it does with the schedule feature

I think you can just re-save **Administration Options ⇾ Edit Owner Limits** page.
