### ISSUE TITLE
cPanel migration to Virtualmin

### ISSUE THREAD

**Issue by ecoin-etn** [virtualmin/virtualmin-gpl#66]
The migration of a new domain just set-up in cPanel WHM 11.48.5 (build 3) over to a freshly installed and untouched Webmin 1.900 / Virtualmin 6.04.gpl fails with the following error message

[root@server cpanel_backup]# virtualmin migrate-domain --type cpanel --source /cpanel_backup/backup-12.3.2018_10-51-10_cptovmin

Validating migration file .. 
.. validation failed : Could not find mail aliases file for cp2vmin.com in backup

As said, the domain was just initialised within cPanel with one email account and one email forwarding address. A full backup was send over to the virtualmin server as a tar archive. The archive was extracted into the folder /cpanel_backup/backup-12.3.2018_10-51-10_cptovmin

Which is the missing mail aliases file, where do I expect it to be found in the cPanel backup?

**Comment by ecoin-etn** [comment]
The problem persists in Virtualmin 6.05.gpl.

**Comment by ecoin-etn** [comment]
Certainly, here's the link to a ZIP file of the backup

http://www.euronetwork.com/BiNXZLxfXn2GHhOeniKIJ9sUSTCO/backup-12.3.2018_10-51-10_cptovmin.zip

**Comment by ecoin-etn** [comment]
Certainly yes, just send you an reply to you email containing a link to a ZIP file.

**Comment by ecoin-etn** [comment]
Today I've tried to import the linked ZIP file with the web interface 
and it did pretty well.

So I'll gave a different domain managed currently by a cPanel server a 
go. By importing a full cPanel backup as tar.gz file through the web 
interface of Virtulamin it converted all features as set on the cPanel 
server properly, i.e. subdomains, email accounts, MySql databases.

As it seems the problem occur only when trying to import using the shell 
script.

**Comment by shoulders** [comment]
this should be closed because:
- end user support
- I just imported from cpanel (with some minor issues which I am going to report)
- date 2018
