### ISSUE TITLE
Navigation menu reorganization

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#663]
I would like to suggest to reorganize some parts of Virtualmin navigation menu, in particular those parts related to virtual server itself.

I think **Administration Options**, **Server Configuration** and **Services** could be replaced by:

  1. **Control Center**
  2. **DNS Configuration**
  3. **Web Configuration**
  4. **Mail Configuration**

Example of items' details:

 * **Control Center** could include:
    * Change Backups Excludes (curr. Excluded Directories and DBs)
    * Change Domain Name
    * Change IP Address
    * Clone Virtual Server
    * Edit Owner Limits
    * Edit Resource Limits
    * List Sub-Servers
    * Manage Extra Admins
    * Move Virtual Server
    * Setup SSL Certificate
    * Switch To Server's Admin
    * Transfer Virtual Server

 * **DNS Configuration** could include:
    * DNS Options
    * DNS Records
    * DNS DKIM Record (as current DomainKey Options page minus options, only full record display)
    * Suggested DNS Records

* **Web Configuration** could include:
   * Configure Website
   * Configure SSL Website
   * Edit Web Pages
   * PHP Options
   * PHP-FPM Configuration
   * Proxy Paths
   * Proxy Settings (curr. Edit Proxy Website)
   * Website Options
   * Website Redirects
   * Preview Website
   * Protected Directories

* **Mail Configuration** could include:
   * Email Settings
   * Signing Keys (as current DomainKey Options page minus DNS record)
   * Signup Email
   * Spam and Virus Delivery
   * SpamAssassin Configuration
   

Additionally **Logs and Reports** would get:
   * Disk Usage

**Comment by marclaporte** [comment]
@nekohayo @fakemoth

**Comment by jcameron** [comment]
Not sure I like "Control Center" as a name ... how about something like "Manage Server" or "Manage Domain" ?

**Comment by iliajie** [comment]
"Management" seems to unspecific to me ..

.. "Manage Server" sounds somewhat alright. Although probably "Manage Virtual Server" would be a bit more fitting to the idea of "virtual servers" rather thank "domains" .. ? But it's a bit too long now ..

Perhaps we could just call it "Server Actions" .. ?

If not what other suggestions do we have?

**Comment by fakemoth** [comment]
"Manage Server" is the only alternative I can think to "Management". Others will have better suggestions I am sure. "...Actions" sounds too... Steven Seagal :) "Manage Virtual Server" is a mouthful and sooner or later will hinder something in the side bar... "Virtual servers" - well it is about THAT specific server not all etc. "Virtual server" (singular) doesn't tell you that you can manage it there, and so on.

**Comment by iliajie** [comment]
Well, okay. But I think I like "**Server Ops**" the most for now. "Ops" clearly implies operations or actions related to the server. "Ops" is a contemporary term, familiar to many in the tech world, making the menu name sound up-to-date.

**Comment by iliajie** [comment]
Alrighty, cool! So, shall I start menu rework then?

**Comment by jcameron** [comment]
Sure, please send me some PRs!

**Comment by iliajie** [comment]
Will do!

**Comment by iliajie** [comment]
Alright, the PR is here: https://github.com/virtualmin/virtualmin-gpl/pull/669. Further discussion should happen on the PR.

**Comment by jcameron** [comment]
Best to only close this ticket once the PR is submitted..

**Comment by marclaporte** [comment]
PR is now merged.

**Comment by iliajie** [comment]
> PR is now merged.

Thanks Marc for the heads up!
