### ISSUE TITLE
Feat: Add DB server host and port in template variable list

### ISSUE THREAD

**Issue by xxorax** [virtualmin/virtualmin-gpl#666]
The template variable list provides these var MYSQL_DB, MYSQL_USER and MYSQL_PASS, however the server host and port are not available.

It should be useful to have also variables like:
- MYSQL_HOST : localhost or specified remote host
- MYSQL_PORT : 3306 or specified port
- optionally MYSQL_HOSTPORT="$MYSQL_HOST:MYSQL_PORT"

And the same for Postgres

Looks like it's around [here](https://github.com/virtualmin/virtualmin-gpl/blob/d100ec5b568ba276362a5ebd8b3740eff6ee71b3/virtual-server-lib-funcs.pl) and [here](https://github.com/virtualmin/virtualmin-gpl/blob/d100ec5b568ba276362a5ebd8b3740eff6ee71b3/feature-mysql.pl#L2035C5-L2035C28).

I will require also to update [the very useful page about it](https://www.virtualmin.com/documentation/system/template_variables/).

Thanks !

**Comment by jcameron** [comment]
Good idea! I will add MYSQL_HOST and MYSQL_PORT template variables in the next release ...

**Comment by xxorax** [comment]
Hi
I think it still missing in the last release.
Thanks

**Comment by iliajie** [comment]
> I think it still missing in the last release.

https://www.virtualmin.com/docs/installation/troubleshooting-repositories/

**Comment by xxorax** [comment]
My bad it's working well !
I was looking in the env vars in the post-action command... sorry
