### ISSUE TITLE
Filemin - bug when editing a file that contains regex and &amp;

### ISSUE THREAD

**Issue by pixel-paul** [virtualmin/virtualmin-gpl#668]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     CentOS Linux 7.9.2009     |
|  Webmin version      |     2.101      |
|  Usermin version     |     2.001     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.04      |
|  Package updates     |     All installed packages are up to date   |

If I have a web page that contains a script such as:

`artwork_url = nowPlaying.current.metadata.artwork_url.replace(/&amp;/g, "&");`

When I edit the page, the `&amp;` is converted to `&`:

`artwork_url = nowPlaying.current.metadata.artwork_url.replace(/&/g, "&");`

**Comment by jcameron** [comment]
@iliajie could this be due to some HTML escaping?

**Comment by iliajie** [comment]
Yes, but ui was fixed in the latest Webmin 2.104.

**Comment by pixel-paul** [comment]
Ah, ok thanks!

I wasn't quite sure where to post filemin related issues, so I'll post to and check out the webmin repo next time.
