### ISSUE TITLE
No system information

### ISSUE THREAD

**Issue by arpio** [virtualmin/virtualmin-gpl#67]
System Information with gauges gone after upgrade to 6.05 yesterday.
Debian 9 / Webmin 1.900

![screenshot from 2018-12-05 03-41-49](https://user-images.githubusercontent.com/24844259/49508376-cc5bda80-f83f-11e8-86db-ea1b056888eb.png)

**Comment by arpio** [comment]
I'm using the 19.22-beta2 and everything enabled in the System Status. I also tried the stable 19.21 still nothing. With 19.21 the Dashboard tab in the sidebar is complete empty.

**Comment by rostovtsev** [comment]
You need to make sure that you are really running latest Webmin (1.900). If you do, you can go to theme configuration and at the bottom of the screen install the latest development theme version. It should just work out of the box.

**Comment by arpio** [comment]
Yes, I'm running Webmin 1.900 and latest development theme version 19.22-beta2.

![screenshot from 2018-12-06 00-48-55](https://user-images.githubusercontent.com/24844259/49569330-dee21c80-f8f0-11e8-8c3c-f463ad95f74d.png)

If I update to Virtualmin 6.05 then system information and the gauges disappear.

**Comment by rostovtsev** [comment]
Are you signed in as a reseller or simply root user?

**Comment by arpio** [comment]
I tried both logins. No changes.

**Comment by rostovtsev** [comment]
Let me suppose that this is the clean install and you haven't saved any Virtualmin configuration yet?

**Comment by arpio** [comment]
Yes, It's a clean install with the install script. On a minimal debian system. After that only regular updates with apt.

**Comment by rostovtsev** [comment]
Okay, does it look like there are no checkboxes/radios checked/selected. Like this:

![image](https://user-images.githubusercontent.com/4426533/49576553-85143d80-f956-11e8-9137-bb59dba94549.png)

**Comment by rostovtsev** [comment]
What is the output of:

```
cat /etc/webmin/virtual-server/config |grep show_sysinfo
```

**Comment by arpio** [comment]
Working now.

![screenshot from 2018-12-06 03-20-30](https://user-images.githubusercontent.com/24844259/49578032-055e8280-f906-11e8-9aed-dadf025aa75f.png)

Was not selected at all. Not "No" and not "Yes". After I selected No everything is back.

I think we can close the issue.

Thanks

**Comment by arpio** [comment]
Yes to both questions. My install was with webmin-virtual-server 6.04.gpl. It happend after I upgraded to 6.05gpl.

**Comment by rostovtsev** [comment]
Do you have `/etc` directory backed up? What would be the output of

```
cat /etc/webmin/virtual-server/config |grep show_sysinfo
```

**Comment by arpio** [comment]
Right now its:
show_sysinfo=2

On the backup:
show_sysinfo=

**Comment by rostovtsev** [comment]
Okay, I will install _Debian Minimal_ with _Virtualmin GPL_ to double check.

**Comment by rostovtsev** [comment]
> Was not selected at all. Not "No" and not "Yes". After I selected No everything is back.

Were other checkboxes/radios not selected as well?

**Comment by arpio** [comment]
No, only the one in the screenshot.

**Comment by rostovtsev** [comment]
I have just installed clean Debian Minimal with Virtualmin GPL and it seems to work fine.

Are you sure you didn't brake config manually?

How is that possible that `show_sysinfo=` is empty?

**Comment by rostovtsev** [comment]
> No, only the one in the screenshot.

In the screenshot all of theme are missing, because I broke config on purpose for testing.

**Comment by rostovtsev** [comment]
Okay, I see now how it happened. It needed to be saved at least once with new Virtualmin release.

[Fixed.](https://github.com/virtualmin/virtualmin-gpl/commit/cab79bcf682290d723fad940cf80e15cd3e95070)

Thank you for reporting.
