### ISSUE TITLE
Feature: The ability to add MariaDB database users with their own password and assign them to a choosen database

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#683]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.101      |
|  Usermin version     |     2.001     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.04      |
|  Package updates     |      5  package updates are available   |

### Explain the issue
I don't understand why there is only one MariaDB username and password as this can't be safe. If one of your CMS gets compromised, the rest probably will do as I guarantee that hackers know that Virtualmin shares SQL credentials (by defaul) across a whole account/virtual server.

I do come from the cPanel world where I could create and independent Database username and password and then assign it to a database of my choice, and it is this that I would like in Virtualmin.

- I do not want to expose my virtual server username
- If i change the MariaDB password I have to change it on all of my CMS.
- A CMS with these details can access other databases
- this does default practice does not seem safe,
- Virtualmin users (i.e. clients) cannot be using Webmin to setup their databases. it should all be handled in module.

### Workaround
Create MariaDB user with Webmin, and then assign it to your choosen database. Give these credentials out instead.

This adds a lot of work if you have more than a couple of websites, i.e. clients.

### Proposed Solution

Update the 2 following tabs, maybe into one allow the adding of additional SQL users. These would be only for this virtual server and its sub-servers,this also addresses #135.

Virtualmin --> Edit Database --> Usernames
Virtualmin --> Edit Database --> Passwords

Maybe a simple wizard like cPanel but this is definitely optional.

thanks

**Comment by iliajie** [comment]
Hello,

You can already do it by creating a new user using **Edit Users** page and granting this user database access.

**Comment by shoulders** [comment]
But this creates another virtualmin user with all that comes with it, i just want additional SQL users.

I do not want more accounts with emails and other associated stuff. This will get messy.

:smile:

**Comment by iliajie** [comment]
I think this is a good idea to be able to list and add extra MySQL-only users in Virtualmin directly.

@jcameron Jamie, what are your thoughts on it?

**Comment by jcameron** [comment]
Sure, we could potentially do that. Although it would be the same as creating a user without email enabled, but with database access...

**Comment by shoulders** [comment]
> Sure, we could potentially do that. Although it would be the same as creating a user without email enabled, but with database access...

or ftp access and home directory quotas/access and so on. This account should be purely for SQL/MySQL/PostgreSQL...

Maybe a section in the 'edit user' to configure the fine grain SQL permissions for that user?

**Comment by jcameron** [comment]
I'll look into this, but no guarantees as this isn't a feature request we've received before, and I'm leery of adding too much complexity in the UI.

**Comment by shoulders** [comment]
this is now added as a pro feature

https://www.virtualmin.com/docs/professional-features/#manage-extra-database-users

**Comment by iliajie** [comment]
That's right! Thanks for the update!

**Comment by James-Oakley** [comment]
There is a setting in virtual server templates to let you set a standard prefix for additional databases. However database users seem to be created always with a name I choose, followed by @, followed by the virtual server domain. Is there any way to change this (so that it starts with the linux username and then an underscore, instead of @ domain, for example)?

**Comment by iliajie** [comment]
Hello,

> There is a setting in virtual server templates to let you set a standard prefix for additional databases.

Which option in particular are you referring to?

**Comment by shoulders** [comment]
I am up for this if possible.

I have not used pro features yet so I am not fully qualified on this.

Off to Install pro now 😃

**Comment by iliajie** [comment]
> However database users seem to be created always with a name I choose, followed by @, followed by the virtual server domain. Is there any way to change this (so that it starts with the linux username and then an underscore, instead of @ domain, for example)?

You can choose the mail user format in "System Settings ⇾ Server Templates: Edit Server Template / Mail for domain" page, using "Format for usernames that include domain" option.

**Comment by James-Oakley** [comment]
> You can choose the mail user format in "System Settings ⇾ Server Templates: Edit Server Template / Mail for domain" page, using "Format for usernames that include domain" option.

Thanks, but I take it no comparable setting for database users at present?

**Comment by iliajie** [comment]
> Thanks, but I take it no comparable setting for database users at present?

Check out the "System Settings ⇾ Virtualmin Configuration: Defaults for new domains" page and the "Domain name style in username" option. Though, it doesn't impact new mail users, only the domain owner.
Jamie, is there a way to configure prefixes for new mail users? Also, the "Domain name style in username" option doesn't seem to support templating when used with regex. For example, something like u-[0-9]{4}-$DOM won't work.

**Comment by jcameron** [comment]
Do you mean you want to change how the domain name is converted to a prefix for new users?

**Comment by iliajie** [comment]
Yeah, I think, it should be possible to substitute template variables like `$DOM` and other common ones within regex patterns like `u-[0-9]{4}-$DOM`.

**Comment by jcameron** [comment]
What would it mean to use a regexp here?

**Comment by iliajie** [comment]
It means that when the `example.com` domain is created, using the `u-[0-9]{4}-$DOM` regex in the "Domain name style in username" field would result in a domain owner named `u-1234-example.com` rather than `u-4768-DOM`.

**Comment by jcameron** [comment]
Oh I see ... that actually seems pretty reasonable!

**Comment by James-Oakley** [comment]
>> Thanks, but I take it no comparable setting for database users at present?
> Check out the "System Settings ⇾ Virtualmin Configuration: Defaults for new domains" page and the "Domain name style in username" option. Though, it doesn't impact new mail users, only the domain owner.

Found it. That looks like it affects the Linux username created for a virtual server, and I've no particular wish to change that default. I'm trying to have a MariaDB user named domain_user rather than user@domain, and can't see how that option would help.

**Comment by jcameron** [comment]
Maybe then what we need is a separate option for the MariaDB username format - no need to make it too complicated with any kind of templating.
