### ISSUE TITLE
Feature: Account Plan - Initially selected option

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#684]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.101      |
|  Usermin version     |     2.001     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.04      |
|  Package updates     |      7  package updates are available   |

## The Issue
Currently when creating a virtual server your Server Template is pre-selected to the ones you set:
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/80886d57-b0d3-4f76-9fb3-dbbc496257df)
- Virtualmin --> System Settings --> Server Templates --> <your choosen template --> Edit template section: Basic settings and usage
  - Initially selected template for top-level servers
  - Initially selected template for sub-servers

The Account Plans do not have an equivalent option. They are listed in alphabettical order and the first one wins when you are creating a virtual server. (Virtualmin --> Create Virtual Server)

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/a943c3d4-1951-4e4f-9c27-1ea6a3330760)

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/b5393019-f266-40d7-ad91-b6d71f53fb30)

## The request
Is it possible to get an option to set the preferred 'Account Plan', if it is possible?

I must admit I have not got my head around everything yet, so I don't know if this was not implemented because of use or technical issues.

**Comment by jcameron** [comment]
That's an excellent suggestion ... I'll look into adding this, and update this ticket when it's done.

**Comment by jcameron** [comment]
Actually, on the **Account Plans** page there's already an option down the bottom below the list to select the default plan..

![image](https://github.com/virtualmin/virtualmin-gpl/assets/102706/52069472-51b8-4c95-9ed3-f516fe64251f)

**Comment by shoulders** [comment]
wow, I cannot believe I missed that. I was looking in the plans for the option just like the server template.

the location of this options makes complete
