### ISSUE TITLE
Restore from Ubuntu 20 to Ubuntu 22 made a mess with user ids.

### ISSUE THREAD

**Issue by alexbogias** [virtualmin/virtualmin-gpl#685]
I tried to restore multiple domains and subdomains from an Ubuntu 20 to 22 and user ids had a class. I choose Ubuntu 22 minimal and after clean install has an already created a user with username "user" with id 1000. I tried to restore 100+ domains but restore failed in user id already exists. I tried to overwrite restore-domain with --reuid and --fix which completed but enable and disable features and change php versions in subdomains of the 1st domain throw errors. I tried a clean install and deleted this user with deluser but still this parent domain got 1001 id and errors continue. Maybe user id part need a rewrite so migrations would be easier?

**Comment by jcameron** [comment]
That seems like a bug - Virtualmin should be re-allocating UIDs on restore to avoid clashes! 

Does this `user` account show up in the /etc/passwd file?

**Comment by alexbogias** [comment]
Not anymore... and the old 1000 user has this uid

**Comment by alexbogias** [comment]
But all subdomains in this parent cant validate.
![image](https://github.com/virtualmin/virtualmin-gpl/assets/1313467/1e606603-7852-4713-9ee2-29297ce164e1)

**Comment by alexbogias** [comment]
I tried change Services -> Configure Website / Configure SSL Website -> User and groups back to 1000 but then got Forbidden errors so i tried and reverted back because the server is live

**Comment by jcameron** [comment]
Did you get that validation error immediately after restoring, and without making any other changes?

**Comment by alexbogias** [comment]
Yeah immediately in restore-domain cli and after it

**Comment by jcameron** [comment]
Would it be possible to get a copy of a backup from your system with only a single domain in it which exhibits this problem? That way I can try a restore on a test Ubuntu 22 system and see what's going wrong...

**Comment by alexbogias** [comment]
Send you a decreased backup from 5G to 45mb in your email. I wish files deletion will not make it unusable.. 
Packed the parent domain and just 1 subdomain.
Let me know if you need any other file

**Comment by jcameron** [comment]
I didn't see the email, sorry. Did you send it to jcameron@virtualmin.com ?

**Comment by alexbogias** [comment]
@webmin

**Comment by jcameron** [comment]
I didn't see that wetransfer, sorry. Can you re-send it? I might have deleted it as spam!

**Comment by alexbogias** [comment]
Of course.. Now send it to both mails

**Comment by alexbogias** [comment]
@jcameron I just notice that in Webmin-> System  -> User and groups the userids of those 2 users is different than /etc/passwd and /etc/groups. Do you think that it is safe to swap them and check if everything is ok?

**Comment by alexbogias** [comment]
And If I tried to enter this userid from /etc/passwd in this Virtual server -> Services -> Configure (SSL) Website -> Users and groups I get:
![image](https://github.com/virtualmin/virtualmin-gpl/assets/1313467/784cdd52-9b49-4b85-9941-16c4f32c4e0a)

If I chose from the list the virtualmin one is ok...
Looks like virtualmin and /etc/passwd / group is not in synced for this user

**Comment by jcameron** [comment]
So I tried to restore one of those backups from the CLI with a command like `virtualmin restore-domain --source /tmp/cms4.nelios.com.tar.gz --all-domains --all-features` and it worked just fine. I even intentionally created a UID clash and Virtualmin did correctly re-allocated a new UID..

What error did you get when you originally restored without the `--reuid` flag?

**Comment by alexbogias** [comment]
Do you know where I can find those logs on my machine?

**Comment by jcameron** [comment]
They might be visible at Webmin -> Webmin Actions Log..

**Comment by alexbogias** [comment]
Sorry but I cant find there... You can close it if you want due to lack of info :(

**Comment by jcameron** [comment]
It's possible this issue is somehow specific to Ubuntu 22 ... let me do some more tests there, but if I can't repro the problem I guess we will have to close this, sorry.

**Comment by alexbogias** [comment]
No problem @jcameron. If will got this again I will ask to reopen and post more info. Thanks a lot for researching ;)

**Comment by jcameron** [comment]
Sorry, but I wasn't able to re-produce this issue ... so I'll have to close this bug.

**Comment by iliajie** [comment]
I can also see that the UID and GID are reallocated. However, having either the same username or the same database login name or database name is a bummer. It just fails then. There should be an option to reallocate usernames as well, I think.

For example if user `my_user1` or restored database login or database or whatever other name exists, it should be reallocated to something else, for example to `my_user1_restored_rand-8-char-str`. It is very common to have name clash upon the restore and making it fail fatally makes no much sense.

Jamie, can we first try to restore with the original name but then if the clash happens, don't die and instead suffix the name? The option can be changed from `Re-allocate UIDs and GID` to `Reallocate user/group names and IDs` or even a new option added, like `Reallocate user and group`.

**Comment by jcameron** [comment]
@iliajie that's an intersting idea, although it could add a lot of complexity! Please open a separate ticket for this..

**Comment by iliajie** [comment]
Done https://github.com/virtualmin/virtualmin-gpl/issues/694.
