### ISSUE TITLE
Initially selected option - Parity between Servers Templates and Accounts Plans

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#688]
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/e2423fb9-0707-4408-849e-1bf2c229e8ed)

The options that set the defaults for these are not in the same relevant location for each type and do not have the same naming convention. So I pro a couple of small fixes:

### 1) Move the 2 following options from with the individual `Server Templates`

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/1eb5facc-3730-42a2-97c3-b6159154e921)

### 2) Rename them and place them as follows:

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/9e2f9d4d-b9e5-4976-bd58-4482e3a6427d)

This is related to #684

**Comment by iliajie** [comment]
I think default template is being set once (or changed very rarely) and I don't see it to be a problem to set it from inside of the template.

**Comment by shoulders** [comment]
It is about consistency with the Account Plans, not a functionality issue.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/95eccc85-ee27-4ad0-8562-f08a096c7dab)

**Comment by jcameron** [comment]
Actually maybe it would be cleaner for account plans to work the way server templates do ...

**Comment by shoulders** [comment]
my thoughts are that the `Account plan` method is better because:

- the `set default template` is not actually an option of the template.
- at a glance you can see what is set as default. otherwise you have to create a virtual template or go through them all to see which is default.
- without editing the template you can change the default one

Either way, if both server templates and account plans use the same, this is still a lot better irrespective of the method you choose.

**Comment by iliajie** [comment]
Yeah, I also like doing in Templates what we already do in Plans in terms of selecting defaults.

**Comment by jcameron** [comment]
I'll play around with the UI a bit and see what looks better ...

**Comment by iliajie** [comment]
I like [this](https://github.com/virtualmin/virtualmin-gpl/commit/320a9116994cec869264d99b5b675ac0eeee4a57) new change more! It's much simpler and clearer! I will close this!

**Comment by jcameron** [comment]
I've also updated the server templates page to work in the same way for setting the defaults.

**Comment by iliajie** [comment]
Great, thanks! And I've also added icons for these new buttons.
