### ISSUE TITLE
"Administration user" section is available for sub-server templates

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#690]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |     All installed packages are up to date   |

## Background
In the `Settings For Sub-Servers` template the `Administration user` section is not there, and I believe this is expected.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/ddf7dc81-8b17-4321-8966-ca364e1df1d0)

## The issue
- When I clone  `Settings For Sub-Servers` template the `Administration user` section is present.
- When i create new template, sub-server only, save it, then re-open it the `Administration user` section is present.

**Blast from the past**
https://n1.virtualmin.com/node/16125
>**Locutus says:** There are some settings in the top-level server default template which cannot apply to a sub-server template, like the Administration user section. I suppose existence of those does not hurt and is simply ignored when it comes to apply the "defaults" to a sub-server template?

>**Jamie Cameron says:** Also, you are right that "Administration user" options shouldn't appear, as they are irrelevant for a sub-server. I will remove those in Virtualmin 3.83.

## Proposed fix
Remove  `Administration user` section as required

**Comment by jcameron** [comment]
Good idea ... I'll fix that.
