### ISSUE TITLE
Virtual Sub-Server showing it belongs to a plan

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#691]
## The Isssue
If you look at the following picture of a sub-server summary you can see it says it belongs to the bronze plan.
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/4edfe522-7380-4007-9932-3ad03bed61d8)

## The Question
Is this correct to show a sub-server's plan?

According to Eric (VM staff), https://forum.virtualmin.com/t/sub-server-account-plan/50910
> A Sub-Server shouldn’t have an account plan associated with it, Account Plans should only be associated with the top-level Virtual Server.

## Proposed fixes
- You could remove the `Account Plan` display for sub-servers
- You could rename `Account Plan` to `Parent Account Plan` and then this would match the `Parent virtual server` below.

**Comment by jcameron** [comment]
Good point, I'll fix this..

**Comment by shoulders** [comment]
this has been fixed with the patch above
