### ISSUE TITLE
`Settings For Sub-Servers` ${PARENT}_ database prefix is ignore in `Settings For Sub-Servers` template, value is pulled from `Default Settings`

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#692]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |     All installed packages are up to date   |

### Can you clarify the following for me:
A `Sub-Server` template should take it's inherited settings from the parent (top-level sever) and not the `Default Settings template.

### The Template Setups
**1) I have the following `server templates` setup:**

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/b384065c-bcfa-4d43-a23e-c6bd62f2202b)
NB:  Only `Settings For Sub-Servers` is a `Sub-Server` template

**2) In the `Default Settings` template (MariaDB database):**

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/b7da0cf0-5214-48dc-8618-42cf5b0906b3)

**3) In my `Internal` server template (MariaDB database):**

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/936fbe0e-a2b0-45ca-83bf-44affa7bb533)

**4) in the `Settings For Sub-Servers` template (MariaDB database):**

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/ef5dba15-f9fc-408e-ba61-d7d7b0c40e59)

### The scenario

I wanted to use `${PARENT}_` in my sub-server template so my databases would have the same prefixes as the parent virtual server (yes, like cPanel :smile:) however this was just ignore and the value was pulled from the `Default Settings` template.

- I setup the following virtual servers
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/c6054147-7c44-426a-9781-a1ffabee99ec)
- But we will just considering the `wordpress.quantumwarp.com` which is a **Sub-Server** of `quantumwarp.com`.
- The account name for `quantumwarp.com` is **chicken** and therefore its databse prefixes are **chicken_** -  for the purposes of this article
- The `Default Settings` template `Prefix for additional databases` =  **${PREFIX}_**
- The `Parent virtual server` uses the `Internal` template which is set to: `Prefix for additional databases` = **From default settings**
- The `Settings For Sub-Servers` template is set to: `Prefix for additional databases` =  **${PARENT}_** 

### The issue

So when i create a new database on `wordpress.quantumwarp.com` it starts with the prefix as follows, not the parent prefix of **chicken_**
  ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/272f28b1-ea1e-4036-8130-28d49a44dc04)

This means it is ignoring **${PARENT}_** in the `Settings For Sub-Servers` template.

I also tried putting  **${PARENT}_** in the parent template and this made no difference.

I think inheritance on this value is broken for sub-servers. There might be other values doing this but I have not checked them.

**Comment by jcameron** [comment]
Sorry, but the way template inheritance works, sub-servers don't inherit from the parent domain's template - only from the default settings. Changing this is probably never going to happen as it would break existing users' expectations, and be complete to implement..

Can you set database prefix in the sub-server template though?

**Comment by shoulders** [comment]
>Can you set database prefix in the sub-server template though?

Do you mean can I manually set one? (i.e. to check if it is the variable that is failing?)
I will go and find out.

>Sorry, but the way template inheritance works, sub-servers don't inherit from the parent domain's template - only from the default settings. Changing this is probably never going to happen as it would break existing users' expectations, ~~and be complete to implement..~~

I think users (I did) expect the settings to be pulled from the parent, other wise what is the point of having a template especially for sub-servers if not to inherit stuff from it's parent. You could just make another server template.

**Comment by shoulders** [comment]
I manually set a prefix in the `Settings For Sub-Servers template` and then created a database. It did not use the manually set prefix (i.e. chicken_).

### Settings For Sub-Servers template
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/9398bca1-b1ec-4727-8da2-9774aa9b7af6)

### Create a new subserver
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/ed2cd778-a18b-4c55-9dc7-01ad13244f37)

### Create a database
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/31cb2f28-1141-4045-8d31-d571d6de064f)

**Comment by jcameron** [comment]
Ok if it's not using the setting from the template, that seems like a bug! I'll take a look ...

**Comment by shoulders** [comment]
@jcameron this one has popped up again now i am adding clients where they have apps with different PHP requirements.

Can you add this one to your list please 😄

**Comment by jcameron** [comment]
Sure, this will be fixed in the next release.

**Comment by shoulders** [comment]
thanks

**Comment by iliajie** [comment]
> Fix inheritance of mysql_suffix

Did you apply this patch https://github.com/virtualmin/virtualmin-gpl/commit/56cdc8ed78a8edd8d90ff851e497c6a21629addf? Did it work for you?

**Comment by shoulders** [comment]
@iliajie I have not applied the patch and tried it. I do not know how to apply these patches to running systems. I have got round to learning that on a Linux system yet. Any pointers welcomed, and I can try later.

**Comment by iliajie** [comment]
> Any pointers welcomed, and I can try later.

```
cd /usr/share/webmin/virtual-server && curl https://github.com/virtualmin/virtualmin-gpl/commit/56cdc8ed78a8edd8d90ff851e497c6a21629addf.patch | git apply --reject --whitespace=fix
```
