### ISSUE TITLE
Feature: phpMyAdmin install script - Remove the requirement for MySQL/MariaDB Database

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#693]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |     All installed packages are up to date   |

### The issue
You need to have a MySQL/MariaDB Database created on a virtual server before being able to install phpMyAdmin otherwise you get this warning.  I don't know why you need this check and rather than being against a database, the check could be against the presence of the server.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/fcf54e83-b36f-4b86-b6e8-cd3ea745d2a8)

### Workaround
- Create a MySQL/MariaDB Database
- Install phpMyAdmin via the script
- Delete the database

### Why is this required
As shown above this can easily be got around so it is not a show stopper.

But consider this, I am installing all of my apps on a subserver so I can point all of my clients to this location instead of them all having their own installed version of phpMyAdmin (and maybe Roundcube). This allows me to keep these apps up to date, I can control access and so on, however this sub-server will not have any databases of it's own.

### Additional (if keeping the check)
Update the error message from `phpMyAdmin requires a MySQL database` to `phpMyAdmin requires a MySQL/MariaDB database`

This will reduce some people thinking they must install MySQL.

**Comment by iliajie** [comment]
> This will reduce some people thinking they must install MySQL.

phpMyAdmin can use database for storage. It isn't strictly required but considering that it's installed for managing MySQL databases, we expect MySQL/MariaDB feature enabled.

**Comment by shoulders** [comment]
> we expect MySQL/MariaDB feature enabled.

I agree, but don't use the presence of a database as an indicator.

**Comment by jcameron** [comment]
I suppose we could pretty easily allow the script to be installed even without a MySQL database, as long as it's not configured to login automatically..

**Comment by shoulders** [comment]
you can login to phpMyAdmin without any databases, no errors are thrown.

**Comment by iliajie** [comment]
> I suppose we could pretty easily allow the script to be installed even without a MySQL database, as long as it's not configured to login automatically.

Alright, fixed here:

https://github.com/virtualmin/virtualmin-gpl/commit/022629bd571a08442949fc39c7f064d00b5ba5b4

**Comment by jcameron** [comment]
Thanks @iliajie for the fix!

**Comment by shoulders** [comment]
@iliajie and @jcameron I just want to say thanks for the fixes and features. I didn't want to say thanks on every thread and spam you inbox :smile:
