### ISSUE TITLE
Restore enhancement request: User and group name reallocation feature

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#694]
Jamie, as we've discussed here https://github.com/virtualmin/virtualmin-gpl/issues/685#issuecomment-1825492519, I suggested that while UID and GID are reassigned during restoration, conflicts with pre-existing usernames, database logins, or database names cause the restore process to fail. To avoid this, it would be beneficial to introduce a feature that also reallocates these names.

For instance, if a username such as `my_user1` already exists, or if there's a database with a conflicting name, the system could automatically rename it to something unique like `my_user1_restored_2023112419225`. Name clashes during restoration are quite common and having the process fail completely because of this doesn't seem practical.

Should it be possible to implement a check during restoration? If a name clash is detected, instead of failing, the system could append a suffix to the name or group. We could modify the existing `Re-allocate UIDs and GIDs` option to encompass user/group names or introduce a new setting like `Reallocate user and group`.

**Comment by jcameron** [comment]
Hmm .. we potentially could do this, but in practice it seems pretty rare that there would be a clash. Because usually the username comes from the domain name, and if that already exists then it would be a case when the domain is being overwritten on restore.

**Comment by iliajie** [comment]
> Because usually the username comes from the domain name, and if that already exists then it would be a case when the domain is being overwritten on restore.

I'm thinking now, that we could solve this problem by just changing defaults and create a username as `example.com` instead of `example` (by default). I personally always liked domain name match the username. It makes things so clear, nice and easy to support. It is pretty common (nowadays) to have the system host both `example.net` and `example.com`..

**Comment by jcameron** [comment]
Sure, users can change that default if they want. Personally I think that just using the first part of the domain name is cleaner, because almost all our customers host a bunch of .com domains with different prefixes..

**Comment by iliajie** [comment]
Alright.

But what if I wanted to merge two servers into one, and eventually restore `example.com` and `example.net` on the new server using default configuration?

**Comment by jcameron** [comment]
I suppose this could be done by changing the username on the source system before backing up. Or actually, you could create example.net on the destination system first, and then restore.

**Comment by iliajie** [comment]
Yes, all this is possible. But a regular use may not be able to figure this out.

  1. How hard it is to change original usernames upon class?
  2. We also need to print a message when UID/GID reallocation happen.

**Comment by jcameron** [comment]
So I thought about this some more, and actually it should be possible to implement this. I'll take a look and let you know how hard it is ...

**Comment by iliajie** [comment]
Excellent! Thanks, Jamie!

**Comment by jcameron** [comment]
Ok this has been implemented, but only when using the `restore-domain` API command with a new `--reuser` flag.

**Comment by iliajie** [comment]
Cool! Can we also add it on the UI too?

**Comment by iliajie** [comment]
Awesome! Thanks!

**Comment by iliajie** [comment]
Jamie, I ran some tests and it doesn't restore the domain on the username clash if there are other names clashes like MariaDB.

**Comment by jcameron** [comment]
> I have created the facility to automatically change database name, login and passwords for most install scripts

Where is this used currently?

**Comment by jcameron** [comment]
Thanks! This could get kind of complex, because potentially a domain can have multiple databases and they all might conflict with existing DBs..

I did add messages telling the user when a UID or GID re-allocation is happening though.

**Comment by iliajie** [comment]
Thanks, I'll run more tests today!

I'm thinking now that we don't need to update databases credentials in scripts if we clearly say there was a clash and all databases and usernames received new names.

I mean, if we already have an option to "reallocate usernames if clashed" we should just do the job for everything. Otherwise this feature may be considered not working as expected.

**Comment by jcameron** [comment]
I think if we do rename the DB user and the DB name, we should at least try to update installed scripts. Renaming the DB user is pretty easy, but I think worth it...

**Comment by jcameron** [comment]
I'll look into this, but we may have to push it till the next release..
