### ISSUE TITLE
Feature: Annotate DS records for registrar (DNSSEC)

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#695]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |      31  package updates are available   |

### The Issue
When you enable `Virtualmin --> DNS Options --> DNSSEC signature enabled: Yes` you then get a new section called **DS records for registrar** and this information is presented as shown below which is great for experienced users but does not tell you what each of the individual numbers do.
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/93b1273d-ef2e-4ab6-80a7-72fb5d9cc2e1)

### Proposed solution
Either add a tooltip with an example telling you what each number does or something similar to this image

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/6dad77cd-9ff4-47f1-ace1-15aa9010fe82)

I understand that Virtualmin is not here to teach us the basics, but this is definitely a useful improvement with such a new technology.

for other people who find issue, I found this article very useful: https://bind9.readthedocs.io/en/latest/dnssec-guide.html#ds-record-format

**Comment by jcameron** [comment]
Oh I see, is this because at some registrars the components of the DS record have to be entered separately?

**Comment by shoulders** [comment]
I did not know some allowed you to copy and paste the whole thing 😄 , you learn every day.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/f6743981-a367-4213-9d7e-64bbeb8fafc7)

**Comment by jcameron** [comment]
Ok, makes sense ... I'll add that.
