### ISSUE TITLE
`php_mod` option is still available in an empty Server Template

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#697]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |      31  package updates are available   |

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/891c2c13-1dc1-4a2a-bc89-24627e880f88)

### What I did
- Virtualmin --> System Settings --> Server Templates --> Create an empty template
- Save and next
- select `Edit template section: PHP options`
- `mod_php` is preselected

### Is this a bug
- I can't work out if this is a bug or a legacy option to allow people to still use `mod_php`
- This option is not available in `Default Settings`
- If you select another PHP option, save, and then I go back to `PHP options` page, `mod_php` has disappeared.

I thought I would mention it because I though `mod_php` was completely removed from Virtualmin.

**Comment by jcameron** [comment]
Thanks, that's a bug ... we'll fix this in the next release.
