### ISSUE TITLE
mysql TLS certificate restart instead of  ALTER INSTANCE RELOAD TLS.

### ISSUE THREAD

**Issue by aqueos** [virtualmin/virtualmin-gpl#698]
hi,

 when a certificate is upgraded that concern mysql, virtualmin restart the mysql server and its adding downtime.

 For mysql 8 the change could be done by setting the values and reloading TLS.

https://dev.mysql.com/doc/refman/8.0/en/alter-instance.html#alter-instance-reload-tls

SET GLOBAL ssl_ca='/etc/mysql/mysql-ssl.ca';
SET GLOBAL ssl_key='/etc/mysql/mysql-ssl.key';
SET GLOBAL ssl_cert='/etc/mysql/mysql-ssl.cert';
ALTER INSTANCE RELOAD TLS;

 and with no need to restart the whole mysql server. This could be very handy in big instance rather than restarting it.

 i dont think 5.7 can do it, the doc does not specify any way other than restart.

best regards,
Ghislain.
AQUEOS.

**Comment by jcameron** [comment]
Good idea, we'll do this in the next Virtualmin release.
