### ISSUE TITLE
Maximum input variables limit - Tooltip URL is broken

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#699]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |      42  package updates are available, of which  4  are security updates   |

### the issue

when you click on the tooltip for `Maximum input variables limit`

`Virtualmin --> Services --> PHP-FPM Configuration --> Resource Limits --> Maximum input variables limit`

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/a8b35772-bf12-4c7e-948b-619c5c18bf49)

it load the following page https://www.php.net/manual-lookup.php?pattern=max-input-vars&lang=en&scope=404quickref

But the link is  https://www.php.net/max-input-vars

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/0424cc24-c075-4203-a018-57a79864fa79)

### Solution
I think they moved the relevant document here (best guess) https://www.php.net/manual/en/info.configuration.php#ini.max-input-vars

## Additional (for Webmin)
The corresponding Webmin tooltip is affected

`Webmin --> Tools --> PHP Configuration --> Resource Limits --> Maximum input variables limit`

**Comment by jcameron** [comment]
Looks like we already fixed this here : https://github.com/webmin/webmin/commit/fb0b6b4044bf39d34ef15eebcbf02268daa7e920

Which Webmin version are you running there?

**Comment by shoulders** [comment]
For context, this might be an issue at PHP.net

`Maximum input parsing time` URL = `https://www.php.net/max-input-time` which then redirects to `https://www.php.net/manual/en/info.configuration.php#ini.max-input-time`

So this might not be a bug because PHP.net have changed the links but have forgotten to add the redirect for ` https://www.php.net/max-input-vars`

**Comment by jcameron** [comment]
Oh, so it's only broken for that one link? I think that's php.net's problem then ...

**Comment by iliajie** [comment]
> Oh, so it's only broken for that one link? I think that's php.net's problem then ...

Yes, I hoped they'd fix it when I was implementing it. Reported here https://github.com/php/web-bugs/issues/118.
