### ISSUE TITLE
CentOS Linux 7 PHP-FPM support was not detected : No FPM configuration directory found

### ISSUE THREAD

**Issue by agemarks** [virtualmin/virtualmin-gpl#70]
CentOS Linux 7.5.1804
Webmin 1.894
Virtualmin 6.04
package php-fpm removed, installed rh-php72-php-fpm

but when Re-Check Configuration:
PHP-FPM support was not detected : No FPM configuration directory found
and FPM is not available in Website Options PHP script execution mode.

**Comment by jcameron** [comment]
Thanks for the fix for this issue!
