### ISSUE TITLE
DNS Domain Registration module name confusion

### ISSUE THREAD

**Issue by verne-work** [virtualmin/virtualmin-gpl#706]
the Feature/Plugin `DNS Domain Registration` seems to not have much to do at all with DNS, or I am very confused.

Should this module and its menu name be changed to something else; maybe just drop the 'dns' part ?

and for general reference, you first have to go to Virtualmin – System Settings – Features and Plugins ...

once there, check the left hand box next to DNS Domain Registration to make it visible under Addresses and Networking.

**Comment by jcameron** [comment]
I mean, it is to do with DNS ... because all registered domains are DNS Domains.

**Comment by iliajie** [comment]
As I mentioned [here](https://forum.virtualmin.com/t/dns-domain-module-issue/123776/16?u=ilia) we will rename it to be called in somewhat more expected way.

**Comment by verne-work** [comment]
Thanks !!
