### ISSUE TITLE
FCGI Wrap: False positive

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#709]
Jamie, look, this code in Virtualmin:

```# If using fcgiwrap, make sure the server is running
if ($d->{'fcgiwrap_port'}) {
    my $st = &get_fcgiwrap_status($d);
    if ($st == 0) {
        return $text{'validate_efcgiwrapinit'};
        }
    elsif ($st == 1) {
        return $text{'validate_efcgiwraprun'};
        }
    }
```

.. produces an error in domain validation test right before LE certificate request, i.e.:

```
Validating configuration for example.com ..
.. errors were found, which will prevent Let's Encrypt from issuing a certificate :

Apache website : No FCGIwrap server bootup action exists!
```

However, my Debian 12 system only has `fcgiwrap`, `fcgiwrap.service`, and `fcgiwrap.timer` units. All of them are running correctly. The `get_fcgiwrap_status` function for `$name` returns for this domain `fcgiwrap-example-com` .. although, this service doesn't exist. However, any of this should be irrelevant, as my system has `suexec-custom` installed.

Apache config for this domain contained:

```
<Directory /home/example.com/cgi-bin>
    allow from all
    AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
    Require all granted
    SetHandler proxy:unix:/var/fcgiwrap/1663060080110061.sock/socket|fcgi://localhost
    ProxyFCGISetEnvIf true SCRIPT_FILENAME "/home/example.com%{reqenv:SCRIPT_NAME}"
</Directory>
```

As I toggled Apache webserver feature, the config was regenerated, and now looks correct, i.e.:

```
<Directory /home/example.com/cgi-bin>
    Require all granted
    AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
</Directory>
```

I assume it was a bug that we fixed recently, right?

Well, if so, we should also reset `fcgiwrap_port` option for the domain config, as it still keeps failing _**false-positively**_!

**Comment by jcameron** [comment]
Is this happening when requesting an LE cert at domain creation, or every time you try to get a cert?

Also, did this domain every use `fcgiwrap` mode to execute CGI scripts? The `fcgiwrap_port` field shouldn't be set unless FCGI mode is in use..

**Comment by iliajie** [comment]
> Is this happening when requesting an LE cert at domain creation, or every time you try to get a cert?

This is for the old domain that was there for a while.

> Also, did this domain every use `fcgiwrap` mode to execute CGI scripts? The `fcgiwrap_port` field shouldn't be set unless FCGI mode is in use.

This is unknown. However, I could easily migrate my domain from the system that used `fcgiwrap` in the past. Domain config should always be adjusted accordingly, i.e. have `fcgiwrap_port` directive removed.

**Comment by jcameron** [comment]
Ok I found a bug that can cause this - it will be fixed in the next release.

**Comment by iliajie** [comment]
The domain in question was never controlled via Virtualmin CLI on that system.

The initial problem will persist, as `fcgiwrap_port` directive will still be stuck in the domain config causing issues ..

**Comment by jcameron** [comment]
But how did `fcgiwrap_port` get set in the first place on this domain? Was it migrated from a system that used suexec to one that uses fcgiwrap?

**Comment by iliajie** [comment]
I don't think it was migrated. It was initially created on that system.

**Comment by jcameron** [comment]
So that `fcgiwrap_port` field is how Virtualmin knows if fcgiwrap is being used to run CGI scripts or not, and if it's set it does expect there to be a per-domain systemd action or init script.

**Comment by iliajie** [comment]
> But how did fcgiwrap_port get set in the first place on this domain? 

As now I'm thinking of this, I think this particular domain was migrated from EL system, which did have `fcgiwrap` enabled but Debian system has `suexec-custom` installed.

I believe we need to clear `fcgiwrap_port` on domain save when not used ..

**Comment by iliajie** [comment]
> Ah this could be an issue with migration if the new CGI mode isn't supported.

Jamie, the problem arises when both `suexec` and `fcgiwrap` are support.

The fix is here:

https://github.com/virtualmin/virtualmin-gpl/pull/715

**Comment by iliajie** [comment]
> Ah this could be an issue with migration if the new CGI mode isn't supported.

Jamie, the problem arises when both `suexec` and `fcgiwrap` are supported upon the domain restore, if the source system had `fcgiwrap` in use.

The fix is here:

https://github.com/virtualmin/virtualmin-gpl/pull/715

**Comment by jcameron** [comment]
So with all my latest commits backups and restores that adjust the CGI mode as needed should now be fully supported.

**Comment by iliajie** [comment]
Alright, I have given it extensive testing again. Everything seems to be working as expected.

However, cross restores, i.e. Apache ↔ Nginx or Nginx ↔ Apache still don't clear either `fcgiwrap_port` or `nginx_fcgiwrap_port` directive in domain config file. This PR addressed this problem as well.

Nevertheless despite this, things seem to work correctly anyway. Although, I'd refer not to have zombie directives hanging around configs, if possible..

**Comment by jcameron** [comment]
I'm not too concerned about these directives, as they do nothing when the other webserver is being used..

**Comment by iliajie** [comment]
> I'm not too concerned about these directives, as they do nothing when the other webserver is being used..

I now agree, as it appears that recent patches have resolved the initial issue! Thanks!
