### ISSUE TITLE
`Website for domain` - Remove index.php4 index.php5 from default settings

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#711]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |      19  package updates are available   |

## the background

In the  Default Server template -->  `Website for domain` the following is defined

`DirectoryIndex index.php index.php4 index.php5 index.htm index.html`

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/4c846dfd-be67-4937-a072-8b7c346bbab3)

## the issue

`index.php4` and `index.php5` are no longer valid index files and if they are they should be added in as required by the user and not by the default installation of virtualmin.

## Proposed solution

remove `index.php4` and `index.php5` from default server template.

## Notes
- I am aware this would only be for new installs and I can remove them myself from my default server template.
- I searched on virtualmins code (GitHub) for `php5` and got a few hits but I did not understand the code and whether that was redundant aswell.

**Comment by jcameron** [comment]
Definitely we don't need `index.php4` anymore. But does including `index.php5` cause any problems?

**Comment by iliajie** [comment]
> But does including `index.php5` cause any problems?

Yeah, it hurts eyes a little bit. 🙂

**Comment by jcameron** [comment]
LOL ... well, it can be removed from the template.

**Comment by iliajie** [comment]
> LOL ... well, it can be removed from the template.

Alright! 😄 I've removed that too.
