### ISSUE TITLE
Server Template - Remove `PHP configuration variables for scripts`

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#714]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |      19  package updates are available   |

## The Background

Virtualmin --> System Settings --> Server Templates --> Edit template section: PHP options --> PHP configuration variables for scripts

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/7b4190f8-bbb2-4b2c-bcf0-71616bc015d8)

This feature performs one of the following actions of which neither I can get to work:

- Installs a PHP file in the root of your virtual server to set PHP variables
- Is called when you install a 3rd party script via virtualmins `Script Installers` and this injects the variables into the script.

I am fairly confident that it is the last option that should happen.

## The Issue

- no one seems to use this
- no one knows what this feature actually does
- I cannot get it to work
- this feature seems to be bypassed by functions in your script installers
  https://github.com/virtualmin/virtualmin-gpl/blob/5c4fe9d0bb3c876d0c6e1c5d757760cf7cb2517a/scripts/roundcube.pl#L59-L70
- the code does not have it's own feature file and is instead the code is in the `Website for domain` file (feature-web.pl)
  - This builds the table
    https://github.com/virtualmin/virtualmin-gpl/blob/5c4fe9d0bb3c876d0c6e1c5d757760cf7cb2517a/feature-web.pl#L3203-L3233
  - This builds the `php_vars` template and puts it in `/etc/webmin/virtual-server/config` and/or your `Server Template`
    https://github.com/virtualmin/virtualmin-gpl/blob/5c4fe9d0bb3c876d0c6e1c5d757760cf7cb2517a/feature-web.pl#L3314-L3332
- this is probably legacy code from the `mod_php` days

## Proposed Solution
- remove this legacy code as it is confusing and I don't think anyone can or does use this.
- Hive `PHP options` out to its own `template` file. (i.e. feature-php.pl) for consistency.

## Related
- A search for `php_vars` in the repo 
  https://github.com/search?q=repo%3Avirtualmin%2Fvirtualmin-gpl+php_vars&type=code&p=1

## Discussion
- https://forum.virtualmin.com/t/php-configuration-variables-for-scripts-where-are-the-settings-added/123665

**Comment by jcameron** [comment]
Yeah, maybe this feature is so rarely used that it doesn't need to exist.

But what is the exact file you mentioned in "Installs a PHP file in the root of your virtual server to set PHP variables" ?

**Comment by shoulders** [comment]
>  "Installs a PHP file in the root of your virtual server to set PHP variables" ?

This was just a guess as nobody knows how this feature changes the PHP values. I wanted to include it just in-case I was wrong.

**Comment by iliajie** [comment]
This feature supposed to add key/value to domain PHP-FPM pool file ..

**Comment by shoulders** [comment]
If this is a valid feature and it is used, the the 2 following things should be changed

- the option's title is wrong, maybe change to `PHP-FPM Pool values`
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/bbdd53ff-b30f-4ff1-abf7-b5bfc0e69449)

and the tooltip needs to mention about the `PHP-FPM pool file` and remove references to scripts.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/8de5f369-7894-40ec-bbf9-43c598ccaa63)

**goes to -->**

This table can be used to enter PHP-FPM pool file values. It can be useful for setting initial PHP-FPM values when creating a virtual server to satisfy specific requirements.

**Comment by iliajie** [comment]
I think this is unintentional. I think this feature should also work for other PHP modes, right Jamie?

**Comment by jcameron** [comment]
So for domains using FPM mode, the values should get added to the pool file. But for domains in FPM or FCGI mode, they'll get added to the `etc/php.ini` file..

**Comment by iliajie** [comment]
> So for domains using FPM mode, the values should get added to the pool file. But for domains in FPM or FCGI mode, they'll get added to the `etc/php.ini` file..

Yes, correct. However, this template feature only works correctly for FPM mode, not for CGI/FCGI ..

**Comment by shoulders** [comment]
I don't think it works even for PHP-FPM. Let me know if I have missed something below or not done something correctly. Thanks

I alterd the default PHP variable line so I could see a change, I then create a test virtual server and the results are below. The `memory_limit` did not change.

### Server Template with `memory_limit` set to `17M`
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/45420087-8419-417a-af6e-43bda5807ce5)

### Create the Virtual Server
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/cb6369cd-4b31-4767-859a-1b417dce167f)

### The pool file for the virtual server
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/490b5df6-be00-4e35-b187-e133d5a79d28)

### phpinfo()
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/a0790f1c-d855-425c-97c8-b9a4e6920a65)

**Comment by jcameron** [comment]
So confusingly, that feature only sets PHP variables when a script is installed using the Script Installers feature.

Maybe we should have it set those variables at domain creation time as well!

**Comment by shoulders** [comment]
> So confusingly, that feature only sets PHP variables when a script is installed using the Script Installers feature.

Does not seem to do that either.

**Comment by iliajie** [comment]
> Maybe we should have it set those variables at domain creation time as well!

Yes, I think we should create those records at domain creation time as well! For PHP-FPM mode the records were created already upon domain creation time, though not for CGI/FCGI modes.

**Comment by shoulders** [comment]
@iliajie I still have not been able to verify this code works.

Can you tell me which file(s) are currently updated with these values? A rough location would be needed as-well. Thanks

**Comment by iliajie** [comment]
If you have PHP-FPM mode setup as default in templates, then PHP-FPM domain pool file (after virtual server creation) will have those directives.

You can find domain pool config file by going to **PHP-FPM Configuration** link.

**Comment by shoulders** [comment]
@iliajie if you mean the following, then the `PHP Values` does not add any values upon virtual server creation. But I can re-check, if yours does and I have got the right location. I appreciate all of the help 😄 

Virtualmin --> PHP-FPM Configuration --> Edit Configuration manually

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/490b5df6-be00-4e35-b187-e133d5a79d28)

**Comment by shoulders** [comment]
I don't usually bump stuff, but I was wondering if there was any further information on this one.

I appreciate this might not be top of the list 😄. thanks

**Comment by iliajie** [comment]
> I don't usually bump stuff, but I was wondering if there was any further information on this one.

It's definitely fine to bump stuff, considering it isn't an urgent issue.

We will need to wait for Jamie's comment on it.

**Comment by jcameron** [comment]
I think we should make sure these are set at domain creation time. I'll add this to my TODO list ...

**Comment by shoulders** [comment]
I think the following `memory_limit` value is there in the default template shipped with a fresh install. Can this be removed so there are no defined variables. It has been a while so I cannot be 100% about this, but this feature should be empty anyway.

Thanks

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/7b4190f8-bbb2-4b2c-bcf0-71616bc015d8)

**Comment by iliajie** [comment]
I also don't think we should set the `memory_limit` specifically to `32M`. It's better to allow installable apps to manage this setting if needed.

**Comment by jcameron** [comment]
Ok this has been implemented for inclusion in the next release.

**Comment by shoulders** [comment]
@jcameron Can you just confirm what exactly this feature is supposed to do? It has never really been clear to me. Thanks
