### ISSUE TITLE
Creating DNSSEC key for new domain .. .. key generation failed : dnssec-keygen: fatal: The -r option has been deprecated. System random data is always used.

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#716]
Hey guys, long time no talk.

Just recently upgraded one of my servers to Debian 12 which I am pretty sure had gotten the virtualmin stamp of approval.

Tried to create a new domain and was given this error:

Creating DNSSEC key for new domain ..
.. key generation failed : dnssec-keygen: fatal: The -r option has been deprecated. System random data is always used.

As usual, its probably me but just in case its not. :)

**Comment by jcameron** [comment]
Hmm, this works OK in my test system running Debian 12. Which BIND version do you see if you go to Webmin -> Servers -> BIND DNS Server?

**Comment by abclution** [comment]
9.18

**Comment by iliajie** [comment]
Try force-refreshing system information page using dashboard (circular arrow button in the top right), it will also clear various caches.

**Comment by chris001** [comment]
Hey @abclution, [this patch from @iliajie](https://github.com/webmin/webmin/commit/1bc262481db121138b031e533d903ab1782c1b22#commitcomment-120928974) might sort out your issue, as it did for another user in a similar situation.

**Comment by abclution** [comment]
> Hey @abclution, [this patch from @iliajie](https://github.com/webmin/webmin/commit/1bc262481db121138b031e533d903ab1782c1b22#commitcomment-120928974) might sort out your issue, as it did for another user in a similar situation.

Bravo @chris001 that is definitely it. Will test it out.

**Comment by abclution** [comment]
Ok well it resolved itself after doing a manual refresh like @iliajie suggested, or it fixed itself overnight. No idea didn't check it again before pressing the refresh.. Weirdness. 

Probably just a ghost in the machine again.
