### ISSUE TITLE
DKIM - Should there be 2 domains in this box

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#718]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |     All installed packages are up to date   |

## Background

When I enabled DKIM there were 2 domains defines in **Extra domains to sign for**

Virtualmin --> Email Settings --> DomainKeys Identifided Mail
![cabb095b343ab949788cb69cf71b542bf5c7befe](https://github.com/virtualmin/virtualmin-gpl/assets/319997/ae5a2bab-3d8e-41fa-895d-017d0c1e90fe)

## The issue

`I think` there should be no domains listed in this box by default because
- `server.example.com`
  - (for context: this is used to send emails from Webmin)
  - Now that there is the option `virtualmin → System Settings → Virtualmin server configuration → configuration category: SSL settings → Create host default domain with Let’s Encrypt certificate`, is this the right place fro this domain or does it make no difference?
- `server` = is not a proper domain name so could not be used anyway, and should be removed.

## Some considerations

- I am not an expert on these settings
- `virtualmin → System Settings → Virtualmin server configuration → configuration category: SSL settings → Create host default domain with Let’s Encrypt certificate` makes no difference to what is added. I mention this because you have the ability to leave the Virtual server visible and all that goes with that.
- some online email tests require SPF on the HELO record
  - [mail-tester.com](https://www.mail-tester.com/)
  ![0352364190dab5fcaecb4ebe0614d9921bb7be9c](https://github.com/virtualmin/virtualmin-gpl/assets/319997/ca125a86-c5ef-44f4-ac57-a49c8fd331ca)
  -  [https://dkimvalidator.com/](https://dkimvalidator.com/)
  ![c44031d186cf7c7ca30e7f506dd0cad98bc32147](https://github.com/virtualmin/virtualmin-gpl/assets/319997/2dcf8f3b-38c2-4e0c-b88d-fb02cc9c1f9e)

## Related
[A discussion of the Virtualmin forum](https://forum.virtualmin.com/t/dkim-should-there-be-2-domains-in-this-box/123941)

**Comment by iliajie** [comment]
Hello,

Thanks for the suggestions. The fix is here:
https://github.com/virtualmin/virtualmin-gpl/commit/d1318673329740fb2b9bbfe84e93f58315edf838

**Comment by jcameron** [comment]
Thanks Ilia, that patch looks good!

**Comment by iliajie** [comment]
Thanks Jamie, for taking a look. I'll close this issue then.
