### ISSUE TITLE
Account Plan - Unexpected Unit conversion

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#719]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.101      |
|  Usermin version     |     2.001     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.04      |
|  Package updates     |      69  package updates are available   |

## Background

I wanted to set my account quotas to 1500MiB

Virtualmin --> System Settings --> Account Plans --> (Quota for entire server | Quota for server administrator user)

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/c7442b1d-8679-4884-b069-5f7404c55c99)

## The issue

When I save 1500MiB it is converted into 1.46GiB

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/f0ed44eb-c93d-4ee2-8074-dea8bbacafe7)

Currently there is noway to actual use the value 1500MiB it will always get converted.

**Additional**
when i save a value for **Quota for entire server** or **Quota for server administrator user** =>`1000` their units are converted up one unit as follows:

- 1500 bytes --> 1 KiB
- 1500 KiB --> 1.46 MiB
- 1500 MiB --> 1.46 GiB
- 1500 GiB --> 1.46 TiB
- 1500 TiB --> 1.46 PiB

## Proposed solution

- Don't change the units upon submission.
- If a user wants 1.46 GiB they can select GiB from the options drop down and enter 1.46

Thanks as ever

**Comment by jcameron** [comment]
So internally we store these numbers in bytes, and just convert them to MiB/GiB/TiB/etc for display. However, it is a problem if the conversion isn't repeatable ... so 1500 MiB should not be converted to 1.46 GiB if this causes a loss of precision.

**Comment by jcameron** [comment]
Ok, this will be fixed in the next Webmin release..
