### ISSUE TITLE
menu: rename `Setup SSL Certificate` to `SSL Certificate`

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#720]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |     All installed packages are up to date   |

## The issue
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/a3a90966-8639-42b3-b1c0-69940995ec79)

- I don't think having the word `setup` at the beginning of  `SSL Certificate` make sense especially if your SSL is already setup.
- You might just want to get information from the `Current SSL certificate details` but `setup` implies a single action/function.

When people are scanning down the menu they will look for `SSL` first.

## Proposed solution
rename `Setup SSL Certificate` to `SSL Certificate`

this will make it read a little bit better.

**Comment by iliajie** [comment]
Hello,

Well, it is understandable.

However, when naming it, I was thinking in the context of having consistency with other links in the category, which all start from a verb, e.g.:

<img width="256" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/bddbe578-a93f-43f0-a81f-20d5c808715f">

**Comment by shoulders** [comment]
I did notice the `verb` format but my thinking was that all the other options were single operations whereas the SSL section was a collection of "reports" and actions. I also thought that this section might have other stuff added to it in the future.

Either name still does the job and would be happy with either as they are both obvious.

So, leave it `as is` unless it is re-flagged?

**Comment by iliajie** [comment]
> So, leave it `as is`

I'd most probably kept it as is.

> unless it is re-flagged?

Not sure what you mean in here..

**Comment by shoulders** [comment]
lol 😄 

> unless it is re-flagged?

What I meant was, keep it as it is and close the job, only reconsidering it if someone else makes another GitHub issue on this subject.
