### ISSUE TITLE
Installing a script in domain post-creation time produces error

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#722]
Hello Jamie,

When creating a new virtual server and a template has **Default script installers** enabled (in my cause it was WordPress), and even though the same template has PHP-FPM mode set as default, upon virtual server creation time an odd and unrelated to PHP-FPM error message is returned, i.e. `could not find domain's php.ini file` for example:

<img width="747" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/d7a6b843-aaaf-4ef0-bf00-d825dfba8e2c">

**Comment by jcameron** [comment]
Actually that error is related to the php.ini file used in fcgid or cgi modes, I think.

Does the file `etc/php.ini` exist under the domain's home directory?

**Comment by jcameron** [comment]
Also, does installing Wordpress immediately after creating the domain work OK?

**Comment by iliajie** [comment]
The answer to the first question is, - no, and I think this is right, because we're in FPM mode, and shouldn't expect `~/etc/php.ini` file exist.

For the second question, - yes, it does work right after.

**Comment by iliajie** [comment]
Have we fixed this one?

**Comment by jcameron** [comment]
Pretty sure this is fixed now ..

**Comment by iliajie** [comment]
Great, I'll close it then.
