### ISSUE TITLE
databases permissions created by virtualmin have underscores escaped in Webmin (MariaDB Database Server)

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#723]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |     All installed packages are up to date   |

## The Issue

When I create a new database in virtualmin: `Virtualmin --> Edit_databases --> Create a new database`

The database names in the webmin `Database Permissions` the underscore preceded by a slash

## The steps
1) Virtualmin --> Edit_databases --> Create a new database

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/5affb1c9-1976-41ed-b3a9-7a646fec0daa)

2) Virtualmin --> Edit_databases - The database is created

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/d336cae3-ec40-4e48-bc1e-0ad9391a6034)

3) navigate to: Webmin --> MariaDB Database Server --> Database Permissions

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/6d9a168a-6067-485b-a624-cb9bc49475f5)

## Additional information

When I create a database permission in webmin directly, this escaping does not occur.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/e5b0d1da-b9cd-40bf-8791-6a6a7f32244d)

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

Escaping `_` is technically unnecessary outside of a `LIKE` clause, as the underscore will be treated as a literal underscore anyway. Escaping it doesn't change its meaning in this context but doesn't harm either.

I could think of having it escaped be beneficial (in a weird way) for an admin to understand how those permissions were created in the first place.

We could easily fix either. Though the simplest would be to fix the display in Webmin UI..

**Comment by shoulders** [comment]
I think this needs fixing in the `name creation code` in virtualmin rather than the `display code` in Webmin because:
- the stored values are different and this could affect things like `grep` text searches as an example.
- the permission names created in webmin and virtualmin would no longer be consistent, even though the slash is irrelevant
- altering the display code is more of a patch than fixing the issue (for me anyway)
- when you edit the database permission it would have a different value in it.

## edit example
When you edit the database permission you get the following and as you can see the `matching pattern` has the slash in it

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/e22149b0-58c2-499c-8c96-6cd30e112658)

## Propose solution
- Alter the virtualmin code to correctly create `Database permissions` with the correct name for new databases as Webmin does.
- For current databases permissions, optionally you could do a script to alter them or just let the end user alter them if they really want to.

**Comment by iliajie** [comment]
> I think this needs fixing in the `name creation code` in virtualmin rather than the `display code` in Webmin

Agreed. The fix is here https://github.com/virtualmin/virtualmin-gpl/commit/e73c62b8ebc7ed80a194e76b97e243c7979b16ce.

> For current databases permissions
> (optionally) you could do a script to alter them to the correct name
> or just let the end user alter them manually if they really want to.

This is actually important to handle. Therefore, we will also handle it correctly (automatically) using the latest patch.

Issue solved.

Thanks for the heads up!

**Comment by jcameron** [comment]
It's been a while since I wrote that code, but I seem to recall that the escaping is necessary because _ is a wildcard character in MySQL. So if it's not escaped, a grant for database `foo_bar` would also match `fooxbar`

**Comment by iliajie** [comment]
> Escaping `_` is technically unnecessary outside of a `LIKE` clause, as the underscore will be treated as a literal underscore

Yeah, I think long before we had to directly alter permissions. Nowadays, using `GRANT` escaping `_` should be unnecessary, as the underscore in database name must be treated as a literal character, not a wildcard character.

**Comment by shoulders** [comment]
@jcameron Webmin does not escape the underscore character when you create the permissions manually.

**Comment by jcameron** [comment]
No, that's intentional in case the admin really does want to match multiple databases with a permission grant.

**Comment by iliajie** [comment]
> Can you test this to make sure?

I have retested it, and it appears that you're right! `_` is still treated as a wildcard character!

I've gotten the wrong impression on reading documentation! I will revert the patch!

Thanks!

**Comment by jcameron** [comment]
Ok, thanks!

**Comment by shoulders** [comment]
just for me, can you confirm this is a non-issue and I will update my notes.

**p.s.** thanks for looking into this and I hope you don't mind all of the issues I have been posting.

**Comment by iliajie** [comment]
It is not an issue. However, displaying permissions with escaped underscore in Webmin UI can be confusing for admins who aren't aware of what's going on ..

**Comment by marclaporte** [comment]
> I hope you don't mind all of the issues I have been posting.

Thank you for all your contributions. I can tell you invest significant time to submit well-researched issues. This is super helpful to improve Webmin/Virtualmin and optimize the time of our great developers.

**Comment by iliajie** [comment]
> @shoulders: Thank you for all your contributions. I can tell you invest significant time to submit well-researched issues.

For real, it helps a lot! Thank you @shoulders!

**Comment by shoulders** [comment]
## I think this might need looking at again.

As you know when Virtualmin create the database permission it puts a slash in the database name it to escape the underscore because of this, the `Matching pattern` option is used. 

There are 3 ways of selecting the database and in the picutre below you can see the inconsistency before you (`example_test`  /  `example\_test`). This clearly shows that `Webmin` does not need the database name underscore to be escaped and actually promotes it not to be.
- Any
- Selected
- Matching pattern
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/e22149b0-58c2-499c-8c96-6cd30e112658)

## Proposed solution
- Virtualmin should use the `Selected` option which does not have the escaped underscore on it. This might be achiebd by not saving the database name with the additional slash in it.
- If the slash is removed from `example\_test` then the **Databases** option is changed from `Matching pattern` to `Selected` meaning that **Webmin** is handling the underscore correctly but **Virtualmin** is not creating the record correctly. Otherwise why are all of the records in `Selected` without underscores?

## Additional

- I dont have a username with an underscore to test if this character is escaped or not
- if you select the database name from the `Selected` drop down then the underscore is not escaped.

**Comment by jcameron** [comment]
This actually looks like a Webmin bug ... on that page, it should also be doing the escaping if the user selects a specific database, because otherwise the _ could match more than one DB.

**Comment by shoulders** [comment]
> This appears to still be an issue:

|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |      1  package update is available, of which  1  is security update   |

### The issue

On the following page, there are visibly escaped

`Webmin --> Servers --> MariaDB Database Server --> Database Permissions`

![image](https://github.com/user-attachments/assets/06a4cbec-88ea-450a-a0ef-947bf53679e5)

when I edit `mbmdev\_joomla` I see 

![image](https://github.com/user-attachments/assets/8d0521c7-59cf-4949-966f-960aa62e95c5)

### proposed solution

remove the visible escaping

**Comment by iliajie** [comment]
> remove the visible escaping

Well, those escapes are necessary. However, I wouldn't mind if they were removed from the view, as the column clearly says **Databases**.

**Comment by iliajie** [comment]
Thanks for the heads up! It's fixed now.

**Comment by shoulders** [comment]
It's the little things in life, lol. Thanks @iliajie

**Comment by iliajie** [comment]
However, as I think about it now, what if a user wants to use `_` to intentionally match more than one DB? I assume this would be a rare scenario, but it would make it look the same as the default way, when the database name is escaped ..

**Comment by shoulders** [comment]
Tricky, but I will leave it to you 😀

I come from the cpanel world where this is the default format, no wild cards.

Db: username_wordpress
Username: username_wordpress

Etc..

**Comment by jcameron** [comment]
As long as the user can still edit database permissions and use an un-escaped _, I'm fine with this

**Comment by shoulders** [comment]
> after further thought the slashes should be kept visible in `Database Permissions` (i.e. revert the patch)

**reasons**
- I listened your your arguments
- if you can enter a escaped or non-escaped underscore, then this should be displayed otherwise it will get confusing as to what was configured, I will get used to this.
- I assume this will only ever be on the database permissions as this is a selection mask rather than an absolute variable.
- the way cPanel get around this is they have drop downs to selected the user against the database and it must escape the underscore quietly in the background. In Webmin you have both this option and pattern matching.
- Maybe add a small notice why there might be slashed underscores, It could go in the tooltip for the `Database Permissions` and the `Edit Database Permissions` or on the page if more appropriate.
  > _ = wildcard
  > \_ = literal underscore

**Comment by iliajie** [comment]
I think it's much less confusing to show the database names as expected and place an asterisk next to those that use actual wildcards:

<img width="543" alt="image" src="https://github.com/user-attachments/assets/b061ed44-c572-45d1-ab4c-5e296e98b9ea">

Fixed now.
