### ISSUE TITLE
Feature: Add `Reset DNS Zone` button

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#724]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |      26  package updates are available   |

### The background

This came about because I wanted add custom name server for my virtual server and I was going to update my server template as required and then reset the DNS zone which would add the custom names servers, but yes I could just add them 😄 , habits die hard.

Restting you DNS zone is also useful if you have been messing and have no idea what entries you should have any more

## The issue 

While looking at my virtual server `DNS Records` in Virtualmin I could not see an option to reset my DNS zone. 

Only Server Administrators can reset the DNS zone via:
- `Limits and Validation ⇾ Validate Virtual Servers page and Reset Features tab`.
- Webmin --> Servers --> BIND DNS Server (probably not recommended for domains managed by Virtualmin)

## Proposed solution

Add a button to this page: Virtualmin --> DNS Settings --> DNS Records

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/772369f9-ee3a-490c-99e4-967ecaebd156)

This button can have one of the following actions:
- Reset the DNS zone directly. There will also be a modal confirmation prompt.
- The button will only appear if the user is an administrator and will load the `Limits and Validation ⇾ Validate Virtual Servers page and Reset Features tab` with the relevant domain and the feature `DNS domain` pre-selected.

## Research

- After searching the forum and the internet I came across the following post
  https://forum.virtualmin.com/t/bind-zone-reset/118308/2
  >Yes, there is an excellent feature in Virtualmin that enables you to quickly reset any feature for a virtual-server (domain). Have a look at `Limits and Validation ⇾ Validate Virtual Servers page and Reset Features tab`. Choose the virtual server which features you want to be reset, then choose DNS domain and set Fully reset by turning features on and off option to Yes, and hit Reset Now button to perform feature reset.
- I think this option is only available to server administrators
- This option is available on a normal cPanel account
  ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/552b4a29-1214-40b8-8df5-fc8617547693)
- This is not a widely used feature but might be useful.

**Comment by jcameron** [comment]
There is a way to do this already using the Virtualmin CLI ... you can run `virtualmin reset-feature --domain whatever.com --dns` , and it will remove and re-add all the default DNS records.

There's also a way to do it in the UI from the "Validate Virtual Servers" page.

**Comment by shoulders** [comment]
@jcameron 

- CLI
  - very useful
  - not everyone is comfortable using the CLI, I am not as I come from windows and cPanel. But I will look into it soon.
- `Validate Virtual Servers` page.
  - not that obvious a place for this feature
  - see my notes above I found it 😄 but only via a forum post.

**Comment by jcameron** [comment]
I suppose we could add a reset button to the DNS Records page pretty easily, yes. Only risk is that users might accidentally delete custom records without realizing it!

**Comment by shoulders** [comment]
> I suppose we could add a reset button to the DNS Records page pretty easily, yes. Only risk is that users might accidentally delete custom records without realizing it!

Just add a modal confirmation prompt, after that if people are that stupid they should not be running a webserver 😄

**Comment by jcameron** [comment]
I'll put this on my TODO list and update this ticket with progress...

**Comment by jcameron** [comment]
Ok I've implemented this for inclusion in the next release of Virtualmin..
