### ISSUE TITLE
can only add validated nameservers which prevents creating local custom nameservers automatically

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#730]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |     All installed packages are up to date   |

## The issue

You can only add name servers that are live so you cannot use the `server template` system to create your own local nameservers eg

- Virtual Server domain = example.com
- Name servers
  - ns1.example.com
  - ns2.example.com

also you cannot use `ns2.${DOM}` in the `Additional manually configured nameservers`

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/a6042979-d49f-4de8-8c61-d35c9124584c)

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/e661748e-6e33-45c0-8a2d-c12305a24d0e)

## Proposed solutions
- Allow the use of shortcodes in `Additional manually configured nameservers`
- Have an option not to validate NS records upon saving, or just remove this validation. I do not know of any ramifications.

## additional

This is the post-installation wizard and it does not like `ns1.${DOM}` or `ns2.${DOM}` but does give you the option of skipping resolvability.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/e0f850fa-9794-41b1-9823-01361a0847f2)

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/2a53cacd-fbf1-48d0-9591-1df11621df19)

**Official documentation**

https://www.virtualmin.com/documentation/dns/faq/#How_do_I_setup_nameservers_for_my_server

**Comment by jcameron** [comment]
Thanks for pointing this out .... we should be able to fix this issue pretty easily.

**Comment by jcameron** [comment]
Ok, this will be fixed in the next Virtualmin release..

**Comment by iliajie** [comment]
> Ok, this will be fixed in the next Virtualmin release..

Has the patch been submitted yet?

**Comment by jcameron** [comment]
Yes I just pushed it
