### ISSUE TITLE
Install Script: Wordpress installation problem

### ISSUE THREAD

**Issue by olivrdd** [virtualmin/virtualmin-gpl#733]
Operating system: Ubuntu Linux 18.04.6
Virtualmin version: 6.17-3
Webmin version: 1.981
Usermin version: 1.823

When trying to install Wordpress 6.4.2 script (via Install Scripts option), I receive the following error (also screenshot attached):

"Failed to install script : Download of https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar is not an archive file - perhaps an error page"

No changes have been made on the server, the script was working fine two weeks ago. The same happens on an older Virtualmin server (on Debian 7/Virtualmin 6.15).

![Screenshot 2024-01-04 152713](https://github.com/virtualmin/virtualmin-gpl/assets/155649767/69166e6e-b851-42af-9197-28961d1bf956)

**Comment by jcameron** [comment]
Does this still happen if you re-try the install?

Alternately, what if you turn off the option to use the Wordpress CLI on the install page?

**Comment by olivrdd** [comment]
Yes, the problem was persistent, but we've updated the latest Wordpress install script from your repo and now the it seems to be working.

And, no. We wanted to try that (the option for using the Worpress CLI, as per already opened ticket and suggestion), but didn't try that , since the option was not available to us (maybe because of the older Virtualmin version).

However, thank you for you response! We really appreciate it!

Regards.

**Comment by iliajie** [comment]
> Virtualmin version: 6.17-3
> Webmin version: 1.981
> Usermin version: 1.823

Why don't you upgrade to the latest Webmin and Virtualmin? If you stuck with the old repos, it's easy to fix and have recent Webmin and Virtualmin-related packages available for installation, .e.g.:

```
sudo sh -c "$(curl -fsSL https://software.virtualmin.com/gpl/scripts/virtualmin-install.sh)" -- --setup
```

**Comment by olivrdd** [comment]
Thank you for the information!

Since the servers are in a production environment, we'll try to do the upgrade on our next planned maintainance session.
