### ISSUE TITLE
check-config issue

### ISSUE THREAD

**Issue by danboid** [virtualmin/virtualmin-gpl#735]
I'm not sure this is actually a problem but I've never seen  `virtualmin check-config` print these messages until today so I thought it best to report it in case it is a bug.

If these messages aren't a problem then `check-config` shouldn't concern the user by printing them at the end of the commands output:

```
Updating all Webmin users with new settings..
.. done

Domain /etc/webmin/virtual-server/domains/16984290552771345 was modified since last read!
Call Stack Trace
In file virtual-server-lib-funcs.pl at line 566 calling WebminCore::print_call_stack
In file /usr/share/webmin/virtual-server/collect-lib.pl at line 219 calling virtual_server::save_domain
In file virtual-server-lib-funcs.pl at line 16509 calling virtual_server::collect_system_info
In file /usr/share/webmin/virtual-server/check-config.pl at line 66 calling virtual_server::run_post_config_actions
Re-loading Webmin ..
.. done

OK
```

Operating system 	Ubuntu Linux 22.04.3
Webmin version 	2.105
Usermin version 	2.005
Virtualmin version 	7.9.0 Pro

**Comment by danboid** [comment]
I had installed the sury repos for newer versions og apache and php etc but it turns out that php-pgsql was broken for the sury php (8.2) packages so I removed all the php packages and reverted to the php 8.1 in the 22.04 repos. I ran `config-check` again and the errors above didn't appear so I'm closing this.

**Comment by jcameron** [comment]
That message isn't a critical error, just a warning that Virtualmin's internal locking of config files may not be perfect. We mainly added it as a debugging tool - I will try a few config checks myself and see if I can re-produce this error.
