### ISSUE TITLE
check.cgi aka Re-Check Configuration sometimes hangs/fails with Framed Theme

### ISSUE THREAD

**Issue by verne-work** [virtualmin/virtualmin-gpl#736]
not sure if this issue will be accepted by staff --- see https://forum.virtualmin.com/t/re-check-configuration-never-finishes/123120/ where I have just one RedHat server with Framed Theme where check.cgi hangs -- on that server when I change over to Authentic Theme it works just fine -- switching back to Framed Theme will cause it to hang again.

As I wrote in the forums, I have other RedHat servers where it works just fine with Framed Theme -- go figure.

My solution for check.cgi as posted in the forums (code stolen from index.cgi) -- replace

`print virtual_server::warning_messages();`

with

```
my $lerr_check_cgi = &warning_messages();
print $lerr_check_cgi;
```

Also not sure if this should be logged against check.cgi or against Framed Theme.

**Comment by jcameron** [comment]
Yeah I think the code should just be : 

```
print & warning_messages();
```

I'll fix that ...

**Comment by verne-work** [comment]
YES YES YES ... and now I feel silly for not noticing that and trying it myself -- but I have never claimed to be a good perl programmer  !!

and -- I just tried that simple update on my failing test server -- and now check.cgi works for both Framed as well as Authentic Themes --- and the cli cmd also continues to work OK (not sure if the cli cmd `virtualmin check-config `shares code or not).

THANK YOU for taking a look at my issue and finding a proper solution !!
