### ISSUE TITLE
`HTTP2` enabled in web interface, but inactive in reality.

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#738]
![http2 enabled yet not active issue](https://github.com/virtualmin/virtualmin-gpl/assets/259416/a911f0ac-8c0e-4f3d-b78b-d299ea6d1af6)

This message is in the Apache error log `/var/log/apache2/error.log`:
```
[Mon Jan 15 00:00:03.414559 2024] [http2:warn] [pid 1239] 
AH10034: The mpm module (prefork.c) is not supported by mod_http2. 
The mpm determines how things are processed in your server. 
HTTP/2 has more demands in this regard and the currently selected mpm will just not do. 
This is an advisory warning. 
Your server will continue to work, but the HTTP/2 protocol will be inactive.
```
From a search, only `mpm-worker` and `mpm-event` are compatible with `http2`.
To deliver on the performance improvements of `http2`, either Virtualmin should choose an `http2`-compatible MPM by default,
Or, show the `error.log` error when `System Settings / Re-check Configuration` runs.

**Comment by jcameron** [comment]
Yeah, that looks like a bug if we're allowing HTTP 2 to be enabled when Apache doesn't support it. I think we should show an error in this case ...

**Comment by jcameron** [comment]
Actually that should already be happening! Can you post the contents of `/etc/webmin/apache2/site` from your system?

**Comment by chris001** [comment]
That file doesn't exist, but this one does:
```
$ cat /etc/webmin/apache/site
path=/usr/sbin/apache2
modules=core/2.457 mod_log_config/2.457 mod_actions/2.457 mod_alias/2.457 mod_auth_basic/2.457 mod_authn_file/2.457 mod_authz_host/2.457 mod_autoindex/2.457 mod_dir/2.457 mod_env/2.457 mod_fcgid/2.457 mod_http2/2.457 mod_mime/2.457 mod_mpm_prefork/2.457 mod_negotiation/2.457 mod_proxy/2.457 mod_rewrite/2.457 mod_setenvif/2.457 mod_ssl/2.457 mod_status/2.457 mod_suexec/2.457 mod_php/2.457
allmodules=core mod_so mod_watchdog http_core mod_log_config mod_logio mod_version mod_unixd mod_access_compat mod_actions mod_alias mod_auth_basic mod_authn_core mod_authn_file mod_authz_core mod_authz_host mod_authz_user mod_autoindex mod_deflate mod_dir mod_env mod_fcgid mod_filter mod_http2 mod_mime mod_mpm_prefork mod_negotiation mod_php8.2 mod_proxy mod_proxy_fcgi mod_reqtimeout mod_rewrite mod_setenvif mod_socache_shmcb mod_ssl mod_status mod_suexec mod_core mod_http mod_php
size=725920
version=2.457
webmin=2.105
fullversion=2.4.57
```

**Comment by jcameron** [comment]
Ok I see the Virtualmin bug that's preventing it from detecting the incompatible prefork module now. This will be fixed in the next release..
