### ISSUE TITLE
list-scripts: Confusing in- and output

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#739]
[According to the documentation](https://www.virtualmin.com/documentation/developer/cli/list_scripts/) and the command line output, [list-scripts.pl](https://github.com/virtualmin/virtualmin-gpl/blob/b50a6ffe6fc7d8c9e60f716ed16d2cfac2e89bd8/list-scripts.pl) should be able limit the output to a certain script

e.g. `virtualmin list-scripts --all-domains --type roundcube` should only list domain in which roundcube is active.

Multiple problems:

1. `--type` seems to only accept lowercase input. But this is not documented. When using `virtualmin list-available-scripts` I am presented with the following output:
```
Name                           Versions                       Available?
------------------------------ ------------------------------ ----------
phpMyAdmin                     5.2.1 4.9.11                   No        
phpPgAdmin                     7.13.0                         No        
RoundCube                      1.6.5 1.5.6                    Yes       
SquirrelMail                   1.4.22                         No        
WHMCS                          8.7.3 8.6.2 8.5.2              No        
WordPress                      6.4.2                          No      
```

This made me think I could use `RoundCube` only in `--type` to only output domains where RoundCube is installed, while only `roundcube` is accepted.

2. When using `--type` (with an accepted value) you still get entries fir each domain instead of only for the domains having the given script installed. e.g.:
```
Scripts in domain example.tld :
ID               Description               Version    URL path                 
---------------- ------------------------- ---------- -------------------------

Scripts in domain example2.tld :
ID               Description               Version    URL path                 
---------------- ------------------------- ---------- -------------------------
1234567890123456 RoundCube                 1.6.5      /folder/                

Scripts in domain example3.tld :
ID               Description               Version    URL path                 
---------------- ------------------------- ---------- -------------------------

```

I would expect to only have the output:
```
Scripts in domain example2.tld :
ID               Description               Version    URL path                 
---------------- ------------------------- ---------- -------------------------
1234567890123456 RoundCube                 1.6.5      /folder/                
```

When using `--multiline`  I only get the domain with the given script installed. E.g. `virtualmin list-scripts --all-domains --type roundcube --multiline`'s output is
```
123456789012345678
    Domain: example2.tld
    Type: roundcube
    Description: RoundCube
    Version: 1.6.5
    Installed: 11/07/2023 07:34 AM
    Manually deleted: No
    Details: Under public_html/folder using mysql database example2_roundcube
    URL: https://example2.tld/folder/
    State: OK
    Directory: /home/example2/public_html/folder
    Database: example2_roundcube (mysql)
    Delete database on uninstall: Yes
    Website: https://www.roundcube.net/
```
Here I see the `Type` I'm supposed to enter in "proper" format

3. The `ID` in both types of output is not exactly the same.
`1234567890123456`
vs
`123456789012345678` (in `--multiline`)
It seems to be truncated in the first case. The values are not the real ones, but the length matches.

**Comment by iliajie** [comment]
Thanks for the heads up! All mentioned issues are fixed in this https://github.com/virtualmin/virtualmin-gpl/commit/d3be3242e00790edb9cdfadddfa151fee87b45dc patch.
