### ISSUE TITLE
Questions about auto-removal of spam and trash

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#742]
As far as I understand it is possible to define a default rule to empt spam in `Server Settings > `Server Templates`
![Screenshot 2024-01-19 at 09 51 06](https://github.com/virtualmin/virtualmin-gpl/assets/45786226/5a7f6e40-fcf4-4d42-8787-49a10911423c)

It is also possible to define the same for each virtual server in the respective `Mail Options` > `Spam and Virus Delivery`
![Screenshot 2024-01-19 at 09 51 43](https://github.com/virtualmin/virtualmin-gpl/assets/45786226/2d182ea9-eb5a-41d6-8b4f-1752715ba1cf)

Also via `CLI` via `virtualmin modfiy-spam …`
```
virtualmin modify-spam --domain name | --all-domains
                      [--spam-delete | --spam-deliver |
                       --spam-mailfile [folder] |
                        --spam-file file-under-home |
                       --spam-email address | --spam-dest file |
                       --spam-maildir [folder] ]
                      [--spam-delete-level score | --spam-no-delete-level]
                      [--virus-delete |
                       --virus-mailfile [folder] |
                       --virus-file file-under-home |
                       --virus-email address | --virus-dest file
                       --virus-maildir [folder] ]
                      [--spam-whitelist | --no-spam-whitelist]
                      [--use-spamassassin | --use-spamc]
                      [--spamclear-none |
                       --spamclear-days days
                       --spamclear-size bytes]
                      [--trashclear-none |
                       --trashclear-days days
                       --trashclear-size bytes]
                      [--use-clamscan | --use-clamdscan |
                       --use-clamd-stream-client | --use-clamdscan-remote]
                      [--spamtrap | --no-spamtrap]

```

A few question:

1. Why is it not possible to define a default rule to empty trash the `Server Templates`?
2. Why is the empty trash listed under spam …(more of a rant)
3. Is it possible that the trash clearing only removes matching files, on the main level of the trash folder, but ignores sub-folders?

**Comment by jcameron** [comment]
> Why is it not possible to define a default rule to empty trash the Server Templates?

Good question - this is a missing feature which we'll fix in the next release.

> Why is the empty trash listed under spam …(more of a rant)

Unfortunately the same cron job is used for spam and trash cleanup, which couples these options even though technically they are separate.

> Is it possible that the trash clearing only removes matching files, on the main level of the trash folder, but ignores sub-folders?

That is correct, only the top-level trash folder is cleaned up. Do you have users with trash sub-folders?

**Comment by PitWenkin** [comment]
> > Why is it not possible to define a default rule to empty trash the Server Templates?
> 
> Good question - this is a missing feature which we'll fix in the next release.
> 

Perfect

> > Why is the empty trash listed under spam …(more of a rant)
> 
> Unfortunately the same cron job is used for spam and trash cleanup, which couples these options even though technically they are separate.
> 

That's what I thought

> > Is it possible that the trash clearing only removes matching files, on the main level of the trash folder, but ignores sub-folders?
> 
> That is correct, only the top-level trash folder is cleaned up. Do you have users with trash sub-folders?

Several levels deep … amounting to several GB 

I don't know it is because they deleted a folder (which would be something that could happen to more than one user) or if they actually use the trash folder as storage-space and the folders are intentional …

In my opinion everything in the trash should be deleted, not only the top-level.

How this will play along with the different possible rules, I don't know what would best.
Clearing trash after x days could mean:


- clearing ONLY the files after x days
- clearing the folders after x days if there are no files left inside
- clearing the folders after x days regardless if there are still files inside

Probably first removing the files recursively over all folders and when that is done removing empty folders would be a save way?

**Comment by jcameron** [comment]
So I think that just automatically clearing trash sub-folders could be a bad idea, because some users might accidentally have put legit folders underneath trash. But we could add an option to enable sub-folder cleanup..

**Comment by PitWenkin** [comment]
> So I think that just automatically clearing trash sub-folders could be a bad idea, because some users might accidentally have put legit folders underneath trash.

They should not do have done that in the first place ;-)
And even now, files that were accidentally put on the top-level of thrash would be deleted …

> But we could add an option to enable sub-folder cleanup..

I can live with that, if it is implemented in the GUI ( in all the places :-P ) and the CLI

**Comment by jcameron** [comment]
Ok I will look into this and update this ticket with progress..

**Comment by jcameron** [comment]
Actually, can you show me some examples of what the user's trash sub-folders are named?

**Comment by PitWenkin** [comment]
After a quick search there are sub-folders with years that are in the 2010-2019 range, and no file with a modification date after 2021 (except for dovecot.index.cache and dovecot.index.log, most of those are from early 2023)

Something like:
- Trash
- - 2017
- - - Project-a
- - - - emails having modification timestamps of 2016 or 2017
- - - - sub-folder
- - - Project-b
- - Project-c
- - - 2012
- - - 2013
- - Project-d
- - - emails having modification timestamps of 2012
- - Project-e
- - - sub1
- - - - sub2
- - - - - sub3

**Comment by jcameron** [comment]
Are those sub-directories under the Trash folder, or just folders named like Trash.2017.Project-a ?

**Comment by PitWenkin** [comment]
> Are those sub-directories under the Trash folder, or just folders named like Trash.2017.Project-a ?

Those are sub folders of the Trash folder, listed on the first level of Maildir.

` .Trash.2017.Project-a`

They are shown in  usermin under "Trash"
![Screenshot 2024-01-24 at 08 03 45](https://github.com/virtualmin/virtualmin-gpl/assets/45786226/5e0cb505-fcac-4628-9939-14f109f06cd5)

They are shown in `Webmin > Servers > Read User Mail`
![Screenshot 2024-01-24 at 08 06 13](https://github.com/virtualmin/virtualmin-gpl/assets/45786226/0e3dc4ef-152a-473a-b7fb-297b03c39cee)

**Comment by jcameron** [comment]
Thanks! The next release will add an option per-domain to enabling cleaning up spam and trash sub-folders..
