### ISSUE TITLE
Create Virtual Server - Rename `Create MariaDB database`

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#750]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |     All installed packages are up to date   |

### The Background
When you create a new virtual server you have the following section where you select what services you want.
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/97dc3520-5ccd-45b3-89a6-703ece37c2c5)

### The Issue
`Create MariaDB database` is not a good fit for this feature because this option actually enables MariaDB and only if it is so configure in the server template, a database will be created.

The name is a little confusing and implies it controls the creation of a database rather than the enabling of the service.

### The solution
Rename `Create MariaDB database` --> Rename `Enable MariaDB`

**Comment by jcameron** [comment]
Yeah I wouldn't object to this either ..

**Comment by iliajie** [comment]
Alright, done! Thanks for the heads up!
