### ISSUE TITLE
Domain search should not use "shortened" domain-name

### ISSUE THREAD

**Issue by timri** [virtualmin/virtualmin-gpl#755]
When long domain names are shortened in the domain-dropdown, searching for a domain should still use the full domain name.
For example the domain "test.some-very-long-subdomain.virtualmin-bug.example.com" is shortened to "test.some-very-l...n-bug.example.com", which is also used for search:
![image](https://github.com/virtualmin/virtualmin-gpl/assets/2048663/9c219fd1-dfd9-4e88-84f7-f1f54edba525)
So searching for "some-very-long does" not find it:
![image](https://github.com/virtualmin/virtualmin-gpl/assets/2048663/f88fdcc1-3a48-4ea0-b7ce-bbfc7d0add6f)
But seaching vor "some-very-l..." does:
![image](https://github.com/virtualmin/virtualmin-gpl/assets/2048663/223748bd-f070-49f5-a5d4-9747faa4d0c6)

Tested with webmin 2.105 + virtualmin 7.9.0.gpl-1 on debian

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

This is a very good suggestion! I will update this ticket with progress!

**Comment by iliajie** [comment]
This feature was implemented for inclusion to the next Authentic Theme release.

Thank you for your suggestion!
