### ISSUE TITLE
Virtualmin Server Summary - Add PHP mode and PHP Versions

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#756]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |      6  package updates are available   |

### The issue

I would at a glance be able to see how the PHP is configured and the ideal place is the Virtualmin Server Summary. If anything was going to be in a summary this should be.

You can go to the relevant section `Virtualmin -->Web configuration --> PHP Options` to see the php settings. I can't remember of top of my head if this menu item can be disabled with permissions.

### Solution

Add the PHP Mode and PHP Versions onto the `Virtualmin Server Summary` in these  places

- **Logged in as root**
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/54c495f2-5279-48a9-87f6-0627be66b34d)

- **Logged in as a user**
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/fc529782-c2d3-4aa5-86cd-9f730c5134b9)

### Additional

- Should these sections look the same / share the same template?
- #691 A related issue to the summary page
- #99 Tidying up the server summary has been mentioned here. I cant work out if the task has been completed. Anyway I have put it here for reference just in-case it is useful.

**Comment by iliajie** [comment]
Hello,

This sounds like an improvement. I wouldn't mind adding it. Let's wait and see what Jamie thinks though.

**Comment by jcameron** [comment]
I wouldn't mind if the PHP mode and version were shown on the summary page.

**Comment by iliajie** [comment]
Alright, implemented in this patch:

https://github.com/virtualmin/virtualmin-gpl/commit/7eff8f7ef865b4470dc5b24f7c00cc237c6c37ef

**Comment by iliajie** [comment]
**Example:**

<img width="1179" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/8f9d8462-2f25-4832-9d8a-1ae44748fff6">

**Comment by jcameron** [comment]
Looks good to me!
