### ISSUE TITLE
Rename 'DomainKeys Identified Mail' menu item to 'DKIM'

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#757]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |      8  package updates are available   |

### The issue

When I was looking for `DKIM` and not `DomainKeys Identified Mail`, even though they are the same thing, most people will look for `DKIM` as they do for `spf`

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/3229237b-fe23-40d1-9797-12040ad1530c)

### Solution
rename the menu item `DomainKeys Identified Mail` --> `DKIM` 

### additional
- you could rename to `DomainKeys Identified Mail (DKIM)`

**Comment by jcameron** [comment]
Sure, this would be trivial to do. Or maybe we could rename it to "DKIM (DomainKeys Identified Mail)"

**Comment by iliajie** [comment]
Currently, typing "DKIM" in the navigation menu's search bar will still bring up autocomplete results for "DomainKeys Identified Mail."

Besides, I don't think it will fit the menu to use "DKIM (DomainKeys Identified Mail)" label.
