### ISSUE TITLE
Default sub-server template doesn't correctly set PHP mode

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#759]
Jamie, we have a bug with the default template for sub-servers, in relation to PHP mode. If default sub-server template doesn't exist, i.e. not saved then with all lates commits it incorrectly shows `mod_php` as an option. `mod_php` isn't installed on the system of course.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/4426533/02070940-b8f1-4f0f-8fba-92832f334f07)

Later, even if we save default sub-server template and select `FCGId` as a mode, and later create a sub-server, then unfortunately `FCGId` isn't selected.

It appears that upon sub-server creation whichever PHP mode is set on the default parent template is selected.

**Comment by jcameron** [comment]
Does this happen if the file `/etc/webmin/virtual-server/templates/1` does not exist?

**Comment by iliajie** [comment]
> Does this happen if the file `/etc/webmin/virtual-server/templates/1` does not exist?



Yes. The issue shown in the screenshot happens only if sub-domain template wasn't saved.

The other issues still happens, even after sub-server template is saved, i.e. selected PHP mode isn't applied from sub-server template.

**Comment by iliajie** [comment]
Thanks, will do.

**Comment by iliajie** [comment]
The previous patch when run in post-install creates default sub-server template and set PHP mode to default PHP-FPM.

However, the original problem isn't yet solved, i.e. creating a new sub-domain with sub-server template doesn't set correct PHP execution mode. For example, in my case I had PHP-FPM set on the default template for the sub-server, and after sub-server was created the PHP execution mode was set to CGI (last option in the list), and not FPM.

**Comment by jcameron** [comment]
You're right ... looking into this now

**Comment by jcameron** [comment]
Ok this should be fixed with the latest commits by making the sub-server PHP template options settable and inheritable separately from the website options.

**Comment by iliajie** [comment]
> Ok this should be fixed with the latest commits by making the sub-server PHP template options settable and inheritable separately from the website options.

Thanks! It seems to work just fine now!

Related Changes Ref.: https://github.com/virtualmin/virtualmin-gpl/commit/360cdb53f7f4f2e25253b473f4f25bf12dbe75c1 https://github.com/virtualmin/virtualmin-gpl/commit/290eac807b14850926f8e3e75f57777e353034ff https://github.com/virtualmin/virtualmin-gpl/commit/9a63c765a480da3898bee2c52465ff001989499a https://github.com/virtualmin/virtualmin-gpl/commit/c050effb5329a3c6f8fe88a33a8ab36c04edf245
