### ISSUE TITLE
Software Packages: Separate into tabs

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#762]
Jamie, I'd like to suggest to add 3 tabs to Software Packages module main page, rather than dropping everything on one page, e.g.:

**Install** and move into it:
  - Install a New Package
  
**Search** and move into it:
  - Installed Packages
  - Identify a File
  
**Upgrade** and move into it:
  - Upgrade All Packages

**Comment by jcameron** [comment]
That seems reasonable to me! The layout of the current module is *very* old and doesn't match our current UI standards.

**Comment by jcameron** [comment]
Done here : https://github.com/webmin/webmin/commit/24bf147c9a96984ee95ccbd5c3e4bfce8014f58e
