### ISSUE TITLE
Backup restore form: Path without leading / does not work

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#766]
Entering a path without leading `/` in the `Restore source` for `Local file or directory` will show the correct folder structure in the popup window.
When selecting a file inside the popup the path will be propperly adjusted in the input **without** appending the leading `/`

When clicking the `Show What Will Be Restored`-button a `Restore failed : Missing or invalid absolute local file`-message indicates that the absolut path with the leading `/`  should have been entered.

By simply adding the leading `/` an re-submitting everything works fine.

**Comment by jcameron** [comment]
We will support relative paths for command-line restores, but in the UI we can't really support local paths as it's not cleat what it would be relative to. Unless the restore is being done as a domain owner, in which case it could be relative to the domain's home directory.

**Comment by PitWenkin** [comment]
I don't need a relative path …

But it is possible to both enter `/path/tobackup/folder` as well as `path/toback/folder` in the GUI.  Both of which show the right folder.

But after submitting the form I get the `Restore failed : Missing or invalid absolute local file` message. Which indicates that the GUI should **not** accept relative path (at least not for root/reseller accounts)

**Comment by jcameron** [comment]
What do you mean by "show the right folder" ? Do you mean in the popup file browser?

**Comment by iliajie** [comment]
> Which indicates that the GUI should **not** accept relative path (at least not for root/reseller accounts)

That's expected, since we can't always presume the relative path defaults to the current user home directory. It is much more straight forward to just deal with full paths only in the UI.
