### ISSUE TITLE
Virtualmin with NGINX and Access Control not accepting IPv6 address/subnet

### ISSUE THREAD

**Issue by AndrusLuht** [virtualmin/virtualmin-gpl#767]
SYSTEM INFORMATION	
OS type and version	Ubuntu Linux 22.04.4
Webmin version	7.9.0
Virtualmin version	2.105
Related packages	nginx

It is not possible to enter valid IPv6 subnet in the Web Configuration > Configure Nginx website > Access Control. Saving it fails with error message "Failed to save access control: xxxx:xxxx:x:x::/64 is not a valid address or address/CIDR

Manually editing the virtual server nginx configuration file produces the result but renders the virtualmin interface not usable to manage allowed addresses/subnets.

**Comment by jcameron** [comment]
Thanks! We'll fix this in a future release of the Nginx plugin - also, the fix can be seen here : https://github.com/virtualmin/virtualmin-nginx/commit/7e6f4f91a04851b0114b24a45d337c3c5e4f2004
