### ISSUE TITLE
Database users always have user@domain format

### ISSUE THREAD

**Issue by jcameron** [virtualmin/virtualmin-gpl#769]
@iliajie anytime a new database-only user is created, he gets a user@domain.com format MySQL login, rather than the standard user-domain or whatever is set in the template. 

The logic for this is here : https://github.com/virtualmin/virtualmin-gpl/blob/master/save_user_db.cgi#L21

**Comment by iliajie** [comment]
Oh, you're right! I missed it before. Now fixed in this https://github.com/virtualmin/virtualmin-gpl/commit/8b00cd26d5ba38bdf08fb02afe09105181ccff29 patch.

**Comment by jcameron** [comment]
Thanks!
