### ISSUE TITLE
Feature reset for webserver and spam filtering failed

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#772]
Hello Jamie!

As trying to reset all features for the virtual server, I got these errors:
<img width="1053" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/e26fc82f-ce8c-4e1f-a57a-08b7dd862c5d">

<img width="1079" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/2e0f8e40-1aa5-40dd-af9a-4efcec628e73">

The error message looks somewhat confusing and unrelated. PHP mode for the domain is FPM.

**Comment by jcameron** [comment]
Hmm, that does look like a bug! Do you only get that error when resetting, or does it happen on other actions like changing the PHP mode?

**Comment by iliajie** [comment]
No, only get this upon feature resetting.

**Comment by jcameron** [comment]
Can you enable display of the full stack trace so we can see where in the code the failure is happening?

**Comment by iliajie** [comment]
I already have `error_stack=1` set in Webmin config.

**Comment by jcameron** [comment]
Is anything logged to `/var/webmin/miniserv.error` ?

**Comment by jcameron** [comment]
Also, do you get the same error if you run `virtualmin reset-feature --domain whatever.com --spam` ?

**Comment by iliajie** [comment]
The source of the original error was linked to a related issue at https://github.com/virtualmin/virtualmin-gpl/issues/773, which has already been addressed.

Before that, I also encountered an error (on top of, and directly related to the original error described in this ticket) when changing the PHP mode to FCGId on the PHP Options page because the username for the same UID was incorrect due to a reset. While the original issue has been addressed, there might be something else that needs attention, perhaps?

Please check the screenshot provided below for the error stack:

<img width="1439" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/62f7965d-ebfa-4b0c-82f8-add4cc440d16">

**Comment by jcameron** [comment]
Seems unlikely that the issue with two users having the same UID would cause that error. In fact I can't see how that could ever happen unless something else deleted the temp file created by the `_as_user` functions.

Does it happen consistently for you?

**Comment by iliajie** [comment]
No, not consistently at all! However, if we unroll the latest patch for Administrator user reset (in `feature-unix.pl`), create FTP user, and then reset all features, then yes, it happens.

**Comment by jcameron** [comment]
Ok, if that latest patch fixed it, then I think we can consider this solved.

**Comment by iliajie** [comment]
> Ok, if that latest patch fixed it, then I think we can consider this solved.

I don't think it solves the problem completely, because it's still possible to choose **Fully reset by turning features on and off?** with **Administration user** reset, and fully break the domain, leaving files under home with wrong permissions. Check this one out:

```
Resetting Administration user ..
Deleting administration user ..
.. done
Deleting administration group ..
.. done
Creating administration group debian12-pro ..
.. done
Creating administration user debian12-pro ..
.. done
Creating aliases for administration user ..
.. done
Adding administration user to groups ..
.. done
.. done
Resetting DNS domain ..
.. ignoring warning : DNS records will be lost : 202305._domainkey (TXT)
Deleting DNS zone ..
.. done
Adding new DNS zone ..
.. done
.. done
Resetting Mail for domain ..
Removing from email domains list ..
.. done
Deleting mail aliases ..
.. done
Removing DKIM records from DNS domain debian12-pro.virtualmin.dev ..
.. already gone
Adding to email domains list ..
.. done
Adding DKIM records to DNS domain debian12-pro.virtualmin.dev ..
.. added successfully
.. done
Resetting Apache website ..
Deleting virtual website ..
.. done
Deleting Apache log files ..
.. done
Adding new virtual website ..
.. done
Switching to CGI execution mode suEXEC wrapper ..
.. done
Adding webserver user www-data to server's group ..
.. done
Performing other Apache configuration ..
.. configuration failed : Failed to open /home/debian12-pro/cgi-bin/php8.2.cgi.webmintmp.29901 : Permission denied 
.. done
Resetting Log file rotation ..
Disabling log file rotation ..
.. done
Setting up log file rotation ..
.. done
.. done
Resetting MariaDB database ..
Deleting MariaDB database debian12_pro ..
.. done
Deleting MariaDB login ..
.. done
Creating MariaDB login ..
.. done
Creating MariaDB database debian12_pro ..
.. done
.. done
Resetting Spam filtering ..
Turning off spam filtering ..
.. done
Setting up spam filtering ..
.. Spam filtering failed! : Failed to replace /home/debian12-pro/cgi-bin/php8.2.cgi with /home/debian12-pro/cgi-bin/php8.2.cgi.webmintmp.29901 : Operation not permitted 
.. done
Resetting Status monitoring ..
Removing status monitor for website ..
.. done
Removing status monitor for SSL certificate ..
.. done
Creating status monitor for website ..
.. done
.. done
Resetting Webmin login ..
Deleting Webmin login ..
.. done
Creating Webmin user ..
.. done
.. done
Resetting AWStats reporting ..
.. done
Restarting PHP-FPM 8.2 server ..
.. done
Applying webserver configuration ..
.. done
Applying DNS zone for debian12-pro.virtualmin.dev ..
.. done
Re-starting DNS server ..
.. done
Re-loading Webmin ..
.. done
```

If I try to use **Fix Permissions** tab to fix permissions, it fixes it partially as it doesn't apply permissions to `public_html` directory, leaving it broken still in the end, until fixed manually! Also, the same issue starts to happen on **PHP Options** page again (expectedly) I described earlier.

**Suggestions:**

 - Completely give up on idea of resetting `unix` feature (remove **Administrator user** as an option from the list) or apply permissions fix afterwards.
 - Indirectly related: fix `public_html` permissions too, optionally at least!
 
**Fix Permissions** and **Reset Features** should be a safe haven, not a death trap. :-)

**Comment by iliajie** [comment]
Alright, but let's just remove it from the select, and internally from the array?

**Comment by jcameron** [comment]
Ok I've checked in a fix to prevent this kind of dangerous full reset

**Comment by iliajie** [comment]
> Ok I've checked in a fix to prevent this kind of dangerous full reset

Alright, great! That works!
