### ISSUE TITLE
Ability to set/manage each user's SSH public keys in vserver users list and in usermin

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#776]
After much searching I found issue #284, but my understanding is that it was implemented just for the primary user of the server, and only on the virtual server's _creation_ page. If so, there are few remaining issues with that:
* The "SSH public key" header label in the "New virtual server details" section somehow made me think it was about the SSH _host_ key rather than the main admin user's key. It might be worth being explicit and labelling it something like "SSH public key for administrative user"?
* There is no way to delete or update the SSH key once set, in "Edit Virtual Server" or "Edit Users"
* This does not solve the problem for add-on users to that vserver? (see below)

It would be nice to have the ability for:
* A virtualmin admin to set up (or update) SSH public keys for each individual (sub-)user of a server, from keys that those users may have sent them to add. Ideally with a way to allow only pubkey-based logins for that server/users.
* A user to "self-service" upload/update their SSH pubkeys via the usermin web interface, which can be practical during their initial setup

Currently (from what I can see in version 7.9.0), in this case, it seems like you have to manually create the `.ssh` folder (with appropriate permissions) and create (or edit) the `authorized_keys` file on the commandline, which isn't the hardest thing to do for a Linux admin, but it's not super convenient either :)

**Comment by jcameron** [comment]
We've actually implemented this for Virtualmin 7.10.0, which should be out in a day or two!

**Comment by EdisAganovic** [comment]
But only for Pro users. Please add that in changelog.

**Comment by iliajie** [comment]
> But only for Pro users. Please add that in changelog.

Done.
