### ISSUE TITLE
dkim keyfiles in /etc, could be hard to manage, move to /etc/dkimkeys should help

### ISSUE THREAD

**Issue by aqueos** [virtualmin/virtualmin-gpl#778]
hi,

 when you add dkim to a domain it create file in /etc/, with a lot of domains it will be hard to manage and fillup /etc.
```

/etc/dkim-keytable
::::::::::::::
default	%:202402:/etc/dkim.key
150998780827309	xxxxxxxxxxxxxxx.fr:202402:/etc/150998780827309.dkim-key
```

 I think it should be stored in a specific directory that could be for exemple 

/etc/dkimkeys

 the debian package create /etc/dkimkeys for this :

This directory is for storing private keys associated with DKIM signing with
opendkim.

```
Here is advice from upstream

(4) Store the private key in a safe place.  We generally use a path like
    /var/db/dkim/SELECTOR.key.pem (where "SELECTOR" is the name you chose).
    The /var/db/dkim directory and the associated .pem file should be owned by
    the user that will be executing the filter (preferably not the
    superuser) and be mode 0700 and 0600 respectively.

In Debian, we use /etc/dkimkeys by default and the directory permissions and
ownership are set correctly.  Ensure that the private key is owned by the
opendkim user and the permissions are 0600.
```

 so i think on debian based at least we could use this directory for that.

best regards,
Ghislain.

**Comment by jcameron** [comment]
That's a good suggestion, let me look into this ...

**Comment by jcameron** [comment]
Ok, we'll fix this in the next Virtualmin release.

**Comment by aqueos** [comment]
thanks a lot for this quick answer and action :)

best regards,
Ghislain.
