### ISSUE TITLE
"Create host default domain with Let’s Encrypt certificate" option doesn't work

### ISSUE THREAD

**Issue by danboid** [virtualmin/virtualmin-gpl#780]
OS type and version 	Ubuntu Linux 22.04.4
Webmin version 	2.105
Virtualmin version 	7.10.0 Pro
Related packages 	SUGGESTED

Our vmin server is currently using the default port 10000 for the webmin login page. That has a current SSL cert but our security guys are complaining that our security score is being negatively impacted because the root domain (without the :10000 appended) doesn’t have a valid cert.

“Create host default domain with Let’s Encrypt certificate” sounds like it should fix this exact issue but after enabling that I still have the same issue because that option hasn't changed the default subdomain nor has it got rid of the cert errors for the subdomain/page that is currently set as the default. I have tried both the "Yes" and "Yes and keep visible" options with no luck.

https://forum.virtualmin.com/t/primary-ssl-cert-for-main-domain/125648/11

**Comment by iliajie** [comment]
Hello,

The "Create host default domain with Let’s Encrypt certificate" feature in Virtualmin sets up a default domain with your hostname. This domain is hidden and doesn't serve any special function. It's there to improve your experience by ensuring you can log into Virtualmin with a valid SSL certificate right after installation.

**Comment by iliajie** [comment]
Default domain for the webserver can be set in **Website Options** page.

**Comment by danboid** [comment]
Sounds like it doesn't do what I thought it did then. Seems I'll have to create a new subdomain with the same name as the root domain then make that the default?

**Comment by iliajie** [comment]
Yeah, as there are many ways of making it work. I highly recommend posting this question to Virtualmin Forums. This is the issue tracker.

**Comment by shoulders** [comment]
@iliajie just a quick followup as there might be an issue with

System Settings → SSL Settings → Create host domain with Let’s Encrypt certtificate

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/5c6724ca-a4af-49a0-821a-0eecbe446318)

The host domain does not appear in the virtual server list when you use `Yes, and keep visible`

### From the Tooltip

> **Create host default domain with Let's Encrypt certificate?**
> However, it is possible to use Yes, and keep visible,option to keep host default domain visible, and not have it removed in case Let's Encrypt certificate cannot be requested successfully, which will allow for manual adjustments later on.

**Comment by iliajie** [comment]
You need to run config check for it to be setup.

**Comment by shoulders** [comment]
Can you add `You need to run a configuration check for the virtual server to be created when using this option.` on to the end of the following paragraph in the tooltip.

> However, it is possible to use Yes, and keep visible,option to keep host default domain visible, and not have it removed in case Let's Encrypt certificate cannot be requested successfully, which will allow for manual adjustments later on. You need to run a configuration check for the virtual server to be created when using this option.

Thanks

**Comment by shoulders** [comment]
i see, it is on the `yes` section of the tooltip and by extension this would also cover the `yes, and keep visible` rather that being explicitly noted on both sections of the tooltip. I was reading each text section for each of the options as separate entities.

thanks for the clarification.
