### ISSUE TITLE
Problem with new php version check

### ISSUE THREAD

**Issue by danboid** [virtualmin/virtualmin-gpl#781]
OS type and version Ubuntu Linux 22.04.4
Webmin version 2.105
Virtualmin version 7.10.0 Pro

I have noticed that every time I run `virtualmin check-config` it thinks that php has been upgraded then it updates every domain which takes a while with almost 1000 domains.

I have run the command a few times today without running apt once and it thinks php has been upgraded every time.

**Comment by jcameron** [comment]
That seems like a bug! What's the message Virtualmin is showing when it updates the domains' PHP configs?

**Comment by danboid** [comment]
Arrgh!

I hasd this happen about 4/5times in a row earlier today. I log back on now and, no doubt because I opened a bug report, its working fine now. I just tried 4 times in a row and it wasn't hallucnating new php versions any more.
