### ISSUE TITLE
Chrooted User Encounters SSL Certificate Errors with `wget`

### ISSUE THREAD

**Issue by SamSirry** [virtualmin/virtualmin-gpl#783]
Hello,

I’ve encountered an issue where a chrooted user created by Virtualmin is unable to use wget to download resources over HTTPS. The operation fails with a “certificate not trusted” error. However, the same operation succeeds when performed by the root user.

This issue seems to be related to the chroot environment, which may not have access to the necessary SSL certificates. I’ve found a related discussion on the Virtualmin community forum that describes a similar problem: [Chroot and /etc/ssl/certs for PHP/cURL](https://forum.virtualmin.com/t/chroot-and-etc-ssl-certs-for-php-curl/123559).

A potential solution is to copy the SSL certificates into the chroot directory. However, this has to be done manually each time a new chrooted user is created. It would be helpful if Virtualmin could handle this automatically when creating a new chrooted user or provide an option to do so.

Thank you for your attention to this matter.

**Comment by iliajie** [comment]
Hello,

> However, this has to be done manually each time a new chrooted user is created. It would be helpful if Virtualmin could handle this automatically when creating a new chrooted user or provide an option to do so.

Thanks for reaching out!

This is actually already possible in Virtualmin Pro version, e.g.:

<img width="1439" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/f6fbdf98-71ff-4a45-9062-85d920573566">

**Comment by SamSirry** [comment]
That's cool to know 🆒
Thank you!!
