### ISSUE TITLE
Plesk 18 - complex subscription migration problems

### ISSUE THREAD

**Issue by urbaman** [virtualmin/virtualmin-gpl#784]
Hi,

I'm trying to migrate from Plesk 18 (latest), and can't seem to be able to migrate complex subscriptions with more than one domain and subdomains.

If I migrate simple subscriptions, it goes flawlessly, but if I try to migrate complex subscriptions it fails to properly locate domains and subdomains, create proper virtual servers and sub-servers.

I could (already did: https://forum.virtualmin.com/t/migrate-from-plesk-multidomain-subscription/124068?u=urbaman) provide a backup and/or more details.

Thank you very much

**Comment by jcameron** [comment]
We're not as familiar with the Plesk terminology - could you explain further what you mean by complex "subscriptions" ? Does it just mean accounts with many domains and sub-domains?

**Comment by urbaman** [comment]
Hi,

Yes, customers have subscriptions, subscriptions have multiple domain and subdomains (servers and subservers?)

I can only do complete subscription backup from plesk, and when I try to migrate it to virtualmin (plesk 9+ migration plugin), it fails recognizing domains/servers, subdomains/subservers and relative properties (directories, dbs,..)

**Comment by jcameron** [comment]
Is it possible that we could get a copy of one of these problematic Plesk backups to look at? Unfortunately the only way to implement this kind of migration in Virtualmin is to reverse-engineer the internal structure..

**Comment by urbaman** [comment]
Yes, let me know how do you prefer to get it.

**Comment by jcameron** [comment]
You could upload it to Google Drive or Dropbox, and send me a link at jcameron@virtualmin.com (and reference this ticket in the email)

**Comment by urbaman** [comment]
Hi  @jcameron 

You have mail.

Let me know if I can help anyway.

**Comment by urbaman** [comment]
Hi,

Any news on this?

**Comment by jcameron** [comment]
Did you send me that link to the uploaded backup files?

**Comment by urbaman** [comment]
@jcameron yes, sent on April 19 and now again.

**Comment by urbaman** [comment]
Hi @jcameron 

Sorry to get back to this old stuff, did you have time to look at it? Can I help some way?

I'd really like to have a usable migration tool for this scenario.

Thank you.

**Comment by jcameron** [comment]
I'm taking a look at your backup now. Can you tell me more about what domains, users and accounts were in this backup on the original Plesk system?

**Comment by urbaman** [comment]
Hi,

This is a single subscription (I would migrate single subscriptions one by one), user urbaman, with a couple of sites (wordpress): a domain (urbaman.it) and a sub-domain (wp-admin.urbaman.it).

Thank you very much

**Comment by jcameron** [comment]
I just did a test migration of that backup you provided, and it did indeed create those two domains.

**Comment by urbaman** [comment]
it also does to me, but with an empty wp-admin sub-domain folder:

![Migrate](https://github.com/user-attachments/assets/25f2120e-87a4-4ffd-9bb1-2fceeca09374)

![MigrateEmptySubDomain](https://github.com/user-attachments/assets/58caecfa-423e-43c6-a868-1c5ce63e36cb)

**Comment by jcameron** [comment]
Ok I see the issue ... the problem is that Plesk 18 is using a new compression format. We'll fix this in the next release, or you can see the fix here : https://github.com/virtualmin/virtualmin-gpl/commit/e7ff6b0f6e0432b1cbd4bcae6b69920a92fc6087

**Comment by urbaman** [comment]
Thank you, tried to change the file online without success, will probably wait for the new release.

**Comment by jcameron** [comment]
If you updated that file from my patch, make sure you run `/etc/webmin/restart` afterwards for it to take effect. Also make sure you have the `unzstd` command installed.

**Comment by urbaman** [comment]
Well, do not know if I'm doing it fine:

- Added the line you pointed out in /usr/share/webmin/virtual-server/virtual-server-lib-funcs.pl
- Restarted webmin

Also tried rebooting the machine, the public-html of the sub-domain is still empty:

Operating system	Ubuntu Linux 22.04.5
Webmin version	2.202
Usermin version	2.102
Virtualmin version	7.20.2  

PS: I'm using the Plesk9+ migration from GUI:

![image](https://github.com/user-attachments/assets/d04c4687-1689-4474-8d5b-26401ba74d03)

And the output:

```
Uploading migration file ..
.. uploaded 144.23 MiB
Validating migration file ..
.. done
Starting migration of urbaman.it from uploaded file ..
Finding contents files ..
.. done
Checking for Plesk features ..
.. found Home directory, Administration user, Webmin login, Mail for domain, Apache website, Log file rotation, MariaDB database .
However, the follow features are not supported or enabled on your system : DNS domain, Webalizer reporting. Some functions of the migrated virtual server may not work.
Checking for clashes and dependencies ..
.. all OK
Creating initial virtual server urbaman.it ..
Saving server details ..
.. done
Creating administration group urbaman ..
.. done
Creating administration user urbaman ..
.. done
Creating aliases for administration user ..
.. done
Adding administration user to groups ..
.. done
Creating home directory ..
.. done
Creating mailbox for administration user ..
.. done
Adding to email domains list ..
.. done
Adding new virtual website ..
.. done
Setting up CGI scripts support with suEXEC execution mode ..
.. done
Adding webserver user www-data to server's group ..
.. done
Performing other Apache configuration ..
.. done
Setting up log file rotation ..
.. done
Creating MariaDB login ..
.. done
Creating Webmin user ..
.. done
Saving server details ..
.. done
Applying webserver configuration ..
.. done
Re-loading Webmin ..
.. done
Updating Webmin user ..
.. done
Re-loading Webmin ..
.. done
.. done
Copying web pages ..
.. done
Copying CGI scripts ..
.. done
Migrating SSL certificate and key ..
.. not found in backup
Re-creating mail users ..
.. done (migrated 22 users)
Re-creating mail aliases ..
.. done (migrated 1 aliases)
Migrating MySQL databases ..
Creating MariaDB database urbaman_wp_akyp8 ..
.. done
Creating MariaDB database urbaman_wp_uekrw ..
.. done
.. done (migrated 2 databases, and created 2 users)
Creating sub-domain wp-manager.urbaman.it ..
Saving server details ..
.. done
Creating home directory ..
.. done
Adding to email domains list ..
.. done
Adding default mail aliases ..
.. done
Adding new virtual website ..
.. done
Setting up CGI scripts support with suEXEC execution mode ..
.. done
Performing other Apache configuration ..
.. done
Saving server details ..
.. done
Applying webserver configuration ..
.. done
Updating Webmin user ..
.. done
Re-loading Webmin ..
.. done
.. done
Re-creating sub-domain users ..
.. created 0
Successfully migrated urbaman.it virtual server, [click here](https://www.fateitalia.it:2087/virtual-server/edit_domain.cgi?dom=17269339327721) to manage it.
```

**Comment by jcameron** [comment]
Ok I see the issue with sub-domains - I've checked in another fix that should address this

**Comment by urbaman** [comment]
I @jcameron 

I tried and finally see all of the correct files.
Now I'll try to find out why the websites give out error 500, but this is a different issue.

Thank you very much.

**Comment by jcameron** [comment]
Excellent! Thanks for your help in supplying backups to re-produce this issue ..

**Comment by urbaman** [comment]
Hi @jcameron 

I think I have another, more complex situation:

- domain1
- - subdomain1-1
- - subdomain1-2
- domain2
- - subdomain2-1
- - subdomain2-2

domain2 gets created in Plesk as a sub-virtual-server of domain1 instead of being a parenr virtual-server by itself.
also, mail users of domain2 get created under domain1.

Should I open a new issue or reopen this one? Should I send you the backup (it's big)?

Thank you very much.

**Comment by jcameron** [comment]
Please open a new issue for this, as that looks like a separate bug. Also if you can provide a backup that reproduces the problem, that would be really useful!
