### ISSUE TITLE
Drop Vpopmail support?

### ISSUE THREAD

**Issue by jcameron** [virtualmin/virtualmin-gpl#788]
Opening this to discuss if we should simplify Virtualmin by removing the support for Vpopmail as a mail system, since I suspect nobody uses it these days.

@iliajie @swelljoe what do you think?

**Comment by swelljoe** [comment]
Last release was ~14 years ago, and last commits were ~9 years ago. I haven't seen it mentioned in a user question in at least that many years. The Inter7 website about it still exists, but doesn't seem to have been touched in a decade or more.

I believe it's smart to drop it. Offering long unmaintained software as a thing that someone might want to use isn't doing users any favors.

I would like us to move toward virtual mailboxes independent of system user accounts, but this aint the way anybody ought to do it today.

**Comment by iliajie** [comment]
Agreed, I think Vpopmail has to go, just as Qmail.

**Comment by jcameron** [comment]
Ok I will make it so!

**Comment by jcameron** [comment]
I'll also drop the incomplete Exim support, unless someone objects?

**Comment by iliajie** [comment]
I wonder if anyone is using it in its incomplete state? Also, is there a lot of work required to make it complete?

**Comment by jcameron** [comment]
I strongly doubt anyone's using it!

**Comment by iliajie** [comment]
cPanel uses Exim, and Exim itself is actively supported. Though, I agree, if its support in Virtualmin is incomplete, we should consider dropping it. Postfix already does it all and more.

**Comment by iliajie** [comment]
I can see you've already deleted Vpopmail and Exim. What about Qmail? We cannot install Qmail from either the EL or Debian repositories. Do we have complete support for Qmail?

**Comment by iliajie** [comment]
Alright, then I assume we can close it.

**Comment by marclaporte** [comment]
I still see some references to VPopMail:
https://github.com/virtualmin/virtualmin-gpl/blob/master/help/config_vpopmail_group.html

**Comment by jcameron** [comment]
Thanks, I just deleted those..

**Comment by marclaporte** [comment]
Super. There are still some hits (translations, config files, etc.): https://github.com/search?q=repo%3Avirtualmin%2Fvirtualmin-gpl%20vpopmail&type=code

**Comment by iliajie** [comment]
Thanks, Marc. I have updated the translations, and all previously removed strings from the English file will also be removed from the translations.
