### ISSUE TITLE
SSL certificate not detected when custom path

### ISSUE THREAD

**Issue by xxorax** [virtualmin/virtualmin-gpl#791]
If I use the `Web Configuration >  Configure SSL Website >> SSL Option` menu to set a custom path for cert, key and CA chain, then the `Manage Virtual Server > Setup SSL Certificate` page tells there is no certificate installed :

> This virtual server does not have an SSL certificate yet. Use one of the tabs on this page to generate a cert and key.

Using the tab ` Update certificate and Key` works, but it copies the files under the domain's home instead of just changing the configuration. Using the install-cert API  does the same.
This last behavior it's strange, while using built-it letsencrypt processing store everything in /etc/ssl ...

Thanks

**Comment by iliajie** [comment]
Hello,

Martin , you could go to **Virtual Server Summary**, click on the **Domain ID** while holding Alt key (Option on Mac) and manually update paths in `ssl_` related keys.

Jamie, what is the value of sticking up to the old SSL paths and not using whatever is currently defined on the template. What if a user migrated 100 domains from CentOS 7 to Rocky 9? Does it mean those domains would be stuck with old paths forever or had to be updated manually?

**Comment by xxorax** [comment]
> Martin, you could go to Virtual Server Summary, click on the Domain ID while holding Alt key (Option on Mac) and manually update paths in ssl_ related keys.

@iliajie Very good shortcut to edit the config file of a domain directly, with caution of course :) I was not aware of this, thanks !

I  confirm : old domains (created on an old Virtualmin version) using letsencrypt stuck with the $HOME/ssl.* files, and there is no way to replace them by /etc/ssl/ (except by editing the domain config file) . Even disabling the `Apache SSL website enabled` option, the ssl_ domain's config is kept.

I guess this restriction is to prevent users who has the `Can manage SSL certificates` capability to not bypass the home directory confinement. But I think it should not be applied to root user.

Thanks !

**Comment by jcameron** [comment]
So it sounds like what we need is a button to copy the SSL cert files to a new location, and update the paths to match?

**Comment by iliajie** [comment]
Why not making it automatically based on existing template?

**Comment by jcameron** [comment]
Because the template generally defines settings for new domains,  not updates to existing ones...

**Comment by iliajie** [comment]
Yes, but not for the options which cannot be changed in anyway? I mean, the path for SSL certificates in particular cannot be changed.

As a new SSL certificate getting requested it wouldn't be completely unexpected to have a path updated according to the current template.

Though, I agree, it's a moot point.

Do you think having another button to show when a path in a domain config is different from the one on the template is better?

**Comment by jcameron** [comment]
Yeah, I agree that we should have a button to move the SSL cert and key to the standard location. I'll work on this...

**Comment by iliajie** [comment]
Thanks!

Though, theoretically speaking, what is the value of having such button? What's the real case scenario, when an admin wouldn't want the SSL path to be updated automatically?

**Comment by jcameron** [comment]
In general we don't ever do these kinds of automatic updates in Virtualmin when a template changes ... it's surprising to admins.

**Comment by iliajie** [comment]
Well, alright. Though, either way it seems to be surprising; 🙂 I just thought to make it more simple. The button would work too.

**Comment by jcameron** [comment]
The next release will add a button to move the cert to the default location, and flags to the `modify-web` API command to do the same.

**Comment by xxorax** [comment]
In waiting, I confirm that I have to change all the following config :
ssl_key
ssl_cert
ssl_chain
ssl_combined
ssl_everything
to have everything in the path I want. 
That's mean even the template path for each of them are set to `Same directory as key file`, changing only the ssl_key path is not enough.

Thanks
