### ISSUE TITLE
CGI script execution mode is not inherited

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#792]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### The issue

the option `CGI script execution mode` in templates does not have an inherit option from the default template

The image below is from my `Developer` template

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/96369b7a-0817-4236-af0a-2c910bf349a5)

### proposed solution

Make this an inheritable option

### Additional

With these being an aging technology, should the default setting in the default template be **CGI scripts disabled**

**Comment by shoulders** [comment]
I think that if you have a system where you inherit from a default template, then all options should be inheritable not just some of the options.

**Comment by shoulders** [comment]
- I hope this clears things up. If you need more, let me know 😄 
- There is no clone button for the default template. There used to be
- **p.s.** I early today manually changed the default template option to: `CGI scripts disabled`

### These were my templates before this option was added
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/86d23705-69c4-48c2-86af-8b3fbb4674a6)

### This is my developer template showing this option
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/1991eea1-c373-4d5f-a56f-419772b84f5c)

### I have just now done - create a template from the default settings + I just hit create (template called chicken)
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/4cc69193-2dbb-4223-9522-f3fa89bae64e)

As you can see none of them show the inherit feature.

**Comment by jcameron** [comment]
Currently this option doesn't get inherited separately - if "Directives and settings for new websites" is set to "From default template", the CGI mode will also be inherited.

**Comment by shoulders** [comment]
- on my `developer` template, `From default settings` is selected but `CGI scripts execution mode` is not greyed out and still can be changed independently. Its radio selection does not match the `default` template upon loading the `website for domain` section in the server template.
- when you create a virtual server with the `developer` template it does pull the setting from the `default` template as expected

**Comment by jcameron** [comment]
> on my developer template, From default settings is selected but CGI scripts execution mode is not greyed out

That sounds like a bug! Can you attach a screenshot of that page?

**Comment by shoulders** [comment]
here you go

### Default Template
![default-settings](https://github.com/virtualmin/virtualmin-gpl/assets/319997/a4588e51-9612-4551-afc6-4659ad614d6e)

### Developer Template
![developer-template](https://github.com/virtualmin/virtualmin-gpl/assets/319997/6cf18986-1651-458c-a4c3-36340cf8543b)

**Comment by jcameron** [comment]
Oh that's a bug, the field should be greyed out - we'll fix this in the next release.
