### ISSUE TITLE
On Webmin tab, Virtualmin tab right click does not respect `Default page for Virtualmin`

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#796]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### the background
When you are on the Webmin tab

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/ebb11964-bb9f-4bd9-9636-6071fef39236)

You can right click on the virtualmin tab to open a new tab on Virtualmin and this always brings up the `Virtualmin Virtual Servers` page

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/e3ec224d-e9e4-4686-a2d0-2bf3c10b6cdd)

### the issue

This operation does not respect the setting: `Theme Configuration --> Default page for Virtualmin`

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/20699652-2a59-434e-b04c-55bee562c3ae)

### the solution

I would like the right click to respect the setting: `Theme Configuration --> Default page for Virtualmin`

or the option to be able to select either the `Virtualmin Virtual Servers` or `Dashboard`

### Additional

If I am on a virtualmin page and right click on the Webmin tab, this opens on the dashboard and also does not respect the setting

`Theme Configuration --> Default page for Webmin` which is ok because the dashboard is a good place to land.

If you set the webmin tab to be initially opened upon login, this setting is respected.

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up! Sadly, it wasn't trivial to fix. However, the latest patches should do it the right way.

Notes:

1. When right-clicking the same product switch (top-left of navigation menu), meaning the one that is currently opened, it will clone/re-open the right page content.
2. When right-clicking on a product switch that isn't currently selected, it will use defaults from the theme config (as you pointed out).
3. You will need to re-save the theme configuration page after applying the latest changes.

**Comment by shoulders** [comment]
I appreciated all the work you and the team do.

**Comment by iliajie** [comment]
> I appreciated all the work you and the team do.

You're welcome; we appreciate your suggestions!
