### ISSUE TITLE
Reset Pro Options visibility

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#797]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### the issue

The was raised by another user. during the use of GPL the user had disabled the showing of additional install scripts so was just left with the free ones. the user was keen to see what paid versions were available but did not want to go and re-install a whole virtualmin setup again just to see them. https://forum.virtualmin.com/t/cannot-see-pro-scripts-in-install-scripts-page/125059

`Virtualmin --> System Settings --> Virtualmin Configuration --> Configuration category: User interface settings --> Show Pro features overview?`
- This option does not restore the permanently disabled pro script displays but hides menu items I think.

### proposed solution
A single button where you can re-enable all of the Pro "advertising". A user who has been using the GPL for a while and then wants to upgrade to pro might just want to have a look of the benefits of Pro on his system before purchase.

I don't think you need to fine grain this and put a show pro option on each page. due to the infrequency of this getting used a single button and action will do the job.

**Comment by iliajie** [comment]
Hello,

> the user was keen to see what paid versions were available but did not want to go and re-install a whole virtualmin setup again just to see them.

This is definitely something that shouldn't be done!

I will address this in the UI by resetting the seen Pro features cache when the **Clear Cache** button is clicked, e.g.:

<img width="297" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/b5bd08ba-97fd-4de9-9753-641c8b967831">


For now, a user could just run:

```
rm -f /var/webmin/modules/virtual-server/seenfeatures/root-pro-tips
```

.. to show all hidden Pro features advertisements for `root` user.
