### ISSUE TITLE
[Bug] syncmx-domain

### ISSUE THREAD

**Issue by TakeMeNL** [virtualmin/virtualmin-gpl#80]
Hi there,

So i found that syncmx-domain has a bug. 
It also syncs disabled domains. Which i don't want.
Also the syncmx-domain accepts --all-domains but it's not in de usage info.

Personally i would add this snipped here: https://github.com/virtualmin/virtualmin-gpl/blob/5d377ca7dbe94cac41e02756ae9f8ff65c761e2e/syncmx-domain.pl#L72
```
foreach $d (grep { $_->{'mail'} } @doms) {
	if ($d->{'disabled'}) {
		next
	}
```
But this will only skip at this command. I think this has to go deeper in the script and also remove disabled domains. Even-though this will be done when a domain is getting disabled.

And update the usage:
```
sub usage
{
print $_[0],"\n\n" if ($_[0]);
print "Updates allowed relay addresses in one or more domains.\n";
print "\n";
print "virtualmin syncmx-domain [--domain name]\n";
print "                         [--user username]\n";
print "                         [--all-domains]\n";
exit(1);
}
```

**Comment by jcameron** [comment]
What problem does syncing disabled domains cause though? Does it add non-disabled MX records?

**Comment by TakeMeNL** [comment]
So what its currently going on is that in the /etc/postfix/relay_recipients is also filled with disabled mailboxes/domains.
In the main.cf is also still the relay_domains populated with disabled domains.
Side note. when removing relay_domains it is not repopulated?

**Comment by jcameron** [comment]
Does including disabled mailboxes in `/etc/postfix/relay_recipients` cause problems though? Like relaying email that then gets bounced from the primary system?

**Comment by TakeMeNL** [comment]
Well yes indeed, because no mailbox/domain is found it gets bounced.
I haven't yet found any problems with that, but if someone sends spam mails to that address you get backscatter spam. Bouncing emails to other mailboxes. Thats theorie.

But if it's for you guys no problem to have disabled domains on secondary server well heck i have to accept that. Because it looks like it you're not going to do anything. Just say it then...
No harmful meaning here, its text. I just don't like people that don't be straight to the point.
_Thats why i don't work at helpdesk jobs :P_

**Comment by jcameron** [comment]
Actually I think you're correct - it's not always clear what the correct configuration choice is (rejecting early vs. bouncing after relaying), but upon reflection you're right that the correct choice is to reject as early as possible.

**Comment by jcameron** [comment]
The next release of Virtualmin will work the way you suggested.

**Comment by TakeMeNL** [comment]
Thank you for considering and support :)
