### ISSUE TITLE
virtualmin modify-php-ini - some changes to the description

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#801]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      3  package updates are available   |

## The background

`virtualmin help modify-php-ini`

![960539e4e3f2b345a7ec9700e1a60a5bff7956a2](https://github.com/virtualmin/virtualmin-gpl/assets/319997/cab6be35-65dc-4adf-8c15-7913aef2c67e)

## The issue

> This command can be used to change the value of a PHP configuration
variable (set in the php.ini file and Apache configuration) for one or
many virtual servers at once.

This refers to php.ini and Apache configuration and their are a few things wrong with this statement

  - I am not sure that the Apache configuration is altered by this command. it might be a relic from the `mod_php` days.
  - This command now alters `.conf` files for the the `PHP-FPM` service

### Proposed solution 

Can you make some changes to the description for the following points

-  (set in the php.ini file and Apache configuration)
    -->
    (set in the php.ini file and FPM .conf files)
- This does not change the global `php.ini`.
  - If this is an obvious point, please ignore.

## Additional
- https://forum.virtualmin.com/t/virtualmin-modify-php-ini-some-clarification-needed/126287

**Comment by jcameron** [comment]
Thanks, I'll update the help text to make it clearer what this command modifies. It will still update the Apache config if mod_php is in use though.
