### ISSUE TITLE
Post-Installation wizard - add password generator to MySQL/MariaDB step

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#804]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      2  package updates are available   |

During the installation wizard you get to the following step to create a password for the root DB user.

Can you add a password generator please.

![5](https://github.com/virtualmin/virtualmin-gpl/assets/319997/3c0265df-c58f-454e-a092-ec5efc7d5d74)

**Comment by jcameron** [comment]
@iliajie can you take a look at this one?

**Comment by iliajie** [comment]
Yes, fixed here https://github.com/virtualmin/virtualmin-gpl/commit/132d3e78c8d5fca3199de13b024975df4aef5841.
