### ISSUE TITLE
Cannot unhide this widget

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#805]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      6  package updates are available   |

### the issue

When you hide this widget there is no mechanism to unhide it, or no-one can find it.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/a665bcd1-54c2-4dfd-a666-d6f49ff9d86c)

_

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/18327811-c764-4def-bdb6-5b09d34c4984)

This option does not work

`Theme Configuration --> Configuration category: Table display --> Show content layout control: Yes`

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/3b3db5b2-405d-4775-a7b2-a8c80b86d397)

however the toggle between on and off with this works as long as you have not used the **Hide This Widget**

### proposed solution

- remove the **Hide This Widget** and revert this setting via an update
or
- advise me where to unhide this widget

### additional
- I am not sure what the purpose of hiding the widget achieves so it might be a pointless feature.
- it is not just me  😄  https://forum.virtualmin.com/t/how-do-you-unhide-this-widget/126477/2

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

> however the toggle between on and off with this works as long as you have not used the **Hide This Widget**

It does work if you reload the page.

> * I am not sure what the purpose of hiding the widget achieves so it might be a pointless feature.

We don't want users to see the old table layout, it has no value! Fewer options are better.

**Comment by shoulders** [comment]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      4  package updates are available   |

### Before I start

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/ad87828a-3a8c-4a80-a42d-1880b469c3ea)

Theme Configuration --> Configuration category: Table display --> Show content layout control: Yes

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/0464bedc-dab2-4947-91c1-6385aa400e93)

### hide widget
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/48ae0231-8cef-46bf-afbb-1fbe6208b7ea)

### After I hide this widget

This widget icon is now missing

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/34f1c741-1889-4cb0-ad34-8d0bf0e9d589)
