### ISSUE TITLE
Prevent selecting spam and virus filtering when there is no mail service

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#809]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      44  package updates are available   |

### the issue

When creating a new virtual server, you can select spam and virus filtering for a mail even when this service is not enabled.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/2aa9ca9b-4ac4-4f7a-b004-9a5d873fc7e8)

### proposed solution

can't select spam and mail filtering if no mail service is selected

### Additional

Some websites will send mail via PHP and sendmail and I do not know how this would be affected.

**Comment by iliajie** [comment]
Hello,

> ### proposed solution
> can't select spam and mail filtering if no mail service is selected

That would involve JavaScript. Though, if you try to submit it as it is, you'd still see an error.

However, automatically removing ticks from Spam and Virus options if mail is disabled would be cool.

**Comment by jcameron** [comment]
@iliajie you could send me a PR for this if you like?

**Comment by iliajie** [comment]
Yes, will do!

**Comment by iliajie** [comment]
Implemented here https://github.com/virtualmin/virtualmin-gpl/pull/811.
