### ISSUE TITLE
Quick question about "One file per server (old format)" backup

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#81]
Hi running virtualmin gpl for quite a few years, words cannot describe my gratitude for this wonderful control panel. Thank you and all the contributors.

Doing some maintenance and experimenting with different backends for my backups.

My current functional backup schedule (which is working fine) for backup format is set to:
One file per server (old format)

I tried to create a new identical backup schedule (to a different save target) which is missing the (old format) option.

**My question is, why is this option missing, is it depreciated? 
If so, what is the difference between the One file per server (old format) and One file per server?**

I know this old format option is quite old at this point, and I cannot remember why I selected it back when I originally setup this backup job. (3+ years ago)

If I recall from my testing, I am trying to store long term daily backups into a borg repository and for some reason the old format was working better.(I don't actually remember though.) 

Regardless I don't compress the backups, just tar as I store them on ZFS with compression and long term archive them daily into a long term borg repo.  Just trying to figure out if I should change all my backup jobs to the non old format, or whatever. 

Thanks.

**Comment by jcameron** [comment]
That format is deprecated, as the new "one file per server" format is much faster to create as it doesn't require running `tar` twice on the home directory.

In the latest Virtualmin release, we hid this option as there's basically no situation in which it ever needs to be manually selected.

**Comment by abclution** [comment]
Hey thanks for the reply. 
I will migrate my backups to the new style. 
Appreciate it.
