### ISSUE TITLE
"Last email login" is always empty for new accounts

### ISSUE THREAD

**Issue by RK-BAKU** [virtualmin/virtualmin-gpl#812]
Seems the problem with position seeking somewhere here:
https://github.com/virtualmin/virtualmin-gpl/blob/2d9e7772b60d18bf210599ed9244590afcd6914f/feature-mail.pl#L5566

Setting $lastpos manually to something less than auto-detected value fixes this issue and login timestamps are being populated after then.

**Comment by iliajie** [comment]
If you add a debug line to figure out what `$maillog` actually is, what do you get? You can do this by adding:

```
var_dump($maillog, 'maillog-var');
```

When the code runs, you can find the dump in the `/tmp/.webmin` directory in a file containing the `maillog-var`.

Also, which OS and version are you seeing this on?

**Comment by RK-BAKU** [comment]
> If you add a debug line to figure out what `$maillog` actually is, what do you get? You can do this by adding:
> 
> ```
> var_dump($maillog, 'maillog-var');
> ```
> 
> When the code runs, you can find the dump in the `/tmp/.webmin` directory in a file containing the `maillog-var`.
> 
> Also, which OS and version are you seeing this on?

It's an actual and correct mail.log log file, just as expected.

**Comment by iliajie** [comment]
After taking a close look, I now think we have already fixed this issue in this patch https://github.com/virtualmin/virtualmin-gpl/commit/aaa52557afe81ce160afc6f63c1fa008cf373642.

**Comment by RK-BAKU** [comment]
Yes, I've noticed that misspelled var name as well -  $lastpost;
Seems the patch is not the part of the latest update yet?

**Comment by iliajie** [comment]
> Seems the patch is not the part of the latest update yet?

No, not yet.

**Comment by RK-BAKU** [comment]
Do you have some approx update date for this?
Thank you for your prompt support!

**Comment by iliajie** [comment]
We don't provide ETA, though hopefully this weekend.

**Comment by jcameron** [comment]
Thanks Ilia for the fix!
