### ISSUE TITLE
`SASL Authentication Server` is too generic and needs renaming

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#815]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      26  package updates are available   |

### the issue

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/3c6cd751-f361-45f9-95c4-3c26ef42d799)

Consider the service named `SASL Authentication Server`
- There are many SASL servers out there, but you cannot tell which one this is.
- The other services have their `brand name` in the name (Dovecot, BIND, Postfix, Apache, MariaDB)

### proposed solution

rename `SASL Authentication Server` to `Cyrus SASL Authentication Server`

### additional

this will also help when people (i.e. me) are trying to learn the system/virtualmin and is in keeping with the other entries in the dashboard services panel.

**Comment by iliajie** [comment]
Hello,

I don't think that's right. We should call services the same way they are called by the vendor. For instance, the `saslauthd` service description is:

```
~# systemctl cat saslauthd | grep Description
Description=SASL Authentication Daemon
```

Therefore, I think the right way to call it would be **SASL Authentication Daemon** instead.

**Comment by shoulders** [comment]
The only thing is it does not say whose Daemon it is.maybe they should add their brand name in to their description 😀

**Comment by marclaporte** [comment]
> We should call services the same way they are called by the vendor.

Let's hope they give them good names. Stalwart has a JMAP server called **Stalwart JMAP Server** and an IMAP server called **Stalwart IMAP Server**. So far, so good.

- https://github.com/stalwartlabs/jmap-server
- https://github.com/stalwartlabs/imap-server

Cyrus has an IMAP server called **Cyrus IMAP**. But this server also does JMAP. There is no Cyrus JMAP. 
https://github.com/cyrusimap/cyrus-imapd

This is just an example that project names can be ambiguous and I think Virtualmin should keep the latitude of making it clearer for new adminstrators while always being transparent about the identity of the upstream project.

**Comment by iliajie** [comment]
I agree, Marc. However, in this particular case, calling it `Cyrus SASL Authentication Server` is likely to be more confusing than helpful.

**Comment by marclaporte** [comment]
Upstream calls it "Cyrus SASL"
https://github.com/cyrusimap/cyrus-sasl/

A new sysadmin will not know what SASL is but it is a generic term that can easily be looked up.

I don't know what is best but I deeply appreciate that @shoulders and @iliajie are collaborating to make Virtualmin even more awesome!

**Comment by jcameron** [comment]
I'd prefer not to use the word "Daemon" because it's kind of an old-school sysadmin term that may confuse users.

**Comment by iliajie** [comment]
> I'd prefer not to use the word "Daemon" because it's kind of an old-school sysadmin term that may confuse users.

Sure, alright.


> Upstream calls it "Cyrus SASL"

Yeah, that's right.

Alright, I wouldn't mind to call it **Cyrus SASL Authentication Server** then.

**Comment by jcameron** [comment]
> Alright, I wouldn't mind to call it Cyrus SASL Authentication Server then.

That works for me!

**Comment by iliajie** [comment]
Alright, that was fixed in the latest linked commits.

**Comment by shoulders** [comment]
@iliajie The german translation got english for stop start.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/1c676b99-e2ee-452e-8709-858824642282)

**Comment by iliajie** [comment]
Ah, you're right! Thanks for pointing this out!

That commit didn't go well - all fixed now!

**Comment by shoulders** [comment]
These things happen. 😸 , Your German is better than mine.

### This might be off topic, but much easier to post here.

In the commits above you have 2 fields:
- index_sastartdesc
- index_sastopdesc

I thought these descriptions would pop up on the dashboard when you hover over services, but they don't.
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/f23c969d-5cfd-4f3c-937c-423a2fb96ea9)

I then looked at `bootup and shutdown` and I cannot get these descriptions to appear there upon hover.

### Question

Have I missed where these tooltips should appear, or is there an issue with the rendering?

### lastly

```
index_sastop=Stop saslauthd daemon
index_sastart=Start saslauthd daemon
index_sarestart=Restart saslauthd daemon
```

The rest of the `server status`  use the term server or just the brand name but not the daemon name  for the stop, start, restart buttons.

**Comment by iliajie** [comment]
> The rest of the `server status` use the term server or just the brand name but not the daemon name for the stop, start, restart buttons.

I remember changing those. Did you check the very latest change?

**Comment by shoulders** [comment]
You are correct about the daemon things have been changed. I was looking at the wrong commit.

**Comment by iliajie** [comment]
> I know in the image above I am over the `stop` button, but if i do a screenshot over the tick icon, nothing would show.

The next Webmin release will show the actual status, like **Running** or **Stopped**, when hovering over the tick icon or stopped icon. However, it won't display the full status description.
