### ISSUE TITLE
Bug: Destination for spam emails - spam turns into junk

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#816]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      26  package updates are available   |

### the background

I am in the UK but I don't know if I have change any regional settings of the top of my head.

I cam across this issue whilst researching the SpamAssassin settings.

### the issue

1) if you go to: `Virtualmin --> Mail Options --> Spam and Virus Delivery` on a default virtual server you can see `~/mail/spam` is shown as my option
  ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/aaf82844-de7c-4a14-a05c-2fc33a34d286)

2) I now will change the `Destination for spam emails` to a random email address `chicken@meat.com`
   ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/77cd74aa-8625-48f2-b17f-9c3d7ab88fd4)

3) I now go back to  `Virtualmin --> Mail Options --> Spam and Virus Delivery`  and you can see that `~/mail/spam` is now `~/mail/junk`
   ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/33ec7d5a-ce5d-4936-8853-9ee6985a10ae)

The `spam` folder should not change into `Junk`

### proposed solution

Figure out why the folder names are being changed by Virtualmin and stop it.

### additional

I think the `spam` folder is more international as it does not need translating.

**Comment by jcameron** [comment]
You can adjust this default spam folder name at System Settings -> Virtualmin Configuration -> Spam filtering options -> Default delivery for spam

**Comment by shoulders** [comment]
> You can adjust this default spam folder name at System Settings -> Virtualmin Configuration -> Spam filtering options -> Default delivery for spam

Absolutely. The problem is i did not change this setting (spam --> junk) but when I came back as shown above it is now called junk, 

this is my current `Default delivery for spam` setting which has not been changed

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/e0a738e6-176e-40fc-8ce2-486964f9a692)

Where did `Junk` come from ?

**Comment by iliajie** [comment]
> I'd support changing that to `.Spam` then

That would be great! Though, could that break anything?

**Comment by jcameron** [comment]
This is only done once at initial install, right? If so, it's safe.

**Comment by iliajie** [comment]
> This is only done once at initial install, right? If so, it's safe.

Alright, I will take a look.

Though, original issue remains:

> There is a discrepancy. If the **Forward to email address** option is given and saved, then `Maildir/.spam` gets changed to `Maildir/.junk`. This doesn't seem right or consistent.
>

**Comment by jcameron** [comment]
> There is a discrepancy. If the Forward to email address option is given and saved, then Maildir/.spam gets changed to Maildir/.junk. This doesn't seem right or consistent.

I wonder if this domain was migrated from another system?

**Comment by shoulders** [comment]
> I wonder if this domain was migrated from another system?

These `Virtual Servers` have never been migrated. They were manually created on their Virtualmin last ~6 months (live and dev site).

If required I can re-test on my 4-6 week old fresh install of Virtualmin to see if it does the same thing. I have just used that to get Postfix Defaults.

**Comment by jcameron** [comment]
Ok I see the underlying bug now! We'll fix this in the next release ...

**Comment by marclaporte** [comment]
On a related note, there is an RFC to identify a folder as junk/spam even if it's called something else.

IMAP LIST Extension for Special-Use Mailboxes:
https://www.rfc-editor.org/rfc/rfc6154.html

**Comment by jcameron** [comment]
Oh interesting .. although I guess that depends on the IMAP server (ie. Dovecot) being configured to tag folders correctly.

**Comment by marclaporte** [comment]
RFC 6154 is supported by Dovecot, Cyrus and Stalwart:
- https://doc.dovecot.org/configuration_manual/namespace/#core_setting-namespace/mailbox/special_use
- https://www.cyrusimap.org/imap/rfc-support.html
- https://stalw.art/docs/development/rfcs/

@jcameron I propose that my team tries to contribute this. It will be a great learning experience. At the very least, we publish the docs, and if it's clean and low risk, we contribute a setting to the Virtualmin code base. How does this sound?

**Comment by jcameron** [comment]
Sure, I'd welcome a PR to add this!
