### ISSUE TITLE
Cannot delete emails with spam at the server level, on at virtual server level

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#818]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      26  package updates are available   |

### background

You can delete email identified as spam at many different levels

- **Webmin Global:**
  - `Webmin --> Servers --> SpamAssassin Mail Filter --> Procmail Spam Deilvery --> Action for messages classified as spam: Throw away`
-  **Virtualmin Defaults:** (included for reference)
   -` Virtualmin --> System Settings --> Virtualmin Configuration --> Configuration category: Spam filtering options --> Default delivery for viruses: Delete`
- **Virtual Server:**
  - `Virtualmin --> Mail Options --> Spam and Virus Delivery --> Destination for spam emails: Throw away`
  - `Virtualmin --> Mail Options --> SpamAssassin Configuration --> Procmail Spam Deilvery --> Action for messages classified as spam: Throw away`
- **Usermin:**
  - `Usermin --> Mail --> SpamAssassin Mail Filter --> option not present, might be permissions`

### The issue

You can only delete emails tagged with spam at the `Virtual Server` level

-  **Virtualmin Defaults:** (included for reference)
   -` Virtualmin --> System Settings --> Virtualmin Configuration --> Configuration category: Spam filtering options --> Default delivery for viruses: Delete`
- **Virtual Server:**
  - `Virtualmin --> Mail Options --> Spam and Virus Delivery --> Destination for virus emails: Throw away`

### proposed solution

Allow the deletion of emails at the server level.

`Webmin --> (Servers | System) --> Spam and Virus Delivery`

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/5a022667-779c-48c9-bc8d-3fdb5f9d6110)

### Additional 
If a email has a virus it should be deleted as soon as possible or the sysadmin decides he wants to delete it and the virtual server owners do not get a choice in the matter.

**Comment by jcameron** [comment]
Are you saying you're looking for a way to switch to deletion of spam and/or viruses for all domains at once?

You can do this with an API command like `virtualmin modify-spam --all-domains --virus-delete`

**Comment by shoulders** [comment]
> virtualmin modify-spam --all-domains --virus-delete

This command cycles through each of the virtual machines and sets the procmail for each of the virtual server to delete emails with virus.

What I am suggesting is that there is a server level promail similiar to
`Webmin --> Servers --> SpamAssassin Mail Filter --> Procmail Spam Deilvery --> Action for messages classified as spam: Throw away`

However, the end result is the same. This is about parity more than functionality.

**Comment by shoulders** [comment]
> Isn't there a warning on the page at Webmin --> Servers --> SpamAssassin Mail Filter --> Procmail Spam Deilvery about this being controlled by Virtualmin though?

no warning

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/3ac33dac-852e-4567-818b-1654a9ee0fa5)

**Comment by jcameron** [comment]
Can you post the contents of the `/etc/procmailrc` and `/etc/webmin/spam/config` files on your system?

**Comment by shoulders** [comment]
### /etc/procmailrc

```
LOGFILE=/var/log/procmail.log
TRAP=/etc/webmin/virtual-server/procmail-logger.pl
:0wi
VIRTUALMIN=|/etc/webmin/virtual-server/lookup-domain.pl $LOGNAME
EXITCODE=$?
:0
* ?/bin/test "$EXITCODE" = "73"
/dev/null
EXITCODE=0
:0
* ?/bin/test "$VIRTUALMIN" != ""
{
INCLUDERC=/etc/webmin/virtual-server/procmail/$VIRTUALMIN
}
ORGMAIL=$HOME/Maildir/
DEFAULT=$HOME/Maildir/
DROPPRIVS=yes
:0
$DEFAULT
:0
* ^X-Spam-Status: Yes
/dev/null
```

### /etc/webmin/spam/config

```
spamassassin=spamassassin
processes=spamd amavisd
amavisdconf=/etc/amavis/conf.d/20-debian_defaults
addto=0
warn_procmail=1
call_spam=1
procmail_cmd=*
local_cf=/etc/spamassassin/local.cf
mode=0
max_awl=200
restart_cmd=systemctl restart spamassassin
sa_learn=sa-learn
procmailrc=/etc/procmailrc
```

**Comment by jcameron** [comment]
Thanks - I see what causes this, and I'll fix it in the next release.

**Comment by shoulders** [comment]
Thanks, It is appreciated.

**Comment by shoulders** [comment]
@jcameron just read the commit, am I right in thinking this will hide the Procmail icon in webmin which will prevent people to configure mail spam to be deleted at the server level? This will also stop people altering their current configuration that they have set now.

A warning would be better or is this is what is going to happen?
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/d27eb9e1-8d3f-4365-8c7b-416b338f250c)


for instance I have set a global SpamAssAssin rule (in webmin) `SPF_FAIL = 10` and these emails are deleted at the server level as they are pointless. These will be deleted irrespective of what the client's SpamAssassin settings are.

**Comment by jcameron** [comment]
Yes, it will hide that icon. I think this is the only safe option, as allowing the admin to setup a global procmail rule for spam will interfere in a potentially confusing way with per-domain settings.

**Comment by shoulders** [comment]
You might want to make sure that the delivery normally is set when the icon is hidden as some users like me could of set emails to be thrown away at the global level, and after your update it would not be that easy to diagnose or change it back to deliver normally.

I am guessing deliver normally will cause procmail to ignore at global level.

**Comment by jcameron** [comment]
Yeah, I'll take a look at that
