### ISSUE TITLE
Domain default page is being shown for a domain with no virtual server

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#819]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### background

I have a mate whose site I am bringing onto my server. I have only changed the A records to point to my server so he can keep DNS at his registrar.

I have not setup a virtual server for him yet.

- www.grosvenor-it.co.uk
- grosvenor-it.co.uk

p.s. when you have seen this I will remove his site reference

### the issue

When I now go to his site I get the following message saying the site is setup correctly, but it is not, because it does not exist on my server

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/0a019157-bdfe-4254-90a3-b8b9e182b56c)

### question

Is this normal behaviour or is there a missing test to display another message saying the site is not setup on this server yet?

### Additional

If this is default behaviour I can live with it as it is a small issue.

**Comment by iliajie** [comment]
Yes, this is normal behavior. If you had the host default domain enabled in **System Settings ⇾ Virtualmin Configuration: SSL settings,** it would display that page instead, e.g.:

<img width="1112" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/25240f85-7cc9-4936-abcb-755cbb680d17">

This is the second most important reason, aside from a smooth login experience after Virtualmin installation, why I implemented this feature.

**Comment by shoulders** [comment]
appreciate the feedback, and it makes sense.
