### ISSUE TITLE
Allowed default login shell

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#828]
Hello Jamie!

I was running pre-release tests with all the latest checked-in code and found that if **Custom Shells** are set to **Virtualmin built-in defaults**, then after creating a new domain, **Server Owner Limits** gets **Allowed login type** set to **Email, FTP, and SSH**.

I believe the previously desirable value was **Email and FTP** only.

**Comment by iliajie** [comment]
Jamie, any update on this one? It looks important to me.

**Comment by jcameron** [comment]
That actually sounds like what we want to me though! It's pretty reasonable for server owners to get SSH access by default..

**Comment by iliajie** [comment]
So we want non-master administrator logins to be able to create SSH users by default, when logged in as a domain owner?

I thought we initially wanted only master administrators to unconditionally create users. SSH user creation wasn't previously allowed for domain owner logins?

**Comment by jcameron** [comment]
Hang on, that's a separate thing ... the setting on **Server Owner Limits** controls the shell for the domain owner, which should be separate from the shell he can give to mailboxes.

**Comment by iliajie** [comment]
> Hang on, that's a separate thing ... the setting on **Server Owner Limits** controls the shell for the domain owner, which should be separate from the shell he can give to mailboxes.

Well, you made those last patches, but I just wanted to point out that currently, by default, domain owners can create SSH accounts. As we discussed last time, we want only the master admin to unconditionally create SSH accounts, while domain owners, by default, wouldn't have that ability. Is that correct?

**Comment by jcameron** [comment]
Now I think about it, maybe this is fine. Because it's not a privilege escalation in any way if a domain owner who has SSH access can himself give SSH access to other mailboxes..

**Comment by iliajie** [comment]
Oh, God! This is so tricky! It indeed works as you say! If I take SSH access away from the domain owner, they cannot create SSH users either when logged in as domain owner. If limits are manually imposed, it also works! Wow!

Well done! The issue is resolved!

Thanks!
