### ISSUE TITLE
Backup: Not detecting mysqldump errors

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#83]
Virtualmin Backup does not report errors encountered while dumping a database.

After updating from Ubuntu 14.04 to 16.04 the the sql settings have changed and no longer allow the dumping of a rather large table in a 26GB database.

Error encountered after trying to dump the database via mysql workbench:
`mysqldump: Error 2020: Got packet bigger than 'max_allowed_packet' bytes when dumping table `***` at row: 59810
`

Unfortunately virtualmin did not report this, but instead wrote in the backup report

>Dumping MySQL database *** ..
>    .. done

Moreover at the end of the report it reported

> ** servers backup successfully, 0 had errors.

Only the fact that the backup size dropped significant made me aware of the problem

**Comment by PitWenkin** [comment]
As far as I can tell it should have been reported by https://github.com/virtualmin/virtualmin-gpl/blob/5d377ca7dbe94cac41e02756ae9f8ff65c761e2e/feature-mysql.pl#L1059 or https://github.com/virtualmin/virtualmin-gpl/blob/5d377ca7dbe94cac41e02756ae9f8ff65c761e2e/feature-mysql.pl#L1063


But I don't get where `foreign_call`is actually located to further debug this.

Neither do I know which occurence of `max_allowed_packet`I have to increase to get the dump working again. [Does virtualmin actually consider the settings in my.cnf](https://serverfault.com/questions/102564/error-2020-got-packet-bigger-than-max-allowed-packet-bytes-when-dumping-table/132135#132135)

If someone could point me in the right direction …

**Comment by jcameron** [comment]
Looks like the validation of the backup for errors has a bug - I'll fix this in the next release.
