### ISSUE TITLE
Restoring domain with shared SSL

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#830]
Hello Jamie!

When trying to restore a domain with a shared SSL certificate, it fails with the following error, e.g.:

```
Checking contents of the backup ..
.. found 1 virtual servers
Starting restore of 1 domains from local file /tmp/.webmin/rocky9-pro-2.virtualmin.dev.tar.gz ..
Extracting backup archive file ..
.. done
Re-creating virtual server rocky9-pro-2.virtualmin.dev ..
.. the virtual server this domain's SSL certificate was shared with does not exist!
.. failed! See the progress output above for the reason why.
```

My question is, why do we do this instead of breaking the link and using a shared SSL certificate for the restored domain directly?

**Comment by jcameron** [comment]
This happens because we don't include the SSL cert in the backup in this case, because it's under the other domain's directory. I suppose that could be fixed in theory though .... does this come up often?

**Comment by iliajie** [comment]
> This happens because we don't include the SSL cert in the backup in this case

Ah, I thought about that too.

> I suppose that could be fixed in theory though .... does this come up often?

I don't think it comes up often because sharing SSL certificates, even when the owner is different, isn't the default. But I still think it should be done right. I don't see any reasonable limitations not to having it work properly.

**Comment by jcameron** [comment]
We'd have to include the SSL cert and key in the backup even when it's shared, and then break the connection on restore. It's kind of risky though, as it the user restores in the wrong order the cert could be broken even when the user doesn't really want it to be..

**Comment by iliajie** [comment]
Yeah, I understand that. Perhaps we could add a button in the UI to enable SSL certificate sharing for a domain when possible? This way, even if sharing is broken in those rare cases, a user would easily be able to re-create this link.

**Comment by jcameron** [comment]
I'll think about it ... may be we could do this is warnings are skipped

**Comment by iliajie** [comment]
> I'll think about it ... may be we could do this is warnings are skipped

Oh, that's a good idea!

But having a button shown in the UI when enabling SSL sharing is possible would be great.

**Comment by jcameron** [comment]
There's flag to the `modify-ssl` CLI command that you can use for this ...

**Comment by iliajie** [comment]
> There's flag to the `modify-ssl` CLI command that you can use for this ...

Thanks! Though, I knew about it, but I still think using the CLI isn't very user-friendly for normal users. Since this button would rarely be shown, it would be useful in certain cases.

**Comment by jcameron** [comment]
I think that for rare operations, we don't want to clutter up the UI with extra buttons. Best to make things as automatic as possible, and for obscure cases like this we allow it via the CLI.

**Comment by iliajie** [comment]
Well, alright! Agreed!

Though, what about the original issue? Should we keep it as is for now?

**Comment by jcameron** [comment]
I'll work on making this a skippable warning

**Comment by iliajie** [comment]
Great, thanks!

**Comment by jcameron** [comment]
So I checked and this is indeed a skippable warning already! When restoring from the CLI, you can use the `--skip-warnings` flag to ignore the error about the domain the SSL cert was shared with no longer existing.
