### ISSUE TITLE
SSL certificate request isn't resilient when a service fails

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#835]
Hello Jamie!

I have spun up a new testing instance and then have intentionally broke Dovecot, e.g.:

```
local_name contabo-dom3.virtualmin.dev {
  ssl_cert = </etc/XXXXssl/virtualmin/1718369675150598/ssl.combined
  ssl_key = </etc/ssl/virtualmin/1718369675150598/ssl.key
}
```

Then I tried to create a new domain and it failed with the following absolutely obscure error message:

<img width="1092" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/88b1458b-44aa-4828-979e-5fd9284346c2">

This shouldn't fail like this! If there is an error, we should skip adding the certificate for this particular service only, but everything else should still work. If a service fails, we should display proper error message, so it would be easy to find and fix the bug.

**Comment by iliajie** [comment]
Actually, I also see the same issue when all services are running well. Something seems to have broken during the rework!

Please have a look!

**Comment by iliajie** [comment]
Sorry for the false alarm! I took a closer look and it appears that the error initially occurred due to a lack of entropy. It happened so sporadically that it confused me at first place.

This is the simplest instance in Contabo. I remember our users reported various issues when using Contabo, so I decided to give it a try myself.

Nevertheless, could we return a more precise error message, as those lines of pluses not really informative? Also, why try creating the SSL web site if self-signed SSL certificate creation already failed?

**Comment by jcameron** [comment]
We could certainly skip the attempt to create an Nginx SSL website if there is no valid key. Normally we assume that at least a self-signed cert will always succeed, but I never considered the lack of entropy case..

**Comment by iliajie** [comment]
Though it's a minor issue, I still think it's better to address it if it doesn't require too much code change ..

**Comment by jcameron** [comment]
Ok I've checked in fixes that should handle this more gracefully.

**Comment by iliajie** [comment]
Great! Thanks!
