### ISSUE TITLE
Expose issues with file ownership / permissions / attributes (Ideally as part of "Scheduled Validation")

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#836]
![2024-06-22_132523](https://github.com/virtualmin/virtualmin-gpl/assets/1004261/57f39de9-52b7-40fe-8523-448dd793c50c)

It would be nice to know what it solved. It would be even nicer to have this as part of the scheduled validation. So we could quickly be alerted about issues (Usually, the sooner we know, the easier it is to address the root cause)
![2024-06-22_132916](https://github.com/virtualmin/virtualmin-gpl/assets/1004261/49e7a0cb-21ef-4ba3-89b8-921effb51815)

Many times, we have wasted time because someone worked as root and forgot to chown a file, or a script running as root created some files, some files were migrated from another site, and we forgot to change the owner, etc.

I realize it could be super slow to do this. So maybe it should be a check box in scheduled validation "Also validate file permissions".

**Comment by iliajie** [comment]
Hey Marc!

This feature makes sense. However, it would imply that we won't be able to use `chown` as we do now for this, since it only returns the number of files affected and not the list of files that was affected.

I don't recall at the moment if we also apply `chmod`, but if not, it could also be optionally added and done based on `umask` settings.

We will need  to wait for Jamie's comment on this.

**Comment by jcameron** [comment]
Checking permissions on all the files that Fix Permissions fixes could be really slow, so I don't think we could do this as part of scheduled validation.

**Comment by marclaporte** [comment]
> could be really slow, so I don't think we could do this as part of scheduled validation

I understand.


> However, it would imply that we won't be able to use `chown` as we do now for this, since it only returns the number of files affected and not the list of files that was affected.

Even just the number of files affected would be nice because it's a hint of the presence or absence of an issue.

I have an idea: chown [-c|--changes] "displays information about files that are actually changed. For example: changed ownership of 'dir/dir1/file1' from hope:neil to hope:hope"

Source: https://www.computerhope.com/unix/uchown.htm

**Comment by iliajie** [comment]
We use Perl's `chown` for this purpose. We either need to shell out to use `chown` with the `--changes` flag or by stating files like:

```
my ($orig_uid, $orig_gid) = (stat $file)[4, 5];
if ($orig_uid != $uid || $orig_gid != $gid) {
    if (chown($uid, $gid, $file)) {
        push @changed_files, $file;
        }
    }
```

**Comment by jcameron** [comment]
We could certainly show the list of files that were changed on the Fix Permissions page..

**Comment by iliajie** [comment]
Yeah, I know. But I think we should make a new Virtualmin 7.20.0 release and keep this particular feature for later!

We also need to wrap up Webmin and Usermin next week, as after that I need to finish the WordPress Workbench and start reworking Cloudmin. The time has come!

**Comment by marclaporte** [comment]
> Yeah, I know. But I think we should make a new Virtualmin 7.20.0 release and keep this particular feature for later!

Sure, let's keep as a nice-to-have one day. I look forward to 7.20.0!

**Comment by marclaporte** [comment]
7.20.x is doing well now :-)
- https://forum.virtualmin.com/t/virtualmin-virtual-server-module-version-7-20-2/128150/
- https://forum.virtualmin.com/t/webmin-version-2-202-released/128615
- https://forum.virtualmin.com/t/usermin-version-2-102-released/128616

**Comment by iliajie** [comment]
Can this ticket be closed?

**Comment by marclaporte** [comment]
No yet. We are still missing:

> We could certainly show the list of files that were changed on the Fix Permissions page..

**Comment by iliajie** [comment]
> No yet. We are still missing:
> 
> > We could certainly show the list of files that were changed on the Fix Permissions page..

Ah, that's right!

**Comment by iliajie** [comment]
> We could certainly show the list of files that were changed on the Fix Permissions page..
> > No yet. We are still missing:
> > > We could certainly show the list of files that were changed on the Fix Permissions page..
> 
> Ah, that's right!

Jamie, what do you think about implementing this feature? Any objections or suggestions? It doesn't seem too hard to implement.

**Comment by jcameron** [comment]
> Jamie, what do you think about implementing this feature? Any objections or suggestions? It doesn't seem too hard to implement.

Do you mean showing it after the fact, or asking for confirmation first?

**Comment by iliajie** [comment]
I mean, if we change file permissions as part of the fix, we show the file name which permissions were changed and what permissions it had before the fix.

**Comment by iliajie** [comment]
(ownership, not permissions to be precise)

**Comment by jcameron** [comment]
Sure that seems like a nice feature, as long as we limit the list to files that were actually changed.

**Comment by iliajie** [comment]
We could put the output into `details` HTML element.

**Comment by jcameron** [comment]
Sure, but what I mean is that if the site has 1000 files and only 5 needed to have their permissions fixed, we should only output the 5 that were fixed.

**Comment by iliajie** [comment]
Oh, sure thing! I’ll send you a PR tomorrow…

**Comment by marclaporte** [comment]
Super! We'll want to add this to our monitoring system.

I explain: If some file ownerships are incorrect, it usually means something was done in a suboptimal way (ex.: a script was ran as root when it should have been done with a non-root user). So I want it logged in the monitoring system (in our case Zabbix) so we know to look for the root cause. We can make a Zabbix template for this.

Thanks!

**Comment by iliajie** [comment]
> so we know to look for the root cause.

Marc, the currently know root cause appears to be the Virtualmin Tiki Manager, which messes up permissions because it still relies on the outdated and insecure practice of running installations and upgrades as root. I’ve brought this to your team’s attention numerous times, but I haven’t yet been able to fully address it myself..

> Oh, sure thing! I’ll send you a PR tomorrow…

Jamie, sorry I couldn’t get to it today—I got caught up in a major rework to add “Micro” and “Nano” installation types to the Virtualmin installer...

**Comment by jcameron** [comment]
Ok no rush!

**Comment by iliajie** [comment]
Implemented here https://github.com/virtualmin/virtualmin-gpl/pull/990.
