### ISSUE TITLE
Reset DNS - add a warning

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#839]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      92  package updates are available   |

## background

- when I reset the DNS on virtual server it just immediately resets the DNS.
- when i clicked on the reset dns button on a sub-server whoes DNS was being controlled by the parent,  virtualmin warned me it was going to reset the DNS. The changes showed it was going to reset the parent DNS (and I assume the sub-servers which was part of it.

## the issue

no warning message for normal virtual servers about what was going to be changed.

## solution

add the prompt indicating what is going to be changed for normal virtual servers rather than immediately carrying out the command.

## related

#838 Reset DNS button should not be available on sub-servers when parent controls the DNS

**Comment by shoulders** [comment]
On the sub server when I clicked the button it showed the records that were going to be removed, but to be honest I did not find that useful except that it showed me it was going to reset the parents zone so in this case it was.

Going forwards this 'bug' will not be an issue, so maybe a warning message will be fine. 

Example message: 

The DNS zone 
`can.example.com` is going to be reset to default values as set by the relevant server template.

**Comment by jcameron** [comment]
Ok, this will be fixed in the next next Virtualmin release.

**Comment by shoulders** [comment]
FYI: using chrome on my dev virtualmin server,  when i clicked the DNS reset button I got the following warning which is great but as you can see I am still on 7.10.0.

Do you only get this warning if a change has been noticed by Virtualmin?

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/3905bacc-8ef4-44b4-b7a3-2662d47658ff)

|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      94  package updates are available   |

**Comment by iliajie** [comment]
Related https://github.com/virtualmin/virtualmin-gpl/issues/774#issuecomment-2155656467.

**Comment by jcameron** [comment]
Yeah the warning is only shown if some records are expected to be removed. Otherwise it proceeds without any warning.
