### ISSUE TITLE
Quotas and LDAP users limited by maximum search results

### ISSUE THREAD

**Issue by SpiffyStores** [virtualmin/virtualmin-gpl#84]
It appears that with a large number of LDAP users, if the LDAP server maximum search limit is exceeded, then quota results for individual users are not available and show up as Unlimited.

Also, the disk quota listings show unresolved uid values for users beyond the search limit.

This may be some sort of optimization, but it seems strange that retrieving the quota settings for an individual user are dependent on retrieving the entire list of user in the LDAP database, even though this list may be truncated by the maximum search limit of the server.

I notice that "getent passwd" suffers the truncation problem as well.

**Comment by jcameron** [comment]
Thanks, I didn't consider this case where the full user list would be unavailable. The next release will handle this properly in the quotas module.
