### ISSUE TITLE
Email Client settings - not showing `use SSL for POP3`

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#842]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      94  package updates are available   |

## background

Just poking around while having a coffee 😄 

`Virtualmin --> Edit Users --> Email Client Settings`

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/c82416ab-1546-4806-b1f2-e97d23753a35)

I am not sure if these are picked up automatically from server settings.

## the issue

The section for POP3 does not have a field saying `Use SSL for POP3?`

In my dovecot configuration I do not allow non-SSL connections

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/375dd5e9-df41-4b54-851e-e6a589cf46e5)

## proposed solution

Add the extra information  `Use SSL for POP3?` in to the email client settings.

`POP3 password encryption type` might need adding, but I don't know if it is still plaintext.

## Question

- if these settings are created from the server settings rather that statics, what setting controls `Use SSL for SMTP?` as I want to check this is working.

## related

my outlook POP3 settings

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/25d322f1-f2a6-4927-b578-491ceb1c8ca2)

**Comment by jcameron** [comment]
Yes, that does look like a bug. How do you have SSL for POP3 configured in Dovecot though?

**Comment by shoulders** [comment]
in SSL configuration I have

![image](https://github.com/webmin/webmin/assets/319997/1700a446-598d-460f-90b5-fd8bc7bc91cb)

so temporarily I put this to **No** so i can test if the setting `Accept SSL connections?` makes any difference.

`only allow SSL` when set to:
- **Only accept SSL** - causes my outlook to come up with an error
  ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/78efb529-691e-491c-9a94-465843d2eac4)
- **Yes** - Works fine when the setting

### my outlook client settings

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/8896edb0-2b22-4cfc-8e64-dc7376140368)

**Comment by jcameron** [comment]
Thanks! I'll update that page to make this clearer in future..
