### ISSUE TITLE
Unable to install libapache2-mod-php due to virtalmin restriction

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#854]
Due to the existence of `/etc/apt/preferences.d/ubuntu-virtualmin-restricted-package`

```
Package: libapache2-mod-php*
Pin: release *
Pin-Priority: -1
```

I was not able to install the `libapache2-mod-php` package.
I got the error `libapache2-mod-php8.1+8.1.2-1ubuntu2 [Not candidate version]`

Why does this file exist, and what will break now that I have commented the content of the file, after which I was able to install the package … ?

**Comment by iliajie** [comment]
> I was not able to install the `libapache2-mod-php` package.

You must never install `mod_php`. This limitation isn't by accident! You should use PHP-FPM, which is fully supported. We did this to protect users from breaking their systems.



> Why does this file exist, and what will break

https://www.virtualmin.com/docs/server-components/php-execution-modes/#precautions-regarding-mod_php

**Comment by PitWenkin** [comment]
Thanks, I will have to change stuff then on my end.
