### ISSUE TITLE
Virtualmin cannot be updated

### ISSUE THREAD

**Issue by v0UwUK6CmCrjVB1PAtRb** [virtualmin/virtualmin-gpl#855]
Webmin version: 2.111
Virtualmin version: 7.**10**.0
Operating system: CentOS Linux 7.9.2009

I'd like to update to 7.**20**.1 however no package updates are available: https://pastebin.com/raw/f2tzGzLB

Here is my /etc/yum.repos.d/: https://pastebin.com/raw/HrZ7V20Q
Here is /etc/yum.repos.d/virtualmin.repo: https://pastebin.com/raw/uutHiTWM

Virtualmin was installed using the following commands:

```
wget http://software.virtualmin.com/gpl/scripts/install.sh
chmod +x install.sh
./install.sh
```

Note: I am aware CentOS 7 is EOL, I do plan on updating to Debian 12 in the coming few days, however I need to first run some tests with more up-to-date PHP versions, which I currently cannot do as per https://github.com/virtualmin/virtualmin-gpl/issues/853

Any thoughts on how I can update to Virtualmin 7.20.1 would be very much appreciated.

**Comment by iliajie** [comment]
Hello,

We haven't yet released Virtualmin 7.20.1 to the users. It may take at least a couple of days.

**Comment by PitWenkin** [comment]
The `apt` packages have not been updated to include `7.20.0`, even though the release was 2 weeks ago …

**Comment by iliajie** [comment]
> I guess I just need to be patient for 7.20.x, I was just confused since I figured because 7.20.x shows at https://github.com/virtualmin/virtualmin-gpl/releases it would be the in the "public" or "stable" tree or whatever Virtualmin

Yes, please wait a bit.

**Comment by chris001** [comment]
> Yes, please wait a bit.

Is there any reason why not to have a script detect the new github release tag and automatically build the rpms and debs?  Same as many other projects have this.

**Comment by iliajie** [comment]
Yes, the primary reason is simply time.

**Comment by PitWenkin** [comment]
`apt` packages are released … `yum` probably too?

**Comment by iliajie** [comment]
> `apt` packages are released … `yum` probably too?

I'm sorry, what are you asking?

**Comment by PitWenkin** [comment]
> > `apt` packages are released … `yum` probably too?
> 
> I'm sorry, what are you asking?

Just stating that I was able to update via apt packages to the most recent version, therefor @Bt6K should be able to do the same via yum.
