### ISSUE TITLE
Suggested DNS records duplicates ipv4 address in SPF record

### ISSUE THREAD

**Issue by apidevlab** [virtualmin/virtualmin-gpl#856]
Webmin version: 2.111
Virtualmin version: 7.10.0

Virtualmin GPL using the latest build shows the IPv4 address of the shared IP duplicated in the SPF record.

`domain.tld.   TXT "v=spf1 a mx a:domain.tld ip4:xx.xx.xx.xx ip4:xx.xx.xx.xx ip6:xxxx:xxxx:xxxx:xxxx::x ?all"`

**Comment by jcameron** [comment]
Thanks for pointing this out - it's pretty harmless, but we'll fix it in the next release.
