### ISSUE TITLE
Virtualmin overwrites "sn" LDAP attribute with "real name" field when given name and surname fields are enabled

### ISSUE THREAD

**Issue by neosonic2** [virtualmin/virtualmin-gpl#860]
I noticed Virtualmin doesn't have separate first name and last name fields available when creating new users in a virtual server (i.e. new email accounts), instead combining both into a single **real name** field. In an attempt to work around this limitation in my LDAP-based setup on Ubuntu, I set the **Show fields for given name and surname** option to **Yes** within the LDAP Users and Groups module configuration options.

This adds a given name and surname field to the user editor form in the module, and correctly saves my changes to the **givenName** and **sn** LDAP attributes, respectively. However, if I then go back into Virtualmin and edit the same user from the Edit Users page, the value of the **sn** attribute that I just populated with the surname from within the LDAP Users and Groups module gets overwritten with the value of the  **real name** field from the Edit Users page.

Is there a way to prevent this from happening? Since the value of the **real name** field also gets stored in the **cn** LDAP attribute, perhaps Virtualmin doesn't need to duplicate this in the **sn** field?

By the way - I have to say I am really enjoying Virtualmin's LDAP integration now that I've got an LDAP server up and running and have worked out all the other issues. I did notice there are a few parts of the [integration documentation](https://www.virtualmin.com/docs/advanced-tutorials/how-to-configure-ldap/#:~:text=Creating%20LDAP%20Users%20with%20Virtualmin,-Once%20the%20LDAP&text=This%20can%20be%20done%20as,re%2Dcheck%20the%20Virtualmin%20configuration.) that are out of date or do not apply to modern versions of Ubuntu, and would be happy to write updates to the docs if desired.

**Comment by jcameron** [comment]
Ok I think I can see why this is happening ... I'll see what we can do to fix it.

**Comment by neosonic2** [comment]
Thanks Jamie, and I appreciate your responsiveness to Virtualmin customers and your commitment to fix issues and make improvements to what has become an outstanding product. If you need me to do any testing of fixes since I have an active LDAP setup, please let me know.

**Comment by jcameron** [comment]
Thanks for the offer! I may have some fixes for you tomorrow ...

So we can certainly preserve the first name and surname when editing a user in Virtualmin, but I am guessing that alone isn't enough. You'd also need a way to edit the name parts separately in the Virtualmin UI, right?

**Comment by neosonic2** [comment]
I think that would be best, yes. At the very least it would prevent someone from needing to go into the LDAP Users and Groups module to edit the first name and surname of a user. It’d be nice to keep everything in the Virtualmin UI since said UI already has other fields for user editing like password and real name.

**Comment by jcameron** [comment]
Ok I'll update this ticket with progress ...

**Comment by jcameron** [comment]
OK this has been implemented for inclusion in the next Virtualmin release ..
