### ISSUE TITLE
`Re-check and refresh configuration` button - Add a hide alert

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#863]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.1       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### the background

when you update virtualmin you get the following alert message and when a check finds no errors the alert is hidden.

![image](https://github.com/user-attachments/assets/04f69472-c8d2-4052-879c-3ab925daf476)

### the issue

If errors are found when checking the alert cannot be hidden.

This is an issue on my dev site where I mess about with settings and it is never going to be correct so I can run this check as often as I like but unless I fix the errors I cannot get rid of it.

### proposed solution

Add a `Hide Alert` button like alot of the other warnings have.

I am not saying hide it permanently, and if this warning is naturally triggered (ie from an update of virtualmin etc...) it should re-appear as normal.

**Comment by iliajie** [comment]
Hello,

We don't want this because Virtualmin expects to have the configuration checked. The right solution in this scenario is to address the root cause of the problem.

Thanks for the heads up anyway!
