### ISSUE TITLE
Add missing services to `Server Status`

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#870]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### background

![image](https://github.com/user-attachments/assets/866837c5-6a71-4bef-9aee-e69c71189988)

### the issue

Some of the vital services of Virtualmin are missing from the `server Status` widget

- Fail2ban
- FirewallD
- Postgrey Greylisting Server
- Usermin Webserver
- Webmin Webserver
- ProFTPD

## related issues

- https://github.com/virtualmin/virtualmin-gpl/issues/867
- https://github.com/virtualmin/virtualmin-gpl/issues/868
- https://github.com/webmin/webmin/issues/2236

**Comment by jcameron** [comment]
Nice suggestions, although it wouldn't make much sense to add Webmin because if it was down we wouldn't be able to see the console!

**Comment by shoulders** [comment]
> Nice suggestions, although it wouldn't make much sense to add Webmin because if it was down we wouldn't be able to see the console!

Maybe it should not be on the default console configuration for obvious reasons 😄 , well spotted.

however is a user adds it manually for the `local` `webmin`it should still be shown but without the stop/start/restart buttons for the following reasons

- it will send user bonkers wondering why it is not being shown
- it is already in the monitors list
- keeps the display logic, logical

![image](https://github.com/user-attachments/assets/37ffc25d-92b6-4278-aaed-76d1f8348e8f)

**Comment by jcameron** [comment]
Ok the next release of Virtualmin will include usermin and postgrey in that list, and proftpd is already supported. I don't think I will include Fail2ban and Firewalld though, as they are not core Virtualmin components..

**Comment by iliajie** [comment]
> I don't think I will include Fail2ban and Firewalld though, as they are not core Virtualmin components.

What is the definition of a core component of Virtualmin? I mean, we install and configure Fail2Ban and FirewallD with the `virtualmin-install.sh` script. Perhaps it's worth considering those?

**Comment by shoulders** [comment]
> as they are not core Virtualmin components

I would say they are, you should always have a firewall and brute force protections running and:

- `firewalld` is installed and enabled by virtualmin
- `fail2ban` is installed and enabled by virtualmin

Also the forum it is almost a given these are enabled and running.

**Comment by chris001** [comment]
It'd be nice to see when `firewalld` or `fail2ban` unexpectedly entered into `stopped` state when you expect them to be up and running.

**Comment by iliajie** [comment]
> It'd be nice to see when `firewalld` or `fail2ban` unexpectedly entered into `stopped` state when you expect them to be up and running.

Have you ever seen this happen? If so, which service in particular and on which OS?

**Comment by chris001** [comment]
> Have you ever seen this happen? If so, which service in particular and on which OS?

If I remember correctly, I've edited `fail2ban` jail and config files, restarted it, it failed, and stayed in `stopped` state.  Due to syntax errors in the config files.  Only Debian, RHEL, and Ubuntu GNU/Linux.  

Same with FirewallD.  A syntax error, an invalid rule, a missing dependency, and a zone conflict, all can make it fail to start or restart.

Indicators (also called "idiot lights") would make it close to impossible to miss when these services are unintentionally down.  Because these are security services and are critical for user data protection against the easiest type of attacks, brute force attacks.

```
root@abc:~# service fail2ban status
● fail2ban.service - Fail2Ban Service
     Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-08-08 19:12:13 EDT; 17min ago
       Docs: man:fail2ban(1)
   Main PID: 943 (fail2ban-server)
      Tasks: 7 (limit: 4617)
     Memory: 177.1M (peak: 181.0M)
        CPU: 4.648s
     CGroup: /system.slice/fail2ban.service
             └─943 /usr/bin/python3 /usr/bin/fail2ban-server -xf start

Aug 08 19:12:13 abc.domain.tld systemd[1]: Started fail2ban.service - Fail2Ban Service.
Aug 08 19:12:13 abc.domain.tld fail2ban-server[943]: 2024-08-08 19:12:13,813 fail2ban.configreader   [943]: WARNING 'allowipv6' not defined in 'Definition'. Using default one>
Aug 08 19:12:15 abc.domain.tld fail2ban-server[943]: Server ready
root@abc:~# 
```

```
root@abc:~# service firewalld status
○ firewalld.service
     Loaded: masked (Reason: Unit firewalld.service is masked.)
     Active: inactive (dead)
root@abc:~# 
```

**Comment by jcameron** [comment]
I've added a support for monitoring the status of firewalld using the System and Server Status module, and fail2ban is already supported there.

**Comment by shoulders** [comment]
@jcameron thanks for the fix
