### ISSUE TITLE
Remove Legacy migrate backup file types

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#872]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### background

You can import backups from other platforms using the following

`Virtualmin --> Add Servers --> Migrate Virtual Server --> Backup file type`

![image](https://github.com/user-attachments/assets/23120760-a46a-4932-bc8c-5938d4f6f66c)

### the issue

the following types of backup file are probably that old they should be `removed` because not one is using them any more:

- `Ensim` - I don't think this is developed anymore, i cant find it's home page
- `Plesk 7` - Is anyone still using this version, Plesk is now version 18
- `Plesk 8` - Is anyone still using this version, Plesk is now version 18
- `LXadmin (beta)` - this was renamed to kloxo and that has not been delvoped since 2020

### additional
- should `Plesk 9+ backup` be renamed `Plesk` so it has parity with `cPanel`

### links
- https://en.wikipedia.org/wiki/Kloxo
   - Free and open-source software portal Kloxo (formerly known as Lxadmin)
   - https://github.com/lxcenter/kloxo - last change 5 years ago

**Comment by jcameron** [comment]
I get that those are obsolete, but on the other hand we don't know what old systems users might still have out there that they want to migrate from. And it's very low overhead for Virtualmin to continue to maintain those options..

**Comment by shoulders** [comment]
@jcameron you are right, people are still using old versions of Plesk, how old I cannot say.

I would remove `LXadmin (beta)` and `Ensim`. These probably have not been used for years. 

If the Plesk imports become unmanageable from your end it will be at that time they should be removed 😄 , but I suspect they are very old.

**Comment by jcameron** [comment]
There's not much maintenance overhead in keeping support for those old migration types..
