### ISSUE TITLE
backup - add webmin backup

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#873]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

I think it would be a good idea of including a `webmin` full backup in a `virtualmin` backup

**Comment by marclaporte** [comment]
The main Virtualmin use case is shared hosting. And Virtualmin users don't have access to data outside their Virtualmin Virtual Server.

In theory, a Virtualmin backup should have everything necessary to restore to another server. Do you see something missing?

Can you describe a bit more your use case?

Thanks!

**Comment by shoulders** [comment]
### background
- Webmin and Virtualmin are different products, but Virtualmin depends on Webmin and together they provide a hosting platform.
- cPanel/WHM are a complete package, cPanel is just the user arm of the platform but it is an integral part of the platform.
- Most people referrer to cPanel as the whole platform and never refer to WHM as a separate piece of software
- Webmin can be a separate product, WHM cannot be separated from cPanel.

### So
- A lot of people when using Virtualmin's backup assume that this is backing up the server settings as-well, i did at first.
- Virtualmin should be considered the hosting software and it is incidental that it is on Webmin.
- Add Parity with cpanel/WHM as this give the option backup `system files`, as shown below
   ![image](https://github.com/user-attachments/assets/3d4e9326-fb0e-4716-a15b-d94ead23b732)

### Question

> The main Virtualmin use case is shared hosting. 

- But there must be an admin who installed Webmin/Virtualmin
- This additional feature is not for the end user, they never see
     ![image](https://github.com/user-attachments/assets/9df3fc8a-7ca8-4366-b7e3-148972186552)

### Additional

- I do struggle with how this Virtualmin backup page is. there should be one for `admins` and another for `End Users` but to do a true backup you then have to log into Webmin and back the Configs up there.
- In cPanel I just backup, I do not need to make any selections. 
- It has been a while since I logged into client account and did a backup 😄

**Comment by iliajie** [comment]
I don't believe that a virtual server related backups should deal with Webmin config files in any way. 

This work should be done by **Webmin ⇾ Backup Configuration Files** module.

**Comment by shoulders** [comment]
I thought I would just post this as probably relevant to the Virtualmin backup discussion. 

We probably should have some sort of consolidated backup page, where we show state of Filesystem Backups, Backup Configuration Files, and Virtualmin Backups (which are all different things, and useful in different disaster recovery scenarios, and may or may not be useful for any given Virtualmin deployment…if you’re a hosting provider with a standard OS image that goes on all systems unchanged, you don’t need the first two, you’re going to just restore Virtualmin backups whenever you need to, everything else is standard across systems). But, a lot of people don’t understand what Virtualmin is backing up, so maybe putting them all in one page would be useful to making the distinction clear.

> **Joe**
> We probably should have some sort of consolidated backup page, where we show state of Filesystem Backups, Backup Configuration Files, and Virtualmin Backups (which are all different things, and useful in different disaster recovery scenarios, and may or may not be useful for any given Virtualmin deployment…if you’re a hosting provider with a standard OS image that goes on all systems unchanged, you don’t need the first two, you’re going to just restore Virtualmin backups whenever you need to, everything else is standard across systems). But, a lot of people don’t understand what Virtualmin is backing up, so maybe putting them all in one page would be useful to making the distinction clear.

**Comment by iliajie** [comment]
> But, a lot of people don’t understand what Virtualmin is backing up

What is this assumption based on? I thought we're pretty clear on what's being backed up and where ..

**Comment by shoulders** [comment]
I am absolutely clear 

I just included the comment from Joe to show some of his thoughts on virtualmin backups in general and it was within the context of this issue. I appreciate this issue is closed.

It was not to reopen this particular issue.

I was going to attach it earlier but it was in a random window.

It was just a FYI moment. 😀, nothing more.

I think in that thread someone assumed all server settings were being backed up by the virtualmin backup procedure

**Comment by iliajie** [comment]
Having a consolidated page for backups overview should be a separate issue (ticket).

The original issue's title was about including a Webmin full backup in a Virtualmin backup. I don't believe it's something we should do, as I'm not even keen on having global Virtualmin configuration added to the domain backups.
