### ISSUE TITLE
backup - change default name

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#874]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### the background

When you generate a full webmin backup and download it via a link,  it generates a backup called `virtualm-backup.gz`

### the issue

This name is very non-descriptive and can cause issues if you have more than one virtualmin system

### proposed solution

I would like some thing like this

`vietualmin`+ `hostname` + `date`

Example: `virtualmin-example-server-com-2024-11-31-1315`

These will always be unique and does not need to be renamed by the user.

**Comment by iliajie** [comment]
> When you generate a full webmin backup and download it via a link, it generates a backup called `virtualm-backup.gz`

Ca you point out which page you're talking about exactly?

**Comment by shoulders** [comment]
`Virtualmin --> Backup and Restore --> Backup Virtual Servers`

![image](https://github.com/user-attachments/assets/78abc894-3b6a-4fb2-a081-e29e1497c9ba)

`Backup Now` -->

![image](https://github.com/user-attachments/assets/424a4051-e1bf-4e87-bc8c-24a27912ec10)

## the actual link
- `https://server.example.com:10000/virtual-server/download_backup.cgi?file=%2Ftmp%2F%2Ewebmin%2Fexampleuser%3Avirtualmin%2Dbackup%2Etar%2Egz`

## the decoded link
- `https://server.example.com:10000/virtual-server/download_backup.cgi?file=/tmp/.webmin/exampleuser:virtualmin-backup.tar.gz`

**Comment by iliajie** [comment]
Thanks! Got it!

Though, when you download the backup, isn't it already saved with a nice name?

**Comment by shoulders** [comment]
I am afraid not

![image](https://github.com/user-attachments/assets/a8ab73f4-4e09-4fa2-a85c-1f87b80027c2)

**Comment by iliajie** [comment]
Got it! Fixed now!

Thanks!

**Comment by jcameron** [comment]
Thanks Ilia for the fix!

**Comment by iliajie** [comment]
> Thanks Ilia for the fix!

You're welcome, Jamie!
