### ISSUE TITLE
Post-Installation Wizard - Memory use - missing option

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#875]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

> *** I have not installed Virtualmin in a while, but I am assuming this wizard step has not changed since then ***

### the background

During the Virtualmin post-installtion wizard you can choose to preload virtualmin libraries with 2 options

- yes
- no

![image](https://github.com/user-attachments/assets/15346dfb-072d-4dc8-9a46-55e4ca5e64b0)

### The issue

This does not match with the options

`Virtualmin --> System Settings --> Virtualmin Configuration --> Configuration category: Server settings --> Preload Virtualmin libraries at startup`

![image](https://github.com/user-attachments/assets/b8f9a41c-699d-4215-ab48-c3566842cefe)

![440bcc76c8693f36eda966957e6d4ddfec4cdbf7](https://github.com/user-attachments/assets/7ccee1a6-63b3-4b27-afff-c1bc73d7dee8)

### Question

- Is this intentional?
- this is my best guest of all of the library load locations, can you tell me if this is correct and If I am missing any:
   - Virtualmin Wizard memory use step
  - `Virtualmin --> System Settings --> Virtualmin Configuration --> Configuration category: Server settings --> Preload Virtualmin libraries at startup`
  - `Webmin --> Webmin Configuration --> Pre-load Webmin functions library`

### related post on forum

https://forum.virtualmin.com/t/should-i-preload-virtualmin-libraries-at-startup/128208

**Comment by iliajie** [comment]
> * Is this intentional?

Yes, there's no need to confuse users with unnecessary questions.

In fact, I think we should automatically configure it in Virtualmin upon installation or just have it always enabled, as it provides better performance with only a 70MB overhead.

In 2024, 70MB of RAM shouldn't be a problem!

What are your thoughts, Jamie?

**Comment by jcameron** [comment]
Yes, I agree that we should do pre-loading by default .. it's a small amount of RAM, and worth it for the performance benefits.

**Comment by jcameron** [comment]
I'll work on this, as it's an easy fix

**Comment by iliajie** [comment]
Great! Would you like to do it, or should I take care of it?

**Comment by iliajie** [comment]
> I'll work on this, as it's an easy fix

Ah, alright! Got it! Thank you!

**Comment by shoulders** [comment]
just to clarify, will the default be `all` or `core` ?

**Comment by jcameron** [comment]
I think it should be "all"

**Comment by iliajie** [comment]
Yes, I agree, it should be "all"!

**Comment by jcameron** [comment]
Ok I've made this change for the next release.

**Comment by shoulders** [comment]
Did you remove the wizard step, I am digging in the garden and can't read the code.

**Comment by jcameron** [comment]
Yes I also removed the wizard step

**Comment by shoulders** [comment]
I should never doubt you 😄 + I will now remove the step from my instructions.
