### ISSUE TITLE
SPF records - Add system and virtual server's IP addresses? - cannot be inherited from default settings

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#877]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      92  package updates are available   |

### the background

- on one of my domains I do not manage his DNS and as such I get a `Suggest DNS Records` option.
   ![image](https://github.com/user-attachments/assets/c3da34b9-2967-4e08-8f0c-afa7b77461df)
- my clients account uses a `client` template which inherits from default settings

### the issue

- The option `Add system and virtual server's IP addresses?` in the srrver template section `DNS domain cannot be set to inherit
- whatever is set in the cleitn template, this is what happens

#### default settings - DNS domain
![image](https://github.com/user-attachments/assets/f4908fad-503b-4104-ba53-d48677825b0a)

#### client template - DNS domain
![image](https://github.com/user-attachments/assets/a3d33761-39e3-4544-aff4-5981f2d91840)

## related issues
- I know there was a long discussion about `?all` and `~all` but I cannot remember where this is
- https://github.com/virtualmin/virtualmin-gpl/issues/856
- https://github.com/virtualmin/virtualmin-gpl/issues/876

**Comment by jcameron** [comment]
This is actually the same cause as the bug in https://github.com/virtualmin/virtualmin-gpl/issues/876 , which will be fixed in the next release. Thanks for reporting it!
