### ISSUE TITLE
Checking Configuration - Incorrect parsing of nameserver

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#879]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### background

I don't know if this is related.

I am currently having issues with DNSSEC chain of trust with one of my domains where it will not resolve `ns1.example.com` as a client (i.e. Not BIND). This is because I have enabled DNSSEC validation on my systemd-resolved DNS stub resolver.

### The issue

When I ran `Re-check and refresh configuration`

![image](https://github.com/user-attachments/assets/3485c7fd-694c-470f-b2a4-c333f43940d9)

I get the following output, however you can see it has not parsed my `${DOM} into a proper domain name

![image](https://github.com/user-attachments/assets/0bcb27f1-d4a2-477a-959e-eae204ce6a38)

### Question

Where is `ns1.${DOM}` being read from? is it the default template?

**Comment by shoulders** [comment]
### Additional

- on my server which is behind a NAT and therefore has a public and an internal IP
- I enabled DNSSEC verification on my systemd-resolved DNS stub resolver
- a couple of my domains have DNSSEC enabled
- I also have been running Split DNS for accessing my website
- I do also have NAT refelction running to catch the ones i did not setup with specifc host entires on my router

### what does this mean

- This meant that the websites that had split DNS host entries and had DNSSEC enabled on them would not resolve.
- the `${DOM}` above might be a result of a fallback position because domain name could not be resolved
- This opens 2 possibliilites
   - the parsing mechanism for `${DOM}` in the check config is not present (but I thought this might be fixed).
   - because the domain failed to resolve, the code just allows `${DOM}`  to be printed onscreen.

**Comment by jcameron** [comment]
Ah yes it looks like the check doesn't expand the default primary nameserver, and in fact it would be impossible to do so because the domain name isn't known in a global config check.

I'll fix this for the next release.
