### ISSUE TITLE
DNS Records - Only the first error discovered is reported

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#880]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### the background

DNS errors are reported in various places but in the DNS Records it is as follows

![image](https://github.com/user-attachments/assets/811d23a1-094f-4feb-95d3-508b22e31871)

### the issue

On this domain (at the time of writing) I know for a fact that both `ns1.quantumwarp.com` and `ns2.quantumwarp,.com` do not have an `A` record and cannot be resolved

after I created an `A` record for the domain the second error appears as follows

![image](https://github.com/user-attachments/assets/d4d64d2a-cc3f-4fae-b928-85110f08a445)

### proposed solution

enable the discovery and display of all errors found with a DNS record.

**Comment by jcameron** [comment]
Good suggestion, I'll fix this.
