### ISSUE TITLE
Manually created database does not set permissions to `All`

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#884]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### Background

My server template is set so that when I create a new Virtual server there is no default database created.

### the issue

When I created a database manually the permissions are not set to all. in fact only `Grant privileges` are not granted.

![image](https://github.com/user-attachments/assets/8eb4eff4-a68f-49d5-b2e6-34818f20c3d1)

-->

![image](https://github.com/user-attachments/assets/805cd579-e3af-404e-a306-23b7114669d8)

![image](https://github.com/user-attachments/assets/b8aaddd9-bf56-431f-a1fd-8532fd07a18b)

### proposed solution

please can you make it when a database is created manually that permissions are set to All.

**Comment by iliajie** [comment]
Hello,

> in fact only `Grant privileges` are not granted.

This is expected.



> please can you make it when a database is created manually that permissions are set to All.

No, this is expected [change](https://github.com/virtualmin/virtualmin-gpl/commit/5b7880a8433746793d1c2f7c24dc75a1518b9596) because we don't want users to re-grant privileges.

**Comment by shoulders** [comment]
because this is expected behaviour, I will now close this non-issue
