### ISSUE TITLE
DMARC - Missing options

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#885]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |      58  package updates are available   |

### The background

There are 3 places to set DMARC settings
- `Virtualmin --> DNS Settings --> DNS Options`
  ![image](https://github.com/user-attachments/assets/5f184984-91d3-4081-bf52-1577d25e3ff7)
- `Virtualmin -->System Settings --> Server Templates`
  ![image](https://github.com/user-attachments/assets/83522b0c-e4a2-4896-970d-af2ab261f290)
- ` Virtualmin --> DNS Settings --> DNS Records`
  ![image](https://github.com/user-attachments/assets/ffac7561-cac8-4f9f-a268-e759beba21cb)

### The issue

There are options in `Virtualmin -->System Settings --> Server Templates` that cannot be configured in `Virtualmin --> DNS Settings --> DNS Records` 

But you can manually edit the DNS records manually however in this contect it is more of a workaround

### Additional

- If DMARC is not enabled during the virtual server creation and the account owner later on decides to enable DMARC
  - then the options from the server template are used such as `Reporting URI for forensic reports` and `Reporting URI for aggregate reports`
  - but I assume that `DMARC policy for emails that fail SPF or DKIM` and `Percentage of messages to apply policy` are not as they are defined on the `DNS Options` page.

### Proposed solution

- Add the missing options in to the  `DNS Options` page so they can be configured through the GUI.
- After the Virtual server is created then perhaps the DMARC settings should not be pulled from the server template as the option control should now be passed to the local account just like SPF.

**Comment by jcameron** [comment]
Good point, I will look into adding these to the DNS Options page..

**Comment by jcameron** [comment]
Ok this has been implemented for inclusion in the next Virtualmin release..

**Comment by iliajie** [comment]
Test, do not reply (will be deleted later):

<img width="888" alt="image" src="https://github.com/user-attachments/assets/409804b4-c617-43b1-ac60-4bb9b3b9662b">
