### ISSUE TITLE
One line fix for broken email autoconfig

### ISSUE THREAD

**Issue by johnheenan** [virtualmin/virtualmin-gpl#889]
In function `get_email_autoconfig_imap` in file `feature-mail.pl` the value of the variable `$imap_host` always evaluates to "mail." no matter what the domain is.

This variable is used in template substitution with autoconfig.cgi. Thunderbird, Outlook and others will be given incorrect imap and pop3 servers to use with auto configuration, requiring manual correction.

One line fix is to add in as first line to the function
```
local ($d) = @_;
```

**Comment by jcameron** [comment]
Thanks for the fix!
