### ISSUE TITLE
Backups failing due to SCP change in Ubuntu 24.04 (and a fix)

### ISSUE THREAD

**Issue by philmck** [virtualmin/virtualmin-gpl#890]
I've recently upgraded a server to Ubuntu 24.04.1 (running Webmin 2.202, Virtualmin 7.20.2) and found that backups from **Virtualmin > Backup and Restore > Scheduled Backups** to an SSH server (running Synology DSM 7.2.1-69057 Update 5) are now consistently failing with a message like this:

`Failed to connect to SSH server : scp: dest open "/volume1/beechesit/test/full_2024-09-01T1758/virtualmin-copy-test.beechesit": No such file or directory scp: failed to upload file /tmp/.webmin/962326_4115860_2_backup.cgi to /volume1/beechesit/test/full_2024-09-01T1758/virtualmin-copy-test.beechesit`

The cause seems to be a compatibility-breaking change in the SCP implementation in the lastest version of Ubuntu. I found it here
https://stackoverflow.com/questions/74311661/subsystem-request-failed-on-channel-0-scp-connection-closed

A workaround is to add the "-O" option to the SCP invocation, but Virtualmin has no way to configure this.

However, I found the line in question in /usr/share/webmin/virtual-server/virtual-server-lib-funcs.pl line #7038, hacked it to add the -O argument and it works. (You will need to restart Webmin in Webmin > Webmin Configuration.)

`local $cmd = "scp -r -O ".($port ? "-P $port " : "").$config{'ssh_args'}." ".`

It's only a temporary fix, obviously. For a start, it will be overwritten by the next Webmin update, but also "legacy" protocols tend to be withdrawn. Probably the quoting needs to be fixed or something.

The comment for that option says 
 > Use  the  legacy SCP protocol for file transfers instead of the SFTP protocol. Forcing the use of the SCP protocol may be necessary for servers that do not implement SFTP,  for  backwards-compatibility for particular filename wildcard patterns and for expanding paths with a ‘~’ prefix for older SFTP servers.

However, none of those explanations appear to apply here. In this case, both ends support the SFTP protocol, removing all wildcard patterns doesn't help and none of the paths are using a '~' prefix.

**Comment by jcameron** [comment]
Wow, surprising that they made a change that wasn't backwards compatible!

However, in the next Virtualmin release I'll add a config option for flags to just the `scp` command that you could use in this case.

**Comment by chris001** [comment]
Yes, `scp` is deprecated, they recommend migrating to `sftp`:
https://www.redhat.com/en/blog/openssh-scp-deprecation-rhel-9-what-you-need-know

**Comment by philmck** [comment]
The same problem exists in **Webmin > Backup Configuration Files**, of course.

The line to fix is at /usr/share/webmin/backup-config/backup-config-lib.pl line 644 if that helps.

**Comment by philmck** [comment]
> Yes, `scp` is deprecated in OpenSSH, they recommend migrating to the `sftp` command...

I find it much slower though (at least as implemented in WinSCP) for common tasks like moving a bunch of files after unzipping.

**Comment by philmck** [comment]
> Wow, surprising that they made a change that wasn't backwards compatible!

Yeah, not the way I was planning to spend Sunday afternoon. And I suspect I'm far from alone in that.

**Comment by chris001** [comment]
> I find it much slower though (at least as implemented in WinSCP) for common tasks like moving a bunch of files after unzipping.

`scp` doesn't require acknowledgment for every individual packet, this really speeds up transfers on high-latency networks.
`sftp` requires acknowledgment for each packet.
Luckily, OpenSSH is known for high performance `sftp`. 
To increase performance, you can try to enable server-side compression in OpenSSH.
Both Webmin and Virtualmin provide interfaces for configuring OpenSSH, but the default settings usually do not include configuring compression.
To enable compression, edit the OpenSSH configuration file (`sshd_config`) and set the `Compression` directive to `yes`.
1. Open the OpenSSH config file:
    Webmin: Go to Servers -> SSH Server -> Edit Config Files.
    Virtualmin: Go to Webmin -> Servers -> SSH Server -> Edit Config Files.
2. Look for the line that says `Compression`.
3. Uncomment it (remove the `#`), and set `Compression` to `yes`.
4. Click `Save and Close`.
5. Click `Apply changes`.

**Comment by philmck** [comment]
Unfortunately, in view of the security issues with SCP it appears that a better solution than adding the -O option to SCP would be to switch the Webmin and Virtualmin "SSH" backups to use SFTP or rsync instead.

**Comment by jcameron** [comment]
Hmm, maybe we should add `sftp` as a separate remote backup type then?

**Comment by chris001** [comment]
> The difference happens at the next step, where you typically select all the files in the subfolder and move them up a level. With SCP this seems to happen in an instant (just an adjustment to the FAT?), with SFTP it seems to take much longer (perhaps copying then deleting rather than moving?).

Might be a good idea to post this issue [on the OpenSSH bugzilla issue tracker](https://bugzilla.mindrot.org/buglist.cgi?quicksearch=sftp) and make them aware of it.  They could take a look at it and see if it's possible to improve the performance of the part of `sftp` that remotely moves files between directories to make it as fast as how `scp` does it.
