### ISSUE TITLE
Virtualmin Dovecot Imap Quota not enabled

### ISSUE THREAD

**Issue by amitsamanta996** [virtualmin/virtualmin-gpl#891]
Filesystem has quota enabled, edit users shows quotas for each mail account as expected
doveadm quota get -u user@example.com also shows correct data
how to enable imap quota, so that mail user quota is shown in imap clients?

**Comment by amitsamanta996** [comment]
`plugin {`
`  quota = fs:user`
`}`

**Comment by iliajie** [comment]
We don't know exactly! You'll need to dig into it and check the Dovecot documentation.

I assume that `/etc/dovecot/conf.d/10-mail.conf` might also need a change, something like:

```
protocol imap {
    mail_plugins = $mail_plugins quota imap_quota
}
```

By the way, the right place to as for help is https://forum.virtualmin.com.
