### ISSUE TITLE
Edit Databases - Remote hosts - Remove the period at the end of the IP mask example

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#902]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.4              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2                            |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  52 package updates are available  |

### The issue

If you look on the page: `Virtualmin --> Edit Databases --> Remote Hosts` you can see the follwoing line

> You may enter hostnames, IP addresses, or network patterns like 192.168.1.% .

![image](https://github.com/user-attachments/assets/6f038c2b-e762-44de-b505-2154f197451d)

On the end is a `period` after the `%` sign now I think this is supposed to show the end of the line rather than being part of the `mask` but this is not clear unless you know. As you know sometimes when entering domain names you have to add a period on the end so I think clarification is needed here.

### proposed solution

1. remove the period and bold the mask
2. put the mask in some other sort of highlighting or maybe increase the font size

either way make it very clear what is the format of entries to add and that the period is not part of it, unless it is and this should be part of the highlighting.

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

Fixed now!

#### Example
<img width="1183" alt="image" src="https://github.com/user-attachments/assets/afaef9ee-e81f-405a-83b4-a957a347ac0d">
