### ISSUE TITLE
Pro: My GPL was downgraded to an old version of Pro

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#906]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5                   |
|  Usermin version     |  2.102                                  |
|  Virtualmin version  |  7.20.2 Pro                             |
|  Theme version       |  21.20.7                                |
|  Apache version      |  2.4.52                                 |
|  Package updates     |  All installed packages are up to date  |

### background

I upgraded my Virtualmin GPL 7.20.2 to Pro

### The issue

When I upgraded from GPL to Pro I expected the same version number but the Pro version, however this did not happen, I got an old version, `7.9.0 Pro`

The upgrade path went as follows:

- started on `7.20.2 (GPL)`
- installed the Pro licence keys + ran upgrade
- I then was on  `7.9.0 Pro`
- there was an upgrade package watiting for virtualmin which i installed
- I am now on `7.20.2.pro-1`

**Comment by jcameron** [comment]
How did you do the upgrade to Pro exactly?

**Comment by shoulders** [comment]
- i went to the menu item `Upgrade to Virtualmin Pro`
- I entered the serial number and key
- I clicked upgrade

**Comment by iliajie** [comment]
We will address this issue in this PR https://github.com/virtualmin/virtualmin-gpl/pull/910.

Did you restore this instance from an old snapshot?

**Comment by shoulders** [comment]
@iliajie did you mean me? Both my `dev` and `live` servers have never been restored from any snapshots. I have also never done any non-standard stuff to them either, so they are vanilla.

**Comment by iliajie** [comment]
Anyway, that PR should address your issue! You can apply that patch using `webmin patch` command and see if that works for you.

**Comment by shoulders** [comment]
Thanks for the fix.

When I installed my Pro license key and serial, Virtualmin was upgraded to `7.9 Pro` with `7.20.2 Pro` waiting in the package updates which I obviously installed immediately and now I am on `7.20.2 Pro`.

So unfortunately I cannot use this patch to see if it works, I reported it because not many people would notice this to report it. 😄 

I assumed it was the update script was pulling an old version of Pro which was the issue. It is almost like it was hardcoded into the upgrade script rather than getting the latest version from the repo (or the equivalent Pro version).

Will this of caused any issues with my installs? I did immediately update to the latest version after converting.

**Comment by iliajie** [comment]
> I assumed it was the update script was pulling an old version of Pro which was the issue.

That’s more of a package manager-related "issue." The update script doesn’t pull anything. Still, I’m having a hard time imagining how that would be possible, since adding a new repo should trigger the package manager to update its metadata.


> Will this of caused any issues with my installs? I did immediately update to the latest version after converting.

No idea. Without exact data, there’s nothing to go on.

Perhaps the time was off on your system, but that would usually trigger an SSL error when updating metadata. So, no clear ideas at the moment...

**Comment by shoulders** [comment]
I might have a snapshot from a couple of weeks ago of my dev site. It is worth me spinning this up for you? It might take me a while.

I will compare my /etc/ and virtualmin configs before and after upgrade to check for issues.

P.s. I did back my websites up first. 😃

**Comment by shoulders** [comment]
I have done a text compare between my configs for Vitualmin and webmin, from before and after and there are almost the same.

Obviously there are a few other settings added for Pro such as `virtualmin-support` references.

### The only thing of note was:

**This folder was created**
/etc/webmin/syslog/

**These files were created**
/etc/webmin/syslog/username1.acl
/etc/webmin/syslog/username2.acl
/etc/webmin/syslog/username3.acl

**These lines were added in `/etc/tmp/backup-config-manifests`**

/etc/webmin/syslog/username1.acl
/etc/webmin/syslog/username2.acl
/etc/webmin/syslog/username3.acl

**NB:** username is just a placeholder for the real usernames.

**Comment by shoulders** [comment]
@iliajie did you want me to spin up the old copy of my website? If so what information would you need?

I suspect I was not the only one to get this issue, it is just I checked package versions and updates. 😄 

Just in case it was a thing, I am sure the initial version of Virtualmin GPL I installed was 7.9.0 which is the same version of the Pro that was installed after the upgrade.

This will not be an issue again for me, so this ticket could be closed from my point of view. 😄

**Comment by iliajie** [comment]
> This will not be an issue again for me, so this ticket could be closed from my point of view.

Agreed! Closing now! Thanks!
