### ISSUE TITLE
Pro: After upgrade - add a button to return to the dash

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#907]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5                   |
|  Usermin version     |  2.102                                  |
|  **Virtualmin version**  |  **7.9.0 Pro**                             |
|  Theme version       |  21.20.7                                |
|  Apache version      |  2.4.52                                 |
|  Package updates     |  All installed packages are up to date  |

### background

I performed an upgrade from GPL to Pro

### feature request

Can you add a button to the dashboard after the upgrade completes. This is not a mandatory thing but I feel like it adds completeness to the process and is a good way of showing this to the user after the process is finished.

The page is where you enter the serial + key

![image](https://github.com/user-attachments/assets/de4a113a-2f6d-4fcb-88a2-f6b8645fecb7)

**Comment by jcameron** [comment]
Good idea, I'll fix that!

**Comment by shoulders** [comment]
@jcameron thanks
