### ISSUE TITLE
Reboot Required - Email notification

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#908]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5                   |
|  Usermin version     |  2.102                                  |
|  Virtualmin version  |  7.20.2 Pro                             |
|  Theme version       |  21.20.7                                |
|  Apache version      |  2.4.52                                 |
|  Package updates     |  All installed packages are up to date  |

### The background

Virtualmin notifies me that a Reboot is required to apply a recent mandatory update by the OS

![reboot required](https://github.com/user-attachments/assets/f82c3956-487b-4eb8-9335-f93663794ebb)

### The feature request

Can it be made so that an email be sent to notify the system admin just like the updates package does now (if enabled).

**Comment by iliajie** [comment]
Hello,

The reboot message is linked to kernel updates, and email notifications for those are already configurable in the "System ⇾ Software Package Updates" page.

What we don’t have yet is the ability to configure an auto-reboot after kernel updates. Both `unattended-upgrades` and `dnf-automatic` offer this option.

**Comment by shoulders** [comment]
> The reboot message is linked to kernel updates, and email notifications for those are already configurable in the "System ⇾ Software Package Updates" page.

I am configured to get security update email notifications only, is this why I am not getting reboot notification emails. I would of regarded this as security thing. As of yet I have never had a reboot notification email but I have had reboot notification emails.

![image](https://github.com/user-attachments/assets/0a05f127-583b-4a55-b0db-641b35b71d07)

> What we don’t have yet is the ability to configure an auto-reboot after kernel updates. Both unattended-upgrades and semi-automatic offer this option.

I don't need automatic rebooting, I prefer to do that manually 😄

**Comment by iliajie** [comment]
> I would of regarded this as security thing. As of yet I have never had a reboot notification email but I have had security notification emails.

If you receive kernel updates by email, they can serve as a reboot notification.

> I don't need automatic rebooting, I prefer to do that manually

99% of the time it's a waste of time.

**Comment by jcameron** [comment]
One thing we could do pretty easily is add a monitor type for "reboot required" in the System and Server Status module. That already supports sending email on a schedule you can control.

**Comment by jcameron** [comment]
I've implemented this in https://github.com/webmin/webmin/commit/65e70835d28a9ccb225a7879abb9fd5ffb800044

**Comment by shoulders** [comment]
@jcameron thanks for the fix.

Should this monitor be enabled by default in Webmin/Virtualmin? If not then this job should be closed.

**My thoughts**

If someone gets an email about needing to reboot and they don't want these emails it will be easy to turn off, but otherwise people might not know this function exists. I will becaus eI reported it and I am going to add to my notes.

I think this should be on by default.

**Comment by jcameron** [comment]
I don't think email notification should be on by default, since there's also a notification that appears on the dashboard when the root user logs in.

**Comment by shoulders** [comment]
fair enough, makes sense.

**Comment by shoulders** [comment]
- Where will be the there a on/off option?
- Did this get the default webmin email treatment? it was not on my list for obvious reasons.

thanks as always

**Comment by jcameron** [comment]
You'll be able to send a reboot needed notification using the System and Server Status module, which will also follow the default email.
