### ISSUE TITLE
Software update packages - Success messages and return button logic

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#909]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5                   |
|  Usermin version     |  2.102                                  |
|  Virtualmin version  |  7.20.2 Pro                             |
|  Theme version       |  21.20.7                                |
|  Apache version      |  2.4.52                                 |
|  Package updates     |  All installed packages are up to date  |

### the issue

When you update packages via `Webmin --> System --> Software Package Updates`  the success message are a bit awkward.

It has `install complete.` and `Successfully installed 2 packages.` and after a pause like the installer is still doing stuff the `Return to package list` button appears

![image](https://github.com/user-attachments/assets/7652cbef-7230-4a89-aeb0-594ac3746147)

![image](https://github.com/user-attachments/assets/b78ed89a-5902-49aa-aa54-7d5b343cafc0)

### proposed solution

- only have one of success messages
  - `install complete.` or 
  - `Successfully installed 2 packages.`
- the `Return to package list`  should appear at the same time as the success message.

NB: Is the installer still doing stuff and that is why there is a pause after the success message before the button appears.

**Comment by iliajie** [comment]
Hello,

Agreed. We should keep the user informed when the package cache list is being updated in the background.

However, we won’t change the "duplication" of the messages, as it’s expected and generated by two different modules, one of which is indented. Though, I’ve made the messages printed at the end of each phase consistent.
