### ISSUE TITLE
Website SSL cert not removed from dovecot configuration

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#91]
Add some point, probably when enabling the 'Apache SSL Website'-feature, and an SSL Certificate is generated, some lines are added to:

> /etc/dovecot/dovecot.conf

Something along the lines of:

```
local_name domain.tld {
  ssl_cert = </home/domain.tld/ssl.cert
  ssl_key = </home/domain.tld/ssl.key
}
```

Unfortunately these lines are not automatically removed when using the 'Delete Virtual Server' function.

This breaks the dovecot server on the next restart:

> doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line ***: ssl_cert: Can't open file /home/***/ssl.cert: No such file or directory

**Comment by jcameron** [comment]
Yeah there's a hard to track down bug that can cause this in some cases. 

Does it happen 100% of the time if you create and delete a domain with SSL?

**Comment by PitWenkin** [comment]
I'm not sure, as I don't often delete domains, at least not ones with mails enabled.

But I would guess that the last 3 I deleted, that had an entry in the dovevot.conf, had this issue.
Unfortunately dovecot does not always restart in the next 24 hours, so it might take a few days for the problem to occur…

I'm however sure that all those domains had a Let's encrypt certificate and not a selfsigned or bought one.

**Comment by PitWenkin** [comment]
This is still happening.
This time it was a Let's Encrypt certificate, unfortunately I did not remember the problem and was not checking logfiles or such.

**Comment by prosinger** [comment]
Confirmed. Happens every time after I delete a Virtual Server and had VM copy the SSL certs to Dovecot prior.

**Comment by iliarostovtsev** [comment]
Latest commits to Dovecot fixes it.
