### ISSUE TITLE
Add "Validate Virtual Server" alerts to Webmin/Virtualmin Action Logs?

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#912]
On one of our servers, scheduled validation by email is set to only send emails when there is a problem. A month ago, we started receiving alerts of an issue. The issues has some similarities to https://github.com/virtualmin/virtualmin-gpl/issues/649 so we started investigating.

We reviewed the action logs for the 24 hours before receiving the validation error report email and it gave us a lead. So it got me thinking: How can we have more relevant troubleshooting information in one place? I am not sure this is the right way to go, but it would have saved us a bit of time today. And if we were new to this server, we would not have had the history of email alerts, and thus, the investigation would have been much more difficult.
 
![2024-09-28_151736](https://github.com/user-attachments/assets/dad73925-9547-46b2-bb49-9086bf0779be)

**Comment by jcameron** [comment]
I see what you mean, but I don't think it would make sense to put this in the actions log because that only tracks operations that change something on the system. Perhaps better instead to use email as your logging mechanism?

Alternately, we could integrate this with the System and Server Status module, that has it's own logging..

**Comment by jcameron** [comment]
Ok I have implemented integration of domain validation with the System and Server Status module, which will allow you to keep track of the history of checks and errors more easily.

**Comment by marclaporte** [comment]
Thank you @jcameron !

We will set this up.

**Comment by marclaporte** [comment]
For the record, here is the commit: https://github.com/virtualmin/virtualmin-gpl/commit/ade76830e8673e878b1abe35e344e3f5f61c030d

**Comment by iliajie** [comment]
Thanks, Marc!

Jamie, could something potentially be slowing down the creation of Apache and Apache SSL websites with all the latest changes? I didn't check the code but I think I’ve noticed it happening recently at domain creating time...

**Comment by jcameron** [comment]
I don't think so - what step is slow exactly?
