### ISSUE TITLE
Automatically re-request an SSL certificate when a new alias is added to the domain

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#915]
Hi Jamie!

Is there a reason why Virtualmin doesn't automatically re-request an SSL certificate when a new alias is added to the domain?

**Comment by jcameron** [comment]
Actually this should happen already - the code for it is here : https://github.com/virtualmin/virtualmin-gpl/blob/master/virtual-server-lib-funcs.pl#L8554

*However*, it only happens if the original domain didn't limit the list of hostnames the SSL cert was request for.

**Comment by jcameron** [comment]
I've made a small improvement to this here : https://github.com/virtualmin/virtualmin-gpl/commit/5efea7b555893789adfc2037efc8784d9804f42d

**Comment by iliajie** [comment]
> I've made a small improvement to this here : [5efea7b](https://github.com/virtualmin/virtualmin-gpl/commit/5efea7b555893789adfc2037efc8784d9804f42d)

Thanks, I’ve commented on it.

**Comment by jcameron** [comment]
Weird, when I open that link I don't see any comment?

**Comment by iliajie** [comment]
Well, I think someone at Microsoft made a questionable UI/UX decision. It’s tucked away on the right side of the screen. I got confused by it myself a few days ago.

<img width="1446" alt="image" src="https://github.com/user-attachments/assets/b5be3f51-4984-47c2-9a8f-287b0b590d03">

**Comment by jcameron** [comment]
Yeah I should do better with my line wrapping! I violated my own 80 character rule here.
