### ISSUE TITLE
S3 Restore seems taking too long since the download repeated each domain

### ISSUE THREAD

**Issue by willnode** [virtualmin/virtualmin-gpl#923]
Hello, I've triggered a restore via CLI

```
virtualmin restore-domain --source s3://domcloud-backups/20241002-nuris.id-ganluza.tar.gz --all-domains --feature virtualmin-nginx --feature virtualmin --feature dns --feature dir --feature mysql --feature webmin --feature postgres --fix --reuid --skip-warnings --option dir delete 1 --option dir homes 1
Checking for missing features ..
.. all features in backup are supported

Checking for errors in backup ..
.. no errors found

Starting restore..
Downloading archive from S3 server ..

.. done

Extracting backup archive files ..
```

Seems stuck there for hours.

I've checked movements in /tmp it seems the download happens repeatedly. This is a large backup.

```
Every 2.0s: ls /tmp/.webmin/577213_2242703_4_restore-domain.pl -lh                                                 sgp.domcloud.co: Wed Oct 16 00:38:00 2024

total 11G
-rw-r--r-- 1 root root 6.9G Oct  2 07:54 20241002-nuris.id-ganluza.tar.gz
-rw-r--r-- 1 root root 4.1G Oct 16 00:38 20241002-nuris.id-ganluza.tar.gz.Abbfd0F0


Every 2.0s: ls /tmp/.webmin/577213_2242703_4_restore-domain.pl -lh                                                 sgp.domcloud.co: Wed Oct 16 00:39:33 2024

total 6.9G
-rw-r--r-- 1 root root 6.9G Oct  2 07:54 20241002-nuris.id-ganluza.tar.gz
                                     /..
    6.9 GiB [######################] /746467_2242703_6_restore-domain.pl                                                                                        6.9 GiB [##################### ] /577213_2242703_4_restore-domain.pl
  960.0 KiB [                      ]  954569_2242703_8_restore-domain.pl
   96.0 KiB [                      ]  477610_2242703_3_restore-domain.pl
    4.0 KiB [                      ]  559622_2242703_5_restore-domain.pl
    4.0 KiB [                      ]  171977_2242703_2_restore-domain.pl
    4.0 KiB [                      ]  937172_2242703_7_restore-domain.pl
```

I'm reporting here to mention slowness issue. Maybe there's some logic that can be optimized. In my specific use case, this one fails due to other issue, that will be raised to Virtualmin Support.

**Comment by jcameron** [comment]
It's possible that virtualmin is downloading the backups, but there are failing to be restored and so it re-tries the backup.

Are you able to successfully restore a smaller domain? If  not, what error message do you get?

**Comment by willnode** [comment]
I think the download is fine. It just that it's weird since it first download `<backup>.tar.gz` then `<backup>.tar.gz.<hash>`. I confirmed that `<backup>.tar.gz.<hash>` redownloads from S3 from iftop. The number of times it redownloads  `<backup>.tar.gz.<hash>` may close to number of domains I have in there. I believe this is logic problem.

**Comment by willnode** [comment]
Found it!

https://github.com/virtualmin/virtualmin-gpl/blob/2bd3f41b0527263214c3fff653e27e7c6aa8f5dc/backups-lib.pl#L3769-L3779

You can see `$dname` is not used anywhere for s3_download. This for loop is redundant.

**Comment by willnode** [comment]
Hmm i'm not fluent in perl yet. But it should say if $tempfile already exist please don't redownload again. `$si->{'file'}` should in same file in this case.

**Comment by willnode** [comment]
I've send a patch. works at my server and it speeds up the download. The whole extraction is within 10 minutes now instead of hours.

**Comment by jcameron** [comment]
Thanks for that patch, but I thunk that the real problem is deeper - Virtualmin shouldn't be downloading the same backup file over and over again.

When you do your restore, are you giving the path to a tar.gz file, or to an S3 container that contains potentially multiple files?

**Comment by jcameron** [comment]
Also, do you have the `aws` CLI command installed on your system?

**Comment by willnode** [comment]
I use this command to restore:

`virtualmin restore-domain --source s3://domcloud-backups/20241002-nuris.id-ganluza.tar.gz ....`

The backup generated using this command:

`virtualmin backup-domain --dest s3://domcloud-backups/20241002-nuris.id-ganluza.tar.gz --user nuris-id --all-features --ignore errors`

This domain contains many subservers, and the destination is a single file.

Yes, we have `aws` cli.

**Comment by jcameron** [comment]
Ok I found the bug that causes this - it happens only if there are many domains in one file. We'll include a fix in the next release..

**Comment by willnode** [comment]
Thank you! I've closed my PR.
