### ISSUE TITLE
MySQL or MariaDB: selector

### ISSUE THREAD

**Issue by Ramoonus** [virtualmin/virtualmin-gpl#926]
New feature request
Functionality should be similar, only package names are different, and config files are stored in another location
but should be relatively easy to implement

**Comment by iliajie** [comment]
Hello,

Can you elaborate on your suggestion? Are you proposing an option to choose between installing MySQL or MariaDB during the Virtualmin installation?

**Comment by Ramoonus** [comment]
> Hello,
> 
> 
> 
> Can you elaborate on your suggestion? Are you proposing an option to choose between installing MySQL or MariaDB during the Virtualmin installation?

Exactly! Some (web-based) applications run better on one or the other.
Real difference for VM would be mostly in the installation prompt and most administrative things can easily be made for both

**Comment by iliajie** [comment]
We currently allow installing MySQL manually, but it must be pre-installed (without performing any configurations) before running the Virtualmin installation script.

**Comment by Ramoonus** [comment]
I tried to install it afterwards by removing MariaDB but I had to spin a new server to be successful

**Comment by iliajie** [comment]
> I tried to install it afterwards by removing MariaDB but I had to spin a new server to be successful

You can do it afterward if done correctly. First, completely remove MariaDB, including manually deleting `/var/lib/mysql` directory, then install MySQL and run:

```
virtualmin-config-system -i MySQL
```

**Comment by Ramoonus** [comment]
thank you, but wasn`t clear to me from the documentation

**Comment by iliajie** [comment]
> thank you, but wasn`t clear to me from the documentation

Thanks, you're right! I’ve just updated the [Download](https://www.virtualmin.com/download/#install-your-operating-system) page to include instructions on how MySQL should be pre-installed.
