### ISSUE TITLE
Cpanel import - cannot choose account plan

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#928]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  10 package updates are available  |

### the issue

When importing a cpanel archive you cannot select the account plan, only the server template

![image](https://github.com/user-attachments/assets/2ca8b637-e156-4d37-b088-3bd5734c2bc3)

### solution

Add this option 😄

**Comment by jcameron** [comment]
That is an excellent suggestion and I have no idea why we never implemented it before! Look for this in the next release of Virtualmin.

**Comment by shoulders** [comment]
awesome
