### ISSUE TITLE
Additional backup destination only offered after saving backup schedule once

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#93]
Adding one or more additional backup destinations in `Backup and Restore - Scheduled Backups` is only possible after saving the schedule with the first destination filled out.

![Add schedule](https://user-images.githubusercontent.com/45786226/61198059-6e964780-a6d8-11e9-8b54-8c8d8f531341.png)

Only after reloading the form the `Add another destination`-button appears

![Edit Schedule](https://user-images.githubusercontent.com/45786226/61198060-70f8a180-a6d8-11e9-8e27-a67d123648bb.png)

If this is not intentional, the fix should be somwhere around those lines:

https://github.com/virtualmin/virtualmin-gpl/blob/b05fa630803240295fbbddd9385c19ddc55030cd/backup_form.cgi#L231

**Comment by jcameron** [comment]
That's actually intentional currently - only one new destination can be added at a time.

**Comment by PitWenkin** [comment]
OK, thanks. I can live with that.
