### ISSUE TITLE
cpanel migrate - password field is not masked

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#931]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  10 package updates are available  |

On the page `Add servers --> migrate virtual server` the **Password for administrator** is not masked. The input box is in clear text.

Please can you add the typical masking here.

![image](https://github.com/user-attachments/assets/a200f81c-73b0-4cf2-92e2-93fc08f11a83)

**Comment by jcameron** [comment]
Thanks, we'll fix this for the next release.
