### ISSUE TITLE
migrate virtual server - Add uploaded file name

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#932]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  10 package updates are available  |

## the issue

on the page `Add servers --> Migrate Virtual Servers` you can upload a file that is going to be imported.

When you have selected the file the page shows the term **1 file selected**.

![image](https://github.com/user-attachments/assets/177d7d70-8eea-45ea-86f6-b3ba49c715b0)

## feature request

Instead of saying 1 file selected, can you make it so it shows the filename. I would prefer this as I allows me to clarify I have selected the correct archive to upload.

**Comment by iliajie** [comment]
> Instead of saying 1 file selected, can you make it so it shows the filename. I would prefer this as I allows me to clarify I have selected the correct archive to upload.

Yes, good suggestion! Fixed now!
