### ISSUE TITLE
cpanel migration - subdomains use my internal IP

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#933]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  10 package updates are available  |

## the issue

I imported a cpanel account which had subdomains. These subdomains DNS were populated with my server's internal IP address  (10.0.0.47) and not my public one (123.123.123.123).

IPs changed for privacy/security.

The parent account's DNS was correctly set.

the 2 subdomains are
- demo.example.com
- search.example.com

```
$ttl 3600
example.com.	IN	SOA	ns1.example.com. root.ns1.example.com. (
			2024101916
			3600
			600
			1209600
			3600 )
@	IN	NS	ns1.example.com.
ns1.example.com.	IN	A	123.123.123.123
@	IN	NS	ns2.example.com.
ns2.example.com.	IN	A	123.123.123.123
example.com.	IN	A	123.123.123.123
www.example.com.	IN	A	123.123.123.123
ftp.example.com.	IN	A	123.123.123.123
localhost.example.com.	IN	A	127.0.0.1
webmail.example.com.	IN	A	123.123.123.123
admin.example.com.	IN	A	123.123.123.123
mail.example.com.	IN	A	123.123.123.123
example.com.	IN	MX	5 mail.example.com.
example.com.	IN	TXT	"v=spf1 a mx ip4:123.123.123.123 -all"
202311._domainkey.example.com.	IN	TXT	( "v=DKIM1;.......................... *** removed on purpose*****
demo.example.com.	IN	A	10.0.0.47
www.demo.example.com.	IN	A	10.0.0.47
ftp.demo.example.com.	IN	A	10.0.0.47
localhost.demo.example.com.	IN	A	127.0.0.1
webmail.demo.example.com.	IN	A	10.0.0.47
admin.demo.example.com.	IN	A	10.0.0.47
search.example.com.	IN	A	10.0.0.47
www.search.example.com.	IN	A	10.0.0.47
ftp.search.example.com.	IN	A	10.0.0.47
localhost.search.example.com.	IN	A	127.0.0.1
webmail.search.example.com.	IN	A	10.0.0.47
admin.search.example.com.	IN	A	10.0.0.47
@	IN	CAA	0 issuewild letsencrypt.org
```

### additional

I was under the assumption when you imported a cpanel account with subdomains a special subdomain would be created (i.e. not sub server).

- Virtualmin --> system settings --> configuration category: Advanced --> Allow creation of sub-domains`

**My current setting**

![image](https://github.com/user-attachments/assets/ede44ccf-d75c-4add-86d6-cbf44848d1ca)

Thanks

**Comment by jcameron** [comment]
Was the issue here that the parent domain had the public IP, but the sub-domain imported from the same cPanel backup was given the internal IP?

**Comment by shoulders** [comment]
> Was the issue here that the parent domain had the public IP, but the sub-domain imported from the same cPanel backup was given the internal IP?

Yes this is correct.

**Comment by iliajie** [comment]
> Ok I see the cause of this now - we'll fix it in the next release.

@shoulders You can test it right away by applying this patch:

```
webmin patch https://github.com/virtualmin/virtualmin-gpl/commit/d8771a1
```

**Comment by shoulders** [comment]
I will try on my test site tommorow.

**Comment by shoulders** [comment]
@iliaross This is off topic but this thread makes it relevant. I will add this to my notes

## background
- above you have a patch

```
webmin patch https://github.com/virtualmin/virtualmin-gpl/commit/d8771a1
```

- the `d8771a1` bit matches up with the shortcode

<img width="850" height="211" alt="Image" src="https://github.com/user-attachments/assets/d472afd3-d18a-44fd-96a3-809857e4f61a" />

- however the link for the sortcode URL is

```
https://github.com/virtualmin/virtualmin-gpl/commit/d8771a1f4cd4f1c979942190881a15a97d44fe00
```

## Questions
- do both these work?
```
webmin patch https://github.com/virtualmin/virtualmin-gpl/commit/d8771a1
webmin patch https://github.com/virtualmin/virtualmin-gpl/commit/d8771a1f4cd4f1c979942190881a15a97d44fe00
```
- Why does the shortcode work when it is not the full commit reference?
- Is there any chance of collisions and the wrong commit being applied if you use this shortened version of the commit reference?

## Why do I need this information

Jamie has made some commits and has asked me to check them so I need to figure out how to build the patch commands and these questions arose.

I search on webmin and virtualmin docs for the word `patch` and did not find any info,

**Comment by iliaross** [comment]
> Do both these work?

Yes.

> Why does the shortcode work when it is not the full commit reference?

Because it's long enough to be unique.

> Is there any chance of collisions and the wrong commit being applied if you use this shortened version of the commit reference?

No.

> Jamie has made some commits and has asked me to check them so I need to figure out how to build the patch commands and these questions arose.

Use the full form for simplicity. I micromanage this for users so the text stays short enough to fit in the visible code box without horizontal scrolling, reducing the chance they mess anything up.

**Comment by shoulders** [comment]
Thank you.
