### ISSUE TITLE
DNS Settings - DNS Options - Included domains to allow is scrambled after save

### ISSUE THREAD

**Issue by flappadap** [virtualmin/virtualmin-gpl#935]
If you add multiple Domains, one per line in the Field DNS Settings - DNS Options "Included domains to allow" and save it and re-visit the page, the entries are scrambled and broken and parts are missing. Also the related DNS entries are broken and mixed and screwed up.
Same for field "Allowed sender mail domains" field.

**Comment by jcameron** [comment]
Can you post a screenshot showing what you mean by the page being scrambled?

**Comment by flappadap** [comment]
Unfortunately this would be difficult without exposing my domains and disrupting my DNS service, as I fixed it manually in the TXT record and when pressing save in the dialog would screw the entry.

So, I try to give a neutral example ...

In that field, I enter multiple domains, I am not sure, but this maybe occurs only if you enter many domains, I have like 15 domains there.

abrakadabra.mydomain1.com
mydomain2.de
mydomain3.org
mydomainb4.email
mydomain5.de

Then I press save in thge dialog.

After revisiting the page, the entries changed and random parts of the domains are missing, e.g it looks like :+1: 

abrakad
mydomain2.de
omain3.org
ain
mydomain5.d

This field creates a TXT entry in the DNS config file, and this one is screwed as well ... it uses " in the middle of tghe line in a way that obviously things are getting lost.

If I fix the TXT line manually in the DNS config, and go to the mentioned dialog, all shows fine. As soon as I press "save" again, it screws the TXT entry.

Cheers

**Comment by jcameron** [comment]
Ok I see the cause of this - it can happen when the list of included domains is really wrong. I'll fix it in the next Webmin release.

**Comment by flappadap** [comment]
Brilliant, thanks !
