### ISSUE TITLE
Usermin's "Create Filter" procmail filtering UI actions to save / move to "other" folders does not offer a choice of IMAP folders, unclear what syntax to use 

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#936]
Testing with VirtualMin 7.20.2 on Debian 12, I tried to create a simple server-side email filter (with Usermin 2.102) to file all mails coming from a certain bug tracker to a subfolder of the inbox folder, structured like this (as seen in Evolution):

![Screenshot from 2024-10-20 23-22-34](https://github.com/user-attachments/assets/9a81bbb7-f449-49fc-bc4f-cd57b8013aa0)

…however, Usermin's "Create Filter" GUI is not really helpful here:

![Screenshot from 2024-10-20 23-20-50](https://github.com/user-attachments/assets/9219ea1b-9dd8-46db-91b2-c2e340e758a9)

It does not show the IMAP folders I have, and the only item in the list I presume I should use is "Other file.." (sic; it should probably say "Other folder…" ?), but it does not give me any choice among available folders (which would be preferrable vs having to type them manually), and does not give me examples of valid syntax (i.e. how would a subfolder of the Inbox folder be represented in a textfield like that?)

It would be much nicer if it gave me a listview picker widget with the list of available IMAP folders in that account.

**Comment by jcameron** [comment]
That seems like a bug if existing sub-folders aren't shown. Where is the actual file for this "ticket mails" folder under your home directory?

**Comment by nekohayo** [comment]
Oh boy, I was actually looking at the wrong server / wrong account, that's why it was not showing! Since it was just showing the default standard folders in that list widget; I thought it was not going to show custom folders within that widget and that you _had_ to go through "Other file..", but it turns out that was not the case.

Testing with another account on this server, if I create a similarly-named folder under inbox, it does show up in the mail filtering actions for that mailbox.

My apologies for this false-positive!

**Comment by jcameron** [comment]
Ok glad you got it working!
