### ISSUE TITLE
6.06-02

### ISSUE THREAD

**Issue by UnleavenedEagle** [virtualmin/virtualmin-gpl#94]
Hello. I have searched literally everywhere and all I can find is the 6.06.deb file released on 10/2/2019.

Where can I find an installation file for Virtualmin GPL 6.06-02 (from 24/2/2019) in debian or Webmin module format?

I'm running on an ARM processor, and to my knowledge the Virtualmin repository for apt only supports x86, so that's not an option for me, please correct me if I'm wrong.

Thanks.

**Comment by swelljoe** [comment]
Use the apt or yum repository. Any repository of ours with `universal` in the name only contains `noarch` or `all` packages is for all architectures. Webmin and all modules, including the Virtualmin modules are pure Perl and will run on any arch.

The install script will not work on ARM systems and the packages in the OS specific repositories won't work, but the packages in the `universal` repositories will.

**Comment by UnleavenedEagle** [comment]
Thanks for the reply.
I have only managed to find this ( http://software.virtualmin.com/gpl/universal/ ) which contains rpm files. I am using Ubuntu 18.04 LTS (Bionic). This is one of the problems. The other one is that I can't find a GPG key.

**Comment by rostovtsev** [comment]
http://www.webmin.com/deb.html

**Comment by swelljoe** [comment]
I'd recommend the newer repos (though both are maintained, the VM 6 repos will be maintained for longer): http://software.virtualmin.com/vm/6/gpl/apt/

The key for the new repo is here: http://software.virtualmin.com/lib/RPM-GPG-KEY-virtualmin-6

Old repo key is in the same directory without the `-6`.

You might also be able to run the Virtualmin install script with the `--setup` flag, though I'm not sure if the architecture is checked and required to be recognized at that stage in the process.

**Comment by UnleavenedEagle** [comment]
> I'd recommend the newer repos (though both are maintained, the VM 6 repos will be maintained for longer): http://software.virtualmin.com/vm/6/gpl/apt/

`N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal InRelease' doesn't support architecture 'arm64'`

> http://www.webmin.com/deb.html
The repository linked on that page only contains Webmin, and not Virtualmin binaries.

The universal repository contains only .rpm files, and I am using Ubuntu, not CentOS.

**Comment by UnleavenedEagle** [comment]
Meanwhile 6.07 was released, so I installed that.

**Comment by UnleavenedEagle** [comment]
Meanwhile 6.07 was released, so I installed that manually from the .deb file from Webmin.com
