### ISSUE TITLE
UB24.04, LEMP Bundle, MariaDB Username Length Restricted To 16 Characters

### ISSUE THREAD

**Issue by andygmorris** [virtualmin/virtualmin-gpl#942]
My db usernames are long, based on the hosted domain name which are sometimes (ok, often) longer than 16 characters.

In the GPL UI for a Virtual Server > Edit Databases > Usernames > Change database username : I found that I could not change to a name that's longer than 16 characters.

Taking the following actions remedied the issue for me :-
- Edit file : /etc/webmin/virtual-server/config
- Add line : mysql_user_size = 80
- Restart mariadb service
- Restart webmin service
- Go back to the UI, change the db username to one with more than 16 characters (it works)

In future, someone could consider changing this file:
-  https://github.com/virtualmin/virtualmin-gpl/blob/master/feature-mysql.pl

feature-mysql.pl :-
$mysql_user_size = $config{'mysql_user_size'} || 16;
Changing the default of 16 to 80 or 128 would be an option as I believe that is/was the system default previously, however and wherever it was being set before.

Hope the above helps someone in the future.
 
System: Ubuntu 24.04, LEMP Stack, Webmin 2.202, Virtualmin 7.20.2
 
About: I have many (and have had many other hundreds of) servers using Virtualmin, since as far back as Ubuntu 16.04 - but it's the first time I've come across / noticed this issue.

**Comment by jcameron** [comment]
We actually fixed this in later versions already - if you did a fresh install of Virtualmin, it would set that `mysql_user_size` automatically to what's supported on your system.

**Comment by andygmorris** [comment]
@jcameron Good man, and thank you for the quick reply.
For reference, this install took place on 25-AUG-2024.
I'll close the Issue.
