### ISSUE TITLE
Search Mail Log - destination email - cannot filter by a custom email address

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#948]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  46 package updates are available  |

## the issue

![image](https://github.com/user-attachments/assets/b2238b8a-47c7-4951-aa9e-3ac5a35fa50a)

- you cannot type in a destination email address of your choosing.
- you can only select from a local domain or any

## feature request

Allow free type of destination address.

## related

https://github.com/virtualmin/virtualmin-gpl/issues/945

**Comment by jcameron** [comment]
Nice idea ... I'lll look into implementing this

**Comment by shoulders** [comment]
Searching by a specific date can be problematic because if you are searching for an email you probably will not know the date it was sent and if crosses time zones this can can get worse, so maybe make the date range optional.

Maybe have parity to the cpanel `Track Delivery` as shown in #945 in which case this issue should be merged.

I "used" this cpanel feature all the time to see if clients were sending me emails, if the were bounced, classed as spam or even if they have just been delivered. the information is invaluable.

**Comment by jcameron** [comment]
Good idea, I'll add this for the next release.
