### ISSUE TITLE
`Re-Check Virtualmin License` menu item is hidden but available in the search

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#952]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  31 package updates are available  |

## The issue

raised here by stefan1959 : https://forum.virtualmin.com/t/lost-virtualmin-pro-serial-number-and-licensed-key-for-education/130186

`Re-Check Virtualmin License` menu item is hidden but available in the search

![3ad492f493f6e6dc3d76d2054508bd96dd1a14b5](https://github.com/user-attachments/assets/5d0b4273-f0ed-4802-a9d6-dd69048c9cac)

![3bbdd5e21c2324177f2b980a3e55e4dedee811c1_2_690x92](https://github.com/user-attachments/assets/3998dbe3-f1cf-48d5-bce9-88628944c5e5)

## Proposed solution

Unhide this option in the menu

## Additional

Are there other menu Items that are getting hidden with HTML?

For me, menu items should not be getting hidden with HTML, but never built into the HTML in the first place. 😄

**Comment by iliajie** [comment]
Hello,

It is indeed hidden. With the upcoming changes, and an introduction of the separate "Virtualmin License Manager" page, I’d say we won’t need it at all, including making it available in the search.

I will remove it in time. Thanks for the heads up!

**Comment by shoulders** [comment]
I will closes this as it is not a bug and will be resolved in the near future anyway.
