### ISSUE TITLE
`max_spare_servers` set too high dynamically. Running out of memory.

### ISSUE THREAD

**Issue by Muffinman** [virtualmin/virtualmin-gpl#954]
Ref: https://forum.virtualmin.com/t/max-spare-servers-set-too-high-dynamically/130261

Our vhosts are filling the memory on the server with old php-fpm processes, we believe this is due to the dynamic `max_spare_servers` setting.

With this set to 8 (as it seems to be dynamically with our setup of `max_children` = 16), we are seeing very large consistent memory usage (~50GB) across as relatively small set of vhosts (~60).

Example pool file:

```
[164448877221794]
user = test
group = test
listen.owner = test
listen.group = test
listen.mode = 0660
listen = 127.0.0.1:8064
pm = dynamic
pm.max_children = 16
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 8 ; <- Far too high
php_value[upload_tmp_dir] = /home/test/tmp
php_value[session.save_path] = /home/test/tmp
php_value[log_errors] = On
php_admin_value[upload_max_filesize] = 40M
php_admin_value[post_max_size] = 40M
```

These 8x child processes per vhost really add up and in most situations do not need to be there. Unless you are expecting very high levels of traffic you never really need 8x processes on standby, 1 or 2 is nearly always sufficient and more will be spun up as needed.

From the PHP-FPM doc comments:

```
;             pm.max_spare_servers - the maximum number of children in 'idle'
;                                    state (waiting to process). If the number
;                                    of 'idle' processes is greater than this
;                                    number then some children will be killed
```

`pm.max_spare_servers` is the number of 'standby' processes that it will leave idle for each pool. If you have 8 of these using ~100mb each for every pool file then it quickly causes a memory issue.

In my opinion it should not be tied to `pm.max_children` at all, it would be far better suited to a static value, many guides advise setting this to the same as `pm.start_servers`.

P.S. One option is to reduce the `pm.max_children` setting for every vhost, however we've found that 16 is the sweet spot (for us) to allow for traffic bursts while protecting the server from too much load overall.

**Comment by Muffinman** [comment]
Thanks, I did not know it was possible to override in that `options` config!

I still disagree that leaving 8 threads idle per vhost is a good idea, but happy that we have found a good solution that works for those with my use case!

**Comment by iliajie** [comment]
> I still disagree that leaving 8 threads idle per vhost is a good idea

This value needs to be dynamic. How much RAM does your server have?

**Comment by Muffinman** [comment]
Our server which had the issue has 64GB RAM.

I've restarted all my FPM processes now but at the time of reporting it was using around ~50GB of this on mostly idle FPM processes.

I did have a lot more vhosts that I remembered on this server, I just counted the individual pool files and it's actually 119.

119 * 8 * 100MB = ~95GB memory to have all pools sitting with 8 idle threads assuming an average of 100MB each.

After changing all pool files to `pm.max_spare_servers` = 2, the memory usage has settled like this and is no longer growing:

![Screenshot 2024-11-07 at 11 09 26](https://github.com/user-attachments/assets/206b0d94-1d2e-4984-86de-7fafdc863f1e)

```
root@myserver ~# ps aux | grep php-fpm | wc -l
226
```

I don't believe there is a noticeable performance difference to having less idle threads unless you're dealing with bursts of 10s req/s on a single pool, but then again I have not done any benchmarks to confirm this.

**Comment by iliajie** [comment]
I think you’re trying to micromanage the system’s memory usage — that’s the kernel’s job! I’d only be concerned if the OOM killer got involved. And yes, for 64 GB of RAM, setting `pm.max_spare_servers` to `8` is generally fine.

I agree, though, that it can vary, which is why we provide the option to override it using templates.

**Comment by stefan1959** [comment]
That override doesn't seem to work for me. I set it to 4 but when I create a new server it still set to 5.
Have you tested on your system?
![image](https://github.com/user-attachments/assets/8c16f54b-8947-4f3e-9688-a7eb34a372ba)
![image](https://github.com/user-attachments/assets/05100597-bf2d-4e89-9e51-addd94fa3607)

**Comment by iliajie** [comment]
I'll look into this bug more closely and get back to you later today. Thanks!

**Comment by iliajie** [comment]
Thanks, I took a closer look and found a bug.

You can apply this patch to your system and try again:

```
webmin patch https://github.com/virtualmin/virtualmin-gpl/commit/c0f36b9
```

**Comment by stefan1959** [comment]
Working as expected now thanks.

**Comment by iliajie** [comment]
Thank you for your feedback!
