### ISSUE TITLE
Feature request:  User Email page: Mark As Spam

### ISSUE THREAD

**Issue by Ramoonus** [virtualmin/virtualmin-gpl#963]
it`s not possible in the :10000/mailboxes/list_mail.cgi file, to select a bunch of emails and mark them as spam all in 1 go

**Comment by iliajie** [comment]
Hello,

It’s possible, but only for one page at a time. You can select multiple emails by holding Shift while clicking a range of checkboxes.

**Comment by Ramoonus** [comment]
selecting is possible, but where can i report them as spam, i don`t see a button/dropdown for that?

**Comment by iliajie** [comment]
> in my opinion, Show spam reporting buttons for | Mailboxes, should be enabled by default

Alright, agreed. We’ll set it to display by default on all new installations.
