### ISSUE TITLE
Global features are being disabled even though domains have them enabled

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#966]
Hey Jamie!

I just discovered a particularly nasty bug! The issue is straightforward: if a feature is disabled on the "System Settings ⇾ Features and Plugins" page (e.g., DNS), but some domains on the system have that feature enabled, Virtualmin does show an error message. However, the Virtualmin configuration file in `/etc/webmin/virtual-server/config` file still disables the feature globally (e.g., `dns=0`).

This issue also occurs with other features I tested, like `web` or `ssl`.

This is a serious bug that needs to be fixed right away. We should include the fix in version 7.30.0.

**Comment by jcameron** [comment]
Let me know if the commit I just attached to this bug helps..

**Comment by iliajie** [comment]
Excellent! That patch worked as expected! However, a similar issue still present with the plugins! It has to be addressed too!

**Comment by jcameron** [comment]
Do you mean that a plugin can be disabled globally even when it's still in use by a domain? Is there no error at all, or does it get saved even though an error is shown?

**Comment by iliajie** [comment]
Yes, plugin can be disabled globally when it’s still in use by a domain! I think error wasn’t shown either.

**Comment by iliajie** [comment]
Excellent, everything works as expected now!
