### ISSUE TITLE
MariaDB 11.4 LTS and above / Incompatible due to deprecated internal paths

### ISSUE THREAD

**Issue by SIP-Online** [virtualmin/virtualmin-gpl#968]
OS: Debian 12
MariaDB Server Repositories: https://mariadb.org/download/?t=repo-config&d=Debian+12+%22Bookworm%22&v=11.4&r_m=ovh

Since MariaDB **11.4 LTS**, command executions containing MySQL have become obsolete.

I am currently in version **11.6**, but no MySQL files are present anymore, this means that after installing Virtualmin, no management is possible for your databases.
**Fortunately, you just have to modify the internal paths of the commands, to have the complete management of MariaDB, see the screenshot below**:
![mariadb_11 6_lts_incompatible_deprecated_paths](https://github.com/user-attachments/assets/83672433-0917-4d3d-91ae-4de61687a284)

This is therefore not an emergency, but a report for the next versions of Webmin and especially Virtuamin.

**Comment by SIP-Online** [comment]
Small update, the current **LTS** version (**23/11/2024**) is not ### 11.6 but version **11.4**.
So I reinstalled, and this version gives the same result, no more commands containing mysql.

I will edit the title of this issue right away. 😉

**Comment by jcameron** [comment]
So they've completely renamed the commands from `mysql` to `mariadb` ?

**Comment by iliajie** [comment]
> So they've completely renamed the commands from `mysql` to `mariadb` ?

Yes, and it’s not very clear how to support it using the module config file. We’ll probably need to handle it internally somehow.

**Comment by SIP-Online** [comment]
> So they've completely renamed the commands from `mysql` to `mariadb` ?

That's right.
For example for **mysqldump** it is no longer present, so you have to type this command: **mariadb-dump**

This is from the official MariaDB repository, however, Debian (so also Fork like Ubuntu) seems to have implemented a patch in their build to keep these few names on version 11.4.3: https://packages.debian.org/fr/trixie/amd64/mariadb-client/filelist
This is still a version in preparation, we will know more by the release of Debian version 13.

**Comment by iliajie** [comment]
We can easily fix it in the module itself.

**Comment by jcameron** [comment]
Yeah we could have Webmin be smarter about finding the `mysql` / `mariadb` or `mariadb-dump` commands.

**Comment by iliajie** [comment]
> Yeah we could have Webmin be smarter about finding the `mysql` / `mariadb` or `mariadb-dump` commands.

Alright, implemented here https://github.com/webmin/webmin/pull/2320.
