### ISSUE TITLE
software.virtualmin.com not working 

### ISSUE THREAD

**Issue by munishsehgal** [virtualmin/virtualmin-gpl#969]
wget http://software.virtualmin.com/gpl/scripts/install.sh
show connecting and stuck 

----------------------------------------------------------------
ubuntu@ip-172-26-2-134:~$ wget http://software.virtualmin.com/gpl/scripts/install.sh
--2024-11-27 08:30:59--  http://software.virtualmin.com/gpl/scripts/install.sh
Resolving software.virtualmin.com (software.virtualmin.com)... 2001:bc8:608:b01::1, 51.158
.66.131
Connecting to software.virtualmin.com (software.virtualmin.com)|2001:bc8:608:b01::1|:80...

**Comment by iliajie** [comment]
Hello,

Yes, we’re aware of the issue—the web server went down. Unfortunately, I don’t have access to that server, so we’ll have to wait for Joe to wake up to fix it.

**Comment by HansHM** [comment]
As we can see this is a long term problem.

Still no body how can reboot the server? It is down for hours.

**Comment by iliajie** [comment]
It has been fixed! Sorry about that!
