### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [virtualmin/virtualmin-gpl#97]
It is possible to migrate the personal account to organization?
- https://help.github.com/articles/converting-a-user-into-an-organization/

It will be more professional ^^
And you could also have all softs in only one FREE organization too.
-> https://help.github.com/en/articles/differences-between-user-and-organization-accounts

And for move webmin repositories to virtualmin: https://help.github.com/en/articles/transferring-a-repository

@jcameron, @rostovtsev, @swelljoe, @webmin, @usermin, @virtualmin: Any news guys after 1,5 years?
All projects in one organization?

Linked to https://github.com/webmin/webmin/issues/876.

**Comment by Neustradamus** [comment]
@jcameron, @rostovtsev, @swelljoe, @webmin, @usermin, @virtualmin: Any news?
- It is not done ;)

All projects in one organization?

Linked to:
- https://github.com/webmin/webmin/issues/876

**Comment by rostovtsev** [comment]
Apparently, Jamie doesn't want to invest time in it. Personally, I don't see any much difference, even though Authentic Theme is under organisation.

What makes you have such great concern about it? What difference will it make, in your opinion, for us and most importantly for our users?

**Comment by swelljoe** [comment]
Y'all can shut up about this now.

**Comment by Neustradamus** [comment]
@jcameron, @rostovtsev, @swelljoe, @webmin, @usermin, @virtualmin: Any news?

Currently, I think that the Virtualmin company has not good people in team!

I am very sad.

I see that take 5mn to do all is very complicated.

**Comment by iliarostovtsev** [comment]
Okay, we moved Virtualmin to an organisation.

> Currently, I think that the Virtualmin company has not good people in team

Please don't be offended, we all may be impatient sometimes.

Thank you for your idea, initially.

**Comment by chris001** [comment]
Looks nicer as an organization now!
Now, just need to add the key people to [the people page](https://github.com/orgs/virtualmin/people) !!
Obviously add @jcameron @swelljoe @iliarostovtsev (and possibly @gnadelwartz ?)

**Comment by Neustradamus** [comment]
@iliarostovtsev: Thanks for your message and the information!

Please note that : Your colleague @swelljoe told me "shut up" and nothing more.

To be perfect:

Now you can do same for:
- https://github.com/usermin
- https://github.com/webmin

Now you can transfer in this organization:
- https://github.com/webmin/webmin
- https://github.com/webmin/usermin

Thanks to listen me.

**Comment by swelljoe** [comment]
@Neustradamus you ignored multiple polite "no" responses, and multiple polite requests to stop reopening the ticket and opening more tickets. So I stopped being polite. You were rude as hell first, I responded in kind.

Virtualmin has been migrated to an organization for our own reasons and in my own time, but this is mostly volunteer labor. Unless you're offering to pay for our time to do things the way you want them done, please stop making demands.

**Comment by Neustradamus** [comment]
@swelljoe: Thanks for this change :)

I have said you that I would like to do it, it is easy and take 5mn for all steps.

All steps have not done, I have published previously (edited with some details).

Virtualmin is now on the good road ^^

PS : I need to do new tickets for the move of webmin and usermin repositories and the convertion webmin and usermin accounts to organization?

**Comment by swelljoe** [comment]
Please don't. If we have time, we will eventually get around to it. You have already made a tick for Webmin (which is where Usermin would go). Making another one, or demanding more attention when we have already made our position on this clear would be extremely rude, bordering on abusive, and will not encourage action.

**Comment by Neustradamus** [comment]
It is normal to inform and have a ticket about problems or improvements.
Without, it is easy to forget...

I have not done tickets about transfer to this organization...

Only about convert to organization (badly already closed but not done usermin and webmin are always personal accounts)

And I have informed about website security problem:
- https://github.com/webmin/webmin/issues/1090

**Comment by swelljoe** [comment]
No, please stop. The organization discussion is over. We will convert Webmin to an organization when Jamie has time and inclination, there is already a ticket for it. Literally nothing you can say or do will change that, so stop badgering. It is rude.

Also, don't change the subject to unrelated issues. There's a ticket for it, as well.
