### ISSUE TITLE
Websocket Proxy not working with Firefox

### ISSUE THREAD

**Issue by danielr0815** [virtualmin/virtualmin-gpl#972]
I created a sub-server and activated a proxy path to forward all traffic incl. Websockets to a docker container.
If I open the webpage with Firefox, I see the following message in the developer console:

> Firefox can’t establish a connection to the server at wss://test.domainname.de/api/v1/ws

I found in the Web-Developer tools in Firefox, that the Request header Connection is not only filled with “Upgrade”: 
> Connection: keep-alive, Upgrade

So I think we have to replace

`RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]` by
`RewriteCond %{HTTP:CONNECTION} Upgrade [NC]`

to get websockets running also in Firefox.

**Comment by jcameron** [comment]
Thanks! We'll fix this in the next release ..
