### ISSUE TITLE
Add support for testing connectivity before installing (aka dry run) and provide a report (ex.: required network changes)

### ISSUE THREAD

**Issue by marclaporte** [virtualmin/virtualmin-gpl#975]
We often install WikiSuite (and thus Virtualmin) behind the firewall. This is not the usual shared hosting use case, but I believe Virtualmin can grow a lot here. Many organizations have thousands of servers, and a GUI like Virtualmin is super useful.

The IT department will supply us a fresh install of the OS we request. It is not uncommon that the installation fails for networking issues.
* IPv4 vs IPv6
* Download sources not accessible
* etc.

It can fail at different steps. And we can end up with a partially installed OS. In these cases, we need to ask the IT department to:
* Change something related to the network (all requests at once so we don't need to repeat the process)
* Re-install the server with a minimal install (Ex.: Debian 12) to make sure we start clean.

There was an attempt to add checks but it was reverted: https://gitlab.com/wikisuite/wikisuite-packages/-/merge_requests/73, and instead this added: 

- https://gitlab.com/wikisuite/wikisuite-packages/-/commit/f11abe5d49d2739c2079ebb2c230dd9a0b142b2e
- https://gitlab.com/wikisuite/wikisuite-packages/-/commit/8fb2e8ad413b378d2afd12b24fc0bb5a190fe938
- https://gitlab.com/wikisuite/wikisuite-packages/-/commit/8117afcf171132fd7945c75641c8156efea81f0e

So now we have a smoother process. We can run the test which supplies all the info (if any) we need to provide to the IT department before attempting an installation.

I realize the behind-the-firewall use case is not so common for Virtualmin, but we have also seen issues with IPv6 support on rented dedicated servers. So I think this would be a good idea to do directly in Webmin/Virtualmin. I would even argue this should run automatically for all installations (like a pre-flight checklist) and if there are issues, abort with a useful error message. Failing early with a nice error message is better than later without a clear error message (it is in the logs, but still). But I understand the concern about adding complexity for infrequent use cases.

What do you think?

**Comment by iliajie** [comment]
> I would even argue this should run automatically for all installations (like a pre-flight checklist) and if there are issues, abort with a useful error message. Failing early with a nice error message is better than later without a clear error message (it is in the logs, but still).

@jcameron @swelljoe To be clear—I asked Marc to create this ticket to get your opinion on whether we should integrate my `test_connection()` sub linked above into the `virtualmin-install.sh` script for a so-called pre-flight check.

I’m undecided about it.

**Comment by jcameron** [comment]
I think it wouldn't be a bad idea to do a network test before starting the install process. It could be pretty simple, just a check that software.virtualmin.com can be resolved and accessed..

**Comment by iliajie** [comment]
Cool! I’ll do it. Something like this:

<img width="930" alt="image" src="https://github.com/user-attachments/assets/5e056f3b-459b-453c-b3db-e431ed86cf28">

But without GitHub in our case.

**Comment by iliajie** [comment]
> I think it wouldn't be a bad idea to do a network test before starting the install process. It could be pretty simple, just a check that software.virtualmin.com can be resolved and accessed..

Implemented here https://github.com/virtualmin/virtualmin-install/commit/367515f6759b05317ea9c46cb453a9cede7ca9f4.

<img width="491" alt="image" src="https://github.com/user-attachments/assets/3c84a672-703a-4a1c-94dc-c72b6614e200">

**Comment by iliajie** [comment]
Implemented.
