### ISSUE TITLE
Virtualmin settings to also backup - puyt on a seperate Tab

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#977]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  88 package updates are available  |

## background

![image](https://github.com/user-attachments/assets/5a15d016-d929-4caa-a53d-914b31d5189c)

when you backup virtual servers you have the option of backing up virtualmin settings (in my opinion these should be handled elsewhere  😄 ).

## the issue

the location of these settings is not logical and depending on whether you have horizontal or vertical set on authentic theme this location can also move.

## proposed solution

It would be fairly easy to move these settings into their open accordion tab

![image](https://github.com/user-attachments/assets/c85206ab-5f20-408f-9931-f239173a07d9)

**Comment by jcameron** [comment]
Can you attach a screenshot showing the current full illogical location?

**Comment by shoulders** [comment]
the whole backup page is dedicated to backing up virtual servers but randomly the backup for virtualmin settings is just bolted in. 

Because these settings are not virtual server related they should not be on this page, but at very least they should have their own accordian.

### Vertical

![vertical](https://github.com/user-attachments/assets/208f9833-2e09-4b99-9a0e-4d84632b9169)


### Horizontal

![horizontal](https://github.com/user-attachments/assets/1b061466-a36e-4492-9a4d-7c5b2fac5f78)

**Comment by jcameron** [comment]
Thanks! We'll fix this..

**Comment by shoulders** [comment]
Perfect, thanks.

**Comment by shoulders** [comment]
@jcameron I think you fixed this with commit `d555508` above, should this be closed or is it waiting for more coding?

**Comment by iliajie** [comment]
> @jcameron I think you fixed this with commit `d555508` above, should this be closed or is it waiting for more coding?

What about having the restore page and "Global Settings" in a separate tab?

**Comment by jcameron** [comment]
No I think we're good now!

**Comment by iliajie** [comment]
But I don’t think we are, because the restore page is now inconsistent with the create backup page...

**Comment by jcameron** [comment]
Oh sorry I missed that this was about the restore page! I'll fix that too..

**Comment by iliajie** [comment]
> Oh sorry I missed that this was about the restore page! I'll fix that too..

Great! Thanks!
