### ISSUE TITLE
Feature reset for website and PHP

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#984]
Hello Jamie,

When trying to reset Apache website feature, like this:

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/a8948086-c4dd-4653-9cf7-eb7850d8bc3f" />

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/c0a672de-a0a9-4f68-8173-c65ca12b1bb7" />

This break!

If template has FPM set as execution mode, and FPM is a current mode for the domain, then after reset PHP-FPM service isn't getting restarted and things don't work, until FPM is manually restarted.

If template has FCGI configured, and FPM is a current mode for the domain, then things are not configured correctly at all, and even server reboot doesn't fix the problem. This is how Apache config looks like after reset feature was applied in FCGI set on the template:

<img width="1083" alt="image" src="https://github.com/user-attachments/assets/7e2a2331-8232-4a0a-97a6-3d8f97fed883" />

Now, check what happens after the toggle.

And this is how it looks when the mode is toggled first to FPM and then back to FCGI on "PHP Options" page:

<img width="983" alt="image" src="https://github.com/user-attachments/assets/b00eae65-b47a-4e9f-a909-44dd7729ec2a" />

---

When tried with Nginx nothing happens at all, no configs changed. Also, Apache is displayed on Nginx system in "Features to reset" multi-select filed.

**Comment by jcameron** [comment]
Let me know if this patch fixes the issue for you on Apache : https://github.com/virtualmin/virtualmin-gpl/commit/84aafe82a4b578fc1023f27cd319e13a999aafc8

**Comment by iliajie** [comment]
> Let me know if this patch fixes the issue for you on Apache : [84aafe8](https://github.com/virtualmin/virtualmin-gpl/commit/84aafe82a4b578fc1023f27cd319e13a999aafc8)

Okay, great! It does solve the main issues with Apache!

However, the Nginx reset still doesn't work.

And the other small issue that that Apache is still displayed on "Features to reset" select on Nginx systems.

**Comment by jcameron** [comment]
I'll fix that issue of Apache being shown on the reset form on Nginx systems.

However, when I try a test Nginx reset it works fine for me!

**Comment by iliajie** [comment]
> I'll fix that issue of Apache being shown on the reset form on Nginx systems.

Thanks!

> However, when I try a test Nginx reset it works fine for me!

Can you share a screenshot of the page after a reset on an Nginx system?

**Comment by jcameron** [comment]
Well I did it with the `reset-feature` API command, which printed out messages showing the Nginx website was removed and re-added.

**Comment by jcameron** [comment]
Oh crap it doesn't work in the UI! Checking in a fix for that now..

**Comment by iliajie** [comment]
All good except when trying to reset Nginx and/with Nginx SSL it returns a wrong error message:

<img width="1019" alt="image" src="https://github.com/user-attachments/assets/99e915df-a15f-40e3-84f4-7d96555f9c49" />

**Comment by jcameron** [comment]
Ah ok, I just checked in a fix for that

**Comment by iliajie** [comment]
> Ah ok, I just checked in a fix for that

Thanks, but it breaks SSL site, i.e. it's never reset back, e.g.:

<img width="1143" alt="image" src="https://github.com/user-attachments/assets/47fa863a-fad3-4bb4-920c-6a287cca1dfd" />

**Comment by jcameron** [comment]
Hmm, that works for me. Can you post the output from the reset process? I get this : 

![image](https://github.com/user-attachments/assets/01a009cc-7dd9-4b02-8571-f88ec246a7ee)

**Comment by iliajie** [comment]
It also works for me, if I _do not_ select "Fully reset by turning features on and off?" option.

The output is here, if "Fully reset by turning features on and off?" option is set to "Yes":

<img width="1020" alt="image" src="https://github.com/user-attachments/assets/24ec5d54-5050-420e-82f8-6442088a89b6" />

**Comment by jcameron** [comment]
Oh and it looks like the same bug exists for Apache SSL websites!

**Comment by iliajie** [comment]
Ah, I see. You’ve added some patches to address it. However, there was still some code missing.

Addressed here:

[virtualmin/virtualmin-gpl@6b160f9]( https://github.com/virtualmin/virtualmin-gpl/commit/6b160f9f270375a6053f3716593f904c152fdd3d)
[virtualmin/virtualmin-nginx@512bcb1](https://github.com/virtualmin/virtualmin-nginx/commit/512bcb13729ab3053d98269f4361f09da6be975e)

**Comment by jcameron** [comment]
Thanks for those patches! That's exactly what I was going to write ..

**Comment by iliajie** [comment]
> Thanks for those patches! That's exactly what I was going to write ..

You're welcome—good to know! I have cherry-picked them for the 7.30.3.
