### ISSUE TITLE
Minor grammar correction

### ISSUE THREAD

**Issue by Deepcuts** [virtualmin/virtualmin-gpl#985]
Virtualmin version: 7.30.2 Pro 

Under **Email Settings/Email Server Owners** the text should be **Also email _users_ in selected domains?** instead of **Also email _userd_ in selected domains?** 

![image](https://github.com/user-attachments/assets/844d7ff7-313f-48fd-9509-771f0ef28a52)

**Comment by jcameron** [comment]
thanks!
