### ISSUE TITLE
Unable to list virtual servers by creation date

### ISSUE THREAD

**Issue by vincegre** [virtualmin/virtualmin-gpl#991]
Hi

Running Virtualmin 7.30.3 Pro, I can get a list of all virtual servers on the machine (Virtualmin -> List Virtual servers) but I can't sort them by creation date.

The creation date columns sort by first field (in my case being in Europe it's the day) while it should adapt at LOCAL and sort properly per year, then month then day ;)

Thanks

Vincèn

**Comment by iliajie** [comment]
Hello,

Thanks for the heads-up!

It should be fixed now! Please apply the following patches and let me know if they solve the problem for you:


```
webmin patch https://github.com/webmin/webmin/commit/07da92a
webmin patch https://github.com/webmin/authentic-theme/commit/6933ed5
```

Merry Christmas!

**Comment by vincegre** [comment]
> It should be fixed now! Please apply the following patches and let me know if they solve the problem for you:

@iliajie Thanks a lot for that very quick fix that works perfect :)

Merry christmas ;)
